### ISSUE TITLE
secretflow支持多方(大于三方)PSI和机器学习建模吗

### ISSUE THREAD

**Issue by huyz1117** [secretflow/secretflow#100]
### Issue Type

Others

### Source

source

### Secretflow Version

secretflow0.6

### OS Platform and Distribution

Centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
请问secretflow支持大于三方clients之间隐私求交以及机器学习建模吗？谢谢
```

### Reproduction code to reproduce the issue.

```shell
请问secretflow支持大于三方clients之间隐私求交以及机器学习建模吗？谢谢
```

**Comment by pchyuan** [comment]
secretflow支持多种算法，包括：
（1）MPC（可证安全）的建模：目前支持了三方/多方LR，稍晚些时候会支持三方/多方XGB
（2）PSI：目前主要是两方的PSI，预计在今年11月份支持多方PSI
（3）联邦学习（非可证安全）的建模：目前已经支持水平多方XGB，稍晚些会发布水平LR算法，另外还有一些NN算法，部分已经支持，原则上也是可以多方参与的

**Comment by icavan** [comment]
> ### Issue Type
> Others
> 
> ### Source
> source
> 
> ### Secretflow Version
> secretflow0.6
> 
> ### OS Platform and Distribution
> Centos7
> 
> ### Python version
> 3.8
> 
> ### Bazel version
> _No response_
> 
> ### GCC/Compiler version
> _No response_
> 
> ### What happend and What you expected to happen.
> ```shell
> 请问secretflow支持大于三方clients之间隐私求交以及机器学习建模吗？谢谢
> ```
> 
> ### Reproduction code to reproduce the issue.
> ```shell
> 请问secretflow支持大于三方clients之间隐私求交以及机器学习建模吗？谢谢
> ```

It's a bit complicated now.

For PSI, we now only support 2pc & 3pc PSI. Usually, there are two ways to implement an NPC PSI. One is to reuse existing 2pc PSI repeatedly to get the final NPC PSI results. Of course, such method is considered a fake NPC PSI (most existing frameworks choose this way). Another way is to use an actual NPC PSI, which might be slower than the fake one. Secretflow now supports a real 3pc PSI and several SOTA 2pc PSIs. We're working on adding a real NPC PSI. Please wait for it in the future.

For the training part, it depends on which algorithm you adopt. Say, FedAVG does support multiparty naturally. However, Cheetah focuses on 2PC only now. While if you choose the outsourcing mode of MPC, the computation is independent of the data providers. This means you get the capability to support multiparty training if outsourcing MPC mode works for you.
