### ISSUE TITLE
在 SecretFlow 中实现简单场景下两方拆分 DCN 算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#1004]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- **任务名称**：在 SecretFlow 中实现简单场景下两方拆分 DCN 算法
- **技术方向**：FL/application
- **任务难度**：进阶🌟🌟
- **任务期望完成时间**：4-5 周

## 详细要求
- 安全性：尽量降低数据、模型泄露的可能
- 功能性：在 SecretFlow 中实现两方拆分版本的 DCN 算法，参考论文[Deep & Cross Network for Ad Click Predictions](https://arxiv.org/abs/1708.05123)。
- 收敛性：跑出实验数据并且证明收敛性
- 特征交叉：双方特征可以各自交叉，特征全局交叉是挑战性要求
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 框架后端：实现 PyTorch 版本。若在完成 PyTorch 版本实现的基础上同步进行 TensorFlow 版本实现将额外累积一颗🌟
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/secretflow/tree/main/secretflow/ml/nn/applications

## 能力要求
- 了解基本 git 操作
- 熟悉 深度学习、联邦学习
- 对 SecretFlow 有一定了解

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/sl_rec_deepfm
- 范例：https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/applications/sl_bst_torch.py

**Comment by reacher1130** [comment]
reacher1130  Give it to me

**Comment by Candicepan** [comment]
> reacher1130 Give it to me

hello～该任务完成过程中是否有什么问题呢 可以在 issue 上直接反馈哈。也可以添加小助手微信：SecretFlow04 进行沟通 加入 OSCP 专属群聊哈
