### ISSUE TITLE
在 SecretFlow 中实现狄利克雷数据集拆分方法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#1008]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- **任务名称**：在 SecretFlow 中实现狄利克雷数据集拆分方法
- **技术方向**：FL/application
- **任务难度**：进阶🌟🌟
- **任务期望时间**：4-5周

## 详细要求
- 安全性：尽量降低数据、模型泄露的可能
- 功能性：在 SecretFlow 中实现狄利克雷数据划分方法，参考论文[Federated multi-task learning under a mixture of distributions](https://arxiv.org/pdf/2108.10252.pdf)。
- 有效性：跑出实验数据并且验证拆分逻辑正确性
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 框架后端：尽量使用jax.numpy实现。
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/secretflow/tree/main/secretflow/ml/nn/utils

## 能力要求
- 了解基本 git 操作
- 熟悉 深度学习、联邦学习
- 对 SecretFlow 有一定了解

## 操作说明
- 多语言操作说明：https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md

**Comment by Chi-Kai** [comment]
在 https://github.com/secretflow/secretflow/blob/main/secretflow/utils/simulation/data/_utils.py 中已经包含有狄利特雷划分方法，是否还需要实现？如果需要的话，应该解耦到什么程度，比如函数的参数有什么要求？

**Comment by Candicepan** [comment]
> 在 https://github.com/secretflow/secretflow/blob/main/secretflow/utils/simulation/data/_utils.py 中已经包含有狄利特雷划分方法，是否还需要实现？如果需要的话，应该解耦到什么程度，比如函数的参数有什么要求？

感谢认领哈～该任务已经完成实现，即上方链接的实现方式，暂时必须再进行解耦啦～感谢您的支持。也欢迎认领其他相关任务呀
