### ISSUE TITLE
请问有使用cheetah的代码demo吗？

### ISSUE THREAD

**Issue by JunZ2364139375** [secretflow/secretflow#101]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow 0.6

### OS Platform and Distribution

Linux ubuntu20.04

### Python version

3.8

### What happend and What you expected to happen.

```shell
如题
```

### Reproduction code to reproduce the issue.

```shell
找了很久的文档也没找到相关代码。
```

**Comment by 6fj** [comment]
Hi @JunZ2364139375 ，

我们并没有使用cheetach的demo，当前spu device支持多种密态协议，你只需要在init spu device的时候在runtime config中选择cheetah协议即可。

请参考：https://github.com/secretflow/spu/issues/11

感谢。
