### ISSUE TITLE
从source加载环境出错

### ISSUE THREAD

**Issue by iven-j** [secretflow/secretflow#1020]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

SecretFlow: 1.2.0.dev20231025

### OS Platform and Distribution

linux ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
通过源码构建虚拟环境时，运行
python setup.py bdist_wheel

pip install dist/*.whl
时报错
```

### Reproduction code to reproduce the issue.

```shell
python setup.py bdist_wheel

pip install dist/*.whl
Requirements:  ['#', '# FEATURE=[lite] is a specific comment, indicating that this dependency will be', '# used as a dependency of secretflow-lite.', '#', '# Avoid thead pool fork issue, see https://github.com/grpc/grpc/issues/31772', 'clean-text  # FEATURE=[lite]', 'click  # FEATURE=[lite]', 'grpcio==1.56.2   # FEATURE=[lite]', 'jax<=0.4.12  # FEATURE=[lite]', 'jaxlib<=0.4.12  # FEATURE=[lite]', 'kuscia==0.0.2.dev231013  # FEATURE=[lite]', 'multiprocess  # FEATURE=[lite]', 'networkx==2.8.8', 'numba==0.57.0  # FEATURE=[lite]', 'numpy==1.23.5  # FEATURE=[lite]', '# TODO: onnx and tensorflow have dependency conflicts, waiting for upstream to resolve', '# onnx==1.13.1', 'pandas==1.5.3  # FEATURE=[lite]', '# For security reason.', 'protobuf==3.19.6  # FEATURE=[lite]', 'pyarrow==11.0.0  # FEATURE=[lite]', 's3fs==2022.1.0', 'scikit-learn==1.1.3  # FEATURE=[lite]', 'sdc-apis==0.1.0b0; platform_system != "Darwin"  # FEATURE=[lite]', 'sdc-sdk==0.1.0b0; platform_system != "Darwin"  # FEATURE=[lite]', 'secretflow-rayfed==0.2.0a7 # FEATURE=[lite]', '# For security reason. This is introduced by TensorFlow.', 'setuptools>=65.5.1', 'sparse>=0.14.0', 'spu==0.6.0.dev20231023  # FEATURE=[lite]', 'sf-heu==0.4.4b0  # FEATURE=[lite]', 'tensorflow-macos==2.11.0; platform_machine == "arm64" and platform_system == "Darwin"', 'tensorflow==2.11.1; platform_machine != "arm64"', 'tf2onnx>=1.13.0', 'tqdm', 'validator.py==1.3.0', 'xgboost==1.7.5', '# For security reason.', 'wheel>=0.38.1', 'torch==2.0.0', 'torchmetrics==0.11.4', 'torchvision==0.15.1', 'torchaudio==2.0.1']
Dependency:  ['--extra-index-url https://download.pytorch.org/whl/cpu']
running bdist_wheel
running build
running build_py
copying secretflow/version.py -> build/lib.linux-x86_64-cpython-38/secretflow
copying secretflow/ml/nn/fl/backend/torch/strategy/fed_avg_wt.py -> build/lib.linux-x86_64-cpython-38/secretflow/ml/nn/fl/backend/torch/strategy
running build_ext
bazel build //secretflow_lib/binding:_lib.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --compilation_mode=opt --config=avx
error: command 'bazel' failed: No such file or directory
WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
```

**Comment by Mingbo-Lee** [comment]
```
error: command 'bazel' failed: No such file or directory
```
从报错来看，你可能需要确认你已经安装了 bazel

**Comment by zhouaihui** [comment]
secretfllow安装脚本涉及到C++的编译，需要安装相关工具链。如果嫌麻烦，可以使用镜像 secretflow/release-ci:latest 编译

**Comment by iven-j** [comment]
安装bazel之后安装还是失败，报错如下：
Target //secretflow_lib/binding:_lib.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.874s, Critical Path: 0.62s
INFO: 38 processes: 38 internal.
FAILED: Build did NOT complete successfully
error: command '/usr/local/bin/bazel' failed with exit code 1

**Comment by iven-j** [comment]
> Hi @iven-j
> 
> 能提供一下完整的日志吗
日志是这个吗？

_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library cpu_features

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow
BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log
PWD=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/wrapper_build_script.sh
BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc
TMPDIR=/tmp
EXT_BUILD_DEPS=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.ext_build_deps
BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a
BUILD_TMPDIR=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.build_tmpdir
SHLVL=2
INSTALLDIR=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features
PATH=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow:/home/iven/.vscode-server/bin/d037ac076cee195194f93ce6fe2bdfe2969cc82d/bin/remote-cli:/home/iven/miniconda3/envs/sfs/bin:/home/iven/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
_=/usr/bin/env
__________________________
+ cmake -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features -DCMAKE_PREFIX_PATH=/home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /home/iven/.cache/bazel/_bazel_iven/484a00d1994ab6e484ca60cd99b94c8a/sandbox/linux-sandbox/147/execroot/secretflow/external/com_github_google_cpu_features
bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/build_script.sh: line 72: cmake: command not found
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log

Target //secretflow_lib/binding:_lib.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.874s, Critical Path: 0.62s
INFO: 38 processes: 38 internal.
FAILED: Build did NOT complete successfully

**Comment by anakinxc** [comment]
`cmake: command not found`

需要安装一下 cmake，你可以照着[这里](https://www.secretflow.org.cn/docs/quickstart/mfbgum8vi3ngs4y9#hPJ96) 看看还缺什么依赖

**Comment by iven-j** [comment]
安装成功了，谢谢答疑
