### ISSUE TITLE
HEU计算

### ISSUE THREAD

**Issue by elina825** [secretflow/secretflow#1023]
secretflow中如何进行同态的指数运算，即一个同态密文与一个明文的指数之间的指数运算

**Comment by usafchn** [comment]
您好，目前 secretflow 仅支持半同态，幂运算本质是要计算`密文*密文`，这个能力当前还不支持。

**Comment by usafchn** [comment]
@elina825  您好，secretflow 目前无法满足需求，如果你愿意的话，可以加 wx secretflow02 技术支持号，我们可以拉上各方向专家在线语音聊一下其它替代方案
