### ISSUE TITLE
环境变量配置了TLS再sf.init后提示 OPENSSL_internal:WRONG_VERSION_NUMBER.

### ISSUE THREAD

**Issue by mingo0117** [secretflow/secretflow#103]
### Issue Type

Others

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

centos7.6

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
ray集群初始化成功后，执行sf.init后一直提示：
E0831 18:08:29.837200777    1118 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0831 18:08:30.843064656    1118 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0831 18:08:31.848803082    1118 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.


求助，谢谢！
```

### Reproduction code to reproduce the issue.

```shell
代码示例：
os.environ["RAY_USE_TLS"] = "1"
os.environ["RAY_TLS_SERVER_CERT"] = "/xxx/server.crt"
os.environ["RAY_TLS_SERVER_KEY"] = "/xxx/server.key"
os.environ["RAY_TLS_CA_CERT"] = "/xxx/ca.crt"
sf.init(address=kwargs["initAddr"], _redis_password=kwargs["redisPassword"])

证书是通过KeyManager工具生成的测试证书
```

**Comment by zhouaihui** [comment]
参考下 #40 ，检查下证书。
https://github.com/secretflow/secretflow/issues/40#issuecomment-1188691381

**Comment by mingo0117** [comment]
您好，我这边三台计算节点都是内网环境，内网ip和dns如下：
![image](https://user-images.githubusercontent.com/29568891/187821967-f7e8888c-d3be-4639-8ec8-fbb25e34a87d.png)
![image](https://user-images.githubusercontent.com/29568891/187822329-f741f97d-729a-4268-bc9c-0030d0c32ac5.png)

感觉之前问题可能出在alternate_names（之前用的一个假域名，没有设置过本机ip）。爬楼看了下教程，按教程完整走了一遍
![image](https://user-images.githubusercontent.com/29568891/187821725-1de2e222-45fd-4f18-8333-dd46c227b14c.png)
标红这块我的设置是：
[ alternate_names ]
DNS.1  = 8.8.8.8
# IPv4 localhost
IP.1   = 10.100.82.173
# IPv6 localhost
IP.2   = ::1

但很不幸依然是同样的报错，不确定是哪里的问题（TLS关闭是ok的）

> 参考下 #40 ，检查下证书。 [#40 (comment)](https://github.com/secretflow/secretflow/issues/40#issuecomment-1188691381)

**Comment by SongGuyang** [comment]
@mingo0117 能把你的pem证书贴出来吗？

**Comment by mingo0117** [comment]
> @mingo0117 能把你的pem证书贴出来吗？

[pem.zip](https://github.com/secretflow/secretflow/files/9475595/pem.zip)

劳烦看下，参考的https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority/21340898

**Comment by SongGuyang** [comment]
> os.environ["RAY_USE_TLS"] = "1"
os.environ["RAY_TLS_SERVER_CERT"] = "/xxx/server.crt"
os.environ["RAY_TLS_SERVER_KEY"] = "/xxx/server.key"
os.environ["RAY_TLS_CA_CERT"] = "/xxx/ca.crt"

会不会是这套环境变量只配置到了一台机器上？我看你们是个三节点的测试？确认下三台机器都配置试试呢？

**Comment by zhouaihui** [comment]
另外，记得执行sf.init也需要设置环境变量。
