### ISSUE TITLE
pad平台新增组件问题

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#1031]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.8.0

### What happend and What you expected to happen.

```shell
2023-11-14 16:36:16 INFO the jobId=chah, taskId=chah-lhysccye-node-5 start ...
2023-11-14 16:40:42 INFO the jobId=chah, taskId=chah-lhysccye-node-5 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "FileNotFoundError: [Errno 2] No such file or directory: 'b'
2023-11-14 08:40:00,406\tERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \x1b[36mray::SPURuntime.del_share()\x1b[39m (pid=1628, ip=chah-lhysccye-node-5-0-global.alice.svc, repr=SPURuntime(device_id=None, party=alice))
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: \x1b[36mray::SPURuntime.load()\x1b[39m (pid=1628, ip=chah-lhysccye-node-5-0-global.alice.svc, repr=SPURuntime(device_id=None, party=alice))
  File \"/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py\", line 458, in load
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'b'
2023-11-14 08:40:00,408\tERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \x1b[36mray::SPURuntime.del_share()\x1b[39m (pid=1628, ip=chah-lhysccye-node-5-0-global.alice.svc, repr=SPURuntime(device_id=None, party=alice))
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: \x1b[36mray::SPURuntime.load()\x1b[39m (pid=1628, ip=chah-lhysccye-node-5-0-global.alice.svc, repr=SPURuntime(device_id=None, party=alice))
  File \"/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py\", line 458, in load
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'a'
PC: @     0x7f66c2e10d96  (unknown)  do_futex_wait.constprop.1
    @     0x7f66c2e12ce0  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2023-11-14 08:40:00,494 E 7 7] logging.cc:361: *** SIGTERM received at time=1699951200 on cpu 12 ***
[2023-11-14 08:40:00,494 E 7 7] logging.cc:361: PC: @     0x7f66c2e10d96  (unknown)  do_futex_wait.constprop.1
[2023-11-14 08:40:00,494 E 7 7] logging.cc:361:     @     0x7f66c2e12ce0  (unknown)  (unknown)
[2023-11-14 08:40:00,494 E 7 7] logging.cc:361:     @ ... and at least 1 more frames
2023-11-14 08:40:00 INFO cleanup.py:77 [alice] --  Notify check sending thread to exit.
"
2023-11-14 16:40:42 INFO the jobId=chah, taskId=chah-lhysccye-node-5 failed: The remaining non-failed parties counts 1 is less than the task success threshold 2
```

### Reproduction code to reproduce the issue.

```shell
# 训练模型
    sl_model.fit(
        input_df,  # 训练数据
        label_col,  # 标签列
        epochs=epochs,  # 训练轮数
        batch_size=batch_size,  # 批大小
        shuffle=shuffle,  # 是否打乱数据
        verbose=0,  # 是否打印日志
        dp_spent_step_freq=10,  # 差分隐私步频率
    )

    model_meta = {"parties_num": parties_num,
    "loss_type": loss_type,
    "sig_type": output_sig_type
    }

    # 获得SPUObject
    spuo = []
    for name in secure_device.actors.keys():
        spuo.append(secure_device.load(name))

    # 输出模型
    model_db = model_dumps(
        "Split_neural",
        DistDataType.NN_MODEL,
        MODEL_MAX_MAJOR_VERSION,
        MODEL_MAX_MINOR_VERSION,
        spuo,
        json.dumps(model_meta),
        local_fs_wd,
        output_model,
        input_data.sys_info,
    )
    return {"output_model": model_db}

我想做一个pad种的拆分学习组件，在训练模型的阶段应该是没问题，现在是使用dumps输出模型的时候出现了问题
```

**Comment by mtl802** [comment]
![6bc51eecda9cf90bbc92026549a8f47](https://github.com/secretflow/secretflow/assets/20579710/553e8615-f314-4d26-b9c5-05270bbc713f)
![9cf9d7b15405e9e2693fabd0531b7a0](https://github.com/secretflow/secretflow/assets/20579710/ae1d480a-adec-4d45-a31d-469621968654)

**Comment by 6fj** [comment]
local_fs_wd 和 output_model 的内容是什么？

**Comment by mtl802** [comment]
@6fj 
![image](https://github.com/secretflow/secretflow/assets/20579710/7e671825-fbe3-4f85-ad43-b91fa30061fb)

![image](https://github.com/secretflow/secretflow/assets/20579710/ed05c6ff-b796-4b1e-be82-01a868d6bc48)
分别如上

local_fs_wd和outputmodel可以得到文件需要存储的位置和文件名

**Comment by mtl802** [comment]
也许是我SPUObject的问题，昨天看了文档，我的理解SPUObject是一个从本地明文传递到SPU的数据，对这个数据加密之后变成了SPUObject。
所以我的问题就是：当前的这个SPUObject解密后仅仅只是一个'alice'或者是'bob'的字符串，导致了这个错误。

然后我对模型进行了保存，保存格式为h5，传递了h5这个模型的权重到SPU，再次运行之后发现无限循环，既不报错也不输出。
![image](https://github.com/secretflow/secretflow/assets/20579710/44250b78-d598-44df-83af-a66fbfc3bdca)

**Comment by 6fj** [comment]
> @6fj ![image](https://user-images.githubusercontent.com/20579710/283289273-7e671825-fbe3-4f85-ad43-b91fa30061fb.png)
> 
> ![image](https://user-images.githubusercontent.com/20579710/283289297-ed05c6ff-b796-4b1e-be82-01a868d6bc48.png) 分别如上
> 
> local_fs_wd和outputmodel可以得到文件需要存储的位置和文件名

从你的输出看起来local_fs_wd里面是空的，所以找不到‘a’这个文件

**Comment by mtl802** [comment]
for i, obj in enumerate(spuo):
    uri = f"{output_model}/{i}"
    spu_path = os.path.join(local_fs_wd, uri)

所以在输出时得到了
![1700103131254](https://github.com/secretflow/secretflow/assets/20579710/ac6ffa69-902d-4ca5-b463-d80712cd1e96)

我是根据SS_SGD组件来写的这个拆分学习的组件，里面local_fs_wd和outputmodel就是如上定义，也没有别的操作

**Comment by 6fj** [comment]
可以有一份可以复现问题的最小集代码吗？

**Comment by mtl802** [comment]
def split_learning_eval_fn(
        *,
        ctx,
        label_num,
        hidden_units,
        hidden_sig_type,
        output_sig_type,
        loss_type,
        epochs,
        batch_size,
        shuffle,
        input_data,
        input_data_feature_selects,
        output_model,
):
    input_df = load_table(
        ctx,
        input_data,
        load_features=True,
        feature_selects=input_data_feature_selects,
        load_labels=True,
    )

    local_fs_wd = ctx.local_fs_wd
    input_info = extract_table_header(input_data, load_labels=True)

    assert len(input_info) == 1, "only support one party has label"
    label_party = next(iter(input_info.keys()))
    smeta = input_info[label_party]
    assert len(smeta) == 1, "only support one label col"
    label_name = next(iter(smeta.keys()))
    label_col = input_df[label_name]

    if ctx.spu_configs is None or len(ctx.spu_configs) == 0:
        raise CompEvalError("spu config is not found.")
    if len(ctx.spu_configs) > 1:
        raise CompEvalError("only support one spu")
    spu_config = next(iter(ctx.spu_configs.values()))
    secure_device = SPU(spu_config["cluster_def"], spu_config["link_desc"])

    定义了了两个本地模型并分发
    创建差分隐私字典
    定义了融合模型
    
    创建拆分学习模型并训练，拆分模型为 sl_model

    //保存模型
    sl_model.save_model(base_model_path="./base_model.h5",
                        fuse_model_path="./fuze_model.h5",
                        is_test=True,
                        save_traces=True,
                        save_format="h5")
    
    //加载融合模型权重
    from keras.models import load_model
    import secretflow as sf
    model = load_model('./fuze_model.h5')
    weights = model.get_weights()
    
    spuo = sf.to(pyus[0], weights).to(secure_device)

    model_db = model_dumps(
        "Split_neural",
        DistDataType.SL_MODEL,
        MODEL_MAX_MAJOR_VERSION,
        MODEL_MAX_MINOR_VERSION,
        [spuo],
        json.dumps(model_meta),
        local_fs_wd,
        output_model,
        input_data.sys_info,
    )

    //输出模型



@6fj

**Comment by mtl802** [comment]
record/event.go:285 Event(v1.ObjectReference{Kind:"Pod", Namespace:"alice", Name:"evjd-lhysccye-node-4-0", UID:"ca9d6ee2-2699-40a2-b5e6-c26c164d5b57", APIVersion:"v1", ResourceVersion:"7327430", FieldPath:""}): type: 'Warning' reason: 'MissingClusterDNS' pod: "evjd-lhysccye-node-4-0_alice(ca9d6ee2-2699-40a2-b5e6-c26c164d5b57)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.

我在查看docke日志的时候看到了这个，有关系吗

**Comment by longshan-ant** [comment]
> record/event.go:285 Event(v1.ObjectReference{Kind:"Pod", Namespace:"alice", Name:"evjd-lhysccye-node-4-0", UID:"ca9d6ee2-2699-40a2-b5e6-c26c164d5b57", APIVersion:"v1", ResourceVersion:"7327430", FieldPath:""}): type: 'Warning' reason: 'MissingClusterDNS' pod: "evjd-lhysccye-node-4-0_alice(ca9d6ee2-2699-40a2-b5e6-c26c164d5b57)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
> 
> 我在查看docke日志的时候看到了这个，有关系吗

这个没关系的，这个只是日志级别不对， 不影响任务正常运行。

**Comment by mtl802** [comment]
> > record/event.go:285 Event(v1.ObjectReference{Kind:"Pod", Namespace:"alice", Name:"evjd-lhysccye-node-4-0", UID:"ca9d6ee2-2699-40a2-b5e6-c26c164d5b57", APIVersion:"v1", ResourceVersion:"7327430", FieldPath:""}): type: 'Warning' reason: 'MissingClusterDNS' pod: "evjd-lhysccye-node-4-0_alice(ca9d6ee2-2699-40a2-b5e6-c26c164d5b57)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
> > 我在查看docke日志的时候看到了这个，有关系吗
> 
> 这个没关系的，这个只是日志级别不对， 不影响任务正常运行。

好的，谢谢

**Comment by mtl802** [comment]
> def split_learning_eval_fn( *, ctx, label_num, hidden_units, hidden_sig_type, output_sig_type, loss_type, epochs, batch_size, shuffle, input_data, input_data_feature_selects, output_model, ): input_df = load_table( ctx, input_data, load_features=True, feature_selects=input_data_feature_selects, load_labels=True, )
> 
> ```
> local_fs_wd = ctx.local_fs_wd
> input_info = extract_table_header(input_data, load_labels=True)
> 
> assert len(input_info) == 1, "only support one party has label"
> label_party = next(iter(input_info.keys()))
> smeta = input_info[label_party]
> assert len(smeta) == 1, "only support one label col"
> label_name = next(iter(smeta.keys()))
> label_col = input_df[label_name]
> 
> if ctx.spu_configs is None or len(ctx.spu_configs) == 0:
>     raise CompEvalError("spu config is not found.")
> if len(ctx.spu_configs) > 1:
>     raise CompEvalError("only support one spu")
> spu_config = next(iter(ctx.spu_configs.values()))
> secure_device = SPU(spu_config["cluster_def"], spu_config["link_desc"])
> 
> 定义了了两个本地模型并分发
> 创建差分隐私字典
> 定义了融合模型
> 
> 创建拆分学习模型并训练，拆分模型为 sl_model
> 
> //保存模型
> sl_model.save_model(base_model_path="./base_model.h5",
>                     fuse_model_path="./fuze_model.h5",
>                     is_test=True,
>                     save_traces=True,
>                     save_format="h5")
> 
> //加载融合模型权重
> from keras.models import load_model
> import secretflow as sf
> model = load_model('./fuze_model.h5')
> weights = model.get_weights()
> 
> spuo = sf.to(pyus[0], weights).to(secure_device)
> 
> model_db = model_dumps(
>     "Split_neural",
>     DistDataType.SL_MODEL,
>     MODEL_MAX_MAJOR_VERSION,
>     MODEL_MAX_MINOR_VERSION,
>     [spuo],
>     json.dumps(model_meta),
>     local_fs_wd,
>     output_model,
>     input_data.sys_info,
> )
> 
> //输出模型
> ```
> 
> @6fj

# 获取parties的PYU信息
    pyus = []
    for py in input_df.partitions:
        pyus.append(py)
    parties_num = len(pyus)

**Comment by mtl802** [comment]
如果我在模型训练完毕后就return：
sl_model.fit(
        input_df,  # 训练数据
        label_col,  # 标签列
        epochs=epochs,  # 训练轮数
        batch_size=batch_size,  # 批大小
        shuffle=shuffle,  # 是否打乱数据
        verbose=0,  # 是否打印日志
        dp_spent_step_freq=10,  # 差分隐私步频率
    )

  return {"output_model": sl_model}

则显示：
![image](https://github.com/secretflow/secretflow/assets/20579710/e7b208e4-5d49-4c1f-b760-44d2088266f1)

**Comment by mtl802** [comment]
我的PYU信息是从联合表获得，应该没有问题吧
![image](https://github.com/secretflow/secretflow/assets/20579710/15cd6748-95dc-44cc-8af3-68fc6984c83a)

**Comment by mtl802** [comment]
目前还有一个问题，就是组件输入的是联合表，我创建了一个组件输入参数，可以确定需要训练的特征，我想根据每个PYU设备去找到他们参与训练数据的PYUObject，这个应该怎么做呢

**Comment by mtl802** [comment]
我又试着修改了一下，如果把spuo改为spuo = sf.to(pyus[i], 10)之后就能分发到每个pyu节点。可能这个没问题，应该在weights上面。我又试着修改了代码，发现我的模型又无法保存，也不知道是不是训练失败的问题
![image](https://github.com/secretflow/secretflow/assets/20579710/0199885f-c5cf-431f-abb1-01c3eceacfea)

**Comment by 6fj** [comment]
看上去是说路径有问题

**Comment by mtl802** [comment]
sl_model.save_model(base_model_path="./base_model.h5",
                    fuse_model_path="./fuze_model.h5",
                    is_test=True,
                    save_traces=True,
                    save_format="h5")
但是这个函数是没变的，我在找文档的过程中也没找到save函数的详细介绍，不知道他具体保存的路径

**Comment by mtl802** [comment]
![image](https://github.com/secretflow/secretflow/assets/20579710/1c55a8ca-1937-4b80-8ac5-608664f50944)
目前的模型应该是可以训练的，能够看到模型的历史信息，问题应该还是出现在模型的保存上

**Comment by mtl802** [comment]
> 看上去是说路径有问题

或者说有没有什么别的办法能够保存这个模型的权重呢，或者说可以将模型直接变成SPUObject

**Comment by 6fj** [comment]
所以你的需求是把一个keras h5 模型文件转化为一个 spu object保存下来？

**Comment by mtl802** [comment]
> 所以你的需求是把一个keras h5 模型文件转化为一个 spu object保存下来？

我是打算把训练完成的模型使用model_dumps传给每个节点，他需要的一个关键参数是object，也就是SPUObject，我试过让slmodel直接转换但是失败了。所以我只能想到的办法就是保存了拆分学习模型之后再使用model.get_weights()获得模型权重，这个就能转换为SPUObject，进而使用model_dumps。所以目前的需求现情况应该是这样

**Comment by 6fj** [comment]
请问 

`weights = model.get_weights()` 中 `weights`是什么类型呢？

**Comment by mtl802** [comment]
[array([[-0.11728375,  0.04082072, -0.05575036, ...,  0.08589619,
         0.04919533,  0.11328789],
       [-0.10003126, -0.09035872,  0.09462692, ..., -0.13041785,
         0.02697525, -0.01480567],
       [ 0.10932262, -0.12064468,  0.14453122, ..., -0.07112716,
         0.06031131,  0.04064548],
       ...,
       [ 0.12170521, -0.00625538, -0.02091132, ...,  0.00050653,
        -0.01638593,  0.06132013],
       [-0.05191369,  0.07199504,  0.01229825, ..., -0.05051134,
        -0.12694111,  0.14001432],
       [-0.18008551, -0.13311976,  0.09148663, ..., -0.09754428,
        -0.1649577 , -0.04145094]], dtype=float32), array([-0.02674481, -0.02405856, -0.02320719, -0.01968795, -0.02728567,
        0.03756308,  0.02860747,  0.02784394,  0.02579685,  0.02737107,
        0.02735861, -0.02373364, -0.02365649, -0.02385873,  0.0295868 ,
        0.02713919, -0.02589113, -0.02544468,  0.02583385, -0.02268114,
       -0.0235868 , -0.02210285,  0.02550967,  0.0252287 ,  0.02725226,
        0.02861634, -0.0206597 ,  0.02709648, -0.02360615, -0.02502923,
       -0.02206768,  0.02708757,  0.02775904,  0.02592006, -0.02419286,
        0.02783041,  0.03064599, -0.02645572, -0.01964748, -0.02248635,
        0.0269279 , -0.02367317, -0.02577271, -0.02404513,  0.0251532 ,
        0.0348644 ,  0.02840746, -0.02616413, -0.02445984,  0.02634072,
       -0.02462471,  0.02735244, -0.01291458, -0.02332176,  0.02843037,
        0.02479439,  0.02619162,  0.02663833, -0.0221936 ,  0.02586692,
       -0.02067187, -0.02612911, -0.02432823, -0.02383043], dtype=float32), array([[ 6.97541535e-02],
       [ 1.55806333e-01],
       [ 1.61648110e-01],
       [-3.76909913e-04],
       [ 8.29363093e-02],
       [-4.10608649e-02],
       [-1.29996285e-01],
       [-7.88343325e-02],
       [-1.88139021e-01],
       [-1.58817157e-01],
       [-1.57961935e-01],
       [ 1.33640230e-01],
       [ 2.47109726e-01],
       [ 6.27042353e-02],
       [-1.46588609e-01],
       [-3.07753831e-01],
       [ 4.27182280e-02],
       [ 1.02784269e-01],
       [-1.34567529e-01],
       [ 7.01942891e-02],
       [ 2.48114571e-01],
       [ 8.64478201e-02],
       [-1.22673906e-01],
       [-5.49712181e-02],
       [-2.64697105e-01],
       [-1.49282202e-01],
       [ 9.89099592e-03],
       [-3.21215719e-01],
       [ 2.74240315e-01],
       [ 1.36753127e-01],
       [ 1.74416870e-01],
       [-2.24018618e-01],
       [-2.69089490e-01],
       [-1.32238954e-01],
       [ 2.75868684e-01],
       [-5.21940887e-02],
       [-3.11996359e-02],
       [ 6.37137964e-02],
       [-1.39296782e-04],
       [ 1.77017733e-01],
       [-2.25745335e-01],
       [ 1.63050637e-01],
       [ 1.65993616e-01],
       [ 2.38483265e-01],
       [-2.70915121e-01],
       [-6.51320219e-02],
       [-3.02408487e-01],
       [ 2.13656887e-01],
       [ 1.20839328e-01],
       [-3.59836332e-02],
       [ 1.14498086e-01],
       [-1.52286813e-01],
       [-1.31315608e-02],
       [ 1.42118454e-01],
       [-1.56118065e-01],
       [-2.79718131e-01],
       [-1.77279860e-01],
       [-3.25455427e-01],
       [ 2.73944717e-02],
       [-2.39809841e-01],
       [ 1.26484498e-01],
       [ 5.92756271e-02],
       [ 2.51928657e-01],
       [ 1.27673715e-01]], dtype=float32), array([-0.02627196], dtype=float32)]
<class 'list'>

@6fj 一个list

**Comment by mtl802** [comment]
这个是我在本地跑出来的，在组件中使用会找不到.h5的文件

**Comment by 6fj** [comment]
看上去是一个array list，这个应该是可以转成spu object的。所以原理是没有问题的。你先试着将
`
model = load_model('./fuze_model.h5')
weights = model.get_weights()

spuo = sf.to(pyus[0], weights).to(secure_device)
`
中的`spuo` `dump` 再 `load`试一下能不能成功。

这部分逻辑可以参考 [`secretflow.component.data_utils.model_dumps`](https://github.com/secretflow/secretflow/blob/main/secretflow/component/data_utils.py#L407-L419) 和 [`secretflow.component.data_utils.model_loads`](https://github.com/secretflow/secretflow/blob/main/secretflow/component/data_utils.py#L495-L510)

**Comment by 6fj** [comment]
> 这个是我在本地跑出来的，在组件中使用会找不到.h5的文件

这个听上去是个小问题，你把拼出来的完整路径打一下吧

**Comment by mtl802** [comment]
sl_model.save_model(base_model_path="./base_model.h5",
                        fuse_model_path="./fuze_model.h5",
                        is_test=True,
                        save_traces=True,
                        save_format="h5")
                        
我的完整代码就是这个，因为我本来是不打算找到他真实存储的位置，只要我能使用load加载出模型并获得权重信息就可以。

from keras.models import load_model
    import secretflow as sf

    model = load_model('./fuze_model.h5')
    weights = model.get_weights()

但是我测试了多次，一直是无法找到fuze_model.h5

**Comment by 6fj** [comment]
嗯 组件里面的路径都是storage config + uri，所以组合在一起就是绝对路径

**Comment by mtl802** [comment]
正常情况下，我使用model.save
sl_model.save_model(base_model_path="./base_model.h5",
fuse_model_path="./fuze_model.h5",
is_test=True,
save_traces=True,
save_format="h5")

base_model_path保存的位置应该是在alice或bob：/home/kuscia/var/storage/data路径下。但是model.save这个代码应该是执行的，但是我的路径下是没有.h5文件的。

fuse_model_path的路径是'./fuze_model.h5'，load的路径正常也应该找得到'./fuze_model.h5'，但是提示无法找到
fuse_model_path应该是保存在master容器中的吧

**Comment by mtl802** [comment]
而且我如果不中断执行，他的训练流会一直执行，不会报错也不会成功
model = load_model('./fuze_model.h5')
    weights = model.get_weights()

    print("--------weights:")
    print(weights)

    assert 1==2, "--------pass"

只要在这里终止，他就会提示无法找到fuze_model.h5

**Comment by 6fj** [comment]
> 正常情况下，我使用model.save sl_model.save_model(base_model_path="./base_model.h5", fuse_model_path="./fuze_model.h5", is_test=True, save_traces=True, save_format="h5")
> 
> base_model_path保存的位置应该是在alice或bob：/home/kuscia/var/storage/data路径下。但是model.save这个代码应该是执行的，但是我的路径下是没有.h5文件的。
> 
> fuse_model_path的路径是'./fuze_model.h5'，load的路径正常也应该找得到'./fuze_model.h5'，但是提示无法找到 fuse_model_path应该是保存在master容器中的吧

ray是lazy

**Comment by mtl802** [comment]
![image](https://github.com/secretflow/secretflow/assets/20579710/6d0c9dff-6da9-479f-87ce-eda8f043a599)
@6fj 多次尝试目前还是同一个问题，我在测试的时候只把一个为int类型的10传递是可以的，都能收到。目前的情况还是在文件上

**Comment by mtl802** [comment]
> > def split_learning_eval_fn( *, ctx, label_num, hidden_units, hidden_sig_type, output_sig_type, loss_type, epochs, batch_size, shuffle, input_data, input_data_feature_selects, output_model, ): input_df = load_table( ctx, input_data, load_features=True, feature_selects=input_data_feature_selects, load_labels=True, )
> > ```
> > local_fs_wd = ctx.local_fs_wd
> > input_info = extract_table_header(input_data, load_labels=True)
> > 
> > assert len(input_info) == 1, "only support one party has label"
> > label_party = next(iter(input_info.keys()))
> > smeta = input_info[label_party]
> > assert len(smeta) == 1, "only support one label col"
> > label_name = next(iter(smeta.keys()))
> > label_col = input_df[label_name]
> > 
> > if ctx.spu_configs is None or len(ctx.spu_configs) == 0:
> >     raise CompEvalError("spu config is not found.")
> > if len(ctx.spu_configs) > 1:
> >     raise CompEvalError("only support one spu")
> > spu_config = next(iter(ctx.spu_configs.values()))
> > secure_device = SPU(spu_config["cluster_def"], spu_config["link_desc"])
> > 
> > 定义了了两个本地模型并分发
> > 创建差分隐私字典
> > 定义了融合模型
> > 
> > 创建拆分学习模型并训练，拆分模型为 sl_model
> > 
> > //保存模型
> > sl_model.save_model(base_model_path="./base_model.h5",
> >                     fuse_model_path="./fuze_model.h5",
> >                     is_test=True,
> >                     save_traces=True,
> >                     save_format="h5")
> > 
> > //加载融合模型权重
> > from keras.models import load_model
> > import secretflow as sf
> > model = load_model('./fuze_model.h5')
> > weights = model.get_weights()
> > 
> > spuo = sf.to(pyus[0], weights).to(secure_device)
> > 
> > model_db = model_dumps(
> >     "Split_neural",
> >     DistDataType.SL_MODEL,
> >     MODEL_MAX_MAJOR_VERSION,
> >     MODEL_MAX_MINOR_VERSION,
> >     [spuo],
> >     json.dumps(model_meta),
> >     local_fs_wd,
> >     output_model,
> >     input_data.sys_info,
> > )
> > 
> > //输出模型
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @6fj
> 
> # 获取parties的PYU信息
> ```
> pyus = []
> for py in input_df.partitions:
>     pyus.append(py)
> parties_num = len(pyus)
> ```

这个定义模型之前的代码我在测试时候好像也报错，但是在这个组件没问题
![ed5d4100d7096e8123a8cca22afc1ea](https://github.com/secretflow/secretflow/assets/20579710/79375cb7-bd3e-40a6-b83b-839e57cd3286)
