### ISSUE TITLE
在连续调用纵向xgb执行流程时，第一次能执行成功，第二次卡在 heu = sf.HEU(heu_config, spu_config['runtime_config']['field'])

### ISSUE THREAD

**Issue by chuchaochen** [secretflow/secretflow#1035]
### Issue Type

Bug

### Source

source

### Secretflow Version

secretflow-1.1.0.dev230828

### OS Platform and Distribution

Linux ubuntu 18.04

### Python version

3.8.1

### Bazel version

6.2.1

### GCC/Compiler version

11.4

### What happend and What you expected to happen.

```shell
我基于secretflow和grpc.aios实现了联邦服务，服务接收客户端消息，然后根据消息执行两方的纵向xgb任务。现在第一次执行能成功，第一次执行完成后开始第二次执行的时候会卡在“heu = sf.HEU(heu_config, spu_config['runtime_config']['field'])”。通过加日志分析，总结来说在连续第二次执行的时候会出现两个现象：
1、流程会卡在“heu = sf.HEU(heu_config, spu_config['runtime_config']['field'])”；
2、通过日志跟踪，发现在secretflow的init方法中，执行fed.init的时候会发生重复执行（fed.init之前不会重复执行，从fed.init开始重复执行，包括fed.init内的语句也是重复执行）
```

### Reproduction code to reproduce the issue.

```shell
1、def sf_init(self, spu_flag=None, heu_flag=None):
        """
        初始化secretflow，如果有spu或者heu的配置，则直接返回
        @param spu_flag: 是否需要spu设置，默认没有
        @param heu_flag: 是否需要heu设置，默认没有
        @return:
        """
        # 获取本地的IP
        localhost = get_localhost()
        # 获取sf配置
        cluster_config, spu_config, heu_config, tls_config, header_metadata = self._set_config()
        log.info("--------------------------cluster_config:{}".format(cluster_config))
        log.info("--------------------------spu_config:{}".format(spu_config))
        log.info("--------------------------heu_config:{}".format(heu_config))
        log.info("--------------------------header_metadata:{}".format(header_metadata))
        log.info("cluster init beginning:{}".format(gp.ray_head_port))
        try:
            sf.init(address="{}:{}".format(localhost, gp.ray_head_port),
                    cluster_config=cluster_config,
                    #tls_config=tls_config,
                    cross_silo_comm_backend="grpc",
                    cross_silo_comm_options={
                        "exit_on_sending_failure": False,
                        "messages_max_size_in_bytes": 2 * 1024 * 1024 * 1024,
                        "http_header": header_metadata
                    })
            log.info("cluster init AFTER")
            #gp.ray_head_port = gp.ray_head_port +101
        except Exception as e:
            log.info("sf init failed")
            log.info("sf init failed ,e:{}".format(str(e)))
        log.info("cluster init success")
        cluster_config = None
        header_metadata = None
        if spu_flag and heu_flag:
            return spu_config, heu_config
        elif spu_flag:
            return spu_config
        elif heu_flag:
            return heu_config
        else:
            pass
这是我调用sf.init的代码，在第二次运行过程中“log.info("--------------------------cluster_config:{}".format(cluster_config))
        log.info("--------------------------spu_config:{}".format(spu_config))
        log.info("--------------------------heu_config:{}".format(heu_config))
        log.info("--------------------------header_metadata:{}".format(header_metadata))
        log.info("cluster init beginning:{}".format(gp.ray_head_port))”均打印一次，从“log.info("cluster init AFTER")”开始打印两次。

2、def _set_connect(self):
        """
        初始化secretflow，在vertical xgboost中，需要初始化cluster、SPU、HEU以及TLS
        :return: HEU配置
        """
        log.info("####################start _set_connect")
        spu_config, heu_config = self.sf_init(spu_flag=True,
                                              heu_flag=True)
        log.info("_set_connect spu_config:{}".format(spu_config))
        log.info("_set_connect heu_config:{}".format(heu_config))
        heu = None
        try:
            heu = sf.HEU(heu_config, spu_config['runtime_config']['field'])
        except Exception as e:
            log.info("$$$$$$$$$$$$$$$$$$$$$$$$")
            log.info("&&&&&&&&&&&&exception:{}".format(str(e)))
        # sf.init(address="{}:6677".format(localhost), cluster_config=cluster_config, tls_config=tls_config)
        return heu
这是我调用HEU的地方，在第二次执行的过程中，卡在了heu = sf.HEU(heu_config, spu_config['runtime_config']['field'])。
```

**Comment by warriorpaw** [comment]
在同一个进程内再次执行 sf.init 前，需要先执行 sf.shutdown 。也不能有多个sf.init 并行执行。

**Comment by chuchaochen** [comment]
> 在同一个进程内再次执行 sf.init 前，需要先执行 sf.shutdown 。也不能有多个sf.init 并行执行。

我有sf.shutdown。我发现是因为我两次连续执行时，用的party不同，导致了第二次执行的时候heu初始化失败。第一次执行的时party是Bob，第二次执行的时候是Bob2。有办法切换吗？

**Comment by usafchn** [comment]
@chuchaochen 你可以把两次运行的  cluster_config, heu_config 都贴一下吗

**Comment by chuchaochen** [comment]
> @chuchaochen 你可以把两次运行的 cluster_config, heu_config 都贴一下吗
第一次运行：
cluster_config:
{'parties': {'cd6429617a87431bb55aae0d0708bcc7_P1123598818738675223': {'address': '192.168.200.192:8555'}, 'cd6429617a87431bb55aae0d0708bcc7_P1123598818738675225': {'address': '172.17.0.5:6678'}}, 'self_party': 'cd6429617a87431bb55aae0d0708bcc7_P1123598818738675225'}
heu_config:
{'sk_keeper': {'party': 'cd6429617a87431bb55aae0d0708bcc7_P1123598818738675223'}, 'evaluators': [{'party': 'cd6429617a87431bb55aae0d0708bcc7_P1123598818738675225'}], 'mode': 'PHEU', 'he_parameters': {'schema': 'ou', 'key_pair': {'generate': {'bit_size': 2048}}}, 'encoding': {'cleartext_type': 'DT_I32', 'encoder': 'IntegerEncoder', 'encoder_args': {'scale': 1}}}


第二次运行：
cluster_config:
{'parties': {'a4c7cd42cdde434896fbe289b9ec19ea_P1123598818738675223': {'address': '172.17.0.13:6678'}, 'a4c7cd42cdde434896fbe289b9ec19ea_P1123598818738675225': {'address': '192.168.200.210:8555'}}, 'self_party': 'a4c7cd42cdde434896fbe289b9ec19ea_P1123598818738675223'}
heu_config:
{'sk_keeper': {'party': 'a4c7cd42cdde434896fbe289b9ec19ea_P1123598818738675223'}, 'evaluators': [{'party': 'a4c7cd42cdde434896fbe289b9ec19ea_P1123598818738675225'}], 'mode': 'PHEU', 'he_parameters': {'schema': 'ou', 'key_pair': {'generate': {'bit_size': 2048}}}, 'encoding': {'cleartext_type': 'DT_I32', 'encoder': 'IntegerEncoder', 'encoder_args': {'scale': 1}}}

**Comment by zhouaihui** [comment]
@chuchaochen ，可以把两方的代码和运行时日志都发一下吗？

**Comment by da-niao-dan** [comment]
你好，提供如何调用 sf_init 和_set_connect 的代码有助于我们复现

**Comment by da-niao-dan** [comment]
另外第二次调用前网络是否联通可以ping一下测试

**Comment by chuchaochen** [comment]
把rayfed中的config.py做如下修改就行
def get_cluster_config():
    """This function is not thread safe to use."""
    global _cluster_config
    if _cluster_config is None:
        compatible_utils._init_internal_kv()
        compatible_utils.kv.initialize()
    raw_dict = compatible_utils.kv.get(fed_constants.KEY_OF_CLUSTER_CONFIG)
    _cluster_config = ClusterConfig(raw_dict)
    return _cluster_config


def get_job_config():
    """This config still acts like cluster config for now"""
    global _job_config
    if _job_config is None:
        compatible_utils._init_internal_kv()
        compatible_utils.kv.initialize()
    raw_dict = compatible_utils.kv.get(fed_constants.KEY_OF_JOB_CONFIG)
    _job_config = JobConfig(raw_dict)
    return _job_config

**Comment by chuchaochen** [comment]
把raw_dict = compatible_utils.kv.get(fed_constants.KEY_OF_CLUSTER_CONFIG)
_cluster_config = ClusterConfig(raw_dict)写在if语句的外面

**Comment by chuchaochen** [comment]
在rayfed的config.py中修改get_cluster_config和get_job_config方法，如下：
把raw_dict = compatible_utils.kv.get(fed_constants.KEY_OF_CLUSTER_CONFIG)
_cluster_config = ClusterConfig(raw_dict)写在if语句的外面

**Comment by da-niao-dan** [comment]
就解决这个问题了？

**Comment by chuchaochen** [comment]
> 就解决这个问题了？

是的，可以接收到新的参与方名称，正常识别sk_keeper，完成heu的初始化，后续的流程也能正常进行
