### ISSUE TITLE
SLModel的torch backend是否支持GPU运算

### ISSUE THREAD

**Issue by iven-j** [secretflow/secretflow#1038]
### Issue Type

Others

### Source

binary

### Secretflow Version

SecretFlow: 1.2.0.dev20231025

### OS Platform and Distribution

linux ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在尝试跑example里面的test_sl_model_parties.py，试着在sf.init里加入num_gpu，但是还是没有使用gpu
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by zhangxingmeng** [comment]
slmodel 的torch 暂时还不支持gpu计算。后续版本会开放支持

**Comment by iven-j** [comment]
好的谢谢
