### ISSUE TITLE
我们现在是通过api交付数据的，怎么使用隐语交付，都没看到相关的案例

### ISSUE THREAD

**Issue by chenxuezhi1986** [secretflow/secretflow#1039]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
我们现在是通过api交付数据的，怎么使用隐语交付，都没看到相关的案例
```

### Reproduction code to reproduce the issue.

```shell
我们现在是通过api交付数据的，怎么使用隐语交付，都没看到相关的案例
```

**Comment by 6fj** [comment]
hi @chenxuezhi1986 

能描述一下你说的交付数据是什么含义吗？

**Comment by john8628** [comment]
@6fj 支持离线训练好的模型；直接通过http接口传入参数，调用模型使用吗？

**Comment by 6fj** [comment]
可以通过调用kuscia api的方式进行离线预测。
