### ISSUE TITLE
DataFrame是否可以从hdfs中聚合数据？

### ISSUE THREAD

**Issue by cs1317** [secretflow/secretflow#104]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

mac

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
DataFrame是否可以从hdfs中聚合数据，还是必须得从csv文件中聚合？如果可以，能否提供hdfs聚合数据的代码？
```

### Reproduction code to reproduce the issue.

```shell
aggr=SecureAggregator(device=alice,participants=[alice,bob])
spu=sf.SPU(sf.utils.testing.cluster_def(parties=['alice','bob']))
comp=SPUComparator(spu)
hdf=read_csv({alice:h_alice_path,bob:h_bob_path},aggregator=aggr,comparator=comp)
```

**Comment by zhouaihui** [comment]
目前`read_csv`底层是调用`pandas.read_csv`， `pandas.read_csv`并不支持hdfs，只能从csv文件加载。

**Comment by miluoalbert** [comment]
`read_csv`中传入的是各方明文csv文件的路径，不需要在加载前进行同态加密。

例如[DataFrame示例Data preparation流程](https://secretflow.readthedocs.io/en/latest/tutorial/DataFrame.html#Data-preparation)，其中`h_alice_path`和`h_bob_path`路径中存储于各方的都是明文csv数据

**Comment by cs1317** [comment]
如果聚合设备已经获得了各方的csv路径，并且获得了读的权限，那无法保证聚合设备这一方不利用现有条件读取用户隐私数据，除非该聚合设备是可信的？

**Comment by zhouaihui** [comment]
read_csv只是告诉各个参与方读取各自的文件，需要明白，这里并没有传输数据给其他方，数据仍然在参与方自己的内存里，所以聚合设备显然并不会获得读权限。至于怎么聚合更安全，可以参考 [安全聚合](https://secretflow.readthedocs.io/en/latest/tutorial/Secure_aggregation.html)

**Comment by usafchn** [comment]
> 目前`read_csv`底层是调用`pandas.read_csv`， `pandas.read_csv`并不支持hdfs，只能从csv文件加载。

补充一下，read_csv 读入的数据是在本地的 PYU 里面，如果要同态加密，把数据从 PYU to 到 HEU 里面即可（需要初始化一个 HEU 设备实例），HEU 加密数据是 lazy 的、隐式的，PYU to 同一方 HEU 数据还是明文的，只有 HEU 发送数据给其它方 HEU 时才会触发数据加密（可以通过 HeObject.is_plain 字段查看数据加密状态）

**Comment by usafchn** [comment]
隐语用的是上帝视角编程模式，您所写的代码称为 driver，driver 只是为了驱动参与方执行逻辑，他本身并不参与计算，例如 read_csv 操作，driver 只是下发 read_csv 命令给所有参与方，真正读取数据的行为是在参与方本地发生，driver 感知不到数据，所以 csv 文件中的数据可以是明文，不需要加密。

**Comment by cs1317** [comment]
各位大佬，我想问一下，搭建了ray集群之后，我通过其他程序将csv文件放到ray集群中某个节点的机器上，此时，secretflow的read_csv如何传这个路径？
from secretflow.data.horizontal import read_csv

**Comment by zhouaihui** [comment]
给出每一方的文件路径即可，参考 [DataFrame](https://secretflow.readthedocs.io/en/latest/tutorial/DataFrame.html#Creation)
