### ISSUE TITLE
avx

### ISSUE THREAD

**Issue by Niyci** [secretflow/secretflow#1040]
![image](https://github.com/secretflow/secretflow/assets/87159755/a7ac650e-bfb2-4416-b898-99c9c8ad938e)
之前提过这个问题，说是使用的cpu不支持avx指令集
哪pip install spu==0.3.3b0 ，可不可以避免这个问题
或者有什么新的解决方案

**Comment by anakinxc** [comment]
Hi @Niyci 

请问你用的什么 CPU 呀？

**Comment by Niyci** [comment]
英特尔w5-3425 CPU（≥12核心，≥4.6GHz睿频） 
我看过这个cpu，里面没有avx,但有avx2和其他的avx系列指令集

**Comment by anakinxc** [comment]
看起来有点奇怪，你试一下

`pip install py-cpu`

然后在 python 里

```python
import py_cpu

cpu_info = py_cpu.CPUInfo()
print(cpu_info.features)
```

**Comment by Niyci** [comment]
设备目前没在身边，
![ce27dd44cd9ad8f8cd3d2b31c41e9129](https://github.com/secretflow/secretflow/assets/87159755/3fc0eeef-fcb3-4184-942d-a23553911fae)
![b9672fbfbcbed4ccdec0d8daaee3460f](https://github.com/secretflow/secretflow/assets/87159755/b8a9c8e5-5d25-4ad0-ab50-798256c2ce59)

**Comment by anakinxc** [comment]
> 设备目前没在身边， ![ce27dd44cd9ad8f8cd3d2b31c41e9129](https://user-images.githubusercontent.com/87159755/284143802-3fc0eeef-fcb3-4184-942d-a23553911fae.png) ![b9672fbfbcbed4ccdec0d8daaee3460f](https://user-images.githubusercontent.com/87159755/284143820-b8a9c8e5-5d25-4ad0-ab50-798256c2ce59.png)

有机会麻烦试一下，你这个 error message 是 jax 报出来的
有可能是 jax 的 avx 检查逻辑有点问题，avx2 理论上是 avx 的扩展。。所以支持 avx2 的应该算是支持 avx
