### ISSUE TITLE
关于SLmodel支持的拆分学习类型

### ISSUE THREAD

**Issue by iven-j** [secretflow/secretflow#1043]
### Issue Type

Others

### Source

source

### Secretflow Version

SecretFlow: 1.2.0.dev20231025

### OS Platform and Distribution

linux ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
请问隐语的slmodel模块是否支持以下两种形式的拆分学习：
1.将数据水平划分给各个参与方，label数据保存在聚合端
2.U型spilt-nn，即数据和label都保存在参与端，
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by ian-huu** [comment]
隐语目前支持的模式是垂直拆分：多个 client 端 + 一个 server 端，其中 server 端可以有特征或者没有特征。每个 client 端样本是垂直切分的。

你提到的两种拆分模式目前都没有支持，具体是有什么样的需求吗
