### ISSUE TITLE
wsl安装secretflow失败

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/secretflow#1046]
wsl ubuntu22.04环境，python3.9
pip直接安装，失败，看不懂这是什么原因

lishihao@lishihao:~$ sudo pip3 install -U secretflow
Collecting secretflow
  Using cached secretflow-0.7.7b0.tar.gz (163 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kaviwyoh/secretflow_07a04a01d5034622904bb8ed46b930d0/setup.py", line 100, in <module>
          install_requires=read_requirements(),
        File "/tmp/pip-install-kaviwyoh/secretflow_07a04a01d5034622904bb8ed46b930d0/setup.py", line 17, in read_requirements
          with open('./requirements.txt') as file:
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wangyixianggogo** [comment]
hello，这个是我们的[推荐步骤](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation#option-4-from-wsl)，看看有没有帮助。

**Comment by daydayuphere** [comment]
是呢，我按照这个帮助来的，唯一的差别是Python版本3.9.
看提示是包里面缺文件，是包打错了吗
with open('./requirements.txt') as file:
FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'

**Comment by wangyixianggogo** [comment]
secretflow只有python3.8的包,我们的环境也是python3.8

**Comment by daydayuphere** [comment]
果然是3.9的问题，改成3.8ok

**Comment by litterqi** [comment]
hello，我的python版本是3.10，也遇到了这个错误。除了改python版本还有什么方法吗
