### ISSUE TITLE
从pypi安装时，快速尝试样例执行失败

### ISSUE THREAD

**Issue by sqh539** [secretflow/secretflow#1048]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.3.0.dev2

### OS Platform and Distribution

CentOS Linux 7 

### Python version

 3.8.18

### What happend and What you expected to happen.

```shell
我参考，secretflow安装文档，方式 1: 从pypi，安装完成后。
在使用【快速尝试】中的步骤进行测试时，产生了下面的错误。
```

### Reproduction code to reproduce the issue.

```shell
[s***@localhost ~]$ conda activate sf
(sf) [s***@localhost ~]$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import secretflow as sf
>>> sf.init(parties=['alice', 'bob', 'carol'], address='local')
2023-11-22 13:49:49,501	INFO worker.py:1538 -- Started a local Ray instance.
[2023-11-22 13:49:51,371 E 67750 67750] core_worker.cc:179: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

**Comment by xiushuiguande** [comment]
hello，请问实例的配置是多少？是否是按照环境推荐配置吗？

**Comment by sqh539** [comment]
> hello，请问实例的配置是多少？是否是按照环境推荐配置吗？

是48核250G的机器，运行时负载很低。

**Comment by zhouaihui** [comment]
```
pip show ray
pip show secretflow-ray
```
看下是否是重复装了ray/secretflow-ray

**Comment by sqh539** [comment]
> ```
> pip show ray
> pip show secretflow-ray
> ```
> 
> 看下是否是重复装了ray/secretflow-ray

(sf) [s**@localhost ~]$ pip show ray
WARNING: Package(s) not found: ray
(sf) [sunqihao@localhost ~]$ pip show secretflow-ray
Name: secretflow-ray
Version: 2.2.0
Summary: Ray provides a simple, universal API for building distributed applications.
Home-page: https://github.com/ray-project/ray
Author: Ray Team
Author-email: ray-dev@googlegroups.com
License: Apache 2.0
Location: /home/s**/.local/lib/python3.8/site-packages
Requires: aiosignal, attrs, click, filelock, frozenlist, grpcio, jsonschema, msgpack, numpy, protobuf, pyyaml, requests, virtualenv
Required-by: secretflow-rayfed

**Comment by zhouaihui** [comment]
是否可能和你的权限有关系，用 sudo 试试看一下？

也可以看一下你是否对/tmp目录有读写权限

**Comment by NKcqx** [comment]
worker 初始化时会用 domain socket 连接本地的 raylet，默认 uds 路径在 `/tmp/ray/session_latest/sockets`  下面，应该有个叫 raylet 的。 怀疑是 raylet 启动有问题或者目录权限、挂载方式，导致没这个 uds 。
先检查下 `/tmp/ray/session_latest/sockets`  是否存在以及权限是否能正常访问；
如果没问题的话麻烦提供下 Ray 的日志，在 `/tmp/ray/session_latest/logs` 目录下

**Comment by sqh539** [comment]
> worker 初始化时会用 domain socket 连接本地的 raylet，默认 uds 路径在 `/tmp/ray/session_latest/sockets` 下面，应该有个叫 raylet 的。 怀疑是 raylet 启动有问题或者目录权限、挂载方式，导致没这个 uds 。 先检查下 `/tmp/ray/session_latest/sockets` 是否存在以及权限是否能正常访问； 如果没问题的话麻烦提供下 Ray 的日志，在 `/tmp/ray/session_latest/logs` 目录下

目录读写权限是正常的，报错日志找到了，在附件，麻烦排查
[raylet.zip](https://github.com/secretflow/secretflow/files/13435353/raylet.zip)

[s**@localhost ~]$ ll /tmp/ray/session_latest/sockets
total 0
srwxr-xr-x 1 s**  wheel 0 Nov 22 15:54 plasma_store

**Comment by NKcqx** [comment]
> OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1029142 max

raylet.err 中的这个报错是 OS 内核打出来的，原因是达到了系统限制的线程数上限。  
1: 检查下当前容器里是否开启太多进程/线程；
2: 根据报错的提示，提高 `RLIMIT_NPROC` 上限；

**Comment by sqh539** [comment]
> > OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailableOpenBLAS blas_thread_init：线程 10（共 64 个）pthread_create失败：资源暂时不可用
> > OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1029142 maxOpenBLAS blas_thread_init：RLIMIT_NPROC 4096 电流，最大1029142
> 
> raylet.err 中的这个报错是 OS 内核打出来的，原因是达到了系统限制的线程数上限。 1: 检查下当前容器里是否开启太多进程/线程； 2: 根据报错的提示，提高 `RLIMIT_NPROC` 上限；

感谢，确实是这个问题。
我将本用户的限制线程数改为10240后，运行不再报错，但同时shell已经不能创建新的线程了。
正常应该设置为多少合适呢？

**Comment by sqh539** [comment]
> > > OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailableOpenBLAS blas_thread_init：线程 10（共 64 个）pthread_create失败：资源暂时不可用
> > > OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1029142 maxOpenBLAS blas_thread_init：RLIMIT_NPROC 4096 电流，最大1029142
> > 
> > 
> > raylet.err 中的这个报错是 OS 内核打出来的，原因是达到了系统限制的线程数上限。 1: 检查下当前容器里是否开启太多进程/线程； 2: 根据报错的提示，提高 `RLIMIT_NPROC` 上限；
> 
> 感谢，确实是这个问题。 我将本用户的限制线程数改为10240后，运行不再报错，但同时shell已经不能创建新的线程了。 正常应该设置为多少合适呢？

另外我在另一台机器跑同样的命令 线程数只会到900多，这台会到 10178

**Comment by NKcqx** [comment]
> > > OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailableOpenBLAS blas_thread_init：线程 10（共 64 个）pthread_create失败：资源暂时不可用
> > > OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1029142 maxOpenBLAS blas_thread_init：RLIMIT_NPROC 4096 电流，最大1029142
> > 
> > 
> > raylet.err 中的这个报错是 OS 内核打出来的，原因是达到了系统限制的线程数上限。 1: 检查下当前容器里是否开启太多进程/线程； 2: 根据报错的提示，提高 `RLIMIT_NPROC` 上限；
> 
> 感谢，确实是这个问题。 我将本用户的限制线程数改为10240后，运行不再报错，但同时shell已经不能创建新的线程了。 正常应该设置为多少合适呢？

通常不需要额外提高 `RLIMIT_NPROC` ，而是优先检查系统环境内是否有进程/线程泄漏或意外开启大量线程。

**Comment by NKcqx** [comment]
> > > > OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailableOpenBLAS blas_thread_init：线程 10（共 64 个）pthread_create失败：资源暂时不可用
> > > > OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1029142 maxOpenBLAS blas_thread_init：RLIMIT_NPROC 4096 电流，最大1029142
> > > 
> > > 
> > > raylet.err 中的这个报错是 OS 内核打出来的，原因是达到了系统限制的线程数上限。 1: 检查下当前容器里是否开启太多进程/线程； 2: 根据报错的提示，提高 `RLIMIT_NPROC` 上限；
> > 
> > 
> > 感谢，确实是这个问题。 我将本用户的限制线程数改为10240后，运行不再报错，但同时shell已经不能创建新的线程了。 正常应该设置为多少合适呢？
> 
> 另外我在另一台机器跑同样的命令 线程数只会到900多，这台会到 10178

ray 不会开启 1w 数量级的线程数，这通常是如上所述的系统环境本身的问题，同样的命令在不同容器内运行时的总线程数不同也可印证这一点。

**Comment by ShallMate** [comment]
@sqh539 您好，我遇到了和提问者相同的问题，这是我的报错日志。麻烦您有时间的话排查一下
[logs.zip](https://github.com/secretflow/secretflow/files/13513131/logs.zip)

**Comment by xiushuiguande** [comment]
@ShallMate pthread_create failed: Resource temporarily unavailable
Resource temporarily unavailable OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 513452 max
  raylet.err 中的这个报错是 OS 内核打出来的，原因是达到了系统限制的线程数上限。
  1: 检查下当前容器里是否开启太多进程/线程；
  2: 根据报错的提示，提高 RLIMIT_NPROC 上限；
hi，你的raylet.err日志和上边提示是一样的。
