### ISSUE TITLE
PIR算子

### ISSUE THREAD

**Issue by liyuu127** [secretflow/secretflow#1049]
### Issue Type

Documentation Bug

### Source

source

### Secretflow Version

0.6b

### OS Platform and Distribution

linux ubuntu20.4

### Python version

3.8

### What happend and What you expected to happen.

```shell
有无PIR算子的TaskInputConfig 结构示例
```

### Reproduction code to reproduce the issue.

```shell
比如https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/tutorial/run_bfia_job_cn#ss-lr-task-input-config ss lr 算子的结构示例 pir如何描述
```

**Comment by 6fj** [comment]
hi @liyuu127 

目前PIR尚未包装成组件，我们预计将会在12月底放出PIR组件。
感谢。
