### ISSUE TITLE
使用kuscia部署，新添加节点页面不显示进入节点按钮

### ISSUE THREAD

**Issue by liyuhui666** [secretflow/secretflow#1057]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretpad:v0.3.0a0-20231109120149-e54dff

### OS Platform and Distribution

centOS7

### Python version

3.9.2

### Bazel version

6.0.0

### What happend and What you expected to happen.

```shell
我使用kuscia部署，新添加节点后，登录页面不显示进入节点按钮，只有删除按钮，但节点状态显示正常
参考文档https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/deploy_master_lite_cn

下面是新增节点命令
```

### Reproduction code to reproduce the issue.

```shell
./deploy.sh lite -n rubtintr -t 7KxxAULhv7gdj4YHRlRMcd5tknVBtum7 -m https://ip:18080 -p 13222 -g 13242 -k 13262 -i ip
```

**Comment by liyuhui666** [comment]
页面是这样的，如果节点没注册，状态是不可用，现在状态是可用，却没有进入按钮

![1701162386](https://github.com/secretflow/secretflow/assets/71497399/1c7cf66c-133b-404d-a982-f9e7be342b28)

**Comment by wangyixianggogo** [comment]
哈喽，我们新版本做了一些更新，现在会用edge页面管理这些节点，可以参考下我们的[更新](https://www.secretflow.org.cn/docs/quickstart/dyd96u55n4fef9mz)

**Comment by liyuhui666** [comment]
我是使用了secretpad:v0.3.0a0-20231109120149-e54dff容器，而且看时间应该是11月9日更新的版本

**Comment by wangyixianggogo** [comment]
哈喽，[这里](https://www.secretflow.org.cn/docs/quickstart/fn9h9yqoievouz2a)是节点安装的文档，然后可以通过localhost：edge的端口号，进入edge页面进行节点的管理
