### ISSUE TITLE
分布式编程实现

### ISSUE THREAD

**Issue by liliiscaiji** [secretflow/secretflow#106]
### Issue Type

Others

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.8

### What happend and What you expected to happen.
我想请教一个如何用编程实现的问题，我看secretflow的教程是单机模拟，就可以在单机的一个.py程序中编程实现。那如果是分布式的，一个物理节点提供标签，一个物理节点提供数据，再来一个物理节点提供模型，那么在哪个节点进行编程实现，这一个节点如何访问其他节点的变量。
```py
# load features on Alice
X, _ = ppd.device("P1")(load_dataset)()

# load labels on Bob
_, Y = ppd.device("P2")(load_dataset)()
```
比如，X，Y分别在不同的节点中，如何把它们一块放如损失函数中。

### Reproduction code to reproduce the issue.
我想请教一个如何用编程实现的问题，我看secretflow的教程是单机模拟，就可以在单机的一个.py程序中编程实现。那如果是分布式的，一个物理节点提供标签，一个物理节点提供数据，再来一个物理节点提供模型，那么在哪个节点进行编程实现，这一个节点如何访问其他节点的变量。
```py
# load features on Alice
X, _ = ppd.device("P1")(load_dataset)()

# load labels on Bob
_, Y = ppd.device("P2")(load_dataset)()
```
比如，X，Y分别在不同的节点中，如何把它们一块放如损失函数中。

**Comment by zhouaihui** [comment]
首先，隐语提供的是single controller编程模式，站在全局视角编写代码。隐语编程并不区分单机或集群模式，其写法是通用的。（单机模式也是通过多进程模拟的多方）

具体到你的问题，Alice有特征，Bob有标签。如果你想进行计算，需要想清楚计算模型是什么（比如执行什么算法），以及如何保证安全性。
按照你的问题假设，如果你想让Bob计算loss，则可以把X发送给Bob，但是注意这是不安全的，X将会被明文发送给Bob。所以你需要设计算法模型来保证安全。

```python
# 以下代码是不安全的明文计算，请不要这么写
alice, bob = sf.PYU('alice'), sf.PYU('bob')
x = alice(load_feature)()
y = bob(load_label)()

# 基于x和y计算loss
# x.to(bob) 表示将x传输给bob，注意是明文发送
bob(loss_func)(x.to(bob), y) 
```

比如想进行逻辑回归计算，则可以参考[基于SPU的逻辑回归](https://secretflow.readthedocs.io/en/latest/tutorial/lr_with_spu.html)。

另外也可以阅读[水平联邦](https://secretflow.readthedocs.io/en/latest/tutorial/Federate_Learning_for_Image_Classification.html)等教程。

**Comment by zhangxingmeng** [comment]
补充一下，分布式和单机区别就在于部署方式有区别，可以参考一下文档[分布式部署](https://github.com/secretflow/secretflow/blob/beta/docs/getting_started/deployment.md)

**Comment by liliiscaiji** [comment]
谢谢啦，我懂一些了，再细微的请问一下
![image](https://user-images.githubusercontent.com/105691533/188360077-df9a76ff-3db3-49c0-8aae-2a143fa69123.png)
我的理解：在单机模拟中，alice和bob是两个进程，spu是由这两个进程构建起来的虚拟设备，执行SEMI2K两方安全计算协议；如果是分布式场景中，alice和bob是两个物理设别，既充当数据提供方，又充当计算方（相当于Colocated模式），spu是由这两个物理设备通过ray进行通信而建立的实现安全多方计算的虚拟设备。请问这样的理解是否正确。
还想请问一下，在文档中分布式设备的布局可以分为Outsourcing，Colocated，Hybrid三种模式，这是在哪里进行设置，还是框架会根据数据提供方，计算方的数量自动的进行选择？

**Comment by zhouaihui** [comment]
针对你的示例代码，稍微澄清一下：
`alice_pyu, bob_pyu = sf.PYU('alice'), sf.PYU('bob')`这行代码表示创建了两个明文计算设备PYU，分别对应alice和bob域内的进程。

`spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))`这行代码是单机模拟用的，会创建一个SPU设备实例，由alice和bob域内的进程组成（注意和PYU的进程并无关联）。


Outsourcing，Colocated，Hybrid三种模式取决于你逻辑上怎么编排代码，逻辑上你可以任意组合，并不需要特别的设置。

比如你让carol/dave提供数据，由alice和bob组成的spu进行计算，那它就是个Outsourcing模式；如果alice/bob同时也提供数据，那就是Colocated模式。隐语在这方面是非常灵活的。

**Comment by liliiscaiji** [comment]
好的，谢谢啦
