### ISSUE TITLE
从pypi安装之后导入报错

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#1065]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.8.0

### What happend and What you expected to happen.

```shell
直接使用pip安装secretflow报错
```

### Reproduction code to reproduce the issue.

```shell
在导入sf包就会提示错误
没有“phe”，但是能看到有phe包
```

**Comment by mtl802** [comment]
![image](https://github.com/secretflow/secretflow/assets/20579710/64dc18bb-c387-49fd-9ebd-07408874ac1e)

**Comment by mtl802** [comment]
想使用编译安装，但是也会报错
DEBUG: Rule 'yacl' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1699248591 +0800"
DEBUG: Repository yacl instantiated at:
  /data/mtl/code/back/primihub/python/secretflow/WORKSPACE:5:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/69b6ebf8a068578904ffe5c48ecc8e0c/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //secretflow_lib/binding:_lib.so (1 packages loaded, 1481 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/69b6ebf8a068578904ffe5c48ecc8e0c/external/yacl/yacl/crypto/base/BUILD.bazel:19:16: Compiling yacl/crypto/base/symmetric_crypto.cc failed: (Exit 1): gcc failed: error executing command /opt/rh/devtoolset-8/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 48 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/yacl/yacl/crypto/base/symmetric_crypto.h:29,
                 from external/yacl/yacl/crypto/base/symmetric_crypto.cc:15:
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:218:64: error: optimization attribute on 'void yacl::crypto::AES_set_encrypt_key(uint128_t, yacl::crypto::AES_KEY*)' follows definition but the attribute doesn't match [-Werror=attributes]
 inline void AES_set_encrypt_key(uint128_t userkey, AES_KEY *key) {
                                                                ^
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:106:5: note: previous definition of 'void yacl::crypto::AES_set_encrypt_key(__m128i, yacl::crypto::AES_KEY*)' was here
     AES_set_encrypt_key(const __m128i userkey, AES_KEY *key) {
     ^~~~~~~~~~~~~~~~~~~
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:223:53: error: optimization attribute on 'yacl::crypto::AES_KEY yacl::crypto::AES_set_encrypt_key(uint128_t)' follows definition but the attribute doesn't match [-Werror=attributes]
 inline AES_KEY AES_set_encrypt_key(uint128_t userkey) {
                                                     ^
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:106:5: note: previous definition of 'void yacl::crypto::AES_set_encrypt_key(__m128i, yacl::crypto::AES_KEY*)' was here
     AES_set_encrypt_key(const __m128i userkey, AES_KEY *key) {
     ^~~~~~~~~~~~~~~~~~~
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:242:64: error: optimization attribute on 'void yacl::crypto::AES_ecb_encrypt_blks(const yacl::crypto::AES_KEY&, absl::lts_20230125::Span<const __int128 unsigned>, absl::lts_20230125::Span<__int128 unsigned>)' follows definition but the attribute doesn't match [-Werror=attributes]
                                  absl::Span<uint128_t> out_blks) {
                                                                ^
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:141:5: note: previous definition of 'void yacl::crypto::AES_ecb_encrypt_blks(const __m128i*, __m128i*, size_t, const yacl::crypto::AES_KEY*)' was here
     AES_ecb_encrypt_blks(const __m128i *in_blks, __m128i *out_blks,
     ^~~~~~~~~~~~~~~~~~~~
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:250:60: error: optimization attribute on 'std::vector<__int128 unsigned> yacl::crypto::AES_ecb_encrypt_blks(const yacl::crypto::AES_KEY&, absl::lts_20230125::Span<const __int128 unsigned>)' follows definition but the attribute doesn't match [-Werror=attributes]
     const AES_KEY &key, absl::Span<const uint128_t> in_blks) {
                                                            ^
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:141:5: note: previous definition of 'void yacl::crypto::AES_ecb_encrypt_blks(const __m128i*, __m128i*, size_t, const yacl::crypto::AES_KEY*)' was here
     AES_ecb_encrypt_blks(const __m128i *in_blks, __m128i *out_blks,
     ^~~~~~~~~~~~~~~~~~~~
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:258:70: error: optimization attribute on 'void yacl::crypto::AES_ecb_encrypt_blks(const yacl::crypto::AES_KEY&, const uint128_t*, size_t, uint128_t*)' follows definition but the attribute doesn't match [-Werror=attributes]
                                  size_t blks_num, uint128_t *out_blks) {
                                                                      ^
external/yacl/yacl/crypto/base/aes/aes_intrinsics.h:141:5: note: previous definition of 'void yacl::crypto::AES_ecb_encrypt_blks(const __m128i*, __m128i*, size_t, const yacl::crypto::AES_KEY*)' was here
     AES_ecb_encrypt_blks(const __m128i *in_blks, __m128i *out_blks,
     ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Target //secretflow_lib/binding:_lib.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.305s, Critical Path: 7.59s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
error: command '/usr/local/bin/bazel' failed with exit code 1

**Comment by Chrisdehe** [comment]
@mtl802 hey
你的conda环境创建了吗？
如果有，请重新创建一个新的尝试
并且指定一个pypi源

**Comment by mtl802** [comment]
> @mtl802 hey 你的conda环境创建了吗？ 如果有，请重新创建一个新的尝试 并且指定一个pypi源

已经可以了，我从编译环境安装的。我想请问一下，编译的GCC版本是11，我在编译安装之后再升级或者降级GCC版本，还能够正常使用sf吗

**Comment by Chrisdehe** [comment]
是可以的哈

**Comment by mtl802** [comment]
好的，感谢
