### ISSUE TITLE
SecretFlow能否源码编译安装？

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#107]
SecretFlow能否源码编译安装？

**Comment by usafchn** [comment]
您可以尝试以下方法：

切换到 secretflow 代码根目录，执行：
```
pip install -e .
```

要求 Python 环境为 3.8

**Comment by anakinxc** [comment]
补充一下，应该还需要先自己编译 spu 和 heu

两个 repo 的 readme 里都有对应的编译方法
