### ISSUE TITLE
关于拆分学习模型使用问题

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#1075]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.8.0

### What happend and What you expected to happen.

```shell
请问一下，关于官方文档中的拆分学习模型中export_model和save_model的区别是什么。
当我保存这个模型后应该如何使用
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by ian-huu** [comment]
save 和 export 的区别类似于 torch 的 [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html) 和 [torch.onnx.export](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)。

在 secretflow 内的保存和加载只需要使用 save_model 即可；export_model 是预留给在线引擎用的，不保证 export 以后可以原样加载。

**Comment by mtl802** [comment]
> save 和 export 的区别类似于 torch 的 [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html) 和 [torch.onnx.export](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)。
> 
> 在 secretflow 内的保存和加载只需要使用 save_model 和 [load_model](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow.ml.nn.ml.nn.sl#secretflow.ml.nn.sl.sl_model.SLModel.load_model) 即可；export_model 是预留给在线引擎用的，不保证 export 以后可以原样加载。

好的，明白了，感谢

**Comment by mtl802** [comment]
请问我有办法只使用单一的本地模型和全局模型进行预测吗
还是说模型的预测必须要有所有参与训练的参与方一起才能预测

**Comment by ian-huu** [comment]
垂直拆分场景下每一个 base 模型所在方需要各自提供特征，所以需要所有模型一起才能正常预测
