### ISSUE TITLE
关于几个产品的疑问

### ISSUE THREAD

**Issue by daoshouchen** [secretflow/secretflow#1077]
### Issue Type

Others

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
1 基于 kuscia 搭建的计算框架和 mvp 之间是什么关系，mvp 包是否包含了 kuscia 框架的所有吗？ 2 我直接使用 mvp 体验包搭建双节点，允许生产计算是否可行？ 3 scql 我想集成，安装了是不是和其他的重复了？ scql 底层是不是又安装了一次 kuscia和secretflow ？小白越看越迷糊.
现在进行尝试搭建测试环境了，求解惑
```

### Reproduction code to reproduce the issue.

```shell
现在针对几个产品的安装使用有点模糊，请大佬介绍一下
```

**Comment by longshan-ant** [comment]
隐语目前实际落地时会分层为： 平台，底座，引擎；  平台主要是 mvp的平台/ezpsi的平台/TEE的平台的。 底座指的是kuscia； 引擎指的是psi,secretflow,trustedflow等。
kuscia会作为所有引擎的底座，所有引擎可以跑在kuscia上，平台通过调用kuscia-api来实现任务调度相关的能力；
所以你上面问题的答案是：
1. mvp部署包是包含了kuscia的
2. mvp部署包目前只支持中心化模式，所以基于他创建2个新的节点，是可以使用的，但是我们中心化模式比较倾向是对中心有信任的场景（比如大集团内部子公司的模式，每个子公司部署节点，平台部署在总公司之类的）； 同时我们目前MVP平台还没有权限管理等等能力，所以可能并不直接适用于生产，这些能力目前需要你们自己来满足。
3. scql目前还是直接提供的引擎，还没有和kuscia等能力集成，我们目前正在开发中；所以你当下部署scql不会部署kuscia和secretflow； 未来scql和kuscia集成好后，不论你单独部署了mvp或者scql能力，都可以动态扩展增加其他能力，而不需要重新部署。
