### ISSUE TITLE
利用tee api实现两方机构csv文件读取 tee内计算问题

### ISSUE THREAD

**Issue by Jymjiaym** [secretflow/secretflow#1080]
第一张图是alice节点日志 第二张图是bob节点日志 第三章是carol方日志，目前想实现alice 和bob 的csc文件 读取后 在 tee求和返回结果 但是carol不打印任何东西，第四张图是业务代码逻辑，麻烦看下是什么问题导致。
![2](https://github.com/secretflow/trustedflow/assets/93430715/1e0476ee-bc3f-4b01-be17-18b3ae3a3ce0)
![3](https://github.com/secretflow/trustedflow/assets/93430715/9d4b38f1-a87d-4888-a15e-dc0a54e9a110)
![4](https://github.com/secretflow/trustedflow/assets/93430715/7ac6494f-ad4e-442b-abc9-09abc81026ff)
![1](https://github.com/secretflow/trustedflow/assets/93430715/fb6024d5-8508-462b-9762-f2aaab0a767d)

**Comment by Jymjiaym** [comment]
补充代码和日志截图：图一是alice代码 图二是bob代码 图三四是carol代码 
![alice方日志](https://github.com/secretflow/secretflow/assets/93430715/866415d2-5cab-4221-87eb-6bcdb285be0a)
![bob日志](https://github.com/secretflow/secretflow/assets/93430715/62a61055-02d1-4458-8005-9a20dca9a9bb)
![carol日志](https://github.com/secretflow/secretflow/assets/93430715/c5e27497-41cf-4efd-a4f7-0b821bec4df4)

**Comment by Jymjiaym** [comment]
@zhouaihui 您好，信息已补充，辛苦帮忙给看下吧。

**Comment by zhouaihui** [comment]
> @zhouaihui 您好，信息已补充，辛苦帮忙给看下吧。

hi, 麻烦检查一下材料，似乎没有代码？

**Comment by Jymjiaym** [comment]
![代码1](https://github.com/secretflow/secretflow/assets/93430715/85795156-e925-483d-b38e-45b8132b14fb)
![代码2](https://github.com/secretflow/secretflow/assets/93430715/2aa98afa-f9f9-420e-91cc-87c68e37a7ba)
![代码3](https://github.com/secretflow/secretflow/assets/93430715/6e7e0648-0e7b-445e-a22d-42e01bde0e45)
![代码4](https://github.com/secretflow/secretflow/assets/93430715/61182282-d050-4136-bc22-b464981b9801)
