### ISSUE TITLE
Malicious security support

### ISSUE THREAD

**Issue by kkonevets** [secretflow/secretflow#1081]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

1.3.0.dev20231206

### OS Platform and Distribution

Linux Ubuntu 22

### Python version

3.8.18

### What happend and What you expected to happen.

```shell
Hi! Currently `Secretflow` [supports](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/mpc_status) only semi-honest security models. Do you plan to add malicious security models like MASCOT / LowGear? Is it hard to add them?
```

### Reproduction code to reproduce the issue.

```shell
It's a feature request...
```

**Comment by tpppppub** [comment]
Hi @kkonevets , supporting malicious security models is not our first priority. 
Currently, although we have an implementation of [Spdz2K protocol](https://github.com/secretflow/spu/tree/main/libspu/mpc/spdz2k), it relies on a trusted third party and is still under development. However, you can check it as a reference for your purpose.

**Comment by kkonevets** [comment]
Thanks, will take a look.
