### ISSUE TITLE
在docker容器中部署出现错误

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#1082]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.8.0

### What happend and What you expected to happen.

```shell
在两台主机上使用docker容器部署。
A主机IP为16，容器IP为26
B主机IP为17，容器IP为27

我在A主机中初始化SF的配置文件为{“A”：“26：port”， “B”：“17:port”}
B主机中初始化SF的配置文件为{“A”：“16：port”， “B”：“27:port”}
```

### Reproduction code to reproduce the issue.

```shell
可以连接成功，也能对VDataFram操作。
最后在执行sl.fit时一直等待
```

**Comment by mtl802** [comment]
![2d74815dce6be695e464af054987de1](https://github.com/secretflow/secretflow/assets/20579710/3a58d9b2-2434-4649-900f-e13b7aced66e)
![01c71f25e9f27869aa553fc667bbc90](https://github.com/secretflow/secretflow/assets/20579710/da8fbd28-d5e3-4384-99c7-46e30a3bf402)

**Comment by zhangxingmeng** [comment]
这个是cuda的的报错，可以检查一下是不是没装好。
也有可能是torch和tf的cuda冲突了，可以尝试更新torch版本来解决问题

**Comment by mtl802** [comment]
如果我不使用集群训练，只进行单机仿真。那就会继续执行，难道集群训练和单机仿真需要的python包版本不一致？

**Comment by zhangxingmeng** [comment]
你这里的问题是集群模式会卡主吗？这个问题可以看一下文档，集群模式需要两方都要配置正确后同时启动。只启动一方就会卡主

**Comment by mtl802** [comment]
集群都起了ray --head，应该是正常的，在sf.init中可以建立连接，但是只有在fit时无法训练

**Comment by zhangxingmeng** [comment]
具体fit的执行也需要两方同时启动的。
