### ISSUE TITLE
为什么文档中水平数据框和垂直数据框数据不一样，是哪里又不一样的操作吗？

### ISSUE THREAD

**Issue by linhaibo123** [secretflow/secretflow#109]
hdf.mean(numeric_only=True)
sepal length (cm)    1.168667
sepal width (cm)     0.611467
petal length (cm)    0.751600
petal width (cm)     0.239867
target               0.200000
dtype: float64
vdf.mean(numeric_only=True)
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64

**Comment by zhouaihui** [comment]
这个是已知问题 #69 ，下个版本我们会修复。

**Comment by zhouaihui** [comment]
Duplicate of #69

**Comment by linhaibo123** [comment]
> 

嗯，我刚测了下，把nan值用0填充之后结果一样了。应该是数据缺失的问题

**Comment by linhaibo123** [comment]
> 

hdf.fillna({'sepal length (cm)': 0, 'petal length (cm)':0})
hdf.mean(numeric_only=True)
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64
vdf.mean(numeric_only=True)
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64
