### ISSUE TITLE
初始化的时候出现错误

### ISSUE THREAD

**Issue by xuan-123d** [secretflow/secretflow#1090]
(sf) xuan@DESKTOP-1FHJOJQ:~$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import secretflow as sf
>>> parties=['alice','bob','carol']
>>> sf.init(parties,num_cpus=16)
WARNING:root:When connecting to an existing cluster, num_cpus must not be provided. Num_cpus is neglected at this moment.
 INFO worker.py:1538 -- Started a local Ray instance.

这个错误怎么搞

**Comment by Chrisdehe** [comment]
@xuan-123d 如WARNING所言，“num_cpus=16”这个无需放在sf.init中。

**Comment by Chrisdehe** [comment]
请参考：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation#a-quick-try
