### ISSUE TITLE
参与隐私求交的一方支持分布式吗

### ISSUE THREAD

**Issue by liyuhui666** [secretflow/secretflow#1093]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.3.0.dev20231109

### OS Platform and Distribution

centOS7

### Python version

3.9.2

### Bazel version

6.0.0

### What happend and What you expected to happen.

```shell
1.现在部署Secretflow使用镜像部署，每个参与方都启动一个容器，每一方能否启动多个容器呢
2.调度使用的是ray，是在每个容器内启动多个任务去并行执行求交任务吗
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by longshan-ant** [comment]
1. 目前暂时不支持一个任务可以分在多个容器中跑。
    PS： 理论上secretflow底层依赖的是ray，是可以多机部署的，但是目前的单任务数据规模有限，没有针对更大数据做扩展，所以每一方还是启动一个容器。
2. 如果你有多任务，一种可以多容器，也可以独立出来ray集群。

另外，我们建议在多任务等场景下使用kuscia来管理任务，这种场景下并不需要了解secretflow和ray的细节信息，只需要通过api/
cli来提交管理隐私计算任务
文档参考这里： [kuscia入门](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/quickstart_cn)

**Comment by liyuhui666** [comment]
目前单容器支持的数据量是多大，启动的容器的内存及核数是在kuscia命令行配置吗

**Comment by longshan-ant** [comment]
> 目前单容器支持的数据量是多大，启动的容器的内存及核数是在kuscia命令行配置吗

单容器支持的数据量和跑的具体算法以及机器性能有关系，如果单独使用secretflow容器，可以直接针对secretflow容器配置；
如果是kuscia，可以针对kuscia的容器设置CPU/MEM数量，目前是默认所有计算任务共享资源的。 我们会在后续，增加针对指定的task单独指定资源。

你这边现在是有资源设置的需求吗？

**Comment by liyuhui666** [comment]
我希望是处理更大数据量数据，毕竟单容器处理量有限，最好是能支持多个容器处理一个任务，共同作为计算的一方

**Comment by longshan-ant** [comment]
> 我希望是处理更大数据量数据，毕竟单容器处理量有限，最好是能支持多个容器处理一个任务，共同作为计算的一方

不好意思，目前暂时还是不支持多容器来跑同一个任务的；一种简单的方法是，如果是类似PSI的任务，可以手动拆分数据后，并发提交多个任务来跑，这样在kuscia层面会自动调度出来多个容器来跑。

你们现在是期望跑什么样的算法，数据规模是什么样的？

**Comment by liyuhui666** [comment]
比如psi任务手动拆分数据，现在有A、B两方，我把A数据拆成10份，然后分成10个任务，分别同一个B求交，B容器只启动一个可以同时执行吗
数据10亿，之前协议用的ecdh，期望哪个快用哪个，kkrt速率怎么样，kkrt是基于布谷鸟做的吗

**Comment by longshan-ant** [comment]
不支持A拆分10份数据，B不拆分数据执行； 
如果要拆分，是需要2边同时来拆分（相同的hash函数），然后A/B的文件要一一对应，才可以跑。

关于PSI性能参考这里： https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/developer/benchmark/psi_benchmark
关于PSI协议参考这里： https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/user_guide/psi

**Comment by liyuhui666** [comment]
2边同时来拆分（相同的hash函数）是什么意思
如果两边同时拆分数据，我如何保证A/B的文件要一 一对应，两方之间数据都是保密的，如果两边都是乱序，怎样保证A1中数据不会出现在B2、B3中，只和B1对应求交，如果对应不了，那岂不是得算10*10求交

**Comment by 6fj** [comment]
hi @liyuhui666 

对于PSI来说，能支持十亿规模的输入。请问你这边是有更大的诉求吗？

**Comment by liyuhui666** [comment]
如果是10亿数据量，需要提供多少内存，执行多久能完成
当前只是调研阶段，还没有实际使用，数据量只能估计，但随着业务发展，需求增多，还是需要考虑更多数据情况

**Comment by 6fj** [comment]
遵从secretflow的统一推荐配置：8c16g即可

**Comment by liyuhui666** [comment]
![8 T W9U~ JGCGRR3LV${R%B](https://github.com/secretflow/secretflow/assets/71497399/4fb5e424-9c21-4a9f-8b7a-9df2e03e8456)
所以文档此处说的分布式，是指的任务调度方面，不同任务并发执行，而不是类似于spark的同一任务分布式计算，我可以这样理解吗

**Comment by 6fj** [comment]
在secretflow中，每一方都是一个ray集群，ray集群本身是可以支持多节点部署从而水平扩展资源的。

psi在每一方只能部署单节点是由于底层算法的原因，换言之，你可以通过secretflow同时并发执行多个psi任务，但是你无法让一个psi任务在其中一方的多节点上执行。

不过psi分布式并发是一个有意思的话题，我们也在关注这个问题。感谢！

**Comment by liyuhui666** [comment]
之前我有尝试使用spark去做ecdh-psi，但由于椭圆曲线对象不能序列化出现异常，希望各位老师在分布式方面多做一些探索，感谢您的回复

**Comment by liyuhui666** [comment]
之前我有尝试使用spark去做ecdh-psi，但由于椭圆曲线对象不能序列化出现异常，希望各位老师在分布式方面多做一些探索，感谢您的回复

**Comment by icavan** [comment]
> 之前我有尝试使用spark去做ecdh-psi，但由于椭圆曲线对象不能序列化出现异常，希望各位老师在分布式方面多做一些探索，感谢您的回复

单个大任务使用多机分布式算力加速这个事情隐语内部还在评估，后续会有类似的能力，从计算引擎的分布式化到编排框架一体化，不过目前来看只有带宽足够的情况下，才有这个增益，单纯从 PSI 的业务目标来看，不少用户使用 ECDH / KKRT 就足够应付十亿级需求了

咱们这边目前的任务调度是需要在 spark 框架下做么？

**Comment by liyuhui666** [comment]
也不是必须用，只是之前有自己尝试过分布式psi，不过出现很多问题，涉及到数据切分，数据顺序，序列化等等，基本是用来加速加密数据部分，求交部分还是不太行。

**Comment by icavan** [comment]
> 也不是必须用，只是之前有自己尝试过分布式psi，不过出现很多问题，涉及到数据切分，数据顺序，序列化等等，基本是用来加速加密数据部分，求交部分还是不太行。

如果只是隐私求交，我们基本可以确认稍微好点的单机 + 优秀的求交算法能够满足您的需求，建议从 kuscia api 入口尝试体验，如果 ECDH 不够快也可以尝试 kkrt / rr22 等 cpu 算力更友好的算法；

至于隐私计算单任务的分布式化支持，这个社区还在内部评估和研发中， 敬请关注后续的 roadmap 和发版具体更新内容

**Comment by liyuhui666** [comment]
好的，谢谢
