### ISSUE TITLE
官网teeu xgb例子运行报错

### ISSUE THREAD

**Issue by Jymjiaym** [secretflow/secretflow#1094]
https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/teeu_xgboost该demo运行后报错，错误日志如下：
![微信图片_20231221232052](https://github.com/secretflow/secretflow/assets/93430715/4b5afd9f-5c36-4051-b97b-f6b05b892e3b)
![微信图片_20231221232102](https://github.com/secretflow/secretflow/assets/93430715/3886b6bc-c5a7-4780-9d14-cd4d91fca5dd)

**Comment by zhouaihui** [comment]
可以修改一下这两行(示例代码有问题，多了一个括号)
```
x_a, y_a = alice(gen_data num_returns=2)()
x_b, y_b = alice(gen_data, num_returns=2)()
```

**Comment by Jymjiaym** [comment]
就说按照以上方式进行了修改， 报错train error，具体详见截图日志。
![微信图片_20231222105049](https://github.com/secretflow/secretflow/assets/93430715/78cb24c8-dfa1-43f2-9150-dbb5e993a992)
![微信图片_20231222105104](https://github.com/secretflow/secretflow/assets/93430715/a888f9cc-627c-445e-bb5e-09a3abc57e70)

**Comment by zhouaihui** [comment]
```
res = teeu(xgb_demo)([x_a_teeu, x_b_teeu], [y_a_teeu, y_b_teeu])

print(f'Train error: {sf.reveal(res)}')
```
麻烦修改一下最后的一行代码，error不是报错的意思，是训练模型预测的错误率。

**Comment by Jymjiaym** [comment]
非常感谢，目前模型训练成功。
另外咨询下，我在我的那个xgb模型训练函数里print 日志，不会打印内容。
例如这个图片里 我在xgb模型训练中加了两行print都没打印，这个能帮忙看下这个为什么print内容出来么？
![Uploading print不打印内容.jpg…]()

**Comment by Jymjiaym** [comment]
补充下代码信息。
![Uploading print不打印内容.jpg…]()

**Comment by zhouaihui** [comment]
用logging打日志可以打印吗

**Comment by Jymjiaym** [comment]
不可以，logging也打印不出来

**Comment by Chrisdehe** [comment]
等待ing 我们内部正在复现中

**Comment by Chrisdehe** [comment]
您好，已确认这个功能目前暂不支持。

**Comment by Jymjiaym** [comment]
那有没有可以打印日志的方法，我想打印一下过程中的一些日志信息。

**Comment by Chrisdehe** [comment]
请问是否已得到问题解决呢？
