### ISSUE TITLE
有关ray分布式运行框架

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1096]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.6.13

### OS Platform and Distribution

centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
现在有这样一个场景:存在两个机构alice和bob,其中alice是一个ray集群包含多台设备(一个主节点和多个从节点),bob同样是一个ray集群包含多台设备,现在两方需要共同完成一个隐私计算任务(联邦学习或者其他),这时候alice和bob这两个集群是可以调度各自集群中的所有算力吗(主节点可以调度从节点的计算资源?)
1.如果不是这样那ray集群的目地是什么呢?怎么实现分布式运行
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by xiushuiguande** [comment]
1、目前不能，有些算子可以用多个设备计算，有些只能用一个，取决于算法怎么实现的
2、mpc(使用 spu)算子目前都是单机的，横向联邦算法可以相对方便的在机构内分布式训练（需要自定义策略）
3、https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/user_guide/federated_learning/horizontal_federated_learning
