### ISSUE TITLE
TLS证书验证出现问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1102]
### Discussed in https://github.com/orgs/secretflow/discussions/1101

<div type='discussions-op-text'>

<sup>Originally posted by **oceanqdu** December 26, 2023</sup>
我在采用tls验证之后，两方连接不成功，一直报not match found for servername：xxx 看到之前的issue里有相同的错误说是生成tls证书的时候没有加ip，但是我在生成的时候填写了cn部分，报错如下：

<img width="656" alt="2d5ec013ceb3923b9c41a3f4d8603c3" src="https://github.com/secretflow/secretflow/assets/49178688/e0466916-d7ec-4540-a384-8e5a4be6960f">

tls生成脚本和相关secretflow代码如下：
`#!/bin/bash

openssl genrsa -out alice_ca.key 2048
openssl req -new -key alice_ca.key -out alice_ca.csr -subj "/C=CN/ST=myprovince/L=mycity/O=myorganization/OU=mygroup/CN=myCA"  
openssl x509 -req -days 365 -in alice_ca.csr -signkey alice_ca.key -out alice_ca.crt

openssl genrsa -out alice_server_key.key 2048
openssl req -new -sha256 -key alice_server_key.key -out alice_server_key.csr -subj "/CN=192.168.56.155"
openssl x509 -req -in alice_server_key.csr -CA alice_ca.crt  -CAkey alice_ca.key -CAcreateserial -days 7120 -out alice_server_cert.crt 
openssl verify -CAfile alice_ca.crt  alice_server_cert.crt`

secretflow代码如下：
`
import secretflow as sf
import os
import sys
import time
import logging
import multiprocess
from absl import app
import spu
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

start=time.time()
tls_config = {
    "ca_cert": "/home/fate01/secretflow-code/certificate/cert/alice_ca.crt",
    "cert": "/home/fate01/secretflow-code/certificate/cert/bob_server_cert.crt",
    "key": "/home/fate01/secretflow-code/certificate/cert/bob_server_key.key",
}

cluster_config ={
    'parties': {
        'alice': {
            'address': '192.168.56.155:9923',
            'listen_addr': '0.0.0.0:9923'
        },
        'bob': {

            'address': '192.168.56.156:9924',
            'listen_addr': '0.0.0.0:9924'
        },
    },
    'self_party': 'bob'
}

sf.init(address='192.168.56.156:25174', cluster_config=cluster_config,tls_config=tls_config)

alice = sf.PYU('alice')
bob = sf.PYU('bob')

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id':'alice',
            'address': '192.168.56.155:25676',
            'listen_addr': '0.0.0.0:25676'
        },
        {
            'party': 'bob',
            'id':'bob',
            'address': '192.168.56.156:25176',
            'listen_addr': '0.0.0.0:25176'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM32,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

link_desc = {
    'recv_timeout_ms': 36000,
}

spu = sf.SPU(cluster_def=cluster_def,link_desc=link_desc)

input_path = {alice: 'database/psi1.csv', bob: '/home/fate01/secretflow-code/database/psi2.csv'}
output_path = {alice: '.data/1_psi.csv', bob: '.data/2_psi.csv'}
spu.psi_csv('id', input_path, output_path, 'alice',protocol='ECDH_PSI_2PC',curve_type="CURVE_FOURQ",bucket_size=1<<30)
logging.info(f"cost time: {time.time() - start}")
`
</div>

**Comment by miluoalbert** [comment]
可能是没有正确在自签证书中添加subjectAltName（SAN）字段的原因，请查阅如何在签名中附带SAN字段并正确配置的相关文档

https://raymii.org/s/tutorials/OpenSSL_generate_self_signed_cert_with_Subject_Alternative_name_oneliner.html

**Comment by oceanqdu** [comment]
> 可能是没有正确在自签证书中添加subjectAltName（SAN）字段的原因，请查阅如何在签名中附带SAN字段并正确配置的相关文档
> 
> https://raymii.org/s/tutorials/OpenSSL_generate_self_signed_cert_with_Subject_Alternative_name_oneliner.html
@miluoalbert 您好，关于tls的问题，我这里还是有些问题，
根据您给的建议我在证书里添加了SAN字段，但是还是报相同的错误，下面是我的自签名证书生成脚本
`
**

openssl genrsa -out alice_ca.key 4096

openssl req -new -key alice_ca.key -out alice_ca.csr -subj "/C=CN/ST=myprovince/L=mycity/O=myorganization/OU=mygroup/CN=myCA"  -addext "subjectAltName = IP:192.168.56.155"
openssl x509 -req -days 365 -in alice_ca.csr -signkey alice_ca.key -out alice_ca.crt



openssl req -nodes -x509 -sha256 -newkey rsa:4096 \
  -keyout alice_ca.key \
  -out alice_ca.crt \
  -days 356 \
  -subj "/C=NL/ST=Zuid Holland/L=Rotterdam/O=ACME Corp/OU=IT Dept/CN=alice_ca"  \
  -addext "subjectAltName = IP:192.168.56.155,IP:192.168.56.156" 


openssl req -nodes -x509 -sha256 -newkey rsa:4096 \
  -keyout alice_server_key.key \
  -out alice_server_cert.crt \
  -CA alice_ca.crt  -CAkey alice_ca.key -CAcreateserial\
  -days 356 \
  -subj "/C=NL/ST=Zuid Holland/L=Rotterdam/O=ACME Corp/OU=IT Dept/CN=192.168.56.155"  \
  -addext "subjectAltName = IP:192.168.56.155,IP:192.168.56.156" 


openssl verify -CAfile alice_ca.crt  alice_server_cert.crt
**

`

**Comment by oceanqdu** [comment]
问题解决了，之前没用过TLS，搞懂自签名证书的用法和含义，现在搞明白了，
`openssl req -nodes -x509 -sha256 -newkey rsa:4096 \
  -keyout alice_ca.key \
  -out alice_ca.crt \
  -days 356 \
  -subj "/C=NL/ST=Zuid Holland/L=Rotterdam/O=ACME Corp/OU=IT Dept/CN=alice_ca"  \
  -addext "subjectAltName = IP:192.168.56.155,IP:192.168.56.156" 

openssl genrsa -out alice_server_key.key 4096
openssl req -new -sha256 -key alice_server_key.key -out alice_server_key.csr -subj "/C=NL/ST=Zuid Holland/L=Rotterdam/O=ACME Corp/OU=IT Dept/CN=192.168.56.155" -addext "subjectAltName = IP:192.168.56.155"
openssl x509 -req -in alice_server_key.csr -CA alice_ca.crt  -CAkey alice_ca.key -CAcreateserial -days 356 -out alice_server_cert.crt  `
用这种方式生成alice_ca.cert 、alice_key.key、bob_ca.cert 、bob_key.key,然后alice和bob互换ca.cert通过验证。
