### ISSUE TITLE
关于SecretFlow中加载csv数据的疑问

### ISSUE THREAD

**Issue by liyuhui666** [secretflow/secretflow#1106]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.3.0.dev20231109

### OS Platform and Distribution

centOS7

### Python version

3.9.2

### Bazel version

6.0.0

### What happend and What you expected to happen.

```shell
我看secretflow中有水平场景和垂直场景的切分文件，水平场景是将一个csv文件切成多个schema相同的小文件吗，垂直场景是取schema的某一个字段吗，切分是为了数据对齐吗，为什么要数据对齐

https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/FedDataFrameDataLoader
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by 6fj** [comment]
hi @liyuhui666 

数据出现水平分割或者垂直分割是因为原始数据的owner可能是不同的，我们在逻辑上把双方的数据当作水平/垂直切割表。

一般水平表需要通过PSI的方式根据两边的id进行对齐。
