### ISSUE TITLE
使用spu.psi_csv，是否可以把加密的数据取出来，如果能取出来，之后是否可以用这些数据进行操作？比如聚合之类的

### ISSUE THREAD

**Issue by wind-and-falling-maple-leaf** [secretflow/secretflow#111]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow        0.6.13b1

### OS Platform and Distribution

centos 7.6

### Python version

Python 3.8.10

### GCC/Compiler version

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

### What happend and What you expected to happen.

```shell
secretFlow使用Ray来做分布式引擎，在各自本地使用明文数据，加密过程是看不见的。若我想用区块链来存储，但要需要将加密的文件数据存入区块链，再从区块链把数据取出来，使用Ray来处理加密的数据，这样是否可以实现呢？
```

### Reproduction code to reproduce the issue.

```shell
使用spu.psi_csv，是否可以把加密的数据取出来，如果能取出来，那加密数据存放的地址在哪？之后是否可以用这些数据进行操作？比如聚合之类的
```

**Comment by icavan** [comment]
不同的 PSI 算法流程不一样，因此可能需要明确这里的加密内容指的是什么 PSI 算法的加密内容什么。比如，限定指 ECDH-PSI 的二次 DH 加密密文。

Secretflow 主要是提供 highlevel API，这些加密内容的存储和细节都在底层，secretflow highlevle API 也会屏蔽掉分桶求交等细节。

如果你有拿出密文的需求，需要去找 lowlevel 的 psi c++ api，我举个参考例子，比如 https://github.com/secretflow/spu/blob/beta/spu/psi/store/cipher_store_impl.h#L70 这里的 CipherStore 可以拿到一些二次 DH 加密密文，但是这是内部 API ，目前可能需要你有一定的 API 和源码研究能力才好跟进。

**Comment by wind-and-falling-maple-leaf** [comment]
> 不同的 PSI 算法流程不一样，因此可能需要明确这里的加密内容指的是什么 PSI 算法的哪个阶段的加密内容。比如，限定指 ECDH-PSI 的二次 DH 加密密文。
> 
> Secretflow 主要是提供 highlevel API，这些加密内容的存储和细节都在底层，secretflow highlevle API 也会屏蔽掉分桶求交等细节。
> 
> 如果你有拿出密文的需求，需要去找 lowlevel 的 psi c++ api，我举个参考例子，比如 https://github.com/secretflow/spu/blob/beta/spu/psi/store/cipher_store_impl.h#L70 这里的 CipherStore 可以拿到一些二次 DH 加密密文，但是这是内部 API ，目前可能需要你有一定的 API 和源码研究能力才好跟进。

好的，我明白了，非常感谢@icavan
