### ISSUE TITLE
测试评分卡程序引入 scorecardpy模块后 secretflow包和评分卡模块版本冲突问题

### ISSUE THREAD

**Issue by Jymjiaym** [secretflow/secretflow#1111]
咨询下，这个冲突有没有什么好的解决方法了？
第一个图是occlum执行评分卡程序报错 
第二个图 secretflow执行评分卡程序 numpy和pandas版本 和scorecard内支持版本不一致 需要降级。
![图一](https://github.com/secretflow/secretflow/assets/93430715/095285f3-f150-47b8-bd53-839193245f96)
![图二](https://github.com/secretflow/secretflow/assets/93430715/52c9cb9f-c518-4212-b6c6-9407c5a9782a)

**Comment by yuki252111** [comment]
第一个问题看上去是少安装了一个python库
第二个问题涉及到版本的，建议使用conda创建一个独立环境，安装的时候指定对应的版本号，至于具体使用哪个版本可以根据报错搜索一下，会有对应的解决方案~（建议使用stackoverflow

**Comment by Jymjiaym** [comment]
麻烦再问下：alice和bob不需要执行具体计算，但是还要有计算的全套环境吗 是否合理 ？例如目前评分卡计算tee测试 alice和bob只是传递本方数据 但是还要引入scorecardpy这些计算部分

**Comment by yuki252111** [comment]
这边使用的是TEEU么，alice与bob所说的全套环境是指  要计算的代码函数么

**Comment by Jymjiaym** [comment]
是的用的teeu  全套环境指的就是那个代码函数

**Comment by yuki252111** [comment]
以alice授权给bob计算为例：alice在创造授权请求的时候必须要告诉TEEU这个函数的标识是多少，因此alice需要这份代码。
bob需要这份代码是因为bob在向TEEU提交计算请求时，需要动态的告诉TEEU他要执行的计算函数是什么。
所以真实运行的是bob处提交的计算函数，alice处的是为了提交对该函数的授权

**Comment by Jymjiaym** [comment]
没太理解， 告诉teeu要执行什么函数，那实际执行不还是在teeu吗，还要在a和b部署执行函数的环境吗

**Comment by yuki252111** [comment]
因为teeu其实没有函数的定义，函数本身是注入式的，也就是通过pickle序列化传输给teeu的

**Comment by Jymjiaym** [comment]
执行xgboost报错如图：
![报错截图](https://github.com/secretflow/secretflow/assets/93430715/8137f26e-959e-4898-82bd-3b6410341960)

**Comment by Jymjiaym** [comment]
好的，谢谢您啦。
