### ISSUE TITLE
执行xgb报错，帮忙给看一下。

### ISSUE THREAD

**Issue by Jymjiaym** [secretflow/secretflow#1119]
1、执行xgb报错,能否像图中这么传多个文件给teeu.
2、问题:为什么三方代码都保持一致了 但是还是报错，参考图一
3、疑问：能不能像图二这样写？
![报错](https://github.com/secretflow/secretflow/assets/93430715/1d2d9fac-edf6-41d0-b372-6c52dfc75b64)
![样例](https://github.com/secretflow/secretflow/assets/93430715/c661378a-8548-4ce8-82de-7228ba483405)

**Comment by yuki252111** [comment]
1. 图1的报错是因为TEEU没有获取到alice和bob的授权，所以在获取数据加密秘钥的时候验证失败了
2. 图2理论上是可以这么写的

**Comment by Jymjiaym** [comment]
问题1怎么获取授权？能否给个样例参考一下

**Comment by yuki252111** [comment]
授权是对TEEU设备进行授权，详细的原理可以查看文档：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/developer/design/teeu#id1    查看TEEU设备这个小节

**Comment by Jymjiaym** [comment]
> 授权是对TEEU设备进行授权，详细的原理可以查看文档：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/developer/design/teeu#id1 查看TEEU设备这个小节
老师您好，有两点疑问1.例如 a_teeu = a.to(teeu, allow_funcs=average)，如果要授权多个函数 allow_funcs该怎么写
2.如果授权的avg函数内调用了save函数，我在a.to只授权了avg函数 即可还是save也要授权？

**Comment by yuki252111** [comment]
1. allow_funcs可以是一个list，所有如果有多个函数的话，放在一个list里面即可
2. 只授权avg函数即可，底层原理其实是对pickle序列化之后的结果授权了

**Comment by Jymjiaym** [comment]
> 1. allow_funcs可以是一个list，所有如果有多个函数的话，放在一个list里面即可
> 2. 只授权avg函数即可，底层原理其实是对pickle序列化之后的结果授权了

感谢老师回复，老师和您请教个问题：目前在tee内训练了xgboost模型，数据量2万用时1.8s，数据量12万用时8.4s。数据量12万和2万训练时间差了好几倍（不包括数据加密和传输时间），如果理解为tee内普通执行python代码的话不应该相差这么多，这个是为什么？

**Comment by yuki252111** [comment]
请问下这边统计是怎么统计的呢？是统计 teeu(foo)(x, y)这个函数的耗时么？这个函数的操作里面有一个比较耗时的操作是数据的解密环节

**Comment by Jymjiaym** [comment]
> 请问下这边统计是怎么统计的呢？是统计 teeu(foo)(x, y)这个函数的耗时么？这个函数的操作里面有一个比较耗时的操作是数据的解密环节

![微信图片_20240105150000](https://github.com/secretflow/secretflow/assets/93430715/77c69b7b-0379-44d1-ba9b-b715698ff723)
是按照训练前后时间相减得出的

**Comment by yuki252111** [comment]
这个与明文计算的差距比较大么，大概明文和teeu的差距是多少呢

**Comment by Jymjiaym** [comment]
> 这个与明文计算的差距比较大么，大概明文和teeu的差距是多少呢

xgboost模型训练明文计算数据量2万用时5.7s，数据量12万用时24.7s

**Comment by yuki252111** [comment]
teeu与明文是在同一台配置的机器上的么，就是其他的环境条件都是一致的对么

**Comment by Jymjiaym** [comment]
> teeu与明文是在同一台配置的机器上的么，就是其他的环境条件都是一致的对么

teeu和明文不是一个环境，一个是本地，一个是加载机上

**Comment by yuki252111** [comment]
可以试一下在同一台机器上跑试试，可以把明文代码放到TEEU的运行机器上。这个看下来怀疑和机器的性能有一定关系

**Comment by Jymjiaym** [comment]
> 可以试一下在同一台机器上跑试试，可以把明文代码放到TEEU的运行机器上。这个看下来怀疑和机器的性能有一定关系
老师按照您所说，我将明文代码放入teeu机器内执行，两种算子都呈现出明文比密文少6-10s情况，这是什么原因造成的，麻烦老师解答下

**Comment by zhouaihui** [comment]
SGX的代码是运行在LibraryOS（Occlum）上面，相比直接在host os上运行，occlum本身就会带来一些overhead，所以比明文慢是符合预期

**Comment by Jymjiaym** [comment]
> SGX的代码是运行在LibraryOS（Occlum）上面，相比直接在host os上运行，occlum本身就会带来一些overhead，所以比明文慢是符合预期
我的明文代码也是在Occlum上执行的 以occlum run /bin/python /root/demo.py的方式，我理解的明文是不涉及alice bob 这两参与者，直接将训练代码在teeu内运行，训练集和预测集都是直接本地读取文件，然后进行训练的

**Comment by yuki252111** [comment]
TEE本身的原理会有一些overhead，比较典型的TEE的内存是加密的，数据进入cpu有个解密到明文的阶段。这个发生在计算机的内存到cpu的数据计算过程中，所以会统计在你这个统计时长的脚本里面的，属于相对比较符合预期的表现

**Comment by Jymjiaym** [comment]
> TEE本身的原理会有一些overhead，比较典型的TEE的内存是加密的，数据进入cpu有个解密到明文的阶段。这个发生在计算机的内存到cpu的数据计算过程中，所以会统计在你这个统计时长的脚本里面的，属于相对比较符合预期的表现

收到 谢谢老师
