### ISSUE TITLE
The actor died because of an error raised in its creation task

### ISSUE THREAD

**Issue by wind-and-falling-maple-leaf** [secretflow/secretflow#112]
### Issue Type

Bug

### Source

source

### Secretflow Version

secretflow        0.6.13b1

### OS Platform and Distribution

Ubuntu 20.04

### Python version

Python 3.8.10

### Bazel version

无

### GCC/Compiler version

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

### What happend and What you expected to happen.

```shell
我搭建了一个Ray集群：执行 ray status时

(base) ray2@ray2:~$ ray status
======== Autoscaler status: 2022-09-08 10:10:13.183642 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_7a31e994af56f32d62c8002fcd5f351f889c42b4ea9eae19251babf2
 1 node_17dd83ececbf1f4f1e07b0d216791a215a5be78a60ca950d451e4439
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.0/8.0 alice
 0.0/8.0 bob
 0.00/4.486 GiB memory
 0.00/2.068 GiB object_store_memory

Demands:
 (no resource demands)
```
当我想要使用spu.psi_csv('uid', input_path, output_path)时
```
>>> spu.psi_csv('uid', input_path, output_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 484, in psi_csv
    return dispatch('psi_csv', self, key, input_path, output_path, protocol, sort)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 177, in psi_csv
    return ray.get(res)
  File "/home/ray2/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray2/.local/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=3230, ip=192.168.14.148, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f9818319340>)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 125, in __init__
    self.link = link.create_brpc(desc, rank)
RuntimeError: what:
        [external/yasl/yasl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=1
stacktrace:
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9868c28ed7
#1 pybind11::cpp_function::dispatcher()+0x7f9868c150cb
#2 PyCFunction_Call+0x5f6929
```
说明：两台机器是一样的配置，其中一台是另一台克隆的
```


### Reproduction code to reproduce the issue.

```shell
sf.init(address='********:6379',_redis_password='********')
alice = sf.PYU('alice')
bob = sf.PYU('bob')
alice(lambda x : x)(2)
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

input_path = {alice: '/home/ray2/workspace/secretFlow/.data/alice.csv', bob: '/home/ray2/workspace/secretFlow/.data/bob.csv'}
output_path = {alice: '/home/ray2/workspace/secretFlow/.data/alice_psi.csv', bob: '/home/ray2/workspace/secretFlow/.data/bob_psi.csv'}
spu.psi_csv('uid', input_path, output_path)
```

**Comment by ian-huu** [comment]
可以参考一下 https://github.com/secretflow/secretflow/issues/50 ，sf.utils.testing.cluster_def 是单机测试用的，集群模式需要根据集群情况填写，参考 [SPU init](https://github.com/secretflow/secretflow/blob/beta/secretflow/device/device/spu.py#L386)

**Comment by wind-and-falling-maple-leaf** [comment]
> 可以参考一下 #50 ，sf.utils.testing.cluster_def 是单机测试用的，集群模式需要根据集群情况填写，参考 [SPU init](https://github.com/secretflow/secretflow/blob/beta/secretflow/device/device/spu.py#L386)

1.很开心您的指导，但是当我按照 #50 提供的思路实现时，它又一次重复了当前的错误，以下是错误详情。
```
>>> spu.psi_csv('uid', input_path, output_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 484, in psi_csv
    return dispatch('psi_csv', self, key, input_path, output_path, protocol, sort)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 177, in psi_csv
    return ray.get(res)
  File "/home/ray2/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray2/.local/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=8592, ip=192.168.14.149, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fdacafd9340>)
  File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 125, in __init__
    self.link = link.create_brpc(desc, rank)
RuntimeError: what:
        [external/yasl/yasl/link/transport/channel_brpc.cc:121] brpc server failed start
stacktrace:
#0 yasl::link::FactoryBrpc::CreateContext()+0x7fdb1e58e8c7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fdb1cc28ece
#2 pybind11::cpp_function::dispatcher()+0x7fdb1cc150cb
#3 PyCFunction_Call+0x5f6929
```
2.这是我这次的代码情况

```
sf.init(['alice', 'bob', 'carol'], num_cpus=8, log_to_driver=False)

import secretflow as sf
import spu
sf.init(address='192.168.14.148:6379')

device = sf.SPU({
'nodes': [
{
'party': 'alice',
'id': 'local:0',
# The address for other peers.
'address': '192.168.14.148:9327',
# The listen address of this node.
# Optional. Address will be used if listen_address is empty.
'listen_address': ''
},
{
'party': 'bob',
'id': 'local:1',
'address': '192.168.14.149:9327',
'listen_address': ''
},
],
'runtime_config': {
'protocol': spu.spu_pb2.SEMI2K,
'field': spu.spu_pb2.FM128,
'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
}
})

alice = sf.PYU('alice')
bob = sf.PYU('bob')
spu = sf.SPU(device.cluster_def)

input_path = {alice: '/home/ray2/workspace/secretFlow/.data/alice.csv', bob: '/home/ray2/workspace/secretFlow/.data/bob.csv'}
output_path = {alice: '/home/ray2/workspace/secretFlow/.data/alice_psi.csv', bob: '/home/ray2/workspace/secretFlow/.data/bob_psi.csv'}
spu.psi_csv('uid', input_path, output_path)
```
3.这是ray集群的运行情况
![](https://user-images.githubusercontent.com/49154306/189280890-e57158f4-9fc7-45b7-ab99-0fa31c08efe7.jpg)

**Comment by wind-and-falling-maple-leaf** [comment]
> > 可以参考一下 #50 ，sf.utils.testing.cluster_def 是单机测试用的，集群模式需要根据集群情况填写，参考 [SPU init](https://github.com/secretflow/secretflow/blob/beta/secretflow/device/device/spu.py#L386)
> 
> 1.很开心您的指导，但是当我按照 #50 提供的思路实现时，它又一次重复了当前的错误，以下是错误详情。
> 
> ```
> >>> spu.psi_csv('uid', input_path, output_path)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 484, in psi_csv
>     return dispatch('psi_csv', self, key, input_path, output_path, protocol, sort)
>   File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
>     return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
>   File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
>     return self._ops[device_type][name](*args, **kwargs)
>   File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 177, in psi_csv
>     return ray.get(res)
>   File "/home/ray2/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ray2/.local/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
>     raise value
> ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=8592, ip=192.168.14.149, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fdacafd9340>)
>   File "/home/ray2/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 125, in __init__
>     self.link = link.create_brpc(desc, rank)
> RuntimeError: what:
>         [external/yasl/yasl/link/transport/channel_brpc.cc:121] brpc server failed start
> stacktrace:
> #0 yasl::link::FactoryBrpc::CreateContext()+0x7fdb1e58e8c7
> #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fdb1cc28ece
> #2 pybind11::cpp_function::dispatcher()+0x7fdb1cc150cb
> #3 PyCFunction_Call+0x5f6929
> ```
> 
> 2.这是我这次的代码情况
> 
> ```
> sf.init(['alice', 'bob', 'carol'], num_cpus=8, log_to_driver=False)
> 
> import secretflow as sf
> import spu
> sf.init(address='192.168.14.148:6379')
> 
> device = sf.SPU({
> 'nodes': [
> {
> 'party': 'alice',
> 'id': 'local:0',
> # The address for other peers.
> 'address': '192.168.14.148:9327',
> # The listen address of this node.
> # Optional. Address will be used if listen_address is empty.
> 'listen_address': ''
> },
> {
> 'party': 'bob',
> 'id': 'local:1',
> 'address': '192.168.14.149:9327',
> 'listen_address': ''
> },
> ],
> 'runtime_config': {
> 'protocol': spu.spu_pb2.SEMI2K,
> 'field': spu.spu_pb2.FM128,
> 'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
> }
> })
> 
> alice = sf.PYU('alice')
> bob = sf.PYU('bob')
> spu = sf.SPU(device.cluster_def)
> 
> input_path = {alice: '/home/ray2/workspace/secretFlow/.data/alice.csv', bob: '/home/ray2/workspace/secretFlow/.data/bob.csv'}
> output_path = {alice: '/home/ray2/workspace/secretFlow/.data/alice_psi.csv', bob: '/home/ray2/workspace/secretFlow/.data/bob_psi.csv'}
> spu.psi_csv('uid', input_path, output_path)
> ```
> 
> 3.这是ray集群的运行情况 ![](https://user-images.githubusercontent.com/49154306/189280890-e57158f4-9fc7-45b7-ab99-0fa31c08efe7.jpg)

代码写错了
应该是
```
device.psi_csv('uid', input_path, output_path)
```
