### ISSUE TITLE
GPU支持的docker版本无法加载Transform[flax]库

### ISSUE THREAD

**Issue by shibo141** [secretflow/secretflow#1121]
### Issue Type

Bug

### Source

source

### Secretflow Version

SecretFlow: 0.8.2b3

### OS Platform and Distribution

Linux Ubuntu20.04 Server Docker

### Python version

3.8.10

### What happend and What you expected to happen.

```shell
问题1：
GPU支持的版本无法加载Transform[flax]库，查询报错后发现是JAX版本过低
升级JAX版本后无法使用GPU，在https://storage.googleapis.com/jax-releases/jax_cuda_releases.html查找对应JAX的和JAXlib的对应版本安装后其实cudnn版本冲突，似乎是8.5的cudnn，但似乎没有该cudnn对应的jaxgpu支持版本
我在docker中该使用JAX的哪个版本既能延续GPU支持，又能使用Transform[flax]库？

问题2：
GPT2的推理是否支持GPU加速？ABY3支持的隐私推理GPT2能否进行GPU加速？确认一下CHEETAH似乎并不支持GPT2的例子，我尝试后SPU报错似乎是底层的问题
```

### Reproduction code to reproduce the issue.

```shell
问题1：
# !pip install transformers[flax]
# !pip install --upgrade jax jaxlib
import sys

# !{sys.executable} -m pip install transformers[flax]
from transformers import AutoTokenizer, FlaxGPT2LMHeadModel, GPT2Config

tokenizer = AutoTokenizer.from_pretrained("gpt2")
pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
def text_generation(input_ids, params):
    config = GPT2Config()
    model = FlaxGPT2LMHeadModel(config=config)

    for _ in range(10):
        outputs = model(input_ids=input_ids, params=params)
        next_token_logits = outputs[0][0, -1, :]
        next_token = jnp.argmax(next_token_logits)
        input_ids = jnp.concatenate([input_ids, jnp.array([[next_token]])], axis=1)
    return input_ids
import jax.numpy as jnp

inputs_ids = tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')
outputs_ids = text_generation(inputs_ids, pretrained_model.params)

print('-' * 65 + '\nRun on CPU:\n' + '-' * 65)
print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))
print('-' * 65)

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

-----------------------------------------------------------------
Run on CPU:
-----------------------------------------------------------------
I enjoy walking with my cute dog, but I'm not sure if I'll ever
-----------------------------------------------------------------
```

**Comment by ian-huu** [comment]
目前 SPU 还不支持 GPU 加速，所以如果要用 SPU 的话可能暂时不用考虑 GPU 的问题

**Comment by anakinxc** [comment]
Hi @shibo141 

SPU 发布的 pip 包是没有开启 GPU 加速的，如果需要测试得从源码编译

还有 Cheetah 的问题可以提供一下日志吗？

**Comment by shibo141** [comment]
@ian-huu 但是似乎使用docker版本无法运行GPT2的例子，因为import transform会报错。解决的办法是升级jax到4.0.12以上的版本，升级后jax无法用GPU。而且我并不清楚docker中自带的cudnn值为多少，似乎并非8.6.0.163，似乎是8.5开头的一个包，导致我找不到合适的jax和jaxlib版本能够让jax使用gpu加速。也就是说问题是**我无法顺利运行GPT2隐私推理例子的同时利用GPU使用jax修改微调运行我的模型，而只能使用纯CPU进行这个过程，这会相当缓慢**，除非我使用完全独立的环境比如在一个docker中构建我的模型，在另一个docker中测试模型的spu隐私推理。
@anakinxc 好的，下面是我的代码
`from transformers import AutoTokenizer, FlaxGPT2LMHeadModel, GPT2Config

tokenizer = AutoTokenizer.from_pretrained("gpt2")
pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
def text_generation(input_ids, params):
    config = GPT2Config()
    model = FlaxGPT2LMHeadModel(config=config)

    for _ in range(10):
        outputs = model(input_ids=input_ids, params=params)
        next_token_logits = outputs[0][0, -1, :]
        next_token = jnp.argmax(next_token_logits)
        input_ids = jnp.concatenate([input_ids, jnp.array([[next_token]])], axis=1)
    return input_ids
import jax.numpy as jnp

inputs_ids = tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')
outputs_ids = text_generation(inputs_ids, pretrained_model.params)

print('-' * 65 + '\nRun on CPU:\n' + '-' * 65)
print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))
print('-' * 65)`
`import spu
import secretflow as sf

# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')

cheetah_config = sf.utils.testing.cluster_def(
    parties=['alice','bob'],
    runtime_config={
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM64,
    },
)

spu = sf.SPU(cheetah_config )

def get_model_params():
    pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
    return pretrained_model.params


def get_token_ids():
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    return tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')


model_params = alice(get_model_params)()
input_token_ids = bob(get_token_ids)()

device = spu
model_params_, input_token_ids_ = model_params.to(device), input_token_ids.to(device)

output_token_ids = spu(text_generation)(input_token_ids_, model_params_)`
`outputs_ids = sf.reveal(output_token_ids)
print('-' * 65 + '\nRun on SPU:\n' + '-' * 65)
print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))
print('-' * 65)`
### **实际上报错信息只有第三段代码产生，也就是调用sf.reveal的时候
我相较于官方给出的代码仅仅是设置使用了CHEETAH协议进行推理**cheetah_config** 部分
打印出来的报错日志如下：**
2024-01-08 06:57:12,387	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=3973, ip=172.21.5.114, repr=SPURuntime(device_id=None, party=bob))
  File "/home/bo/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 504, in run
    self.runtime.run(executable)
  File "/home/bo/anaconda3/envs/sf/lib/python3.8/site-packages/spu/api.py", line 44, in run
    return self._vm.Run(executable.SerializeToString())
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:411] Get data timeout, key=root-1-1:P2P-327:0->1
stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7f59a6eef547
#1 yacl::link::Context::Recv()+0x7f59a6ef0c72
#2 yacl::crypto::(anonymous namespace)::GenSyncedSeed()+0x7f59a65022f1
#3 yacl::crypto::FerretOtExtSend_cheetah()+0x7f59a6503560
#4 spu::mpc::cheetah::YaclFerretOTeAdapter::Bootstrap()+0x7f59a64e2d17
#5 spu::mpc::cheetah::YaclFerretOTeAdapter::rcot()+0x7f59a64e4ab3
#6 spu::mpc::cheetah::YaclFerretOt::Impl::SendRandMsgRandChoice()+0x7f59a64e07ce
#7 spu::mpc::cheetah::YaclFerretOt::Impl::SendRandMsgRandChoice<>()+0x7f59a64e0d08
#8 spu::mpc::cheetah::BasicOTProtocols::AndTriple()+0x7f59a64797e1
#9 spu::mpc::cheetah::BasicOTProtocols::BitwiseAnd()+0x7f59a647ab83
#10 spu::mpc::cheetah::EqualProtocol::DoCompute()+0x7f59a64579a7
#11 spu::mpc::cheetah::EqualProtocol::Compute()+0x7f59a6459921
#12 std::_Function_handler<>::_M_invoke()+0x7f59a641a390
#13 std::__future_base::_State_baseV2::_M_do_set()+0x7f59a619665e
#14 __pthread_once_slow+0x7f5a41a514df
(SPURuntime(device_id=None, party=alice) pid=3969) 2024-01-08 06:57:12.348 [error] [channel.cc:operator():119] SendThread error [external/yacl/yacl/link/transport/channel.cc:634] Throttle window wait timeout
2024-01-08 06:57:12,662	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffdb59823ee942c6d65a50773601000000 Worker ID: 7fbed557ecc5f970d496a346ccbc25cf02f1193c4a691d5d1d38837e Node ID: 5f1ca165ad63ce1d2313d1ad22aa49a3cbe88ad40f076d57b9d9fe63 Worker IP address: 172.21.5.114 Worker port: 39217 Worker PID: 3969 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
---------------------------------------------------------------------------
RayActorError                             Traceback (most recent call last)
Cell In[3], line 1
----> 1 outputs_ids = sf.reveal(output_token_ids)
      2 print('-' * 65 + '\nRun on SPU:\n' + '-' * 65)
      3 print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py:153, in reveal(func_or_object, heu_encoder)
    149 elif isinstance(x, SPUObject):
    150     assert isinstance(
    151         x.shares_name[0], (ray.ObjectRef, fed.FedObject)
    152     ), f"shares_name in spu obj should be ObjectRef or FedObject, but got {type(x.shares_name[0])} "
--> 153     info, shares_chunk = x.device.outfeed_shares(x.shares_name)
    154     all_spu_chunks_count.append(len(shares_chunk))
    155     all_object_refs.append(info)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py:1903, in SPU.outfeed_shares(self, shares_name)
   1895 def outfeed_shares(
   1896     self, shares_name: List[Union[ray.ObjectRef, fed.FedObject]]
   1897 ) -> Tuple[
   1898     Union[ray.ObjectRef, fed.FedObject],
   1899     List[Union[ray.ObjectRef, fed.FedObject]],
   1900 ]:
   1901     assert len(shares_name) == len(self.actors)
-> 1903     shares_chunk_count = sfd.get(
   1904         (next(iter(self.actors.values()))).outfeed_shares_chunk_count.remote(
   1905             shares_name[0]
   1906         )
   1907     )
   1909     ret = []
   1910     for i, actor in enumerate(self.actors.values()):

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:158, in get(object_refs)
    156     return fed.get(object_refs)
    157 elif get_distribution_mode() == DISTRIBUTION_MODE.SIMULATION:
--> 158     return ray.get(object_refs)
    159 elif get_distribution_mode() == DISTRIBUTION_MODE.DEBUG:
    160     return object_refs

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py:2311, in get(object_refs, timeout)
   2309             raise value.as_instanceof_cause()
   2310         else:
-> 2311             raise value
   2313 if is_individual_id:
   2314     values = values[0]

RayActorError: The actor died unexpectedly before finishing this task.
	class_name: SPURuntime
	actor_id: db59823ee942c6d65a50773601000000
	pid: 3969
	namespace: 523b1b9f-1ba6-40da-a742-590727a6ea09
	ip: 172.21.5.114
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

2024-01-08 06:57:17,390	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=3973, ip=172.21.5.114, repr=SPURuntime(device_id=None, party=bob))
  File "/home/bo/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 504, in run
    self.runtime.run(executable)
  File "/home/bo/anaconda3/envs/sf/lib/python3.8/site-packages/spu/api.py", line 44, in run
    return self._vm.Run(executable.SerializeToString())
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:411] Get data timeout, key=root-1-1:P2P-327:0->1
stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7f59a6eef547
#1 yacl::link::Context::Recv()+0x7f59a6ef0c72
#2 yacl::crypto::(anonymous namespace)::GenSyncedSeed()+0x7f59a65022f1
#3 yacl::crypto::FerretOtExtSend_cheetah()+0x7f59a6503560
#4 spu::mpc::cheetah::YaclFerretOTeAdapter::Bootstrap()+0x7f59a64e2d17
#5 spu::mpc::cheetah::YaclFerretOTeAdapter::rcot()+0x7f59a64e4ab3
#6 spu::mpc::cheetah::YaclFerretOt::Impl::SendRandMsgRandChoice()+0x7f59a64e07ce
#7 spu::mpc::cheetah::YaclFerretOt::Impl::SendRandMsgRandChoice<>()+0x7f59a64e0d08
#8 spu::mpc::cheetah::BasicOTProtocols::AndTriple()+0x7f59a64797e1
#9 spu::mpc::cheetah::BasicOTProtocols::BitwiseAnd()+0x7f59a647ab83
#10 spu::mpc::cheetah::EqualProtocol::DoCompute()+0x7f59a64579a7
#11 spu::mpc::cheetah::EqualProtocol::Compute()+0x7f59a6459921
#12 std::_Function_handler<>::_M_invoke()+0x7f59a641a390
#13 std::__future_base::_State_baseV2::_M_do_set()+0x7f59a619665e
#14 __pthread_once_slow+0x7f5a41a514df

**Comment by tpppppub** [comment]
1. 建议使用最新的 SecretFlow 版本进行实验，0.8.2b3 版本之后修复了很多问题

**Comment by shibo141** [comment]
@tpppppub 我最近测试过最新secretflow版本的dev14，cheetah协议仍然无法顺利运行包括GPT2例子和一个我自己加载的hugingface模型安全推理的例子 但是同样的测试在ABY3协议上都能顺利通过
目前我的服务器配置是64GB内存，运行cheetah协议进行GPT2测试时，报错日志仍然如前文所示，只是会发生在运行`sf.reveal()后`且巅峰内存占用大约40gb，确定并非内存不足的问题

**Comment by tpppppub** [comment]
把
```python
spu = sf.SPU(cheetah_config)
``` 
改成
```python
link_desc = {}
link_desc['throttle_window_size'] = 0
spu = sf.SPU(cheetah_config,link_desc)
```
再试试
