### ISSUE TITLE
测试使用SPU时遇到问题

### ISSUE THREAD

**Issue by ShallMate** [secretflow/secretflow#1123]
我按照文档对SPU进行一个小测试。我运行了一个简单的代码，但是很奇怪的是貌似并没有work。终端只显示了如下的信息，并没有打印reveal的值，即好像并没有运行到后面去。同时不管我做什么操作貌似都不会生效。终端没有给出更多的报错信息，因此我不知道是我哪一步做错了。

我在这里给出了我的代码和我的终端输出。
终端只打印了
2024-01-10 20:20:43,420	INFO worker.py:1538 -- Started a local Ray instance.
这实在让我疑惑。
![image](https://github.com/secretflow/secretflow/assets/25976948/45e79271-b555-44e1-b537-90821690fb26)

![image](https://github.com/secretflow/secretflow/assets/25976948/276a85be-5107-477d-a468-ffe27249e05f)

**Comment by zhouaihui** [comment]
hi, @ShallMate , 可以打开logging再跑一下，在init添加参数`logging_level='debug'`

**Comment by ShallMate** [comment]
@zhouaihui 还是看不到额外的信息

**Comment by Chrisdehe** [comment]
Secretflow和SPU的版本是多少呢？

**Comment by ShallMate** [comment]
![image](https://github.com/secretflow/secretflow/assets/25976948/61ad52c0-89ac-4e9f-9a9c-ee9680754f01)
您好，分别是0.6.0b0和1.3.0
@Chrisdehe

**Comment by ShallMate** [comment]
@Chrisdehe 非常感谢。我会尝试一下的。我刚刚用docker启动secretflow就是可以的。请问我该如何打印上述代码的通信量呢？

**Comment by Chrisdehe** [comment]
[SPU config](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config) 里有 enable_pphlo_profile 和 enable_hal_profile 两个 field，开启以后 spu 会打印出一些 profile 的信息，里面包含了计算时间和数据通信量

**Comment by ShallMate** [comment]
@Chrisdehe 
![image](https://github.com/secretflow/secretflow/assets/25976948/b9ee5831-1514-4041-af14-102d9b801923)
为什么通信量都是0呢？

**Comment by tpppppub** [comment]
这里统计的信息是密态计算阶段的通信量，因为你的程序调用的 mpc 算子 `add_aa`、`add_ap` 这些都是可以本地运算的，所以不会有通信

**Comment by ShallMate** [comment]
哦哦，对哈。我明白了。我用乘法试了一下确实产生了通信量，非常感谢

**Comment by ShallMate** [comment]
哦哦，对哈。我明白了。我用乘法试了一下确实产生了通信量，非常感谢~。
@tpppppub

**Comment by ShallMate** [comment]
![image](https://github.com/secretflow/secretflow/assets/25976948/25b32f8e-39bb-44b4-903a-df6f3b616237)
您好，如果是PSI协议的话，我又该如何测试通信量和计算开销呢。 enable_pphlo_profile 和 enable_hal_profile 貌似在这里不起作用？ @Chrisdehe

**Comment by Chrisdehe** [comment]
出现了什么问题呢？

**Comment by ShallMate** [comment]
![image](https://github.com/secretflow/secretflow/assets/25976948/7273a9e5-4aa0-424c-9201-ee0154e57b82)
hen'yi'h如果使用cluster_def(
parties=['alice', 'bob'],
runtime_config={
'enable_pphlo_profile': True,
'enable_hal_profile':True,
},
)
，那么会出现上述的问题。很疑惑，我运行BC22是和ABY3没关系的吧。是我哪里调用出错了吗？ @Chrisdehe

**Comment by Chrisdehe** [comment]
两个问题：
1、runtime_config 没写 protocol
2、输出通信量的那个参数在PSI协议中无法使用，因为PSI实际上不走SPU，目前PSI无法查看输出通信量等操作。

**Comment by 6fj** [comment]
> ![image](https://private-user-images.githubusercontent.com/25976948/296169914-7273a9e5-4aa0-424c-9201-ee0154e57b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTE3MzksIm5iZiI6MTcwNTA1MTQzOSwicGF0aCI6Ii8yNTk3Njk0OC8yOTYxNjk5MTQtNzI3M2E5ZTUtNGFhMC00MjRjLTkyMDEtZWUwMTU0ZTU3YjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA5MjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MjJlZmE0OTQwMjgwMTA3ZTAzY2NjYjVhMzY4OTkyZmQ2Mjc1MGY3YTBjODkxNDEyNjVkY2M4ODY0M2UyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IfeVi22q5DF6XNFz3LCBC-R8yU6MggNYsY52LLGqhkU) hen'yi'h如果使用cluster_def( parties=['alice', 'bob'], runtime_config={ 'enable_pphlo_profile': True, 'enable_hal_profile':True, }, ) ，那么会出现上述的问题。很疑惑，我运行BC22是和ABY3没关系的吧。是我哪里调用出错了吗？ @Chrisdehe
> 
> 即，只修改上面的代码的spu那行为： spu = sf.SPU(sf.utils.testing.cluster_def(parties=['alice', 'bob'],runtime_config={'enable_pphlo_profile': True,'enable_hal_profile':True}))
> 
> 会出现终端中的error

**Comment by 6fj** [comment]
hi @ShallMate 

目前psi仍然和spu捆绑在一起，psi会使用spu产生的context，因此需要你这边声明的spu只包含两方。

另外，你可以使用新的psi_v2接口来启用RR22。api请查阅：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow#secretflow.SPU.psi_v2

**Comment by ShallMate** [comment]
@6fj 现在是没办法查看PSI协议的通信量的是吗？

**Comment by 6fj** [comment]
keys 必须以map的方式题咏，比如

```
keys={"alice":["id0","id1"], "bob":["id0","id1"]}
```

**Comment by ShallMate** [comment]
![image](https://github.com/secretflow/secretflow/assets/25976948/20a334e4-4838-48ae-a642-ff8f51c2c4f9)
![image](https://github.com/secretflow/secretflow/assets/25976948/1811fc92-f84a-4aa8-af25-d01b44ae115d)
还是不能调用呢 @6fj

**Comment by 6fj** [comment]
key是string，不是PYU

**Comment by ShallMate** [comment]
不好意思，没有明白您的意思。你开始举的例子是keys={"alice":["id0","id1"], "bob":["id0","id1"]}。我这里求交的ID是“uid”，于是我把“id0”和“id1”换成了“uid”。请问您指的string是什么意思。 @6fj

**Comment by 6fj** [comment]
```
input_path = {"alice": "...", "bob": "..."}
```
input_path / out_path 这些dict 的 keys 是 sting 而不是 PYU

**Comment by ShallMate** [comment]
哦哦，我明白了，代码成功运行了。非常感谢。我想问一下。虽然现在不支持直接查看通信量。但是我有什么方法能够得到通信量吗？ @6fj

**Comment by cho-chem** [comment]
Hi @ShallMate 如果你在 Kuscia 里面跑 Secretflow 任务，Kuscia 的 envoy 网关会统计一些流量数据，可以在 Kuscia 容器中通过命令 `curl http://127.0.0.1:10000/stats` 查看。
