### ISSUE TITLE
多方 MPC 训练后，其中一方使用test数据推理标签

### ISSUE THREAD

**Issue by hacker-jerry** [secretflow/secretflow#1127]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.14.0

### OS Platform and Distribution

ubuntu

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
您好，我在训练sgb模型时，使用了 3 方标签，但是预测数据的标签全部存在 c 方，请问这种情况下是用什么函数保存模型，加载模型，并推理结果呢？
```

### Reproduction code to reproduce the issue.

```shell
/
```

**Comment by da-niao-dan** [comment]
你好，参考https://github.com/secretflow/secretflow/blob/main/secretflow/ml/boost/sgb_v/complete_model.py

**Comment by Chrisdehe** [comment]
@hacker-jerry 我先关闭了哈，有问题随时开启
