### ISSUE TITLE
ARM architecture is not supported by kuscia currently

### ISSUE THREAD

**Issue by HavAnIdea** [secretflow/secretflow#1131]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.1.0b0

### OS Platform and Distribution

macos

### Python version

3.11

### What happend and What you expected to happen.

```shell
macos m1 install error 
ARM architecture is not supported by kuscia currently
```

### Reproduction code to reproduce the issue.

```shell
macos m1 install error 
ARM architecture is not supported by kuscia currently
```

**Comment by Chrisdehe** [comment]
@HavAnIdea ，目前kuscia还并不支持Arm架构，也暂无排期，如果有兴趣的话您这边是否愿意贡献相关代码到仓库中？（我们可出方案）如果愿意的话，我们可以新增一个kuscia支持arm的OSCP任务。

**Comment by panmason** [comment]
> ### Issue Type
> Bug
> 
> ### Source
> binary
> 
> ### Secretflow Version
> 0.1.0b0
> 
> ### OS Platform and Distribution
> macos
> 
> ### Python version
> 3.11
> 
> ### Bazel version
> _No response_
> 
> ### GCC/Compiler version
> _No response_
> 
> ### What happend and What you expected to happen.
> ```shell
> macos m1 install error 
> ARM architecture is not supported by kuscia currently
> ```
> 
> ### Reproduction code to reproduce the issue.
> ```shell
> macos m1 install error 
> ARM architecture is not supported by kuscia currently
> ```

我使用的M3，目前在构建镜像，基础镜像从ubuntu 得arm版本构建，目前是卡在了 secretflow上，他们版本依赖上传的有问题，对应secretflow-ray依赖没有上传或代码仓库没有开源，在M3上依赖安装失败，没有办法进行镜像构建，我也在跟他们沟通，目前为止，官方还没有理解我的意思，也没有提供一个有效的解决办法

**Comment by Chrisdehe** [comment]
@panmason
你目前已经有官方的ray，这个会跟secretflow-ray有依赖冲突
我已经在你提的issue中给到具体解决方法：
1、SecretFlow要求安装secretflow-ray （2.2.0）
2、请不要同时安装官方ray，会产生冲突。如果有安装，请确保先卸载ray以及secretflow-ray，然后重新安装secretflow-ray

请问是否有尝试呢？

**Comment by panmason** [comment]
> @panmason 你目前已经有官方的ray，这个会跟secretflow-ray有依赖冲突 我已经在你提的issue中给到具体解决方法： 1、SecretFlow要求安装secretflow-ray （2.2.0） 2、请不要同时安装官方ray，会产生冲突。如果有安装，请确保先卸载ray以及secretflow-ray，然后重新安装secretflow-ray
> 
> 请问是否有尝试呢？

我已经按照你的方案，卸载了ray，安装的时候依旧报错，也就是说你们没有给出一个可用的解决方案

**Comment by Chrisdehe** [comment]
已更新回复哈，辛苦在你提的issue中继续
https://github.com/secretflow/secretflow/issues/1135
