### ISSUE TITLE
请问隐语多参与方的log从哪里获取？能设置路径吗？

### ISSUE THREAD

**Issue by hacker-jerry** [secretflow/secretflow#1132]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.13.0

### OS Platform and Distribution

ubuntu

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
请问训练过程log能否设置路径？
```

### Reproduction code to reproduce the issue.

```shell
/
```

**Comment by zhouaihui** [comment]
hi, @hacker-jerry ，你是在问哪个训练算法？

**Comment by da-niao-dan** [comment]
sgb 算法没有用MPC，所以暂时不存在SPU 的log

**Comment by da-niao-dan** [comment]
暂不支持

**Comment by da-niao-dan** [comment]
terminal 中会有， 可以保存terminal log 来保存log。
比如 `python sgb.py > temp.txt 2>&1 &` 这样
