### ISSUE TITLE
SecretPad P2P部署

### ISSUE THREAD

**Issue by LeoneChen** [secretflow/secretflow#1133]
[这里](https://www.secretflow.org.cn/docs/quickstart/dbd670doqfio1puq#hfHFD)说了P2P部署模式

![1705824070163](https://github.com/secretflow/secretflow/assets/35480440/e08af803-772c-4927-9593-603fcd7ef732)

但是我在[本地部署](https://www.secretflow.org.cn/deployment)没找到支持p2p部署的安装包，看起来只支持中心化部署

![1705825233022](https://github.com/secretflow/secretflow/assets/35480440/943c3537-5193-4ce9-b805-ce30b0fa3f35)

**Comment by CodePorterL** [comment]
你好 感谢提问 目前secretpad是支持p2p模式的，但是在脚本中没有说明，下个版本中会一起同步出去。
下面是参数说明~
sh install.sh p2p -n alice -s 8098 -g 8082 -k 8081 -p 8080 -c /root/p2p/alice
-n alice    是节点名称，用户自定义 最多 63 个字符
                只能包含小写字母、数字，以及 '-'
                必须以字母数字开头
                必须以字母数字结尾

-s 8098，secretpad p2p web端口号
-g 8082，kuscia p2p 节点 API HTTP 端口
-k 8081，kuscia p2p 节点 API GRPC 端口
-p 8080，kuscia p2p 节点的gateway端口号
-c /root/p2p/alice  证书挂载路径

**Comment by LeoneChen** [comment]
ok，感谢感谢

**Comment by LeoneChen** [comment]
我在部署时又遇到另一个问题 `./install.sh p2p -n ironman`
```
Found the secretflow image 'secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109' on host
+ log 'Start importing image '\''secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109'\'' Please be patient...'
+ local 'log_content=Start importing image '\''secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109'\'' Please be patient...'
+ echo -e '\033[0;32mStart importing image '\''secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109'\'' Please be patient...\033[0m'
Start importing image 'secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109' Please be patient...
+ local image_id
++ docker images --filter=reference=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109 --format '{{.ID}}'
+ image_id=5695d3fa24cb
+ local image_tar
++ echo secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109
++ sed 's/\//_/g'
+ image_tar=/tmp/secretflow-registry.cn-hangzhou.cr.aliyuncs.com_secretflow_secretflow-lite-anolis8:1.3.0.dev20231109.5695d3fa24cb.tar
+ '[' '!' -e /tmp/secretflow-registry.cn-hangzhou.cr.aliyuncs.com_secretflow_secretflow-lite-anolis8:1.3.0.dev20231109.5695d3fa24cb.tar ']'
+ docker save secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109 -o /tmp/secretflow-registry.cn-hangzhou.cr.aliyuncs.com_secretflow_secretflow-lite-anolis8:1.3.0.dev20231109.5695d3fa24cb.tar
+ docker exec -it chenliheng-kuscia-autonomy-ironman ctr -a=/home/kuscia/containerd/run/containerd.sock -n=k8s.io images import /tmp/secretflow-registry.cn-hangzhou.cr.aliyuncs.com_secretflow_secretflow-lite-anolis8:1.3.0.dev20231109.5695d3fa24cb.tar
unpacking secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.3.0.dev20231109 (sha256:d6bfb2fc38fc54bf8194e224cd8cd2fa0061812c66646356e5612080aee26dc4)...INFO[0033] apply failure, attempting cleanup             error="wrong diff id calculated on extraction \"sha256:51d8a7b96057b0d0cd6ca72a3da8b594541d43c389300d5fe3ad30680e2ae091\"" key="extract-22418527-xH1N sha256:8dff2b73bdd5672e410af214c174ade52d0b590e6a8662eb71741086c783f6cc"
ctr: wrong diff id calculated on extraction "sha256:51d8a7b96057b0d0cd6ca72a3da8b594541d43c389300d5fe3ad30680e2ae091"
```
完成的log如文件里所示
[log.txt](https://github.com/secretflow/secretflow/files/14010068/log.txt)

**Comment by LeoneChen** [comment]
前面的基础上再运行一遍`./install.sh p2p -n alice -s 8098 -g 8082 -k 8081 -p 8080`能安装成功，但前面的问题似乎并没有解决，而是第二轮`crictl inspecti`返回了true使得提早return。
![1705930395908](https://github.com/secretflow/secretflow/assets/35480440/7bd0c784-709e-455c-871d-d73772042152)

（如前所述不知道是否正确地）安装后使用过程中，在添加节点的过程中会发现节点不可用，而我其实已经在那台机子也（如前所述不知道是否正确地）安装了
![1705930506640](https://github.com/secretflow/secretflow/assets/35480440/41bedf1b-ec81-4974-84e2-4a228d5b21cd)

此外，最新的`install.sh`脚本没有对p2p部分选项设置默认值。`start_p2p.sh`脚本变量写错了（不太重要）
![1705930641764](https://github.com/secretflow/secretflow/assets/35480440/02e8f09f-2be5-4ce5-99c0-ddb1d5078a1e)

**Comment by CodePorterL** [comment]
> 前面的基础上再运行一遍`./install.sh p2p -n alice -s 8098 -g 8082 -k 8081 -p 8080`能安装成功，但前面的问题似乎并没有解决，而是第二轮`crictl inspecti`返回了true使得提早return。 ![1705930395908](https://private-user-images.githubusercontent.com/35480440/298601808-7bd0c784-709e-455c-871d-d73772042152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzY3MjIsIm5iZiI6MTcwNTk3NjQyMiwicGF0aCI6Ii8zNTQ4MDQ0MC8yOTg2MDE4MDgtN2JkMGM3ODQtNzA5ZS00NTVjLTg3MWQtZDczNzcyMDQyMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAyMjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOTZjYjU3Y2I1OGNiODM5OWJhMjUyNzU5MjU1ZGUwMGI2ODEzN2VhNzZmNmEyY2VlNTlkMDFiN2QxN2E4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yfotHwBHXdem0imlWVENZaO0iGJ9Bi0Y6u5zso-vdaQ)
> 
> （如前所述不知道是否正确地）安装后使用过程中，在添加节点的过程中会发现节点不可用，而我其实已经在那台机子也（如前所述不知道是否正确地）安装了 ![1705930506640](https://private-user-images.githubusercontent.com/35480440/298602333-41bedf1b-ec81-4974-84e2-4a228d5b21cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzY3MjIsIm5iZiI6MTcwNTk3NjQyMiwicGF0aCI6Ii8zNTQ4MDQ0MC8yOTg2MDIzMzMtNDFiZWRmMWItZWM4MS00OTc0LTg0ZTItNGEyMjhkNWIyMWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAyMjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZDhkODdhMzU5N2Y2YzY1ZDA5MzAwNzY0OTRiNGNjOTY5NzQ5OTJhOGJhZjAxNGRhODdmMDYyNzA4OTY1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.42Sxwmksel2om_O9-Fy62X2iyetX5f19VowD8TBfdBE)
> 
> 此外，最新的`install.sh`脚本没有对p2p部分选项设置默认值。`start_p2p.sh`脚本变量写错了（不太重要） ![1705930641764](https://private-user-images.githubusercontent.com/35480440/298602909-02e8f09f-2be5-4ce5-99c0-ddb1d5078a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzY3MjIsIm5iZiI6MTcwNTk3NjQyMiwicGF0aCI6Ii8zNTQ4MDQ0MC8yOTg2MDI5MDktMDJlOGYwOWYtMmJlNS00Y2U1LTk5YzAtZGRiMWQ1MDc4YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAyMjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NThhYjdlNGQ0ZTk0NzE2NjA3NGEyM2ZjOGNhNzk0Y2FhOTE0ZjQ5NjgxNmMxYjMzMzkyYzkwZjAwNjdjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12mPA2wX9VF6RVbJLk_65wc1v41l0L2nWTVmrCP6zfA)
你好 
第一个问题看起来可能是因为磁盘上存在镜像缓存。
如果是在同一目录下，解压allinone包时，建议删除之前已经解压的secretflow包，否则可能会导致镜像加载错误等问题。
![image](https://github.com/secretflow/secretflow/assets/91072507/7cdfd3bc-fd6e-4bb8-ab91-ea5ef53b77fe)
第二个问题需要docker ps看一下docker镜像暴露的端口，如果是上述命令安装的，那么看起来对方的端口应该填写8080端口。
![image](https://github.com/secretflow/secretflow/assets/91072507/f331fbef-3a3a-4181-8a40-bd7a757a9780)
第三个脚本问题感谢提醒~~

**Comment by LeoneChen** [comment]
第一个问题中，我下载的是`secretflow-allinone-package-latest.tar.gz`

删除了之前解压的`secretflow-allinone-package`。

同时我还`uninstall.sh`了之前的安装

删除了`/home/chenliheng/kuscia`和`/tmp/secretflow-registry.cn-hangzhou.cr.aliyuncs.com_secretflow_secretflow-lite-anolis8:1.3.0.dev20231109.5695d3fa24cb.tar`

`for i in $(docker images|grep secretpad|awk '{print $1":"$2}'); do; docker rmi $i;done`删除了所有secretpad镜像

`for i in $(docker images|grep secretflow|awk '{print $1":"$2}'); do; docker rmi $i;done`删除了所有secretflow镜像

感觉应该都清干净了后还是有这第一个问题

**Comment by cho-chem** [comment]
Hi @LeoneChen 缓存的镜像是放在 docker volume 中的，可以使用命令 `docker volume ls | grep containerd` 看到，如果还有上述问题可以尝试将 volume 清理掉再安装 `docker volume rm xxx`

**Comment by LeoneChen** [comment]
`uninstall.sh`的时候已经删除volume了，您那边的机器上不会出现我这里的问题吗？

**Comment by yushiqie** [comment]
> `uninstall.sh`的时候已经删除volume了，您那边的机器上不会出现我这里的问题吗？我刚刚又去试了下，并确认是已经清理掉volume了，但问题依旧

请问你的机器配置，以及docker 版本是多少啊

**Comment by LeoneChen** [comment]
`uname -a`
```shell
Linux Ironman 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

`docker --version`
```shell
Docker version 25.0.0, build e758fe5
```

`lsb_release -a`
```shell
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by yushiqie** [comment]
感谢问题反馈，这是最新 docker 25.X 引发的问题。目前我们适配过的 docker 最高版本是 24.X， 可以尝试用这个版本进行部署吗。

**Comment by LeoneChen** [comment]
okok，感谢

**Comment by yushiqie** [comment]
这是 docker 25.0.0 引入的bug，docker 将在 25.0.1 修复(还未发布) https://github.com/moby/moby/issues/47150，所以目前还是避免使用 docker 25.0.0 最新版本呢

**Comment by LeoneChen** [comment]
原来如此，感谢提醒

**Comment by LeoneChen** [comment]
刚试了下，docker 25.0.1 deb包已经发布了，没有上述问题了，感谢

**Comment by LeoneChen** [comment]
关于问题二，secretpad起来后节点信息里面默认的通讯地址一直都是`127.0.0.1:28080`，而且这还是可修改的，这和前面`install.sh`的端口有什么关系吗？[官网有关的描述](https://www.secretflow.org.cn/docs/quickstart/kvu445094gvtkp3f)太少了，我还是连通不起来
![1706156367474](https://github.com/secretflow/secretflow/assets/35480440/332422f3-7e6f-4c16-9cd7-9c6f0a8a71e8)

**Comment by CodePorterL** [comment]
install.sh脚本配置的是kuscia的master节点，alice和bob是默认内置节点，默认内置节点配置的端口是28080和38080。
![image](https://github.com/secretflow/secretflow/assets/91072507/293e4d68-2473-478b-bc4e-65b7d8147920)
