### ISSUE TITLE
本地代码调试依赖无法安装

### ISSUE THREAD

**Issue by panmason** [secretflow/secretflow#1135]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

1.3.0b0

### OS Platform and Distribution

MacOS 14.1 

### Python version

3.9.6

### Bazel version

bazel 6.4.0

### GCC/Compiler version

arm64-apple-darwin23.1.0

### What happend and What you expected to happen.

```shell
当我在安装依赖时，提示 secretflow-rayfed==0.2.0a7 安装失败，提示

ERROR: Cannot install secretflow-rayfed==0.1.0b1, secretflow-rayfed==0.1.1a0, secretflow-rayfed==0.1.1a3, secretflow-rayfed==0.1.1a4, secretflow-rayfed==0.2.0a0, secretflow-rayfed==0.2.0a1, secretflow-rayfed==0.2.0a16 and secretflow-rayfed==0.2.0a7 because these package versions have conflicting dependencies.

The conflict is caused by:
    secretflow-rayfed 0.2.0a16 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.2.0a7 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.2.0a1 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.2.0a0 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.1.1a4 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.1.1a3 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.1.1a0 depends on secretflow-ray>=2.1.0
    secretflow-rayfed 0.1.0b1 depends on secretflow-ray>=2.1.0


当我在尝试安装 secretflow-ray时提示

ERROR: Could not find a version that satisfies the requirement secretflow-ray (from versions: none)
ERROR: No matching distribution found for secretflow-ray
```

### Reproduction code to reproduce the issue.

```shell
ERROR: Could not find a version that satisfies the requirement secretflow-ray (from versions: none)
ERROR: No matching distribution found for secretflow-ray
```

**Comment by Chrisdehe** [comment]
@panmason hey
pip show ray
pip show secretflow-ray
看下是否是重复装了ray/secretflow-ray

**Comment by panmason** [comment]
> @panmason hey pip show ray pip show secretflow-ray 看下是否是重复装了ray/secretflow-ray

$ pip show ray
Name: ray
Version: 2.2.0
Summary: Ray provides a simple, universal API for building distributed applications.
Home-page: https://github.com/ray-project/ray
Author: Ray Team
Author-email: ray-dev@googlegroups.com
License: Apache 2.0
Location: /Users/didi/pyprojects/secretflow/venv/lib/python3.9/site-packages
Requires: aiosignal, attrs, click, filelock, frozenlist, grpcio, jsonschema, msgpack, numpy, protobuf, pyyaml, requests, virtualenv
Required-by: 


 pip show secretflow-ray
WARNING: Package(s) not found: secretflow-ray

**Comment by Chrisdehe** [comment]
另外，secretflow中自带有secretflow-ray，无需重复下载

**Comment by panmason** [comment]
> secretflow

目前在编译出来的whl中在安装时提示无法找到secretflow-ray

ERROR: Could not find a version that satisfies the requirement secretflow-ray>=2.1.0 (from secretflow-rayfed) (from versions: none)
ERROR: No matching distribution found for secretflow-ray>=2.1.0

**Comment by Chrisdehe** [comment]
检查下 /tmp/ray/session_latest/sockets 是否存在以及权限是否能正常访问；
 如果没问题的话麻烦提供下 Ray 的日志，在 /tmp/ray/session_latest/logs 目录下
 raylet.err

**Comment by panmason** [comment]
> /tmp/ray/session_latest/sockets

依赖安装问题，没有运行起来，哪里来的日志

**Comment by Chrisdehe** [comment]
1、SecretFlow要求安装secretflow-ray （2.2.0）
2、请不要同时安装官方ray，会产生冲突。如果有安装，请确保先卸载ray以及secretflow-ray，然后重新安装secretflow-ray

**Comment by panmason** [comment]
> secretflow-ray

我已经完成卸载了ray和secretflow-ray，我在重现安装时候依旧在报错

```
ERROR: Could not find a version that satisfies the requirement secretflow-ray>=2.1.0 (from secretflow-rayfed) (from versions: none)
ERROR: No matching distribution found for secretflow-ray>=2.1.0
```

我在怀疑你们的依赖的上传的又问题，提示没有对用 distribution 在secretflow-ray上，你们应该是没有提交或没有上传到公共仓库的依赖中，或者secretflow-ray 这个包是那个开源仓库构建出来，我自己构建也可以

**Comment by ian-huu** [comment]
确认一下 python 版本，目前 secretflow 只支持 3.8，更高版本支持还在进行中。

此外 arm mac 的支持也是实验性质的，不保证所有功能都正常（但应该可以安装）。
