### ISSUE TITLE
拆分学习模型加载相关问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1140]
根据官方文档完成了拆分学习的模型训练阶段，https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing得到了alice_base_model 、bob_base_model和fuse_model三个模型
现在我想用在训练阶段得到上述三个模型进行推理

预测数据：使用了训练数据作为预测数据，仅删除了alice中的标签列'y'.代码中省略了数据预处理过程

`
import secretflow as sf
import matplotlib.pyplot as plt
from secretflow.ml.nn import SLModel

sf.init(['alice', 'bob'], address='local')
alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

file_dict = {alice:'../database/alice_predict_bank.csv',bob:'../database/bob_predict_bank.csv'}  

data = sf.data.vertical.read_csv(file_dict )

base_model_path = {alice:'../model/alice_base_model',bob:'../model/alice_base_model'}

fuse_model_path = '../model/fuse_model'

sl_model = SLModel(device_y=alice)
sl_model.load_model(base_model_path=base_model_path,fuse_model_path=fuse_model_path)   
y = sl_model.predict(data)

`

错误如下：
![image](https://github.com/secretflow/secretflow/assets/49178688/ac9ccedc-3766-41cf-91ac-b066e64d0885)

请问一下是什么原因呢？SLModel在初始化的时候需要额外的参数吗

**Comment by zhangxingmeng** [comment]
当然,一般来说你可以复用训练时候的slmodel定义。
也可以参考以下代码
```python
sl_model = SLModel(
                  base_model_dict={
                          alice:None,
                          bob:None,
                  backend="tensorflow",
                  strategy="split_nn",
}
                  device_y=alice)
```

**Comment by oceanqdu** [comment]
@zhangxingmeng 感谢解答，已解决
