### ISSUE TITLE
有关参与方异常中断的问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1142]
在执行secretflow相关代码时需要两方（alice和bob）同时执行，在执行过程中一方执行发生了错误（例如alice的数据集有问题，所以alice的终端发生错误，相关程序终止），但是bob方还在正常执行（bob的数据没有问题），这时候bob就会一直卡住不动，一直在等待，请问一下这种情况下如何让bob方自动中断程序呢？

**Comment by zhouaihui** [comment]
hi, @oceanqdu, 麻烦提供下secretflow版本号

**Comment by oceanqdu** [comment]
@zhouaihui  secretflow v1.4.0.dev240123

**Comment by zhouaihui** [comment]
可以发一下复现code吗？你用的这个版本已经支持异常传播。

**Comment by oceanqdu** [comment]
@zhouaihui 刚刚发现出现问题的虚拟机版本是v1.4.0.dev20231225，请问这个版本是不支持异常传播的吗？更新到secretflow v1.4.0.dev240123就可以了吗

**Comment by Chrisdehe** [comment]
是的 最新版本已经支持异常传播了，辛苦更新到最新版本尝试

**Comment by oceanqdu** [comment]
好的非常感谢
