### ISSUE TITLE
在secretflow中有类似于pd.concat的函数接口吗？

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1149]
在secretflow中有类似于pd.concat()的函数接口吗？例如我在隐语中对Hdataframe进行数据预处理时，假设我选择对某一列进行onehot编码，将原来的一列变为了多列，现在我想将onehot处理过后的多列拼接到原数据中，并删除初始列，请问有现成的函数接口能实现吗

**Comment by zhangxingmeng** [comment]
目前concat是不支持的，drop是支持的。
你可以试试HDataFrame的apply_func方法，可以接受一段逻辑来做处理
