### ISSUE TITLE
如何得到一个计算结果的单个份额？

### ISSUE THREAD

**Issue by ShallMate** [secretflow/secretflow#1154]
![QQ截图20240220191433](https://github.com/secretflow/secretflow/assets/25976948/4e88e289-8e22-44e5-b99b-eae8f8f76682)
当使用SPU进行两方计算时，我该如何得到让alice和bob分别得到结果的明文份额呢？比如，在上述的代码，我希望让alice和bob分别得到变量add_,sub_，matmul_的秘密份额，而不是直接调用sf.reveal去回复完整的计算结果。

**Comment by ShallMate** [comment]
份额指的是数据分片，比如add_的份额可能是add_1+<add_2=add_，我的需求是如何让alice和bob分别得到add_1和add_2呢

**Comment by 6fj** [comment]
hi @ShallMate, 可以看一下这个文档：https://www.secretflow.org.cn/docs/secretflow/v1.3.0b0/zh-Hans/tutorial/spu_basics

感谢！

**Comment by ShallMate** [comment]
@6fj 非常不好意思。我没有从这个文档中找到我的需求。如果是我搞错了什么东西，非常抱歉。我再说一次我的需求吧。我需要得到计算结果的分片。比如我使用dir(计算结果)查看计算结果可以使用的方法,我并没有找到该对象的哪个方法可以得到单个分片。

**Comment by 6fj** [comment]
![image](https://github.com/secretflow/secretflow/assets/99384777/51191d1c-1383-4d5c-ab6e-fe234860cc30)

一个SPU object 本质上就是meta和shares组成的，每个shares位于不同的party。

你还可以参考一下SPUObject的文档：https://www.secretflow.org.cn/docs/secretflow/v1.3.0b0/zh-Hans/source/secretflow#secretflow.SPUObject

**Comment by 6fj** [comment]
你这里所谓的得到分片是指想要将密文保存在各方的本地吗？

**Comment by ShallMate** [comment]
@6fj 不是的，我希望得到计算结果的明文分片。比如说两方MPC计算的结果应该是结果的秘密共享。秘密共享应该分配在两方。但是我没办法得到这个share

**Comment by ShallMate** [comment]
> ![image](https://private-user-images.githubusercontent.com/99384777/306535942-51191d1c-1383-4d5c-ab6e-fe234860cc30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDE0NjgsIm5iZiI6MTcwODUwMTE2OCwicGF0aCI6Ii85OTM4NDc3Ny8zMDY1MzU5NDItNTExOTFkMWMtMTM4My00ZDVjLWFiNmUtZmUyMzQ4NjBjYzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA3MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMzQyODNiY2FiZTY3ZmUyYjM5YWM1ZTRlNjA2ZTVjMmQxMjJmN2QyODRmY2U3Njc0ZjAwYTc0NDFmOWM0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvM0DqAFiWM0FQd4pa_aSYWgXJcggOZjUZKId0fyilI)
> 
> 一个SPU object 本质上就是meta和shares组成的，每个shares位于不同的party。
> 
> 你还可以参考一下SPUObject的文档：https://www.secretflow.org.cn/docs/secretflow/v1.3.0b0/zh-Hans/source/secretflow#secretflow.SPUObject

可是为什么add_里并没有对应shares的方法？是那个shares_name吗？但是我也没办法得到具体的明文呀

**Comment by ShallMate** [comment]
@6fj 不知道您有没有理解我的意思。我希望得到的是明文。但是需要的是share，而不是恢复后的结果。

**Comment by 6fj** [comment]
你可以用dump api把share保存成文件查看：https://www.secretflow.org.cn/docs/secretflow/v1.3.0b0/zh-Hans/source/secretflow#secretflow.SPU.dump

**Comment by ShallMate** [comment]
@6fj 直接保存整个add_ ?单个share怎么获取呢

**Comment by ShallMate** [comment]
@6fj 我已经试过了。我保存的是.txt文件。这样得到的是二进制乱码呀。

**Comment by tpppppub** [comment]
share 本身就是随机数，没有很好的可读性支持，如果有需求可以参考[这个 issue](https://github.com/secretflow/spu/issues/458) 修改 SPU 源码打印 share 到 log 里看
