### ISSUE TITLE
代理端口开放-端口列表

### ISSUE THREAD

**Issue by songsong124** [secretflow/secretflow#1156]
### Issue Type

Others

### Source

binary

### Secretflow Version

刚开源时版本

### OS Platform and Distribution

centos7.9

### Python version

3.8

### Bazel version

1

### GCC/Compiler version

2

### What happend and What you expected to happen.

```shell
csql 使用的mpc 通信框架的端口是多少？是随机端口吗
```

### Reproduction code to reproduce the issue.

```shell
csql 使用的mpc 通信框架的端口是多少？是随机端口吗
```

**Comment by Chrisdehe** [comment]
看起来您提出了两条同样的问题，优先在信息量较多的[这条issue](https://github.com/secretflow/scql/issues/248)回复
