### ISSUE TITLE
关于更新依赖包后的编译问题

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#1162]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

1.0

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.15

### Bazel version

5.4.1

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
大佬好，小白提问。
我在使用隐语1.4.0的时候使用扫描工具对隐语的源码进行了一个分析。发现TensorFlow:2.11.1和onnx:1.12.0两个版本库存在安全漏洞。
请教两个问题
1 将直接依赖TensorFlow:2.11.1改成了TensorFlow:2.15,但是onnx这个间接依赖有什么好的方式修改吗？
2 替换依赖版本后，我需要测试新依赖后的代码功能有没有问题，我是应该先用bazel编译打包它为镜像，还是直接在docker目录下直接打包对应的文件为镜像呢？ 还是直接运行单元测试验证功能就行呢？
```

### Reproduction code to reproduce the issue.

```shell
问题如上
```

**Comment by Chrisdehe** [comment]
请问问题是否得到解决呢？
