### ISSUE TITLE
金融风控业务的解释

### ISSUE THREAD

**Issue by LeoneChen** [secretflow/secretflow#1170]
SecretPad的教程中提到了金融风控业务，关于WOE分箱、分箱转换的输出等等能不能介绍一下这都是干什么的，是分箱后的数据拿去回归训练？（不太懂）以及这个流程怎么体现金融风控，我应该从哪里得到什么样的结论？
![image](https://github.com/secretflow/secretflow/assets/35480440/75695daf-f71a-4fb7-8731-746a9abbd566)

**Comment by Chrisdehe** [comment]
WOE分箱和分箱转换是训练前的数据预处理技术，主要用于逻辑回归等统计模型的构建，以提高模型预测性能和解释性。
参考内容如下：
https://mp.weixin.qq.com/s/Bno0XjhrHSkDIf1PPW4QGg
https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/tutorial/risk_control_scenario#隐语SecretFlow金融风控全链路能力展示

**Comment by LeoneChen** [comment]
感谢
