### ISSUE TITLE
关于官方教程中关于联邦学习图像分类的教程文档中的一些疑问

### ISSUE THREAD

**Issue by RocDDD** [secretflow/secretflow#1171]
### Issue Type

Documentation Bug

### Source

binary

### Secretflow Version

secretflow

### OS Platform and Distribution

ubuntu

### Python version

3.8

### What happend and What you expected to happen.

```shell
https://i.hd-r.cn/3867ab8743a99d5e3ff9a4af5e5090b1.png
Q1:在进行ALICE 和BOB两方数据可视化时采用了一模一样的代码，是否是编辑错误

https://imgse.com/i/pFBTHB9
Q2:在进行单机对比实验时，markdown中说明取2w样本，实际切片为1w样本，作为对照实验是否Alice需要控制样本数量与联邦学习中的3W一致，且验证集也与联邦学习中保持一致呢？

Q3：实验最后得出的结论基于的模型准确度貌似与前面的结果无法正确映射。想了解一下隐语的安全聚合是否会造成精度损失
```

### Reproduction code to reproduce the issue.

```shell
/
```

**Comment by Chrisdehe** [comment]
我看把issue关闭了 问题是否得到解决了呢？

**Comment by RocDDD** [comment]
不好意思重新编辑提了一个新的issue







| |
dolphinDDD
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月4日 15:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [secretflow/secretflow] 关于官方教程中关于联邦学习图像分类的教程文档中的一些疑问 (Issue #1171) |

我看把issue关闭了 问题是否得到解决了呢？
