### ISSUE TITLE
关于官方教程中关于联邦学习图像分类的教程文档中的一些疑问

### ISSUE THREAD

**Issue by RocDDD** [secretflow/secretflow#1172]
https://www.secretflow.org.cn/docs/secretflow/v1.3.0b0/zh-Hans/tutorial/Federate_Learning_for_Image_Classification

有一些关于官方的这篇文档的疑问想咨询一下
Q1:在进行ALICE 和BOB两方数据可视化时采用了一模一样的代码，是否是编辑错误
<img width="815" alt="Q1" src="https://github.com/secretflow/secretflow/assets/97602802/81ae54c0-fecd-4473-82f2-4e0cc30dc819">
Q2:在进行单机对比实验时，markdown中说明取2w样本，实际切片为1w样本，作为对照实验是否Alice需要控制样本数量与联邦学习中的3W一致，且验证集也与联邦学习中保持一致呢？
<img width="818" alt="Q2" src="https://github.com/secretflow/secretflow/assets/97602802/087c9fea-ffa9-44b6-9a87-394bfaad70c1">
Q3:实验最后得出的结论基于的模型准确度貌似与前面的结果无法正确映射。想了解一下隐语的安全聚合是否会造成精度损失呢？

**Comment by zhangxingmeng** [comment]
Hi，感谢您的提问，您发现这几个问题都是文档在演进更新中的一些错误。我们会尽快修复。
隐语的安全聚合不会造成精度损失。

**Comment by zhangxingmeng** [comment]
https://github.com/secretflow/secretflow/pull/1175
fix pr在这里，可以一起帮忙review一下 @RocDDD

**Comment by RocDDD** [comment]
感谢您的回复，新的文档中我看将联邦学习中的ALice方的样本比例调整为0.15 是为了和单方建模1w样本对齐嘛，如果是的话，那单方建模时用的测试集是否也应该取minist['x/y_test']而不是从1w样本中划分呢

**Comment by zhangxingmeng** [comment]
> 感谢您的回复，新的文档中我看将联邦学习中的ALice方的样本比例调整为0.15 是为了和单方建模1w样本对齐嘛，如果是的话，那单方建模时用的测试集是否也应该取minist['x/y_test']而不是从1w样本中划分呢

这个您可以在自己的尝试中进行修改，这个demo并不是一个严肃的实验论证，更多是一个样例，主要是告诉大家该怎样去跑。
读取mnist['test_data']在进行筛选当然是可以的，如果你觉得还是有问题，欢迎修改后提交pr

**Comment by RocDDD** [comment]
哦哦好的，感谢您的耐心反馈

**Comment by Chrisdehe** [comment]
@RocDDD 
hey，更深入的交流可以添加隐语技术支持WeChat哈，隐语最新动态实时同步～（secretflow02）
