### ISSUE TITLE
关于SPU官网例子的使用问题

### ISSUE THREAD

**Issue by coffee1110** [secretflow/secretflow#1176]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.3.0.dev20231128

### OS Platform and Distribution

CentOS 7.9

### Python version

3.8.18

### Bazel version

5.4.1

### GCC/Compiler version

4.8.5

### What happend and What you expected to happen.

```shell
您好,我想请问下,按照生产环境启动了ray节点后
1.示例中的以下代码应该是alice还是bob节点执行呢,亦或者是需要一个第三方节点去执行?
def deduce_from_account(bank_account, amount):
    new_bank_account = []
    for account in bank_account:
        account['deposit'] = account['deposit'] - amount
        new_bank_account.append(account)
    return new_bank_account

new_bank_account_spu = spu_device(deduce_from_account)(
    bank_account_spu, debit_amount_spu
)
2.如果是alice或者bob执行,那么这个方法的两个参数应该分属于alice和bob节点,那么在alice或者bob节点中如何获取到对方的的spuObject对象呢,进行执行呢?
```

### Reproduction code to reproduce the issue.

```shell
alice节点
import secretflow as sf
from secretflow.device.device import spu

cluster_config = {
    'parties': {
        'alice': {
            'address': '192.168.209.131:30505',
            'listen_addr': '0.0.0.0:30505'
        },
        'bob': {
            'address': '192.168.209.132:30506',
            'listen_addr': '0.0.0.0:30506'
        }
    },
    'self_party': 'alice',
    'runtime_config': {
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM64
    }
}
sf.init(address='192.168.209.131:30505', cluster_config=cluster_config)
spu_device = sf.SPU(cluster_config)
alice = sf.PYU('alice')
spu_alice_data = sf.to(alice,10).to(spu_device)
# 在alice节点如何获取bob的spu对象，进行计算呢
```

**Comment by Chrisdehe** [comment]
@coffee1110 
1. 需要Alice和bob双方同时执行，方法可以参考[生产模式](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/getting_started/deployment#production)
2. 关于你描述的“如何获取到对方的的spuObject对象呢,进行执行呢?” 我没有get到，麻烦展开描述

**Comment by coffee1110** [comment]
我的想法是,比如alice和bob两个ray主节点,分别代表两个机构,节点已经按照生产模式的方式,启动了ray节点
ray start --head --node-ip-address="192.168.209.131" --port="30505" --include-dashboard=False --disable-usage-stats
ray start --head --node-ip-address="192.168.209.132" --port="30506" --include-dashboard=False --disable-usage-stats
此时要实现类似教程里面的deduce_from_account运算.
1.alice具有明文数据amount = 10,alice将10转成spuObject对象
2.bob节点具有bank的集合数据,bob节点将bank集合也转成spuObject对象
之后应该如何调用呢,能否在alice获取到bob的spuObject对象,与本地的spuObject对象进行计算,还是说需要一个第三方几点汇总两个spuObject,执行计算呢

**Comment by Chrisdehe** [comment]
隐语是上帝视角编程，请参考[隐语的编程思想](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/developer/design/programming_in_secretflow)

**Comment by Chrisdehe** [comment]
另外，实际例子里面 bank_account debit_account 可以写成从 alice、bob 本地文件读取

**Comment by coffee1110** [comment]
就是类似psi的例子中吗,把数据写入到文件,通过文件读取的方式吗?

**Comment by gxcuit** [comment]
> @coffee1110  
> 
> 1. 需要Alice和bob双方同时执行，方法可以参考[生产模式](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/getting_started/deployment#production)
> 2. 关于你描述的“如何获取到对方的的spuObject对象呢,进行执行呢?” 我没有get到，麻烦展开描述

@Chrisdehe Hi，我有相同的问题
“需要Alice和bob双方同时执行” 这一点，我get到了

`def deduce_from_account(bank_account, amount):
    new_bank_account = []
    for account in bank_account:
        account['deposit'] = account['deposit'] - amount
        new_bank_account.append(account)
    return new_bank_account

new_bank_account_spu = spu_device(deduce_from_account)(
    bank_account_spu, debit_amount_spu
)`

假设Alice 有bank_account_spu， bob有debit_amount_spu（value是10）.
Alice在执行代码的时候，如何获取debit_amount_spu这个变量呢？

**Comment by Chrisdehe** [comment]
@gxcuit hey，问题我没有get到，不过看起来你想了解的是在[《如何设计&开发新的明密文混合算法》](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/programming_guide)这篇文档，建议阅读。
祝好

**Comment by gxcuit** [comment]
> @gxcuit hey，问题我没有get到，不过看起来你想了解的是在[《如何设计&开发新的明密文混合算法》](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/programming_guide)这篇文档，建议阅读。 祝好

假如说有两方Alice 和Bob，Alice 拥有数据a=10； Bob拥有数据b=100. 打算使用SPU计算a+b

`
def add(a, b):
return a+b

add_spu= spu_device(add)(a, b)`


我理解的：
1. Alice 和Bob 都需要在本地的机器上指定对应spu的代码？
2. 那Alice在执行代码的时候，怎么知道b呢？ b是Bob持有的，代码里b这个变量该如何赋值呢？


Thanks @Chrisdehe
