### ISSUE TITLE
plt.plot(history["global_history"]['accuracy'])会报错，应该修改为plt.plot(history.global_history['accuracy'])

### ISSUE THREAD

**Issue by SkyTu** [secretflow/secretflow#1184]
### 文档修改建议

<details>
      <summary>技术信息</summary>
      <ul>
        <li>页面 <a href="https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/tutorial/Federate_Learning_for_Image_Classification">https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/tutorial/Federate_Learning_for_Image_Classification</a></li>
        <li>源码 <a href="https://github.com/secretflow/secretflow/blob/e0435dadd4d2d1ec2303e3b6aec9059fcb816f5f/docs/tutorial/Federate_Learning_for_Image_Classification.ipynb">https://github.com/secretflow/secretflow/blob/e0435dadd4d2d1ec2303e3b6aec9059fcb816f5f/docs/tutorial/Federate_Learning_for_Image_Classification.ipynb</a></li>
        <li>浏览器 <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</code></li>
      </ul>
    </details>

**Comment by zhangxingmeng** [comment]
主分支已修复，等下个版本的文档更新后就好啦。感谢反馈
