### ISSUE TITLE
我想请问下,隐语框架哪里用到了零知识证明,还有是否有使用案例

### ISSUE THREAD

**Issue by coffee1110** [secretflow/secretflow#1186]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.3.0.dev20231128

### OS Platform and Distribution

CentOS 7.9

### Python version

3.8.18

### Bazel version

5.4.1

### GCC/Compiler version

4.8.5

### What happend and What you expected to happen.

```shell
隐语框架是否有用到了零知识证明,如果有的话,是否存在文档或者使用教程呢
```

### Reproduction code to reproduce the issue.

```shell
隐语框架是否有用到了零知识证明,如果有的话,是否存在文档或者使用教程呢
```

**Comment by Chrisdehe** [comment]
@coffee1110 hey
ZKP可参考隐语文档：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.3.0b0/awesome-pets/papers/tools/zkp#zkp-standard-efforts
另外，如果有想了解隐语的一些文档，除了去看列表以外还可以在[官网文档](https://www.secretflow.org.cn/zh-CN/)右上角的搜索框（放大镜）中输入关键词等信息即可哈～

**Comment by coffee1110** [comment]
好的,感谢

**Comment by coffee1110** [comment]
我看到这个网站上都是一些zkp的论文文档,没有隐语这边使用的文档吗,类似heu使用的那种

**Comment by Jamie-Cui** [comment]
> 我看到这个网站上都是一些zkp的论文文档,没有隐语这边使用的文档吗,类似heu使用的那种

不好意思，目前隐语对 ZKP 的支持还处于非常早期的实验阶段，目前并没有文档。感兴趣的话可以加我们小助手沟通一下您的使用需求，具体 zkp 代码可以在 yacl repo 下查看。

感谢

**Comment by coffee1110** [comment]
好的好的,感谢
