### ISSUE TITLE
python=3.8 pip install -U secretflow 失败

### ISSUE THREAD

**Issue by onewink** [secretflow/secretflow#119]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

*

### OS Platform and Distribution

mac studio (m1)

### Python version

3.8.13

### What happend and What you expected to happen.

I execute the command, and get an error from pip ""

```
conda create -n sf python=3.8
pip install -U secretflow
```

error info
```
ERROR: Could not find a version that satisfies the requirement secretflow (from versions: none)
ERROR: No matching distribution found for secretflow
```

### Reproduction code to reproduce the issue.

```shell
-
```

**Comment by anakinxc** [comment]
Secretflow does not support Apple Silicon so far, we are still working on this :)

You can either give Rosetta a chance or wait for a future release.
