### ISSUE TITLE
spec子仓库找不到

### ISSUE THREAD

**Issue by LeoneChen** [secretflow/secretflow#1196]
https://github.com/secretflow/secretflow/tree/v1.4.0b0/submodules 下面的spec子仓库找不到（[25dd619](https://github.com/secretflow/spec/tree/25dd619f07dd8ba9cb445fb610bafc6370f4702d)）

**Comment by Chrisdehe** [comment]
看起来是链接挂掉了，我们再优先确认一下

**Comment by 6fj** [comment]
> https://github.com/secretflow/secretflow/tree/v1.4.0b0/submodules 下面的spec子仓库找不到（[25dd619](https://github.com/secretflow/spec/tree/25dd619f07dd8ba9cb445fb610bafc6370f4702d)）

目前这个版本的spec还没有同步，但是你在编译secretflow的时候应该不需要。

**Comment by LeoneChen** [comment]
好的好的

**Comment by Chrisdehe** [comment]
那我先关闭，有问题随时reopen

**Comment by 6fj** [comment]
hi @LeoneChen ,

spec 可参考：https://github.com/secretflow/spec/releases/tag/v1.0.dev240301
