### ISSUE TITLE
psi在使用BC22或kkrt协议时出现的问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1197]
### Issue Type

Others

### Source

binary

### Secretflow Version

v1.4.0.dev240123

### OS Platform and Distribution

centos7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
PSI在使用BC22和KKRT 协议时precheck_input参数改为false，有重复值也可以执行
```

### Reproduction code to reproduce the issue.

```shell
spu.psi_csv(psi_key_dict, input_dict, output_dict,precheck_input=False,receiver=parties_list[receiver],broadcast_result=True,protocol=BC22_PSI_2PC,curve_type=curve_type,bucket_size=1<<30)
```

**Comment by oceanqdu** [comment]
[psi_alice.csv](https://github.com/secretflow/secretflow/files/14634320/psi_alice.csv)
[alice_bank_data.csv](https://github.com/secretflow/secretflow/files/14634332/alice_bank_data.csv)
求交数据集为以上，其中alice的数据为psi_alcie.csv ,bob的数据集为alice_bank_data.csv  求交字段分别为 id 和 age

**Comment by Chrisdehe** [comment]
进展同步：内部正在查看和复现中

**Comment by 6fj** [comment]
hi @oceanqdu 

我们可以确认**psi_csv**存在上述问题。与此同时，请使用 **psi**(**psi_v2**) 这两个API，这是我们最新的api，会逐渐替换**psi_csv**: https://www.secretflow.org.cn/en/docs/secretflow/v1.5.0.dev240312/source/secretflow#secretflow.SPU.psi。

**Comment by 6fj** [comment]
hi @oceanqdu 
我们可以确认的是，KKRT等协议当求交键发生重复的时候，行为是不确定的，可能报错，也可能不会报错。因此除非你确认输入不存在求交键没有重复的情况下，请不要关闭precheck_input，感谢。请不要依赖程序报错来规避检查。
