### ISSUE TITLE
基于secretflow1.3.0.dev231120分支，百兆左右的两方数据执行woe分箱和分箱转换组件后，结果文件行数变少了且两方行不对齐

### ISSUE THREAD

**Issue by zhouhansheng** [secretflow/secretflow#1202]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.3.0.dev231120

### OS Platform and Distribution

Linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
基于secretflow1.3.0.dev231120分支，百兆左右的两方数据执行woe分箱和分箱转换组件后，两方结果文件行数变少了且两方行不对齐。
组件执行过程未报错，请问这是由woe分箱和分箱转换组件导致的bug，还是数据量大引起的？
```

### Reproduction code to reproduce the issue.

```shell
None
```

**Comment by zhouhansheng** [comment]
> 辛苦贴一下代码

secretpad上运行的woe分箱和woe转换组件，woe分箱后的rule文件内容为：
alice方：

> {'feature_iv_info': [{'else_iv': 1.4284002292050182e-08, 'feature_iv': 0.0012504422090033461, 'ivs': (2.280473292953912e-05, 0.00015294863497061805, 4.762964603672263e-06, 7.346349100064366e-05, 0.00016899977618179454, 0.00021075332213524173, 6.201384527374507e-05, 2.280473292953912e-05, 1.461494989418682e-05, 0.0005172757590843659), 'name': 'x0'}, {'else_iv': 1.4284002292050182e-08, 'feature_iv': 0.0021160523687703174, 'ivs': (5.337496922237677e-05, 0.0005950314609435339, 7.237563967016381e-05, 0.0005028499610359983, 0.0001858521658572973, 1.9917767829189325e-05, 9.675491027729e-05, 2.85680045841005e-05, 1.2083803382647781e-07, 0.0005612066513165407), 'name': 'x1'}, {'else_iv': 1.4284002292050182e-08, 'feature_iv': 0.0005586893554786702, 'ivs': (0.00013769865758405596, 6.201384527374507e-05, 4.369068867535939e-05, 8.11675252670196e-08, 1.232220418027199e-05, 1.4670502937543e-05, 0.00012182478910044481, 2.85680045841005e-05, 0.00013769865758405596, 1.2083803382647781e-07), 'name': 'x626'}, {'else_iv': 1.4284002292050182e-08, 'feature_iv': 0.002650991888059338, 'ivs': (5.24522009299649e-05, 8.281434299340654e-06, 0.00034701182866833565, 0.0003957532452958993, 0.0008309608212280461, 9.792401073603888e-06, 0.000261276014812874, 0.00044769906614512375, 3.6488860793275825e-05, 0.000261276014812874), 'name': 'x627'}], 'variables': [{'else_counts': 0, 'else_filling_value': 0.016901247353914038, 'filling_values': [-0.015101483732259696, -0.03911339420075717, 0.006901164019330769, -0.027105853374918342, -0.041115020188810636, 0.04591779033295367, 0.024901290020990348, -0.015101483732259696, -0.012086289519338163, 0.07194265282203331], 'name': 'x0', 'split_points': [-0.027273199999999997, -0.01829648, -0.012644499999999998, -0.007918589999999994, -0.00329228, 0.0013709980000000002, 0.006955670000000015, 0.014118740000000005, 0.0247331], 'total_counts': [2000, 2000, 2000, 2000, 2000, 1999, 2000, 2000, 2001, 1999], 'type': 'numeric'}, {'else_counts': 0, 'else_filling_value': 0.016901247353914038, 'filling_values': [-0.02310408725978516, -0.07716805986242065, 0.026901330688497607, 0.0709143750964673, -0.043116762372338927, -0.01411674706972011, -0.031107971832446422, 0.016901247353914038, -0.001099238669706869, 0.07491751489663878], 'name': 'x1', 'split_points': [-0.02289832, -0.01126978, -0.0030203359999999967, 0.0035986800000000056, 0.00901755, 0.013822300000000003, 0.01832978000000001, 0.023390800000000003, 0.03039398], 'total_counts': [2000, 2000, 2000, 2000, 2000, 1999, 2000, 2000, 2000, 2000], 'type': 'numeric'}]}

bob方：

> {'variables': [{'else_counts': 0, 'else_filling_value': 0.016901247353914038, 'filling_values': [-0.037111880388639065, 0.024901290020990348, 0.02090125268726035, 0.0009009060074731513, -0.011100582194579017, -0.01211529562512552, 0.034901733377535035, 0.016901247353914038, -0.037111880388639065, -0.001099238669706869], 'name': 'x626', 'split_points': [-0.02622344, -0.016574619999999998, -0.010126499999999998, -0.004995785999999998, -0.000598904, 0.003913866000000008, 0.009116604000000004, 0.015678600000000015, 0.026031620000000005], 'total_counts': [2000, 2000, 2000, 2000, 2000, 1999, 2000, 2000, 2000, 2000], 'type': 'numeric'}, {'else_counts': 0, 'else_filling_value': 0.016901247353914038, 'filling_values': [0.02290126535401132, -0.009100217461287639, 0.058907422988069384, 0.06290936126275774, -0.09120391269551524, 0.009897716976576692, -0.05112497350194237, 0.06691166792857532, -0.01910264140208808, -0.05112497350194237], 'name': 'x627', 'split_points': [-0.0337176, -0.027939, -0.023283679999999998, -0.018496799999999997, -0.012983, -0.006841873999999985, 0.0005258622000000061, 0.009204036000000006, 0.020119700000000008], 'total_counts': [2000, 2000, 2000, 2000, 2000, 1999, 2000, 2000, 2000, 2000], 'type': 'numeric'}]}

原始输入文件两方各有2w行450列数据，alice方选取x0和x1列，bob方选取x626和x627列做分箱，做完分箱转换后，查看垂直表对应的两方文件，两方都只有2000多行，按理说应该是2w行。

**Comment by Chrisdehe** [comment]
建议升级到最新的版本尝试一下呢
另外关于分箱和分箱转换可以参考一下
https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/risk_control_scenario#woe分箱

**Comment by zhouhansheng** [comment]
> 建议升级到最新的版本尝试一下呢 另外关于分箱和分箱转换可以参考一下 [https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/risk_control_scenario#woe分箱](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/risk_control_scenario#woe%E5%88%86%E7%AE%B1)

secretflow最新分支分箱组件结果是正常的，我看了一下dev1120分支的问题主要是结果保存那边的：
1120分支：

```
def dump_vertical_table(
    ctx,
    v_data: VDataFrame,
    uri: str,
    meta: VerticalTableWrapper,
    system_info: SystemInfo,
) -> DistData:
    assert isinstance(v_data, VDataFrame)

    with ctx.tracer.trace_io():
        output_uri = {p: uri for p in v_data.partitions}
        output_path = {
            p: os.path.join(ctx.local_fs_wd, output_uri[p]) for p in output_uri
        }
        wait(v_data.to_csv(output_path, index=False))
        order = [p.party for p in v_data.partitions]
```

最新分支：
```
def dump_vertical_table(
    ctx,
    v_data: VDataFrame,
    uri: str,
    meta: VerticalTableWrapper,
    system_info: SystemInfo,
) -> DistData:
    assert isinstance(v_data, VDataFrame)
    assert v_data.aligned
    assert len(v_data.partitions) > 0
    assert math.prod(v_data.shape), "empty dataset is not allowed"

    parties_length = {}
    for device, part in v_data.partitions.items():
        parties_length[device.party] = len(part)
    assert (
        len(set(parties_length.values())) == 1
    ), f"number of samples must be equal across all devices, got {parties_length}"

    with ctx.tracer.trace_io():
        output_uri = {p: uri for p in v_data.partitions}
        output_path = {
            p: lambda uri=output_uri[p]: ctx.comp_storage.get_writer(uri)
            for p in output_uri
        }
        wait(v_data.to_csv(output_path, index=False))
        order = [p.party for p in v_data.partitions]
        file_metas = {
            p: p(lambda uri=output_uri[p]: ctx.comp_storage.get_file_meta(uri))()
            for p in output_uri
        }
        file_metas = reveal(file_metas)
        logging.info(
            f"dumped VDataFrame, file uri {output_path}, samples {parties_length}, file meta {file_metas}"
        )
```
差别好像就是新分支在v_data.to_csv之后把file_metas打印了一下，这样是为了规避wait(v_data.to_csv)保存不完全的问题？

**Comment by Chrisdehe** [comment]
这个可能是旧版本故障，新版本做了日志优化
