### ISSUE TITLE
如何将源码build为docker镜像？

### ISSUE THREAD

**Issue by LindaHu0701** [secretflow/secretflow#1206]
如题，或者是否有相关教程？

**Comment by LindaHu0701** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月25日(周一) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [secretflow/secretflow] 如何将源码build为docker镜像？ (Issue #1206)




  
编写Dockerfile：在源码的根目录下创建一个名为Dockerfile的文件，并在其中定义构建镜像的指令。Dockerfile是一个文本文件，其中包含了一系列指令，用于告诉Docker如何构建镜像。
 
编写Dockerfile指令：在Dockerfile中可以使用一系列指令来构建镜像，例如FROM、RUN、COPY、CMD等。其中，FROM指令用于指定基础镜像，RUN指令用于在容器中执行命令，COPY指令用于将文件从源码复制到镜像中，CMD指令用于设置容器启动时执行的命令等。
 
执行docker build命令：在终端中使用docker build命令来执行构建镜像的操作。命令的基本格式为：docker build -t <镜像名&gt;:<标签&gt; <Dockerfile所在目录&gt;。其中，-t参数用于指定镜像的名称和标签，<Dockerfile所在目录&gt;指定Dockerfile文件所在的目录。
 
等待构建完成：根据源码的规模和依赖关系，构建过程可能需要一些时间。等待构建完成后，Docker将生成一个新的镜像并将其保存到本地的镜像仓库中。
 
验证镜像：可以使用docker images命令来查看本地的镜像仓库，并验证新构建的镜像是否存在。
 
运行容器：使用docker run命令来运行基于新构建的镜像的容器。命令的基本格式为：docker run -d -p <宿主机端口&gt;:<容器端口&gt; <镜像名&gt;:<标签&gt;。其中，-d参数用于在后台运行容器，-p参数用于指定端口映射关系。
  
这是一个基础的编译教程，可以参考一下。如需更详细的内容可以自行查找。

**Comment by LindaHu0701** [comment]
请问base-ci镜像的源码或dockerFile在哪儿？
<img width="313" alt="image" src="https://github.com/secretflow/secretflow/assets/37866628/a1ce3881-26db-410c-aa84-4d2b34392218">

**Comment by zhouaihui** [comment]
https://github.com/secretflow/devtools/blob/main/dockerfiles/ubuntu-base-ci.DockerFile
