### ISSUE TITLE
GPU支持

### ISSUE THREAD

**Issue by SJTUHGX** [secretflow/secretflow#1208]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secret flow v1.4.0b0

### OS Platform and Distribution

Linux Ubuntu v1.4.0b0

### Python version

3.10.12

### What happend and What you expected to happen.

```shell
按方式2：自行构建GPU Docker镜像，在secretflow/docker文件夹里没有secretflow-gpu.Dockerfile文件，无法构建。
```

### Reproduction code to reproduce the issue.

```shell
Error response from daemon：manifest for secretflow/secretflow-gpu：latest not found：manifest unknow：manifest unknow.
```

**Comment by Mingbo-Lee** [comment]
https://github.com/secretflow/secretflow/blob/main/docker/release/secretflow-gpu.Dockerfile

**Comment by SJTUHGX** [comment]
会卡在=> =>#Geographic area:那步，按了6（6.Asia）回车，没有任何反应。

**Comment by Chrisdehe** [comment]
没理解什么问题，可以展开前后说一下吗？

**Comment by SJTUHGX** [comment]
> https://github.com/secretflow/secretflow/blob/main/docker/release/secretflow-gpu.Dockerfile

用这个路径下的secretflow-gpu.Dockerfile文件，用命令docker build -f secretflow-gpu.Dockerfile -t secret flow-gpu .去build的时候，会一直卡在[2/9] RUN apt-get update && apt-get install -y libcudnn8=8.6.0163-1+cuda11.8...... --allow-change-held-packages。这行在更新或安装某个包的时候，会一直卡在地理区域选择这里，=> =>#Geographic area:那步，按了6（6.Asia）回车，没有任何反应。
![image](https://github.com/secretflow/secretflow/assets/136354142/7d119c00-1c7c-4cbf-aa6d-8e6ee80a1aad)<img width="1003" alt="image" src="https://github.com/secretflow/secretflow/assets/136354142/1e3ed213-9bb4-4e41-b011-9ad6e61d7e66">

**Comment by Chrisdehe** [comment]
检查内存是否不足、版本、依赖是否对应等问题了吗？

**Comment by SJTUHGX** [comment]
应该不存在，你说的内存不足等的的这些问题。因为，我是用一个新机器安装的。我直接docker pull 拉了一个10个月之前发布的那个0.8.2b3版本的镜像，没有任何问题。不知道，和最新的这个版本有什么区别。
![image](https://github.com/secretflow/secretflow/assets/136354142/481fec42-57c4-4ea7-92d3-cf0f64647a8b)
![image](https://github.com/secretflow/secretflow/assets/136354142/39259888-16c2-4a78-bc1d-7b55ab0cf8f1)
![image](https://github.com/secretflow/secretflow/assets/136354142/b65eb8b9-483c-44e8-9f3c-7fb421c11752)

**Comment by Chrisdehe** [comment]
因为GPU版本很早了，跟最新版本的secretflow可能会有兼容性问题，你可以退回前几个版本的secretflow来尝试吗

**Comment by SJTUHGX** [comment]
具体是哪前几个版本呢？是最新发布的v1.5.0dev240312还是v1.4.0b0，这两个版本有GPU支持吗？

**Comment by Chrisdehe** [comment]
这个问题比较复杂，如果你不需要 jax的gpu加速，环境的搭建会简易许多，可以通过技术支持WeChat来沟通（secretflow02）

**Comment by SJTUHGX** [comment]
OK,我加他了。

**Comment by Chrisdehe** [comment]
可以参考一下这方面建设的核心思路
https://b23.tv/vBMBWoV

**Comment by zhangxingmeng** [comment]
你好，可以尝试把docker-file的第一个修改为
```
RUN  export DEBIAN_FRONTEND=noninteractive && \
     apt-get update \
     && apt-get install -y libcudnn8=8.6.0.163-1+cuda11.8 --allow-downgrades --allow-change-held-packages  \
     && apt-get install -y python3.10 --allow-downgrades --allow-change-held-packages   \
     && apt-get install -y python3-pip --allow-downgrades --allow-change-held-packages --no-install-recommends \
```

**Comment by SJTUHGX** [comment]
谢谢，我先试试。

**Comment by SJTUHGX** [comment]
确实能够成功build，但是，遇到一个新问题，run的时候，会发现找不到python。
<img width="1500" alt="image" src="https://github.com/secretflow/secretflow/assets/136354142/77987c97-317b-44f3-b5b1-5feb585b3f0e">

**Comment by zhangxingmeng** [comment]
> 确实能够成功build，但是，遇到一个新问题，run的时候，会发现找不到python。 <img alt="image" width="1500" src="https://private-user-images.githubusercontent.com/136354142/317950142-77987c97-317b-44f3-b5b1-5feb585b3f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTE5NDAsIm5iZiI6MTcxMjA1MTY0MCwicGF0aCI6Ii8xMzYzNTQxNDIvMzE3OTUwMTQyLTc3OTg3Yzk3LTMxN2ItNDRmMy1iNWIxLTVmZWI1ODViM2YwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwOTU0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTMwYzliMzJjYmI4ODA5MGJmZjNhYTNmYmQ1NGIxYjgwYjkyZmNiMjA0OTVkOGQ0MzRjOWQ5NGE2ODA0M2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1UAVQ-SleSr-1ZrVsZFHM2rVh2zB5RmQBaUBjag5Hc0">

https://github.com/secretflow/secretflow/pull/1228 gpu-docker file已修复，可以参考这里的正确版本来build吧。
