### ISSUE TITLE
如何查看参与方之间的交互数据？

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1215]
### Issue Type

Others

### Source

binary

### Secretflow Version

v1.4.0.dev240123

### OS Platform and Distribution

centos7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
如何查看参与方之间交互的数据？我们现在有以下需求：在使用隐语的算法时，需要根据两方的数据交互日志向客户证明出域的数据非原始明文数据，从而证明数据的安全性，以横向联邦学习为例：
Alice和Bob之间执行水平联邦学习https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/Federate_Learning_for_Image_Classification
安全聚合器采用以下：
''secure_aggregator = SecureAggregator(alice, [alice, bob])''
训练流程：
 1. 各个参与方从服务器下载最新的模型 
 2. 每个参与方利用本方的本地数据训练模型，将梯度加密（或者将参数加密）上传给服务器（怎么查看客户端发送出域的数据？）
 3. 服务器得到各方上传上来的加密梯度（加密参数）（怎么查看聚合器接收到的数据？）在服务端进行安全聚合，用聚合后的梯度更新模型参数。
 4. 服务器将更新后的模型返回给各个参与方（需要查看发送数据）
 5. 各个参与方更新各自的模型，准备下一次训练。
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by oceanqdu** [comment]
https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/fl_model.py
`fit()函数中
                    client_param_list.append(client_params)  #此处为将client本地训练的模型参数加入表单？用来后续做聚合？
                    sample_num_list.append(sample_num) 
`
![image](https://github.com/secretflow/secretflow/assets/49178688/4e6bd5b5-74bb-4717-b5c1-01b38e37af99)

**Comment by ian-huu** [comment]
目前还没有好的办法，一种临时的办法是修改代码，在所有调用 `DeviceObject.to(xxU)` 的地方手动打日志，比如说：
``` python
import logging

def log_obj(obj):
    logging.info(obj)

# 如果是 PYUObject，可以这么打印
obj_a.device(log_obj)(obj_a)

obj_a.to(xxx) # 这里是传递数据到 xxx
```

**Comment by oceanqdu** [comment]
根据您给的建议，我在使用水平联邦学习时在fit函数中手动打印了日志。
水平联邦参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/Federate_Learning_for_Image_Classification#%E6%B0%B4%E5%B9%B3%E8%81%94%E9%82%A6%EF%BC%9A%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB

我做了如下改动：
      修改了https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/fl_model.py#L336 中的fit函数，在某些地方手动打印了日志，增加代码如下：
https://github.com/secretflow/secretflow/blob/3b3c6e9181dce4d4a44614c46cee9cfb0eb8c393/secretflow/ml/nn/fl/fl_model.py#L509
在509行进行了日志打印，如图所示增加了以下代码：

![image](https://github.com/secretflow/secretflow/assets/49178688/03ee95a2-12f4-48a4-98b0-8982dc0bffa7)
`
if step ==0:
    for i in range(len(client_param_list)):
        client_param_list[i].device(logging.info)(f'{client_param_list.device} model params is:\n %s ',client_param_list[i])

`
执行水平联邦后查看日志，发现结果如下：
alice:
![image](https://github.com/secretflow/secretflow/assets/49178688/c48a8b9b-502d-4966-82c3-738c26e6e05d)

bob:
![image](https://github.com/secretflow/secretflow/assets/49178688/05bb484c-2a82-4981-8966-52384f46e76c)

按照我的理解，此处打印的日志应该是 alice和bob在本地训练的模型参数，现在打印出来发现两方的本地参数几乎一致，请问这是合理的吗？

**Comment by zhangxingmeng** [comment]
建议你在sf.init里面加上debug=True，试试看
