### ISSUE TITLE
spu修改源码后，生成的whl文件如何替换掉secretflow中已经安装的SPU版本

### ISSUE THREAD

**Issue by iconley** [secretflow/secretflow#1222]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

0.7.18b5

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
首先我从源码安装secretflow，安装成功。同样，我从源码安装SPU，安装成功。他们在不同的容器中都安装成功。
然后，我修改spu部分源码，执行Python setup.py bdist_wheel，生成新的whl安装包。
最后，我想在secretflow的容器中，将原有的spu用新生成的SPU的whl安装包替换，于是我在secretflow的容器中，执行pip install spu-*.whl，同样安装成功。
问题是：
当我import secretflow 时，报错提示找不到bingding文件夹。去安装路径/root/miniconda3/lib/python3.8/site-packages下查看，可以看到这种方法安装的spu和secretflow自带的spu所包含的文件是不一样的。请问如何才能实现替换？
```

### Reproduction code to reproduce the issue.

```shell
同上
```

**Comment by wangzul** [comment]
你可以通过下面的方法测试是否支持
方式1.尝试先执行 pip uninstall spu  ｜ 在执行 pip install spu-*.whl
方式2.移除sf源码中requirements.txt  spu  ｜执行 pip install spu-*.whl  ｜执行sf编译 安装  【注意避免安装错误的sf.whl  文件】

**Comment by iconley** [comment]
还是不行，提示信息如下：

**Comment by iconley** [comment]
还是不行，提示如下：

**Comment by iconley** [comment]
![Uploading 1.png…]()

**Comment by iconley** [comment]
还是不行，提示如下：
(base) [root@558b64755fa0 secretflow]# python
Python 3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import secretflow as sf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mpc/secretflow/secretflow/__init__.py", line 15, in <module>
    from . import data, device, ml, preprocessing, security, utils
  File "/mpc/secretflow/secretflow/data/__init__.py", line 15, in <module>
    from . import horizontal, vertical
  File "/mpc/secretflow/secretflow/data/horizontal/__init__.py", line 15, in <module>
    from .dataframe import HDataFrame
  File "/mpc/secretflow/secretflow/data/horizontal/dataframe.py", line 21, in <module>
    from secretflow.data.base import DataFrameBase, Partition
  File "/mpc/secretflow/secretflow/data/base.py", line 24, in <module>
    from secretflow.device import PYUObject, reveal
  File "/mpc/secretflow/secretflow/device/__init__.py", line 15, in <module>
    from .device import *
  File "/mpc/secretflow/secretflow/device/device/__init__.py", line 16, in <module>
    from .heu import HEU
  File "/mpc/secretflow/secretflow/device/device/heu.py", line 29, in <module>
    from .spu import SPUValueMeta
  File "/mpc/secretflow/secretflow/device/device/spu.py", line 36, in <module>
    import spu.binding._lib.link as spu_link
ModuleNotFoundError: No module named 'spu.binding'

**Comment by iconley** [comment]
(base) [root@558b64755fa0 secretflow]# cd /root/miniconda3/lib/python3.8/site-packages/spu
(base) [root@558b64755fa0 spu]# ls
__init__.py  __pycache__  api.py  libspu.so  psi.py  psi_pb2.py  spu_pb2.py  utils  version.py

可以看到里面没有binding文件夹，而在secretflow自带的spu下可以看到binding文件夹

**Comment by tonywu6** [comment]
@iconley Hi!

确认一下：

- Issue 里面填写了 `secretflow` 版本是 `0.7.18b5`，是的确安装了这个版本吗？你可以在你的 shell 中运行 `python3 -c "from secretflow.version import __version__; print(__version__)"` 查看
    如果的确安装了 `0.7.18b5` 版本：这个版本我们已经不再支持，请先升级到最新版：`python3 -m pip install "secretflow>=1.4.0b0"`

- 你想要修改的是 `secretflow` 包中的 "SPU 代码"（Python 代码），还是 `spu` 包中的 Python 代码，还是 `spu` 的 C++ 源码？取决于想要尝试哪种代码，构建方式会有些不一样

**Comment by iconley** [comment]
@tonywu6 Hi！
我确实安装的是0.7.18b5，比较早的版本，我升级一下试试。
另外我是修改了部分spu包中的c++源码。构建使用Python setup.py bdist_wheel。
