### ISSUE TITLE
VertBinSubstitution.substitution()返回值

### ISSUE THREAD

**Issue by imwangyt** [secretflow/secretflow#1227]
### 文档修改建议

【woe分箱】章节，以下代码中，`substitution`的返回值是Tuple：
```python
vdf = woe_sub.substitution(vdf, bin_rules)
```
应改为：
```python
vdf, _ = woe_sub.substitution(vdf, bin_rules)
```
源码：https://github.com/secretflow/secretflow/blob/e3050b292421405c2ef6c190919974b3cfd82e06/secretflow/preprocessing/binning/vert_bin_substitution.py#L129

ps：方法声明也不对。

<details>
      <summary>技术信息</summary>
      <ul>
        <li>页面 <a href="https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/risk_control_scenario">https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/risk_control_scenario</a></li>
        <li>源码 <a href="https://github.com/secretflow/secretflow/blob/dd349d318f128f1bf6cf31a413ec75110ba333ed/docs/tutorial/risk_control_scenario.ipynb">https://github.com/secretflow/secretflow/blob/dd349d318f128f1bf6cf31a413ec75110ba333ed/docs/tutorial/risk_control_scenario.ipynb</a></li>
        <li>浏览器 <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0</code></li>
      </ul>
    </details>

**Comment by da-niao-dan** [comment]
你好， 没错，vert bin 代码更新了，但是docs 还没改。 欢迎提pr 改，或者我们后续也可修复。

感谢

**Comment by da-niao-dan** [comment]
我们已经修复了，感谢反馈
