### ISSUE TITLE
单机测试水平联邦学习报错：Failed to send data to seq_id ping of bob from ping

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1229]
### Issue Type

Others

### Source

source

### Secretflow Version

1.5.0.dev240319

### OS Platform and Distribution

centos 7.9

### Python version

3.10

### Bazel version

6.5.0

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
单机测试时发现如下异常：
(SenderProxyActor pid=4872) >
(SenderProxyActor pid=4872) 2024-04-03 09:30:17.860 ERROR barriers.py:171 [alice] -- [Anonymous_job] Failed to send data to seq_id ping of bob from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=4872) 	status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=4872) 	details = "Deadline Exceeded"
(SenderProxyActor pid=4872) 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-04-03T09:30:17.859606037+08:00", grpc_status:4}"
(SenderProxyActor pid=4872) >
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
from secretflow.data.horizontal import read_csv

from secretflow.security.aggregation import SecureAggregator
from secretflow.ml.nn import FLModel

# In case you have a running secretflow runtime already.
sf.shutdown()


parties = {
  'alice': {
    'address': '127.0.0.1:3033'
  },
  'bob': {
    'address': '127.0.0.1:3034'
  }
}

cluster_config ={
  'parties': parties,
  'self_party': 'alice'
}


sf.init(address='local', cluster_config=cluster_config)

alice, bob = sf.PYU('alice'), sf.PYU('bob')
hdf = read_csv(filepath={alice: "gonghangFL.csv", bob: "jianhangFL.csv"})
label = hdf["label"]
data = hdf.drop(columns="label")


def create_nn_model():
    def create_model():
        from tensorflow import keras
        from tensorflow.keras import layers

        # Create model
        model = keras.Sequential(name="model")
        model.add(layers.Dense(32, input_dim=5, activation='relu'))
        model.add(layers.Dense(32, input_dim=32, activation='relu'))
        model.add(layers.Dense(1, activation='sigmoid'))

        # Compile model
        model.compile(
            loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"]
        )
        return model

    return create_model


model = create_nn_model()
device_list = [alice, bob]
secure_aggregator = SecureAggregator(alice, [alice, bob])

fed_model = FLModel(device_list=device_list, model=model, aggregator=secure_aggregator)
history = fed_model.fit(
    data,
    label,
    validation_data=(data, label),
    epochs=20,
    batch_size=128,
    aggregate_freq=1,
)
```

**Comment by coderSun20201112** [comment]
然后我又修改了下源码：sf.init(['alice', 'bob'], address='local')
然后提示我这个问题：
(pid=7381) 2024-04-03 10:01:17.111895: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(pid=7381) 2024-04-03 10:01:16.467965: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(pid=7381) 2024-04-03 10:01:17.111948: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)

**Comment by Chrisdehe** [comment]
好的 我复现一下

**Comment by Chrisdehe** [comment]
@coderSun20201112 hey
> parties = {
>  'alice': {
>    'address': '127.0.0.1:3033'
>  },
>  'bob': {
>    'address': '127.0.0.1:3034'
>  }
>}

>cluster_config ={
>  'parties': parties,
>  'self_party': 'alice'
>}

>sf.init(address='local', cluster_config=cluster_config)

这个是生产模式的代码配置方式，单机模式请参考[单机仿真部署](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/getting_started/deployment#standalone-mode-for-simulation)
另外，针对之前测试定制的水平联邦代码，建议先使用pyhton==3.8的secretflow版本

**Comment by coderSun20201112** [comment]
非常感谢老师的悉心指导，给老师添麻烦了，再次感谢！
