### ISSUE TITLE
Secretflow底层通信机制的疑问

### ISSUE THREAD

**Issue by farmerj777** [secretflow/secretflow#1233]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

1.5.0.dev20240325

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.10.14

### GCC/Compiler version

11.2.4

### What happend and What you expected to happen.

```shell
我在查阅以下两个文档之后发现Sectetflow使用的是Ray作为其分布式引擎:
https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/developer/design/architecture
https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/developer/design/programming_in_secretflow
根据文档中给出的实例我发现在本地模拟多参与方，使用的是利用不同端口模拟参与方之间进行进程间的通信。而文档中也给出了隐语并不是照搬Ray的跨机构通信机制，而是在其基础上进行修改和调优实现出RayFed，但是因为文档中没有过多的介绍RayFed的实现，所以在阅读完以上文档后我有两个疑问：
1. RayFed的底层通信机制。RayFed是如何进行进程间通信的？是利用socket还是什么方式进行？
2. 在通信上RayFed相对于Ray做了哪些优化?这些能够在哪些任务中提升时间效率？
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by Chrisdehe** [comment]
@farmerj777 
你好！可以参考一下[隐语的编程思想](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/developer/design/programming_in_secretflow)

**Comment by zhouaihui** [comment]
rayfed解决的是跨机构协作single controller不安全的问题，所以针对的是跨机构之间通信，目前默认是grpc。机构内的任务调度和通信仍然还是ray负责。
 有兴趣可以阅读源码 https://github.com/ray-project/rayfed
