### ISSUE TITLE
Question on the benchmark example, how to generate the data (80w_1500_1500)?

### ISSUE THREAD

**Issue by LiuTxxx** [secretflow/secretflow#1234]
### Issue Type

Documentation Feature Request

### Source

source

### Secretflow Version

latest

### OS Platform and Distribution

Centos 7

### Python version

3.8

### What happend and What you expected to happen.

```shell
When I'm reproduce the 'sf_component_test', dont know how to generate the 80w 1500 data file, is there any script to generate the data file, or the format of the csv file.
我在尝试复现sf_component_test时，不知如何生成里面的80w 1500特征的数据集，请问是否有相关的生成脚本，或者其所用的csv的格式。我使用自己生成的随机文件测试时，出现以下报错：

{"mem_peak": 0, "run_time": 0, "result": null, "error_msg": "run comp err: input attr input/train_dataset/feature_selects check_table_attr_col_cnt fails.", "error_code": -1}
```

### Reproduction code to reproduce the issue.

```shell
{"mem_peak": 0, "run_time": 0, "result": null, "error_msg": "run comp err: input attr input/train_dataset/feature_selects check_table_attr_col_cnt fails.", "error_code": -1}
```

**Comment by Chrisdehe** [comment]
@LiuTxxx 
你好，“80w 1500特征的数据集”所关联的页面辛苦贴一下

**Comment by da-niao-dan** [comment]
Hello, this data is just randomly generated csv. You can generate the data you want or use public datasets. For generating random data, you may find sklearn https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html helpful.

**Comment by LiuTxxx** [comment]
> Hello, this data is just randomly generated csv. You can generate the data you want or use public datasets. For generating random data, you may find sklearn https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html helpful.
> 
> 80w_1500 data means 800000 samples, 1500 feature dimensions each party

thanks for reply.
however, i try to generate the random data, but the benchmark still get error shown in my original post.
is it my format of csv have something wrong? or sth wrong on config?

my format of csv is: id, x1, x2....x1500, y, and i have modified the data.json to fit the input format.

**Comment by da-niao-dan** [comment]
OK, so in the ML train config file, the example (sgb e.g.) is as follows:

```json
{
    "num_boost_round": 10,
    "max_depth": 4,
    "learning_rate": 0.3,
    "objective": "logistic",
    "sketch_eps": 0.007936507936507936,
    "subsample": 1.0,
    "colsample_by_tree": 1.0,
    "input/train_dataset/label": ["y"]
}
```

We should add one line based on your data, like this:

```json
{
    "num_boost_round": 10,
    "max_depth": 4,
    "learning_rate": 0.3,
    "objective": "logistic",
    "sketch_eps": 0.007936507936507936,
    "subsample": 1.0,
    "colsample_by_tree": 1.0,
    "input/train_dataset/feature_selects: [f"x{i}" for i in range(1, 1501)],
    "input/train_dataset/label": ["y"]
}
```
