### ISSUE TITLE
The current version does not support HEU standalone deployment mode

### ISSUE THREAD

**Issue by LiuTxxx** [secretflow/secretflow#1237]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.4.0.dev24011601, 1.4.0b0, 1.5.0.dev20240321

### OS Platform and Distribution

Centos 7

### Python version

3.8 for sf_1.4.0*, 3.10 for sf_1.5.0

### What happend and What you expected to happen.

```shell
When trying to benchmark the sgb_train/predict, seems the version is incompatible or something. The error info is pasted below in code part.
Is this happened because of wrong version (I tried 3 version of sf) or I should use other deployment way other than HEU standalone mode.
BTW, besides from HEU standalone mode, how can i try other deployment mode.
```

### Reproduction code to reproduce the issue.

```shell
{"mem_peak": 0, "run_time": 0, "result": null, "error_msg": "run comp err: The current version does not support HEU standalone deployment mode", "error_code": -1}
```

**Comment by da-niao-dan** [comment]
Hi, first let's explain the error for future reference:

HEU standalone mode means the secret key keeper and evaluators contain only one party.
```
assert (
            'sk_keeper' in self.config
        ), f"The current version does not support HEU standalone deployment mode"
        assert (
            'evaluators' in self.config and len(self.config['evaluators']) > 0
        ), f"The current version does not support HEU standalone deployment mode"
```

For SGB train, the label holder party will be assigned as sk_keeper while other parties will be assigned as evaluators.
```
heu = heu_from_base_config(
        ctx.heu_config,
        label_party,
        [p.party for p in x.partitions if p.party != label_party],
    )
```

This error may raise if you try to train sgb in a single party. (There are no evaluators.)

**Comment by LiuTxxx** [comment]
> Hi, first let's explain the error for future reference:
> 
> HEU standalone mode means the secret key keeper and evaluators contain only one party.
> 
> ```
> assert (
>     'sk_keeper' in self.config
> ), f"The current version does not support HEU standalone deployment mode"
> assert (
>     'evaluators' in self.config and len(self.config['evaluators']) > 0
> ), f"The current version does not support HEU standalone deployment mode"
> ```
> 
> For SGB train, the label holder party will be assigned as sk_keeper while other parties will be assigned as evaluators.
> 
> ```
> heu = heu_from_base_config(
>     ctx.heu_config,
>     label_party,
>     [p.party for p in x.partitions if p.party != label_party],
> )
> ```
> 
> This error may raise if you try to train sgb in a single party. (There are no evaluators.)

Hi, thanks for reply, that helps a lot.
