### ISSUE TITLE
关于Secretflow进行安全多方计算的疑问

### ISSUE THREAD

**Issue by farmerj777** [secretflow/secretflow#1245]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.5.0.dev20240325

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.10.14

### What happend and What you expected to happen.

```shell
1. 我想知道我将数据从PYU导入到SPU时，是通过什么机制保证SPU不会掌握PYU的原始数据的呢？ 举个例子，假如我有1000个PYU (每个PYU上都有数据)和由5个SPU组成的隐私集群。每个PYU的数据不愿意告知其他PYU或者任何SPU的隐私信息，那么在将数据导入到SPU时，其是否会通过“切分”成碎片的形式保证每个SPU都无法获得信息，然后需要让所有SPU联合在一起才能获得信息(也就是安全多方计算期望达到的效果)? 如果有这种“切分”机制的话其底层具体用的是哪种切分机制？
2. 正如上面那个例子所说，我的需求可能需要有1000个PYU来分别存储自己的数据(可以理解为1000个服务器各自有隐私配置不愿意让其他人看到)，那么有没有快速定义1000个PYU的方法？还是需要逐个命名(比如用alice_1，alice_2 ... alice_1000)这样的方式才能创建1000个PYU？
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by ian-huu** [comment]
1. 是的，没有什么特别的机制，就是代码实现保证的，在 PYUObject.to(spu_device) 的底层实现中，该 PYUObject 会由所在的 PYU 负责随机分片，并发送给 spu_device 对应的各个物理机器，在这个过程中只有对应的 PYU 有所有信息，其他人拿到的都是分片后的随机数
2. 目前 secretflow 只支持 cross-silo 场景，也就是比较稳定的集群架构下（一般来说是机构之间，而不是手机这种设备之间）的隐私计算任务，1000 个 PYU 的场景在实际生产模式部署中不太可行（网络结构过于复杂，稳定性成疑）。如果只是 simulation 模式做实验的话，你可以用简单的 for 循环来定义多个 PYU：
```python
import secretflow as sf

party_names = [f"p{i}" for i in range(1000)]
sf.init(parties=party_names, address='local')

pyus = [sf.PYU(name) for name in party_names]
```

不过这么多 PYU 的任务可能需要比较高配置的机器，你可以先尝试一下

**Comment by farmerj777** [comment]
> 1. 是的，没有什么特别的机制，就是代码实现保证的，在 PYUObject.to(spu_device) 的底层实现中，该 PYUObject 会由所在的 PYU 负责随机分片，并发送给 spu_device 对应的各个物理机器，在这个过程中只有对应的 PYU 有所有信息，其他人拿到的都是分片后的随机数
> 2. 目前 secretflow 只支持 cross-silo 场景，也就是比较稳定的集群架构下（一般来说是机构之间，而不是手机这种设备之间）的隐私计算任务，1000 个 PYU 的场景在实际生产模式部署中不太可行（网络结构过于复杂，稳定性成疑）。如果只是 simulation 模式做实验的话，你可以用简单的 for 循环来定义多个 PYU：
> 
> ```python
> import secretflow as sf
> 
> party_names = [f"p{i}" for i in range(1000)]
> sf.init(parties=party_names, address='local')
> 
> pyus = [sf.PYU(name) for name in party_names]
> ```
> 
> 不过这么多 PYU 的任务可能需要比较高配置的机器，你可以先尝试一下

好的，非常感谢你细致的回答！

**Comment by ian-huu** [comment]
分片方式依赖于目标 spu 配置的协议，不同协议会有不同的分片方式：https://www.secretflow.org.cn/zh-CN/docs/spu/0.8.0b0/reference/mpc_status

**Comment by farmerj777** [comment]
感谢你以上的回答！接着以上的背景，我在具体进行实验的时候发现了一个问题：如果我现在要将这1000个PYUs的数据以密文形式存在同一个SPU设备以方便后续计算时，我对于如何在密文中将数组“升维”产生了疑问，具体而言：

**Comment by farmerj777** [comment]
感谢你以上的回答！接着以上的背景，我在具体进行实验的时候发现了一个问题：如果我现在要将这1000个PYUs的数据以密文形式存在同一个SPU设备以方便后续计算时，我对于如何在密文中将数组“升维”产生了疑问。具体而言：首先我现在有1000个PYUs的输入数据，他们以不同数组的形式以文件读入进PYU中，例子如下所示: <br/>  def InputMatrixDataToPYU(i):
    // read data <br/> .....  <br/> // read data 
&emsp;     return TestArray1,TestArray2.... TestArrayk  <br/>  对于这些数据我分别用一个PYU设备接受它 (pyus[i] = pyus[i](InputMatrixDataToPYU)(i) )，并将其提供给同一密文设备（我期望让result_spu）接收：<br/> for i in range(50):
&emsp;     i_array = [i]
&emsp;     alice_spu = pyus[i].to(spu_device)
&emsp;     i_spu = sf.to(dave,i_array).to(spu_device)
&emsp;     result_spu = spu_device(InputMatrixDataToSPU)(alice_spu,i)  ；但现在的问题是当我期望把数据导入进spu时，<br/>def InputMatrixDataToSPU(x,i):
&emsp;     return x[i][...][...] <br/>发现无法用输入函数作为下标的(因为被traced了)，请问一下我该如何把这些PYU的数据全部导入到同一SPU下且保证不会泄露隐私？

**Comment by ian-huu** [comment]
你的代码有点看不太清，我给一个简单的例子：
```py


pyus = [sf.PYU(name) for name in party_names]
spu = sf.SPU(...)

def load_data_to_pyu():
    return np.array([1,2,3])

# 各个 pyu 读取数据
pyu_objs = []
for pyu in pyus:
    obj = pyu(load_data_to_pyu)()
    pyu_objs.append(obj)

# 把所有数据放到 spu
spu_objs = []
for pyu_obj in pyu_objs:
    # 这一步已经完成了数据从 pyu 到 spu 的过程
    spu_obj = pyu_obj.to(spu)
    spu_objs.append(spu_obj)

def process_data_in_spu(objs):
    ...

# 在 spu 上处理数据
spu(process_data_in_spu)(spu_objs)
```

**Comment by farmerj777** [comment]
> 你的代码有点看不太清，我给一个简单的例子：
> 
> ```python
> pyus = [sf.PYU(name) for name in party_names]
> spu = sf.SPU(...)
> 
> def load_data_to_pyu():
>     return np.array([1,2,3])
> 
> # 各个 pyu 读取数据
> pyu_objs = []
> for pyu in pyus:
>     obj = pyu(load_data_to_pyu)()
>     pyu_objs.append(obj)
> 
> # 把所有数据放到 spu
> spu_objs = []
> for pyu_obj in pyu_objs:
>     # 这一步已经完成了数据从 pyu 到 spu 的过程
>     spu_obj = pyu_obj.to(spu)
>     spu_objs.append(spu_obj)
> 
> def process_data_in_spu(objs):
>     ...
> 
> # 在 spu 上处理数据
> spu(process_data_in_spu)(spu_objs)
> ```

好的我理解了您的例子。不过我想请问一下如果我有非常多的pyu，想要输入给SPU，那么在循环中其是串行执行还是能够并发执行？因为这些pyus没有数据依赖，有没有办法使其通过并发或者其他方法更快的输入到SPU中？

**Comment by ian-huu** [comment]
这是个好问题，上面的代码可以分两部分来看：
一部分是 pyu_objs、spu_objs 涉及到的代码（for 循环等），这部分是 `driver` 代码；
另一部分是 load_data_to_pyu 和 process_data_in_spu 这些函数内的实际执行计算的代码，叫做 `worker` 代码。

`driver` 代码实际上是对计算逻辑的一些"编排"，他把实际的`worker` 代码串联成一个计算图(dag)，这个计算图中的节点只要没有依赖，都是可以并发执行的，实际上也是并发执行的。而 `driver` 代码那个 for 循环只负责生成计算图，所以执行时间可以忽略不计。

实际执行分为两种情况,
[仿真模式](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.5.0b0/getting_started/deployment#simulation):  在单 ray 集群内，易用 ray 的 task 异步执行能力实现没依赖的节点并发执行。
[生产模式](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.5.0b0/getting_started/deployment#production): 在多个 ray 集群内，每一方分别执行各自的代码，pyu 的部分没有依赖所以天然就是并发执行的。

**Comment by farmerj777** [comment]
根据您的回答，我的理解是只要worker代码没有依赖那么可以并发执行，其使用了os.fork()和jax来实现multithreade。但我在进行输入实验时发现只有一个CPU核心在进行工作，通过htop我发现其只在单核上运行。 ![image](https://github.com/secretflow/secretflow/assets/57624631/273713dd-a801-42b7-8e28-5958a0e3adba)  问题如下:  <br />1. 我试图使用multiprocessing.Pool来试图进行multiprocess编程，但我不清楚这是否会导致死锁? <br />2.  我的代码中是否含有依赖？( 我认为我的代码没有，理论上应该可以并发执行，但是根据打印的中间结果发现for循环是顺序执行的)  <br />3. 我试图采用在SPU_config中切换'protocol'和 'field'来尝试减少时间开销，请问下有没有文档提供所有可选的protocol和field?  <br />以下是我的代码:<br />  <pre><code>def InputMatrixDataToPYU(Index):
    file_path = "/home/secretflow/InputDataset/Input-P" + str(Index) + "-0"  # 文件的绝对路径
    #print(file_path)
    with open(file_path, "r") as file:
        data = file.read()  # 读取文件内容
    MetaRows = data.split("\n")  # 按行切分数据

    cnt = 0
    array1 = []
    array2 = []
    array3 = []
    array4 = []
    array5 = []
    
    for row in MetaRows:
        cnt = cnt + 1
        if cnt > 6:
            break

        if row.strip() == "":
            continue
        if cnt == 1:
            for i in range(len(values)):
                array1.append(values[i])
            N = len(values)
        if cnt == 2:
            for i in range(len(values)):
                array2.append(values[i])
        if cnt == 3:
            for i in range(len(values)):
                array3.append(values[i])
        if cnt == 4:
            for i in range(len(values)):
                array4.append(values[i])
        if cnt == 5:
            for i in range(len(values)):
                array5.append(values[i])
    
    array6 =  [ [ [_ for _ in range(5)]  for _ in range(10)] for _ in range(N)]
    array7 =  [ [ [_ for _ in range(5)]  for _ in range(10)] for _ in range(N)]
    ...
    ...
    array15 = [ [ [_ for _ in range(5)]  for _ in range(10)] for _ in range(N)]
    
    
    Tail = 0
    """
    process array6-array15
    """     
    return array1,...array15

if __name__ == "__main__":
    for i in range(50):
        temp_spu = pyus[i].to(spu_device)
        result_spus.append(temp_spu)
</code></pre>

**Comment by ian-huu** [comment]
> 根据您的回答，我的理解是只要worker代码没有依赖那么可以并发执行，其使用了os.fork()和jax来实现multithreade。但我在进
> ...
> result_spus.append(temp_spu)
> `

能给一下完整一点的代码吗？不需要全部代码，但是麻烦提供关键部分的代码，比如 pyus 是什么从哪里来的。


另外代码建议使用 markdown 格式，保证格式显示正确：

\`\`\`python
def func():
&nbsp;&nbsp;&nbsp;&nbsp;return 1
\`\`\`

**Comment by farmerj777** [comment]
```python
def InputMatrixDataToPYU(Index):
    file_path = "/home/secretflow/InputDataset/Input-P" + str(Index) + "-0"  
    with open(file_path, "r") as file:
        data = file.read()  
    RawRows = data.split("\n")  
    MetaRows = []
    cnt = 0

    cnt = 0
    array1 = []
    array2 = []
    array3 = []
    array4 = []
    array5 = []

    for row in MetaRows:
        cnt = cnt + 1
        if cnt > 6:
            break

        if row.strip() == "":
            continue
        if cnt == 1:
            for i in range(len(values)):
                array1.append(values[i])
            N = len(values)
        if cnt == 2:
            for i in range(len(values)):
                array2.append(values[i])
        if cnt == 3:
            for i in range(len(values)):
                array3.append(values[i])
        if cnt == 4:
            for i in range(len(values)):
                array4.append(values[i])
        if cnt == 5:
            for i in range(len(values)):
                array5.append(values[i])

    array6 =  [ [ [_ for _ in range(5)]  for _ in range(10)] for _ in range(N)]
    array7 =  [ [ [_ for _ in range(5)]  for _ in range(10)] for _ in range(N)]
    ...
    ...
    array15 = [ [ [_ for _ in range(5)]  for _ in range(10)] for _ in range(N)]
    Tail = 0
    """
    process array6-array15
    """           
    return array1,...array15
if __name__ == "__main__":
    party_names = [f"p{i}" for i in range(52)]
    sf.init(parties=party_names, address='local')
    pyus = [sf.PYU(name) for name in party_names]

    aby3_config = sf.utils.testing.cluster_def(parties=['p0', 'p1', 'p2','p3','p4'])
    cheetah_config = sf.utils.testing.cluster_def(
        parties=['p0', 'p1', 'p2','p3','p4'],
        runtime_config={
            'protocol': 4,
            'field': 3,
        },
    )
    spu_device = sf.SPU(cheetah_config)
    for i in range(50):
        pyus[i] = pyus[i](InputMatrixDataToPYU)(i)
    result_spus = []
    for i in range(50):
        temp_spu = pyus[i].to(spu_device)
        result_spus.append(temp_spu)
```

**Comment by ian-huu** [comment]
推测可能是因为 ray 的 [object-spilling](https://docs.ray.io/en/latest/ray-core/objects/object-spilling.html)，可以看一下运行过程中有没有类似的进程，如果数据比较大的话比较容易触发 object-spilling。

此外 spu_device 可能会成为瓶颈，他的处理能力是有限的（背后是几个固定的进程），但是这里是这个原因的可能性不大。

这一步的并发执行应该是没有问题的：`pyus[i](InputMatrixDataToPYU)(i)`
