### ISSUE TITLE
基于生产模式部署时，关于“每个机构都需要同时执行代码”的疑问

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1246]
### Issue Type

Others

### Source

source

### Secretflow Version

1.5.0.dev240319

### OS Platform and Distribution

centos 7.9

### Python version

3.10

### Bazel version

6.5.0

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
在基于生产模式部署时，官方提及要每个机构都需要同时执行代码，我有如下疑问：
1、基于Kuscia部署时，是每个机构自己触发执行代码，还是Kuscia自己触发？
2、基于Ray部署时，是每个机构自己触发执行代码，还是Ray集群自己触发？
3、如果是每个机构自己触发执行的话，是不是该机构要新开发一套系统来完成这个触发动作？
4、既然是提到同时执行，这对时间要求非常严格吗？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by ian-huu** [comment]
1. 不太理解 “每个机构自己触发执行代码，还是Kuscia自己触发” 的区别，如果使用 kuscia，那么每个机构都会有 kuscia 节点，在运行任务时，每个机构的 kuscia 节点会各自负责拉起 secretflow，所以可以认为是 kuscia 在每个机构各自触发的
2. 如果不用 kuscia，那么需要每个机构自己想办法各自触发，ray 本身没有这种触发机制
3. kuscia 可以解决这个问题，当然也可以自己开发
4. 这个取决于超时配置，secretflow 在任务启动前会先进行握手，只要启动间隔没有超过握手的超时时间即可

**Comment by coderSun20201112** [comment]
明白了，谢谢老师
