### ISSUE TITLE
【文档】SPU基础的一个问题： 如何防止另外一个参与方调用sf.reveal

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretflow#1250]
### Issue Type

Bug

### Source

binary

### Secretflow Version

main

### OS Platform and Distribution

Windows

### Python version

3.9

### What happend and What you expected to happen.

我看[SPU基础的文档](https://www.secretflow.org.cn/zh-CN/docs/secretflow/main/tutorial/spu_basics#%E6%AD%A5%E9%AA%A42%EF%BC%9A%E5%B0%86SPU%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6%E5%92%8C%E7%A7%98%E5%AF%86%E5%88%86%E4%BA%AB%E5%88%86%E9%85%8D%E7%BB%99SPU%E5%8F%82%E4%B8%8E%E6%96%B9%E3%80%82)。

假设两方Alice 和Bob， Alice 如何防止Bob直接调用sf.reveal呢?

host 究竟怎么理解？跟alice/bob有什么不同

**Comment by tpppppub** [comment]
请参考 #26
