### ISSUE TITLE
【文档】真是部署中，数据是怎么传输的

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretflow#1251]
Hi
我在看文档使用[SPU进行逻辑回归](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/lr_with_spu#%E4%BD%BF%E7%94%A8-SPU-%E8%BF%9B%E8%A1%8C%E9%80%BB%E8%BE%91%E5%9B%9E%E5%BD%92)。

我理解，该文档对应的是单机演示环境的。那我有如下几个问题，

假设两方Alice（192.168.1.2  有x_1） 和Bob（192.168.1.3 有x_2 和y）

1.  该文档的代码，是在Alice 执行还是在Bob执行
2. 假设是在Alice执行，那Bob的 x_2 和y 如何传递给Alice（或Alice的代码应该做怎样的调整？）即要在Alice的机器上执行什么操作，在Bob的机器上执行什么操作？

### Reproduction code to reproduce the issue.

```shell
1
```

**Comment by anakinxc** [comment]
请查看[这个文档](https://www.secretflow.org.cn/en/docs/spu/0.9.0b1/development/runtime#vm-layout)
