### ISSUE TITLE
在单机仿真模式中，如何将某一方的输出 到控制台？

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretflow#1255]
Hi， 我在看[如何开发明密文混合编程](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/programming_guide)
我用的是单机 仿真模式，1.4.0b0版本的隐语

文档中有提到“在开发过程中，我们可以用 sf.reveal（也就是把数据公开出来）的方式拿到真实的数据，然后打印出来。”

```
def print_data(msg, data):
    print(f'{msg}: {data}')


_ = alice(print_data)('alice_data', alice_data)
```

但是我的控制台并没有输出：
`(_run pid=3908759) alice_data: [ 6  7  8  9 10]`

我只有SPU相关的输出`<secretflow.device.device.pyu.PYUObject at 0x7f2a900c12b0>`

请问如何得到上述进程的输出呢

**Comment by ian-huu** [comment]
你是用 jupyter 运行的还是 python 脚本？如果是 python 脚本的话，可能是因为 print 语句是在另外的进程中执行的，所以没有打印出来。

推荐直接使用 jupyter notebook，文档对应的源码在：https://github.com/secretflow/secretflow/blob/main/docs/tutorial/programming_guide.ipynb

如果需要直接运行 python 脚本，可以把 print 改成 logging

**Comment by gxcuit** [comment]
> 你是用 jupyter 运行的还是 python 脚本？如果是 python 脚本的话，可能是因为 print 语句是在另外的进程中执行的，所以没有打印出来。
> 
> 推荐直接使用 jupyter notebook，文档对应的源码在：https://github.com/secretflow/secretflow/blob/main/docs/tutorial/programming_guide.ipynb
> 
> 如果需要直接运行 python 脚本，可以把 print 改成 logging

用的是jupyter notebook。 感谢！
