### ISSUE TITLE
关于ECDH-PSI (3P)的UML时序图，请老师帮忙审核一下看看是否有问题

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1257]
### Issue Type

Others

### Source

source

### Secretflow Version

1.5.0.dev240319

### OS Platform and Distribution

centos 7.9

### Python version

3.10

### Bazel version

6.5.0

### GCC/Compiler version

11.2.1

### What happend and What you expected to happen.

```shell
基于ECDH-PSI(3P)算法，画了一个整体的UML时序图，但我不知道对不对，因此，希望老师帮忙看一下，指出问题
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by coderSun20201112** [comment]
![ECDH](https://github.com/secretflow/secretflow/assets/74349453/97139db8-096a-4740-a5c3-8e1fa3c64b15)

**Comment by 6fj** [comment]
hi @coderSun20201112 

时序图看上去没有问题

**Comment by coderSun20201112** [comment]
好的，谢谢老师
