### ISSUE TITLE
关于使用联邦学习框架定义模型时加入批量归一化层(BN)层会报错

### ISSUE THREAD

**Issue by OkayYang** [secretflow/secretflow#1264]
### Issue Type

Bug

### Source

binary

### Secretflow Version

main分支

### OS Platform and Distribution

Ubuntu 22.04.3 LTS

### Python version

Python 3.10.14

### Bazel version

bazel 6.5.0

### GCC/Compiler version

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### What happend and What you expected to happen.

```shell
加入bn层后运行联邦学习策略就会报错：ray.exceptions.RayTaskError(AssertionError): ray::_Masker.mask() (pid=140976, ip=172.26.198.224, actor_id=2d8c188d34ee05b99dbf726b01000000, repr=<secretflow.security.aggregation.secure_aggregator._Masker object at 0x7f48d36915d0>)
  File "/home/yang/PycharmProjects/pr/secretflow/secretflow/device/proxy.py", line 76, in wrapper
    return method(*args, **kwargs)
  File "/home/yang/PycharmProjects/pr/secretflow/secretflow/security/aggregation/secure_aggregator.py", line 74, in mask
    datum.dtype == dtype
AssertionError: Data should have same dtypes but got int64 float32.
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf

# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob', 'charlie'], address='local')
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')
from secretflow.ml.nn.core.torch import (
    metric_wrapper,
    optim_wrapper,
    BaseModule,
    TorchModel,
)
from secretflow.ml.nn import FLModel
from torchmetrics import Accuracy, Precision
from secretflow.security.aggregation import SecureAggregator
from secretflow.utils.simulation.datasets import load_mnist
from torch import nn, optim
from torch.nn import functional as F
class ConvNet(BaseModule):
    """Small ConvNet for MNIST with Batch Normalization."""
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 3, kernel_size=3)
        self.bn1 = nn.BatchNorm2d(3)
        self.fc_in_dim = 192
        self.fc = nn.Linear(self.fc_in_dim, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(self.bn1(x))
        x = F.max_pool2d(x, 3)
        x = x.view(-1, self.fc_in_dim)
        x = self.fc(x)
        return F.softmax(x, dim=1)

(train_data, train_label), (test_data, test_label) = load_mnist(
    parts={alice: 0.4, bob: 0.6},
    normalized_x=True,
    categorical_y=True,
    is_torch=True,
)

loss_fn = nn.CrossEntropyLoss
optim_fn = optim_wrapper(optim.Adam, lr=1e-2)
model_def = TorchModel(
    model_fn=ConvNet,
    loss_fn=loss_fn,
    optim_fn=optim_fn,
    metrics=[
        metric_wrapper(Accuracy, task="multiclass", num_classes=10, average='micro'),
        metric_wrapper(Precision, task="multiclass", num_classes=10, average='micro'),
    ],
)
device_list = [alice, bob]
server = charlie
aggregator = SecureAggregator(server, [alice, bob])

# spcify params
fl_model = FLModel(
    server=server,
    device_list=device_list,
    model=model_def,
    aggregator=aggregator,
    strategy='fed_avg_w',  # fl strategy
    backend="torch",  # backend support ['tensorflow', 'torch']
)
history = fl_model.fit(
    train_data,
    train_label,
    validation_data=(test_data, test_label),
    epochs=20,
    batch_size=32,
    aggregate_freq=1,
)
```

**Comment by OkayYang** [comment]
感谢你的回复，我是在OSCP中认领了实现FedBN策略这个任务，发现你们最新代码中已经加入了skip_bn参数，我看源码聚合和更新权重的时候会先检查这个参数，这应该就是FedBN算法的实现吧，或许我漏掉了需要完善的信息吗？感谢你的指导。

**Comment by OkayYang** [comment]
> hi，BN算法比较特殊，在Aggragator中不能直接对weight做平均，所以会报错。BN算法不需要做聚合，目前FlModel中专门提供了跳过BN做聚合的参数，用法如下：
> 
> 
> 
> ``` python
> 
> fl_model = FLModel(
> 
>     server=server,
> 
>     device_list=device_list,
> 
>     model=model_def,
> 
>     aggregator=aggregator,
> 
>     strategy='fed_avg_w',  # fl strategy
> 
>     backend="torch",  # backend support ['tensorflow', 'torch'],
> 
>     skip_bn=True
> 
> )
> 
> 
> 
> ```
> 
> 但目前skip_bn实现上还有一点问题，会尽快修复该问题。
> 
> 

感谢你的回复，我是在OSCP中认领了实现FedBN策略这个任务，发现你们最新代码中已经加入了skip_bn参数，我看源码聚合和更新权重的时候会先检查这个参数，这应该就是FedBN算法的实现吧，或许我漏掉了需要完善的信息吗？感谢你的指导。

**Comment by zhangxingmeng** [comment]
> > hi，BN算法比较特殊，在Aggragator中不能直接对weight做平均，所以会报错。BN算法不需要做聚合，目前FlModel中专门提供了跳过BN做聚合的参数，用法如下：
> > ```python
> > fl_model = FLModel(
> > 
> >     server=server,
> > 
> >     device_list=device_list,
> > 
> >     model=model_def,
> > 
> >     aggregator=aggregator,
> > 
> >     strategy='fed_avg_w',  # fl strategy
> > 
> >     backend="torch",  # backend support ['tensorflow', 'torch'],
> > 
> >     skip_bn=True
> > 
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但目前skip_bn实现上还有一点问题，会尽快修复该问题。
> 
> 感谢你的回复，我是在OSCP中认领了实现FedBN策略这个任务，发现你们最新代码中已经加入了skip_bn参数，我看源码聚合和更新权重的时候会先检查这个参数，这应该就是FedBN算法的实现吧，或许我漏掉了需要完善的信息吗？感谢你的指导。

对的，这个就是我们这边对fedbn的实现，可以帮忙double check一下看看实现有没有什么问题，欢迎一起讨论。

**Comment by OkayYang** [comment]
> > > hi，BN算法比较特殊，在Aggragator中不能直接对weight做平均，所以会报错。BN算法不需要做聚合，目前FlModel中专门提供了跳过BN做聚合的参数，用法如下：
> 
> > > ```python
> 
> > > fl_model = FLModel(
> 
> > > 
> 
> > >     server=server,
> 
> > > 
> 
> > >     device_list=device_list,
> 
> > > 
> 
> > >     model=model_def,
> 
> > > 
> 
> > >     aggregator=aggregator,
> 
> > > 
> 
> > >     strategy='fed_avg_w',  # fl strategy
> 
> > > 
> 
> > >     backend="torch",  # backend support ['tensorflow', 'torch'],
> 
> > > 
> 
> > >     skip_bn=True
> 
> > > 
> 
> > > )
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > 但目前skip_bn实现上还有一点问题，会尽快修复该问题。
> 
> > 
> 
> > 感谢你的回复，我是在OSCP中认领了实现FedBN策略这个任务，发现你们最新代码中已经加入了skip_bn参数，我看源码聚合和更新权重的时候会先检查这个参数，这应该就是FedBN算法的实现吧，或许我漏掉了需要完善的信息吗？感谢你的指导。
> 
> 
> 
> 对的，这个就是我们这边对fedbn的实现，可以帮忙double check一下看看实现有没有什么问题，欢迎一起讨论。

好的，感谢🙏

**Comment by fy222fy** [comment]
#1267 修复了skip_bn没有正确执行的问题

@OkayYang 感谢反馈的问题以及对隐语联邦学习的支持，欢迎认领其他发布的OSCP任务~
