### ISSUE TITLE
运行官方文档例子出错 ModuleNotFoundError: No module named 'secretflow.ml.boost.ss_xgb_v'

### ISSUE THREAD

**Issue by xiaojiu1414** [secretflow/secretflow#128]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.6.13b1

### OS Platform and Distribution

Ubuntu 18.04

### Python version

Python：3.8

### What happend and What you expected to happen.

```shell
/app/venv/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [4], line 7
      5 import spu
      6 import secretflow as sf
----> 7 from secretflow.ml.boost.ss_xgb_v import Xgb
      8 from secretflow.device.driver import wait, reveal
      9 from secretflow.data import FedNdarray, PartitionWay

ModuleNotFoundError: No module named 'secretflow.ml.boost.ss_xgb_v'
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging

import spu
import secretflow as sf
from secretflow.ml.boost.ss_xgb_v import Xgb
from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay

from sklearn.metrics import roc_auc_score


# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# init all nodes in local Standalone Mode.
sf.init(['alice', 'bob', 'carol'])

# init PYU, the Python Processing Unit, process plaintext in each node.
alice = sf.PYU('alice')
bob = sf.PYU('bob')
carol = sf.PYU('carol')

# init SPU, the Secure Processing Unit,
#           process ciphertext under the protection of a multi-party secure computing protocol
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))

# read data in each party
def read_x(start, end):
    from sklearn.datasets import load_breast_cancer
    x = load_breast_cancer()['data']
    return x[:, start:end]

def read_y():
    from sklearn.datasets import load_breast_cancer
    return load_breast_cancer()['target']

# alice / bob / carol each hold one third of the features of the data
v_data = FedNdarray(
    partitions={
        alice: alice(read_x)(0, 10),
        bob: bob(read_x)(10, 20),
        carol: carol(read_x)(20, 30),
    },
    partition_way=PartitionWay.VERTICAL,
)
# Y label belongs to alice
label_data = FedNdarray(
    partitions={alice: alice(read_y)()},
    partition_way=PartitionWay.VERTICAL,
)
# wait IO finished
wait([p.data for p in v_data.partitions.values()])
wait([p.data for p in label_data.partitions.values()])

# run SS-XGB
xgb = Xgb(spu)
start = time.time()
params = {
    # for more detail, see Xgb API doc
    'num_boost_round': 5,
    'max_depth': 5,
    'learning_rate': 0.1,
    'sketch_eps': 0.08,
    'objective': 'logistic',
    'reg_lambda': 0.1,
    'subsample': 1,
    'colsample_bytree': 1,
    'base_score': 0.5,
}
model = xgb.train(params, v_data, label_data)
logging.info(f"train time: {time.time() - start}")

# Do predict
start = time.time()
# Now the result is saved in the spu by ciphertext
spu_yhat = model.predict(v_data)
# reveal for auc test.
yhat = reveal(spu_yhat)
logging.info(f"predict time: {time.time() - start}")
y = read_y()
logging.info(f"auc: {roc_auc_score(y, yhat)}")
```

**Comment by zhouaihui** [comment]
你需要升级SecretFlow
```
pip install -U secretflow
```

**Comment by xiaojiu1414** [comment]
>

**Comment by xiaojiu1414** [comment]
> 你需要升级SecretFlow
> 
> ```
> pip install -U secretflow
> ```

更新了，重启了notebook，但仍然是这个报错

**Comment by zhouaihui** [comment]
可以看下你升级后的SecretFlow版本，现在最新的应该是0.7.7b1

**Comment by xiaojiu1414** [comment]
> 可以看下你升级后的SecretFlow版本，现在最新的应该是0.7.7b1

! pip list

Package                      Version
---------------------------- ----------
absl-py                      1.0.0
aiobotocore                  2.1.2
aiohttp                      3.8.2
aioitertools                 0.11.0
aiosignal                    1.2.0
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        22.1.0
botocore                     1.23.24
cachetools                   5.2.0
certifi                      2022.9.14
charset-normalizer           2.1.1
chex                         0.1.5
click                        8.0.4
cloudpickle                  2.0.0
coverage                     6.4.4
cycler                       0.11.0
dgl                          0.9.1
dill                         0.3.4
distlib                      0.3.6
dm-tree                      0.1.7
filelock                     3.8.0
flatbuffers                  2.0.7
flax                         0.4.1
fonttools                    4.37.3
frozenlist                   1.3.1
fsspec                       2022.1.0
gast                         0.4.0
google-auth                  2.11.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.56.4
grpcio                       1.48.1
h5py                         3.7.0
idna                         3.4
importlib-metadata           4.12.0
importlib-resources          5.9.0
jax                          0.3.7
jaxlib                       0.3.7
jmespath                     0.10.0
joblib                       1.2.0
jsonschema                   4.16.0
keras                        2.7.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
libclang                     14.0.6
loguru                       0.6.0
lxml                         4.9.1
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.5.2
msgpack                      1.0.4
multidict                    5.2.0
multiprocess                 0.70.12.2
networkx                     2.8.6
numpy                        1.22.3
oauthlib                     3.2.1
opt-einsum                   3.3.0
optax                        0.1.3
packaging                    21.3
pandas                       1.4.0
patsy                        0.5.2
Pillow                       9.2.0
pip                          22.0.4
pkgutil_resolve_name         1.3.10
platformdirs                 2.5.2
promise                      2.3
protobuf                     3.19.4
psutil                       5.9.0
pyarrow                      9.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
pyrsistent                   0.18.1
python-dateutil              2.8.2
pytz                         2022.2.1
PyYAML                       6.0
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
s3fs                         2022.1.0
scikit-learn                 1.0.2
scipy                        1.9.1
secretflow                   0.7.7b1
secretflow-ray               2.0.0.dev1
setuptools                   57.5.0
sf_heu                       0.2.0b0
six                          1.16.0
spu                          0.2.4b1
statsmodels                  0.13.2
tensorboard                  2.10.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.1
tensorflow-datasets          4.5.2
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.27.0
tensorflow-metadata          1.10.0
termcolor                    2.0.1
threadpoolctl                3.1.0
toolz                        0.12.0
torch                        1.10.1
torchmetrics                 0.9.2
torchvision                  0.11.2
tqdm                         4.62.3
typing_extensions            4.3.0
unittest-xml-reporting       3.2.0
urllib3                      1.26.12
validator.py                 1.3.0
virtualenv                   20.16.5
Werkzeug                     2.2.2
wheel                        0.37.1
wrapt                        1.14.1
xgboost                      1.5.2
yarl                         1.8.1
zipp                         3.8.1

**Comment by zhouaihui** [comment]
可以检查下notebook的运行环境，比如python环境是否正确。

**Comment by xiaojiu1414** [comment]
> 可以检查下notebook的运行环境，比如python环境是否正确。

没有问题啊   运行其它脚本没问题
