### ISSUE TITLE
secretflow docker image在公司内部扫描显示docker file里有chinese characters

### ISSUE THREAD

**Issue by Bell-Fintech** [secretflow/secretflow#1283]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow-anolis8:1.5.0b0

### OS Platform and Distribution

centsos 8.0

### Python version

3.9

### What happend and What you expected to happen.

```shell
当我们把dockerhub的secretflow-anolis8:1.5.0b0镜像拉到我们公司内部做安全扫描时，经过公司内部安全团队同事判别，这个镜像在扫描时遇到encoding characters error，麻烦帮忙check下这个问题
```

### Reproduction code to reproduce the issue.

```shell
None
```

**Comment by Chrisdehe** [comment]
@Bell-Fintech hey
是这样的，因为我们的镜像的 dockerfile 里面打包了组件的中文翻译

**Comment by Bell-Fintech** [comment]
> @Bell-Fintech hey
> 
> 是这样的，因为我们的镜像的 dockerfile 里面打包了组件的中文翻译

你好，请问这种可以暂时规避吗？目前汇丰在引用这个到内部的时候一直卡在安全扫描这一步

**Comment by Chrisdehe** [comment]
您可以通过自行打包docker镜像来规避安全扫描问题的

**Comment by Bell-Fintech** [comment]
> 您可以通过自行打包docker镜像来规避安全扫描问题的

请问可以share下dockerfile吗，我们自己内部打包一下

**Comment by Chrisdehe** [comment]
打包脚本参考：https://github.com/secretflow/secretflow/blob/main/docker/release/build.sh
dockerfile参考：https://github.com/secretflow/secretflow/blob/main/docker/release/anolis-lite.Dockerfile

**Comment by Bell-Fintech** [comment]
> 打包脚本参考：https://github.com/secretflow/secretflow/blob/main/docker/release/build.sh
> 
> dockerfile参考：https://github.com/secretflow/secretflow/blob/main/docker/release/anolis-lite.Dockerfile

好的，感谢
