### ISSUE TITLE
关于使用Shamir秘密共享协议和定义SPU配置的问题

### ISSUE THREAD

**Issue by sda427** [secretflow/secretflow#1286]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.5.0.dev20240325

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.10.14

### What happend and What you expected to happen.

```shell
1.在secretflow的手册中写到目前SPU设备支持ABY3之外的多种MPC协议（https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.5.0b0/tutorial/spu_basics#%E8%BF%9B%E9%98%B6%E4%B8%BB%E9%A2%98%EF%BC%9A%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84-MPC-%E5%8D%8F%E8%AE%AE），请问secretflow是否支持使用shamir秘密共享协议？如果可以的话，我想在secretflow中采用诚实大多数的半诚实模型来进行安全多方计算时，如何在SPU中配置protocol为shamir协议、filed为prime？
2.如果我们自己的代码已经将n方的隐私数据使用shamir协议聚合成m个参与方，我们想要将这m个参与方输入到secretflow中定义一个SPU进行安全多方计算（这m方持有的是已经使用shamir协议拆分后的碎片数据），那么该如何配置使得SPU能够识别到我们的输入是已经通过shamir协议聚合过后的非原始数据（在后续secretflow的安全多方计算中，能够自动还原出需要的中间值和最终计算结果）？
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by tpppppub** [comment]
1. 目前不支持 Shamir Secret Sharing，但在计划中
2. 目前不支持直接输入秘密分享，但可以使用一些 trick 把秘密分享当作原始数据进行处理，可以参考  [这个](https://github.com/secretflow/spu/issues/445)

**Comment by sda427** [comment]
好的，非常感谢您的回答，期待secretflow能够尽早支持Shamir Secret Sharing。
还请问下FieldType除了选定FM32、FM64、FM128外，能否支持自定义为其他值？

**Comment by tpppppub** [comment]
目前不支持
