### ISSUE TITLE
secretflow 1.5.X镜像打包bug

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1296]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.5.X

### OS Platform and Distribution

centos7

### Python version

3.10

### What happend and What you expected to happen.

```shell
参考https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/mfbgum8vi3ngs4y9#bNO7d进行镜像打包时，执行sh build.sh -v test_compare 发生如下错误
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)
Retrieving notices: ...working... done

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```

### Reproduction code to reproduce the issue.

```shell
经过排查发现错误是在https://github.com/secretflow/secretflow/blob/28f66cabe6317bdd5a32577af025d3fc5213f595/docker/dev/entry.sh#L23
将此行命令修改为conda create -n build python=3.10 --solver classic -y后问题解决。
```

**Comment by warriorpaw** [comment]
1、目前release/1.5分支上执行 bash build.sh -v 1.5.0，可以正常打包，无法复现你描述的问题。
2、entry.sh是在打包镜像secretflow/release-ci内执行的，不要直接在开发环境内执行entry.sh脚本，见https://github.com/secretflow/secretflow/blob/28f66cabe6317bdd5a32577af025d3fc5213f595/docker/dev/build.sh#L92
