### ISSUE TITLE
大文件上传问题

### ISSUE THREAD

**Issue by littleunicorn** [secretflow/secretflow#1298]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

docker

### OS Platform and Distribution

docker服务

### Python version

3.7

### Bazel version

1

### GCC/Compiler version

1

### What happend and What you expected to happen.

```shell
文件过大，列过多的数据情况，如何上传个？
拆分文件上传，但没有支持数据拼接的模块
```

### Reproduction code to reproduce the issue.

```shell
大文件上传问题
```

**Comment by Chrisdehe** [comment]
hi @littleunicorn 
可以详细描述一下您的需求吗？
比如您在做什么任务，有什么业务背景？
