### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by deadlywing** [secretflow/secretflow#13]
直接使用pip install 安装了secretflow后，在import secretflow时报错：
![IMG_1649](https://user-images.githubusercontent.com/25818621/177673554-53aa6769-31b4-4274-99f5-f594360a87e4.PNG)

请问是否是对系统的某些dependence版本什么的有要求？

BTW: 使用的系统是centos7，gcc版本4.8.5；google了一下这个报错，似乎是要安装更高版本的glibc，现在的服务器上还有其他应用，不敢乱来，请问后面有考虑提供一个**docker**镜像用来学习测试么？这样尝试的成本会小一些。

**Comment by zhouaihui** [comment]
我们正在添加docker镜像，可以先使用 registry.hub.docker.com/secretflow/spu-gcc11-anolis-dev:latest 来安装secretflow。

另外，我们也在降低对glibc的依赖，后续会推送新的包。
