### ISSUE TITLE
secretflow 最新版本的v1.6.1b0 的release note在哪里能获取

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretflow#1306]
Hi， 我观察到 secretflow 最近发布了v1.6.1b0 版本
请问，每次发布新的版本，相关的change log 或release note 在哪能获取？

secretpad 仓库里，有[版本的对应关系](https://github.com/secretflow/secretpad?tab=readme-ov-file#versions)

secretflow 仓库里的change log 我看还是上个版本的

anyway，我想知道v1.6.1b0 和v1.6.0b0 做了哪些更新

**Comment by ian-huu** [comment]
release note 可以在 [release 页面](https://github.com/secretflow/secretflow/releases) 查看，每个大版本会对应一个分支：https://github.com/secretflow/secretflow/tree/release/1.6.x ，也可以在对应分支的 CHANGELOG 中查看

**Comment by gxcuit** [comment]
Thanks
