### ISSUE TITLE
Incompatibility Between TensorFlow and Jupyter Notebook

### ISSUE THREAD

**Issue by kylin5207** [secretflow/secretflow#1309]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.6.1b0 

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.14

### What happend and What you expected to happen.

当我使用新版的secretflow时，安装了jupyter notebook来运行，似乎遇到了一些问题。
``` 
cannot import name 'TypeAliasType' from 'typing_extensions' (/usr/local/lib/python3.10/site-packages/typing_extensions.py)
```

- 尝试查看该问题的解决，https://stackoverflow.com/questions/69876370/why-arent-transformers-imported-in-python#comment126233975_69876417
- 根据建议对该包进行了升级。但是，升级后又和tensorflow冲突。
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.1 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.12.0 which is incompatible.
```
 麻烦官方童鞋看一下兼容性，不胜感激🥹

### Reproduction code to reproduce the issue.
single line ```import secretflow ``` in Jupyter notebook ipynb

**Comment by tonywu6** [comment]
Hi!

这里的 "Jupyter Notebook" 指的是 JupyterLab 吗？

如果是的话，以下版本应当是相互兼容的

```bash
pip install "secretflow==1.6.1b0" "jupyterlab==4.2.1"
```

依赖应当解析到 `typing-extensions==4.5.0`

（你可能需要全新的 virtual env）

[requirements-linux-arm64.txt](https://github.com/secretflow/secretflow/files/15482459/requirements-linux-arm64.txt)

**Comment by kylin5207** [comment]
不是JupyterLab，而是Jupyter Notebook 。它提供了一个简单、单一的笔记本界面，用于进行仿真模式下的交互式编码。```pip install notebook```

**Comment by tonywu6** [comment]
@kylin5207 

```bash
pip install "secretflow==1.6.1b0" "notebook==7.2.0"
```

[requirements-linux-arm64.txt](https://github.com/secretflow/secretflow/files/15482818/requirements-linux-arm64.txt)

**Comment by kylin5207** [comment]
New problem has raised:
```
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu-aws==2.12.1 (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu-aws==2.12.1
```

**Comment by tonywu6** [comment]
What's the exact install command you used? What's your system architecture? `amd64` or `arm64`? 

That requirements.txt is for arm64 and for reference only. `tensorflow-cpu-aws==2.12.1` is likely an ARM only dep.

If you have a different architecture than arm64 you should run the above `pip install` command and let `pip` figure the rest out.

Let me know if there are still errors.

**Comment by kylin5207** [comment]
My system architecture is x86_64(amd64).

**Comment by kylin5207** [comment]
So, I'll first comment out tensorflow-cpu-aws==2.12.1 from the requirements。

**Comment by kylin5207** [comment]
其实还是没有解决问题，Jupyter notebook需要的typing_extensions版本和secretflow1.6.1b0的tensorflow需要的冲突啦。这个问题还是没有解决

**Comment by kylin5207** [comment]
不过也不是一定要解决的，只是对于使用notebook进行开发的小伙伴不太友好。控制台运行python脚本是没有问题的。

**Comment by tonywu6** [comment]
> 不过也不是一定要解决的

嗯，这边确认使用 Ubuntu 24.04，amd64，micromamba，使用全新的 Python 3.10 虚拟环境，运行 `pip install "secretflow==1.6.1b0" "notebook==7.2.0"`，能够安装到所有依赖的正确版本，也可以在 Notebook 中正确引入 `secretflow` 和 `tensorflow`，其中解析到的版本是 `secretflow==1.6.1b0` `notebook==7.2.0` `typing-extensions==4.5.0` `tensorflow==2.12.1`。

如果还是没有办法安装，那么非常大概率是其他环境上的影响（PATH 上找到了不正确的 Python 解释器，或者是虚拟环境中已经存在一些包使得依赖冲突，或者是在某处自行指定了不相容的依赖），或者是有其他的运行时问题，issue 上下文并未指明。

没有办法复现原文提到的问题，这个 issue 我会先关闭；如果有其他的疑问，欢迎在新的 issue 中讨论。

**Comment by kylin5207** [comment]
还是没有解决，就是tensorflow的包的版本依赖的typing_extensions版本，和jupyter notebook依赖的版本冲突了，未来升级tensorflow包应该是可以解决的。只是目前1.6.1b0限定了tf的版本，如此看来，这个问题暂时解决不了

**Comment by kylin5207** [comment]
安装是可以正常安装，但是当你打开ipynb，尝试输入一行简单代码```import secretflow as sf```就可以看到日志的报错信息。

**Comment by kylin5207** [comment]
By the way, `secretflow==1.5.0.dev20240321` does not have the same problem, the version of tf is `2.11.1`

**Comment by tonywu6** [comment]
<img width="750" alt="Screenshot 2024-05-30 at 10 25 06 AM" src="https://github.com/secretflow/secretflow/assets/93302820/220d0048-a692-4994-b611-c6e3b5d9ecea">

如果你安装了以上版本，那么 "tensorflow的包的版本依赖的typing_extensions" 和 "jupyter notebook依赖的版本" 和 secretflow 的版本相互是没有冲突；如果安装的/需要的不是以上版本，那么就超出 issue 支持的范畴了。

感谢提问！

**Comment by kylin5207** [comment]
你的python版本是3.10.13，我上报的好像是3.10.14。我重新制作镜像试一下。

**Comment by tonywu6** [comment]
@kylin5207 

重新尝试了一下，可以复现这个问题；具体而言，当 `pip install` 仅指定 secretflow 和 notebook 时，pip 将会解析到以下依赖

- `tensorflow==2.12.1`
- `typing-extensions==4.5.0`

此时安装会成功，但由于 typing-extensions 版本过旧，在 Notebook 上首次运行任何代码时，ipykernel 会失败

潜在的解决方式是同时指定 secretflow 和 typing-extensions 的版本到最新版：

```bash
pip install "secretflow==1.6.1b0" "typing-extensions==4.12.0" "notebook"
```

会解析到 `tensorflow==2.12.0`，仍然在兼容范围内；结果如下：

![IMG_0890](https://github.com/secretflow/secretflow/assets/93302820/d2a6170b-2245-46c0-8dfd-beece706df32)

可以使用这个命令在全新的 Python 3.10 虚拟环境中尝试

secretflow 完整版的依赖相对复杂，没有办法完全确保所有用法的兼容性（特别是当上游依赖本身没有保证兼容性时）；另一个建议是，如果有可能的话，直接使用已经打包好的镜像，或者基于这个镜像制作其他镜像，见文档：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/getting_started/installation#option-2-from-docker

如果有额外的问题，请开启新的 issue

**Comment by kylin5207** [comment]
很棒，问题解决了
