### ISSUE TITLE
集群模式使用公网EIP问题

### ISSUE THREAD

**Issue by allenkang** [secretflow/secretflow#131]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.6.13b1

### OS Platform and Distribution

centos7.8

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
环境：
准备了两台云服务器，各自有独立的公网eip，分别作为head和work节点。启动命令如下：
ray start --head --node-ip-address="head公网ip" --port="32345" --redis-password='1234' --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
  ray start --address="head节点公网ip:32345" --node-ip-address="work节点公网ip" --redis-password='1234' --resources='{"bob": 8}' --disable-usage-stats

执行横向dataframe求平均是出错：
2022-09-21 13:36:04.239688: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
[2022-09-21 13:36:05,354 I 16659 16659] global_state_accessor.cc:357: This node has an IP address of 192.168.0.60, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
<secretflow.device.device.spu.SPU object at 0x7f05c44b3400>
SPUAggregator(device=<secretflow.device.device.spu.SPU object at 0x7f05c44b3400>)
h_read_csv time cost:
 2430.0448894500732 ms
HDataFrame(partitions={<secretflow.device.device.pyu.PYU object at 0x7f0542417ca0>: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7f0540177280>), <secretflow.device.device.pyu.PYU object at 0x7f059c183130>: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7f05401773a0>)}, aggregator=SPUAggregator(device=<secretflow.device.device.spu.SPU object at 0x7f05c44b3400>), comparator=SPUComparator(device=<secretflow.device.device.spu.SPU object at 0x7f05c44b3400>))
Traceback (most recent call last):
  File "wages-2-cluster.py", line 54, in <module>
    print('Horizontal df:\n', hdf.mean(numeric_only=True))
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/data/horizontal/dataframe.py", line 109, in mean
    reveal(
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/device/driver.py", line 158, in reveal
    value_obj = ray.get(value_ref)
  File "/usr/local/python3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3.8/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=15127, ip=120.46.213.151, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f91dd9bab80>)
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 125, in __init__
    self.link = link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yasl/yasl/link/transport/channel_brpc.cc:121] brpc server failed start
stacktrace: 
#0 yasl::link::FactoryBrpc::CreateContext()+0x7f923658e8c7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9234c28ece
#2 pybind11::cpp_function::dispatcher()+0x7f9234c150cb
#3 PyCFunction_Call+0x43bdca

如果替换为云服务器各自的内外ip，能够顺利执行。
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
import time
import spu

sf.shutdown()

# 初始化serectflow，集群模式，设置集群head节点地址
password='1234'
sf.init(address='head节点公网ip:32345', _redis_password=password)
# 定义两方计算集群，用于构建两方计算密文设备
cdef = {
    'nodes': [
            {'party': 'alice', 'id': 'local:0', 'address': 'head节点公网ip:30345'},
        {'party': 'bob', 'id': 'local:1', 'address': 'work节点公网ip:30345'},
],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    },
}
# 两参与方，明文设备
alice, bob= sf.PYU('alice'), sf.PYU('bob')
# 构建两方计算密文设备
spu_2pc = sf.SPU(cdef)
print(spu_2pc)

from secretflow.data.horizontal import read_csv as h_read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator

# 安全聚合
comp = SPUComparator(spu_2pc)
aggr = sf.security.aggregation.SPUAggregator(spu_2pc)
print(aggr)

#定义数据集路径
h_alice_path="/root/secretflow/demo/dataset/wages1.csv"
h_bob_path="/root/secretflow/demo/dataset/wages2.csv"

# 读取两方数据为横向dataframe
t0 = time.time()
hdf = h_read_csv({alice: h_alice_path, bob: h_bob_path},
                 aggregator=aggr,
                 comparator=comp)
t0_e = time.time()
print("h_read_csv time cost:\n", float(t0_e-t0)*1000.0, "ms")
print(sf.reveal(hdf))

t1 = time.time()
print('Horizontal df:\n', hdf.mean(numeric_only=True))
t1_e = time.time()
print("hdf.mean time cost:\n", float(t1_e-t1)*1000.0, "ms")
```

**Comment by zhouaihui** [comment]
`brpc server failed start`说明端口30345被占用了，建议检查下。
另外，为了避免类似冲突，重新创建ray集群之前建议执行ray stop以停止原有的ray集群。

**Comment by allenkang** [comment]
> `brpc server failed start`说明端口30345被占用了，建议检查下。 另外，为了避免类似冲突，重新创建ray集群之前建议执行ray stop以停止原有的ray集群。

机器是干净的机器，启动集群后，使用netstat -apn |grep 30345 查看是没有端口占用

**Comment by zhouaihui** [comment]
从我们使用brpc的经验来看，`brpc server failed start`的几种常见可能性是1）监听地址无法解析 2）端口已经被占用 3）监听地址不正确。通常在这几个原因范围内。

**Comment by allenkang** [comment]
> 从我们使用brpc的经验来看，`brpc server failed start`的几种常见可能性是1）监听地址无法解析 2）端口已经被占用 3）监听地址不正确。通常在这几个原因范围内。

嗯嗯，谢谢您的分享。不过目前看我这边貌似不存在这几个问题，我再排查下。顺带想咨询下，这种集群的定义是否正确：
cdef = {
    'nodes': [
            {'party': 'alice', 'id': 'local:0', 'address': 'head节点公网ip:30345'},
        {'party': 'bob', 'id': 'local:1', 'address': 'work节点公网ip:30345'},
],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    },
}

其中nodes里的id 为 local:0，是否有id定义的格式说明？local表示什么意思？local之外还有其他定义吗？谢谢

**Comment by allenkang** [comment]
后面尝试过重装系统，更新到0.7.7b1版本，替换集群定义nodes的端口等方式排查，任然是相同的情况，基本可以排除端口占用问题。查看集群状态也正常，蚂蚁的同学可以再帮确认下问题吗？
Node status
---------------------------------------------------------------
Healthy:
 1 node_1f30db760318b3bcf03b38149017cbb47d91938ad83733410d801e1c
 1 node_6f2e1c1fd8adfa0d06fc97204150db07da558e91fe6406d321b00257
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/16.0 CPU
 0.0/8.0 alice
 0.0/8.0 bob
 0.00/19.425 GiB memory
 0.00/8.963 GiB object_store_memory


猜测的一个原因是：
错误日志有显示：[2022-09-21 13:36:05,354 I 16659 16659] global_state_accessor.cc:357: This node has an IP address of 192.168.0.60, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
<secretflow.device.device.spu.SPU object at 0x7f05c44b3400>

当前执行程序在head节点机器上执行，但gcs识别的当前机器ip是内网地址192.168.0.60，而其对应公网eip，导致无法连接。

**Comment by zhouaihui** [comment]
可以使用ray的`node-ip-address`参数指定ray使用的ip，例如`ray start --head --node-ip-address xxx`，`ray start --node-ip-address xxx`

**Comment by zhouaihui** [comment]
和id没有关系，id其实可以任意填写，没有格式要求。

**Comment by allenkang** [comment]
> 可以使用ray的`node-ip-address`参数指定ray使用的ip，例如`ray start --head --node-ip-address xxx`，`ray start --node-ip-address xxx`

恩，测试时， ray start 启动都指定了对应的公网ip

**Comment by rivertalk** [comment]
Hi，可以试一下增加 `listen_address` 到cluster def 里吗？

具体可以参考如下样式

```
# 定义两方计算集群，用于构建两方计算密文设备
cdef = {
    'nodes': [
            {'party': 'alice', 'id': 'local:0', 'address': 'head节点公网ip:30345', 'listen_address': '0.0.0.0:30345' },
           {'party': 'bob', 'id': 'local:1', 'address': 'work节点公网ip:30345', 'listen_address': '0.0.0.0:30345' },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    },
}
```

**Comment by allenkang** [comment]
> Hi，可以试一下增加 `listen_address` 到cluster def 里吗？
> 
> 具体可以参考如下样式
> 
> ```
> # 定义两方计算集群，用于构建两方计算密文设备
> cdef = {
>     'nodes': [
>             {'party': 'alice', 'id': 'local:0', 'address': 'head节点公网ip:30345', 'listen_address': '0.0.0.0:30345' },
>            {'party': 'bob', 'id': 'local:1', 'address': 'work节点公网ip:30345', 'listen_address': '0.0.0.0:30345' },
>     ],
>     'runtime_config': {
>         'protocol': spu.spu_pb2.SEMI2K,
>         'field': spu.spu_pb2.FM128,
>         'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
>     },
> }
> ```

感谢解答，加上'listen_address': '0.0.0.0:30345'是可以运行成功的。方便请教下这两个地址分别起什么作用吗？我顺带尝试了下只设置'listen_address': '0.0.0.0:30345'和只设置'address': '0.0.0.0:30345'的两种情况，都无法运行成功。

**Comment by rivertalk** [comment]
address 是告知 对方 访问自己 时使用的地址
listen_address 是自己 listen （自己）机器的地址

因为云上 listen 地址是自己租户机器的地址，和访问的（公网）地址是不同的，所以需要分开配置

PS: 以后我们可能会做一些优化来去掉 listen_address，祝您生活愉快

**Comment by allenkang** [comment]
> address 是告知 对方 访问自己 时使用的地址 listen_address 是自己 listen （自己）机器的地址
> 
> 因为云上 listen 地址是自己租户机器的地址，和访问的（公网）地址是不同的，所以需要分开配置
> 
> PS: 以后我们可能会做一些优化来去掉 listen_address，祝您生活愉快

好的，了解了，再次感谢
