### ISSUE TITLE
1.6.1b0新增的Onehot支持丢弃众数列的功能

### ISSUE THREAD

**Issue by kylin5207** [secretflow/secretflow#1311]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.14

### What happend and What you expected to happen.

看到新版对于onehot算法新增了新的功能：丢弃众数列，所以想尝试一下，但是没有发现对应的参数设置。丢弃众数列是否应该由参数控制呢，还是我用法错了。还是说就是参数`min_frequency`和`max_categories`，但这两个参数在之前的版本里也实现了哦。

### Reproduction code to reproduce the issue.

```shell
from secretflow.preprocessing import OneHotEncoder

sf_onehot = OneHotEncoder()
encoded_vdf = sf_onehot.fit_transform(vdf_train)
```

**Comment by da-niao-dan** [comment]
仅在组件模式下实现了， 可以看看components 中的onehot 组件

**Comment by kylin5207** [comment]
好滴，在相关的component中找到啦，感谢。
