### ISSUE TITLE
model_export使用说明

### ISSUE THREAD

**Issue by kylin5207** [secretflow/secretflow#1317]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

secretflow 1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.13

### What happend and What you expected to happen.

哪里可以查看model_export的开发说明？
- model_export位置（https://github.com/secretflow/secretflow/blob/v1.6.1b0/secretflow/component/model_export/model_export.py ）
- 目前仅查到了相关参数介绍
- 只能通过(https://github.com/secretflow/secretflow/blob/v1.6.1b0/tests/component/infra/test_model_export.py) 分析model_export的作用。

### Reproduction code to reproduce the issue.

希望得到官方教程以助于更好的学习，感谢～。

**Comment by zimu-yuxi** [comment]
可以看下[这里](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/component/comp_list#model-export)组件说明文档看下呢

**Comment by kylin5207** [comment]
是的，之前看的就是这里的说明哈（基本只有参数解释），但是希望有个使用教程。

**Comment by kaixin-haha** [comment]
感谢您的反馈，我们重视您的意见,会在未来的规划中考虑完善文档和增加教程
