### ISSUE TITLE
secretflow 1.5.0b0 SecureBoost组件如何使用

### ISSUE THREAD

**Issue by xuzhijin** [secretflow/secretflow#1321]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

secretflow 1.5.0b0

### OS Platform and Distribution

centos7

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
我按照https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/main/components_instruction#id30 这个文档去试验SecureBoost组件如何使用，发现运行不成功
```

### Reproduction code to reproduce the issue.

```shell
File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/heu.py\", line 645, in init
    'evaluators' in self.config and len(self.config['evaluators']) > 0
AssertionError: The current version does not support HEU standalone deployment mode 这个错误，请问该怎么修改一下
```

**Comment by da-niao-dan** [comment]
https://github.com/secretflow/secretflow/issues/1237
