### ISSUE TITLE
SecureBoost组件的

### ISSUE THREAD

**Issue by xuzhijin** [secretflow/secretflow#1322]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 1.5.0b0

### OS Platform and Distribution

centos7

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
按照官网的设置去运行组件，发现运行错误，该怎么配置
```

### Reproduction code to reproduce the issue.

```shell
File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/heu.py\", line 645, in init
    'evaluators' in self.config and len(self.config['evaluators']) > 0
AssertionError: The current version does not support HEU standalone deployment mode
```

**Comment by xuzhijin** [comment]
![image](https://github.com/secretflow/secretflow/assets/8954761/1268161a-e5d8-4c49-8529-043cf1fb9079)

已经按照官网的组件组合去连接

**Comment by da-niao-dan** [comment]
https://github.com/secretflow/secretflow/issues/1237

**Comment by xuzhijin** [comment]
代码意思是懂，那在平台上该如何操作呢

**Comment by xuzhijin** [comment]
This error may raise if you try to train sgb in a single party. (There are no evaluators.) ，平台怎么设置才会可以多个parties

**Comment by da-niao-dan** [comment]
你好，特征列选择的时候，确保每一方的特征都有被选呢

**Comment by xuzhijin** [comment]
![image](https://github.com/secretflow/secretflow/assets/8954761/58b8a7c8-cd26-4f38-9f4c-c30cf7caf3fe)
![image](https://github.com/secretflow/secretflow/assets/8954761/48a41791-bdc3-498a-8f09-dd26629545f9)
你好，右边预测的数据是这样的，通过日志预测错误的原因在哪呢

**Comment by xuzhijin** [comment]
预测特征列填的是x和y

**Comment by da-niao-dan** [comment]
训练的时候的特征要和预测保持一致

**Comment by xuzhijin** [comment]
![image](https://github.com/secretflow/secretflow/assets/8954761/7d780c3f-044e-45eb-9a28-5cf7fbcf70d4)
![image](https://github.com/secretflow/secretflow/assets/8954761/485d7b5d-8511-430d-8663-1b81b03ed4cc)
预测和特征都已经设置了x和y

**Comment by xuzhijin** [comment]
![image](https://github.com/secretflow/secretflow/assets/8954761/ca60d480-ee2e-4c5f-9658-80023e33932c)
XGB预测的时候报了这个错误，要怎么设置一下呢

**Comment by xuzhijin** [comment]
![image](https://github.com/secretflow/secretflow/assets/8954761/f4aa2d81-a5aa-49fd-9a5f-69eb0e479bf7)


使用双方特征训练出来的模型，然后预测的时候，不是需要用双方的特征去预测吗？
例如：
A节点：id1、f1、f2、y
B节点：id2、f3
训练出来模型后
使用新的一组数据
id、f1、f2、f3 去做预测。
预测结果，以上报错

**Comment by da-niao-dan** [comment]
hello， train_test_split 来确保训练集和测试集一样哈

**Comment by xuzhijin** [comment]
你的意思是要对数据进行随机分割处理一下才不会报错么

**Comment by da-niao-dan** [comment]
如果训练预测集的特征列真的是对齐的，那也不应该有报错。随机分割的数据集 两个特征列肯定是对的上的，你把你现在的训练和预测数据做个全表统计之类的观察一下两边特征到底是不是对齐的？

**Comment by xuzhijin** [comment]
![image](https://github.com/secretflow/secretflow/assets/8954761/ff3732c8-31d7-450a-b52a-66ca1ff1eccb)
想问以下NN分类的组件怎样才能够显示c出来使用的呢
