### ISSUE TITLE
教程-联邦学习-水平联邦XGBoost中，为何三方都要执行相同的代码？

### ISSUE THREAD

**Issue by Klein920116** [secretflow/secretflow#1328]
### Issue Type

Documentation Bug

### Source

binary

### Secretflow Version

secretflow 0.6.13b0

### OS Platform and Distribution

CentOS Linux release 7.9.2009

### Python version

3.10.14

### What happend and What you expected to happen.

```shell
我们在生产模式的横向联邦学习中进行实验，有两点疑问：

1.为什么arbiter方主要用来做聚合，并不需要数据，但是在教程中仍然需要加载数据？
2.provider方和promoter方应该是不一样的数据，但是在demo中是一样的？如果是真实世界中的场景，是不是demo中的代码就不符合了？

代码：data = load_dermatology(parts=[alice, bob], aggregator=aggr, comparator=comp)
```

### Reproduction code to reproduce the issue.

```shell
代码完全依照教程-联邦学习-水平联邦XGBoost中的代码部署在三方。
```

**Comment by zhangxingmeng** [comment]
1. demo只是一个示范，水平场景各方要求的schema是一致的。所以这里用相同的数据来简化的流程。真实场景换成真实数据就可以了。
2. arbiter你指的是aggr这一方吗？不需要加载数据，只做hist聚合。

但你在代码中可以看到server端其实mock了一份schema相同的数据，这是因为在booster这一层我们是从联邦层面定义了federated_update，在各方计算完grad和hess之后才会进入联邦建树逻辑。mock数据是在这里用的。
