### ISSUE TITLE
component的组件定义和docs中comp_list.md中的有差异

### ISSUE THREAD

**Issue by kylin5207** [secretflow/secretflow#1335]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.14

### What happend and What you expected to happen.

当我查看onehot的component组件的用法时，发现和docs中的描述有不一致的地方，似乎是没有更新component的docs。例如，onehot_encode组件的属性`drop`（ https://github.com/secretflow/secretflow/blob/v1.6.1b0/secretflow/component/preprocessing/unified_single_party_ops/onehot_encode.py#L44 ）
在文档中（ https://github.com/secretflow/secretflow/blob/v1.6.1b0/docs/component/comp_list.md#onehot_encode ）确是`drop_first`。

**Comment by kylin5207** [comment]
此外，关于`input/input_dataset/features`的定义也有疑惑，在文档中该参数放在了inputs中，而在使用时，却放在了attr。例如：
```
onehot_encode_output = f"{work_path}/onehot.csv"
onehot_rule_path = f"{work_path}/onehot.rule"
onehot_report_path = f"{work_path}/onehot.report"

onehot_param = NodeEvalParam(
    domain="preprocessing",
    name="onehot_encode",
    version="0.0.3",
    attr_paths=[
        "drop",
        "input/input_dataset/features",
    ],
    attrs=[
        Attribute(s="no_drop"),
        Attribute(ss=["o1", "o2"]),
    ],
    # use binning sub output
    inputs=[pre_res.outputs[0]],
    output_uris=[
        onehot_encode_output,
        onehot_rule_path,
        onehot_report_path,
    ],
)
```

**Comment by zimu-yuxi** [comment]
@kylin5207 
1.感谢，我们会尽快修改一下
2.方便贴一下代码链接吗？

**Comment by kylin5207** [comment]
@zimu-yuxi  here https://github.com/secretflow/secretflow/blob/v1.6.1b0/tests/component/infra/test_model_export.py#L394

**Comment by zimu-yuxi** [comment]
> @zimu-yuxi here https://github.com/secretflow/secretflow/blob/v1.6.1b0/tests/component/infra/test_model_export.py#L394

它是inputs的features，都是参数。后续会对此做个优化，但暂时不影响使用哈。
感谢！！！！

**Comment by kylin5207** [comment]
看出来啦，对于inputs的相关参数也会放在attrs里
