### ISSUE TITLE
SS-LR是基于哪篇论文？

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretflow#1336]
Hi，请问SS-LR是基于哪篇论文？

[MOOK](【MOOC2 第35讲 白盒互联互通丨隐语开放算法协议介绍】 【精准空降到 19:14】 https://www.bilibili.com/video/BV1Rw411p7MG/?share_source=copy_web&vd_source=d083c7e113148ed5ebd091b062b1c8eb&t=1154)里出现了协议的具体截图，但不清楚出处

Thanks

**Comment by zimu-yuxi** [comment]
@gxcuit  hi，这篇https://arxiv.org/abs/2008.08753

目前是有什么疑惑吗？想要根据此篇论文做什么呢？可以分享下吗？

**Comment by gxcuit** [comment]
> @gxcuit hi，这篇https://arxiv.org/abs/2008.08753 视频中的 SS-LR 本身没有发论文，这个是 HESS-LR 的论文，SS-LR 是 HESS-LR 的简化算法
> 
> 目前是有什么疑惑吗？想要根据此篇论文做什么呢？可以分享下吗？

Hi, @zimu-yuxi 单纯想学习下。因为我搜了许多，也搜到了SSHE-LR。 以为SS-LR有单独的论文。

Anyway， 感谢您的回复！
