### ISSUE TITLE
关于 PYU 本地计算

### ISSUE THREAD

**Issue by Diomchen** [secretflow/secretflow#1341]
### Issue Type

Others

### Source

source

### Secretflow Version

v1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
流程：
假设 Alice 是一个PYU 设备，其包含了一份本地数据 a（数据类型为FedNdarray），我首先需要从 a 选出随机 n 行，组成一个新的矩阵 a_r。之后再把这个结果 a_r 跟 a 进行本地计算得到res。
以下为大致的代码
~~~python
alice = sf.PYU('alice')
# 选出随机点列表
r = Random.r_list()
# 将 r 转至 alice 本地
r_d = sf.to(alice, r)
# 得出随机行矩阵
a_r = a[alice][r_d]
# 本地计算得到结果
res = alice(func_1)(a, a_r) # <- 问题所在
~~~
我期望的结果：
能顺利得到 res。

实际结果：
会卡住，ctrl+c 后，提示了不太清晰的类型转换错误。
```

### Reproduction code to reproduce the issue.

```shell
我的问题是：
PYU 本地计算，这样写是否正确？若不正确（或者说不常规），我该如何修改，或者哪里有具体的样例？
```

**Comment by aokaokd** [comment]
收到您的问题，正在处理中。请稍等

**Comment by aokaokd** [comment]
可能是因为你指初始化一个error导致，会出现 No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.

**Comment by aokaokd** [comment]
可能是因为你指初始化一个error导致，会出现 No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.<>

**Comment by Diomchen** [comment]
> 可能是因为你指初始化一个error导致，会出现 No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
> 
> ```python
> import numpy as np
> import secretflow as sf
> 
> 
> # Check the version of your SecretFlow
> print('The version of SecretFlow: {}'.format(sf.__version__))
> 
> # In case you have a running secretflow runtime already.
> sf.shutdown()
> 
> sf.init(['alice', 'bob', 'charlie'], address='local')
> alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')
> # Mock example: Creating a dummy FedNdarray
> class FedNdarray:
>     def __init__(self, data):
>         self.data = data
> 
>     def __getitem__(self, idx):
>         return self.data[idx]
> 
> # Mock example: Alice's PYU device with FedNdarray data
> a_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
> a = FedNdarray(a_data)
> 
> # Step 1: Generate random row indices
> n = 2  # Number of random rows to select
> num_rows = len(a.data)  # Number of rows in a
> 
> random_indices = np.random.choice(num_rows, size=n, replace=False)
> 
> # Step 2: Send random indices to Alice
> indices_ptr = sf.to(alice, random_indices)
> 
> # Step 3: Alice's local computation function
> def local_computation(a_data, indices_ptr):
>     # Retrieve selected rows based on indices_ptr
>     selected_rows = a_data[indices_ptr]
> 
>     # Compute sum of squared differences between selected_rows and all rows in a_data
>     diff_squared_sum = np.sum((selected_rows[:, None] - a_data) ** 2)
> 
>     return diff_squared_sum
> 
> # Step 4: Execute local computation on Alice's device
> res = alice(local_computation)(a.data, indices_ptr)
> 
> print("Result of local computation (res):", res)
> ```

非常感谢，我再修改并调试一下
