### ISSUE TITLE
SPU PYU

### ISSUE THREAD

**Issue by YIYEYIYE** [secretflow/secretflow#135]
### Issue Type

Others

### Source

source

### Secretflow Version

0.6.13b0

### OS Platform and Distribution

centos7

### Python version

3.8.12

### What happend and What you expected to happen.

```shell
SPU是不是就是在中心进行安全计算？
PYU是不是参与方在本地进行计算？
总体说，就是PYU属于参与各方，可以直接用明文数据计算？而中心则用SPU进行安全计算？
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by zhouaihui** [comment]
1. `PYU`是明文设备，目前是依托于python作为载体，主要提供参与方本地的明文计算。
2. `SPU`是MPC密态设备。这里密态设备是虚拟的概念，SPU本质上是由多个计算方组成，并提供了密态设备这个视角，好处是帮助用户屏蔽MPC底层多个计算方协同计算的细节。SPU并不是你理解的`在中心进行安全计算`，计算还是发生在各个计算方的，你说的`中心`更多的可以理解为是驱动者（driver），driver负责把计算任务分发给SPU，而SPU提供了虚拟设备的视角，让你看起来是在driver这个视角操纵了它。

**Comment by YIYEYIYE** [comment]
1.SPU是不是可以理解为在SPU设备的每一方都有一个spu去执行密文计算，只不过因为各个参与方是一个整体，所以用一个SPU去概括了各个参与方？
2.在SPU和HEU内进行的计算是不是都是对密文进行计算？
3.用SPU进行MPC，那么各个参与方的数据是在本地计算然后再汇总？还是通过SS、OT等协议(ABY3、CHEETAH等)将数据共享出去，然后各自计算再汇总？

**Comment by anakinxc** [comment]
Hi,

1. 是的，概念上是用一个 spu 来表示了一个 spu 实体集群。
2. 是的
3. 计算时是数据提供方把分片后的数据放入 spu 实体(例如 aby3 就是数据提供方生成三个分片，分别放入三个 spu 实体节点)，然后各个 spu 节点用自己的分片数据进行计算

**Comment by YIYEYIYE** [comment]
1.单机部署时，一个SPU运行时(pid)是不是就代表了一个参与方？
2.用SPU进行计算时，怎么看一下数据的流动情况？

**Comment by 6fj** [comment]
1. 可以这么理解。
2. secretflow目前没有简单的方法查看数据流动，我这里简单介绍一下背景吧。secretflow设备之间的数据流动（比如spu设备和pyu设备）底层由Ray来处理，这一块可以查阅Ray的[object ref](https://docs.ray.io/en/latest/ray-core/objects.html); spu设备下spu 运行时(runtime)之间的数据流动由brpc处理，底层的代码在[secretflow/yasl](https://github.com/secretflow/yasl)中。

**Comment by zhouaihui** [comment]
> 1.单机部署时，一个SPU运行时(pid)是不是就代表了一个参与方？ 2.用SPU进行计算时，怎么看一下数据的流动情况？

关于第一个问题，补充一下，我们应该仍然把SPU视作是多个参与方，只是单机部署时，由一台机器承担了多个参与方的角色。

**Comment by kanppa** [comment]
这里不同的party本质上也是归属于同一个ray集群，由ray来处理数据的流动，是否对跨域的数据流动有优化呢

**Comment by 6fj** [comment]
Hi @kanppa ,

对于spu 设备下的各个party之间的spu runtime，数据流动是由brpc处理的，而不是ray来处理。

**Comment by lidh15** [comment]
> pyu 就是python unit的缩写吗？这里的“一个设备”指的是什么？是指一个PYU实例可以以非隐私的方式执行各种python函数吗？

**Comment by lidh15** [comment]
> 1. `PYU`是明文设备，目前是依托于python作为载体，主要提供参与方本地的明文计算。
> 2. `SPU`是MPC密态设备。这里密态设备是虚拟的概念，SPU本质上是由多个计算方组成，并提供了密态设备这个视角，好处是帮助用户屏蔽MPC底层多个计算方协同计算的细节。SPU并不是你理解的`在中心进行安全计算`，计算还是发生在各个计算方的，你说的`中心`更多的可以理解为是驱动者（driver），driver负责把计算任务分发给SPU，而SPU提供了虚拟设备的视角，让你看起来是在driver这个视角操纵了它。

pyu 就是python unit的缩写吗？这里的“一个设备”指的是什么？是指一个PYU实例可以以非隐私的方式执行各种python函数吗？
