### ISSUE TITLE
使用模型融合后的模型进行预测，特征是传入单边的吗？

### ISSUE THREAD

**Issue by didadida321** [secretflow/secretflow#1355]
根据官网提供的demo，模型训练双方分别使用breast数据的前15列，和15列后的数据，但是使用模型融合后的模型进行预测时，使用的是所有特征x进行预测。我理解不应该是拿单边的数据做预测吗？
官网代码如下：
    model, complete_model_object, x = sgb_model_complete_model_and_x
    v_data = FedNdarray(
        {
            sf_production_setup_devices_aby3.alice: (
                sf_production_setup_devices_aby3.alice(lambda: x[:, :15])()
            ),
            sf_production_setup_devices_aby3.bob: (
                sf_production_setup_devices_aby3.bob(lambda: x[:, 15:])()
            ),
        },
        partition_way=PartitionWay.VERTICAL,
    )

    true_predict = reveal(model.predict(v_data))

    assert model.base == reveal(
        env.alice(lambda model: model.base)(complete_model_object)
    )

    complete_model_predict = reveal(
        env.alice(lambda model, x: model.predict(x))(complete_model_object, x)
    )

**Comment by zimu-yuxi** [comment]
是双方的，各自特征数据源在各方
可以参考下[此处](https://www.secretflow.org.cn/zh-CN/docs/serving/0.4.0b0/topics/system/intro#architecture)
