### ISSUE TITLE
模型融合的模型提取，无法提取非标签携带方，那非标签携带方可以使用携带方的融合模型吗？

### ISSUE THREAD

**Issue by didadida321** [secretflow/secretflow#1358]
根据官网提供的模型融合例子，模型融合无法提取非标签携带方的模型，那么让alice侧导出模型，提供给bob侧，bob再load模型做预测可行吗？

**Comment by kaixin-haha** [comment]
问题已解决

直接用不行，因为有device的信息
但把模型的参数都导出，用bob的再导入，应该是可以的
test_complete_model_serde 里头的代码，这么稍微改下就好了，核心是把alice导出的模型参数文件，用bob再次导入

`
 with open('model.json', 'r') as file:
        loaded_obj = env.bob(lambda x: from_dict(json.loads(file.read())))(
            ''
        )
`

**Comment by aokaokd** [comment]
好的，感谢您的反馈
