### ISSUE TITLE
对于 sf.reveal  揭示共同中间变量的一些困惑

### ISSUE THREAD

**Issue by Diomchen** [secretflow/secretflow#1360]
### Issue Type

Others

### Source

binary

### Secretflow Version

v1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
情况：我发现 sf.reveal 在具体过程中会有较大的时间消耗，想了解在特定情况下，如何减少类似reveal操作的消耗时间。
```

### Reproduction code to reproduce the issue.

```shell
**背景：**
存在 A,B,C 三方，假设分别拥有数据 a,b,c。在本地数据不泄露的情况下，参与一个计算得到一个共同可reveal的中间值，假设为 r_temp = a+b+c ,此时再需要进行一个明文函数的计算E=f(r_temp), 然后 E 需要传递回各方再进行本地计算。

**想要的到的优化：**
能否有方法减少共同中间量 r_temp 揭示所耗时间，或者是否有其他方案达到整体时间减少这个目的？
```

**Comment by aokaokd** [comment]
收到您的问题，一般在正式场景中，不会用到 sf.reveal 函数。根据您上面描述的需求，您直接使用PYU对象进行明文计算即可跳过sf.reveal 这一环节

**Comment by Diomchen** [comment]
> 收到您的问题，一般在正式场景中，不会用到 sf.reveal 函数。根据您上面描述的需求，您直接使用PYU对象进行明文计算即可跳过sf.reveal 这一环节

但是，我三方PYU该如何在彼此数据不泄露的情况下，进行共同计算？

**Comment by Diomchen** [comment]
PYU 对象直接作运算吗？

**Comment by aokaokd** [comment]
> > 收到您的问题，一般在正式场景中，不会用到 sf.reveal 函数。根据您上面描述的需求，您直接使用PYU对象进行明文计算即可跳过sf.reveal 这一环节
> 
> 但是，我三方PYU该如何在彼此数据不泄露的情况下，进行共同计算？
sorry，刚才没有理解您的意思。如果您在计算过程中需要用到 其他方的数据进行密算，可以使用SPU。  同时可以用密算来直接计算E=f(r_temp)，无需使用reveal函数。

**Comment by Diomchen** [comment]
嗯嗯，现在就是这个 E 结果三方都需要知道，因为其需要参与各方后续的本地计算，因此我感觉还是需要reveal E

**Comment by Diomchen** [comment]
可能我需要的是 spu 对象-> pyu？

**Comment by ian-huu** [comment]
sf.reveal 操作执行了：1、等待计算结果，2、广播到所有方，这两个操作。理论上不会有太大的性能问题。

能否用更加实际的例子说明一下哪里遇到了性能问题？（一种可能得情况是 reveal 需要等待计算结果，如果前面有复杂的计算的话，就会看起来慢）

**Comment by fy222fy** [comment]
这里E需要三方都知道，那么r_temp一定也需要三方都知道吗，如果不需要的话，只需要reveal最后的E即可，尽量减少reveal的次数，这样依赖，E也可以直接在spu里面继续做计算，不用等待E，reveal出来，再把E分发给各个参与方，可以并行进行计算。

还是要考虑下场景，到底什么时候需要reveal

**Comment by Diomchen** [comment]
> sf.reveal 操作执行了：1、等待计算结果，2、广播到所有方，这两个操作。理论上不会有太大的性能问题。
> 
> 能否用更加实际的例子说明一下哪里遇到了性能问题？（一种可能得情况是 reveal 需要等待计算结果，如果前面有复杂的计算的话，就会看起来慢）

感谢回复，嗯嗯，若是你说的这种过程，我认为可能是我前面计算方法存在较大消耗，进而体现在 reveal 过程

**Comment by Diomchen** [comment]
> 这里E需要三方都知道，那么r_temp一定也需要三方都知道吗，如果不需要的话，只需要reveal最后的E即可，尽量减少reveal的次数，这样一来，E也可以直接在spu里面继续做计算，不用等待E reveal出来再把E分发给各个参与方。
> 
> 还是要考虑下场景，到底什么时候需要reveal

感谢，确实我将连续计算这个过程拆开了，我再修改测试下
