### ISSUE TITLE
部署allinone时运行install.sh报错

### ISSUE THREAD

**Issue by yedoukk** [secretflow/secretflow#1364]
运行install.sh时报错;
install.sh:32:Bad substitution 
ADM64 or Intel 64-bit architecture detected    
install.sh:149:Syntax error:"(" unexpected

**Comment by aokaokd** [comment]
您好，请提供您的cpu架构类型 x86 or Arm？  另外想问一下，您在使用过程中有修改install.sh吗

**Comment by yedoukk** [comment]
x86_64   没有修改install.sh

**Comment by aokaokd** [comment]
不好意思，这边没复现出来呢，根据您的错误，请您使用官网最新的安装包进行安装，[下载链接](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.6.1b0/deployment_package)
同时，安装时也请您携带端口号，例如：
```
sh  install.sh autonomy -n alice -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls 
参数解释：
容器:                端口对应:外部->内部  部署参数:
secretpad  http     port:  8088->8080   -s 参数
kuscia     http     prot:  18082->8082  -k 参数
kuscia     grpc     port:  18083->8083  -g 参数
kuscia     gateway  port:  18080->1080  -p 参数
```
各个参数解释：[平台安装指引](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.6.1b0/p2p_deploy/platform_installation_guidelines#id1)

**Comment by yedoukk** [comment]
好的

**Comment by yedoukk** [comment]
在未联网的Ubuntu系统环境下，allinone的install.sh的运行命令是不是需要修改一下？有在intsall.sh里面看到前面几个参数都使用了阿里云镜像网站

**Comment by yedoukk** [comment]
在未联网的Ubuntu系统环境下，allinone的install.sh的运行命令是不是需要修改一下？有在intsall.sh里面看到前面几个参数都使用了阿里云镜像网站

**Comment by zimu-yuxi** [comment]
> 在未联网的Ubuntu系统环境下，allinone的install.sh的运行命令是不是需要修改一下？有在intsall.sh里面看到前面几个参数都使用了阿里云镜像网站

不需要的哈，allinone包支持离线安装的，压缩包中已经提供了相关的离线镜像，在image文件夹下

**Comment by yedoukk** [comment]
在未联网的Ubuntu系统环境下，allinone的install.sh的运行命令是不是需要修改一下？有在intsall.sh里面看到前面几个参数都使用了阿里云镜像网站

**Comment by hallowsman** [comment]
> 运行install.sh时报错; install.sh:32:Bad substitution ADM64 or Intel 64-bit architecture detected install.sh:149:Syntax error:"(" unexpected

请问这个问题最终是如何解决的呢？我在ubuntu中也碰到了一样的问题

**Comment by wangzul** [comment]
> > 运行install.sh时报错; install.sh:32:Bad substitution ADM64 or Intel 64-bit architecture detected install.sh:149:Syntax error:"(" unexpected
> 
> 请问这个问题最终是如何解决的呢？我在ubuntu中也碰到了一样的问题

执行sed -i 's/\r$//'  install.sh命令后尝试重新部署

**Comment by wangzul** [comment]
> > > 运行install.sh时报错; install.sh:32:Bad substitution ADM64 or Intel 64-bit architecture detected install.sh:149:Syntax error:"(" unexpected
> > 
> > 
> > 请问这个问题最终是如何解决的呢？我在ubuntu中也碰到了一样的问题
> 
> 执行sed -i 's/\r$//' install.sh命令后尝试重新部署

使用bash install.sh 运行脚本

**Comment by wangzul** [comment]
> > 运行install.sh时报错; install.sh:32:Bad substitution ADM64 or Intel 64-bit architecture detected install.sh:149:Syntax error:"(" unexpected
> 
> 请问这个问题最终是如何解决的呢？我在ubuntu中也碰到了一样的问题

问题解决了吗？

**Comment by hallowsman** [comment]
> > > 运行install.sh时报错; install.sh:32:Bad substitution ADM64 or Intel 64-bit architecture detected install.sh:149:Syntax error:"(" unexpected
> > 
> > 
> > 请问这个问题最终是如何解决的呢？我在ubuntu中也碰到了一样的问题
> 
> 问题解决了吗？

问题已解决 谢谢
