### ISSUE TITLE
部署allinone时运行sh install.sh master

### ISSUE THREAD

**Issue by yedoukk** [secretflow/secretflow#1368]
运行sh install.sh master报错：
[Error] Probe datamesh in container 'root-kuscia-lite-alice' failed
You clould run command that 'docker logs root-kuscia-lite-alice' to check the log

**Comment by zimu-yuxi** [comment]
secretpad的问题，可以迁到相关模块下。
顺便提供下docker版本，系统，allinone包版本，谢谢

**Comment by yedoukk** [comment]
docker20.10   allinone-linux-x86_64-latest

**Comment by aokaokd** [comment]
可能是空间不足导致的，all in one需要8u 16g的空间

**Comment by yedoukk** [comment]
我的是4u8g，装lite版本可以吗

**Comment by aokaokd** [comment]
抱歉，all in one 包暂时没有lite版本的

**Comment by yedoukk** [comment]
如何通过serectpad的安装包手动安装serectpad？

**Comment by aokaokd** [comment]
可以看一下这个文档：https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.8.1b0/development/build_secretpad_cn
