### ISSUE TITLE
请问蚂蚁隐语平台这个差分隐私模块在哪里？差分隐私怎么衡量加多少不会泄露隐私？对于枚举类型的训练数据该如何加差分隐私？

### ISSUE THREAD

**Issue by 1853582** [secretflow/secretflow#1369]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow latest

### OS Platform and Distribution

ubuntu 22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
关于隐语的差分隐私模块似乎没有专门的章节，唯一能找到的是https://github.com/secretflow/secretflow/blob/3937b7b5973bc378636da5ffc2ee00a46351fe9c/secretflow/security/privacy/mechanism/label_dp.py这个代码文件。这个代码文件似乎只是对标签数据进行扰动，而且这个扰动是以一定概率跳变，这个会不会对训练结果产生比较大的影响？
这个代码差分隐私能否保护训练数据不被泄露？现在我有个场景是训练一个XGB模型，但是防止训练出来的模型泄露原始数据，训练数据主要是枚举类型(如男性1，女性0)这种，想解决上述问题应该如何使用隐语的DP能力？
```

### Reproduction code to reproduce the issue.

```shell
请问蚂蚁隐语平台这个差分隐私模块在哪里？差分隐私怎么衡量加多少不会泄露隐私？对于枚举类型的训练数据该如何加差分隐私？
```

**Comment by pchyuan** [comment]
隐语差分隐私没有单独的模块，差分本身逻辑不复杂。
加多少不会泄露隐私这个完全看业务需求，没有一概而论的，但是这部分有理论基础，可以根据隐私损耗预算来设置，简单来说，这里隐私和准确性就是不可两者完全兼得。

**Comment by 1853582** [comment]
如果我训练集的数据基本是枚举类型，那该如何加差分隐私呢？

**Comment by zimu-yuxi** [comment]
> 如果我训练集的数据基本是枚举类型，那该如何加差分隐私呢？

理论是一样的

**Comment by 1853582** [comment]
> > 如果我训练集的数据基本是枚举类型，那该如何加差分隐私呢？
> 
> 理论是一样的

麻烦可以具体说明一下么，比如我的数据集里有一列是男生0，女生1这个特征列，该如何加差分隐私呢？
