### ISSUE TITLE
第一个逻辑回归例子

### ISSUE THREAD

**Issue by YIYEYIYE** [secretflow/secretflow#137]
### Issue Type

Bug

### Source

source

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

centos7

### Python version

3.8.12

### What happend and What you expected to happen.

```shell
第一个逻辑回归例子：执行到sf.reveal的时候就报这个错误。试了试将spu对象给alice变为pyu对象，然后再reveal，还是不行。
ValueError: Task returned 455 objects, but num_returns=2
```

### Reproduction code to reproduce the issue.

```shell
losses = sf.reveal(losses)
plot_losses(PYU_losses)
```

**Comment by 6fj** [comment]
Hi @YIYEYIYE ,

你应该是在尝试https://secretflow.readthedocs.io/en/latest/tutorial/lr_with_spu.html 这个例子吧。我刚刚重新执行了一遍，并没有发生错误。

为了便于定位问题，请

- 直接下载secretflow源码，并用jupyter notebook执行 [docs/tutorial/lr_with_spu.ipynb](https://github.com/secretflow/secretflow/blob/beta/docs/tutorial/lr_with_spu.ipynb).
- 如果仍然出现，请贴出完整的错误信息。

感谢。

**Comment by YIYEYIYE** [comment]
第二天又重跑了一下，可以运行了。两次的区别就是创建线程池那块儿。但往里再研究就不知道具体怎么个情况了。
感谢！

**Comment by 6fj** [comment]
Hi @YIYEYIYE ,

你说的创建线程池是对应哪一块代码？是初始化SPU和PYU设备那一块吗？

**Comment by YIYEYIYE** [comment]
目前不清楚，我也是刚学，慢慢研究下吧
