### ISSUE TITLE
按照文档操作，最终新组件ss_compare没有出现

### ISSUE THREAD

**Issue by byeyang** [secretflow/secretflow#1377]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

release/1.7.x    

### OS Platform and Distribution

linux  kylin

### Python version

3.10.0

### What happend and What you expected to happen.

```shell
按照文档操作，最终新组件ss_compare没有出现
```

### Reproduction code to reproduce the issue.

```shell
https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.7.0b0/more_tutorials/new_components安装此文档操作的。
```

**Comment by lanyy9527** [comment]
您好，麻烦咱这边确认下：
1.secretflow组件是否注册成功了（一般没问题）
2.镜像是否注册，替换为自定义的镜像了（看他是P2P还是中心化，这里 -m参数需要跟随部署模式修改，https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.7.0b0/more_tutorials/new_components#kuscia，或者进kuscia容器内看下sf镜像信息，kubectl get appimage -A ）
3.secretpad侧的组件列表是否有更新(secretpad容器内，/app/config/components/secretflow.json，看下有没有他自定义的组件)

**Comment by byeyang** [comment]
超级感谢解答~
我一一排除了问题，内容如下
[root@root-kuscia-master-localhost-localdomain kuscia]# kubectl get appimage -A
NAME                      AGE
secretflow-nsjail-image   3d14h
sf-serving-image          3d14h
tee-dm-image              3d14h
tee-image                 3d14h
secretflow-image          3d14h
[root@root-kuscia-master-localhost-localdomain kuscia]# ^C
[root@root-kuscia-master-localhost-localdomain kuscia]# 
exit
(base) [root@localhost ~]# docker exec -it root-kuscia-lite-bob /bin/bash
[root@root-kuscia-lite-bob-localhost-localdomain kuscia]# kubectl get appimage -A
E0717 17:34:41.942382    5214 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:34:41.947015    5214 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:34:41.949316    5214 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:34:41.952165    5214 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:34:41.958446    5214 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@root-kuscia-lite-bob-localhost-localdomain kuscia]# 
exit
(base) [root@localhost ~]# docker exec -it root-kuscia-lite-alice /bin/bash
[root@root-kuscia-lite-alice-localhost-localdomain kuscia]# kubectl get appimage -A
E0717 17:36:03.787828    5204 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:36:03.790282    5204 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:36:03.791730    5204 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:36:03.793103    5204 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:36:03.795288    5204 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@root-kuscia-lite-alice-localhost-localdomain kuscia]# kubectl get appimage -A
E0717 17:38:25.385945    5245 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:38:25.435825    5245 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:38:25.437967    5245 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:38:25.439254    5245 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0717 17:38:25.441112    5245 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@root-kuscia-lite-alice-localhost-localdomain kuscia]# 
exit
(base) [root@localhost ~]# 
(base) [root@localhost ~]# docker exec -it root-kuscia-master-secretpad /bin/bash
[root@304aa54f9a66 app]# cat /app/config/components/secretflow.json
省略 有新组件的信息...
——————————————————————————————————————————————————
此时我没有做任何改动，重新去secretpad网页看到了, 自定义组件出现了!  那大概是有延时吗，或者因为，有重启过机器，不知道为什么这样，我昨天有刷新过很多次但都没有出现自定义组件。
1.另外上面的进入节点容器如root-kuscia-lite-alice，执行命令后，显示couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused是正常的吗
2.另外执行的适合出现下面的错误：
![image](https://github.com/user-attachments/assets/9437879f-d225-488a-a369-7d2a3843f857)

**Comment by lanyy9527** [comment]
1. 是正常的，这个错误表示在bob和alice节点无法链接k3s服务。在中心化模式中，k3s通常是内置在master节点，所以在lite节点是无法访问这个API的，必须在master节点中查看；
2. No module named ‘secretflow.protos’ 应该是在secretflow的代码中组件没有正常注册导致的，建议重新修改secretflow代码并打包后进行尝试；

**Comment by byeyang** [comment]
好的，感谢解答~
