### ISSUE TITLE
secretflow/release-ci 镜像无法拉取，有什么方案

### ISSUE THREAD

**Issue by killomsc** [secretflow/secretflow#1379]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

1.7

### OS Platform and Distribution

linux

### Python version

3.10

### What happend and What you expected to happen.

```shell
通过源码尝试制作镜像的时候，很多依赖的镜像无法拉取。比如docker pull secretflow/release-ci:20240619
已经设置了国内源，但还是拉取不了。请问有什么好的处理方法？
```

### Reproduction code to reproduce the issue.

```shell
docker pull secretflow/release-ci:20240619
```

**Comment by BrainWH** [comment]
您好，收到您的问题，我们先内部看一下

**Comment by byeyang** [comment]
docker 桌面版本可以下载，  保存导出save， 导到你需要的地方load,   即可。
