### ISSUE TITLE
secretpad新增节点

### ISSUE THREAD

**Issue by yedoukk** [secretflow/secretflow#1380]
![Uploading 1721268543332.png…]()

**Comment by yedoukk** [comment]
新增节点不可用

**Comment by wangzul** [comment]
> 新增节点不可用

方便提供一下新增节点的命令吗？以及补充一下相关问题的图片信息。

**Comment by yedoukk** [comment]
ray start --head --node-ip-address=172.18.1.245 --port=8090  --resources='{"test-a": 16}' --include-dashboard=False --disable-usage-stats

**Comment by wangzul** [comment]
> ray start --head --node-ip-address=172.18.1.245 --port=8090 --resources='{"test-a": 16}' --include-dashboard=False --disable-usage-stats

您这个是在创建secretflow ray节点吗？如果方便的话您可以把这个问题转在secretflow，可以吧错误日志发一下，您上边的图片我这边无法访问。
