### ISSUE TITLE
使用kuscia接入pir能力，报key not found

### ISSUE THREAD

**Issue by jianjew** [secretflow/secretflow#1384]
使用kuscia（中心化部署）调用pir-setup时，在bob端（作为数据拥有方，alice是查询方）报错key not found， 已经在bob端的/home/kuscia/var/storage/data/目录下生成server_oprf_key，详细日志见附件
[alice.txt](https://github.com/user-attachments/files/16327324/alice.txt)
[bob.txt](https://github.com/user-attachments/files/16327325/bob.txt)
[master.txt](https://github.com/user-attachments/files/16327326/master.txt)
：

**Comment by aokaokd** [comment]
我看看日志，稍后给你回复

**Comment by aokaokd** [comment]
这个不是密钥的问题，看日志了解到你的bob.csv找不到id字段。可以详细说下你是如何集成的吗

**Comment by jianjew** [comment]
kuasic job和component见附件：
[componen_pir.txt](https://github.com/user-attachments/files/16329097/componen_pir.txt)
[kuasic job.txt](https://github.com/user-attachments/files/16329098/kuasic.job.txt)

1、新建一个pir的component，并通过attr传入必要的参数；
2、编译将镜像，向kuacis中注册镜像
2、bob.csv 的数据结构是id2,contact_cellular,contact_telephone,contact_unknown,month_apr,month_aug,month_dec,month_feb,month_jan,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,y
3、alice.csv中是需要查询内容，内容如下：
“id2”
“0”

**Comment by jianjew** [comment]
> 这个不是密钥的问题，看日志了解到你的bob.csv找不到id字段。可以详细说下你是如何集成的吗

请问下您是怎么从日志中看出是找不到id字段的，bob端日志中显示的是“key not found” “key item_count no value”这样的字眼

**Comment by aokaokd** [comment]
我这边复现后，发现这不是导致错误的原因：
![image](https://github.com/user-attachments/assets/75bf0fe8-a369-434e-a5f3-0c24e73e473c)

**Comment by jianjew** [comment]
> 边复现后，发现这不是导致错误的原因：

我这边定位出来了，是内存溢出导致的问题
错误日志是这个：Enforce fail at external/psi/psi/apsi/padding.cc:24] (data.size() + 4) \u003c= max_len. data_size:19 max_len:20
代码为：
std::vector<uint8_t> PaddingData(yacl::ByteContainerView data, size_t max_len) {
  YACL_ENFORCE((data.size() + 4) <= max_len, "data_size:{} max_len:{}",
               data.size(), max_len);

  std::vector<uint8_t> data_with_padding(max_len);
  uint32_t data_size = data.size();

  std::memcpy(&data_with_padding[0], &data_size, sizeof(uint32_t));
  std::memcpy(&data_with_padding[4], data.data(), data.size());

  return data_with_padding;
}
第二个memcpy内存溢出了，像这些内存操作最好要加返回值判断，不然太难定位了。
根本原因是pir_setup函数的label_max_len设置太小导致的。

**Comment by aokaokd** [comment]
好的，目前的日志中包含了很多ray的日志。导致排查困难。目前在调整了
