### ISSUE TITLE
修改spi代码仓的内容，如何打包到secretflow镜像中使用？

### ISSUE THREAD

**Issue by jianjew** [secretflow/secretflow#1389]
现状：
1、拉取secretflow代码仓并编译了镜像；
2、将secretflow镜像注册到kuscia中；
3、通过kuscia api运行psi任务。

问题：
需要在psi代码仓新增逻辑，如何编译？secretflow镜像中如何调用新的psi逻辑？

**Comment by BrainWH** [comment]
您好，请问您是想要新增组件还是想要修改psi的代码？可以具体地描述一下您想要新增的逻辑吗？

**Comment by jianjew** [comment]
> 您好，请问您是想要新增组件还是想要修改psi的代码？可以具体地描述一下您想要新增的逻辑吗？
我在secretflow代码仓新增了一个pir的组件，能通过kuscia api直接调度；
我看源码的调用仓路径是secretflow->spu->spi， 如果我还想修改spi仓的逻辑，整个镜像如何给构建？目前只是在secretflow仓构建镜像，如何能带上spi仓的修改

**Comment by BrainWH** [comment]
你想要修改的是psi仓吗？spi指的是什么？

**Comment by jianjew** [comment]
> 你想要修改的是psi仓吗？spi指的是什么？

是psi仓

**Comment by huocun-ant** [comment]
> 现状： 1、拉取secretflow代码仓并编译了镜像； 2、将secretflow镜像注册到kuscia中； 3、通过kuscia api运行psi任务。
> 
> 问题： 需要在psi代码仓新增逻辑，如何编译？secretflow镜像中如何调用新的psi逻辑？

当前psi的pybind是在[SPU](https://github.com/secretflow/spu/blob/main/spu/psi.py)里做的。所以的你的修改顺序是这样的：
1. 修改PSI的代码，也就是这个仓。
2. 修改SPU仓的依赖，也就是[这里](https://github.com/secretflow/spu/blob/54ec5f1b6f5f2125fa84a01ff247d8ecb3d64bc4/bazel/repositories.bzl#L49)
3. (可选）如果你要修改psi的pybind接口，可以修改[这里](https://github.com/secretflow/spu/blob/main/spu/psi.py)
4. 更新[secretflow]()仓里的spu的依赖，就是[这里](https://github.com/secretflow/secretflow/blob/8f3bb41ed65f1ee6057b065d0bfddc51f8b01e67/requirements.txt#L34)

**Comment by jianjew** [comment]
> > 现状： 1、拉取secretflow代码仓并编译了镜像； 2、将secretflow镜像注册到kuscia中； 3、通过kuscia api运行psi任务。
> > 问题： 需要在psi代码仓新增逻辑，如何编译？secretflow镜像中如何调用新的psi逻辑？
> 
> 当前psi的pybind是在[SPU](https://github.com/secretflow/spu/blob/main/spu/psi.py)里做的。所以的你的修改顺序是这样的：
> 
> 1. 修改PSI的代码，也就是这个仓。
> 2. 修改SPU仓的依赖，也就是[这里](https://github.com/secretflow/spu/blob/54ec5f1b6f5f2125fa84a01ff247d8ecb3d64bc4/bazel/repositories.bzl#L49)，这里你需要修改bazel的配置文件，你可以修改成让bazel依赖远端或本地你的最新修改
> 3. (可选）如果你要修改psi的pybind接口，可以修改[这里](https://github.com/secretflow/spu/blob/main/spu/psi.py)
> 4. 修改好后，你需要打一个spu的whl包，使用[这个脚本](https://github.com/secretflow/spu/blob/main/build_wheel_entrypoint.sh)
> 5. 更新secretflow仓里的spu的依赖版本，就是[这里](https://github.com/secretflow/secretflow/blob/8f3bb41ed65f1ee6057b065d0bfddc51f8b01e67/requirements.txt#L34)

你好，再请教一个问题：
我在psi仓中新增了读取数据源的逻辑，引用的是三方poco依赖，psi能编译通过，但是进行到第4步， 在spu中打包whl时，有如下报错：
ERROR: /home/liangjiaxing/.cache/bazel/_bazel_liangjiaxing/fbe8b6889124e50a4985151a153352e0/external/psi/psi/datasource/BUILD.bazel:59:11: no such package '@org_pocoproject_poco//': The repository '@org_pocoproject_poco' could not be resolved: Repository '@org_pocoproject_poco' is not defined and referenced by '@psi//psi/datasource:odbc_adaptor'
ERROR: Analysis of target '//spu:init' failed; build aborted: 
INFO: Elapsed time: 4.524s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (206 packages loaded, 13904 targets configured)
在spu编译拉psi仓时不会自动编译psi仓吗？ 这样的问题该如何解决？感谢
