### ISSUE TITLE
phe的两个问题

### ISSUE THREAD

**Issue by deadlywing** [secretflow/secretflow#139]
```python
kit = hnp.setup(phe.SchemaType.ZPaillier, 2048)
encryptor = kit.encryptor()
```
在官网文档上看到使用的`schemaType`是`phe.SchemaType.ZPaillier `；

```python
FPaillier = None # (!) forward: FPaillier, real value is '<SchemaType.FPaillier: 2>'
Mock = None # (!) forward: Mock, real value is '<SchemaType.Mock: 0>'
ZPaillier = None # (!) forward: ZPaillier, real value is '<SchemaType.ZPaillier: 1>'
```
看pycharm生成的stub里，应该还有`FPaillier`，在文档里没看到关于这个的介绍，但是可以注意到`phe.SchemaType.ZPaillier`的加密速度显著比`SchemaType.FPaillier`快。相对的，`phe.SchemaType.ZPaillier`的初始化阶段也会显著的比`SchemaType.FPaillier`慢。

另外，对象是int时，两个schema加密后解密都是正确的；我一开始以为`FPaillier`是针对浮点数(F)封装了定点化的加密方式，但是发现好像并不是。
```python
from heu import numpy as hnp
from heu import phe

kit = hnp.setup(phe.SchemaType.ZPaillier, 2048)
encryptor = kit.encryptor()
decryptor = kit.decryptor()
evaluator = kit.evaluator()

plaintext = [0.78, 1.1]
ct_arr = encryptor.encrypt(hnp.array(plaintext))
pt_arr = decryptor.decrypt(ct_arr)

print(plaintext)   # [0.78, 1.1]
print(pt_arr) 
# [[0]
#  [1]]
```

问题主要有两个：
1. `SchemaType.FPaillier`和`SchemaType.ZPaillier`分别代表什么含义？提供这两个选择是否存在什么需要trade-off的东西？
2. 如果想执行浮点数加解密，有什么推荐的方式么？（看文档的意思是需要自己先把cleartext用Float编码器做定点化，scale成plaintext，加解密后，再使用Float编码器从plaintext转化为cleartext，有现成的语法糖封装么？）

**Comment by usafchn** [comment]
@deadlywing 您好，

简单的回答：
1. Python API 中，FPaillier 与 ZPaillier 功能完全等价，并且 ZPaillier 性能更高，任何情况下都应该选择 ZPaillier

3. 加密浮点数需要外挂的 encoder，参考 [快速入门](https://heu.readthedocs.io/zh_CN/latest/getting_started/quick_start.html) 和 [矩阵运算](https://heu.readthedocs.io/zh_CN/latest/getting_started/numpy.html) 关于 Encoder 的介绍。

```
edr = phe.FloatEncoder()
harr = hnp.array([1.1, 2.1], edr)
# .... encrypt and decrypt ....
nparr = harr.to_numpy(edr)
```
encoder 的本质是把浮点数乘上，所以特别注意密态乘法导致的 scale 翻倍问题，这点在[文档](https://heu.readthedocs.io/zh_CN/latest/getting_started/numpy.html#id7)中有更详细说明。

补充回答：

在 C++ Api 层面，FPaillier 与 ZPaillier 确实有一些不同，FPaillier 对标 [Python-Paillier](https://python-paillier.readthedocs.io/en/develop/)，相当于把 Python-Paillier 的逻辑用C++翻译了一遍，其特点是算法层面支持浮点数加密，原理是把 scale 比特数作为明文打包在密文中，密态运算阶段算法会自行对齐、更新 scale 值。而 ZPaillier 是我们实现的一个高度优化的 Paillier 版本，只支持整数加密，性能比 FPaillier 高很多。

FPailiier 的浮点数运算接口在 Python api 中没有暴露出来，所以 Python 端统一选 ZPaillier。

**Comment by deadlywing** [comment]
非常感谢回复，，还想请问一个设计上的问题，，很多其他库都会在密文对象上重载加减乘除函数，这样在api使用上会相对更加简便灵活。（比如FATE的`PaillierEncryptedNumber`和Tenseal的`CKKSTensor`等）
```python
edr = phe.FloatEncoder()
enc_v1 = hnp.array([1.1, 2.1], edr)

# 因为没有对操作符重载，所以以下操作不支持
enc_v1 + enc_v1  
enc_v1 * 1.2
```

**Comment by usafchn** [comment]
> 非常感谢回复，，还想请问一个设计上的问题，，很多其他库都会在密文对象上重载加减乘除函数，这样在api使用上会相对更加简便灵活。（比如FATE的`PaillierEncryptedNumber`和Tenseal的`CKKSTensor`等）

主要问题在于序列化和反序列化的数据量大小，因为 HE 运算依赖公钥，如果重载运算符，每个密文需要 ref 对应的 pk，这在单方运算时没什么问题，但如果要把密文序列化，则得把 pk（或者 pk 的 id）一同序列化，以便对端可以成功返序列化。现在的设计相当于把 pk 和 ciphertext 解耦了，由上层保证两者之间的对应关系，从而减少网络传输量。

至于明文矩阵运算，重载运算符是可以的，但是没有必要，因为 op 两边都是 plaintext-matrix 的话，一般人都会选择 numpy 库吧 - -
