### ISSUE TITLE
后端自定义模型相关问题

### ISSUE THREAD

**Issue by SabYic** [secretflow/secretflow#1395]
### Issue Type

Others

### Source

source

### Secretflow Version

secreflow0.6.13b0

### OS Platform and Distribution

Ubuntu20.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
想问一下我想自己定义损失函数来构建一个密态机器学习模型应该怎么做？比如说我隐私求交后想训练模型，这时候的数据应该是密态的？这时候如果我不用secureboost而是自定义一个机器学习模型进行训练是可行的吗？
```

### Reproduction code to reproduce the issue.

```shell
（无相关代码）
```

**Comment by lanyy9527** [comment]
1. 隐私求交后的数据不是密态的
2. 如果是两方接收结果，要保证A表和B表的ID是一样的，手动合并后，可以通过一般的tf或者pytorch来训练
