### ISSUE TITLE
关于SecretPad All In One部署后，合作节点不可用

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1396]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.7.0b0

### OS Platform and Distribution

Kylin 10

### Python version

3.10

### Bazel version

6.5

### GCC/Compiler version

11

### What happend and What you expected to happen.

```shell
我按照SecretPad All In One操作步骤，先安装docker，后执行sh install.sh autonomy -n alice -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls来安装，但安装后，合作节点的"通讯状态"提示不可用，然后我又在官方看到"mtls: 这种模式也使用 HTTPS 进行通信，但它支持双向 TLS 验证，需要手动交换证书以建立安全连接"，这里有具体手动交换证书的手册吗？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by coderSun20201112** [comment]
> 通讯状态不可用可以检查：
> 
> 1. 通讯地址是否为本机对外IP地址；
> 2. 如果在同一台机器中部署，需要确认kuscia和pad的端口不被占用；
> 3. 检查协议是否一致；
> 4. 使用 curl -kvvv https://1.1.1.1:18080/ 检查通信是否正常；
> 
> 第二个问题可以参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/deployment/Docker_deployment_kuscia/deploy_p2p_cn#id4

按照参考链接，已经把alice与bob之间的HTTPS证书互换了，然后使用curl -kvvv https://X.X.X.X:10080/测试，返回的是401，然后我又做了配置授权，删掉合作节点，再次新建合作节点，但"通讯状态"还是不可用

**Comment by zimu-yuxi** [comment]
> > 通讯状态不可用可以检查：
> > 
> > 1. 通讯地址是否为本机对外IP地址；
> > 2. 如果在同一台机器中部署，需要确认kuscia和pad的端口不被占用；
> > 3. 检查协议是否一致；
> > 4. 使用 curl -kvvv https://1.1.1.1:18080/ 检查通信是否正常；
> > 
> > 第二个问题可以参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/deployment/Docker_deployment_kuscia/deploy_p2p_cn#id4
> 
> 按照参考链接，已经把alice与bob之间的HTTPS证书互换了，然后使用curl -kvvv [https://X.X.X.X:10080/测试，返回的是401，然后我又做了配置授权，删掉合作节点，再次新建合作节点，但"通讯状态"还是不可用](https://X.X.X.X:10080/%E6%B5%8B%E8%AF%95%EF%BC%8C%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AF401%EF%BC%8C%E7%84%B6%E5%90%8E%E6%88%91%E5%8F%88%E5%81%9A%E4%BA%86%E9%85%8D%E7%BD%AE%E6%8E%88%E6%9D%83%EF%BC%8C%E5%88%A0%E6%8E%89%E5%90%88%E4%BD%9C%E8%8A%82%E7%82%B9%EF%BC%8C%E5%86%8D%E6%AC%A1%E6%96%B0%E5%BB%BA%E5%90%88%E4%BD%9C%E8%8A%82%E7%82%B9%EF%BC%8C%E4%BD%86%22%E9%80%9A%E8%AE%AF%E7%8A%B6%E6%80%81%22%E8%BF%98%E6%98%AF%E4%B8%8D%E5%8F%AF%E7%94%A8)

双方都做路由了吗，kubectl get cdr -A 双方容器都看下

**Comment by coderSun20201112** [comment]
> > > 通讯状态不可用可以检查：
> > > 
> > > 1. 通讯地址是否为本机对外IP地址；
> > > 2. 如果在同一台机器中部署，需要确认kuscia和pad的端口不被占用；
> > > 3. 检查协议是否一致；
> > > 4. 使用 curl -kvvv https://1.1.1.1:18080/ 检查通信是否正常；
> > > 
> > > 第二个问题可以参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/deployment/Docker_deployment_kuscia/deploy_p2p_cn#id4
> > 
> > 
> > 按照参考链接，已经把alice与bob之间的HTTPS证书互换了，然后使用curl -kvvv [https://X.X.X.X:10080/测试，返回的是401，然后我又做了配置授权，删掉合作节点，再次新建合作节点，但"通讯状态"还是不可用](https://X.X.X.X:10080/%E6%B5%8B%E8%AF%95%EF%BC%8C%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AF401%EF%BC%8C%E7%84%B6%E5%90%8E%E6%88%91%E5%8F%88%E5%81%9A%E4%BA%86%E9%85%8D%E7%BD%AE%E6%8E%88%E6%9D%83%EF%BC%8C%E5%88%A0%E6%8E%89%E5%90%88%E4%BD%9C%E8%8A%82%E7%82%B9%EF%BC%8C%E5%86%8D%E6%AC%A1%E6%96%B0%E5%BB%BA%E5%90%88%E4%BD%9C%E8%8A%82%E7%82%B9%EF%BC%8C%E4%BD%86%22%E9%80%9A%E8%AE%AF%E7%8A%B6%E6%80%81%22%E8%BF%98%E6%98%AF%E4%B8%8D%E5%8F%AF%E7%94%A8)
> 
> 双方都做路由了吗，kubectl get cdr -A 双方容器都看下

![微信图片_20240731111028](https://github.com/user-attachments/assets/d2b9f7ad-0829-4a8c-b736-9d8295bb8f02)
![微信图片_20240731111032](https://github.com/user-attachments/assets/453ffab1-5765-4e96-9957-d0764acd7d3b)

**Comment by lanyy9527** [comment]
双方的授权状态都显示为true吗？

**Comment by coderSun20201112** [comment]
> 双方的授权状态都显示为true吗？

在alice节点中，alice-bob/bob-alice的READY都是true，
在bob节点中，alice1-bob没有显示READY状态，bob-alice1的READY是false，alice-bob/bob-alice的READ都是true，
且我通过HTML界面新增合作节点的时候，界面名称是alice/bob，节点标识是alice/bob时，总是提示新增失败，只有改成alice1或者bob1才可以新增合作节点

**Comment by lanyy9527** [comment]
1. 目前显示alice和bob两个节点的授权是正常的，alice1-bob节点之间授权失败；
可以看下授权失败的日志原因：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/reference/troubleshoot/networkauthorizationcheck#id3
3. 是在alice方，添加合作节点bob的时候失败吗？是否有截图

**Comment by coderSun20201112** [comment]
> 1. 目前显示alice和bob两个节点的授权是正常的，alice1-bob节点之间授权失败；
>    可以看下授权失败的日志原因：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/reference/troubleshoot/networkauthorizationcheck#id3
> 2. 是在alice方，添加合作节点bob的时候失败吗？是否有截图

问题1正在看，
问题2，在alice节点添加bob、bob节点添加alice都是失败的

**Comment by zimu-yuxi** [comment]
> > 双方的授权状态都显示为true吗？
> 
> 在alice节点中，alice-bob/bob-alice的READY都是true， 在bob节点中，alice1-bob没有显示READY状态，bob-alice1的READY是false，alice-bob/bob-alice的READ都是true， 且我通过HTML界面新增合作节点的时候，界面名称是alice/bob，节点标识是alice/bob时，总是提示新增失败，只有改成alice1或者bob1才可以新增合作节点

“只有改成alice1或者bob1才可以新增合作节点”，domain是唯一的，已经存在alice，无法再创建alice

“在alice节点中，alice-bob/bob-alice的READY都是true， 在bob节点中，alice1-bob没有显示READY状态，bob-alice1的READY是false，alice-bob/bob-alice的READ都是true”，alice的节点你无需关注，目前看时通信是没问题的，你需要看下alice1的节点，需要alcie1和bob双方互相建立路由

**Comment by coderSun20201112** [comment]
> > > 双方的授权状态都显示为true吗？
> > 
> > 
> > 在alice节点中，alice-bob/bob-alice的READY都是true， 在bob节点中，alice1-bob没有显示READY状态，bob-alice1的READY是false，alice-bob/bob-alice的READ都是true， 且我通过HTML界面新增合作节点的时候，界面名称是alice/bob，节点标识是alice/bob时，总是提示新增失败，只有改成alice1或者bob1才可以新增合作节点
> 
> “只有改成alice1或者bob1才可以新增合作节点”，domain是唯一的，已经存在alice，无法再创建alice
> 
> “在alice节点中，alice-bob/bob-alice的READY都是true， 在bob节点中，alice1-bob没有显示READY状态，bob-alice1的READY是false，alice-bob/bob-alice的READ都是true”，alice的节点你无需关注，目前看时通信是没问题的，你需要看下alice1的节点，需要alcie1和bob双方互相建立路由

我计划重装SecretPad All In One再试试，如果还是不行就使用-P tls参数
