### ISSUE TITLE
Secretflow All In One功能咨询

### ISSUE THREAD

**Issue by dyx0001** [secretflow/secretflow#1398]
### Issue Type

Feature Request

### Source

source

### Secretflow Version

secretflow 1.8.0.b0

### OS Platform and Distribution

centos 7.9 

### Python version

3.10

### What happend and What you expected to happen.

```shell
我们这里有个项目需要每天定时自动执行100个左右两两隐私求交并反回求交结果，关于Secretflow All In One中，有没有相关API直接调用，向数据库里添加一条数据，来自动发起任务，通过Secretflow All In One调用相关组件实现隐私求交，最后结果可以在SecretPad上查看？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by wangzul** [comment]
这个问题分为2个方面回答
1.我们这里有个项目需要每天定时自动执行100个左右两两隐私求交并反回求交结果，关于Secretflow All In One中，有没有相关API直接调用，向数据库里添加一条数据，来自动发起任务，
目前kusciaAPI是不支持定时创建任务的，可以自行修改代码或者外部定时任务调用API创建隐私求教任务

2.有没有相关API直接调用，向数据库里添加一条数据，来自动发起任务，通过Secretflow All In One调用相关组件实现隐私求交，最后结果可以在SecretPad上查看？
目前SecretPad不支持直接调用组件实现隐私求教需要通过二次开发来满足需求。

**Comment by dyx0001** [comment]
有个问题想咨询一下，SecretPad All In One部署的时候涉及很多端口，是否可以通过Nginx将外部端口都映射到一个端口上对外提供服务

**Comment by wangzul** [comment]
> 有个问题想咨询一下，SecretPad All In One部署的时候涉及很多端口，是否可以通过Nginx将外部端口都映射到一个端口上对外提供服务

1.如果需要使用nginx做端口映射，可以考虑配置nginx路由来实现.
比如 secretpad 访问端口为8080；nginx:port/secretpad
比如 kuscia的端口是1080【18080】[可以通过]nginx:port/kuscia
