### ISSUE TITLE
Secretflow All in One做PSI时报错

### ISSUE THREAD

**Issue by dyx0001** [secretflow/secretflow#1401]
### Issue Type

Bug

### Source

source

### Secretflow Version

v1.8.0.b0

### OS Platform and Distribution

centos 7.9 

### Python version

3.10

### What happend and What you expected to happen.

```shell
SecretPad All in One 创建训练流求交报错
```

### Reproduction code to reproduce the issue.

```shell
2024-08-03 01:36:52 INFO the jobId=ijqd, taskId=ijqd-xxyvrwkz-node-35 start ...
2024-08-03 01:37:22 INFO the jobId=ijqd, taskId=ijqd-xxyvrwkz-node-35 failed: party bob failed msg: container[secretflow] terminated state reason "Error", message: "tflow/kuscia/entry.py\", line 547, in <module>
    main()
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 527, in main
    res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/entry.py\", line 176, in comp_eval
    res = comp.eval(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1132, in eval
    raise e from None
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1127, in eval
    ret = self.__eval_callback(ctx=ctx, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py\", line 374, in two_party_balanced_psi_eval_fn
    report = spu.psi(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py\", line 2097, in psi
    return dispatch(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py\", line 615, in psi
    return sfd.get(res)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py\", line 156, in get
    return fed.get(object_refs)
  File \"/usr/local/lib/python3.10/site-packages/fed/api.py\", line 621, in get
    values = ray.get(ray_refs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/worker.py\", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
\tclass_name: SPURuntime
\tactor_id: 593501fa57ce9a24f3372ba301000000
\tpid: 603
\tnamespace: 6b839ef8-f131-4173-a335-0747602e6477
\tip: ijqd-xxyvrwkz-node-35-0-global.bob.svc
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:18.976] [info] [launch.cc:119] PSI config: {\"protocol_config\":{\"protocol\":\"PROTOCOL_RR22\",\"role\":\"ROLE_RECEIVER\",\"broadcast_result\":true},\"input_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/learn_440_1980-01-01_1924362153.csv\"},\"output_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/ijqd-xxyvrwkz-node-35-output-0\"},\"keys\":[\"x3\"],\"left_side\":\"ROLE_RECEIVER\"}
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:18.976] [info] [receiver.cc:37] [Rr22PsiReceiver::Init] start
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:18.976] [info] [interface.cc:78] [AbstractPsiParty::Init] start
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.032] [info] [interface.cc:136] [AbstractPsiParty::Init][Check csv pre-process] start
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.052] [info] [csv_checker.cc:243] Executing script to get duplicates: LC_ALL=C tail -n +2 /tmp/583e5a13-483c-49d6-b120-615065344c6a.psi_checked | LC_ALL=C sort --parallel=8 --buffer-size=1G --stable | LC_ALL=C uniq -d > /tmp/583e5a13-483c-49d6-b120-615065344c6a.psi_checked_duplicates
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.137] [info] [interface.cc:145] [AbstractPsiParty::Init][Check csv pre-process] end
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.198] [info] [interface.cc:183] [AbstractPsiParty::Init] end
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.198] [info] [receiver.cc:42] [Rr22PsiReceiver::Init] end
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.198] [info] [receiver.cc:47] [Rr22PsiReceiver::PreProcess] start
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.198] [info] [bucket_psi.cc:516] psi protocol=3, rank=0 item_size=1000
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.198] [info] [bucket_psi.cc:516] psi protocol=3, rank=1 item_size=1000
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.200] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file /home/kuscia/var/storage/data/learn_440_1980-01-01_1924362153.csv.
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.201] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file /home/kuscia/var/storage/data/learn_440_1980-01-01_1924362153.csv.
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.203] [info] [receiver.cc:81] [Rr22PsiReceiver::PreProcess] end
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.204] [info] [receiver.cc:86] [Rr22PsiReceiver::Online] start
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.209] [info] [bucket.cc:37] psi protocol=3, rank=0, inputs_size=1000
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.209] [info] [bucket.cc:37] psi protocol=3, rank=1, inputs_size=1000
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.209] [info] [bucket.cc:50] run psi bucket_idx=0, bucket_item_size=1000 
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.212] [info] [thread_pool.cc:30] Create a fixed thread pool with size 7
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.214] [info] [rr22_psi.cc:163] out buffer begin
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.214] [info] [rr22_psi.cc:167] out buffer end
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.221] [info] [rr22_oprf.cc:470] a_,b_ size:1436 1436
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.221] [info] [rr22_oprf.cc:472] begin vole recv
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.222] [info] [rr22_oprf.cc:489] solve begin
\x1b[36m(SPURuntime(device_id=None, party=bob) pid=603)\x1b[0m [2024-08-02 17:37:19.222] [info] [rr22_oprf.cc:491] solve end
\x1b[33m(raylet)\x1b[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff593501fa57ce9a24f3372ba301000000 Worker ID: aff39b5d314b5bf2be1bb8db86096851e59e5767ce21bbba4d3fa3d1 Node ID: a9d6a4b025b0032e1a5f30d6c9931a6e13b3eea9ba89eb358e50dd86 Worker IP address: ijqd-xxyvrwkz-node-35-0-global.bob.svc Worker port: 10012 Worker PID: 603 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
"
```

**Comment by aokaokd** [comment]
你的数据中有重复项吗，开启重复项检查，换成ecdh协议试一下

**Comment by dyx0001** [comment]
刚才两个节点分别造了三条数据，其中有一个交集，执行ecdh协议的求交以及开启重复检查，还是报错，报错信息如下：

2024-08-05 23:59:33 INFO the jobId=mcmk, taskId=mcmk-lhvmekhd-node-35 start ...
2024-08-06 00:00:00 INFO the jobId=mcmk, taskId=mcmk-lhvmekhd-node-35 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "nction::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697

stacktrace: 
#0 psi::ecdh::EcdhPsiReceiver::PreProcess()+0x7f5a4eee7f34
#1 psi::RunPsi()+0x7f5a4eedaab0
#2 psi::BindLibs()::{lambda()#3}::operator()()+0x7f5a4eed0205
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner
    self.run()
  File \"/usr/local/lib/python3.10/threading.py\", line 953, in run
    self._target(*self._args, **self._kwargs)
  File \"/usr/local/lib/python3.10/site-packages/fed/_private/message_queue.py\", line 51, in _loop
    res = self._msg_handler(message)
  File \"/usr/local/lib/python3.10/site-packages/fed/cleanup.py\", line 47, in <lambda>
    lambda msg: self._process_data_sending_task_return(msg),
  File \"/usr/local/lib/python3.10/site-packages/fed/cleanup.py\", line 166, in _process_data_sending_task_return
    send(
  File \"/usr/local/lib/python3.10/site-packages/fed/proxy/barriers.py\", line 502, in send
    get_global_context().get_cleanup_manager().push_to_sending(
AttributeError: 'NoneType' object has no attribute 'get_cleanup_manager'
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [920.183]       perfetto.cc:47470 Tracing session 1 ended, total sessions:0
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/runpy.py\", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 547, in <module>
    main()
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 527, in main
    res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/entry.py\", line 176, in comp_eval
    res = comp.eval(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1132, in eval
    raise e from None
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1127, in eval
    ret = self.__eval_callback(ctx=ctx, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py\", line 374, in two_party_balanced_psi_eval_fn
    report = spu.psi(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py\", line 2097, in psi
    return dispatch(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py\", line 615, in psi
    return sfd.get(res)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py\", line 156, in get
    return fed.get(object_refs)
  File \"/usr/local/lib/python3.10/site-packages/fed/api.py\", line 621, in get
    values = ray.get(ray_refs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/worker.py\", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): \x1b[36mray::SPURuntime.psi()\x1b[39m (pid=603, ip=mcmk-lhvmekhd-node-35-0-global.alice.svc, actor_id=69b2edcc8c4408d316e163bc01000000, repr=SPURuntime(device_id=None, party=alice))
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py\", line 1379, in psi
    report = spu.psi.psi(config, self.link)
  File \"/usr/local/lib/python3.10/site-packages/spu/psi.py\", line 118, in psi
    report_str = libpsi.libs.psi(
RuntimeError: what: 
\t[Enforce fail at external/psi/psi/cryptor/cryptor_selector.cc:92] cryptor != nullptr. FourQ requires AVX2 instruction
Stacktrace:
#0 psi::ecdh::EcdhPsiReceiver::PreProcess()+0x7f5a4eee7f34
#1 psi::RunPsi()+0x7f5a4eedaab0
#2 psi::BindLibs()::{lambda()#3}::operator()()+0x7f5a4eed0205
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697

stacktrace: 
#0 psi::ecdh::EcdhPsiReceiver::PreProcess()+0x7f5a4eee7f34
#1 psi::RunPsi()+0x7f5a4eedaab0
#2 psi::BindLibs()::{lambda()#3}::operator()()+0x7f5a4eed0205
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [info] [launch.cc:119] PSI config: {\"protocol_config\":{\"protocol\":\"PROTOCOL_ECDH\",\"role\":\"ROLE_RECEIVER\",\"broadcast_result\":true,\"ecdh_config\":{\"curve\":\"CURVE_FOURQ\"}},\"input_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/learn_1_2074372473.csv\"},\"output_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/mcmk-lhvmekhd-node-35-output-0\"},\"keys\":[\"id\"],\"advanced_join_type\":\"ADVANCED_JOIN_TYPE_LEFT_JOIN\",\"left_side\":\"ROLE_RECEIVER\"}
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [info] [receiver.cc:41] [EcdhPsiReceiver::Init] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [info] [interface.cc:78] [AbstractPsiParty::Init] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [warning] [interface.cc:299] The check of duplicated items will be skiped while advanced join is enabled. 
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.996] [info] [interface.cc:91] [AbstractPsiParty::Init][Advanced join pre-process] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.998] [info] [key.cc:91] Executing sort scripts: tail -n +2 /home/kuscia/var/storage/data/learn_1_2074372473.csv | LC_ALL=C sort  --parallel=8 --buffer-size=1G --stable --field-separator=, --key=1,1  >>/tmp/receiver_fb7dbac8-7119-4993-8a60-14b40cb51faf_advanced_join_sorted_input.csv
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.028] [info] [key.cc:93] Finished sort scripts: tail -n +2 /home/kuscia/var/storage/data/learn_1_2074372473.csv | LC_ALL=C sort  --parallel=8 --buffer-size=1G --stable --field-separator=, --key=1,1  >>/tmp/receiver_fb7dbac8-7119-4993-8a60-14b40cb51faf_advanced_join_sorted_input.csv, ret=0
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.044] [info] [interface.cc:113] [AbstractPsiParty::Init][Advanced join pre-process] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.049] [info] [interface.cc:183] [AbstractPsiParty::Init] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.049] [info] [receiver.cc:49] [EcdhPsiReceiver::Init] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.049] [info] [receiver.cc:54] [EcdhPsiReceiver::PreProcess] start
"

**Comment by dyx0001** [comment]
刚才两个节点分别造了三条数据，其中有一个交集，执行ecdh协议的求交以及开启重复检查，还是报错，报错信息如下：

2024-08-05 23:59:33 INFO the jobId=mcmk, taskId=mcmk-lhvmekhd-node-35 start ...
2024-08-06 00:00:00 INFO the jobId=mcmk, taskId=mcmk-lhvmekhd-node-35 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "nction::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697

stacktrace: 
#0 psi::ecdh::EcdhPsiReceiver::PreProcess()+0x7f5a4eee7f34
#1 psi::RunPsi()+0x7f5a4eedaab0
#2 psi::BindLibs()::{lambda()#3}::operator()()+0x7f5a4eed0205
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner
    self.run()
  File \"/usr/local/lib/python3.10/threading.py\", line 953, in run
    self._target(*self._args, **self._kwargs)
  File \"/usr/local/lib/python3.10/site-packages/fed/_private/message_queue.py\", line 51, in _loop
    res = self._msg_handler(message)
  File \"/usr/local/lib/python3.10/site-packages/fed/cleanup.py\", line 47, in <lambda>
    lambda msg: self._process_data_sending_task_return(msg),
  File \"/usr/local/lib/python3.10/site-packages/fed/cleanup.py\", line 166, in _process_data_sending_task_return
    send(
  File \"/usr/local/lib/python3.10/site-packages/fed/proxy/barriers.py\", line 502, in send
    get_global_context().get_cleanup_manager().push_to_sending(
AttributeError: 'NoneType' object has no attribute 'get_cleanup_manager'
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [920.183]       perfetto.cc:47470 Tracing session 1 ended, total sessions:0
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/runpy.py\", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 547, in <module>
    main()
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 527, in main
    res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/entry.py\", line 176, in comp_eval
    res = comp.eval(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1132, in eval
    raise e from None
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1127, in eval
    ret = self.__eval_callback(ctx=ctx, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py\", line 374, in two_party_balanced_psi_eval_fn
    report = spu.psi(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py\", line 2097, in psi
    return dispatch(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py\", line 615, in psi
    return sfd.get(res)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py\", line 156, in get
    return fed.get(object_refs)
  File \"/usr/local/lib/python3.10/site-packages/fed/api.py\", line 621, in get
    values = ray.get(ray_refs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/worker.py\", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): \x1b[36mray::SPURuntime.psi()\x1b[39m (pid=603, ip=mcmk-lhvmekhd-node-35-0-global.alice.svc, actor_id=69b2edcc8c4408d316e163bc01000000, repr=SPURuntime(device_id=None, party=alice))
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py\", line 1379, in psi
    report = spu.psi.psi(config, self.link)
  File \"/usr/local/lib/python3.10/site-packages/spu/psi.py\", line 118, in psi
    report_str = libpsi.libs.psi(
RuntimeError: what: 
\t[Enforce fail at external/psi/psi/cryptor/cryptor_selector.cc:92] cryptor != nullptr. FourQ requires AVX2 instruction
Stacktrace:
#0 psi::ecdh::EcdhPsiReceiver::PreProcess()+0x7f5a4eee7f34
#1 psi::RunPsi()+0x7f5a4eedaab0
#2 psi::BindLibs()::{lambda()#3}::operator()()+0x7f5a4eed0205
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697

stacktrace: 
#0 psi::ecdh::EcdhPsiReceiver::PreProcess()+0x7f5a4eee7f34
#1 psi::RunPsi()+0x7f5a4eedaab0
#2 psi::BindLibs()::{lambda()#3}::operator()()+0x7f5a4eed0205
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5a4eed0483
#4 pybind11::cpp_function::dispatcher()+0x7f5a4eeb243d
#5 cfunction_call+0x4fc697
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [info] [launch.cc:119] PSI config: {\"protocol_config\":{\"protocol\":\"PROTOCOL_ECDH\",\"role\":\"ROLE_RECEIVER\",\"broadcast_result\":true,\"ecdh_config\":{\"curve\":\"CURVE_FOURQ\"}},\"input_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/learn_1_2074372473.csv\"},\"output_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/mcmk-lhvmekhd-node-35-output-0\"},\"keys\":[\"id\"],\"advanced_join_type\":\"ADVANCED_JOIN_TYPE_LEFT_JOIN\",\"left_side\":\"ROLE_RECEIVER\"}
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [info] [receiver.cc:41] [EcdhPsiReceiver::Init] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [info] [interface.cc:78] [AbstractPsiParty::Init] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.992] [warning] [interface.cc:299] The check of duplicated items will be skiped while advanced join is enabled. 
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.996] [info] [interface.cc:91] [AbstractPsiParty::Init][Advanced join pre-process] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:57.998] [info] [key.cc:91] Executing sort scripts: tail -n +2 /home/kuscia/var/storage/data/learn_1_2074372473.csv | LC_ALL=C sort  --parallel=8 --buffer-size=1G --stable --field-separator=, --key=1,1  >>/tmp/receiver_fb7dbac8-7119-4993-8a60-14b40cb51faf_advanced_join_sorted_input.csv
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.028] [info] [key.cc:93] Finished sort scripts: tail -n +2 /home/kuscia/var/storage/data/learn_1_2074372473.csv | LC_ALL=C sort  --parallel=8 --buffer-size=1G --stable --field-separator=, --key=1,1  >>/tmp/receiver_fb7dbac8-7119-4993-8a60-14b40cb51faf_advanced_join_sorted_input.csv, ret=0
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.044] [info] [interface.cc:113] [AbstractPsiParty::Init][Advanced join pre-process] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.049] [info] [interface.cc:183] [AbstractPsiParty::Init] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.049] [info] [receiver.cc:49] [EcdhPsiReceiver::Init] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=603)\x1b[0m [2024-08-05 15:59:58.049] [info] [receiver.cc:54] [EcdhPsiReceiver::PreProcess] start
"

**Comment by lanyy9527** [comment]
您好，方便提供下您的CPU型号吗？
通过日志观察到您的CPU不支持 AVX2 指令集，FourQ 需要 AVX2 指令集，建议您更换 curve_type 后再次尝试；

**Comment by dyx0001** [comment]
我这里CPU型号是：Intel(R) Xeon(R) CPU E5-2603 v2 @1.8GHz , 我这台服务器之前部署过EasyPSI倒是可以使用求交。

**Comment by lanyy9527** [comment]
感谢您的反馈！您这边方便提供下EasyPSI和Pad分别运行的参数配置吗？

**Comment by dyx0001** [comment]
刚才运行ECDH协议除了FOURQ的其它曲线，倒是可以正常求交，而KKRT与RR22协议无法进行求交。EasyPSI与Pad就是官方界面的参数分别尝试了。那个CPU型号要支持AVX2指令集需要哪种型号有范围么？

**Comment by lanyy9527** [comment]
1. KKRT与RR22协议无法进行求交：检查下是否有重复数据，可以开启重复值检查选项重新试下；
2. 目前还没有，可能需要您查阅 Intel 处理器的规格表和官方文档：https://ark.intel.com/ ；

**Comment by dyx0001** [comment]
关于Pad有时服务器断电重启或者正常重启之后，合作节点一直无法建立连接，也无法重新添加连接不上的节点，是什么情况，以及该如何解决？

**Comment by lanyy9527** [comment]
1. 在两边的容器中看下授权状态是否正常：kubectl get cdr；
2. 检查双方端口的通信是否正常：curl -kvvv https://1.1.1.1:18080/；
