### ISSUE TITLE
在同一个机器中，启动两个节点，互相不能通讯

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretflow#1408]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretpad:0.9.0b0 

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.11.7

### What happend and What you expected to happen.

```shell
1.下载官网上的在secretpad
2.在机器上分别部署
sh install.sh autonomy -n alice -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls
sh install.sh autonomy -n bob-s 8090 -g 40813 -k 40812 -p 10090 -q 13091 -P mtls

3.互相添加为合作节点，通讯状态为不可用
```

### Reproduction code to reproduce the issue.

```shell
未进行代码编写
```

**Comment by wangzul** [comment]
按照以下步骤执行：
1. 删除创建的合作节点
2. 配置节点信息中的ip端口信息
Tips：节点通讯地址协议是根据平台安装时「-P 参数（默认为TLS）」自动生成，NOTLS对应http，TLS和MTLS对应https。
![image](https://github.com/user-attachments/assets/ec9588fa-5c80-4b8c-9fa1-ce0b475415d3)
3.复制A方节点认证吗去B方配置合作节点注意协议
4.复制B方节点认证吗去A方配置合作节点注意协议
