### ISSUE TITLE
使用样例数据进行隐私求交，报错提示：解密失败

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretflow#1409]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretpad:0.9.0b0 

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.11.7

### What happend and What you expected to happen.

```shell
使用pad all in one 进行部署alice bob两个节点，使用notl协议
下载页面指导的样例数据进行隐私求交，在求交组件发生报错，提示Bob节点解密失败
```

### Reproduction code to reproduce the issue.

```shell
无代码
```

**Comment by zimu-yuxi** [comment]
是否有重装节点吗？
这个报错一般是 节点重装后节点的私钥变了，导致无法解密之前的数据了。 节点重装如果希望保留原有数据，需要保留节点的私钥 （kuscia.yaml 中的 domainkey字段 即为私钥）

**Comment by EightMonth** [comment]
都是重装后，重新导入的数据

**Comment by EightMonth** [comment]
我的重装是执行uninstall.sh，然后删除文件夹，重新解压部署，再重新引入的数据，最后再配置训练流发生的报错

**Comment by pchyuan** [comment]
> 我的重装是执行uninstall.sh，然后删除文件夹，重新解压部署，再重新引入的数据，最后再配置训练流发生的报错

问题你解决了吗？
