### ISSUE TITLE
init spu protocal

### ISSUE THREAD

**Issue by YIYEYIYE** [secretflow/secretflow#141]
### Issue Type

Documentation Feature Request

### Source

source

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

centos7

### Python version

3.8.12

### What happend and What you expected to happen.

```shell
1.初始化spu时，选择cheetah协议，这个协议是基于OT、SS还是什么？从网上找了很多没有找到，还有就是从哪儿能找到这些协议(cheetah、aby3等)的相关资料？
2.用spu计算时，密文的计算是同态的吗？如果不是同态的，那又是怎么计算并最后多方综合的？
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by 6fj** [comment]
Hi @YIYEYIYE ,

1. 请查阅我们的文档：https://spu.readthedocs.io/en/beta/reference/mpc_status.html
2. spu的计算是基于mpc协议（即你前面提到的aby3等协议）。请参阅相关论文和资料了解mpc是如何计算的，以及不同协议的secret sharing schema和明密文转化流程。
3. 另外，如果你想进行同态计算，请使用secretflow的另一个子项目-heu：https://secretflow.readthedocs.io/zh_CN/latest/developer/design/heu.html。

**Comment by usafchn** [comment]
hi，补充一下，
1. cheetah协议是阿里巴巴双子座实验室原创的协议，详见 paper https://eprint.iacr.org/2022/207
2. spu 是个虚拟设备，相当于一个 spu 是有多个独立的半诚实参与方组成（一般为2到3个），各参与方之间执行秘密分享算法执行计算。spu 主要基于秘密分享算法，而不是同态。
