### ISSUE TITLE
SFxgboost报错

### ISSUE THREAD

**Issue by eternalovee** [secretflow/secretflow#1417]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.6

### OS Platform and Distribution

ubuntu 22.04

### Python version

3

### What happend and What you expected to happen.

```shell
bst.train(hdf, hdf, params=params, num_boost_round=4)语句执行报错
params = {
    # XGBoost parameter tutorial
    # https://xgboost.readthedocs.io/en/latest/parameter.html
    'max_depth': 4,  # max depth
    'eta': 0.3,  # learning rate
    'objective': 'multi:softmax',  # objection function，support "binary:logistic","reg:logistic","multi:softmax","multi:softprob","reg:squarederror"
    'min_child_weight': 1,  # The minimum value of weight
    'lambda': 0.1,  # L2 regularization term on weights (xgb's lambda)
    'alpha': 0,  # L1 regularization term on weights (xgb's alpha)
    'max_bin': 10,  # Max num of binning
    'num_class': 6,  # Only required in multi-class classification
    'gamma': 0,  # Same to min_impurity_split,The minimux gain for a split
    'subsample': 1.0,  # Subsample rate by rows
    'colsample_bytree': 1.0,  # Feature selection rate by tree
    'colsample_bylevel': 1.0,  # Feature selection rate by level
    'eval_metric': 'merror',  # supported eval metric：
    # 1. rmse
    # 2. rmsle
    # 3. mape
    # 4. logloss
    # 5. error
    # 6. error@t
    # 7. merror
    # 8. mlogloss
    # 9. auc
    # 10. aucpr
    # Special params in SFXgboost
    # Required
    'hess_key': 'hess',  # Required, Mark hess columns, optionally choosing a column name that is not in the data set
    'grad_key': 'grad',  # Required，Mark grad columns, optionally choosing a column name that is not in the data set
    'label_key': 'Class',  # Required，ark label columns, optionally choosing a column name that is not in the data set
}
```

### Reproduction code to reproduce the issue.

```shell
RayTaskError(ValueError): [36mray::HomoBooster.homo_train()[39m (pid=2539, ip=172.18.0.3, actor_id=2f05104083dfc29d9dd29d8601000000, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7bdb7f222680>)
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/proxy.py", line 76, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 146, in homo_train
    self.bst = train(
  File "/usr/local/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 208, in train
    bst = _train_internal(
  File "/usr/local/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 136, in _train_internal
    bst.federate_update(params, dtrain, hdata, global_bin, iter_round=i, fobj=obj)
  File "/usr/local/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/core.py", line 117, in federate_update
    grad, hess = fobj(pred, dtrain)
  File "/usr/local/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/tree_core/loss_function.py", line 114, in _softmaxobj
    grad = (prob - labels).astype(np.float64)
ValueError: operands could not be broadcast together with shapes (10000,6) (10000,2)
```

**Comment by BrainWH** [comment]
你好，根据你的报错信息，问题是出在对数据的预处理上，可以描述下对hdf的处理过程吗？

**Comment by eternalovee** [comment]
> 你好，根据你的报错信息，问题是出在对数据的预处理上，可以描述下对hdf的处理过程吗？

老师你好，上一个问题已经解决，我还想提问在按照https://secretflow.readthedocs.io/zh-cn/stable/tutorial/Federated_Xgboost.html教程所使用代码运行时，
在执行完bst.train(data, data, params=params, num_boost_round=6)后
INFO:root:Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party bob.
INFO:root:start recursive
到recursive后就没有更多显示了，代码完全使用教程内的，请问这是什么问题

**Comment by BrainWH** [comment]
是否改参数了？完整的日志只有三行吗？

**Comment by eternalovee** [comment]
> 你好，确认一下是否改参数了？可以贴出来完整的日志
好的老师，我展示全部的过程
%load_ext autoreload
%autoreload 2

import secretflow as sf

# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob', 'charlie'], address='local')
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')

The version of SecretFlow: 1.5.0b0

/usr/local/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
2024-08-14 13:16:15,334	WARNING services.py:1996 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=2.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2024-08-14 13:16:16,699	INFO worker.py:1724 -- Started a local Ray instance.

from secretflow.data.horizontal import read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator
from secretflow.utils.simulation.datasets import load_dermatology

aggr = SecureAggregator(charlie, [alice, bob])
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
comp = SPUComparator(spu)
data = load_dermatology(parts=[alice, bob], aggregator=aggr, comparator=comp)
data.fillna(value=0, inplace=True)
data

INFO:root:Create proxy actor <class 'secretflow.security.aggregation.secure_aggregator._Masker'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.security.aggregation.secure_aggregator._Masker'> with party bob.
INFO:root:Create proxy actor <class 'secretflow.data.core.agent.PartitionAgent'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.data.core.agent.PartitionAgent'> with party bob.

HDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7d5f091f84f0>, PYURuntime(bob): <secretflow.data.core.partition.Partition object at 0x7d5f075cbf40>}, aggregator=<secretflow.security.aggregation.secure_aggregator.SecureAggregator object at 0x7d5f07b69840>, comparator=SPUComparator(device=<secretflow.device.device.spu.SPU object at 0x7d5f07b69cc0>))


params = {
    # XGBoost parameter tutorial
    # https://xgboost.readthedocs.io/en/latest/parameter.html
    'max_depth': 4,  # max depth
    'eta': 0.3,  # learning rate
    'objective': 'multi:softmax',  # objection function，support "binary:logistic","reg:logistic","multi:softmax","multi:softprob","reg:squarederror"
    'min_child_weight': 1,  # The minimum value of weight
    'lambda': 0.1,  # L2 regularization term on weights (xgb's lambda)
    'alpha': 0,  # L1 regularization term on weights (xgb's alpha)
    'max_bin': 10,  # Max num of binning
    'num_class': 6,  # Only required in multi-class classification
    'gamma': 0,  # Same to min_impurity_split,The minimux gain for a split
    'subsample': 1.0,  # Subsample rate by rows
    'colsample_bytree': 1.0,  # Feature selection rate by tree
    'colsample_bylevel': 1.0,  # Feature selection rate by level
    'eval_metric': 'merror',  # supported eval metric：
    # 1. rmse
    # 2. rmsle
    # 3. mape
    # 4. logloss
    # 5. error
    # 6. error@t
    # 7. merror
    # 8. mlogloss
    # 9. auc
    # 10. aucpr
    # Special params in SFXgboost
    # Required
    'hess_key': 'hess',  # Required, Mark hess columns, optionally choosing a column name that is not in the data set
    'grad_key': 'grad',  # Required，Mark grad columns, optionally choosing a column name that is not in the data set
    'label_key': 'class',  # Required，ark label columns, optionally choosing a column name that is not in the data set
}

from secretflow.ml.boost.homo_boost import SFXgboost

bst = SFXgboost(server=charlie, clients=[alice, bob])

INFO:root:Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party bob.
INFO:root:Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party charlie.

bst.train(data, data, params=params, num_boost_round=6)

INFO:root:Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party bob.
INFO:root:start recursive


上面是完整的在secretnote的执行情况。于此同时，使用相同的参数xgb可以正常训练

**Comment by BrainWH** [comment]
你好，你的代码没有问题，sf1.5的版本也可以跑
检查一下：1、CPU/Memory: 推荐最低配置是 8C16G
                  2、如果配置符合要求，清理一下内存，然后再执行

**Comment by eternalovee** [comment]
> 你好，你的代码没有问题，sf1.5的版本也可以跑 检查一下：1、CPU/Memory: 推荐最低配置是 8C16G 2、如果配置符合要求，清理一下内存，然后再执行

您好，配置符合要求，清理内存后还是未能解决。我的问题描述可能不清晰，最后一步能正常执行并且没有报错，但是不显示结果，只能看到recursive为止，但是params里面有eval_metric参数，请问现象正常吗，如果不正常有排查办法吗

**Comment by BrainWH** [comment]
你好，你可以这么做
1、你可以写成python文件去跑一下
2、如果python文件可以正常看到最后的输出结果，那就要检查你的secretnote环境

**Comment by eternalovee** [comment]
> 你好，你可以这么做 1、你可以写成python文件去跑一下 2、如果python文件可以正常看到最后的输出结果，那就要检查你的secretnote环境
谢谢，我去尝试一下
