### ISSUE TITLE
拆分学习 NN 模型训练，slnn_train组件的运行

### ISSUE THREAD

**Issue by T-ze-yu** [secretflow/secretflow#1418]
### Issue Type

Bug

### Source

binary

### Secretflow Version

Secretflow 1.7.0b0 

### OS Platform and Distribution

Ubuntu 20.04.6 LTS

### Python version

python3.10

### What happend and What you expected to happen.

```shell
希望使用kuscai api能够正常运行这个组件，由于需要将ENABLE_NN 环境变量设置成 true，通过相关指导在dockerfile加入ENV ENABLE_NN=true重新打包了sf完整版的镜像，再使用该镜像，还是遇到错误：secretflow.component.component.CompEvalError: slnn component is not enabled, please make sure tensorflow is installed and set env ENABLE_NN=true.
通过调试相关报错代码，tensorflow可以正确导入，确定还是环境变量ENABLE_NN没有设置正确
```

### Reproduction code to reproduce the issue.

```shell
FROM openanolis/anolisos:8.8 as builder

# 设置环境变量
ENV ENABLE_NN=true

RUN yum install -y \
    wget gcc gcc-c++ autoconf bison flex git protobuf-devel libnl3-devel \
    libtool make pkg-config protobuf-compiler \
    && yum clean all

RUN cd / && git clone https://github.com/google/nsjail.git \
    && cd /nsjail && git checkout 3.3 -b v3.3 \
    && make && mv /nsjail/nsjail /bin

FROM secretflow/anolis8-python:3.10.13 as python

FROM openanolis/anolisos:8.8

LABEL maintainer="secretflow-contact@service.alipay.com"

COPY --from=builder /bin/nsjail /usr/local/bin/
COPY --from=python /root/miniconda3/envs/secretflow/bin/ /usr/local/bin/
COPY --from=python /root/miniconda3/envs/secretflow/lib/ /usr/local/lib/

RUN yum install -y protobuf libnl3 libgomp && yum clean all

RUN grep -rl '#!/root/miniconda3/envs/secretflow/bin' /usr/local/bin/ | xargs sed -i -e 's/#!\/root\/miniconda3\/envs\/secretflow/#!\/usr\/local/g'

COPY *.whl /tmp/

RUN pip install -i https://mirrors.aliyun.com/pypi/simple/  kuscia
RUN pip install -i https://mirrors.aliyun.com/pypi/simple/   /tmp/*.whl && rm -rf /root/.cache

COPY .nsjail /root/.nsjail

ARG config_templates=""
LABEL kuscia.secretflow.config-templates=$config_templates

ARG deploy_templates=""
LABEL kuscia.secretflow.deploy-templates=$deploy_templates

ARG comp_list=""
LABEL kuscia.secretflow.comp_list=$comp_list

ARG translation=""
LABEL kuscia.secretflow.translation=$translation

# run as root for now
WORKDIR /root

CMD ["/bin/bash"]

```

**Comment by T-ze-yu** [comment]
这是完整的日志文件：
[Uploading rz.txt…]()

**Comment by BrainWH** [comment]
你好，可以重新发下日志文件，这个文件没有上传成功

**Comment by T-ze-yu** [comment]
好的
[rz.txt](https://github.com/user-attachments/files/16607097/rz.txt)

**Comment by lanyy9527** [comment]
试下在系统中设置 export ENABLE_NN=true

**Comment by T-ze-yu** [comment]
> 试下在系统中设置 export ENABLE_NN=true

还是一样的，代码中ENABLE_NN还是false：
![image](https://github.com/user-attachments/assets/68d3addc-f6a4-4a29-b88b-ae5c97b106a3)

**Comment by T-ze-yu** [comment]
这是完整日志：
[rz2.txt](https://github.com/user-attachments/files/16657684/rz2.txt)

**Comment by T-ze-yu** [comment]
接下来我修改了下面两处代码，跳过了报错和确保默认值的使用：
![image](https://github.com/user-attachments/assets/d910a621-e487-4bb0-94c7-37be3fb435d0)
![image](https://github.com/user-attachments/assets/6fc3df45-1d1d-4c6c-8bed-6612411d529a)
尽管此时代码好像进入了训练阶段，但还是遇到了报错，具体日志如下
[rz3.txt](https://github.com/user-attachments/files/16657895/rz3.txt)

**Comment by lanyy9527** [comment]
检查下 TensorFlow 的版本和 echo $ENABLE_NN

**Comment by T-ze-yu** [comment]
日志有打印TensorFlow 的版本
![image](https://github.com/user-attachments/assets/0f6de100-7c4a-423d-b724-64bfb4bab6ec)
![image](https://github.com/user-attachments/assets/8a08bf9d-7815-4541-bcc3-f37f45fa79b5)

**Comment by lanyy9527** [comment]
收到您的反馈，我们会在一定的时间内进行测试，并尽快跟进这个问题。感谢您的耐心等待。

**Comment by T-ze-yu** [comment]
> 收到您的反馈，我们会在一定的时间内进行测试，并尽快跟进这个问题。感谢您的耐心等待。

好的，感谢！
