### ISSUE TITLE
执行相关系数矩阵问题

### ISSUE THREAD

**Issue by gaodongdong-software** [secretflow/secretflow#1419]
通过secretPad平台执行相关系数矩阵的时候,会报以下错误
![image](https://github.com/user-attachments/assets/41491d5e-bf2b-426b-bce0-0f7e1dc08430)
![image](https://github.com/user-attachments/assets/52034984-0624-4da4-a0af-ed02ec13f118)

不通过secretPadweb平台,单独进行docker部署中心化集群环境中运行相关系数矩阵组件,则能够正常运行

**Comment by BrainWH** [comment]
你好，可以把完整的报错信息贴出来，这两次执行的数据是一样的吗？
