### ISSUE TITLE
二分类评估组件的输入参数问题

### ISSUE THREAD

**Issue by killomsc** [secretflow/secretflow#1427]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.7

### OS Platform and Distribution

ubuntu 22

### Python version

3.10

### What happend and What you expected to happen.

```shell
二分类评估组件的输入参数：

  "inputs": [
        {
          "name": "in_ds",
          "desc": "Input table with prediction and label, usually is a result from a prediction component.",
          "types": [
            "sf.table.vertical_table",
            "sf.table.individual"
          ],
          "attrs": [
            {
              "name": "label",
              "desc": "The label name to use in the dataset.",
              "colMinCntInclusive": "1",
              "colMaxCntInclusive": "1"
            },
            {
              "name": "prediction",
              "desc": "The prediction result column name to use in the dataset.",
              "colMinCntInclusive": "1",
              "colMaxCntInclusive": "1"
            }
          ]
        }
      ]
```

### Reproduction code to reproduce the issue.

```shell
组件的输入有两种类型，"sf.table.vertical_table", "sf.table.individual"。一般情况下，都是接入预测的结果，对应的类型是sf.table.individual。那另外一个联合表的sf.table.vertical_table的类型，是什么情况下会使用？
```

**Comment by killomsc** [comment]
我尝试选择了一份联合表的数据，但是运行的时候会报错。
AttributeError: unknown cols {'y', 'contact_cellular'} in col_selects
所以想问下具体是怎么使用？

**Comment by zimu-yuxi** [comment]
1.可以参考下隐语[开放标准](https://www.secretflow.org.cn/zh-CN/docs/spec/v1.0.dev240328/spec#data)，有对这两种类型的简单介绍
2.如组件描述所讲，‘带有预测和标签的输入表，通常是预测组件的结果’

**Comment by killomsc** [comment]
采用预测组件的结果是可以成功运行的，这个对应的输入类型是sf.table.individual。
而还有另外一种可输入的类型sf.table.vertical_table，这个类型是联合表，具体是什么场景会采用？
说具体点，就是除了预测的组件的结果，还有哪个组件的结果能作为二分类评估组件的输入。

**Comment by zimu-yuxi** [comment]
> 我尝试选择了一份联合表的数据，但是运行的时候会报错。 AttributeError: unknown cols {'y', 'contact_cellular'} in col_selects 所以想问下具体是怎么使用？

这里你使用的是哪个组件的输出？

**Comment by killomsc** [comment]
我这里就随意选了一个求交的结果，因为pad上也没限制，只要数据集都可以连上去。我的理解是不是只要这份数据集，有标签y和一个预测的分数就可以执行评估组件。
没有什么场景，只是看了下组件的输入参数支持两种输入的数据集类型，有疑问而已。
