### ISSUE TITLE
若模型有多层，如何选择某层参数聚合，其余层不聚合

### ISSUE THREAD

**Issue by luolin101** [secretflow/secretflow#1428]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 1.8

### OS Platform and Distribution

windows

### Python version

3.9

### What happend and What you expected to happen.

```shell
使用pytorch构建联邦模型，模型有多层，只希望某层的参数进行聚合，而有些层保持私有，不进行聚合，例如fc1似有不聚合，fc2进行聚合，如何实现
```

### Reproduction code to reproduce the issue.

```shell
# 定义模型
class SimpleModel(BaseModule):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 128)  # 这个层的参数不聚合
        self.fc2 = nn.Linear(128, 10)       # 这个层的参数会聚合

    def forward(self, x):
        x = x.view(-1, 28 * 28)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

# 定义损失函数、优化器和指标
loss_fn = nn.CrossEntropyLoss
optim_fn = optim_wrapper(optim.Adam, lr=1e-2)
metrics = [
    metric_wrapper(Accuracy, task="multiclass", num_classes=10, average='micro'),
    metric_wrapper(Precision, task="multiclass", num_classes=10, average='micro')
]

# 定义模型
model_def = TorchModel(
    model_fn=SimpleModel,
    loss_fn=loss_fn,
    optim_fn=optim_fn,
    metrics=metrics,
    aggregate_freq=1 
)

# 初始化 SecureAggregator
aggregator = SecureAggregator(parties=['alice', 'bob'])

# 初始化联邦学习模型
fl_model = FLModel(
    server=server,
    device_list=[alice, bob],
    model=model_def,
    aggregator=aggregator,
    strategy='fed_avg_w',  
    backend="torch"
)
```

**Comment by lanyy9527** [comment]
1. 可以通过 aggregate 将模型的参数标记为True/False是否需要聚合；
2. 通过 SecureAggregator 自定义参数聚合

**Comment by luolin101** [comment]
> 1. 可以通过 aggregate 将模型的参数标记为True/False是否需要聚合；
> 2. 通过 SecureAggregator 自定义参数聚合

你好，请问可以给一个代码案例吗，官方文档里面没有看到这部分内容，例如fc1不聚合，fc2进行聚合

**Comment by lanyy9527** [comment]
> 
> 你好，请问可以给一个代码案例吗，官方文档里面没有看到这部分内容，例如fc1不聚合，fc2进行聚合

您好，可以参考：https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/backend/tensorflow/strategy/fed_avg_g.py 像这样实现一个 strategy；
需要继承 [fl_base](https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/backend/tensorflow/fl_base.py#L236) 然后修改 get_weights 和 set_weights

**Comment by lanyy9527** [comment]
您好，咱这边有什么具体的场景吗？

**Comment by luolin101** [comment]
> 您好，咱这边有什么具体的场景吗？
嗯嗯，我先研究一下进行聚合的策略的代码，目前的场景是用于联邦推荐系统，涉及到推荐的个性化，对于其中一些层，打算采用不聚合的方式保证完全个性化

**Comment by luolin101** [comment]
> 您好，咱这边有什么具体的场景吗？

嗯嗯，我先研究一下进行聚合的策略的代码，目前的场景是用于联邦推荐系统，涉及到推荐的个性化，对于其中一些层，打算采用不聚合的方式保证完全个性化
