### ISSUE TITLE
secretpad all in one的引擎日志如何接入

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretflow#1429]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretpad:0.9.0b0 

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.11.7

### What happend and What you expected to happen.

```shell
最新版本使用中心化模式安装的secretpad all in one如何使用阿里云sls接入引擎日志
```

### Reproduction code to reproduce the issue.

```shell
无代码
```

**Comment by zimu-yuxi** [comment]
参考官网文档[阿里云sls配置](secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/development/support_sls_cloud_log)

**Comment by EightMonth** [comment]
以中心化形式部署secretpad all in one后，我使用docker exec -it root-kuscia-master bash进入容器，按照上述文档配置进行部署logtail时，始终无法成功，pod的状态始终为pending，而且describe pod时，发现events 为 <none>

**Comment by EightMonth** [comment]
secretpad all in one 接入 sls是否还有其它注意事项
