### ISSUE TITLE
SPU pip无法安装

### ISSUE THREAD

**Issue by oahcnauygnid** [secretflow/secretflow#143]
pip install spu报错
ERROR: Could not find a version that satisfies the requirement spu (from versions: none)
ERROR: No matching distribution found for spu
直接pip install -U secretflow也是这个错误

**Comment by zhouaihui** [comment]
你好  @oahcnauygnid ，麻烦按照我们的issue模板，补充相关信息。

**Comment by oahcnauygnid** [comment]
现在可以pip安装了，谢谢！
