### ISSUE TITLE
关于隐私求交的疑问

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1434]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow-1.8.0

### OS Platform and Distribution

centos7.9

### Python version

3.10

### Bazel version

6.5

### What happend and What you expected to happen.

```shell
我通过SecretPad All In One部署应用后，进行隐私求交时有几个选项：inner_join/left_join/full_join/difference，请问各位老师：
问题1：这几个选项代表什么含义？
问题2：这几个选项分别适用于哪些场景？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by wangzul** [comment]
你可以参考这个文档https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.0beta/reference/psi_v2_config#psiconfig

**Comment by coderSun20201112** [comment]
> 你可以参考这个文档https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.0beta/reference/psi_v2_config#psiconfig

我按照链接，找到了配置说明，但Description一栏为none，我主要的是想知道这几个选项，从业务层面的解释是什么，即每一种配置代表什么含义，分别适合哪些不同场景。

**Comment by wangzul** [comment]
> > 你可以参考这个文档https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.0beta/reference/psi_v2_config#psiconfig
> 
> 我按照链接，找到了配置说明，但Description一栏为none，我主要的是想知道这几个选项，从业务层面的解释是什么，即每一种配置代表什么含义，分别适合哪些不同场景。

inner_join = 获取交集
left_join = 获取交集+left方的非交集
full_join = 获取所有数据
difference = 只保留非交集

**Comment by wangzul** [comment]
> 本

疑问1 ： 针对left_join，假设alice 与 bob进行PSI，然后采用left_join，left节点是alice，那对于bob方，除了获取交集之外，还能获取alice节点的非交集数据？
bob方，只能获取自己的交集

疑问2：full_join获取所有数据，指的是获取本节点的所有数据，还是本节点 + 对方节点的所有数据？
结果是本节点 + 对方节点(以填充的方式获取，只知道有几行但是不知道真实数据是什么)

疑问3：按照ECDH算法描述，PSI结果应该只落在一方，但SecretPad All In One中求交结果是双方可见，这里面，是不是ECDH分别求交2次，一次在alice节点求交，一次在bob节点求交？
是的双方都会进行一次交集计算

**Comment by coderSun20201112** [comment]
> 结果是本节点 + 对方节点(以填充的方式获取，只知道有几行但是不知道真实数据是什么)

老师，你看我理解的对不对：
①alice inner_join bob：alice节点仅仅获取本节点的交集记录；bob节点仅仅获取本节点的交集记录。
②alice left_join bob：alice节点仅仅获取本节点的交集记录；bob节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。
③alice full_join bob：alice节点不仅获取本节点的交集记录，还能获取bob节点所有记录的数量；同理bob节点不仅获取本节点交集记录，还能获取alice节点所有记录数量。
④alice difference bob：alice节点获取本节点非交集记录；bob节点获取本节点非交集记录；

**Comment by wangzul** [comment]
> > 结果是本节点 + 对方节点(以填充的方式获取，只知道有几行但是不知道真实数据是什么)
> 
> 老师，你看我理解的对不对： ①alice inner_join bob：alice节点仅仅获取本节点的交集记录；bob节点仅仅获取本节点的交集记录。 ②alice left_join bob：alice节点仅仅获取本节点的交集记录；bob节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。 ③alice full_join bob：alice节点不仅获取本节点的交集记录，还能获取bob节点所有记录的数量；同理bob节点不仅获取本节点交集记录，还能获取alice节点所有记录数量。 ④alice difference bob：alice节点获取本节点非交集记录；bob节点获取本节点非交集记录；


②alice left_join bob：bob节点仅仅获取本节点的交集记录；alice节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。

④alice difference bob：alice节点不仅仅获取本节点的非交集记录，还能获取bob节点非交集记录的数量；bob节点不仅仅获取本节点的非交集记录，还能获取alice节点非交集记录的数量。

**Comment by coderSun20201112** [comment]
> > > 结果是本节点 + 对方节点(以填充的方式获取，只知道有几行但是不知道真实数据是什么)
> > 
> > 
> > 老师，你看我理解的对不对： ①alice inner_join bob：alice节点仅仅获取本节点的交集记录；bob节点仅仅获取本节点的交集记录。 ②alice left_join bob：alice节点仅仅获取本节点的交集记录；bob节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。 ③alice full_join bob：alice节点不仅获取本节点的交集记录，还能获取bob节点所有记录的数量；同理bob节点不仅获取本节点交集记录，还能获取alice节点所有记录数量。 ④alice difference bob：alice节点获取本节点非交集记录；bob节点获取本节点非交集记录；
> 
> ②alice left_join bob：bob节点仅仅获取本节点的交集记录；alice节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。
> 
> ④alice difference bob：alice节点不仅仅获取本节点的非交集记录，还能获取bob节点非交集记录的数量；bob节点不仅仅获取本节点的非交集记录，还能获取alice节点非交集记录的数量。

感谢老师讲解，最后一个问题：获取对方记录数量，这个功能做什么用的，是为什么功能而服务的？

**Comment by wangzul** [comment]
> > > > 结果是本节点 + 对方节点(以填充的方式获取，只知道有几行但是不知道真实数据是什么)
> > > 
> > > 
> > > 老师，你看我理解的对不对： ①alice inner_join bob：alice节点仅仅获取本节点的交集记录；bob节点仅仅获取本节点的交集记录。 ②alice left_join bob：alice节点仅仅获取本节点的交集记录；bob节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。 ③alice full_join bob：alice节点不仅获取本节点的交集记录，还能获取bob节点所有记录的数量；同理bob节点不仅获取本节点交集记录，还能获取alice节点所有记录数量。 ④alice difference bob：alice节点获取本节点非交集记录；bob节点获取本节点非交集记录；
> > 
> > 
> > ②alice left_join bob：bob节点仅仅获取本节点的交集记录；alice节点不仅仅获取本节点的交集记录，还能获取alice节点非交集记录的数量。
> > ④alice difference bob：alice节点不仅仅获取本节点的非交集记录，还能获取bob节点非交集记录的数量；bob节点不仅仅获取本节点的非交集记录，还能获取alice节点非交集记录的数量。
> 
> 感谢老师讲解，最后一个问题：获取对方记录数量，这个功能做什么用的，是为什么功能而服务的？

对缺失值进行填充，主要是为了数据对齐，保证数据的完成性和准确性

**Comment by coderSun20201112** [comment]
感谢老师热心解答，谢谢
