### ISSUE TITLE
09:21目的：将Secretflow通过读取CSV文件获取数据，修改为 传入的CSV文件中包含了数据库的连接串信息，底层通过连接串信息去查询MYSQL，然后返回DF

### ISSUE THREAD

**Issue by beng003** [secretflow/secretflow#1436]
### Discussed in https://github.com/orgs/secretflow/discussions/1315

<div type='discussions-op-text'>

<sup>Originally posted by **secretflowcode** June  4, 2024</sup>
思路：修改secretflow/data/core/io.py，通过修改_read_csv方法，分析CSV文件得到连接串，然后请求MYSQL获取数据
实现代码：
secretflow/data/core/io.py修改如下
    def _read_csv(_filepath, _backend, *_args, **_kwargs):
        import select_sql
        df = pd.read_csv(_filepath)
        url = df.iloc[0, 0]
        port = df.iloc[0, 1]
        username = df.iloc[0, 2]
        password = df.iloc[0, 3]
        database = df.iloc[0, 4]
        table = df.iloc[0, 5]
        columns = list(df.columns)
        return select_sql.fetch_data_from_mysql(url, port, username, password, database, table, columns)
		
		# 以下模块不执行
        if _backend == "pandas":
            from secretflow.data.core.pandas.util import read_pandas_csv

            return read_pandas_csv(_filepath, *_args, **_kwargs)

        elif _backend == "polars":
            from secretflow.data.core.polars.util import read_polars_csv

            return read_polars_csv(_filepath, *_args, **_kwargs)
        else:
            raise RuntimeError(f"Unknown data backend {_backend}")
			
			
select_sql.py实现如下
import pymysql
import pandas as pd
def fetch_data_from_mysql(url, port, username, password, database, table, columns):
    connection = pymysql.connect(
        host=url,
        port=int(port),
        user=username,
        password=password,
        database=database,
        charset='utf8mb4'
    )</div>

您好，我们最近也在思考如何把函数
```
def read_csv(
    filepath: Dict[PYU, Union[str, Callable]],
    delimiter=",",
    usecols: Dict[PYU, List[str]] = None,
    dtypes: Dict[PYU, Dict[str, type]] = None,
    converters: Dict[PYU, Dict[str, Callable]] = None,
    spu: SPU = None,
    keys: Union[str, List[str], Dict[Device, List[str]]] = None,
    drop_keys: Union[str, List[str], Dict[Device, List[str]]] = None,
    psi_protocl=None,
    no_header: bool = False,
    backend: str = 'pandas',
    nrows: int = None,
    skip_rows_after_header: int = None,
) -> VDataFrame:
```
从csv文件读取数据转变为从数据库读取数据，我们希望在不改变原有库函数的基础上实现，我们进行了以下实验
```
import pymysql
import numpy as np
import pandas as pd


def connect_to_mysql_and_read_data(
    database_name="alice_database", table_name="alice_bank"
):
    connection = None
    try:
        connection = pymysql.connect(
            host="localhost",
            user="beng003",
            password="12341234",
            database=database_name,
        )

        with connection.cursor() as cursor:

            cursor.execute(f"SELECT * FROM {table_name};")
            rows = cursor.fetchall()
            columns = [desc[0] for desc in cursor.description]

        return pd.DataFrame(rows, columns=columns)

    except pymysql.MySQLError as e:
        print("错误：", e)
    finally:
        if connection:
            connection.close()


def add(a, b):
    return a + b


if __name__ == "__main__":

    import secretflow as sf

    # Check the version of your SecretFlow
    print("The version of SecretFlow: {}".format(sf.__version__))

    # In case you have a running secretflow runtime already.
    sf.shutdown()

    sf.init(["alice", "bob"], address="local")
    spu_config = sf.utils.testing.cluster_def(parties=["alice", "bob"])
    spu_device = sf.SPU(spu_config)
    alice, bob = sf.PYU("alice"), sf.PYU("bob")

    v_alice = alice(connect_to_mysql_and_read_data)()
    v_bob = bob(connect_to_mysql_and_read_data)()

    print(v_alice)
    print(sf.reveal(v_alice))

    a = spu_device.psi_df(
        key="uid",
        dfs=[v_alice, v_bob],
        receiver=None,
    )
    print(a)

    sf.shutdown()
```
我们想问一下有没有办法把求交后的数据转化为VDataFrame数据？
另外从数据库读取数据进行横向合并（HDataFrame）也希望能给出一些思路

**Comment by lanyy9527** [comment]
1. 参考[API文档](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/source/secretflow.data.data.vertical#secretflow.data.vertical.dataframe.VDataFrame.__init__)
2. 参考[案例](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/user_guide/preprocessing/DataFrame#%E5%88%9B%E5%BB%BA)
