### ISSUE TITLE
Some questions about GPU acceletarion

### ISSUE THREAD

**Issue by summer-xrx** [secretflow/secretflow#1439]
Hello, I am very curious about GPU acceletarion. I have noticed that GPU acceleration has not yet been implemented in many mainstream fully homomorphic encryption libraries. Now, I have the following questions:
1. Why can't GPU acceleration be implemented in those mainstream libraries now? 
2. What are the technical challenges of using GPU to accelerate homomorphic encryption? 
3. Compared to other mainstream FHE libraries, what are the advantages of your library?
Looking forward to your reply, thank you!

**Comment by Chrisdehe** [comment]
@warriorpaw Can you help me take a look at this issue?
Thanks！

**Comment by zhouaihui** [comment]
@usafchn Could you have a look?

**Comment by anakinxc** [comment]
> * What are the technical challenges of using GPU to accelerate homomorphic encryption?

Check [this](https://developer.nvidia.com/blog/accelerated-encrypted-execution-of-general-purpose-applications/)

**Comment by usafchn** [comment]
1. I believe FHE is still in a niche area and hasn't been widely adopted in the industry. In other words, the technological development of FHE is not yet sufficient to support large-scale applications, resulting in a small number of FHE developers. Consequently, FHE libraries are still in their infancy, and the use of GPUs has not yet become prevalent.

2. As FHE continues to develop, I think that support for heterogeneous hardware acceleration is inevitable. GPUs are particularly good at floating-point calculations, while FHE requires integer calculation capabilities. From this perspective, GPUs may not be the most suitable, and other acceleration hardware might emerge in the future.

3. The goal of the HEU library in SecretFlow is to provide an easy-to-use, high-performance HE library. We want to lower the threshold for using HE and offer SOTA performance, allowing users to seamlessly switch between various algorithms.

**Comment by summer-xrx** [comment]
OK, thank you very much for your generous reply!
