### ISSUE TITLE
密文上比较大小

### ISSUE THREAD

**Issue by huyz1117** [secretflow/secretflow#144]
请问secretflow有提供在密文上比较大小的接口吗

**Comment by usafchn** [comment]
hi, @huyz1117 
SPU 支持密文比较的，用的是 boolean secret sharing 协议，用法参考[这个文档](https://secretflow.readthedocs.io/zh_CN/latest/tutorial/spu_basics.html?#%E8%BF%9B%E9%98%B6%E4%B8%BB%E9%A2%98%EF%BC%9A%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84-MPC-%E5%8D%8F%E8%AE%AE)，里面提到了用 spu 来解 Yao’s Millionaires’ problem
