### ISSUE TITLE
在secretpad中手动创建domaindata和domaindatasource跑psi任务失败

### ISSUE THREAD

**Issue by Handikang** [secretflow/secretflow#1444]
1.alice创建自己的domaindatasource
export CTR_CERTS_ROOT=/home/kuscia/var/certs
curl -k -X POST 'https://localhost:8082/api/v1/domaindatasource/create' \
 --header "Token: $(cat ${CTR_CERTS_ROOT}/token)" \
 --header 'Content-Type: application/json' \
 --cert ${CTR_CERTS_ROOT}/kusciaapi-server.crt \
 --key ${CTR_CERTS_ROOT}/kusciaapi-server.key \
 --cacert ${CTR_CERTS_ROOT}/ca.crt \
 -d '{
  "domain_id": "com2023011620060497797",
  "datasource_id":"test-alice-datasource-id",
  "type":"localfs",
  "name": "DemoDataSource",
  "info": {
      "localfs": {
          "path": "/home/kuscia/var/storage/data/alice"
      }
  },
  "access_directly": true
}'
2.bob创建自己的domaindatasource
export CTR_CERTS_ROOT=/home/kuscia/var/certs
curl -k -X POST 'https://localhost:8082/api/v1/domaindatasource/create' \
 --header "Token: $(cat ${CTR_CERTS_ROOT}/token)" \
 --header 'Content-Type: application/json' \
 --cert ${CTR_CERTS_ROOT}/kusciaapi-server.crt \
 --key ${CTR_CERTS_ROOT}/kusciaapi-server.key \
 --cacert ${CTR_CERTS_ROOT}/ca.crt \
 -d '{
  "domain_id": "com2023011620072311738",
  "datasource_id":"test-bob-datasource-id",
  "type":"localfs",
  "name": "DemoDataSource",
  "info": {
      "localfs": {
          "path": "/home/kuscia/var/storage/data/bob"
      }
  },
  "access_directly": true
}'
3.alice创建domaindata
export CTR_CERTS_ROOT=/home/kuscia/var/certs
curl -k -X POST 'https://localhost:8082/api/v1/domaindata/create' \
 --header "Token: $(cat ${CTR_CERTS_ROOT}/token)" \
 --header 'Content-Type: application/json' \
 --cert ${CTR_CERTS_ROOT}/kusciaapi-server.crt \
 --key ${CTR_CERTS_ROOT}/kusciaapi-server.key \
 --cacert ${CTR_CERTS_ROOT}/ca.crt \
 -d '{
  "domain_id": "com2023011620060497797",
  "domaindata_id": "alice-003",
  "datasource_id": "test-alice-datasource-id",
  "name": "alice003",
  "type": "table",
  "relative_uri": "piralice.csv",
  "columns": [
    {
      "name": "id",
      "type": "int32",
      "comment": ""
    }
  ]
}'
4.bob创建domaindata
export CTR_CERTS_ROOT=/home/kuscia/var/certs
curl -k -X POST 'https://localhost:8082/api/v1/domaindata/create' \
 --header "Token: $(cat ${CTR_CERTS_ROOT}/token)" \
 --header 'Content-Type: application/json' \
 --cert ${CTR_CERTS_ROOT}/kusciaapi-server.crt \
 --key ${CTR_CERTS_ROOT}/kusciaapi-server.key \
 --cacert ${CTR_CERTS_ROOT}/ca.crt \
 -d '{
  "domain_id": "com2023011620072311738",
  "domaindata_id": "bob-003",
  "datasource_id": "test-bob-datasource-id",
  "name": "bob003",
  "type": "table",
  "relative_uri": "pirbob.csv",
  "columns": [
    {
      "name": "id",
      "type": "int32",
      "comment": ""
    },
    {
      "name": "name",
      "type": "str",
      "comment": ""
    },
     {
      "name": "occup",
      "type": "str",
      "comment": ""
    }
  ]
}'
5.在secretpad上跑psi任务显示：
![image](https://github.com/user-attachments/assets/4919b32c-70b4-4595-a835-960caec06b8d)
6.secretpad版本（0.7.1b0），kuscia版本（0.8.0b0），部署模式（p2p-allinone部署）

**Comment by BrainWH** [comment]
你好，看到了你的报错信息。你可以这么做：
进入对应的secretpad容器，执行以下命令 cd db ；sqlite3 secretpad.sqlite；select  * from project_graph_domain_datasource
看下结果

**Comment by Handikang** [comment]
@BrainWH 不好意思，我进去发现没有这个表
![image](https://github.com/user-attachments/assets/88da42b3-6402-476b-ab10-9c3a2beab8c2)

**Comment by BrainWH** [comment]
你好，datasource_id应该使用默认值

**Comment by Handikang** [comment]
![image](https://github.com/user-attachments/assets/45df78e0-0b92-4415-acf1-ecc659494b15)
好的，现在我用最原始的secretflow版本1.6.1b0,跑psi跑到这里显示brpc的问题，然后psi就卡死在这里，我想问是什么原因 @BrainWH

**Comment by BrainWH** [comment]
你好，可以发下两方的完整的日志信息

**Comment by Handikang** [comment]
你好，经过验证是环境的问题，已经解决了，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月29日(周四) 中午1:47
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/secretflow] 在secretpad中手动创建domaindata和domaindatasource跑psi任务失败 (Issue #1444)




 
你好，可以发下两方的完整的日志信息

**Comment by Handikang** [comment]
yes



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月29日(周日) 下午5:41
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/secretflow] 在secretpad中手动创建domaindata和domaindatasource跑psi任务失败 (Issue #1444)




 
Stale issue message. Please comment to remove stale tag. Otherwise this issue will be closed soon.
