### ISSUE TITLE
进行非平衡隐私求交报错

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1446]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow-1.7.0

### OS Platform and Distribution

Kylin 10

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
我想基于secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.7.0b0镜像，来测试非平衡PSI，为此，我找了2台虚拟机，每台虚拟机基于"主机模式"创建一个docker容器，容器alice的IP是XX.XX.XX.71，bob的IP是XX.XX.XX.75，我在alice容器创建ray header节点提示成功，但在bob容器创建ray从属节点时失败，提示：RuntimeError:Failed to connect to GCS
```

### Reproduction code to reproduce the issue.

```shell
RAY_DISABLE_REMOTE_CODE=true ray start --address="XX.XX.XX.71:9394" --resources='{"bob": 8}'
```

**Comment by lanyy9527** [comment]
您好，请检查下：
1. 是否使用host方式启动docker容器（比如在启动时添加参数--network host）；
2. telnet下alice的9394是否正常访问；
3. 确保虚拟机的防火墙规则允许ray的端口通信；

**Comment by Chrisdehe** [comment]
@coderSun20201112 看起来是因为你参考UB PSI文档的Ray启动命令需要更新，请先使用以下命令启动Ray集群，
ray start --head --node-ip-address="ip" --port="port" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
ray start --address="alice ip:port" --resources='{"bob": 16}' --disable-usage-stats

另外，如果你是需要做性能测试，建议通过生产模式来运行。
