### ISSUE TITLE
多方联合训练的问题

### ISSUE THREAD

**Issue by linhaibo123** [secretflow/secretflow#145]
您好，这里有几个疑问希望您能帮忙回答一下
假设我现在有三台机器：A, B, C
现在我在机器A上部署了一个k8s集群（参考ray部署）。机器A ip为：172.0.0.1 
在机器B上有一份代码：
`
import secretflow as sf

sf.init(address='ray://172.0.0.1 :10001')
bob , carlo,= sf.PYU('bob'), sf.PYU('carlo')
spu = sf.SPU({
                    'nodes': [
                        {
                            'party': 'bob',
                            'id': 'local:0',
                            'address': '机器B:9001',
                            'listen_address': '' # Optional. Address will be used if listen_address is empty.
                        },
                        {
                            'party': 'carlo',
                            'id': 'local:1',
                            'address': '机器C:9002',
                            'listen_address': ''
                        },
                    ],
                    'runtime_config': {
                        'protocol': spu.spu_pb2.SEMI2K,
                        'field': spu.spu_pb2.FM128,
                        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
                    }
                })
x1, _ = carlo(breast_cancer)(party_id=1)
x2, y = bob(breast_cancer)(party_id=2)
device = spu
W = jnp.zeros((30,))
b = 0.0
W_, b_, x1_, x2_, y_ = (
    sf.to(device, W),
    sf.to(device, b),
    x1.to(device),
    x2.to(device),
    y.to(device),
)
losses, W_, b_ = device(
    fit,
    static_argnames=['epochs'], num_returns=3
)(W_, b_, x1_, x2_, y_, epochs=10, learning_rate=1e-2)
`
请问下：
1. sf.init(address='ray://172.0.0.1 :10001')  这行代码我看是连接到机器A的集群的意思，那么前4行这样的代码如此写，使用的是机器A还是机器B的物理资源？
2. 现在我如果想使用机器B和机器C联合训练，那么我机器A的集群有没有必要？
或者类似的疑问就是我是否将cluster_def 直接改成机器A的地址，就可以实现机器A当做服务器，机器B和机器C分别使用本地的物理资源执行训练然后将参数上传到机器A进行参数的聚合操作，再分发给机器B和C？

**Comment by longshan-ant** [comment]
请参考一下 [集群部署](https://github.com/secretflow/secretflow/blob/beta/DEPLOYMENT.md) 的文档。
需要在ray节点（机器）加入集群的时候，按照文档指明是哪一方，这样在调度的时候会将计算调度到对应的机器；

**Comment by longshan-ant** [comment]
这个是对应的 [中文文档](https://secretflow.readthedocs.io/zh_CN/latest/getting_started/deployment.html#cluster-mode) 供参考

**Comment by linhaibo123** [comment]
> 请参考一下 [集群部署](https://github.com/secretflow/secretflow/blob/beta/DEPLOYMENT.md) 的文档。 需要在ray节点（机器）加入集群的时候，按照文档指明是哪一方，这样在调度的时候会将计算调度到对应的机器；

不好意思，还是不是很明白。我这样理解对吗?
1. 假设机器A为head节点，B和C 都为worker节点，其实是B和C在本地进行计算的
2. 进行数据交互的时候，机器B的代码是

`
B：
sf.init(address='ray://机器A :10001')
bob , carlo,= sf.PYU('bob','node'='node_B'), sf.PYU('carlo', node='node_C')  //使用node来指定节点
spu = sf.SPU({
'nodes': [
{
'party': 'bob',
'id': 'local:0',
'address': '机器B:9001',
'listen_address': '' # Optional. Address will be used if listen_address is empty.
},
{
'party': 'carlo',
'id': 'local:1',
'address': '机器C:9002',
'listen_address': ''
},
],
'runtime_config': {...}
})
x1, _ = carlo(breast_cancer)(party_id=1)
x2, y = bob(breast_cancer)(party_id=2)
x1_ = x1.to(bob)  //这样就完成了数据的传递
`
不知道这样是否可以？
3. 这个node后面填的内容现在还不懂，是启动ray的时候pod_name吗？

**Comment by longshan-ant** [comment]
ray在k8s上部署的方案可能并不直接适用于这里；因为现实中B/C并不会和A在同一个K8S集群中；所以最好的方式，就是你在B/C机器上手动启动ray实例，并按照[中文文档](https://secretflow.readthedocs.io/zh_CN/latest/getting_started/deployment.html#cluster-mode) 声明是哪个party； 如果按照此方案，可以不用管pod_name的事情

**Comment by linhaibo123** [comment]
> ray在k8s上部署的方案可能并不直接适用于这里；因为现实中B/C并不会和A在同一个K8S集群中；所以最好的方式，就是你在B/C机器上手动启动ray实例，并按照[中文文档](https://secretflow.readthedocs.io/zh_CN/latest/getting_started/deployment.html#cluster-mode) 声明是哪个party； 如果按照此方案，可以不用管pod_name的事情

明白了，谢谢

**Comment by linhaibo123** [comment]
```
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import OneHotEncoder
# import numpy as np
# from secretflow.utils.simulation.datasets import dataset

# mnist = np.load(dataset('mnist'), allow_pickle=True)
# image = mnist['x_train']
# label = mnist['y_train']
# alice_y = OneHotEncoder(sparse=False).fit_transform(label.reshape(-1, 1))
#
# random_seed = 1234
# alice_X_train, bob_X_train, alice_y_train, bob_y_train = train_test_split(image,
#                                                                           label, test_size=0.4,
#                                                                           random_state=random_seed)
# alice_X_train, X_test, alice_y_train, y_test = train_test_split(alice_X_train,
#                                                                 alice_y_train, test_size=0.33, random_state=random_seed)
#
# alice_X_test, bob_X_test, alice_y_test, bob_y_test = train_test_split(X_test,
#                                                                       y_test, test_size=0.5, random_state=random_seed)


# alice_y_train = OneHotEncoder(sparse=False).fit_transform(alice_y_train.reshape(-1, 1))
# alice_y_test = OneHotEncoder(sparse=False).fit_transform(alice_y_test.reshape(-1, 1))
# bob_y_train = OneHotEncoder(sparse=False).fit_transform(bob_y_train.reshape(-1, 1))
# bob_y_test = OneHotEncoder(sparse=False).fit_transform(bob_y_test.reshape(-1, 1))

# import pickle
# with open('./data/alice_train_img.csv', 'wb') as file:
#     pickle.dump(alice_X_train, file)
# with open('./data/alice_train_labels.csv', 'wb') as file:
#     pickle.dump(alice_y_train, file)
# with open('./data/alice_test_img.csv', 'wb') as file:
#     pickle.dump(alice_X_test, file)
# with open('./data/alice_test_labels.csv', 'wb') as file:
#     pickle.dump(alice_y_test, file)
#
# with open('./data/bob_train_img.csv', 'wb') as file:
#     pickle.dump(bob_X_train, file)
# with open('./data/bob_train_labels.csv', 'wb') as file:
#     pickle.dump(bob_y_train, file)
# with open('./data/bob_test_img.csv', 'wb') as file:
#     pickle.dump(bob_X_test, file)
# with open('./data/bob_test_labels.csv', 'wb') as file:
#     pickle.dump(bob_y_test, file)

# ==================上方注释部分全部都是构造数据，模拟两个不同节点，构造完后将bob的数据放到bob的物理节点，alice放到alice的物理节点========================================================

# 训练模型
import secretflow as sf
num_classes = 10
input_shape = (28, 28, 1)
from secretflow.security.aggregation import DeviceAggregator, SecureAggregator
from secretflow.ml.nn import FLModel


def create_conv_model(input_shape, num_classes, name='model'):
    def create_model():
        from tensorflow import keras
        from tensorflow.keras import layers
        # Create model
        model = keras.Sequential(
            [
                keras.Input(shape=input_shape),
                layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
                layers.MaxPooling2D(pool_size=(2, 2)),
                layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
                layers.MaxPooling2D(pool_size=(2, 2)),
                layers.Flatten(),
                layers.Dropout(0.5),
                layers.Dense(num_classes, activation="softmax"),
            ]
        )
        # Compile model
        model.compile(loss='categorical_crossentropy',
                      optimizer='adam',
                      metrics=["accuracy"])
        return model

    return create_model


model = create_conv_model(input_shape, num_classes)
password = '1234'
sf.init(address='192.168.27.29:30000', _redis_password=password)
carol, bob = sf.PYU('carol'), sf.PYU('bob')
# alice = sf.PYU('alice')
device_list = [carol, bob]
import spu
cdef = {
    'nodes': [
            {'party': 'carol', 'id': 'carol:0', 'address': '192.168.27.29'},
        {'party': 'bob', 'id': 'bob:1', 'address': '192.168.27.122'},
],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    },
}

spu_2pc = sf.SPU(cdef)
print(spu_2pc)
secure_aggregator = SecureAggregator(carol, device_list)
spu_aggregator = DeviceAggregator(spu_2pc)
fed_model = FLModel(server=carol,
                    device_list=device_list,
                    model=model,
                    aggregator=secure_aggregator,
                    strategy="fed_avg_w",
                    backend="tensorflow")

from secretflow.data.ndarray import load

x_train = load(sources={carol: '/home/linhb/workspace/secretflow_platform/data/alice_train_img.csv',
                bob: '/home/root/secret_data/bob_train_img.csv'}, allow_pickle=True)
y_train = load(sources={carol: '/home/linhb/workspace/secretflow_platform/data/alice_train_labels.csv',
                bob: '/home/root/secret_data/bob_train_labels.csv'}, allow_pickle=True)
x_test = load(sources={carol: '/home/linhb/workspace/secretflow_platform/data/alice_test_img.csv',
                bob: '/home/root/secret_data/bob_test_img.csv'}, allow_pickle=True)
y_test = load(sources={carol: '/home/linhb/workspace/secretflow_platform/data/alice_test_labels.csv',
                bob: '/home/root/secret_data/bob_test_labels.csv'}, allow_pickle=True)
history = fed_model.fit(x_train,
                        y_train,
                        validation_data=(x_test, y_test),
                        epochs=15,
                        sampler_method="batch",
                        batch_size=128,
                        aggregate_freq=2)

global_metric = fed_model.evaluate(x_test, y_test, batch_size=128)
print(global_metric)
```
上面的代码给大家参考下
1：机器A启动了一个alice的主节点，然后在机器A再一次启动了一个carol的从节点加入alice主节点。
2：机器B启动了一个bob的从节点，
3：上面的代码等于bob的数据是在机器B上，carol的数据是在机器A上，所以将carol改成alice也是可以跑成功的
4：机器A和机器B都会进行计算，这点观察cpu或者gpu可以看出来

下一步测试计划：
1：上面的机器A和机器B网络是互通的
2： 找三台机器，ABC。A和BC网络互通，ＢＣ之间不互通
3：Ａ启动主节点ａｌｉｃｅ。BC启动从节点bob 和carol。
4：然后BC尝试进行联邦训练，看是否可以成功
5：还有上面关于大佬说的这部分https://github.com/secretflow/secretflow/issues/145#issuecomment-1260302050
我还没想明白如果A和B/C不在同一个集群，那么假设B/C网络不互通，那么如何让BC联邦呢？要等上面测试完可能会进一步了解

**Comment by zhouaihui** [comment]
hi, @linhaibo123，上面的评论是指实践中A/B/C不会是一个跨机构的k8s全局集群，因为它们理论上是不同机构。隐语目前是要求节点之间互通的。

**Comment by linhaibo123** [comment]
> hi, @linhaibo123，上面的评论是指实践中A/B/C不会是一个跨机构的k8s全局集群，因为它们理论上是不同机构。隐语目前是要求节点之间互通的。

谢谢，我测完了，节点不互通secretflow是无法正常进行训练的
