### ISSUE TITLE
ray节点起不来

### ISSUE THREAD

**Issue by littleunicorn** [secretflow/secretflow#1454]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.1.0b0

### OS Platform and Distribution

centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
执行ray start后 ray节点会失效
```

### Reproduction code to reproduce the issue.

```shell
执行ray start后 ray节点会失效
```

**Comment by littleunicorn** [comment]
![image](https://github.com/user-attachments/assets/7e247fbf-ef72-4963-8cc7-7dc903112a9e)

**Comment by zimu-yuxi** [comment]
方便给一个ray start之后的截图吗？上方截图像是缺失的。
具体是ray节点起不来还是什么？

**Comment by zimu-yuxi** [comment]
线下已解决，启动ray时，使用公网IP，导致出现remote faild。修改为内网本机IP后解决
