### ISSUE TITLE
使用PIR功能时无法设置协议类型

### ISSUE THREAD

**Issue by chenxuqing** [secretflow/secretflow#1457]
### Issue Type

Others

### Source

binary

### Secretflow Version

v1.8.0b0

### OS Platform and Distribution

20.04

### Python version

3.10

### Bazel version

bazel 6.4.0

### GCC/Compiler version

9.4.0

### What happend and What you expected to happen.

```shell
这个pir_setup设置，好像无法配置协议类型是 IndexPIR 或 KeywordPIR，是否正常呢？
```

### Reproduction code to reproduce the issue.

```shell
spu.pir_setup(
    server="alice",
    input_path=f"{current_dir}/pir.csv",
    key_columns=["uid"],
    label_columns=["name","age"],
    oprf_key_path=f"{current_dir}/server_secret_key",
    setup_path=f"{current_dir}/alice_setup",
    num_per_query=1,
    label_max_len=20,
    bucket_size=1000000
)

reports = spu.pir_query(
    server="alice",
    client="bob",
    server_setup_path=f"{current_dir}/alice_setup",
    client_key_columns=["uid"],
    client_input_path=f"{current_dir}/pir-query.csv",
    client_output_path=f"{current_dir}/pir_result.csv",
)
```

**Comment by Chrisdehe** [comment]
@chenxuqing 
At this moment, SealPIR is temporaily removed and will come back later.

https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.2b0/user_guide/pir

**Comment by chenxuqing** [comment]
好的，非常期待！
