### ISSUE TITLE
使用secretflow训练模型后，通过Kuscia API 运行一个secretflow serving，预测结果始终是一个固定值

### ISSUE THREAD

**Issue by dmxdxx** [secretflow/secretflow#1458]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow v1.8.0b0

### OS Platform and Distribution

Win11

### Python version

3.12。5

### What happend and What you expected to happen.

```shell
使用secretflow训练模型后，通过Kuscia API 运行一个secretflow serving，预测结果始终是一个固定值：
```

### Reproduction code to reproduce the issue.

```shell
1
```

**Comment by dmxdxx** [comment]
![1725004208153_72428648-A98B-420a-BF01-112DDBA2A9A1](https://github.com/user-attachments/assets/5b365a94-4ad2-4d51-8991-9338d8577c3b)
![lQLPJwJUefWbjwPNA4_NB4Cwro48C5cSPsEGuhtOsjRAAA_1920_911](https://github.com/user-attachments/assets/8405a82c-6b8f-47da-9838-a0f394182233)

训练完成的模型文件
[phlo-nkvlkxbi-node-41-output-0.tar.gz](https://github.com/user-attachments/files/16813649/phlo-nkvlkxbi-node-41-output-0.tar.gz)

**Comment by lanyy9527** [comment]
您好，您这边训练的参数是如何配置的，可以发下相关截图吗；

**Comment by dmxdxx** [comment]
> 您好，您这边训练的参数是如何配置的，可以发下相关截图吗；

![image](https://github.com/user-attachments/assets/d8c13d89-1e55-4824-98e7-255c5655a391)
两张样本表：
[dsj.csv](https://github.com/user-attachments/files/16814405/dsj.csv)
[changxin.csv](https://github.com/user-attachments/files/16814407/changxin.csv)

**Comment by dmxdxx** [comment]
> 您好，您这边训练的参数是如何配置的，可以发下相关截图吗；

麻烦老师有空时帮忙答疑下，辛苦啦

**Comment by dmxdxx** [comment]
> 您好，您这边训练的参数是如何配置的，可以发下相关截图吗；

老师是因为我使用了mock服务吗？

**Comment by lanyy9527** [comment]
> > 您好，您这边训练的参数是如何配置的，可以发下相关截图吗；
> 
> 老师是因为我使用了mock服务吗？

是的，mock服务会返回一个固定的值，你可以试着用其它的（例如csv）

**Comment by dmxdxx** [comment]
> > > 您好，您这边训练的参数是如何配置的，可以发下相关截图吗；
> > 
> > 
> > 老师是因为我使用了mock服务吗？
> 
> 是的，mock服务会返回一个固定的值，你可以试着用其它的（例如csv）

好的，老师能不能麻烦提供一下相关使用文档，如何使用csv文件，没找到相关使用文档，辛苦了

**Comment by dmxdxx** [comment]
> > > > > 您好，您这边训练的参数是如何配置的，可以发下相关截图吗；
> > > > 
> > > > 
> > > > 老师是因为我使用了mock服务吗？
> > > 
> > > 
> > > 是的，mock服务会返回一个固定的值，你可以试着用其它的（例如csv）
> > 
> > 
> > 好的，老师能不能麻烦提供一下相关使用文档，如何使用csv文件，没找到相关使用文档，辛苦了
> 
> 可以参考：https://www.secretflow.org.cn/zh-CN/docs/serving/0.6.0b0/topics/system/feature_service

麻烦问下老师，这个SPI接口服务的逻辑是什么呢，/BatchFeatureService/BatchFetchFeature通过SPI获取特征数据并给出预测结果，那/PredictionService/Predict这个传参预测接口是干什么的呢
