### ISSUE TITLE
secretflow后面有计划支持windows吗，大概会是什么时间呢

### ISSUE THREAD

**Issue by allenkang** [secretflow/secretflow#146]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow 0.6.13b1

### OS Platform and Distribution

centos7.8

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
如题
```

### Reproduction code to reproduce the issue.

```shell
如题
```

**Comment by anakinxc** [comment]
介于 Windows 上有 WSL，而且性能非常的不错，短期内没有计划 Windows 的原生支持，个人推荐试一下 WSL 或者 Docker

**Comment by allenkang** [comment]
> 个人推荐试一下 WSL 或者 Docker

收到，谢谢
