### ISSUE TITLE
水平联邦学习自定义联邦策略

### ISSUE THREAD

**Issue by eternalovee** [secretflow/secretflow#1461]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

1.6

### OS Platform and Distribution

ubuntu 22.04

### Python version

3

### What happend and What you expected to happen.

```shell
请问docker下的secretnote支持开发自定义的联邦学习策略吗
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by wangzul** [comment]
SecretNote 是专为隐语开发者打造的高级工具套件。以 notebook 的形式呈现，支持多节点代码执行和文件管理，同时提供运行状态追踪功能，能较大程度提升开发者的效率和工作体验。

可以自主开发代码。

**Comment by eternalovee** [comment]
> SecretNote 是专为隐语开发者打造的高级工具套件。以 notebook 的形式呈现，支持多节点代码执行和文件管理，同时提供运行状态追踪功能，能较大程度提升开发者的效率和工作体验。
> 
> 可以自主开发代码。

请问有相关教程吗

**Comment by eternalovee** [comment]
> SecretNote 是专为隐语开发者打造的高级工具套件。以 notebook 的形式呈现，支持多节点代码执行和文件管理，同时提供运行状态追踪功能，能较大程度提升开发者的效率和工作体验。
> 
> 可以自主开发代码。

请问使用自定义策略如何在secretnote中实现部署

**Comment by wangzul** [comment]
> > SecretNote 是专为隐语开发者打造的高级工具套件。以 notebook 的形式呈现，支持多节点代码执行和文件管理，同时提供运行状态追踪功能，能较大程度提升开发者的效率和工作体验。
> > 可以自主开发代码。
> 
> 请问使用自定义策略如何在secretnote中实现部署，即更新__init__.py文件

要实现修改代码

**Comment by wangzul** [comment]
代码调试完毕后可通过编译、安装的方式进行代码更新。
