### ISSUE TITLE
spi求交失败

### ISSUE THREAD

**Issue by littleunicorn** [secretflow/secretflow#1464]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.1.0b0

### OS Platform and Distribution

centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
secretflow，spu启动正常
spi任务执行失败
```

### Reproduction code to reproduce the issue.

```shell
spuruntime调度失败
```

**Comment by littleunicorn** [comment]
![image](https://github.com/user-attachments/assets/d427fbe5-77ea-42e8-add0-bd0108f9a7fa)

**Comment by littleunicorn** [comment]
'SPURuntime' object has no attribute 'id'这个报错是啥情况

**Comment by zimu-yuxi** [comment]
> 'SPURuntime' object has no attribute 'id'这个报错是啥情况

这个报错没什么意义，可以将报错信息以文件形式贴出来吗，感觉不是很全
