### ISSUE TITLE
是否支持中文特征进行预测

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretflow#1470]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretpad:0.9.0b0 

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.11.7

### What happend and What you expected to happen.

```shell
无
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by 1139763082** [comment]
支持

**Comment by EightMonth** [comment]
但是我看secretpad的模型训练组件支持的特征字段都是double类型的

**Comment by 1139763082** [comment]
具体是哪个组件，在什么场景是使用？

**Comment by EightMonth** [comment]
![image](https://github.com/user-attachments/assets/44e9e8f1-7d46-41a0-af18-2605b80126d3)

**Comment by 1139763082** [comment]
现有的组件支持支double类型数据训练，如需支持中文需要先做转换为double，或者可以通过自定义组件的方式实现。
参考：https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/more_tutorials/new_components
