### ISSUE TITLE
运行PIR setup代码出现KeyboardInterrupt异常

### ISSUE THREAD

**Issue by yongboy** [secretflow/secretflow#1472]
### Issue Type

Bug

### Source

binary

### Secretflow Version

v1.9.0b1

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.10.12

### What happend and What you expected to happen.

您好：
我是在最新版的SecretNote上运行的PIR示范代码，参考视频教程：【第4讲：匿踪查询和隐语PIR的介绍及开发实践｜山大暑期课程】https://www.bilibili.com/video/BV1GS421R7Lh?p=4&vd_source=455a9c8cc4c628b815b0ea2085c11b15  。
（该视频教程请从第14分钟开始观看，直到播放完毕。）
该代码文件，我已上传到下面附件中，解压后即可得到 `pir_sigle_abs.ipynb` 文件。
[pir_sigle_abs.ipynb.zip](https://github.com/user-attachments/files/16929188/pir_sigle_abs.ipynb.zip)

运行到

```shell
spu.pir_setup(
    server="alice",
    input_path="alice_pir_input.csv",
    key_columns=["name"],
    label_columns=["age"],
    oprf_key_path="alice_oprf_key",
    setup_path="alice_setup",
    num_per_query=1,
    label_max_len=20,
    bucket_size=1000000
)
```

遇到`KeyboardInterrupt`异常，该异常可在  `pir_sigle_abs.ipynb` 文件中找到。

### Reproduction code to reproduce the issue.

请参考附件中的`pir_sigle_abs.ipynb`的`spu.pir_setup`代码输出部分。

**Comment by zimu-yuxi** [comment]
cluster_def和cluster_config里的端口不能一致，修改下之后试下呢

**Comment by yongboy** [comment]
@zimu-yuxi 
非常感谢，已正常工作！

**Comment by yongboy** [comment]
已解决！
