### ISSUE TITLE
关于ABY3的问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretflow#1473]
请教隐语的各位老师一个问题，在看到spu的协议配置的时候看到可以选择ABY3，但是看隐语中ABY3的说明：
![image](https://github.com/user-attachments/assets/e9f6314e-2ee6-48de-8fc4-d0d807e7fa1d)
在隐语中的实现不依赖于姚氏协议，请问这个应该怎么理解？ABY里的Y不就是姚氏协议吗？是在隐语里只实现了算术电路和布尔电路的转换吗？

**Comment by wangzul** [comment]
gc性能大部分情况下比较差所以没实现～

**Comment by wangzul** [comment]
gc性能大部分情况下比较差所以没实现～
