### ISSUE TITLE
secretpad源码安装的时候secret-web报这个错误

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1475]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.8

### OS Platform and Distribution

ub22,docker27+,24g内存，16核

### Python version

无

### What happend and What you expected to happen.

```shell
mvn clean install -Dmaven.test.skip=true
执行之后
```

### Reproduction code to reproduce the issue.

```shell
CreateProcess error=193, %1 is not a valid Win32 application
```

**Comment by liusiqqq** [comment]
![Uploading Snipaste_2024-09-10_16-21-21.png…]()

**Comment by liusiqqq** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for secretpad-parent 0.0.1-SNAPSHOT:
[INFO]
[INFO] secretpad-parent ................................... SUCCESS [  0.886 s]
[INFO] secretpad-common ................................... SUCCESS [  4.051 s]
[INFO] secretpad-api ...................................... SUCCESS [  0.165 s]
[INFO] client-java-kusciaapi .............................. SUCCESS [ 17.747 s]
[INFO] secretpad-persistence .............................. SUCCESS [  3.533 s]
[INFO] secretpad-manager .................................. SUCCESS [  2.191 s]
[INFO] secretpad-service .................................. SUCCESS [  6.894 s]
[INFO] secretpad-web ...................................... FAILURE [  2.213 s]
[INFO] client-java-secretpad .............................. SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.091 s
[INFO] Finished at: 2024-09-10T16:18:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project secretpad-web: Command execution failed.: Cannot run program "C:\Users\user\Desktop\secrest\secretpad-main\secretpad-web\..\scripts\cert\gen_secretpad_serverkey.sh" (in directory "C:\Users\user\Desktop\secrest\secretpad-main\secretpad-web"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :secretpad-web

**Comment by wangzul** [comment]
这是一个兼容性问题
脚本兼容性：该错误意味着该脚本可能是为类Unix环境（Linux、macOS）设计的，并试图在Windows系统上运行。Shell脚本（.sh文件）在基于Unix的系统上本机运行，如果没有Git Bash、Cygwin或WSL（Linux的Windows子系统）等其他工具，就不能在Windows上直接执行。
