### ISSUE TITLE
按照文档操作无法生成镜像

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1477]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.8

### OS Platform and Distribution

ub22,docker27+,24g内存，16核

### Python version

无

### What happend and What you expected to happen.

```shell
无法生成镜像
```

### Reproduction code to reproduce the issue.

```shell
前后端都是最新版
```

**Comment by liusiqqq** [comment]
![Uploading Snipaste_2024-09-11_16-00-17.png…]()

**Comment by liusiqqq** [comment]
![Snipaste_2024-09-11_16-00-17](https://github.com/user-attachments/assets/f141c34c-06d5-4859-8084-22941e1e2538)

**Comment by liusiqqq** [comment]
![Uploading Snipaste_2024-09-11_16-01-23.png…]()

**Comment by liusiqqq** [comment]
![Uploading Snipaste_2024-09-11_16-01-23.png…]()

**Comment by liusiqqq** [comment]
![Snipaste_2024-09-11_16-01-23](https://github.com/user-attachments/assets/145daba2-aeac-4dbc-9797-5fd0091e6fe0)

**Comment by liusiqqq** [comment]
![Snipaste_2024-09-11_16-03-01](https://github.com/user-attachments/assets/51162e66-ae7e-4500-8bf3-6a42262d45c2)

**Comment by liusiqqq** [comment]
![Snipaste_2024-09-11_16-03-19](https://github.com/user-attachments/assets/fb975caa-a179-45ca-9313-d9bfb22d61c0)

**Comment by zimu-yuxi** [comment]
这个文档需要更新，build.sh只是打了jar包。你需要执行build_image.sh，并且需要修改build_image.sh脚本github_flag=false，
![image](https://github.com/user-attachments/assets/e1751f14-d213-4019-af3d-e4c64384f825)

**Comment by liusiqqq** [comment]
> 这个文档需要更新，build.sh只是打了jar包。你需要执行build_image.sh，并且需要修改build_image.sh脚本github_flag=false， ![image](https://private-user-images.githubusercontent.com/72854640/366370436-e1751f14-d213-4019-af3d-e4c64384f825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDQ0NzksIm5iZiI6MTcyNjA0NDE3OSwicGF0aCI6Ii83Mjg1NDY0MC8zNjYzNzA0MzYtZTE3NTFmMTQtZDIxMy00MDE5LWFmM2QtZTRjNjQzODRmODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA4NDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZDdmNmI1YjViNzI1ZGUyOTZlMDE0MjBmYTgwMTFmYmMyMDNhOTA0MDk2MTA3ZmM3OTZmODk0Njk3NzdkYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IWx7wRtTkx6lIwYrYmq_yi6_HZQNqWNJN4om-oqjgKg)

![image](https://github.com/user-attachments/assets/b66f53c8-0f48-4df8-938b-9836db7b7e01)

**Comment by liusiqqq** [comment]
还是没有生成镜像

**Comment by liusiqqq** [comment]
> > 这个文档需要更新，build.sh只是打了jar包。你需要执行build_image.sh，并且需要修改build_image.sh脚本github_flag=false， ![image](https://private-user-images.githubusercontent.com/72854640/366370436-e1751f14-d213-4019-af3d-e4c64384f825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDQ0NzksIm5iZiI6MTcyNjA0NDE3OSwicGF0aCI6Ii83Mjg1NDY0MC8zNjYzNzA0MzYtZTE3NTFmMTQtZDIxMy00MDE5LWFmM2QtZTRjNjQzODRmODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA4NDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZDdmNmI1YjViNzI1ZGUyOTZlMDE0MjBmYTgwMTFmYmMyMDNhOTA0MDk2MTA3ZmM3OTZmODk0Njk3NzdkYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IWx7wRtTkx6lIwYrYmq_yi6_HZQNqWNJN4om-oqjgKg)
> 
> ![image](https://private-user-images.githubusercontent.com/133972439/366373462-b66f53c8-0f48-4df8-938b-9836db7b7e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDUyNTUsIm5iZiI6MTcyNjA0NDk1NSwicGF0aCI6Ii8xMzM5NzI0MzkvMzY2MzczNDYyLWI2NmY1M2M4LTBmNDgtNGRmOC05MzhiLTk4MzZkYjdiN2UwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwODU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDJlM2YyYTQ4MWU1MGMyZGUxZWY1MTAzZGRjZmJiNWE2Yjk4YjE5YzM3OTljNzIyYzFjMDVmNTM0OWExOTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-2RRs_g6YLXY6cwVz5HeAwha5SFQERJirNmaO3a_tVU)

还是没有镜像生成

**Comment by zimu-yuxi** [comment]
执行的是build_image吗？如果是，那你再尝试下make image，前提还是build_image脚本里的github_flag修改为false

**Comment by liusiqqq** [comment]
> zimu

直接make不就是从远程那前端了？

**Comment by liusiqqq** [comment]
> 执行的是build_image吗？如果是，那你再尝试下make image，前提还是build_image脚本里的github_flag修改为false

直接make不就是从远程那前端了？
![Snipaste_2024-09-11_17-05-45](https://github.com/user-attachments/assets/e0b39ff6-bd4f-4834-9a25-f9b2b5e54396)

**Comment by zimu-yuxi** [comment]
github_flag要改成false

**Comment by liusiqqq** [comment]
> github_flag要改成false

![Snipaste_2024-09-11_17-21-41](https://github.com/user-attachments/assets/6c2c3c97-a830-48f3-93a9-34ce5ccf4185)

**Comment by liusiqqq** [comment]
> > github_flag要改成false
> 
> ![Snipaste_2024-09-11_17-21-41](https://private-user-images.githubusercontent.com/133972439/366387719-6c2c3c97-a830-48f3-93a9-34ce5ccf4185.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDY4MTEsIm5iZiI6MTcyNjA0NjUxMSwicGF0aCI6Ii8xMzM5NzI0MzkvMzY2Mzg3NzE5LTZjMmMzYzk3LWE4MzAtNDhmMy05M2E5LTM0Y2U1Y2NmNDE4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwOTIxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTM2YjdjOWM4ZGE0NTA2ZmI5ZDY3MGIyYzkzODlkYjMyYjYxZTFhYzFmMDdjZTIxZjg1ODA4NGE2MGU1YmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ARp8jFqWimvkxr-GVFkxAFtCQPrhzKCPd_yc0i-wv6A)

改了

**Comment by zimu-yuxi** [comment]
> > 执行的是build_image吗？如果是，那你再尝试下make image，前提还是build_image脚本里的github_flag修改为false
> 
> 直接make不就是从远程那前端了？ ![Snipaste_2024-09-11_17-05-45](https://private-user-images.githubusercontent.com/133972439/366385673-e0b39ff6-bd4f-4834-9a25-f9b2b5e54396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzUwMDYsIm5iZiI6MTcyNjEzNDcwNiwicGF0aCI6Ii8xMzM5NzI0MzkvMzY2Mzg1NjczLWUwYjM5ZmY2LWJkNGYtNDgzNC05YTI1LWY5YjJiNWU1NDM5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwOTUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTFkOGU3ZWUyZTc1YTkzOTYxOGQ4ZDVlNGUyNWI2M2UwYTBlMmZjMjdjYTVkOTc1Zjk2N2I5ZGVjZTFiZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1vh0zIFqleg52kVx607fytndTp_fU6DhfgHNa4iRfWo)


改完再执行下脚本呢？看你这个还是true
