### ISSUE TITLE
secretflow 仓库下的tests目录下的测试用例是怎么运行的？

### ISSUE THREAD

**Issue by jianjew** [secretflow/secretflow#1479]
看到secretflow代码仓下有一个tests目录，里面都是对应源码的测试用例。比如：
\secretflow\tests\component\preprocessing\data_prep\test_psi.py
请问下这个测试用例该怎么才能运行起来？需要做哪些操作吗？感谢

**Comment by zimu-yuxi** [comment]
可以参考[这里](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md)看下
