### ISSUE TITLE
Training performance of SSRegression with CHEETAH protocol

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/secretflow#148]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow 0.7.7b1

### OS Platform and Distribution

Linux ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
Hi,
the training time of one epoch is 1646.16 seconds, which is very slow, is there any way to improve the performance?
Each party has a training dataset of which the shape is [40w, 450]. The node of ray cluster is initialized with 32 workers. I use spu.spu_pb2.CHEETAH for SPU protocol configuration.
The spu configuration is:
cdef = {
    'nodes': [
        {'party': 'alice', 'id': 'alice:0', 'address': '***'},
        {'party': 'bob', 'id': 'bob:1', 'address': '***'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    },
}
```

### Reproduction code to reproduce the issue.

```shell
# run SS-SGD
# SSRegression use spu to fit model.
model = SSRegression(spu)
start = time.time()
model.fit(
    v_data,      # x
    label_data,  # y
    1,           # epochs
    0.001,       # learning_rate
    1024,        # batch_size
    't1',        # sig_type
    'logistic',  # reg_type
    'l2',        # penalty
    0.1,         # l2_norm
)
```

**Comment by rivertalk** [comment]
Hi @BeStrongok , thanks for the question.

You can change `field` from `FM128` to `FM64`, it should be faster.

**Comment by 6fj** [comment]
Hi @BeStrongok ，

Cheetah protocol is expected to be slower than ABY3 protocol since it's a 2PC MPC protocol. Please check [SPU doc](https://spu.readthedocs.io/en/beta/reference/mpc_status.html).

Thanks.

**Comment by BeStrongok** [comment]
> Hi @BeStrongok , thanks for the question.
> 
> You can change `field` from `FM128` to `FM64`, it should be faster.

Thanks for your advice, the training time of one epoch is reduced to 1063.24 seconds. :)

**Comment by rivertalk** [comment]
> Is there a multi-threading for local computation?

Yes, the local computation is paralleled, with thread pool.

We are trying to improve concurrency, but that's probably a long story :P

**Comment by BeStrongok** [comment]
> > Is there a multi-threading for local computation?
> 
> Yes, the local computation is paralleled, with thread pool.
> 
> We are trying to improve concurrency, but that's probably a long story :P

Cool, looking for your improvement.

**Comment by BeStrongok** [comment]
> Hi @BeStrongok ，
> 
> Cheetah protocol is expected to be slower than ABY3 protocol since it's a 2PC MPC protocol. Please check [SPU doc](https://spu.readthedocs.io/en/beta/reference/mpc_status.html).
> 
> Thanks.

Thanks for your advice, with `spu.spu_pb2.ABY3` configuration, the training time is reduced to 106.07 seconds, which is fast enough. :)

**Comment by 6fj** [comment]
Hi @BeStrongok 

At this moment, we don't provide the option of thread num. ** protocol** and ** field** would be main factor to performance. 

If you are interested, you may try to modify fxp arithmetic options like * fxp_exp_mode* and * fxp_log_mode*.

To check the runtime config, please check: https://spu.antfin-inc.com/reference/runtime_config.html#runtimeconfig
To check MPC Protocol, please check: https://spu.antfin-inc.com/reference/mpc_status.html
To check Fxp Arithmetic options, please check https://spu.antfin-inc.com/reference/fxp.html

Thanks.

**Comment by BeStrongok** [comment]
> Hi @BeStrongok
> 
> At this moment, we don't provide the option of thread num. **protocol** and **field** would be main factor to performance.
> 
> If you are interested, you may try to modify fxp arithmetic options like _fxp_exp_mode_ and _fxp_log_mode_.
> 
> To check the runtime config, please check: https://spu.antfin-inc.com/reference/runtime_config.html#runtimeconfig To check MPC Protocol, please check: https://spu.antfin-inc.com/reference/mpc_status.html To check Fxp Arithmetic options, please check https://spu.antfin-inc.com/reference/fxp.html
> 
> Thanks.

Thanks for your help. :)

**Comment by BeStrongok** [comment]
Hi,
I find that the training time of the first epoch is obviously longer than the latter. Why this appears?
```
INFO:ray.worker:Connecting to existing Ray cluster at address: ***
INFO:absl:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
INFO:absl:Unable to initialize backend 'gpu': NOT_FOUND: Could not find registered platform with name: "cuda". Available platform names are: Host Interpreter
INFO:absl:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
INFO:root:epoch 1 times: 105.28203415870667s
INFO:root:epoch 2 times: 41.352490186691284s
INFO:root:epoch 3 times: 41.79883646965027s
INFO:root:epoch 4 times: 40.615687131881714s
INFO:root:epoch 5 times: 40.58101201057434s
INFO:root:epoch 6 times: 40.28035926818848s
INFO:root:epoch 7 times: 40.73111152648926s
INFO:root:epoch 8 times: 40.176098346710205s
INFO:root:epoch 9 times: 40.04830360412598s
```

**Comment by 6fj** [comment]
Hi @BeStrongok ,

There are two reasons:
1. We need to do data infeeds in the first epoch while not in the following epochs. This should be the main factor.
2. From the second epoch, spu compiler can utilize cache.

**Comment by anakinxc** [comment]
> Hi, I find that the training time of the first epoch is obviously longer than the latter. Why this appears?
> 
> ```
> INFO:ray.worker:Connecting to existing Ray cluster at address: ***
> INFO:absl:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
> INFO:absl:Unable to initialize backend 'gpu': NOT_FOUND: Could not find registered platform with name: "cuda". Available platform names are: Host Interpreter
> INFO:absl:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
> WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
> INFO:root:epoch 1 times: 105.28203415870667s
> INFO:root:epoch 2 times: 41.352490186691284s
> INFO:root:epoch 3 times: 41.79883646965027s
> INFO:root:epoch 4 times: 40.615687131881714s
> INFO:root:epoch 5 times: 40.58101201057434s
> INFO:root:epoch 6 times: 40.28035926818848s
> INFO:root:epoch 7 times: 40.73111152648926s
> INFO:root:epoch 8 times: 40.176098346710205s
> INFO:root:epoch 9 times: 40.04830360412598s
> ```

Hi BeStrongok,

The first epoch includes initial data feed which can take a fair amount of time, also SPU uses JIT compilation and caches the compiled results for later reuses.

So the first epoch is indeed doing more things :P.

**Comment by BeStrongok** [comment]
Cool! It seems that the first epoch do a lot of things, which includes compilation, data feed and so on. This is pretty fast.
