### ISSUE TITLE
Kuscia 上运行 SCQL 联合分析任务时报错

### ISSUE THREAD

**Issue by moon-177** [secretflow/secretflow#1480]
### Discussed in https://github.com/orgs/secretflow/discussions/1478

<div type='discussions-op-text'>

<sup>Originally posted by **YanTingting-deep** September 11, 2024</sup>
请问在 Kuscia 上运行 SCQL 联合分析任务时，返回以下报错，是什么原因导致的?
其中Kuscia为0.11.0b0，SCQL 为0.9.0b1。同步查询前的操作均按照文档完成。 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/tutorial/run_scql_on_kuscia_cn#kuscia-scql

bash-5.2# curl -X POST http://127.0.0.1:80/intra/query \
--header "host: scql-broker-intra.alice.svc" \
--header "kuscia-source: alice" \
-H "Content-Type: application/json" \
-d '{
    "project_id": "demo",
    "query":"SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;"
}'

{"status":{"code":320,"message":"RunExecutionPlan run jobs(f049da41-704f-11ef-a139-0aab3169f188) failed, catch std::exception=[Enforce fail at engine/datasource/csvdb_adaptor.cc:194] !duck_result->HasError(). send query to DuckDB failed, msg=IO Error: No files found that match the pattern \"/home/kuscia/var/storage/data/scql-alice.csv\"\nStacktrace:\n#0 scql::engine::op::RunSQL::Execute()+0x560c6855c9c8\n#1 scql::engine::Executor::RunExecNode()+0x560c682587e6\n#2 scql::engine::EngineServiceImpl::RunPlanCore()+0x560c68242639\n#3 std::_Function_handler<>::_M_invoke()+0x560c682434fb\n#4 std::__future_base::_State_baseV2::_M_do_set()+0x560c6823c133\n#5 (unknown)+0x7fc896f6fee8\n","details":[]},"result":null}</div>

**Comment by zimu-yuxi** [comment]
data 目录挂载后，容器内的数据被覆盖了。可以在https://github.com/secretflow/kuscia/tree/main/testdata这里找到相关的测试数据，把它放到kuscia容器对应的位置/home/kuscia/var/storage/data下

后续我们会修改下官方文档

**Comment by YanTingting-deep** [comment]
kuscia容器对应的位置/home/kuscia/var/storage/data下是有文件的。上述任务中需要的scql-alice.csv和scql-bob.csv都在。

**Comment by zimu-yuxi** [comment]
可以截图看一下吗？

**Comment by YanTingting-deep** [comment]
您需要看什么，我文字描述一下。

**Comment by zimu-yuxi** [comment]
> 您需要看什么，我文字描述一下。
No files found that match the pattern "/home/kuscia/var/storage/data/scql-alice.csv"，因为看报错是没有找到文件，我们内部看了下，部署后，的确在该路径下没有scql-alice.csv文件

**Comment by moon-177** [comment]
“该路径”是指kuscia容器中的/home/kuscia/var/storage/data/scql-alice.csv吗？我这边看是有的，我们部署的两个节点alice和bob的容器中对应路径下都有这些文件。

具体操作如下：1、docker inspect找到容器实际存储位置，2、接着进入/home/kuscia/var/storage/data/路径下，3、存在scql-alice.csv。或者通过命令进入容器中，cd到/home/kuscia/var/storage/data/，文件存在。

我们刚才有考虑这里说的没有找到文件，莫非是到scql容器中去找了？

**Comment by zimu-yuxi** [comment]
> “该路径”是指kuscia容器中的/home/kuscia/var/storage/data/scql-alice.csv吗？我这边看是有的，我们部署的两个节点alice和bob的容器中对应路径下都有这些文件。
> 
> 具体操作如下：1、docker inspect找到容器实际存储位置，2、接着进入/home/kuscia/var/storage/data/路径下，3、存在scql-alice.csv。或者通过命令进入容器中，cd到/home/kuscia/var/storage/data/，文件存在。
> 
> 我们刚才有考虑这里说的没有找到文件，莫非是到scql容器中去找了？

如果/home/kuscia/var/storage/data/下没有scql-alice.csv，是能够复现出来你这个问题，新增之后就可以解决。因此目前疑惑点文件是否真的存在。可以ls | grep scql-alice.csv看下吗？感谢

**Comment by LeeTheByRiver** [comment]
您这边kuscia的部署模式是runc、runp还是runk？

**Comment by moon-177** [comment]
runc

**Comment by moon-177** [comment]
> > “该路径”是指kuscia容器中的/home/kuscia/var/storage/data/scql-alice.csv吗？我这边看是有的，我们部署的两个节点alice和bob的容器中对应路径下都有这些文件。
> > 具体操作如下：1、docker inspect找到容器实际存储位置，2、接着进入/home/kuscia/var/storage/data/路径下，3、存在scql-alice.csv。或者通过命令进入容器中，cd到/home/kuscia/var/storage/data/，文件存在。
> > 我们刚才有考虑这里说的没有找到文件，莫非是到scql容器中去找了？
> 
> 如果/home/kuscia/var/storage/data/下没有scql-alice.csv，是能够复现出来你这个问题，新增之后就可以解决。因此目前疑惑点文件是否真的存在。可以ls | grep scql-alice.csv看下吗？感谢

您好，我在alice容器中执行了 ls 命令，没有 scql-alice.csv 这个文件；但是我直接去容器对应的实际路径下看确实是有的…

**Comment by moon-177** [comment]
> 可以将CSV文件copy到容器内或者从[这里](https://github.com/secretflow/kuscia/tree/main/testdata)获取

您好，将csv文件放进容器后，任务跑成了。非常感谢！！！
