### ISSUE TITLE
使用bash scripts/build/build_image.sh 无法产生镜像

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1482]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.8

### OS Platform and Distribution

ub22,docker27+,24g内存，16核

### Python version

无

### What happend and What you expected to happen.

```shell
111
```

### Reproduction code to reproduce the issue.

```shell
111
```

**Comment by liusiqqq** [comment]
![Snipaste_2024-09-12_10-18-10](https://github.com/user-attachments/assets/4851d4bb-7e9a-4383-b7f0-e8f500636e81)

**Comment by liusiqqq** [comment]
![image](https://github.com/user-attachments/assets/c9dda323-40d7-4725-90ac-bbf39a33629f)

**Comment by liusiqqq** [comment]
是产生了吗？产生的镜像在哪里呀？

**Comment by wangzul** [comment]
![image](https://github.com/user-attachments/assets/876fba27-e0fb-4d64-a802-6033553168ae)

**Comment by liusiqqq** [comment]
> ![image](https://private-user-images.githubusercontent.com/55971198/366739439-876fba27-e0fb-4d64-a802-6033553168ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjQzODEsIm5iZiI6MTcyNjEyNDA4MSwicGF0aCI6Ii81NTk3MTE5OC8zNjY3Mzk0MzktODc2ZmJhMjctZTBmYi00ZDY0LWE4MDItNjAzMzU1MzE2OGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOWU5ZjVjNzFkNzA0ZDY3MzI3NmRlNjIxMzFhMThkYmIyMjMyOWQxMWExMDllY2E0ZmEwMjE2YzM0ZjE3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t8-dDC9C5UzEuhby4Iyn0CPDQSnnMf-jc5Qvw2c7Nbk)

![image](https://github.com/user-attachments/assets/59d1a052-63cd-4bf6-a131-524ef1925500)
报这个异常怎么解决下呢

**Comment by BrainWH** [comment]
你好，https://github.com/secretflow/secretflow/issues/1477里面的问题解决了吗？现在是什么状态呢？
