### ISSUE TITLE
secretpad0.9.0 idea p2p部署运行异常

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1486]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretPad0.9

### OS Platform and Distribution

ub22,docker27+,24g内存，16核

### Python version

无

### What happend and What you expected to happen.

```shell
111
```

### Reproduction code to reproduce the issue.

```shell
111
```

**Comment by liusiqqq** [comment]
![image](https://github.com/user-attachments/assets/8c38b618-1c56-4b5a-88d3-a1741be92a8e)

**Comment by lanyy9527** [comment]
需要从allinone部署路径下，将server.jks文件拷贝到secretpad路径下 ：
cp /Users/allinone/secretpad/config/server.jks /Users/secretpad/config/server.jks（Users 替换成你本地路径）
