### ISSUE TITLE
Cluster workers died When training SS-XGB with ABY3 protocol

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/secretflow#149]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.7.7b1

### OS Platform and Distribution

Linux ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
Hi,
I'm training the SS-XGB model with 3-nodes cluster. There is an error raised by ray. 
The VM Layout for SPURuntime is Hybrid.
I tried several times, this error occurred stably.
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging

import spu
import secretflow as sf
import pandas as pd

from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay
from secretflow.ml.boost.ss_xgb_v import Xgb

from sklearn.metrics import roc_auc_score

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# init all nodes in local Standalone Mode.
sf.shutdown()
sf.init(address='***')

# init PYU, the Python Processing Unit, process plaintext in each node.
alice = sf.PYU('alice')
bob = sf.PYU('bob')

# init SPU, the Secure Processing Unit,
#           process ciphertext under the protection of a multi-party secure computing protocol

cdef = {
    'nodes': [
        {'party': 'alice', 'id': 'alice:0', 'address': '***'},
        {'party': 'bob', 'id': 'bob:1', 'address': '***'},
        {'party': 'carol', 'id': 'carol:2', 'address': '***'}
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM64,
    },
}

spu = sf.SPU(cdef)

# read data in each party
def read_x(role, mode):
    file_path = "/shared/sf_test/{}/{}_{}_epsilon_450d.csv".format(role, mode, role)
    x = pd.read_csv(file_path)
    if role == "host":
        x = x.to_numpy()[:, 1:]
    else:
        x = x.to_numpy()[:, 2:]
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    return x

def read_y(role, mode):
    file_path = "/shared/sf_test/{}/{}_{}_epsilon_450d.csv".format(role, mode, role)
    y = pd.read_csv(file_path)
    y = y.to_numpy()
    return y[:, 1]

# alice / bob / carol each hold one third of the features of the data
# read_x is execute locally on each node.
v_data = FedNdarray(
    partitions={
        alice: alice(read_x)("host", "train"),
        bob: bob(read_x)("guest", "train"),
    },
    partition_way=PartitionWay.VERTICAL,
)
# Y label belongs to alice
label_data = FedNdarray(
    partitions={
        bob: bob(read_y)("guest", "train"),
    },
    partition_way=PartitionWay.VERTICAL,
)

# wait IO finished
wait([p.data for p in v_data.partitions.values()])
wait([p.data for p in label_data.partitions.values()])


# run SS-XGB
xgb = Xgb(spu)
start = time.time()
params = {
    # for more detail, see Xgb API doc
    'num_boost_round': 5,
    'max_depth': 5,
    'learning_rate': 0.1,
    'sketch_eps': 0.08,
    'objective': 'logistic',
    'reg_lambda': 1,
    'subsample': 1,
    'colsample_bytree': 1,
    'base_score': 0.5,
}
model = xgb.train(params, v_data, label_data)
logging.info(f"train time: {time.time() - start}")


# Do predict
start = time.time()
test_data = FedNdarray(
    partitions={
        alice: alice(read_x)("host", "test"),
        bob: bob(read_x)("guest", "test"),
    },
    partition_way=PartitionWay.VERTICAL,
)
# Now the result is saved in the spu by ciphertext
spu_yhat = model.predict(test_data)
# reveal for auc test.
yhat = reveal(spu_yhat)
logging.info(f"predict time: {time.time() - start}")
y = read_y("guest", "test")
logging.info(f"auc: {roc_auc_score(y, yhat)}")
```

**Comment by BeStrongok** [comment]
The log of ray worker is:
```
[2022-10-11 11:23:57,274 I 48450 48450] core_worker_process.cc:120: Constructing CoreWorkerProcess. pid: 48450
[2022-10-11 11:23:57,277 I 48450 48450] grpc_server.cc:105: worker server started, listening on port 10015.
[2022-10-11 11:23:57,280 I 48450 48450] core_worker.cc:175: Initializing worker at address: ***, worker ID b888304477f787569d8dfa34775d9b07f75145bc1701c9583d98609f, raylet de5ab6d85dcfc76556c8ea0e28f76c3ad3509f3efc1ac709fcca5c2b
[2022-10-11 11:23:57,280 I 48450 48473] gcs_server_address_updater.cc:32: GCS Server updater thread id: 139624873711360
[2022-10-11 11:23:57,382 I 48450 48450] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2022-10-11 11:23:57,383 I 48450 48490] core_worker.cc:494: Event stats:


Global stats: 16 total (11 active)
Queueing time: mean = 194.006 us, max = 1.110 ms, min = 198.231 us, total = 3.104 ms
Execution time:  mean = 22.984 us, total = 367.740 us
Event stats:
        PeriodicalRunner.RunFnPeriodically - 7 total (2 active, 1 running), CPU time: mean = 52.534 us, total = 367.740 us
        UNKNOWN - 3 total (3 active), CPU time: mean = 0.000 s, total = 0.000 s
        InternalPubSubGcsService.grpc_client.GcsSubscriberPoll - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
        GcsClient.deadline_timer.check_gcs_connection - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
        WorkerInfoGcsService.grpc_client.AddWorkerInfo - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
        InternalPubSubGcsService.grpc_client.GcsSubscriberCommandBatch - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
        NodeManagerService.grpc_client.ReportWorkerBacklog - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
        CoreWorker.deadline_timer.flush_profiling_events - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s


[2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = b92df5f0b7329c551c28e70ed6146944fc90fe7553673517c0f4c44d, IsAlive = 1
[2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = de5ab6d85dcfc76556c8ea0e28f76c3ad3509f3efc1ac709fcca5c2b, IsAlive = 1
[2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = 00a937ac4146f0f746a369b93cbf6d238ae3b6f96d7b48a124410af9, IsAlive = 1
[2022-10-11 11:24:07,391 W 48450 48491] metric_exporter.cc:207: [1] Export metrics to agent failed: GrpcUnknown: RPC Error message: Method not found!; RPC Error details: . This won't affect Ray, but you can lose metrics from the cluster.
```

**Comment by 6fj** [comment]
Hi @BeStrongok ,

I will try to reproduce the issue and reach back to you on the next working day.

**Comment by anakinxc** [comment]
> The log of ray worker is:
> 
> ```
> [2022-10-11 11:23:57,274 I 48450 48450] core_worker_process.cc:120: Constructing CoreWorkerProcess. pid: 48450
> [2022-10-11 11:23:57,277 I 48450 48450] grpc_server.cc:105: worker server started, listening on port 10015.
> [2022-10-11 11:23:57,280 I 48450 48450] core_worker.cc:175: Initializing worker at address: ***, worker ID b888304477f787569d8dfa34775d9b07f75145bc1701c9583d98609f, raylet de5ab6d85dcfc76556c8ea0e28f76c3ad3509f3efc1ac709fcca5c2b
> [2022-10-11 11:23:57,280 I 48450 48473] gcs_server_address_updater.cc:32: GCS Server updater thread id: 139624873711360
> [2022-10-11 11:23:57,382 I 48450 48450] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
> [2022-10-11 11:23:57,383 I 48450 48490] core_worker.cc:494: Event stats:
> 
> 
> Global stats: 16 total (11 active)
> Queueing time: mean = 194.006 us, max = 1.110 ms, min = 198.231 us, total = 3.104 ms
> Execution time:  mean = 22.984 us, total = 367.740 us
> Event stats:
>         PeriodicalRunner.RunFnPeriodically - 7 total (2 active, 1 running), CPU time: mean = 52.534 us, total = 367.740 us
>         UNKNOWN - 3 total (3 active), CPU time: mean = 0.000 s, total = 0.000 s
>         InternalPubSubGcsService.grpc_client.GcsSubscriberPoll - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
>         GcsClient.deadline_timer.check_gcs_connection - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
>         WorkerInfoGcsService.grpc_client.AddWorkerInfo - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
>         InternalPubSubGcsService.grpc_client.GcsSubscriberCommandBatch - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
>         NodeManagerService.grpc_client.ReportWorkerBacklog - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
>         CoreWorker.deadline_timer.flush_profiling_events - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> 
> 
> [2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = b92df5f0b7329c551c28e70ed6146944fc90fe7553673517c0f4c44d, IsAlive = 1
> [2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = de5ab6d85dcfc76556c8ea0e28f76c3ad3509f3efc1ac709fcca5c2b, IsAlive = 1
> [2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = 00a937ac4146f0f746a369b93cbf6d238ae3b6f96d7b48a124410af9, IsAlive = 1
> [2022-10-11 11:24:07,391 W 48450 48491] metric_exporter.cc:207: [1] Export metrics to agent failed: GrpcUnknown: RPC Error message: Method not found!; RPC Error details: . This won't affect Ray, but you can lose metrics from the cluster.
> ```
> 
> The error message output by secreflow is:
> 
> ```
> ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
> 2022-10-11 11:24:54,061 ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=24849, ip=***, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f68a82bb250>)
>   At least one of the input arguments for this task could not be computed:
> ray.exceptions.RayTaskError: ray::_spu_compile() (pid=11410, ip=***)
>   At least one of the input arguments for this task could not be computed:
> ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=11409, ip=***, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f3a047f7340>)
>   At least one of the input arguments for this task could not be computed:
> ray.exceptions.RayTaskError: ray::_spu_compile() (pid=11410, ip=***)
>   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 476, in _spu_compile
>     meta_args, meta_kwargs = jax.tree_util.tree_map(
>   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/jax/_src/tree_util.py", line 184, in tree_map
>     return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
>   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/jax/_src/tree_util.py", line 184, in <genexpr>
>     return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
>   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 477, in <lambda>
>     lambda x: ray.get(x) if isinstance(x, ray.ObjectRef) else x,
> ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
> ```

Hi BeStrongok,

What's your machine spec and size of dataset?

FYI, compare with LR, XGB requires way more memory.

**Comment by 6fj** [comment]
Hi @BeStrongok ,

Could you please provide the mock version of epsilon_450d.csv for two parties?

**Comment by BeStrongok** [comment]
> > The log of ray worker is:
> > ```
> > [2022-10-11 11:23:57,274 I 48450 48450] core_worker_process.cc:120: Constructing CoreWorkerProcess. pid: 48450
> > [2022-10-11 11:23:57,277 I 48450 48450] grpc_server.cc:105: worker server started, listening on port 10015.
> > [2022-10-11 11:23:57,280 I 48450 48450] core_worker.cc:175: Initializing worker at address: ***, worker ID b888304477f787569d8dfa34775d9b07f75145bc1701c9583d98609f, raylet de5ab6d85dcfc76556c8ea0e28f76c3ad3509f3efc1ac709fcca5c2b
> > [2022-10-11 11:23:57,280 I 48450 48473] gcs_server_address_updater.cc:32: GCS Server updater thread id: 139624873711360
> > [2022-10-11 11:23:57,382 I 48450 48450] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
> > [2022-10-11 11:23:57,383 I 48450 48490] core_worker.cc:494: Event stats:
> > 
> > 
> > Global stats: 16 total (11 active)
> > Queueing time: mean = 194.006 us, max = 1.110 ms, min = 198.231 us, total = 3.104 ms
> > Execution time:  mean = 22.984 us, total = 367.740 us
> > Event stats:
> >         PeriodicalRunner.RunFnPeriodically - 7 total (2 active, 1 running), CPU time: mean = 52.534 us, total = 367.740 us
> >         UNKNOWN - 3 total (3 active), CPU time: mean = 0.000 s, total = 0.000 s
> >         InternalPubSubGcsService.grpc_client.GcsSubscriberPoll - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> >         GcsClient.deadline_timer.check_gcs_connection - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> >         WorkerInfoGcsService.grpc_client.AddWorkerInfo - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> >         InternalPubSubGcsService.grpc_client.GcsSubscriberCommandBatch - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> >         NodeManagerService.grpc_client.ReportWorkerBacklog - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> >         CoreWorker.deadline_timer.flush_profiling_events - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
> > 
> > 
> > [2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = b92df5f0b7329c551c28e70ed6146944fc90fe7553673517c0f4c44d, IsAlive = 1
> > [2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = de5ab6d85dcfc76556c8ea0e28f76c3ad3509f3efc1ac709fcca5c2b, IsAlive = 1
> > [2022-10-11 11:23:57,383 I 48450 48490] accessor.cc:599: Received notification for node id = 00a937ac4146f0f746a369b93cbf6d238ae3b6f96d7b48a124410af9, IsAlive = 1
> > [2022-10-11 11:24:07,391 W 48450 48491] metric_exporter.cc:207: [1] Export metrics to agent failed: GrpcUnknown: RPC Error message: Method not found!; RPC Error details: . This won't affect Ray, but you can lose metrics from the cluster.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The error message output by secreflow is:
> > ```
> > ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
> > 2022-10-11 11:24:54,061 ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=24849, ip=***, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f68a82bb250>)
> >   At least one of the input arguments for this task could not be computed:
> > ray.exceptions.RayTaskError: ray::_spu_compile() (pid=11410, ip=***)
> >   At least one of the input arguments for this task could not be computed:
> > ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=11409, ip=***, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f3a047f7340>)
> >   At least one of the input arguments for this task could not be computed:
> > ray.exceptions.RayTaskError: ray::_spu_compile() (pid=11410, ip=***)
> >   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 476, in _spu_compile
> >     meta_args, meta_kwargs = jax.tree_util.tree_map(
> >   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/jax/_src/tree_util.py", line 184, in tree_map
> >     return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
> >   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/jax/_src/tree_util.py", line 184, in <genexpr>
> >     return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
> >   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 477, in <lambda>
> >     lambda x: ray.get(x) if isinstance(x, ray.ObjectRef) else x,
> > ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
> > ```
> 
> Hi BeStrongok,
> 
> What's your machine spec and size of dataset?
> 
> FYI, compare with LR, XGB requires way more memory.

I run the docker with `-m 50G --shm-size=10.24gb` options. The logical processors of host machine is 48.

**Comment by 6fj** [comment]
Hi @BeStrongok ,

Thank you for your patience.
We are still working on optimizations to support  large dataset. At this moment, could you please shrink the dataset to [10000, 450] to check if everything else goes well?

**Comment by BeStrongok** [comment]
> Hi @BeStrongok ,
> 
> Thank you for your patience. We are still working on optimizations to support large dataset. At this moment, could you please shrink the dataset to [10000, 450] to check if everything else goes well?

Thanks for your help. Due to the upload limitation of github, i have to shrink the dataset to [5000, 450].
[train_guest_epsilon_450d_sample.csv](https://github.com/secretflow/secretflow/files/9761155/train_guest_epsilon_450d_sample.csv)
[train_host_epsilon_450d_sample.csv](https://github.com/secretflow/secretflow/files/9761156/train_host_epsilon_450d_sample.csv)

**Comment by BeStrongok** [comment]
I also run by myself on this minimum dataset, it can work well.
```
(secretflow) bash-4.4# python test_xgb.py 
2022-10-12 03:20:34.121245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
INFO:ray.worker:Connecting to existing Ray cluster at address: ***
INFO:absl:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
INFO:absl:Unable to initialize backend 'gpu': NOT_FOUND: Could not find registered platform with name: "cuda". Available platform names are: Interpreter Host
INFO:absl:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
INFO:root:global_setup time 30.576295614242554s
INFO:root:epoch 0 time 92.19655013084412s
```

**Comment by 6fj** [comment]
Hi @BeStrongok ，

Please stay tuned for future versions. We are keep improving algorithms to support larger datasets.
Thanks.

**Comment by BeStrongok** [comment]
> Hi @BeStrongok ，
> 
> Please stay tuned for future versions. We are keep improving algorithms to support larger datasets. Thanks.

Thanks, looking for your improvement. :)
