### ISSUE TITLE
secretpad打成mvp部署包还可以用自己的前后端代码吗

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1492]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretPad0.9

### OS Platform and Distribution

ub22,docker27+,24g内存，16核

### Python version

无

### What happend and What you expected to happen.

```shell
使用secretpad源码，然后把前端的dist目录内容放到Java/resource/static目录下，如果利用https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/development/build_mvp中的mvp打包方式，打出的包是自己的前后端代码吗？如果不是怎样才可以用前后端源码打包呢？
```

### Reproduction code to reproduce the issue.

```shell
111
```

**Comment by 1139763082** [comment]
可以参考下这块代码
![image](https://github.com/user-attachments/assets/53d449b5-410a-412a-b1a5-9f4ed6be5603)

**Comment by liusiqqq** [comment]
> 可以参考下这块代码 ![image](https://private-user-images.githubusercontent.com/25895306/367499025-53d449b5-410a-412a-b1a5-9f4ed6be5603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDEyMDAsIm5iZiI6MTcyNjMwMDkwMCwicGF0aCI6Ii8yNTg5NTMwNi8zNjc0OTkwMjUtNTNkNDQ5YjUtNDEwYS00MTJhLWIxYTUtOWY0ZWQ2YmU1NjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZTE1M2FhMmRkYTdlNWQ2MGM0YjdhY2JlYzk3YTE3Zjc5MmFkMjg3YzBmOTA2ZTFiNTQwOWNkMzUwM2Y0ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FsbnLIwoxEKJGqKG9sUnA5ckAdCKz4g9aCeAWTrQXc)

大佬，你这个是哪个文件里的

**Comment by 1139763082** [comment]
https://github.com/secretflow/secretpad/blob/main/scripts/build/build.sh

**Comment by liusiqqq** [comment]
> https://github.com/secretflow/secretpad/blob/main/scripts/build/build.sh

大佬，你能再看下问题1490不

**Comment by 1139763082** [comment]
> > https://github.com/secretflow/secretpad/blob/main/scripts/build/build.sh
> 
> 大佬，你能再看下issues1490不

用的哪个分支的代码，麻烦发一下
