### ISSUE TITLE
利用secretflow allinone 部署secretpad0.9.0前后端源码页面打开异常

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1499]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretPad0.9

### OS Platform and Distribution

windows

### Python version

无

### What happend and What you expected to happen.

```shell
sercetpad前后端的版本都是0.9.0的，把前端的dist放到指定目录后部署，打不开页面
```

### Reproduction code to reproduce the issue.

```shell
111
```

**Comment by liusiqqq** [comment]
![368ac4cf13c7716d64a18f4e11c2ee3](https://github.com/user-attachments/assets/e6c455cb-82ef-4b53-a212-e2810cda5a9c)
前端的版本

**Comment by liusiqqq** [comment]
异常
![f85717e9fb602509be9b5ff90e097d2](https://github.com/user-attachments/assets/13dfca8b-59dd-4eb0-83d1-03c455168f2f)

**Comment by liusiqqq** [comment]
static目录中的结构
![image](https://github.com/user-attachments/assets/465bc35f-d82e-4345-82dd-2e56ba275362)

**Comment by liusiqqq** [comment]
打包镜像时用的命令是bash scripts/build/build_image.sh

**Comment by liusiqqq** [comment]
前端好多dist目录应该用哪个呀
![3d54d826b06ef27d377b6d0a959768d](https://github.com/user-attachments/assets/9a7c86b4-b205-436d-b1f9-a2e343de889f)

**Comment by BrainWH** [comment]
你好，dist目录换成platform下的试一下

**Comment by liusiqqq** [comment]
> 你好，dist目录换成platform下的试一下

谢谢，解决了
