### ISSUE TITLE
多方联邦学习

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/secretflow#1507]
您好，请问除了逻辑回归可以用混合联邦的形式实现外，还有哪些模型可以实现三方及以上联邦？是否有比较通用的方式实现多方联邦学习？

**Comment by 1139763082** [comment]
您好，麻烦问一下您那边是什么样的使用场景？

**Comment by zzx-QDU** [comment]
就是一般业务场景，需要支持多方联合训练。

**Comment by 1139763082** [comment]
> 就是一般业务场景，需要支持多方联合训练。
您是想了解下其它多方训练的算法么？还是想了解除了混合联邦之外有没有其它的训练形式（比如垂直联邦、水平联邦）支持多方训练。

**Comment by zzx-QDU** [comment]
是的，我看只有逻辑回归有混合联邦的方法。我想知道普通横向联邦和纵向联邦可以支持多方吗？

**Comment by 1139763082** [comment]
> 是的，我看只有逻辑回归有混合联邦的方法。我想知道普通横向联邦和纵向联邦可以支持多方吗？

可以的

**Comment by 1139763082** [comment]
> 就是一般业务场景，需要支持多方联合训练。

您是想了解下其它多方训练的算法么？还是想了解除了混合联邦之外有没有其它的训练形式（比如垂直联邦、水平联邦）支持多方训练。

**Comment by zzx-QDU** [comment]
我们主要是想了解普通的横向和纵向，特别是纵向如何实现多方联邦，因为文档里的例子基本上都是两方的。

**Comment by 1139763082** [comment]
> 我们主要是想了解普通的横向和纵向，特别是纵向如何实现多方联邦，因为文档里的例子基本上都是两方的。

可以支持的，稍等我给您找下之前跑的示例

**Comment by 1139763082** [comment]
> 我们主要是想了解普通的横向和纵向，特别是纵向如何实现多方联邦，因为文档里的例子基本上都是两方的。

官网上面的，加一个carol方就可以了
![image](https://github.com/user-attachments/assets/e0a5306c-4a15-436a-b241-34fec48a374e)

**Comment by zzx-QDU** [comment]
好的，感谢。
