### ISSUE TITLE
secretpad源码中配置文件里的kuscia含义

### ISSUE THREAD

**Issue by liusiqqq** [secretflow/secretflow#1509]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretPad0.9

### OS Platform and Distribution

windows

### Python version

无

### What happend and What you expected to happen.

```shell
application-dev中有一个root-kuscia-master，application-p2p中有一个root-kuscia-autonomy，这两个是干什么用的呢？在虚拟机中只运行了一个kuscia，这两个node可以共用一个kuscia吗？
```

### Reproduction code to reproduce the issue.

```shell
111
```

**Comment by liusiqqq** [comment]
就是这两个
![image](https://github.com/user-attachments/assets/c5e13589-4e34-4c11-9bc7-3f99f9478acd)
![image](https://github.com/user-attachments/assets/62872764-63aa-49da-b4f6-f36045a5e997)

**Comment by zimu-yuxi** [comment]
这是不同的部署方式，master是指kuscia是以中心化模式部署，autonomy是指kuscia是以P2P模式部署。node就是指的是kuscia容器，也就是你的secretpad连接的kuscia容器

**Comment by liusiqqq** [comment]
> 这是不同的部署方式，master是指kuscia是以中心化模式部署，autonomy是指kuscia是以P2P模式部署。node就是指的是kuscia容器，也就是你的secretpad连接的kuscia容器

那为什么我用p2p模式部署仍然要配置master的kuscia呢，不然会报错

**Comment by zimu-yuxi** [comment]
没有明白什么意思。您是指kuscia是P2P部署的方式，secretpad连接kuscia的配置信息必须配置master信息，才可以？那么想要确认以下几个问题：
1.master的host配置的是哪个kuscia容器的ip：port呢？
2.如何起的secretpad容器，本地源码还是自己打了镜像，然后使用allinone脚本部署
3.如果是本地源码启动，是否参考[这里](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.10.1b0/development/ru_in_idea_cn#secretpad)根据部署模式的不同来修改参数？
4.如果是自己打了secretpad镜像，源码有做哪些修改？

**Comment by liusiqqq** [comment]
> 没有明白什么意思。您是指kuscia是P2P部署的方式，secretpad连接kuscia的配置信息必须配置master信息，才可以？那么想要确认以下几个问题： 1.master的host配置的是哪个kuscia容器的ip：port呢？ 2.如何起的secretpad容器，本地源码还是自己打了镜像，然后使用allinone脚本部署 3.如果是本地源码启动，是否参考[这里](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.10.1b0/development/ru_in_idea_cn#secretpad)根据部署模式的不同来修改参数？ 4.如果是自己打了secretpad镜像，源码有做哪些修改？

就是这个意思，p2p也要配置master，不然报错。本地源码启动，就是按文档里操作的，目前就是虚拟机里启动了一个kuscia，master和autonomy都配置的是虚拟机里的同一个kuscia

**Comment by liusiqqq** [comment]
dev的配置：
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:sqlite:./db/secretpad.sqlite

springdoc:
  api-docs:
    enabled: true

secretpad:
  platform-type: AUTONOMY    # CENTER  EDGE  AUTONOMY
  deploy-mode: ${DEPLOY_MODE:ALL-IN-ONE} # MPC TEE ALL-IN-ONE
  node-id: ${NODE_ID:kuscia-system} # install.sh -n
  gateway: ${KUSCIA_GW_ADDRESS:127.0.0.1:9001} # install.sh -q envoy port (used in autonomy or master or edge mode)
  logs:
    path: ../log

kuscia:
  nodes:
    - domainId: ${NODE_ID:kuscia-system}
      mode: master
      host: ${KUSCIA_API_ADDRESS:192.168.200.214}
      port: ${KUSCIA_API_PORT:40896}
      protocol: ${KUSCIA_PROTOCOL:notls}
      cert-file: config/certs/client.crt
      key-file: config/certs/client.pem
      token: config/certs/token

    - domainId: alice
      mode: lite
      host: ${KUSCIA_API_LITE_ALICE_ADDRESS:root-kuscia-lite-alice}
      port: ${KUSCIA_API_PORT:8083}
      protocol: ${KUSCIA_PROTOCOL:tls}
      cert-file: config/certs/alice/client.crt
      key-file: config/certs/alice/client.pem
      token: config/certs/alice/token

    - domainId: bob
      mode: lite
      host: ${KUSCIA_API_LITE_BOB_ADDRESS:root-kuscia-lite-bob}
      port: ${KUSCIA_API_PORT:8083}
      protocol: ${KUSCIA_PROTOCOL:tls}
      cert-file: config/certs/bob/client.crt
      key-file: config/certs/bob/client.pem
      token: config/certs/bob/token

**Comment by liusiqqq** [comment]
p2p的配置：
spring:
  flyway:
    baseline-on-migrate: true
    locations:
      - filesystem:./config/schema/p2p

secretpad:
  deploy-mode: ${DEPLOY_MODE:MPC} # MPC TEE ALL-IN-ONE
  platform-type: AUTONOMY
  node-id: ${NODE_ID}
  center-platform-service: secretpad.master.svc
  p2p-platform-service: secretpad
  auth:
    enabled: true
  data:
    host-path: ${HOST_PATH}
    dir-path: /app/data/
  datasync:
    center: false
    p2p: true
    # fastFailedPolicy :   Throw an exception, log it, and don't try again
    # retryPolicy      :   Keep trying until you succeed
    retry: fastFailedPolicy

kuscia:
  nodes:
    - domainId: ${NODE_ID}
      mode: p2p
      host: ${KUSCIA_API_ADDRESS:192.168.200.214}
      port: ${KUSCIA_API_PORT:40896}
      protocol: ${KUSCIA_PROTOCOL:notls}
      cert-file: config/certs/client.crt
      key-file: config/certs/client.pem
      token: config/certs/token

data:
  sync:
    - org.secretflow.secretpad.persistence.entity.ProjectDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphNodeDO
    - org.secretflow.secretpad.persistence.entity.ProjectJobDO
    - org.secretflow.secretpad.persistence.entity.ProjectDatatableDO
    - org.secretflow.secretpad.persistence.entity.VoteRequestDO
    - org.secretflow.secretpad.persistence.entity.VoteInviteDO
    - org.secretflow.secretpad.persistence.entity.ProjectApprovalConfigDO
    - org.secretflow.secretpad.persistence.entity.ProjectNodeDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphNodeKusciaParamsDO
    - org.secretflow.secretpad.persistence.entity.ProjectModelServingDO
    - org.secretflow.secretpad.persistence.entity.ProjectModelPackDO
    - org.secretflow.secretpad.persistence.entity.ProjectFeatureTableDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphDomainDatasourceDO

# path which do not use in this mode ,config this mvc return 404 to user
# @see DynamicBeanRegisterInit
unregister-mapping:
  path:
    - /sync
    - /api/v1alpha1/user/node/resetPassword
    - /api/v1alpha1/user/remote/resetPassword
    - /api/v1alpha1/project/inst/add
    - /api/v1alpha1/project/node/add
    - /api/v1alpha1/project/delete
    - /api/v1alpha1/approval/pull/status
    - /api/v1alpha1/vote_sync/create
    - /api/v1alpha1/datatable/pushToTee
    - /api/v1alpha1/project/create
    - /api/v1alpha1/project/list
    - /api/v1alpha1/project/update
    - /api/v1alpha1/project/tee/list
    - /api/v1alpha1/node/create
    - /api/v1alpha1/node/delete
    - /api/v1alpha1/node/newToken
    - /api/v1alpha1/node/refresh
    - /api/v1alpha1/node/token
    - /api/v1alpha1/node/page
    - /api/v1alpha1/nodeRoute/delete
    - /api/v1alpha1/nodeRoute/listNode

#the path in p2p mode will not be interception,let go
white-list:
  paths:
    - /api/v1alpha1/p2p/node/delete
    - /api/v1alpha1/p2p/project/update
    - /api/v1alpha1/graph/list
    - /api/v1alpha1/project/get
    - /api/v1alpha1/project/job/list
    - /api/v1alpha1/project/job/get
    - /api/v1alpha1/project/datatable/get
    - /api/v1alpha1/project/job/task/output
    - /api/v1alpha1/project/job/task/logs
    - /api/v1alpha1/data/create
    - /api/v1alpha1/datatable/list
    - /api/v1alpha1/graph/node/status
    - /api/v1alpha1/graph/detail
    - /api/v1alpha1/graph/node/output
    - /api/v1alpha1/graph/node/logs

**Comment by liusiqqq** [comment]
p2p的配置：
spring:
  flyway:
    baseline-on-migrate: true
    locations:
      - filesystem:./config/schema/p2p

secretpad:
  deploy-mode: ${DEPLOY_MODE:MPC} # MPC TEE ALL-IN-ONE
  platform-type: AUTONOMY
  node-id: ${NODE_ID}
  center-platform-service: secretpad.master.svc
  p2p-platform-service: secretpad
  auth:
    enabled: true
  data:
    host-path: ${HOST_PATH}
    dir-path: /app/data/
  datasync:
    center: false
    p2p: true
    # fastFailedPolicy :   Throw an exception, log it, and don't try again
    # retryPolicy      :   Keep trying until you succeed
    retry: fastFailedPolicy

kuscia:
  nodes:
    - domainId: ${NODE_ID}
      mode: p2p
      host: ${KUSCIA_API_ADDRESS:192.168.200.214}
      port: ${KUSCIA_API_PORT:40896}
      protocol: ${KUSCIA_PROTOCOL:notls}
      cert-file: config/certs/client.crt
      key-file: config/certs/client.pem
      token: config/certs/token

data:
  sync:
    - org.secretflow.secretpad.persistence.entity.ProjectDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphNodeDO
    - org.secretflow.secretpad.persistence.entity.ProjectJobDO
    - org.secretflow.secretpad.persistence.entity.ProjectDatatableDO
    - org.secretflow.secretpad.persistence.entity.VoteRequestDO
    - org.secretflow.secretpad.persistence.entity.VoteInviteDO
    - org.secretflow.secretpad.persistence.entity.ProjectApprovalConfigDO
    - org.secretflow.secretpad.persistence.entity.ProjectNodeDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphNodeKusciaParamsDO
    - org.secretflow.secretpad.persistence.entity.ProjectModelServingDO
    - org.secretflow.secretpad.persistence.entity.ProjectModelPackDO
    - org.secretflow.secretpad.persistence.entity.ProjectFeatureTableDO
    - org.secretflow.secretpad.persistence.entity.ProjectGraphDomainDatasourceDO
# path which do not use in this mode ,config this mvc return 404 to user
# @see DynamicBeanRegisterInit
unregister-mapping:
  path:
    - /sync
    - /api/v1alpha1/user/node/resetPassword
    - /api/v1alpha1/user/remote/resetPassword
    - /api/v1alpha1/project/inst/add
    - /api/v1alpha1/project/node/add
    - /api/v1alpha1/project/delete
    - /api/v1alpha1/approval/pull/status
    - /api/v1alpha1/vote_sync/create
    - /api/v1alpha1/datatable/pushToTee
    - /api/v1alpha1/project/create
    - /api/v1alpha1/project/list
    - /api/v1alpha1/project/update
    - /api/v1alpha1/project/tee/list
    - /api/v1alpha1/node/create
    - /api/v1alpha1/node/delete
    - /api/v1alpha1/node/newToken
    - /api/v1alpha1/node/refresh
    - /api/v1alpha1/node/token
    - /api/v1alpha1/node/page
    - /api/v1alpha1/nodeRoute/delete
    - /api/v1alpha1/nodeRoute/listNode

#the path in p2p mode will not be interception,let go
white-list:
  paths:
    - /api/v1alpha1/p2p/node/delete
    - /api/v1alpha1/p2p/project/update
    - /api/v1alpha1/graph/list
    - /api/v1alpha1/project/get
    - /api/v1alpha1/project/job/list
    - /api/v1alpha1/project/job/get
    - /api/v1alpha1/project/datatable/get
    - /api/v1alpha1/project/job/task/output
    - /api/v1alpha1/project/job/task/logs
    - /api/v1alpha1/data/create
    - /api/v1alpha1/datatable/list
    - /api/v1alpha1/graph/node/status
    - /api/v1alpha1/graph/detail
    - /api/v1alpha1/graph/node/output
    - /api/v1alpha1/graph/node/logs

**Comment by zimu-yuxi** [comment]
> dev的配置： spring: jpa: show-sql: false properties: hibernate: format_sql: false datasource: url: jdbc:sqlite:./db/secretpad.sqlite
> 
> springdoc: api-docs: enabled: true
> 
> secretpad: platform-type: AUTONOMY # CENTER EDGE AUTONOMY deploy-mode: ${DEPLOY_MODE:ALL-IN-ONE} # MPC TEE ALL-IN-ONE node-id: ${NODE_ID:kuscia-system} # install.sh -n gateway: ${KUSCIA_GW_ADDRESS:127.0.0.1:9001} # install.sh -q envoy port (used in autonomy or master or edge mode) logs: path: ../log
> 
> kuscia: nodes: - domainId: ${NODE_ID:kuscia-system} mode: master host: ${KUSCIA_API_ADDRESS:192.168.200.214} port: ${KUSCIA_API_PORT:40896} protocol: ${KUSCIA_PROTOCOL:notls} cert-file: config/certs/client.crt key-file: config/certs/client.pem token: config/certs/token
> 
> ```
> - domainId: alice
>   mode: lite
>   host: ${KUSCIA_API_LITE_ALICE_ADDRESS:root-kuscia-lite-alice}
>   port: ${KUSCIA_API_PORT:8083}
>   protocol: ${KUSCIA_PROTOCOL:tls}
>   cert-file: config/certs/alice/client.crt
>   key-file: config/certs/alice/client.pem
>   token: config/certs/alice/token
> 
> - domainId: bob
>   mode: lite
>   host: ${KUSCIA_API_LITE_BOB_ADDRESS:root-kuscia-lite-bob}
>   port: ${KUSCIA_API_PORT:8083}
>   protocol: ${KUSCIA_PROTOCOL:tls}
>   cert-file: config/certs/bob/client.crt
>   key-file: config/certs/bob/client.pem
>   token: config/certs/bob/token
> ```

如果是按照官网文档增加启动参数dev，那么你需要修改application-dev的配置，kuscia的配置信息以p2p的配置来搞，你需要先明确这点

**Comment by liusiqqq** [comment]
> > dev的配置： spring: jpa: show-sql: false properties: hibernate: format_sql: false datasource: url: jdbc:sqlite:./db/secretpad.sqlite
> > springdoc: api-docs: enabled: true
> > secretpad: platform-type: AUTONOMY # CENTER EDGE AUTONOMY deploy-mode: ${DEPLOY_MODE:ALL-IN-ONE} # MPC TEE ALL-IN-ONE node-id: ${NODE_ID:kuscia-system} # install.sh -n gateway: ${KUSCIA_GW_ADDRESS:127.0.0.1:9001} # install.sh -q envoy port (used in autonomy or master or edge mode) logs: path: ../log
> > kuscia: nodes: - domainId: ${NODE_ID:kuscia-system} mode: master host: ${KUSCIA_API_ADDRESS:192.168.200.214} port: ${KUSCIA_API_PORT:40896} protocol: ${KUSCIA_PROTOCOL:notls} cert-file: config/certs/client.crt key-file: config/certs/client.pem token: config/certs/token
> > ```
> > - domainId: alice
> >   mode: lite
> >   host: ${KUSCIA_API_LITE_ALICE_ADDRESS:root-kuscia-lite-alice}
> >   port: ${KUSCIA_API_PORT:8083}
> >   protocol: ${KUSCIA_PROTOCOL:tls}
> >   cert-file: config/certs/alice/client.crt
> >   key-file: config/certs/alice/client.pem
> >   token: config/certs/alice/token
> > 
> > - domainId: bob
> >   mode: lite
> >   host: ${KUSCIA_API_LITE_BOB_ADDRESS:root-kuscia-lite-bob}
> >   port: ${KUSCIA_API_PORT:8083}
> >   protocol: ${KUSCIA_PROTOCOL:tls}
> >   cert-file: config/certs/bob/client.crt
> >   key-file: config/certs/bob/client.pem
> >   token: config/certs/bob/token
> > ```
> 
> 如果是按照官网文档增加启动参数dev，那么你需要修改application-dev的配置，kuscia的配置信息以p2p的配置来搞，你需要先明确这点

这个怎么改下啊，大佬

**Comment by zimu-yuxi** [comment]
参考P2P的配置改下

**Comment by liusiqqq** [comment]
> 参考P2P的配置改下

文档中只说了改这两个地方，还有其他地方需要改吗？
![image](https://github.com/user-attachments/assets/910987e9-b076-4a7e-8459-1399bd41272d)

**Comment by zimu-yuxi** [comment]
kuscia node里的mode改成P2P

**Comment by liusiqqq** [comment]
> kuscia node里的mode改成P2P

大佬，这里的对方ip是什么意思？是另一个节点的ip吗？端口就是-g参数的端口吗？
![image](https://github.com/user-attachments/assets/81f342c6-1e49-4bf7-965b-653a1888334c)

**Comment by zimu-yuxi** [comment]
kuscia的

**Comment by liusiqqq** [comment]
> kuscia的

我看前面是gateway,注释里写的是env，那么端口是-p参数的还是-q参数的呀

**Comment by zimu-yuxi** [comment]
q，文档可能存在描述不准确问题，我们内部看下如何优化掉
