### ISSUE TITLE
spuruntime 和spu类之间的关系，区别和含义

### ISSUE THREAD

**Issue by Afive233** [secretflow/secretflow#1512]
### Issue Type

Others

### Source

source

### Secretflow Version

0.6.13b0

### OS Platform and Distribution

ubantu 18.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
不太懂spuruntime 和spu类之间的关系，区别和含义。发现它们两者有同名的方法，成员，请
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by lanyy9527** [comment]
spuruntime运行时主要负责管理spu的生命周期，而spu类主要是负责具体的安全计算；
