### ISSUE TITLE
非平衡求交，使用dokcer部署后，执行ray命令，提示未找到命令

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#1523]
### Issue Type

Bug

### Source

binary

### Secretflow Version

使用docker方式按latest方式安装的secretflow

### OS Platform and Distribution

麒麟V10

### Python version

3.10.13   docker方式安装

### What happend and What you expected to happen.

```shell
国庆节前，通过docker方式部署的secretflow，并且执行非平衡脚本offline和online都可以正常完成。
昨天，再次执行ray命令时，就报未找到指令。
以为是环境出了什么问题，然后又在另外两台服务器上使用docker重新部署了secretflow，其中一台可以使用ray命令正常启动。另一台还是报未找到指令，请问是什么原因导致的？如何解决？
```

### Reproduction code to reproduce the issue.

```shell
执行的ray命令：ray start --head --node-ip-address="10.2.11.72" --port="3156" --resources='{"carol":16}' --include-dashboard=False --disable-usage-stats
```

**Comment by wjwJack** [comment]
![1728453610482](https://github.com/user-attachments/assets/63e232c0-888f-4466-8fdb-2bf07b330123)
上图为节前部署好能正常运行非平衡脚本的服务器上，启动ray时的报错。

下图为重新使用dokcer部署secretflow，启动ray时的报错。
![图片](https://github.com/user-attachments/assets/2b1cec83-1759-4755-a0bc-228e2c9aa1d2)

**Comment by zimu-yuxi** [comment]
docker运行镜像方式，确认下你是否在dock儿容器内呢？

**Comment by wjwJack** [comment]
> docker运行镜像方式，确认下你是否在dock儿容器内呢？

嗯，是在dokcer容器内运行的ray命令。

**Comment by wjwJack** [comment]
因为前后测试了四台服务器，在dokcer容器内运行ray命令时没问题的。后来我退出dokcer容器，然后重新进入容器，又可以了，感觉稳定性存疑。

**Comment by zimu-yuxi** [comment]
> 因为前后测试了四台服务器，在dokcer容器内运行ray命令时没问题的。后来我退出dokcer容器，然后重新进入容器，又可以了，感觉稳定性存疑。

‘在docker容器内运行ray命令没有问题，退出重进又可以了’ 没有很明白什么意思，可以再描述下吗？

**Comment by wjwJack** [comment]
> > 因为前后测试了四台服务器，在dokcer容器内运行ray命令时没问题的。后来我退出dokcer容器，然后重新进入容器，又可以了，感觉稳定性存疑。
> 
> ‘在docker容器内运行ray命令没有问题，退出重进又可以了’ 没有很明白什么意思，可以再描述下吗？

在docker容器内执行ray命令报未找到命令后，执行了exit命令退出当前容器，然后再执行docker exec -it 容器id /bin/bash进入容器，再执行ray命令，正常了。

**Comment by wjwJack** [comment]
现在ray的问题算暂时解决了，能帮忙看看这个问题吗？  @zimu-yuxi  
![f1e4d7c3779a789db492df064a1866a](https://github.com/user-attachments/assets/0cb97ce0-f799-4543-b12e-ba9f9c5f37b3)
我在单台机器上已完成非平衡求交，但在两台服务器上卡在这了

**Comment by zimu-yuxi** [comment]
1.两台机器通信是否正常
2.代码配置提供一下

**Comment by wangzul** [comment]
用的是哪一个镜像
secretflow-anolis8:latest
secretflow-lite-anolis8:latest

**Comment by wjwJack** [comment]
> 用的是哪一个镜像 secretflow-anolis8:latest secretflow-lite-anolis8:latest

装了有一段时间了，记不太清了，大概率是secretflow-anolis8:latest，如果有方法可以验证的话，我可以试试。

**Comment by wjwJack** [comment]
> 1.两台机器通信是否正常 2.代码配置提供一下
下图为两台服务器的通信验证，是不是有问题？
![图片](https://github.com/user-attachments/assets/fcb9fb95-3e18-449c-abb3-cd63fb32335c)

创建镜像时的命令，看看有问题吗？  命令：docker run -it --network=host -p 3255:3255 -p 3256:3256 -p 12946:12946 -p 12947:12947  -p 3155:3155 -p 3156:3156 -p 3355:3355 -p 3356:3356 -p 13946:13946 -p 13947:13947  -p 3157:3157 -p 3158:3158 -p 3055:3055 -p 3056:3056 -p 3057:3057 -p 3058:3058 -p 3059:3059 -p 3060:3060 -p 3061:3061 -p 3062:3062 sf_fei /bin/bash

执行的两个offline脚本:
[bob_offline_wjw_71 - 副本.txt](https://github.com/user-attachments/files/17320973/bob_offline_wjw_71.-.txt)
[carol_offline_wjw_75 - 副本.txt](https://github.com/user-attachments/files/17320974/carol_offline_wjw_75.-.txt)

**Comment by zimu-yuxi** [comment]
截图看不清楚，在容器内telnet看下双方端口是否可访问。

**Comment by wjwJack** [comment]
> 截图看不清楚，在容器内telnet看下双方端口是否可访问。

容器内telnet命令报没有，我在容器外宿主机上telnet的
![3801002f8a014cd66b21c4fd887286e](https://github.com/user-attachments/assets/cd86482c-5a58-4f31-be8e-0cc26794a60f)

**Comment by zimu-yuxi** [comment]
看你关闭了防火墙，重新再跑下

**Comment by wjwJack** [comment]
> 看你关闭了防火墙，重新再跑下

关闭防火墙后，跑了下offline脚本，通过了，跑online脚本时，两台服务器都报这个错：
![4fd9a11c04756f2c05553c70b5310b2](https://github.com/user-attachments/assets/56d77ac8-f3f6-4b12-9833-7dbfe6262895)


[bob_online_wjw_71 - 副本.txt](https://github.com/user-attachments/files/17321448/bob_online_wjw_71.-.txt)
[carol_online_wjw_75 - 副本.txt](https://github.com/user-attachments/files/17321449/carol_online_wjw_75.-.txt)

**Comment by wjwJack** [comment]
关闭防火墙后，offline和online脚本都执行完成了，谢谢

**Comment by zimu-yuxi** [comment]
> > 用的是哪一个镜像 secretflow-anolis8:latest secretflow-lite-anolis8:latest
> 
> 装了有一段时间了，记不太清了，大概率是secretflow-anolis8:latest，如果有方法可以验证的话，我可以试试。

方便在容器内secretflow -v看下吗？

**Comment by wjwJack** [comment]
> > > 用的是哪一个镜像 secretflow-anolis8:latest secretflow-lite-anolis8:latest
> > 
> > 
> > 装了有一段时间了，记不太清了，大概率是secretflow-anolis8:latest，如果有方法可以验证的话，我可以试试。
> 
> 方便在容器内secretflow -v看下吗？

没问题，看了下版本是1.9.0b1
![e19a2117d063496a63ea9854ec53a02](https://github.com/user-attachments/assets/49dd553b-e530-45f9-94e2-95cc364bd09a)
