### ISSUE TITLE
关于Split Learning的使用，能否提供一个基于pytorch实现的base_model和fuse_model的示例

### ISSUE THREAD

**Issue by kylin5207** [secretflow/secretflow#1526]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 1.9.2b0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### What happend and What you expected to happen.

Split Learning目前只有tensorflow定义模型的示例，能否提供pytorch的demo呢？

**Comment by BrainWH** [comment]
你好，可以参照https://github.com/secretflow/secretflow/blob/main/tests/ml/nn/sl/test_sl_model_torch.py

**Comment by kylin5207** [comment]
Thanks
