### ISSUE TITLE
在同一虚拟机上P2P部署两个节点，在secretpad allinone上合作，通讯状态不可用

### ISSUE THREAD

**Issue by o7s4** [secretflow/secretflow#1528]
### Issue Type

Bug

### Source

binary

### Secretflow Version

 SecretPad All In One v1.9.0b2

### OS Platform and Distribution

Ubuntu 24.04.1

### Python version

无

### What happend and What you expected to happen.

```shell
根据文档，在同一虚拟机上P2P部署两个节点sh install.sh autonomy -n alice -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls，在secretpad上合作，通讯状态不可用
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by o7s4** [comment]
![9bf91f8244a1c4ed93d6b0f233c18da](https://github.com/user-attachments/assets/8e02e45d-85f7-4806-8bbf-3998835b11b5)
![8170ca206ac710a63fd73476045b76a](https://github.com/user-attachments/assets/bc7e4504-5c07-440d-8c69-9e5409d0e62f)
![470961b7af125bda30b83e5ee49dc0f](https://github.com/user-attachments/assets/a1708cbb-841e-4d9c-bf46-8c9dc8c754a9)
![a84e6c1b986757cb601570b784887c4](https://github.com/user-attachments/assets/00233ac4-890e-4acc-b7de-a7440f1c9a22)

**Comment by o7s4** [comment]
不清楚这个通讯地址要如何设置

**Comment by BrainWH** [comment]
你好，合作节点通讯地址端口是由启动节点的-p参数设置的
p:参数传递的是 lite/autonomy 容器 kuscia-gateway 映射到主机的端口，保证和主机上现有的端口不冲突即可
k:参数传递的是 lite/autonomy 容器 Kuscia-api 映射到主机的 HTTP/HTTPS 端口，保证和主机上现有的端口不冲突即可
g:参数传递的是 lite/autonomy 容器 Kuscia-grpc 映射到主机的 HTTP/HTTPS 端口，保证和主机上现有的端口不冲突即可
s:secretpad平台端口，保证和主机上现有的端口不冲突即可
