### ISSUE TITLE
SecretPad新增节点添加数据提交报错

### ISSUE THREAD

**Issue by hallowsman** [secretflow/secretflow#1529]
### Issue Type

Bug

### Source

binary

### Secretflow Version

Secretflow 1.8.0

### OS Platform and Distribution

 Ubuntu 22.04 LTS (GNU/Linux 6.5.13-5-pve x86_64)

### Python version

Python 3.10.12

### What happend and What you expected to happen.

```shell
1 在10.0.0.175部署了中心化Center平台。
2 添加节点third
3 在10.0.0.27部署新节点执行命令
bash install.sh lite -n sufqwrjg -m 'https://10.0.0.175:18080' -t  YGpL5dmLtUt7ZR6ndnze8E9dNluKj37j -p 10080 -s 8180 -k 41802 -g 40803 -q 13081 -P tls
4 部署成功以后，添加数据源，按照文档里面的haha-alice.csv这个文件是哪里来的？是把以前的alice.csv直接改名字吗？
5我改名字以后，提交，提示读取到的特征名称不对
```

### Reproduction code to reproduce the issue.

```shell
1 在10.0.0.175部署了中心化Center平台。
2 添加节点third
3 在10.0.0.27部署新节点执行命令
bash install.sh lite -n sufqwrjg -m 'https://10.0.0.175:18080' -t  YGpL5dmLtUt7ZR6ndnze8E9dNluKj37j -p 10080 -s 8180 -k 41802 -g 40803 -q 13081 -P tls
4 部署成功以后，添加数据源，按照文档里面的haha-alice.csv这个文件是哪里来的？是把以前的alice.csv直接改名字吗？
5我改名字以后，提交，提示读取到的特征名称不对
```

**Comment by hallowsman** [comment]
<img width="623" alt="c13e308d99bacb1c5c5c1d6a95f2ff8" src="https://github.com/user-attachments/assets/a2eb7b49-cb6e-4cc2-b423-9c5477c63ae6">

**Comment by hallowsman** [comment]
![image](https://github.com/user-attachments/assets/ad69e25f-ecfd-4023-bcd8-e3b26472b453)

**Comment by lanyy9527** [comment]
1. haha-alice 只是自定义的文件名称（这个地方用的是内置的数据），可以替换成自己的psi文件；
2. psi数据中，header字段不能出现空格；

**Comment by hallowsman** [comment]
[data-sync.log](https://github.com/user-attachments/files/17339363/data-sync.log)
[error.log](https://github.com/user-attachments/files/17339365/error.log)
[secretpad.log](https://github.com/user-attachments/files/17339366/secretpad.log)
