### ISSUE TITLE
spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice') error

### ISSUE THREAD

**Issue by wangwen1024** [secretflow/secretflow#154]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.18.13

### Bazel version

docker

### GCC/Compiler version

11.2.0

### What happend and What you expected to happen.

```shell
>>> spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice')
(scheduler +6m9s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +6m9s) Error: No available node types can fulfill resource request {'alice': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +6m44s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +6m44s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +7m19s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +7m19s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +7m54s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +7m54s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +8m29s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +8m29s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +9m4s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +9m4s) Error: No available node types can fulfill resource request {'alice': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +9m39s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +9m39s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +10m14s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +10m14s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +10m49s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +10m49s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'alice': 1.0}. Add suitable node types to this cluster to resolve this issue.
```

### Reproduction code to reproduce the issue.

```shell
spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice') error，我想运行一个隐私求交运算但是无法得到结果，会一直卡住并且提示一些错误信息。
```

**Comment by miluoalbert** [comment]
Hi, @wangwen1024 

看错误提示，应该是使用`sf.SPU()`创建spu时，传入的cluster_def参数中要求了'alice'和'bob'节点。但`sf.init()`时没有创建对应名称的节点，导致一直查找不到对应node。

**Comment by wangwen1024** [comment]
当我sf.init()之后，
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 739, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 227, in psi_csv
    return ray.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=414, ip=172.17.0.6, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f2b848df3d0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 442, in psi_csv
    report = psi.bucket_psi(self.link, config)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 39, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString())
RuntimeError: what: 
	[Enforce fail at spu/psi/bucket_psi.cc:183] ec.value() == 0. failed to create output dir=/data/secretflow for path=/data/secretflow/docker, reason = No such file or directory
stacktrace: 
#0 spu::psi::BucketPsi::BucketPsi()+0x7f2bed5f331f
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f2bec3d677d
#2 pybind11::cpp_function::dispatcher()+0x7f2bec3bb552
#3 cfunction_call_varargs+0x561ed697a00e
>>> 2022-10-17 11:42:16,781	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.psi_csv() (pid=415, ip=172.17.0.6, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f9e1c108340>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 442, in psi_csv
    report = psi.bucket_psi(self.link, config)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 39, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString())
RuntimeError: what: 
	[Enforce fail at spu/psi/bucket_psi.cc:183] ec.value() == 0. failed to create output dir=/data/secretflow for path=/data/secretflow/docker, reason = No such file or directory
stacktrace: 
#0 spu::psi::BucketPsi::BucketPsi()+0x7f9e7271531f
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9e714f877d
#2 pybind11::cpp_function::dispatcher()+0x7f9e714dd552
#3 cfunction_call_varargs+0x55a985c6000e
提示我failed to create output dir=/data/secretflow for path=/data/secretflow/docker, reason = No such file or directory
但是我是有这个目录的

**Comment by miluoalbert** [comment]
Hi,

这里的路径是节点侧的路径，需要检查运行节点的docker中有对应路径吗？

**Comment by wangwg1** [comment]
你这个就是在 cluster_def 定义前面缺少：sf.init(address='ip:port')

**Comment by mingo0117** [comment]
求教个问题：
spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice') 
这个相对于上一版，接口变化了，必须指定一个receiver（如alice）？
意思是求交结果只能一方看到么？如果每一方都要看到呢？

**Comment by oeqqwq** [comment]
> 求教个问题：
spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice')
这个相对于上一版，接口变化了，必须指定一个receiver（如alice）？
意思是求交结果只能一方看到么？如果每一方都要看到呢？

Hi，
psi_csv额外有参数`broadcast_result`可以控制求交结果是否每一方都能收到，具体你可以参考文档https://secretflow.readthedocs.io/zh_CN/latest/source/secretflow.device.device.html#secretflow.device.device.spu.SPU.psi_csv
或者查看代码中psi_csv接口的注释

**Comment by mingo0117** [comment]
> > 求教个问题：
> > spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice')
> > 这个相对于上一版，接口变化了，必须指定一个receiver（如alice）？
> > 意思是求交结果只能一方看到么？如果每一方都要看到呢？
> 
> Hi， psi_csv额外有参数`broadcast_result`可以控制求交结果是否每一方都能收到，具体你可以参考文档https://secretflow.readthedocs.io/zh_CN/latest/source/secretflow.device.device.html#secretflow.device.device.spu.SPU.psi_csv 或者查看代码中psi_csv接口的注释

好的，只是感觉receiver这个设计成必传有点奇怪。receiver传了，broadcast_result默认为true，多方都能收到

**Comment by oeqqwq** [comment]
> > > 求教个问题：
> > > spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice')
> > > 这个相对于上一版，接口变化了，必须指定一个receiver（如alice）？
> > > 意思是求交结果只能一方看到么？如果每一方都要看到呢？
> > 
> > 
> > Hi， psi_csv额外有参数`broadcast_result`可以控制求交结果是否每一方都能收到，具体你可以参考文档https://secretflow.readthedocs.io/zh_CN/latest/source/secretflow.device.device.html#secretflow.device.device.spu.SPU.psi_csv 或者查看代码中psi_csv接口的注释
> 
> 好的，只是感觉receiver这个设计成必传有点奇怪。receiver传了，broadcast_result默认为true，多方都能收到

receiver不仅仅只是是只是指定结果接收方，也有涉及到算法设计上的考虑，交互细节上会有一定区别，进一步可以参考相关算法的说明文档https://secretflow.readthedocs.io/zh_CN/latest/components/psi.html#kkrt16-psi
broadcast_result默认值为true则是基于训练下场景下的默认值

**Comment by mingo0117** [comment]
> > > > 求教个问题：
> > > > spu.psi_csv(['c1', 'c2'], input_path, output_path, 'alice')
> > > > 这个相对于上一版，接口变化了，必须指定一个receiver（如alice）？
> > > > 意思是求交结果只能一方看到么？如果每一方都要看到呢？
> > > 
> > > 
> > > Hi， psi_csv额外有参数`broadcast_result`可以控制求交结果是否每一方都能收到，具体你可以参考文档https://secretflow.readthedocs.io/zh_CN/latest/source/secretflow.device.device.html#secretflow.device.device.spu.SPU.psi_csv 或者查看代码中psi_csv接口的注释
> > 
> > 
> > 好的，只是感觉receiver这个设计成必传有点奇怪。receiver传了，broadcast_result默认为true，多方都能收到
> 
> receiver不仅仅只是是只是指定结果接收方，也有涉及到算法设计上的考虑，交互细节上会有一定区别，进一步可以参考相关算法的说明文档https://secretflow.readthedocs.io/zh_CN/latest/components/psi.html#kkrt16-psi broadcast_result默认值为true则是基于训练下场景下的默认值

谢谢，大概明白了

**Comment by anakinxc** [comment]
> 隐私求交这个功能，需要安装哪些组件？除了SecretFlow以外，SPU 需要安装吗？

SecretFlow 依赖 SPU，所以只用装 sf 就行。pip 会把所有的依赖都装上

**Comment by zhujinfang0819** [comment]
隐私求交支持逻辑求交吗，比如key值大于小于或者在某个范围里

**Comment by zhanglei486** [comment]
> 隐私求交支持逻辑求交吗，比如key值大于小于或者在某个范围里

spu目前实现的psi协议不支持逻辑求交，得到key值严格相等的交集
crypto2022 的论文[Structure-Aware Private Set Intersection, With Applications to Fuzzy Matching](https://eprint.iacr.org/2022/1011)  可以进行模糊匹配交集，有兴趣可以了解一下

**Comment by zhujinfang0819** [comment]
求交key值得内容是字符串的，报错了。是不支持字符串求交吗？中文也不支持？

**Comment by zhanglei486** [comment]
> 求交key值得内容是字符串的，报错了。是不支持字符串求交吗？中文也不支持？
支持字符串求交的，给的python示例中输入也是字符串
麻烦请参照提问模板贴一下出错的输入内容和报错信息，方便相关值班同学帮着一起分析问题

**Comment by zhujinfang0819** [comment]
Traceback (most recent call last):
  File "psi_test.py", line 10, in <module>
    spu.psi_csv('edu', input_path, output_path, 'bmw')
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 739, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 227, in psi_csv
    return ray.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=4952, ip=172.17.0.2, repr=<secretflow.device.device.spu.SPURuntime object at 0x7ef99f293310>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 442, in psi_csv
    report = psi.bucket_psi(self.link, config)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 39, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString())
RuntimeError: what: 
	[Enforce fail at spu/psi/utils/csv_checker.cc:137] duplicated_size == 0. found duplicated keys: undergraduate
stacktrace: 
#0 std::_Function_handler<>::_M_invoke()+0x7ef9fa711899
#1 std::__future_base::_State_baseV2::_M_do_set()+0x7ef9f97755ef
#2 __pthread_once_slow+0x7efc9fac2dd7
(secretflow) bash-4.4# 
(secretflow) bash-4.4#

**Comment by zhujinfang0819** [comment]
> Traceback (most recent call last): File "psi_test.py", line 10, in spu.psi_csv('edu', input_path, output_path, 'bmw') File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 739, in psi_csv return dispatch( File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch return _registrar.dispatch(self.device_type, name, self, *args, **kwargs) File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch return self._ops[device_type][name](*args, **kwargs) File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 227, in psi_csv return ray.get(res) File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper return func(*args, **kwargs) File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1843, in get raise value.as_instanceof_cause() ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=4952, ip=172.17.0.2, repr=<secretflow.device.device.spu.SPURuntime object at 0x7ef99f293310>) File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 442, in psi_csv report = psi.bucket_psi(self.link, config) File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 39, in bucket_psi report_str = _lib.libs.bucket_psi(link, config.SerializeToString()) RuntimeError: what: [Enforce fail at spu/psi/utils/csv_checker.cc:137] duplicated_size == 0. found duplicated keys: undergraduate stacktrace: #0 std::_Function_handler<>::_M_invoke()+0x7ef9fa711899 #1 std::__future_base::_State_baseV2::_M_do_set()+0x7ef9f97755ef #2 __pthread_once_slow+0x7efc9fac2dd7 (secretflow) bash-4.4# (secretflow) bash-4.4#


输入的数据是：
gender,age,edu,consume,income,annualincome,tel
male,48,undergraduate,50000,80000,960000,13900203903
male,20,high school,5000,10000,120000,13900203904
male,39,undergraduate,20000,30000,360000,13910872031

**Comment by oeqqwq** [comment]
> gender,age,edu,consume,income,annualincome,tel
male,48,undergraduate,50000,80000,960000,13900203903
male,20,high school,5000,10000,120000,13900203904
male,39,undergraduate,20000,30000,360000,13910872031

Hi,
目前PSI求交需要保证求交键值的唯一性，在你的数据中`undergraduate`重复了

**Comment by zhujinfang0819** [comment]
> > gender,age,edu,consume,income,annualincome,tel
> > male,48,undergraduate,50000,80000,960000,13900203903
> > male,20,high school,5000,10000,120000,13900203904
> > male,39,undergraduate,20000,30000,360000,13910872031
> 
> Hi, 目前PSI求交需要保证求交键值的唯一性，在你的数据中`undergraduate`重复了

好的。另外数据中有中文也不支持是吗？

**Comment by oeqqwq** [comment]
> > > gender,age,edu,consume,income,annualincome,tel
> > > male,48,undergraduate,50000,80000,960000,13900203903
> > > male,20,high school,5000,10000,120000,13900203904
> > > male,39,undergraduate,20000,30000,360000,13910872031
> > 
> > 
> > Hi, 目前PSI求交需要保证求交键值的唯一性，在你的数据中`undergraduate`重复了
> 
> 好的。另外数据中有中文也不支持是吗？

中文是支持的

**Comment by zhujinfang0819** [comment]
隐语提供隐匿查询功能吗？ 就是PIR技术

**Comment by zhanglei486** [comment]
> 隐语提供隐匿查询功能吗？ 就是PIR技术

SPU模块提供了SealPIR实现，可以用于IndexPIR
SPU模块提供了微软APSI(Labeled PSI)封装，可以用于keywordPIR

**Comment by zhujinfang0819** [comment]
> > 隐语提供隐匿查询功能吗？ 就是PIR技术
> 
> SPU模块提供了SealPIR实现，可以用于IndexPIR SPU模块提供了微软APSI(Labeled PSI)封装，可以用于keywordPIR

indexPIR 和keywordPIR 也要求key值或者index值不能重复吗？

**Comment by miluoalbert** [comment]
Hi, @zhanglei486 @zhujinfang0819 
单独建立了一个讨论PIR的issue #160 ，后续讨论可以移到这个issue
