### ISSUE TITLE
Shuffle和SortByKey protocol

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/secretflow#1550]
我在《SecretFlow-SCQL: A Secure Collaborative Query pLatform》这篇论文了解到scql实现了Shuffle和SortByKey protocol。我想问一下如果我想单独测试一下这两个协议，该如何进行呢，相关的函数代码在哪里呢

**Comment by tongke6** [comment]
duplicate with https://github.com/secretflow/scql/issues/383
