### ISSUE TITLE
关于secretflow通信机制的一点疑问

### ISSUE THREAD

**Issue by qiaoqiao321** [secretflow/secretflow#1551]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.6.13b0

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.10。13

### What happend and What you expected to happen.

```shell
对于secretflow通信机制的存在一些疑问，请问envoy代理和 domain route 之间的关系是怎么样的
特别是在两种组网模式的情况下，分别是怎么实现通信的呢。
中心组网模式下，是使用envoy作为代理，来将一个节点的请求转发给另一个节点吗
点对点组网模式下，是双方直接通信吗，那为什么两方都要部署envoy呢，是用来鉴权吗
```

### Reproduction code to reproduce the issue.

```shell
我对于secretflow通信机制非常好奇，有此疑问
```

**Comment by wangzul** [comment]
可以参考[kuscia](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/reference/architecture_cn#centralized)文档，相关组件的功能和不同组网模式运行状态。

**Comment by qiaoqiao321** [comment]
是的，我一直在阅读 kuscia 的文档，只是我对于其中关于通信的部分envoy部分并没有理解，故有此一问，我认为是否可以把通信的部分单独拎出来写，这样会更方便理解一些

**Comment by wangzul** [comment]
> 是的，我一直在阅读 kuscia 的文档，只是我对于其中关于通信的部分envoy部分并没有理解，故有此一问，我认为是否可以把通信的部分单独拎出来写，这样会更方便理解一些

收到你的建议了，我们会考虑优化这部分内容。
