### ISSUE TITLE
创建隐私求教任务，如何修改协议？如何创建隐匿查询任务。

### ISSUE THREAD

**Issue by yaoyizhuo** [secretflow/secretflow#1556]
### Issue Type

Others

### Source

source

### Secretflow Version

1.10

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
python新手
在此文档中 https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b0/tutorial/PSI_On_SPU
我创建了一个隐私求交任务，已经跑成功了。
1，我看文档支持三种隐私求交算法,spu.psi_csv(...)方法中，如何找到protocol的枚举类来替换自己的使用协议？

2，文档中没找得到隐匿查询的相关代码，如何使用python来创建一个本机的pir任务？找到spu.pir_setup和spu.pir_query方法，没看到文档中有调用的例子。
```

### Reproduction code to reproduce the issue.

```shell
python新手
在此文档中 https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b0/tutorial/PSI_On_SPU
我创建了一个隐私求交任务，已经跑成功了。
1，我看文档支持三种隐私求交算法,spu.psi_csv(...)方法中，如何找到protocol的枚举类来替换自己的使用协议？

2，文档中没找得到隐匿查询的相关代码，如何使用python来创建一个本机的pir任务？找到spu.pir_setup和spu.pir_query方法，没看到文档中有调用的例子。
```

**Comment by lanyy9527** [comment]
1. 可以在「[隐语PSI](https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.2b0/reference/psi_config#psitype)」中进行查看协议说明；
2. 暂时没有代码示例，可以先参考API来进行开发；

**Comment by yaoyizhuo** [comment]
> 1. 可以在「[隐语PSI](https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.2b0/reference/psi_config#psitype)」中进行查看协议说明；
> 2. 暂时没有代码示例，可以先参考API来进行开发；

可以在问一个嘛，，隐私求交，可以计算出差集吗？我现在看到只有求交集。

**Comment by lanyy9527** [comment]
> 可以在问一个嘛，，隐私求交，可以计算出差集吗？我现在看到只有求交集。

可以，配置advanced_join_type=ADVANCED_JOIN_TYPE_DIFFERENCE；
参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b0/source/secretflow#secretflow.SPU.psi

**Comment by yaoyizhuo** [comment]
> > 可以在问一个嘛，，隐私求交，可以计算出差集吗？我现在看到只有求交集。
> 
> 可以，配置advanced_join_type=ADVANCED_JOIN_TYPE_DIFFERENCE； 参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b0/source/secretflow#secretflow.SPU.psi

`sf.shutdown()

sf.init(parties=['alice', 'bob', 'carol'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))


input_path = {alice: './data/PIR-PSI用户数据A.csv', bob: './data/PSI-用户数据B.csv'}
output_path = {alice: './data/A.csv', bob: './data/B.csv'}
# spu.psi_csv('姓名', input_path, output_path, 'alice', protocol='RR22_FAST_PSI_2PC')

# protocol in ['PROTOCOL_ECDH', 'PROTOCOL_KKRT', 'PROTOCOL_RR22']
# 调用 PSI

keys = {
    'alice': ['姓名'],  # Alice 的数据集中的列名
    'bob': ['姓名']     # Bob 的数据集中的列名
}

spu.psi(
    keys=keys,  # 注意：这里是字符串列表，匹配 CSV 文件中的列名
    input_path=input_path,
    output_path=output_path,
    receiver='alice',  # 指定谁可以收到结果
    protocol='PROTOCOL_RR22',  # 使用的 PSI 协议
    advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN"  # 使用交集连接
)`

这段代码运行报错,KeyError: 'alice'...
<img width="1477" alt="image" src="https://github.com/user-attachments/assets/882065ee-2f10-4f65-9408-7c9f7eb79c15">

**Comment by yaoyizhuo** [comment]
> > 可以在问一个嘛，，隐私求交，可以计算出差集吗？我现在看到只有求交集。
> 
> 可以，配置advanced_join_type=ADVANCED_JOIN_TYPE_DIFFERENCE； 参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b0/source/secretflow#secretflow.SPU.psi

sf.shutdown()

sf.init(parties=['alice', 'bob', 'carol'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))


input_path = {alice: './data/PIR-PSI用户数据A.csv', bob: './data/PSI-用户数据B.csv'}
output_path = {alice: './data/A.csv', bob: './data/B.csv'}
# spu.psi_csv('姓名', input_path, output_path, 'alice', protocol='RR22_FAST_PSI_2PC')

# protocol in ['PROTOCOL_ECDH', 'PROTOCOL_KKRT', 'PROTOCOL_RR22']
# 调用 PSI
keys = {
    'alice': ['姓名'],  # Alice 的数据集中的列名
    'bob': ['姓名']     # Bob 的数据集中的列名
}

spu.psi(
    keys=keys,  # 注意：这里是字符串列表，匹配 CSV 文件中的列名
    input_path=input_path,
    output_path=output_path,
    receiver='alice',  # 指定谁可以收到结果
    protocol='PROTOCOL_RR22',  # 使用的 PSI 协议
    advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN"  # 使用交集连接
)


这段代码运行提示:KeyError: 'alice'

**Comment by lanyy9527** [comment]
> sf.shutdown()
> 
> sf.init(parties=['alice', 'bob', 'carol'], address='local')
> 
> alice, bob = sf.PYU('alice'), sf.PYU('bob') spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
> 
> input_path = {alice: './data/PIR-PSI用户数据A.csv', bob: './data/PSI-用户数据B.csv'} output_path = {alice: './data/A.csv', bob: './data/B.csv'} keys = { 'alice': ['姓名'], # Alice 的数据集中的列名 'bob': ['姓名'] # Bob 的数据集中的列名 }
> 
> spu.psi( keys=keys, # 注意：这里是字符串列表，匹配 CSV 文件中的列名 input_path=input_path, output_path=output_path, receiver='alice', # 指定谁可以收到结果 protocol='PROTOCOL_RR22', # 使用的 PSI 协议 advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN" # 使用交集连接 )
> 
> 这段代码运行提示:KeyError: 'alice'


将代码修改为：
input_path = {'alice': './data/PIR-PSI用户数据A.csv', 'bob': './data/PSI-用户数据B.csv'} 
output_path = {'alice': './data/A.csv', 'bob': './data/B.csv'}

**Comment by yaoyizhuo** [comment]
> > sf.shutdown()
> > sf.init(parties=['alice', 'bob', 'carol'], address='local')
> > alice, bob = sf.PYU('alice'), sf.PYU('bob') spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
> > input_path = {alice: './data/PIR-PSI用户数据A.csv', bob: './data/PSI-用户数据B.csv'} output_path = {alice: './data/A.csv', bob: './data/B.csv'} keys = { 'alice': ['姓名'], # Alice 的数据集中的列名 'bob': ['姓名'] # Bob 的数据集中的列名 }
> > spu.psi( keys=keys, # 注意：这里是字符串列表，匹配 CSV 文件中的列名 input_path=input_path, output_path=output_path, receiver='alice', # 指定谁可以收到结果 protocol='PROTOCOL_RR22', # 使用的 PSI 协议 advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN" # 使用交集连接 )
> > 这段代码运行提示:KeyError: 'alice'
> 
> 将代码修改为： input_path = {'alice': './data/PIR-PSI用户数据A.csv', 'bob': './data/PSI-用户数据B.csv'} output_path = {'alice': './data/A.csv', 'bob': './data/B.csv'}

成功运行了，做了一个并集，发现有一些输出为NA..，如图
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/0a6a62d6-2c73-443e-afc6-878cdf9aa2bd">

**Comment by yaoyizhuo** [comment]
> > > sf.shutdown()
> > > sf.init(parties=['alice', 'bob', 'carol'], address='local')
> > > alice, bob = sf.PYU('alice'), sf.PYU('bob') spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
> > > input_path = {alice: './data/PIR-PSI用户数据A.csv', bob: './data/PSI-用户数据B.csv'} output_path = {alice: './data/A.csv', bob: './data/B.csv'} keys = { 'alice': ['姓名'], # Alice 的数据集中的列名 'bob': ['姓名'] # Bob 的数据集中的列名 }
> > > spu.psi( keys=keys, # 注意：这里是字符串列表，匹配 CSV 文件中的列名 input_path=input_path, output_path=output_path, receiver='alice', # 指定谁可以收到结果 protocol='PROTOCOL_RR22', # 使用的 PSI 协议 advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN" # 使用交集连接 )
> > > 这段代码运行提示:KeyError: 'alice'
> > 
> > 
> > 将代码修改为： input_path = {'alice': './data/PIR-PSI用户数据A.csv', 'bob': './data/PSI-用户数据B.csv'} output_path = {'alice': './data/A.csv', 'bob': './data/B.csv'}
> 
> 成功运行了，做了一个并集，发现有一些输出为NA..，如图 <img alt="image" width="1345" src="https://private-user-images.githubusercontent.com/59595238/381052470-0a6a62d6-2c73-443e-afc6-878cdf9aa2bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTI5MDgsIm5iZiI6MTczMDE5MjYwOCwicGF0aCI6Ii81OTU5NTIzOC8zODEwNTI0NzAtMGE2YTYyZDYtMmM3My00NDNlLWFmYzYtODc4Y2RmOWFhMmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA5MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjQxZmEwYzEzYjgwMDczOGJkZWM2NDI0MjUxZDgzYjVhNjEwYzFhYTBiNjY5OGVlNmUwNjcwNmEyZGU5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xxm5ZZwrPK1IaGAzKIHtWUE5PoMVhcjyk4LJBWj0s-0">

[PIR-PSI用户数据A.csv](https://github.com/user-attachments/files/17554294/PIR-PSI.A.csv)
[PSI-用户数据B.csv](https://github.com/user-attachments/files/17554296/PSI-.B.csv)

**Comment by yaoyizhuo** [comment]
> > > > sf.shutdown()
> > > > sf.init(parties=['alice', 'bob', 'carol'], address='local')
> > > > alice, bob = sf.PYU('alice'), sf.PYU('bob') spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
> > > > input_path = {alice: './data/PIR-PSI用户数据A.csv', bob: './data/PSI-用户数据B.csv'} output_path = {alice: './data/A.csv', bob: './data/B.csv'} keys = { 'alice': ['姓名'], # Alice 的数据集中的列名 'bob': ['姓名'] # Bob 的数据集中的列名 }
> > > > spu.psi( keys=keys, # 注意：这里是字符串列表，匹配 CSV 文件中的列名 input_path=input_path, output_path=output_path, receiver='alice', # 指定谁可以收到结果 protocol='PROTOCOL_RR22', # 使用的 PSI 协议 advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN" # 使用交集连接 )
> > > > 这段代码运行提示:KeyError: 'alice'
> > > 
> > > 
> > > 将代码修改为： input_path = {'alice': './data/PIR-PSI用户数据A.csv', 'bob': './data/PSI-用户数据B.csv'} output_path = {'alice': './data/A.csv', 'bob': './data/B.csv'}
> > 
> > 
> > 成功运行了，做了一个并集，发现有一些输出为NA..，如图 <img alt="image" width="1345" src="https://private-user-images.githubusercontent.com/59595238/381052470-0a6a62d6-2c73-443e-afc6-878cdf9aa2bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTI5MDgsIm5iZiI6MTczMDE5MjYwOCwicGF0aCI6Ii81OTU5NTIzOC8zODEwNTI0NzAtMGE2YTYyZDYtMmM3My00NDNlLWFmYzYtODc4Y2RmOWFhMmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA5MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjQxZmEwYzEzYjgwMDczOGJkZWM2NDI0MjUxZDgzYjVhNjEwYzFhYTBiNjY5OGVlNmUwNjcwNmEyZGU5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xxm5ZZwrPK1IaGAzKIHtWUE5PoMVhcjyk4LJBWj0s-0">
> 
> [PIR-PSI用户数据A.csv](https://github.com/user-attachments/files/17554294/PIR-PSI.A.csv) [PSI-用户数据B.csv](https://github.com/user-attachments/files/17554296/PSI-.B.csv)

code:

sf.init(parties=['alice', 'bob', 'carol'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

input_path = {'alice': './data/PIR-PSI用户数据A.csv', 'bob': './data/PSI-用户数据B.csv'}

keys = {
    'alice': ['姓名'],  # Alice 的数据集中的列名
    'bob': ['姓名']     # Bob 的数据集中的列名
}

output_path = {'alice': './data/psi_result/FULL_A.csv', 'bob': './data/psi_result/FULL_B.csv'}
spu.psi(
    keys=keys,
    input_path=input_path,
    output_path=output_path,
    receiver='alice',
    protocol='PROTOCOL_RR22',
    broadcast_result=False,
    disable_alignment=True,
    skip_duplicates_check=True,
    advanced_join_type="ADVANCED_JOIN_TYPE_FULL_JOIN" # 并集
)

**Comment by lanyy9527** [comment]
advanced_join_type 不同配置输出的结果可以参考：https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.2b0/reference/psi_v2_config#psiconfig
