### ISSUE TITLE
可以在docker中内置jupyter客户端

### ISSUE THREAD

**Issue by lvying0019** [secretflow/secretflow#156]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

无

### OS Platform and Distribution

无

### Python version

无

### What happend and What you expected to happen.

```shell
可以在docker中内置jupyter客户端，默认jupyter启动，并且映射端口，这样可能更快速和方便
```

### Reproduction code to reproduce the issue.

```shell
可以在docker中内置jupyter客户端，默认jupyter启动，并且映射端口，这样可能更快速和方便
```

**Comment by zhouaihui** [comment]
hi, @lvying0019 ，你可以手动安装jupyter，或者可以自行修改[dockerfile](https://github.com/secretflow/secretflow/blob/beta/docker/release/anolis.Dockerfile)以满足你的需求。

考虑到镜像需要尽量小，以及jupyter并不是运行secreflow的必须依赖，我们目前不考虑内置jupyter。
