### ISSUE TITLE
生产模式2节点代码执行报错

### ISSUE THREAD

**Issue by yuandl** [secretflow/secretflow#1560]
### Issue Type

Others

### Source

source

### Secretflow Version

v1.9.0b2

### OS Platform and Distribution

Linux 4.19.90-52.40.v2207.ky10.x86_64 SMP Wed Jul 24 15:07:09 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

### Python version

Python 3.10.14

### What happend and What you expected to happen.

```shell
使用两台服务器启动双节点模拟生产模式，启动命令如下：
ray start --head --node-ip-address="192.168.11.82" --port="7001" --resources='{"lun": 16}' --include-dashboard=False --disable-usage-stats
ray start --head --node-ip-address="192.168.11.83" --port="7001" --resources='{"ma": 16}' --include-dashboard=False --disable-usage-stats


启动后，在secretnote同时执行两个节点的命令
提交yuan节点执行如下代码：
#yuan
import spu
import secretflow as sf

sf.shutdown()


cluster_config={
    'parties': {
        'yuan':{'address':'192.168.11.82:7002'},
        'ma':{'address':'192.168.11.83:7002'},
    },
    'self_party':'yuan',
}

cluster_def={
    'nodes': [
        {
            'party': 'yuan',
            # Please choose an unused port.
            'address': '192.168.11.82:7002',
        },
        {
            'party': 'ma',
            # Please choose an unused port.
            'address': '192.168.11.83:7002',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

sf.init(address='192.168.11.82:7001',num_cpus=32,cluster_config=cluster_config)

#创建SPU设备
spu_device = sf.SPU(cluster_def=cluster_def)

yuan, ma = sf.PYU('yuan'), sf.PYU('ma')


提交ma节点如下代码：
#ma
import spu
import secretflow as sf

sf.shutdown()


cluster_config={
    'parties': {
        'yuan':{'address':'192.168.11.82:7002'},
        'ma':{'address':'192.168.11.83:7002'},
    },
    'self_party':'ma',
}

cluster_def={
    'nodes': [
        {
            'party': 'yuan',
            # Please choose an unused port.
            'address': '192.168.11.82:7002',
        },
        {
            'party': 'ma',
            # Please choose an unused port.
            'address': '192.168.11.83:7002',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

sf.init(address='192.168.11.83:7001',num_cpus=32,cluster_config=cluster_config)


#创建SPU设备
spu_device = sf.SPU(cluster_def=cluster_def)

yuan, ma = sf.PYU('yuan'), sf.PYU('ma')


产生错误如下，看起来是shutdown引起的报错，请问如何解决，感谢！
ValueError: Failed to look up actor with name 'SenderProxyActor'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[19], line 5
      2 import spu
      3 import secretflow as sf
----> 5 sf.shutdown()
      8 # cluster_config={
      9 #     'parties': {
     10 #         'yuan':{'address':'192.168.11.82:7002'},
   (...)
     46 # output_path = {yuan: '/root/ma_psi.csv', ma: '/root/ma2_psi.csv'}
     47 # spu_device.psi_csv('tyshxydm', input_path, output_path, receiver='yuan')

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/secretflow/device/driver.py:553, in shutdown(barrier_on_shutdown, on_error)
    548 logging.info(
    549     f"shutdown is called, barrier_on_shutdown {barrier_on_shutdown},"
    550     f" on_error {on_error}"
    551 )
    552 if barrier_on_shutdown and not on_error:
--> 553     barrier()
    554 sfd.shutdown(on_error=on_error)

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/secretflow/device/driver.py:522, in barrier()
    520 for party in global_state.parties():
    521     barriers.append(PYU(party)(lambda: None)())
--> 522 reveal(barriers)

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/secretflow/device/driver.py:161, in reveal(func_or_object, heu_encoder)
    158         logging.debug(f'Getting teeu data from TEEU {x.device.party}.')
    160 cur_idx = 0
--> 161 all_object = sfd.get(all_object_refs)
    163 new_flatten_val = []
    164 for x in flatten_val:

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/secretflow/distributed/primitive.py:162, in get(object_refs)
    160     return sf_fed.get(object_refs)
    161 elif get_distribution_mode() == DISTRIBUTION_MODE.RAY_PRODUCTION:
--> 162     return rayfed.get(object_refs)
    163 elif get_distribution_mode() == DISTRIBUTION_MODE.SIMULATION:
    164     return ray.get(object_refs)

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/fed/api.py:598, in get(fed_objects)
    596             else:
    597                 fed_object._mark_is_sending_to_party(party_name)
--> 598                 send(
    599                     dest_party=party_name,
    600                     data=ray_object_ref,
    601                     upstream_seq_id=fed_object.get_fed_task_id(),
    602                     downstream_seq_id=fake_fed_task_id,
    603                 )
    604 else:
    605     # This is the code path that the fed_object is not in current party.
    606     # So we should insert a `recv_op` as a barrier to receive the real
    607     # data from the location party of the fed_object.
    608     if fed_object.get_ray_object_ref() is not None:

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/fed/proxy/barriers.py:494, in send(dest_party, data, upstream_seq_id, downstream_seq_id, is_error, check_sending)
    479 def send(
    480     dest_party: str,
    481     data: Any,
   (...)
    485     check_sending: bool = True,
    486 ):
    487     """
    488     Args:
    489         is_error: Whether the `data` is an error object or not. Default is False.
   (...)
    492             checked in the sending check loop.
    493     """
--> 494     sender_proxy = ray.get_actor(sender_proxy_actor_name())
    495     res = sender_proxy.send.remote(
    496         dest_party=dest_party,
    497         data=data,
    498         upstream_seq_id=upstream_seq_id,
    499         downstream_seq_id=downstream_seq_id,
    500     )
    501     if check_sending:

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py:22, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     19 @wraps(fn)
     20 def auto_init_wrapper(*args, **kwargs):
     21     auto_init_ray()
---> 22     return fn(*args, **kwargs)

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~/anaconda3/envs/SecretEnv/lib/python3.10/site-packages/ray/_private/worker.py:2889, in get_actor(name, namespace)
   2887 worker = global_worker
   2888 worker.check_connected()
-> 2889 return worker.core_worker.get_named_actor_handle(name, namespace or "")

File python/ray/_raylet.pyx:4180, in ray._raylet.CoreWorker.get_named_actor_handle()

File python/ray/_raylet.pyx:574, in ray._raylet.check_status()

ValueError: Failed to look up actor with name 'SenderProxyActor'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
```

### Reproduction code to reproduce the issue.

```shell
代码如上
```

**Comment by Chrisdehe** [comment]
1、在sf.init中去掉num_cpus=32参数
2、双方代码cluster_def中端口号与cluster_config都是7002，端口号重复了，cluster_def中改为7003
修改以上内容请再次尝试一下

**Comment by yuandl** [comment]
> 1、在sf.init中去掉num_cpus=32参数 2、双方代码cluster_def中端口号与cluster_config都是7002，端口号重复了，cluster_def中改为7003 修改以上内容请再次尝试一下

您好，我已经修改尝试了，看起来还是一样的问题。
![image](https://github.com/user-attachments/assets/eab5b869-f490-4602-8afb-067fde8dac48)
![image](https://github.com/user-attachments/assets/c64b86b6-41df-4bbd-9bf3-81f7cf93e3b4)

**Comment by wangzul** [comment]
你是如何安装的secrerflow  是自己构建的吗？

**Comment by yuandl** [comment]
> 你是如何安装的secrerflow 是自己构建的吗？

您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote

**Comment by wangzul** [comment]
> > 你是如何安装的secrerflow 是自己构建的吗？
> 
> 您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote

尝试在终端中运行代码 python -c "import secretflow as sf;sf.shutdown()"    
先不用secretnote看上方代码能否执行

**Comment by yuandl** [comment]
> > > 你是如何安装的secrerflow 是自己构建的吗？
> > 
> > 
> > 您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote
> 
> 尝试在终端中运行代码 python -c "import secretflow as sf;sf.shutdown()" 先不用secretnote看上方代码能否执行

好吧，刚才终端尝试失败了，同样报错，之前用local模式正常运行所以没关注这个问题。

我重启了ray还是一样的问题

![image](https://github.com/user-attachments/assets/8dc6ea99-2f65-48e5-9f88-9ea0ff21aa09)

之前从未遇到过，local做psi也是正常运行的

启动命令为
ray start --head --node-ip-address="192.168.11.82" --port="7001" --resources='{"lun": 16}' --include-dashboard=False --disable-usage-stats

**Comment by wangzul** [comment]
> > > > 你是如何安装的secrerflow 是自己构建的吗？
> > > 
> > > 
> > > 您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote
> > 
> > 
> > 尝试在终端中运行代码 python -c "import secretflow as sf;sf.shutdown()" 先不用secretnote看上方代码能否执行
> 
> 好吧，刚才终端尝试失败了，同样报错，之前用local模式正常运行所以没关注这个问题。
> 
> 我重启了ray还是一样的问题
> 
> ![image](https://private-user-images.githubusercontent.com/7816984/381379067-8dc6ea99-2f65-48e5-9f88-9ea0ff21aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYwMDksIm5iZiI6MTczMDI2NTcwOSwicGF0aCI6Ii83ODE2OTg0LzM4MTM3OTA2Ny04ZGM2ZWE5OS0yZjY1LTQ4ZTUtOWY4OC05ZWEwZmYyMWFhMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDUyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ2YzNlNzE0OWU3MjI0OGI2NjkzOTBlMjFmZjQwMjYwMzJiMzVhZGFhNTUzY2VkZDYxYmE2MjYzMjg0MzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rjxOdo48hJxsNEEH8iK00BKYzj5VbzRS6Hs5H7v5GB0)
> 
> 之前从未遇到过，local做psi也是正常运行的
> 
> 启动命令为 ray start --head --node-ip-address="192.168.11.82" --port="7001" --resources='{"lun": 16}' --include-dashboard=False --disable-usage-stats

尝试重装sf试试，pip uninstall secretflow ,pip install secretflow==1.9.0b2

**Comment by yuandl** [comment]
> > > > > 你是如何安装的secrerflow 是自己构建的吗？
> > > > 
> > > > 
> > > > 您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote
> > > 
> > > 
> > > 尝试在终端中运行代码 python -c "import secretflow as sf;sf.shutdown()" 先不用secretnote看上方代码能否执行
> > 
> > 
> > 好吧，刚才终端尝试失败了，同样报错，之前用local模式正常运行所以没关注这个问题。
> > 我重启了ray还是一样的问题
> > ![image](https://private-user-images.githubusercontent.com/7816984/381379067-8dc6ea99-2f65-48e5-9f88-9ea0ff21aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYwMDksIm5iZiI6MTczMDI2NTcwOSwicGF0aCI6Ii83ODE2OTg0LzM4MTM3OTA2Ny04ZGM2ZWE5OS0yZjY1LTQ4ZTUtOWY4OC05ZWEwZmYyMWFhMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDUyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ2YzNlNzE0OWU3MjI0OGI2NjkzOTBlMjFmZjQwMjYwMzJiMzVhZGFhNTUzY2VkZDYxYmE2MjYzMjg0MzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rjxOdo48hJxsNEEH8iK00BKYzj5VbzRS6Hs5H7v5GB0)
> > 之前从未遇到过，local做psi也是正常运行的
> > 启动命令为 ray start --head --node-ip-address="192.168.11.82" --port="7001" --resources='{"lun": 16}' --include-dashboard=False --disable-usage-stats
> 
> 尝试重装sf试试，pip uninstall secretflow ,pip install secretflow==1.9.0b2

重装以后确实解决了第一个问题，shutdown正常了，但是后续的还是出了点没看懂的问题。

就是我首先在第一个节点提交了任务，过了一两秒在第二个节点提交了任务，如下：
第一个节点：
![image](https://github.com/user-attachments/assets/555d926e-0026-4072-a6f5-3135a6ef5360)
第二个节点：
![image](https://github.com/user-attachments/assets/8a914ef5-ef97-4f0b-83fa-2dfd712206ca)


在secretnote中日志就停留在这里了，也没报错，但是也没提示任务是否成功。


BTW，我这是第一次生产模式执行，Try ping ['ma'] at 0 attemp, up to 3600 attemps.，是不是理解为多个节点提交共同计算的任务，要在这3600次ping的时间内，各个节点完成自己节点的任务提交，才被认为是合法可执行的任务？

**Comment by wangzul** [comment]
> > > > > > 你是如何安装的secrerflow 是自己构建的吗？
> > > > > 
> > > > > 
> > > > > 您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote
> > > > 
> > > > 
> > > > 尝试在终端中运行代码 python -c "import secretflow as sf;sf.shutdown()" 先不用secretnote看上方代码能否执行
> > > 
> > > 
> > > 好吧，刚才终端尝试失败了，同样报错，之前用local模式正常运行所以没关注这个问题。
> > > 我重启了ray还是一样的问题
> > > ![image](https://private-user-images.githubusercontent.com/7816984/381379067-8dc6ea99-2f65-48e5-9f88-9ea0ff21aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYwMDksIm5iZiI6MTczMDI2NTcwOSwicGF0aCI6Ii83ODE2OTg0LzM4MTM3OTA2Ny04ZGM2ZWE5OS0yZjY1LTQ4ZTUtOWY4OC05ZWEwZmYyMWFhMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDUyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ2YzNlNzE0OWU3MjI0OGI2NjkzOTBlMjFmZjQwMjYwMzJiMzVhZGFhNTUzY2VkZDYxYmE2MjYzMjg0MzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rjxOdo48hJxsNEEH8iK00BKYzj5VbzRS6Hs5H7v5GB0)
> > > 之前从未遇到过，local做psi也是正常运行的
> > > 启动命令为 ray start --head --node-ip-address="192.168.11.82" --port="7001" --resources='{"lun": 16}' --include-dashboard=False --disable-usage-stats
> > 
> > 
> > 尝试重装sf试试，pip uninstall secretflow ,pip install secretflow==1.9.0b2
> 
> 重装以后确实解决了第一个问题，shutdown正常了，但是后续的还是出了点没看懂的问题。
> 
> 就是我首先在第一个节点提交了任务，过了一两秒在第二个节点提交了任务，如下： 第一个节点： ![image](https://private-user-images.githubusercontent.com/7816984/381409303-555d926e-0026-4072-a6f5-3135a6ef5360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjc5MDUsIm5iZiI6MTczMDI2NzYwNSwicGF0aCI6Ii83ODE2OTg0LzM4MTQwOTMwMy01NTVkOTI2ZS0wMDI2LTQwNzItYTZmNS0zMTM1YTZlZjUzNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDU1MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI2Mjk4ZDJjY2I0MjVhZTU2NDgxZGFlMTY1ZDI5YzFkZWZiMGFkMjU5ZWY5NTZjY2NmOTc3NTU4NmQxNGNmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tq5sKjCgCM6aXNduDLIHG52yb6zQgVB5mu6nTREfjBg) 第二个节点： ![image](https://private-user-images.githubusercontent.com/7816984/381409344-8a914ef5-ef97-4f0b-83fa-2dfd712206ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjc5MDUsIm5iZiI6MTczMDI2NzYwNSwicGF0aCI6Ii83ODE2OTg0LzM4MTQwOTM0NC04YTkxNGVmNS1lZjk3LTRmMGItODNmYS0yZGZkNzEyMjA2Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDU1MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlZTc2YThiN2E3OTQ0ZmU3MTE3ZjNmMTAyYzM2ZDAyNGQzMTdjOWU4OTRiNTMzYTkwNzYwMzcxYzhjYzhjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VJIz-LZ7lnke-x6_ALNgiyoe3Yr9aToKKQqAWTrCIhI)
> 
> 在secretnote中日志就停留在这里了，也没报错，但是也没提示任务是否成功。
> 
> BTW，我这是第一次生产模式执行，Try ping ['ma'] at 0 attemp, up to 3600 attemps.，是不是理解为多个节点提交共同计算的任务，要在这3600次ping的时间内，各个节点完成自己节点的任务提交，才被认为是合法可执行的任务？

1. 是的，初始化完成后会等待合作节点的响应。
2. 你的第二个节点看起来还有sf.shutdown()问题，这个节点也可以重新安装一下。

**Comment by yuandl** [comment]
> > > > > > > 你是如何安装的secrerflow 是自己构建的吗？
> > > > > > 
> > > > > > 
> > > > > > 您好，对的，因为没法用docker安装，所以用pypi的方式安装的，参照官方教程，分别装了sf和secretnote
> > > > > 
> > > > > 
> > > > > 尝试在终端中运行代码 python -c "import secretflow as sf;sf.shutdown()" 先不用secretnote看上方代码能否执行
> > > > 
> > > > 
> > > > 好吧，刚才终端尝试失败了，同样报错，之前用local模式正常运行所以没关注这个问题。
> > > > 我重启了ray还是一样的问题
> > > > ![image](https://private-user-images.githubusercontent.com/7816984/381379067-8dc6ea99-2f65-48e5-9f88-9ea0ff21aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYwMDksIm5iZiI6MTczMDI2NTcwOSwicGF0aCI6Ii83ODE2OTg0LzM4MTM3OTA2Ny04ZGM2ZWE5OS0yZjY1LTQ4ZTUtOWY4OC05ZWEwZmYyMWFhMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDUyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ2YzNlNzE0OWU3MjI0OGI2NjkzOTBlMjFmZjQwMjYwMzJiMzVhZGFhNTUzY2VkZDYxYmE2MjYzMjg0MzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rjxOdo48hJxsNEEH8iK00BKYzj5VbzRS6Hs5H7v5GB0)
> > > > 之前从未遇到过，local做psi也是正常运行的
> > > > 启动命令为 ray start --head --node-ip-address="192.168.11.82" --port="7001" --resources='{"lun": 16}' --include-dashboard=False --disable-usage-stats
> > > 
> > > 
> > > 尝试重装sf试试，pip uninstall secretflow ,pip install secretflow==1.9.0b2
> > 
> > 
> > 重装以后确实解决了第一个问题，shutdown正常了，但是后续的还是出了点没看懂的问题。
> > 就是我首先在第一个节点提交了任务，过了一两秒在第二个节点提交了任务，如下： 第一个节点： ![image](https://private-user-images.githubusercontent.com/7816984/381409303-555d926e-0026-4072-a6f5-3135a6ef5360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjc5MDUsIm5iZiI6MTczMDI2NzYwNSwicGF0aCI6Ii83ODE2OTg0LzM4MTQwOTMwMy01NTVkOTI2ZS0wMDI2LTQwNzItYTZmNS0zMTM1YTZlZjUzNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDU1MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI2Mjk4ZDJjY2I0MjVhZTU2NDgxZGFlMTY1ZDI5YzFkZWZiMGFkMjU5ZWY5NTZjY2NmOTc3NTU4NmQxNGNmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tq5sKjCgCM6aXNduDLIHG52yb6zQgVB5mu6nTREfjBg) 第二个节点： ![image](https://private-user-images.githubusercontent.com/7816984/381409344-8a914ef5-ef97-4f0b-83fa-2dfd712206ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjc5MDUsIm5iZiI6MTczMDI2NzYwNSwicGF0aCI6Ii83ODE2OTg0LzM4MTQwOTM0NC04YTkxNGVmNS1lZjk3LTRmMGItODNmYS0yZGZkNzEyMjA2Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDU1MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlZTc2YThiN2E3OTQ0ZmU3MTE3ZjNmMTAyYzM2ZDAyNGQzMTdjOWU4OTRiNTMzYTkwNzYwMzcxYzhjYzhjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VJIz-LZ7lnke-x6_ALNgiyoe3Yr9aToKKQqAWTrCIhI)
> > 在secretnote中日志就停留在这里了，也没报错，但是也没提示任务是否成功。
> > BTW，我这是第一次生产模式执行，Try ping ['ma'] at 0 attemp, up to 3600 attemps.，是不是理解为多个节点提交共同计算的任务，要在这3600次ping的时间内，各个节点完成自己节点的任务提交，才被认为是合法可执行的任务？
> 
> 1. 是的，初始化完成后会等待合作节点的响应。
> 2. 你的第二个节点看起来还有sf.shutdown()问题，这个节点也可以重新安装一下。

已重新更新第二个节点，看起来在互ping环节以后日志还是停止打印了
![image](https://github.com/user-attachments/assets/d60a4783-03eb-43c3-9e7c-26b35d2413e5)
![image](https://github.com/user-attachments/assets/12084fbe-bf31-4029-83af-6f6ef5605771)

**Comment by wangzul** [comment]
![image](https://github.com/user-attachments/assets/b292b271-7ebf-46cb-a105-86f1fd9c56f1)
配置一下监听端口

**Comment by yuandl** [comment]
> ![image](https://private-user-images.githubusercontent.com/55971198/381423726-b292b271-7ebf-46cb-a105-86f1fd9c56f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzE3MTQsIm5iZiI6MTczMDI3MTQxNCwicGF0aCI6Ii81NTk3MTE5OC8zODE0MjM3MjYtYjI5MmIyNzEtN2ViZi00NmNiLWExMDUtODZmMWZkOWM1NmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA2NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YzE5ZmJhYjA4NGY2YTcyOWVjNzU0YjYzNGE5NzNlZDVjMzFkMzgwNmI4MGMzNWVlZjU4ZGRkY2E1OTg1ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PhqL-UzCCZz2Q4_fb29wN8tq2UQMcMjAVFHJS-IIqAI) 配置一下监听端口

这个我确实漏掉了，刚看了一下官方部署文档给加上了，开通防火墙策略以后就好了
![image](https://github.com/user-attachments/assets/d3ab342b-5733-4cb5-92ea-7c3dd8eaf990)


后面其他问题我再另建新issue吧，感谢各位大佬的鼎力协助。

另外问一下，咱有微信群之类的沟通方式吗，一些小问题有没有更方便的沟通方式？

谢谢

**Comment by Chrisdehe** [comment]
@yuandl 有的，有微信的技术交流群，可以添加隐语技术支持WeChat：secretflow02，来邀请你进群。

**Comment by yuandl** [comment]
> @yuandl 有的，有微信的技术交流群，可以添加隐语技术支持WeChat：secretflow02，来邀请你进群。

已添加好友，咱次感谢各位鼎力支持，但是还是厚着脸皮说后面还会继续求助哈哈
