### ISSUE TITLE
FLModel 只能 fit 横向数据吗？

### ISSUE THREAD

**Issue by Diomchen** [secretflow/secretflow#1564]
### Issue Type

Bug

### Source

binary

### Secretflow Version

v1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.8

### What happend and What you expected to happen.

```shell
FLModel 只能 fit 横向数据吗？
我现在有两方，需要进行纵向融合后进行自定义算法训练，但是目前从源码来看，似乎不支持纵向数据。想问一下，我还有其他办法吗？
```

### Reproduction code to reproduce the issue.

```shell
Traceback (most recent call last):
  File "/algorithm/ex/Ex1.py", line 233, in train
    res_matrix = fed_model.fit(
  File "/opt/conda/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 438, in fit
    train_steps_per_epoch = self._handle_data(
  File "/opt/conda/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 300, in _handle_data
    y_partitions = train_y.partitions[device]
```

**Comment by BrainWH** [comment]
sl_model支持纵向的联邦学习，可以参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/tutorial/Split_Learning_for_bank_marketing

**Comment by Diomchen** [comment]
> sl_model支持纵向的联邦学习，可以参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/tutorial/Split_Learning_for_bank_marketing

非常感谢！🙏
