### ISSUE TITLE
spu cluster docs bug （spu集群设置文档bug）

### ISSUE THREAD

**Issue by wangwg1** [secretflow/secretflow#157]
### Issue Type

Bug

### Source

binary

### Secretflow Version

beta

### OS Platform and Distribution

linux ubuntu

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
快速开始->部署->集群模式：
（可选）如何在集群模式下启动SPU：
问题1、其中import secteflow 错误，应为secretflow
问题2、用这个例子执行有问题，缺少：
sf.init(address='ip:port')
```

### Reproduction code to reproduce the issue.

```shell
快速开始->部署->集群模式：
（可选）如何在集群模式下启动SPU：
问题1、其中import secteflow 错误，应为secretflow
问题2、用这个例子执行有问题，缺少：
sf.init(address='ip:port')
```

**Comment by zhouaihui** [comment]
hi， @wangwg1 ，确实是一个typo，你可以提一个PR来修改吗？
