### ISSUE TITLE
在secretflow中添加组件能否支持“可变数量”的参与方

### ISSUE THREAD

**Issue by sabakioukenasai** [secretflow/secretflow#1575]
按照[官方文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.9.0b2/more_tutorials/new_components#id9)的步骤演示在secretflow中新增组件，我想知道能否让新增的组件支持可变数量的参与方。

根据文档中给出的例子，定义一个组件时要定义其参数和输入输出。在定义输出输出的那一步其实隐形地限制了组件参与方的数量，当我们为组件定义了两个输入时，是否就意味着该组件无法用于三方甚至更多方的计算场景了呢？

（文档中定义输入输出的示例如下）
```python
ss_compare_comp.io(
    io_type=IoType.INPUT,
    name="input_table",
    desc="Input vertical table",
    types=[DistDataType.VERTICAL_TABLE],
    col_params=[
        TableColParam(
            name="alice_value",
            desc="Column(s) used to compare.",
            col_min_cnt_inclusive=1,
            col_max_cnt_inclusive=1,
        ),
        TableColParam(
            name="bob_value",
            desc="Column(s) used to compare.",
            col_min_cnt_inclusive=1,
            col_max_cnt_inclusive=1,
        ),
    ],
)


ss_compare_comp.io(
    io_type=IoType.OUTPUT,
    name="alice_output",
    desc="Output for alice",
    types=[DistDataType.INDIVIDUAL_TABLE],
)

ss_compare_comp.io(
    io_type=IoType.OUTPUT,
    name="bob_output",
    desc="Output for bob",
    types=[DistDataType.INDIVIDUAL_TABLE],
)
```

请问有没有办法将参与方的数量延迟到运行时决定（比如作为参数输入），不知道在这种情况下应当如何定义组件的输入输出呢？

**Comment by lanyy9527** [comment]
>  根据文档中给出的例子，定义一个组件时要定义其参数和输入输出。在定义输出输出的那一步其实隐形地限制了组件参与方的数量，当我们为组件定义了两个输入时，是否就意味着该组件无法用于三方甚至更多方的计算场景了呢？


是的，三方和两方的组件不是同一个；

**Comment by sabakioukenasai** [comment]
> > 根据文档中给出的例子，定义一个组件时要定义其参数和输入输出。在定义输出输出的那一步其实隐形地限制了组件参与方的数量，当我们为组件定义了两个输入时，是否就意味着该组件无法用于三方甚至更多方的计算场景了呢？
> 
> 是的，三方和两方的组件不是同一个；

那我非常好奇，如果我实现了一个五方计算组件，是不是必须为其实现相应的四方，三方和两方的版本？有没有方式能够减少重复开发呢？

**Comment by lanyy9527** [comment]
可以分享下您这边具体的业务场景吗？

**Comment by sabakioukenasai** [comment]
> 可以分享下您这边具体的业务场景吗？

大概就是五个参与方要计算一些联合函数，虽然可以两两计算，用树状结构得到最终结果，但是这会引入中间值，从而导致信息泄漏。我们希望能在一个组件中直接计算出最终结果并发给各个参与方。但是这可能会使得只有四个参与方的时候无法调用这个组件。

**Comment by lanyy9527** [comment]
需要新的算法，目前还没有满足安全定义的五方算法
