### ISSUE TITLE
pytest测试脚本经常执行卡住失败

### ISSUE THREAD

**Issue by magic-hya** [secretflow/secretflow#1585]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretpad all in one 1.9.0b2

### OS Platform and Distribution

CentOS Linux 7

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
执行pytest，测试自定义组件经常卡住或者失败，而且每次都启动4方
1.有没有什么办法能只启动alice和bob
2.经常执行半天脚本，没有一次成功的，有什么别的办法可以测试吗

错误的日志见下：
```

### Reproduction code to reproduce the issue.

```shell
>       assert server_state[0], server_state[1]
E       AssertionError: Failed to listen on 0.0.0.0:61514 as exception:
E       what:
E               [external/yacl/yacl/link/transport/brpc_link.cc:104] brpc server failed start
E       stacktrace:
E       #0 yacl::link::FactoryBrpc::CreateContext()+0x7fc202d964f4
E       #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fc2012f83e4
E       #2 pybind11::cpp_function::dispatcher()+0x7fc2012cbb5e
E       #3 cfunction_call+0x56328fbdd446

/root/miniconda3/lib/python3.10/site-packages/fed/proxy/barriers.py:464: AssertionError

=========================================================== short test summary info ============================================================
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_bob] - AssertionError: Failed to listen on 0.0.0.0:63312 as exception:
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_carol] - AssertionError: Failed to listen on 0.0.0.0:64413 as exception:
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_alice] - AssertionError: Failed to listen on 0.0.0.0:62211 as exception:
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_davy] - AssertionError: Failed to listen on 0.0.0.0:61514 as exception:
================================================ 4 failed, 3854 warnings in 1148.78s (0:19:08) =================================================
```

**Comment by zimu-yuxi** [comment]
pytest执行的命令方便提供下吗？

**Comment by magic-hya** [comment]
> pytest执行的命令方便提供下吗？

pytest --env prod  -n auto  -v --capture=no  tests/component/stats/test_table_statistics.py

**Comment by lanyy9527** [comment]
1. 排查下端口使用情况：netstat -tuln | grep port；
2. 另外可以提供下系统的配置信息；
3. 如果1排查后仍然无法执行，请提供完整的日志信息；

**Comment by magic-hya** [comment]
首先这个脚本执行成功过，开发过程中有时候非常顺利，有时候几天一次都执行不成功，会在各种地方卡住失败。
有什么手段排查端口被拦截占用，具体排查哪些端口

1.端口排查正常：
```
-bash-4.2# netstat -tuln | grep 62211
-bash-4.2# netstat -tuln | grep 63312
-bash-4.2# netstat -tuln | grep 64413
-bash-4.2# netstat -tuln | grep 61514
-bash-4.2# netstat -tuln | grep 62625
-bash-4.2# netstat -tuln | grep 63726
-bash-4.2# netstat -tuln | grep 63841
-bash-4.2# netstat -tuln | grep 63942
-bash-4.2# netstat -tuln | grep 63743
-bash-4.2# netstat -tuln | grep 63644
```
2.环境使用的官方提供的dockerfile打包出来的镜像，在镜像内部执行的脚本。参考配置[release-ci.DockerFile](https://github.com/secretflow/devtools/blob/main/dockerfiles/release-ci.DockerFile)

**Comment by lanyy9527** [comment]
docker update --cpu --memory --memory-swap 
可以尝试将容器的cpu和mem调大，然后重新运行；

**Comment by magic-hya** [comment]
docker update --cpus 24.0 -m 64g --memory-swap 64g secretpad_dev
docker restart secretpad_dev
之后依然会卡住，一般在启动2个ray instance后
![image](https://github.com/user-attachments/assets/afd898ed-4ddf-44c4-b8c8-f2f26af3339d)

**Comment by lanyy9527** [comment]
这是已经挂了，尝试在宿主机中运行测试；

> docker update --cpus 24.0 -m 64g --memory-swap 64g secretpad_dev docker restart secretpad_dev 之后依然会卡住，一般在启动2个ray instance后 ![image](https://private-user-images.githubusercontent.com/85269941/387910655-afd898ed-4ddf-44c4-b8c8-f2f26af3339d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzY0NDEsIm5iZiI6MTczMjE3NjE0MSwicGF0aCI6Ii84NTI2OTk0MS8zODc5MTA2NTUtYWZkODk4ZWQtNGRkZi00NGM0LWI4YzgtZjJmMjZhZjMzMzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA4MDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NmU5MDM2NDk2MGJkYWM3YWY3NWFhYzNiMmM4ODk5ZjE1MDBkNTA0MGZjNjY3NGM1NDU3YzYzYzExODg4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3UXUiSyhev9lDjFlz3aFsyG_QM5xMG1Mu6tIMQ6wDSA)

**Comment by gxcuit** [comment]
我也遇到相同问题，请问解决了吗

**Comment by da-niao-dan** [comment]
hello， 一般确实都是端口占用，查出占用端口的进程并杀掉它们就好。（确保可以杀，不行就换端口），怎么查到占用端口的进程并杀掉可以搜索或问大模型。

```
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_bob] - AssertionError: Failed to listen on 0.0.0.0:63312 as exception:
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_carol] - AssertionError: Failed to listen on 0.0.0.0:64413 as exception:
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_alice] - AssertionError: Failed to listen on 0.0.0.0:62211 as exception:
FAILED tests/component/oran/test_od_train.py::test_od_train_comp[SF_PARTY_PREFIX_davy] - AssertionError: Failed to listen on 0.0.0.0:61514 as exception:
```

确保任何一个上述端口都没有进程使用。
