### ISSUE TITLE
是否会增加基于HESS的线性回归的实现呢

### ISSUE THREAD

**Issue by kylin5207** [secretflow/secretflow#1589]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 1.9.2b0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### What happend and What you expected to happen.

查看代码https://github.com/secretflow/secretflow/blob/main/secretflow/ml/linear/hess_sgd/model.py， 这里只有关于HESS的逻辑回归的实现，是否会增加关于HESS的线性回归的实现呢？

### Reproduction code to reproduce the issue.
通过简单的将代码中的`_sigmoid_minimax`方法进行改写，是否就能支持线性回归？
```python
@staticmethod
def _sigmoid_minimax(p1, p2, y, scale):
        """sigmoid minimax approximation: y = 0.5 + 0.125 * x"""
        # NOTE: Prediction `p1` and `p2` are triple scaled integers and
        # label `y` is single scaled integer, so we have to right shift
        # `(p1 + p2)`. The whole return value is single scaled integer.
        y = y.reshape((y.shape[0],))
        yhat = (1 << (scale - 1)) + ((p1 + p2) >> (2 * scale + 3))
        yhat = jnp.select([yhat < 0, yhat > (1 << scale)], [0, (1 << scale)], yhat)
        return yhat - y
```
将代码中的t1泰勒近似sigmoid计算直接改为线性求和。
```python
@staticmethod
def _linear_regression(p1, p2, y, scale):
        # NOTE: Prediction `p1` and `p2` are triple scaled integers and
        # label `y` is single scaled integer, so we have to right shift
        # `(p1 + p2)`. The whole return value is single scaled integer.
        y = y.reshape((y.shape[0],))
        yhat = (p1 + p2) >> (2 * scale)
        return yhat - y
```

**Comment by kylin5207** [comment]
遇到了溢出问题，不知道如何解决。因为线性回归的标签不像二分类那样简单

**Comment by da-niao-dan** [comment]
hello 你好， 感谢你的努力。 能描述一下 溢出问题具体是什么变量在哪个步骤溢出的？溢出的表现是什么？

**Comment by kylin5207** [comment]
就是我上面提到的，我只是对源代码中的sigmoid近似计算进行了改动，以及模型预测部分去掉了sigmoid计算。但是最后的线性回归预测结果超过了1e20，不知道还需要修改什么位置。

**Comment by wangzul** [comment]
> 就是我上面提到的，我只是对源代码中的sigmoid近似计算进行了改动，以及模型预测部分去掉了sigmoid计算。但是最后的线性回归预测结果超过了1e20，不知道还需要修改什么位置。

有日志吗? 运行代码就是上方贴的吗？

**Comment by kylin5207** [comment]
日志没有报错，但是结果不对。对，代码就是对源码中的`_sigmoid_minimax`方法进行了改写，同时修改了`_predict`方法如下：

**Comment by kylin5207** [comment]
其实就是把hess-sgd中关于sigmoid的计算去掉了

**Comment by kylin5207** [comment]
我猜测是不是要修改heu_config的encoding呢

**Comment by kylin5207** [comment]
之前是对数据集接入标准化的，但是label没办法进行标准化，你们可以找个例如boston房价的数据集试一下，就能看出来结果了。

**Comment by kylin5207** [comment]
另外，我想问下，线性回归的输出需要什么激活函数呢？

**Comment by kylin5207** [comment]
是的，在修改的时候考虑到了这一点。

**Comment by kylin5207** [comment]
其实，我在问题的开始说明了这一点：
``` python
@staticmethod
def _linear_regression(p1, p2, y, scale):
        # NOTE: Prediction `p1` and `p2` are triple scaled integers and
        # label `y` is single scaled integer, so we have to right shift
        # `(p1 + p2)`. The whole return value is single scaled integer.
        y = y.reshape((y.shape[0],))
        yhat = (p1 + p2) >> (2 * scale)
        return yhat - y
```

**Comment by da-niao-dan** [comment]
hello, 我们知道这个改动。但是它不够。提示一点，identity activation function 不会把y scale 到 0 1 范围内，sigmoid的 learning_rate 可能对于 y 来说太大了。可以参考其他方法中的处理：
![image](https://github.com/user-attachments/assets/5bfd0e92-a30c-43fa-a3e9-75678352de44)

另外，有可能的确需要其他的修改才能使得训练收敛，加油。

**Comment by kylin5207** [comment]
对呀，所以我的问题是，隐语是否会增加这个功能呢，我改了很多地方发现都不行。所以只能问官方啦

**Comment by da-niao-dan** [comment]
hello， sf最近没有改进HESS LR 的计划。但是如果有业务场景需要它，并说明为什么ss lr 等其他技术不行，我们有可能会考虑改进它。

**Comment by kylin5207** [comment]
首先，线性回归比逻辑回归更简单，不是特别复杂的算法。两者在算法上的差异就是激活函数和预测部分的差异

**Comment by kylin5207** [comment]
😂 所以，一个简单的改动就会实现的功能都不愿意做吗

**Comment by kylin5207** [comment]
所以，我问的问题，首先并没有在代码上尝试一下。就只是简单的看一下问题给出结论，是否不严谨呢？

**Comment by da-niao-dan** [comment]
hello， 抱歉，HESS LR 这块代码只是处于demo 水平，且没有生产落地的场景。只是表明某种联邦算法是可行的。 在有明确需要它的场景之前，它就只是一个demo。您提供的代码并不能直接执行。

模型训练收敛有诸多因素，我们提供了它不收敛的原因之一。的确还有别的可能导致它不收敛，但是没有证据表明我们应该现在投入更多去尝试。

我们欢迎共建和场景输入，如果有需求我们一定可以实现。 再次感谢。

**Comment by kylin5207** [comment]
哎，很可惜我的问题没有解决。

**Comment by kylin5207** [comment]
甚至连试都不原因试一下
