### ISSUE TITLE
nvidia显卡缺少libcudart11.0包(所有包括docker下)

### ISSUE THREAD

**Issue by wangwg1** [secretflow/secretflow#159]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

linux deepin

### Python version

3.8.13

### GCC/Compiler version

7.5

### What happend and What you expected to happen.

```shell
nvidia显卡缺少libcudart11.0包(所有包括docker下)
```

### Reproduction code to reproduce the issue.

```shell
docker 下安装nvidia驱动的话比较麻烦。可直接在本地安装，例如：
sudo apt-get install libcudart11.0
之后将libcudart.so.11.0和libcudart.so.11.4.148两个包用
docker cp 拷贝到容器中/usr/lib64/下即可。

本地的话直接安装完毕后就没有问题了
```

**Comment by anakinxc** [comment]
请问您是需要用 cuda 加速吗？

**Comment by wangwg1** [comment]
> 请问您是需要用 cuda 加速吗？

不是。
