### ISSUE TITLE
提交模型疑问

### ISSUE THREAD

**Issue by Afive233** [secretflow/secretflow#1590]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow1.9.0b2

### OS Platform and Distribution

ubantu 18.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
提交模型时选择组件 可以选择所有组件吗 为什么这里只能选择上游的分箱组件 下游的预测组件等都选不了
```

### Reproduction code to reproduce the issue.

```shell
/
```

**Comment by wangzul** [comment]
> ![0GPM{6E)S0{4Y)8F4$)XNK1](https://private-user-images.githubusercontent.com/101703951/388014404-e41c0272-f4b0-4b24-a61a-84ff44c3d878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTM3NTgsIm5iZiI6MTczMjA5MzQ1OCwicGF0aCI6Ii8xMDE3MDM5NTEvMzg4MDE0NDA0LWU0MWMwMjcyLWY0YjAtNGIyNC1hNjFhLTg0ZmY0NGMzZDg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwOTA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDgxZDBhZTMxZjFmOWRhY2QxNjgyM2FlMGI2YjUwNmRiZWU4Y2JiYTY1ZWYxMGZiNzc0M2JkNjgzMGE0OWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T2Rp1uJ-efh9kPvG32jNQ4lZnBlAX2gR-2xgs3lvRRY)

![image](https://github.com/user-attachments/assets/aa534e39-4071-4dd1-a41c-524326097231)
可以选择模型训练组件 和其对应的上游输入组件。

**Comment by Afive233** [comment]
> > ![0GPM{6E)S0{4Y)8F4$)XNK1](https://private-user-images.githubusercontent.com/101703951/388014404-e41c0272-f4b0-4b24-a61a-84ff44c3d878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTM3NTgsIm5iZiI6MTczMjA5MzQ1OCwicGF0aCI6Ii8xMDE3MDM5NTEvMzg4MDE0NDA0LWU0MWMwMjcyLWY0YjAtNGIyNC1hNjFhLTg0ZmY0NGMzZDg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwOTA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDgxZDBhZTMxZjFmOWRhY2QxNjgyM2FlMGI2YjUwNmRiZWU4Y2JiYTY1ZWYxMGZiNzc0M2JkNjgzMGE0OWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T2Rp1uJ-efh9kPvG32jNQ4lZnBlAX2gR-2xgs3lvRRY)
> 
> ![image](https://private-user-images.githubusercontent.com/55971198/388021929-aa534e39-4071-4dd1-a41c-524326097231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTQyNDQsIm5iZiI6MTczMjA5Mzk0NCwicGF0aCI6Ii81NTk3MTE5OC8zODgwMjE5MjktYWE1MzRlMzktNDA3MS00ZGQxLWE0MWMtNTI0MzI2MDk3MjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA5MTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMGVlODAzN2ExMjRlYWNjMTc3M2Q5ZTljZDNhOWRhNDRhNzlmNmExMzVkNWJkMjAxMjZmOTNhMWYwMTIwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ZuPfY7JfnPStQA7XVYyeYOw-XsI6xJdhPjfvZHU4O0) 可以选择模型训练组件 和其对应的上游输入组件。

其他的组件暂不支持选择吗；还有模型发布后该如何使用，如何预测

**Comment by wangzul** [comment]
是的，暂不支持非模型组件。
使用文档可参考：https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.10.0b0/center_deploy/model_deployment
