### ISSUE TITLE
跑生产模式下隐私查询，隐匿求交的ray job id 问题

### ISSUE THREAD

**Issue by yaoyizhuo** [secretflow/secretflow#1591]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.10

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.10

### Bazel version

null

### GCC/Compiler version

null

### What happend and What you expected to happen.

```shell
初始化命令如下:
sf.init(address="127.0.0.1:9913", cluster_config=cluster_config) # address=ray rpc

从ray任务控制台中看到job id是默认生成，有没有方法可以自己来定义?
```

### Reproduction code to reproduce the issue.

```shell
如题。。
```

**Comment by wangzul** [comment]
在Ray中，常规情况下，Job ID 是由系统自动生成的，并且不允许用户自定义。Ray 的设计理念是尽量减少手动管理带来的复杂性和潜在错误。因此，Job ID 通常被视为系统内部的标识符。

**Comment by yaoyizhuo** [comment]
> 在Ray中，常规情况下，Job ID 是由系统自动生成的，并且不允许用户自定义。Ray 的设计理念是尽量减少手动管理带来的复杂性和潜在错误。因此，Job ID 通常被视为系统内部的标识符。

好的，所以ray面板中是查询不到具体的某个任务的嘛
