### ISSUE TITLE
萌新提问TEE

### ISSUE THREAD

**Issue by processpullulate** [secretflow/secretflow#16]
想请问一下，隐语框架针对TEE部分，是哪块的代码，基于TEE做了哪些算法

**Comment by zhouaihui** [comment]
目前TEE部分的代码暂未开放，不过后续的开源计划里有这块内容，敬请期待。

**Comment by icavan** [comment]
> 想请问一下，隐语框架针对TEE部分，是哪块的代码，基于TEE做了哪些算法

The TEE parts have not been released yet. SecretFlow plans to provide two ways to use TEE.

We rely on [Occlum](https://github.com/occlum/occlum) to migrate the existing AI/BI frameworks into TEE. They do a great job. SecretFlow will focus on building a TEE-based multi-party computation solution (different from single-party TEE computation) that provides typical machine learning and SQL functions. In this mode, nearly the whole computation will happen in TEE.

Another way to use TEE in SecretFlow is to put the crucial part in TEE only. Say in FedAVG, we could run secure aggregation in TEE while still computing gradients in the non-TEE world. In this way, we could get a much smaller TCB in TEE. This usage will be abstracted as a TEE device in SecretFlow.
