### ISSUE TITLE
隐语提供隐匿查询功能吗？ 就是PIR技术

### ISSUE THREAD

**Issue by miluoalbert** [secretflow/secretflow#160]
隐语提供隐匿查询功能吗？ 就是PIR技术

_Originally posted by @zhujinfang0819 in https://github.com/secretflow/secretflow/issues/154#issuecomment-1283901049_

**Comment by zhanglei486** [comment]
index/key不能重复；payload可以有重复，但有长度限制，一般在1024B以内

**Comment by zhujinfang0819** [comment]
有SealPIR的例子吗，学习一下，谢谢

**Comment by zhanglei486** [comment]
> 
目前secretflow还不支持pir，可以直接调用spu 的c++接口，示例可以参考seal_pir的单测代码
https://github.com/secretflow/spu/blob/main/spu/pir/seal_pir_test.cc

**Comment by xiaoqingzh** [comment]
请问针对sealPIR的上层封装在下个版本能提供出来么？谢谢！

**Comment by zhanglei486** [comment]
> 请问针对sealPIR的上层封装在下个版本能提供出来么？谢谢！

由于人力紧张，目前还没规划在下个版本中提供

**Comment by zhujinfang0819** [comment]
对于一个简单的查询语句比如age>=18, 没有index，也没有keyword。 这种情况 PIR能支持吗？

**Comment by zhanglei486** [comment]
> 对于一个简单的查询语句比如age>=18, 没有index，也没有keyword。 这种情况 PIR能支持吗？

PIR不支持，可以关注我们后续开源的SCQL产品，可以支持这种比较查询条件

**Comment by xiaoqingzh** [comment]
请问下关于PIR上层封装的版本有计划在啥时提供么

**Comment by zhanglei486** [comment]
> 请问下关于PIR上层封装的版本有计划在啥时提供么

暂时还没有，后续的研发规划还在讨论中，有具体结果后会对外发布的，请多关注，谢谢

**Comment by zhujinfang0819** [comment]
我看到隐语平台上有SCQL这个项目了，还没开源吗？

**Comment by rivertalk** [comment]
> 我看到隐语平台上有SCQL这个项目了，还没开源吗？

暂时还没有开源，敬请期待
