### ISSUE TITLE
支持多方联邦学习所需要的最低版本

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/secretflow#1610]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.6

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
您好，一些旧版本的部分组件是否只能支持两方联邦，比如1.6版本的训练集分割，里面有个判断联邦表是否是两方的断言函数，而最新版的代码则没有。如果我想稳定的实现多方，使用1.6版本（注释掉这些断言函数）是否能够做到？如果不行，那我至少需要更新到什么版本呢？

感谢帮助！
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by lanyy9527** [comment]
“注释掉这些断言函数” 是可以做到三方的，或者升级到1.7及以上的版本

**Comment by zzx-QDU** [comment]
好的，谢谢！
