### ISSUE TITLE
使用docker包0.7.7b1，运行文档例子，报错No module named 'secretflow.ml.boost.ss_xgb_v'

### ISSUE THREAD

**Issue by xiaojiu1414** [secretflow/secretflow#162]
通过以下文档安装了secretflow：
https://secretflow.readthedocs.io/zh_CN/latest/getting_started/installation.html#option-2-from-docker

安装的是https://hub.docker.com/layers/secretflow/secretflow-anolis8/0.7.7b1/images/sha256-1f9f98644b84c0bd696b55375be9012bf1cf3e1494a0e79e13f34739e2823a1d?context=explore

-------------------------------------------

运行以下代码：
```shell
import sys
import time
import logging

import spu
import secretflow as sf
from secretflow.ml.boost.ss_xgb_v import Xgb
from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay

from sklearn.metrics import roc_auc_score


# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# init all nodes in local Standalone Mode.
sf.init(['alice', 'bob', 'carol'])

# init PYU, the Python Processing Unit, process plaintext in each node.
alice = sf.PYU('alice')
bob = sf.PYU('bob')
carol = sf.PYU('carol')

# init SPU, the Secure Processing Unit,
#           process ciphertext under the protection of a multi-party secure computing protocol
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))

# read data in each party
def read_x(start, end):
    from sklearn.datasets import load_breast_cancer
    x = load_breast_cancer()['data']
    return x[:, start:end]

def read_y():
    from sklearn.datasets import load_breast_cancer
    return load_breast_cancer()['target']

# alice / bob / carol each hold one third of the features of the data
v_data = FedNdarray(
    partitions={
        alice: alice(read_x)(0, 10),
        bob: bob(read_x)(10, 20),
        carol: carol(read_x)(20, 30),
    },
    partition_way=PartitionWay.VERTICAL,
)
# Y label belongs to alice
label_data = FedNdarray(
    partitions={alice: alice(read_y)()},
    partition_way=PartitionWay.VERTICAL,
)
# wait IO finished
wait([p.data for p in v_data.partitions.values()])
wait([p.data for p in label_data.partitions.values()])

# run SS-XGB
xgb = Xgb(spu)
start = time.time()
params = {
    # for more detail, see Xgb API doc
    'num_boost_round': 5,
    'max_depth': 5,
    'learning_rate': 0.1,
    'sketch_eps': 0.08,
    'objective': 'logistic',
    'reg_lambda': 0.1,
    'subsample': 1,
    'colsample_bytree': 1,
    'base_score': 0.5,
}
model = xgb.train(params, v_data, label_data)
logging.info(f"train time: {time.time() - start}")

# Do predict
start = time.time()
# Now the result is saved in the spu by ciphertext
spu_yhat = model.predict(v_data)
# reveal for auc test.
yhat = reveal(spu_yhat)
logging.info(f"predict time: {time.time() - start}")
y = read_y()
logging.info(f"auc: {roc_auc_score(y, yhat)}")
```

-------------------------------------------

报错：

```
2022-10-21 01:27:23.470766: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
/app/venv/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 7
      5 import spu
      6 import secretflow as sf
----> 7 from secretflow.ml.boost.ss_xgb_v import Xgb
      8 from secretflow.device.driver import wait, reveal
      9 from secretflow.data import FedNdarray, PartitionWay

ModuleNotFoundError: No module named 'secretflow.ml.boost.ss_xgb_v'

```

**Comment by anakinxc** [comment]
请问一下你是不是在 secretflow 文件夹下运行的这个脚本呀

**Comment by xiaojiu1414** [comment]
> ```shell
> import sys
> import time
> import logging
> 
> import spu
> import secretflow as sf
> from secretflow.ml.boost.ss_xgb_v import Xgb
> from secretflow.device.driver import wait, reveal
> from secretflow.data import FedNdarray, PartitionWay
> 
> from sklearn.metrics import roc_auc_score
> 
> 
> # init log
> logging.basicConfig(stream=sys.stdout, level=logging.INFO)
> 
> # init all nodes in local Standalone Mode.
> sf.init(['alice', 'bob', 'carol'])
> 
> # init PYU, the Python Processing Unit, process plaintext in each node.
> alice = sf.PYU('alice')
> bob = sf.PYU('bob')
> carol = sf.PYU('carol')
> 
> # init SPU, the Secure Processing Unit,
> #           process ciphertext under the protection of a multi-party secure computing protocol
> spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))
> 
> # read data in each party
> def read_x(start, end):
>     from sklearn.datasets import load_breast_cancer
>     x = load_breast_cancer()['data']
>     return x[:, start:end]
> 
> def read_y():
>     from sklearn.datasets import load_breast_cancer
>     return load_breast_cancer()['target']
> 
> # alice / bob / carol each hold one third of the features of the data
> v_data = FedNdarray(
>     partitions={
>         alice: alice(read_x)(0, 10),
>         bob: bob(read_x)(10, 20),
>         carol: carol(read_x)(20, 30),
>     },
>     partition_way=PartitionWay.VERTICAL,
> )
> # Y label belongs to alice
> label_data = FedNdarray(
>     partitions={alice: alice(read_y)()},
>     partition_way=PartitionWay.VERTICAL,
> )
> # wait IO finished
> wait([p.data for p in v_data.partitions.values()])
> wait([p.data for p in label_data.partitions.values()])
> 
> # run SS-XGB
> xgb = Xgb(spu)
> start = time.time()
> params = {
>     # for more detail, see Xgb API doc
>     'num_boost_round': 5,
>     'max_depth': 5,
>     'learning_rate': 0.1,
>     'sketch_eps': 0.08,
>     'objective': 'logistic',
>     'reg_lambda': 0.1,
>     'subsample': 1,
>     'colsample_bytree': 1,
>     'base_score': 0.5,
> }
> model = xgb.train(params, v_data, label_data)
> logging.info(f"train time: {time.time() - start}")
> 
> # Do predict
> start = time.time()
> # Now the result is saved in the spu by ciphertext
> spu_yhat = model.predict(v_data)
> # reveal for auc test.
> yhat = reveal(spu_yhat)
> logging.info(f"predict time: {time.time() - start}")
> y = read_y()
> logging.info(f"auc: {roc_auc_score(y, yhat)}")
> ```

是在root下

**Comment by zhouaihui** [comment]
可以看下root目录下是否存在secretflow文件夹
