### ISSUE TITLE
想请教一下隐语支持用已训练好的keras神经网络模型做密态的推理吗？

### ISSUE THREAD

**Issue by beng003** [secretflow/secretflow#1625]
### Question Category

Usability

### Installation Source

Binary

### Secretflow Version

v1.10.0b1

### Operating System and Distribution

Linux Ubuntu 18.04

### Python Version

3.10.13

### Bazel Version

4.2.1

### GCC/Compiler Version

9.3.0

### Question Details

```shell
隐语支持用已训练好的keras神经网络模型做密态的推理吗？详情如下：
仅考虑推理预测部分，两方参与计算，一方以模型作为隐私数据（模型已经利用一些其他方法得到），另一方以样本作为隐私数据。数据以密文形式出域，数据和模型都以 SPUObject 形式交互
```

**Comment by BrainWH** [comment]
目前 spu 只支持 jax 生态，keras 不支持的。jax 可以参考官网文档：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/tutorial/gpt2_with_spu

**Comment by beng003** [comment]
> 目前 spu 只支持 jax 生态，keras 不支持的。jax 可以参考官网文档：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/tutorial/gpt2_with_spu

好的
