### ISSUE TITLE
xgboost水平联邦建模后，用xgboost加载进行预测，会出现报错，请问如何正确的进行预测

### ISSUE THREAD

**Issue by random-ticket** [secretflow/secretflow#1636]
### Question Category

Usability

### Installation Source

Binary

### Secretflow Version

1.9.0b2

### Operating System and Distribution

docker

### Python Version

3.10.13

### Question Details

```shell
联合建模时用的是csv数据源，报错training data did not have the following fields: id_card, month, day, type, amount，后面的这些fields都是我csv里的表头。
```

**Comment by BrainWH** [comment]
可以提供一下代码和使用的数据
