### ISSUE TITLE
SecretFlow计时问题

### ISSUE THREAD

**Issue by Runnoob123** [secretflow/secretflow#1644]
### Question Category

Performance

### Installation Source

Binary

### Secretflow Version

spu  0.9.3.dev20241118

### Operating System and Distribution

Linux Ubuntu 22.04

### Python Version

3.10.12

### Question Details

```shell
作者们您好！我最近在使用secretflow和spu进行一个模型的推理，我想请问secretflow是否支持对程序运行时间进行细致化计时并输出结果？我目前没在你们的官方文档里找到相关描述，我自己之前尝试在代码里使用python time库计时，但计时结果显著小于实际运行时间（例如，实际程序运行时间是300s，但我使用time库统计的时间只有25s），因此想请问计时方案，非常感谢！
```

**Comment by Chrisdehe** [comment]
目前使用运行计时是导包调用，如下：
``
import time
import logging


    logging.info(f"cost time: {time.time() - start}")

``
不知道能否解答你的问题

**Comment by Runnoob123** [comment]
> 目前使用运行计时是导包调用，如下： `` import time import logging
> 
> ```
> logging.info(f"cost time: {time.time() - start}")
> ```
> 
> `` 不知道能否解答你的问题
感谢！我尝试一下

**Comment by Runnoob123** [comment]
感觉不是很行/(ㄒoㄒ)/~~，结果和print(f"cost time: {time.time() - start}")一样，主要奇怪的是为什么在函数内部time计时的时间远小于在函数外面对函数整体time计时的时间

**Comment by Chrisdehe** [comment]
@Runnoob123 
辛苦贴一下代码，以及运行出来的日志。

**Comment by Chrisdehe** [comment]
@Runnoob123 
记录全局时间可以尝试使用time命令，例如
`time ls`
`time python your_script.py`
它会输出三个时间指标：real、user 和 sys。（user+sys=real）
其中
- real 时间 是你最直观感受到的时间，包括了所有等待时间和实际计算时间。
- user 时间 反映了你的代码在 CPU 上实际运行的时间。
- sys 时间 反映了操作系统在处理你的代码时所花费的时间，比如文件 I/O、网络 I/O 等。

**Comment by Runnoob123** [comment]
感谢您的指导与解答，没有问题了，非常感谢！
