### ISSUE TITLE
高可用的实现方案

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/secretflow#1649]
### Question Category

Build/Installation

### Installation Source

Binary

### Secretflow Version

v1.6.1b0

### Operating System and Distribution

Ubuntu 22.04

### Python Version

3.10

### Question Details

```shell
您好，隐语是否考虑过高可用的实现方案？我们现在是通过Secretflow+Kuscia实现的联邦学习，想要实现高可用，希望了解一下官方对高可用的设计理念或看法。

感谢帮助！
```

**Comment by BrainWH** [comment]
如果是 docker 组网部署，参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.13.0b0/deployment/Docker_deployment_kuscia/deploy_clustered_cn
如果是  k8s 的话，部署 Kuscia 多副本即可

**Comment by zzx-QDU** [comment]
这种方式应该是每个参与方一台机器，然后这台机器上有多个容器。如果我们是每个参与方有多台机器，希望实现机器的高可用，应该如何处理呢？

**Comment by BrainWH** [comment]
docker 组网部署，官网结构图示中，以 Alice 为 2 台机器组网示例，和 Bob 方创建任务时，任务会随机分配到 Alice 中的其中一台，达到高可用的目的 : https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.13.0b0/deployment/Docker_deployment_kuscia/deploy_clustered_cn

**Comment by zzx-QDU** [comment]
好的 非常感谢您的帮助！
