### ISSUE TITLE
请问有关已经实现的ABY3与SPDZ-2K文件所在位置

### ISSUE THREAD

**Issue by chenggang12138** [secretflow/secretflow#165]
### Issue Type

Others

### Source

source

### Secretflow Version

0.6.13b0

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
想要了解有关ABY3文件，请问相关源代码文件的位置
```

### Reproduction code to reproduce the issue.

```shell
ABY3文件的位置
```

**Comment by anakinxc** [comment]
Hi,

感谢关照，相关代码在 spu repo 的 spu/mpc 文件夹内

Best

**Comment by chenggang12138** [comment]
谢谢，找到了

**Comment by tarantula-leo** [comment]
> Hi,
> 
> 感谢关注，相关代码在 spu repo 的 spu/mpc 文件夹内
> 
> Best

您好 有两个问题想问下：
1. SEMI2k里面设计三元组内容的代码在哪里？默认是由其中一方生成的吗？
2. 3PC的conf文件里 Nodes为什么匹配了五个？

**Comment by rivertalk** [comment]
> SEMI2k里面设计三元组内容的代码在哪里？默认是由其中一方生成的吗？

Beaver Provider被设计成是可配置的，可以由密码学算法生成，或者使用可信第三方、可信第一方 来生成。目前SEMI2K使用第一方生成的，不建议生产使用。
PS: 可以考虑使用CHEETAH协议，他的Beaver是由密码学算法(HE/OT)生成的

> 3PC的conf文件里 Nodes为什么匹配了五个？

其中两个是 数据提供方，也就是 PYU，三个是计算提供方，共同执行ABY3协议

**Comment by 6fj** [comment]
Hi @tarantula-leo 

补充一下，请参考https://spu.readthedocs.io/en/latest/reference/mpc_status.html 理解spu中支持的mpc协议。

感谢。

**Comment by tarantula-leo** [comment]
> > SEMI2k里面设计三元组内容的代码在哪里？默认是由其中一方生成的吗？
> 
> Beaver Provider被设计成是可配置的，可以由密码学算法生成，或者使用可信第三方、可信第一方 来生成。目前SEMI2K使用第一方生成的，不建议生产使用。 PS: 可以考虑使用CHEETAH协议，他的Beaver是由密码学算法(HE/OT)生成的
> 
> > 3PC的conf文件里 Nodes为什么匹配了五个？
> 
> 其中两个是 数据提供方，也就是 PYU，三个是计算提供方，共同执行ABY3协议

您好，想问下这里的不建议生成使用指的是使用第一方的SEMI2k还是说整个SPU？比如 有可信方的SEMI2K、CHEETAH、ABY3这些适用于生成环境吗？ 或者是SPU必须集成在SF里才适用于生产环境呢？

**Comment by icavan** [comment]
> > > SEMI2k里面设计三元组内容的代码在哪里？默认是由其中一方生成的吗？
> > 
> > 
> > Beaver Provider被设计成是可配置的，可以由密码学算法生成，或者使用可信第三方、可信第一方 来生成。目前SEMI2K使用第一方生成的，不建议生产使用。 PS: 可以考虑使用CHEETAH协议，他的Beaver是由密码学算法(HE/OT)生成的
> > > 3PC的conf文件里 Nodes为什么匹配了五个？
> > 
> > 
> > 其中两个是 数据提供方，也就是 PYU，三个是计算提供方，共同执行ABY3协议
> 
> 您好，想问下：
> 
> 1. 这里的不建议生成使用指的是使用第一方的SEMI2k还是说整个SPU？比如 有可信方的SEMI2K、CHEETAH、ABY3这些适用于生成环境吗？ 或者是SPU必须集成在SF里才适用于生产环境呢？
> 2. Beaver Provider被设计成是可配置的，是在哪个部分的代码中设计的？

1、 不建议生产使用是指 aby3 这类 3PC 协议，其默认安全假设是三个计算主体大多数诚实可信，这个安全假设不总是成立的，因此需要用户`确认`自己的场景满足三个主体里至少两个不作恶的设定，方能用于生产。和是否在 SF 里使用没有关系。

2、 Beaver Provider  https://github.com/secretflow/spu/tree/main/spu/mpc/beaver 目前只是提供了一个 Trusted First Party 的 mock 实现，以及 Cheetah 的实现。你可以看到他预留了接口类，后续版本会提供基于 VOLE 的 2PC 生成 beaver triplet 协议（也是一个 2pc 协议），以及软硬结合比如基于 TEE 的 Triplet 生成（性能较好）等多种可选模式。

**Comment by tarantula-leo** [comment]
想问下Beaver文件中的beaver_tfp和beaver_ref的作用是什么？

**Comment by 6fj** [comment]
Hi @tarantula-leo 


beaver_tfp指的是Trust First Party的beaver triple生成器，具体作用请看上面 @icavan 回答的第二点。

beaver_ref是测试使用，无需关注。

感谢。
