### ISSUE TITLE
如何增加Secretflow实际运行SPU设备时的Thead Pool Size

### ISSUE THREAD

**Issue by Runnoob123** [secretflow/secretflow#1651]
### Question Category

Usability

### Installation Source

Binary

### Secretflow Version

spu  0.9.3.dev20241118

### Operating System and Distribution

Linux Ubuntu 22.04

### Python Version

3.10.12

### Question Details

```shell
您好！我想请问一下在实际使用SPU运行程序时，为什么在不同设备上的下列信息的Thread Pool Size不同？
(SPURuntime pid=xxx) xxx-xxx-xxx xxx:xxx:xxx.xxx [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size xxx
例如，我在两台服务器上运行一模一样的程序时，一个程序的Thread Pool Size是127，而另一个程序的Thread Pool Size是95，我想请问是什么造成了这两者之间的差异？以及是否有办法增大Thread Pool Size（例如调整其从95到127），谢谢！
```

**Comment by BrainWH** [comment]
您好，spu 可以配置的。spu 创建 RuntimeConfig 对象并设置 max_concurrency。具体的你可以看下 spu 的代码： libspu/core/context.cc 里面的 set_num_threads

**Comment by Runnoob123** [comment]
> 您好，spu 可以配置的。spu 创建 RuntimeConfig 对象并设置 max_concurrency。具体的你可以看下 spu 的代码： libspu/core/context.cc 里面的 set_num_threads

非常感谢！我这就试一试

**Comment by Runnoob123** [comment]
> 您好，spu 可以配置的。spu 创建 RuntimeConfig 对象并设置 max_concurrency。具体的你可以看下 spu 的代码： libspu/core/context.cc 里面的 set_num_threads

感谢您的解答，问题已解决，您的解答非常有效👍
