### ISSUE TITLE
横向联邦学习的例子有提供吗？

### ISSUE THREAD

**Issue by zhujinfang0819** [secretflow/secretflow#167]
### Issue Type

Others

### Source

source

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.18.13

### GCC/Compiler version

11.2.0

### What happend and What you expected to happen.

```shell
想找个联邦学习的例子运行一下，有具体的操作步骤和调用代码吗？
```

### Reproduction code to reproduce the issue.

```shell
运行一个横向联邦学习的方法是什么？
```

**Comment by zhouaihui** [comment]
hi, @zhujinfang0819 , 可以阅读教程 [水平联邦：图像分类](https://secretflow.readthedocs.io/zh_CN/latest/tutorial/Federate_Learning_for_Image_Classification.html)
