### ISSUE TITLE
CentOS7下secretflow安装问题

### ISSUE THREAD

**Issue by Wyyyb** [secretflow/secretflow#17]
CentOS7创建虚拟环境py=3.8，执行pip install -U secretflow后import secretflow报错。

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/20929360/177730993-0bc3b210-975c-4a70-a705-e04c329bf642.png">

**Comment by zhouaihui** [comment]
抱歉，这个原因是我们的一个库依赖了较高版本的glibc，我们正在处理。有更新后我们尽快通知。

你可以使用docker来安装secretflow吗？镜像： registry.hub.docker.com/secretflow/spu-gcc11-anolis-dev:latest

**Comment by Wyyyb** [comment]
好的 感谢解答

**Comment by zhouaihui** [comment]
可以试试 secretflow==0.6.13b1，这个版本降低了对glibc版本的要求
