### ISSUE TITLE
集群建模卡死问题

### ISSUE THREAD

**Issue by patricxu** [secretflow/secretflow#172]
双机集群卡死问题。配置和代码如下。请问是哪里出了问题？
head 机器
`ray start --head --node-ip-address=10.114.16.143 --port=8001 --include-dashboard=False --disable-usage-stats`
worker机器（实际IP 10.114.16.142)
` ray start --address='10.114.16.143:8001'`

` import secretflow as sf
sf.shutdown()
sf.init(address='10.114.16.143:8001')

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.114.16.143:8002',
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.114.16.142:8003',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

alice, bob = sf.PYU('alice', node='node_a'), sf.PYU('bob', node='node_b')
clus_spu = sf.SPU(cluster_def=cluster_def)

from secretflow.data.horizontal import read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator
from secretflow.utils.simulation.datasets import load_dermatology

aggr = SecureAggregator(alice, [alice, bob])
comp = SPUComparator(clus_spu)
print(comp)
data = load_dermatology(parts=[alice, bob], aggregator=aggr,
                        comparator=comp)`

**Comment by zhouaihui** [comment]
hi，@patricxu 
1. 使用`ray status`查看下集群状态
2. 屏幕输出日志麻烦提供下

**Comment by patricxu** [comment]
找到问题了。集群配置不正确！启动ray的时候需要指定名称。
