### ISSUE TITLE
Malicious party can use `ray.get()` to get the private data of other parties. 

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/secretflow#174]
### Issue Type

Bug

### Source

source

### Secretflow Version

secretflow 0.7.7b1

### OS Platform and Distribution

Linux ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

Hi,
I'm worried about the security issue when SecretFlow uses `ray cluster` to manage the task of parties.

For example,`bob` run the following code:
```
import jax.numpy as np
alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')

v_alice_path = "/shared/data0.csv"
v_bob_path = "/shared/sf_test/data1.csv"
v_carol_path = "/shared/data2.csv"

def load_data(path):
    x = pd.read_csv(path, index_col=0)
    return x.to_numpy()

def mul(a, b, c):
    tmp = np.concatenate((a, b, c), axis=0)
    return np.var(tmp)

alice_pyu = alice(load_data)(v_alice_path)
bob_pyu = bob(load_data)(v_bob_path)
carol_pyu = carol(load_data)(v_carol_path)
```
The attribute `data` of `alice_pyu` can be used to get the private data of `alice` using `ray.get(data)`, which is not security. So how to prevent this situation in production environment?

**Comment by zhouaihui** [comment]
hi, @BeStrongok, thanks for this good question!

Single ray cluster is designed  for convenient and fast simulation. Multiple ray clusters will be used in production environment. That means each party will own an independent ray cluster and code will be executed simultaneously among parties. Please stay tuned for this upcoming feature.

**Comment by BeStrongok** [comment]
> hi, @BeStrongok, thanks for this good question!
> 
> Single ray cluster is designed for convenient and fast simulation. Multiple ray clusters will be used in production environment. That means each party will own an independent ray cluster and code will be executed simultaneously among parties. Please stay tuned for this upcoming feature.

Thanks! Looking for this feature!

**Comment by BeStrongok** [comment]
> hi, @BeStrongok, thanks for this good question!
> 
> Single ray cluster is designed for convenient and fast simulation. Multiple ray clusters will be used in production environment. That means each party will own an independent ray cluster and code will be executed simultaneously among parties. Please stay tuned for this upcoming feature.

BTW, I think you should point out this situation in the deployment document [here](https://secretflow.readthedocs.io/zh_CN/latest/getting_started/deployment.html#cluster-mode).
Single ray cluster between parties bring the issues of backdoor attacks by malicious party, which is dangerous.

**Comment by tarantula-leo** [comment]
> hi, @BeStrongok, thanks for this good question!
> 
> Single ray cluster is designed for convenient and fast simulation. Multiple ray clusters will be used in production environment. That means each party will own an independent ray cluster and code will be executed simultaneously among parties. Please stay tuned for this upcoming feature.

想问下使用集群模式的时候加上RAY_DISABLE_REMOTE_CODE=true，使用sf.reveal依旧可以看到其它方节点的数据，是需要另外设置什么参数才能保证安全性吗？
类似如下代码在A节点上运行，可以看到B机器上的数据：
alice, bob= sf.PYU('alice'), sf.PYU('bob')
def load_data(file):
    import pandas as pd
    return pd.read_csv(file).values
a: sf.PYUObject = alice(load_data)('/usr/cyx/.data/a.csv')
b: sf.PYUObject = bob(load_data)('/usr/cyx/.data/b.csv')
print(sf.reveal(b))

**Comment by zhouaihui** [comment]
SF建议仅在必要的控制流和debug的时候使用reveal，但是没有强制性的检查。参见 #178 

在实际生产模式，每个机构都是独立的ray集群（这个功能即将发布），代码是机构经过审核之后执行的，机构可以确认自己执行的代码是否安全。比如，Bob看到代码中alice在非法读取不需要的数据，则bob可以拒绝执行这份代码。

**Comment by tarantula-leo** [comment]
> SF建议仅在必要的控制流和debug的时候使用reveal，但是没有强制性的检查。参见 #178
> 
> 在实际生产模式，每个机构都是独立的ray集群（这个功能即将发布），代码是机构经过审核之后执行的，机构可以确认自己执行的代码是否安全。比如，Bob看到代码中alice在非法读取不需要的数据，则bob可以拒绝执行这份代码。

想问下如何保证Alice执行的是审核后的代码，或者说审核后Alice不能够进行篡改以获取对方数据呢？
RAY_DISABLE_REMOTE_CODE=true这个参数是否可以阻止reveal操作来保证安全性？

**Comment by zhouaihui** [comment]
1. RAY_DISABLE_REMOTE_CODE 参数仅仅是防止driver下发非本地定义的方法。
2. 在即将发布的多控制器模式下，代码是需要每一方都同时执行才能work的。目前单个ray集群的模式适用于simulation。

**Comment by tarantula-leo** [comment]
> 1. RAY_DISABLE_REMOTE_CODE 参数仅仅是防止driver下发非本地定义的方法。
> 2. 在即将发布的多控制器模式下，代码是需要每一方都同时执行才能work的。目前单个ray集群的模式适用于simulation。

谢谢解答！下个版本大概会在什么时间发布呢？是否会按之前的开源计划上新增可视化界面和资源管理层？

**Comment by zhouaihui** [comment]
> > 1. RAY_DISABLE_REMOTE_CODE 参数仅仅是防止driver下发非本地定义的方法。
> > 2. 在即将发布的多控制器模式下，代码是需要每一方都同时执行才能work的。目前单个ray集群的模式适用于simulation。
> 
> 谢谢解答！下个版本大概会在什么时间发布呢？是否会按之前的开源计划上新增可视化界面和资源管理层？ 另有两个地方的注释可能有问题，可以看下：
> 
> 1. https://github.com/secretflow/secretflow/blob/main/tests/data/test_partition.py
>    test_setitem_on_different_partition_should_ok 是否应改为wrong
> 2. secretflow/ml/boost/homo_boost/tree_core/criterion.py
>    def node_gain(self, sum_grad: float, sum_hess: float) -> float:
>    """Calculate not gain
>    是否应改为node

感谢指出，您方便直接提个pr来修改吗？

**Comment by pchyuan** [comment]
> > 1. RAY_DISABLE_REMOTE_CODE 参数仅仅是防止driver下发非本地定义的方法。
> > 2. 在即将发布的多控制器模式下，代码是需要每一方都同时执行才能work的。目前单个ray集群的模式适用于simulation。
> 
> 谢谢解答！下个版本大概会在什么时间发布呢？是否会按之前的开源计划上新增可视化界面和资源管理层？ 另有两个地方的注释可能有问题，可以看下：
> 
> 1. https://github.com/secretflow/secretflow/blob/main/tests/data/test_partition.py
>    test_setitem_on_different_partition_should_ok 是否应改为wrong
> 2. secretflow/ml/boost/homo_boost/tree_core/criterion.py
>    def node_gain(self, sum_grad: float, sum_hess: float) -> float:
>    """Calculate not gain
>    是否应改为node

感谢您对隐语计划的关注！
我们预计在下周会发布一个小的版本，提供金融场景全链路建模需要用到的算法，以及在PSI，联邦学习，以及基础设备层的一些优化；
可视化及资源管理计划明年Q1发布，也欢迎对具体希望提供的功能点提建议，方便我们对开发的优先级进行对应调整。

**Comment by tarantula-leo** [comment]
> > > 1. RAY_DISABLE_REMOTE_CODE 参数仅仅是防止driver下发非本地定义的方法。
> > > 2. 在即将发布的多控制器模式下，代码是需要每一方都同时执行才能work的。目前单个ray集群的模式适用于simulation。
> > 
> > 
> > 谢谢解答！下个版本大概会在什么时间发布呢？是否会按之前的开源计划上新增可视化界面和资源管理层？ 另有两个地方的注释可能有问题，可以看下：
> > 
> > 1. https://github.com/secretflow/secretflow/blob/main/tests/data/test_partition.py
> >    test_setitem_on_different_partition_should_ok 是否应改为wrong
> > 2. secretflow/ml/boost/homo_boost/tree_core/criterion.py
> >    def node_gain(self, sum_grad: float, sum_hess: float) -> float:
> >    """Calculate not gain
> >    是否应改为node
> 
> 感谢指出，您方便直接提个pr来修改吗？

已经提交Pr。

**Comment by zhouaihui** [comment]
hi, @BeStrongok, SecretFlow 0.7.18b0 is available now, you can get the production mode tutorials on [deployment](https://www.secretflow.org.cn/docs/secretflow/en/getting_started/deployment.html#).

In production mode，malicious party can not use `ray.get` to get the data from other parties since every party has its own ray cluster.
