### ISSUE TITLE
secretflow联邦学习能否对接更复杂的深度学习任务，比如目标检测？

### ISSUE THREAD

**Issue by cs1317** [secretflow/secretflow#175]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

mac

### Python version

3.8.0

### What happend and What you expected to happen.

```shell
secretflow联邦学习能否对接更复杂的深度学习任务，比如目标检测？
```

### Reproduction code to reproduce the issue.

```shell
#
```

**Comment by longshan-ant** [comment]
是一个横向的NN任务，还是一个纵向的NN任务？

**Comment by zhangxingmeng** [comment]
理论上是可以的，欢迎使用FLModel进行尝试，如果遇到什么问题，可以随时沟通。
