### ISSUE TITLE
from secretflow.ml.boost.ss_xgb_v import Xgb 保存模型

### ISSUE THREAD

**Issue by junzlovegood** [secretflow/secretflow#177]
from secretflow.ml.boost.ss_xgb_v import Xgb
model = xgb.train(params, v_train_data, label_train_data)
使用ss-xgb训练得到的模型，应该如何保存到两方中

**Comment by rivertalk** [comment]
Hi @junzlovegood 这是个很好的问题～

目前，隐语暂时还没有开发模型存储和加载的API，所以暂时没有很方便的方法可以存取模型

相关的功能在SPU中以及有了“实验性”支持，会在隐语中逐步开放，详情见这里
https://github.com/secretflow/spu/blob/94f437c151cbc7e4e12f6bcf8c63a6310c41ad75/examples/python/ml/jax_lr.py#L134

**Comment by da-niao-dan** [comment]
现在通过组件模式调用保存模型 已经得到了支持。
