### ISSUE TITLE
Is there any limitation to reveal data?

### ISSUE THREAD

**Issue by kanppa** [secretflow/secretflow#178]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

docker

### Python version

3.8

### What happend and What you expected to happen.

```shell
Deployed as https://github.com/secretflow/secretflow/discussions/164 instructed utilizing cluster mode. I created a vertical dataframe, and there's no limitation revealing data in driver.
```

### Reproduction code to reproduce the issue.

```shell
Cluster def:

sf.init(address="192.168.99.131:6379")
alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_def = {
        'nodes': [
            {
                'party': 'alice',
                'id': '0',
                # Use the address and port of alice instead.
                # Please choose a unused port.
                'address': '192.168.99.131:9327',
            },
            {
                'party': 'bob',
                'id': '1',
                # Use the ip and port of bob instead.
                # Please choose a unused port.
                'address': '192.168.99.131:9328',
            },
        ],
        'runtime_config': {
            'protocol': spu.spu_pb2.SEMI2K,
            'field': spu.spu_pb2.FM128,
            'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
        }
    }
spu = sf.SPU(cluster_def=cluster_def)

# creating vertical dataframe.

from secretflow.data.vertical import read_csv
v_df = read_csv({alice: '.data/alice.csv', bob: '.data/bob.csv'}, spu=spu, keys='uid')



Revealing both data in driver will succeed.

sf.reveal(v_df.partitions[bob].values)
sf.reveal(v_df.partitions[alice].values)
```

**Comment by zhouaihui** [comment]
Minimize usage of `reveal` is strongly recommended, even `reveal` has no mandatory restrictions for now. Some best practices of using `reveal`

1. in some control flow. E.g., if a control condition comes from a party and then reveal is good to use here.
2. for debug purpose.

**Comment by icavan** [comment]
> ### Issue Type
> Others
> 
> ### Source
> binary
> 
> ### Secretflow Version
> 0.7.7b1
> 
> ### OS Platform and Distribution
> docker
> 
> ### Python version
> 3.8
> 
> ### Bazel version
> _No response_
> 
> ### GCC/Compiler version
> _No response_
> 
> ### What happend and What you expected to happen.
> ```shell
> Deployed as https://github.com/secretflow/secretflow/discussions/164 instructed utilizing cluster mode. I created a vertical dataframe, and there's no limitation revealing data in driver.
> ```
> 
> ### Reproduction code to reproduce the issue.
> ```shell
> Cluster def:
> 
> sf.init(address="192.168.99.131:6379")
> alice, bob = sf.PYU('alice'), sf.PYU('bob')
> 
> cluster_def = {
>         'nodes': [
>             {
>                 'party': 'alice',
>                 'id': '0',
>                 # Use the address and port of alice instead.
>                 # Please choose a unused port.
>                 'address': '192.168.99.131:9327',
>             },
>             {
>                 'party': 'bob',
>                 'id': '1',
>                 # Use the ip and port of bob instead.
>                 # Please choose a unused port.
>                 'address': '192.168.99.131:9328',
>             },
>         ],
>         'runtime_config': {
>             'protocol': spu.spu_pb2.SEMI2K,
>             'field': spu.spu_pb2.FM128,
>             'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
>         }
>     }
> spu = sf.SPU(cluster_def=cluster_def)
> 
> # creating vertical dataframe.
> 
> from secretflow.data.vertical import read_csv
> v_df = read_csv({alice: '.data/alice.csv', bob: '.data/bob.csv'}, spu=spu, keys='uid')
> 
> 
> 
> Revealing both data in driver will succeed.
> 
> sf.reveal(v_df.partitions[bob].values)
> sf.reveal(v_df.partitions[alice].values)
> ```

In the[ production mode](https://github.com/secretflow/secretflow/issues/174), the algorithm codes will be fixed on your local side. Then you do not have to worry about some malicious party calling improper `reveal`.

**Comment by kanppa** [comment]
> > ### Issue Type
> > Others
> > ### Source
> > binary
> > ### Secretflow Version
> > 0.7.7b1
> > ### OS Platform and Distribution
> > docker
> > ### Python version
> > 3.8
> > ### Bazel version
> > _No response_
> > ### GCC/Compiler version
> > _No response_
> > ### What happend and What you expected to happen.
> > ```shell
> > Deployed as https://github.com/secretflow/secretflow/discussions/164 instructed utilizing cluster mode. I created a vertical dataframe, and there's no limitation revealing data in driver.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Reproduction code to reproduce the issue.
> > ```shell
> > Cluster def:
> > 
> > sf.init(address="192.168.99.131:6379")
> > alice, bob = sf.PYU('alice'), sf.PYU('bob')
> > 
> > cluster_def = {
> >         'nodes': [
> >             {
> >                 'party': 'alice',
> >                 'id': '0',
> >                 # Use the address and port of alice instead.
> >                 # Please choose a unused port.
> >                 'address': '192.168.99.131:9327',
> >             },
> >             {
> >                 'party': 'bob',
> >                 'id': '1',
> >                 # Use the ip and port of bob instead.
> >                 # Please choose a unused port.
> >                 'address': '192.168.99.131:9328',
> >             },
> >         ],
> >         'runtime_config': {
> >             'protocol': spu.spu_pb2.SEMI2K,
> >             'field': spu.spu_pb2.FM128,
> >             'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
> >         }
> >     }
> > spu = sf.SPU(cluster_def=cluster_def)
> > 
> > # creating vertical dataframe.
> > 
> > from secretflow.data.vertical import read_csv
> > v_df = read_csv({alice: '.data/alice.csv', bob: '.data/bob.csv'}, spu=spu, keys='uid')
> > 
> > 
> > 
> > Revealing both data in driver will succeed.
> > 
> > sf.reveal(v_df.partitions[bob].values)
> > sf.reveal(v_df.partitions[alice].values)
> > ```
> 
> In the[ production mode](https://github.com/secretflow/secretflow/issues/174), the algorithm codes will be fixed on your local side. Then you do not have to worry about some malicious party calling improper `reveal`.

Any tutorial for production mode deployment? Meanwhile showcases for how to verify data flows securely between different parties under the hood will be very helpful.

**Comment by zhouaihui** [comment]
hi, @kanppa, SecretFlow 0.7.18b0 is available now, you can get the production mode tutorials on [deployment](https://www.secretflow.org.cn/docs/secretflow/en/getting_started/deployment.html#)
