### ISSUE TITLE
源码安装异常

### ISSUE THREAD

**Issue by ychy00001** [secretflow/secretflow#181]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

main分支最新代码

### OS Platform and Distribution

Linux CentOS 7.9

### Python version

Python 3.8.13

### Bazel version

2.0.0

### GCC/Compiler version

gcc (GCC) 4.8.5

### What happend and What you expected to happen.

```shell
执行：源码安装文档第二步，安装SecretFlow
python setup.py bdist_wheel 

运行异常，异常见后面代码
```

### Reproduction code to reproduce the issue.

```shell
(/data/conda_env/secretflow) [app@sjyjy-xhml-dev-algorithm-4bi8ik secretflow]$ python --version
Python 3.8.13
(/data/conda_env/secretflow) [app@sjyjy-xhml-dev-algorithm-4bi8ik secretflow]$ bazel --version
bazel 2.0.0
(/data/conda_env/secretflow) [app@sjyjy-xhml-dev-algorithm-4bi8ik secretflow]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(/data/conda_env/secretflow) [app@sjyjy-xhml-dev-algorithm-4bi8ik secretflow]$ python setup.py bdist_wheel
Requirements:  ['numpy==1.22.3', 'protobuf==3.19.4', 'six==1.16.0', 'dill==0.3.4', 'jax==0.3.7', 'jaxlib==0.3.7', 'tensorflow_datasets==4.5.2', 'absl-py==1.0.0', 'flax==0.4.1', 'cloudpickle==2.0.0', 'networkx~=2.8', '', 'dgl>=0.9.0', 'pandas==1.4.0', 'pyarrow', 'scikit-learn==1.0.2', 'secretflow-ray==2.0.0.dev1', 'tensorflow==2.7.1; platform_machine != "arm64"', 'tensorflow-macos==2.7.0; platform_machine == "arm64" and platform_system == "Darwin"', 'torch==1.10.1', 'torchvision==0.11.2', 'torchmetrics==0.9.2', '', 's3fs==2022.1.0', 'xgboost==1.5.2', 'validator.py==1.3.0', 'tqdm==4.62.3', 'loguru==0.6.0', 'statsmodels==0.13.2', '', 'matplotlib==3.5.2', 'multiprocess==0.70.12.2', 'cachetools==5.2.0', '', '# for tests', 'psutil==5.9.0', 'coverage', 'unittest-xml-reporting', 'spu==0.2.4b1', 'sf-heu==0.2.0b0']
running bdist_wheel
running build
running build_py
running build_ext
bazel build //secretflow_lib/binding:_lib.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --compilation_mode=opt
DEBUG: Rule 'yasl' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1663642727 +0800"
DEBUG: Call stack for the definition of repository 'yasl' which is a git_repository (rule definition at /home/app/.cache/bazel/_bazel_app/f22b3e0a54cb9a69c2a53b63767f0d88/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /data/mpc/secretflow/WORKSPACE:5:1
ERROR: /home/app/.cache/bazel/_bazel_app/f22b3e0a54cb9a69c2a53b63767f0d88/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9: //external:simplest_ot: no such attribute 'recursive_init_submodules' in 'git_repository' rule
ERROR: error loading package '': Encountered error while reading extension file 'foreign_cc/repositories.bzl': no such package '@rules_foreign_cc//foreign_cc': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'foreign_cc/repositories.bzl': no such package '@rules_foreign_cc//foreign_cc': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.118s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
error: command '/data/opt/bazel/bin/bazel' failed with exit code 1
```

**Comment by rivertalk** [comment]
看上去 `recursive_init_submodules` attribute 在 bazel 2.0.0 没有支持
https://docs.bazel.build/versions/2.0.0/repo/git.html

请升级到 bazel 5.1.1 再尝试build，详见
https://github.com/secretflow/secretflow/blob/main/.bazeliskrc

祝您生活愉快

**Comment by ychy00001** [comment]
> 看上去 `recursive_init_submodules` attribute 在 bazel 2.0.0 没有支持 https://docs.bazel.build/versions/2.0.0/repo/git.html
> 
> 请升级到 bazel 5.1.1 再尝试build，详见 https://github.com/secretflow/secretflow/blob/main/.bazeliskrc
> 
> 祝您生活愉快

各种工具版本也都升级了，还是有异常，求助
目前发现的错误信息： fatal: unable to open include file `os.inc'，没有查找到相关解决方案


gcc (GCC) version 11.2.1
cmake version 3.23.2
bazel version 5.1.1 
ninjia version 1.12.0.git
NASM version 2.10.07


`[773/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptdesdecryptcbcpxca.c.o
[774/7518] Building ASM_NASM object sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm.o
FAILED: sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm.o
/bin/nasm -I/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/external/com_github_intel_ipp/sources/include -I/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/external/com_github_intel_ipp/sources/ippcp/asm_intel64 -Dlinux -DLINUX32E -D_ARCH_EM64T -DIPP_PIC -MD sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm.o.d -MT sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm.o -D_M7 -D_MERGED_BLD -f elf64 -o sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm.o /root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp.build_tmpdir/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm
/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp.build_tmpdir/asm_sources/m7/asm_intel64/m7_aes_keyexp_128.asm:18: fatal: unable to open include file `os.inc'
[775/7518] Building ASM_NASM object sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm.o
FAILED: sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm.o
/bin/nasm -I/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/external/com_github_intel_ipp/sources/include -I/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/external/com_github_intel_ipp/sources/ippcp/asm_intel64 -Dlinux -DLINUX32E -D_ARCH_EM64T -DIPP_PIC -MD sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm.o.d -MT sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm.o -D_M7 -D_MERGED_BLD -f elf64 -o sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm.o /root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp.build_tmpdir/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm
/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp.build_tmpdir/asm_sources/m7/asm_intel64/m7_aes_keyexp_192.asm:18: fatal: unable to open include file `os.inc'
[776/7518] Building ASM_NASM object sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm.o
FAILED: sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm.o
/bin/nasm -I/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/external/com_github_intel_ipp/sources/include -I/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/external/com_github_intel_ipp/sources/ippcp/asm_intel64 -Dlinux -DLINUX32E -D_ARCH_EM64T -DIPP_PIC -MD sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm.o.d -MT sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm.o -D_M7 -D_MERGED_BLD -f elf64 -o sources/ippcp/CMakeFiles/ippcp_s_m7-asmobjs.dir/__/__/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm.o /root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp.build_tmpdir/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm
/root/.cache/bazel/_bazel_root/f22b3e0a54cb9a69c2a53b63767f0d88/sandbox/processwrapper-sandbox/42/execroot/secretflow/bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp.build_tmpdir/asm_sources/m7/asm_intel64/m7_aes_keyexp_256.asm:18: fatal: unable to open include file `os.inc'
[777/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptdesdecryptecbca.c.o
[778/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptdesencryptcbcpx.c.o
[779/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptdesencryptecbca.c.o
[780/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptdesencryptcfbca.c.o
[781/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcpver.c.o
[782/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptrngenhwca.c.o
[783/7518] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_pcptdesofbca.c.o
ninja: build stopped: subcommand failed.
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp_foreign_cc/CMake.log

Target //secretflow_lib/binding:_lib.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /data/mpc/secretflow/secretflow_lib/binding/BUILD.bazel:13:17 Linking secretflow_lib/binding/_lib.so failed: (Exit 1): bash failed: error executing command /bin/bash -c bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 452.765s, Critical Path: 67.90s
INFO: 56 processes: 15 internal, 41 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
error: command '/data/opt/bazel/bin/bazel' failed with exit code 1`

**Comment by rivertalk** [comment]
hi @ychy00001 

看上去是 nasm版本有些低，ippcp要求nasm>=2.15 ，可以升级再尝试一下吗？

具体的版本要求在这里
https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux

nasm 编译安装详见
https://github.com/secretflow/secretflow/blob/dbfe8c3f8bf4691f51f080f3985beee8cc339882/docker/sf-gcc11-centos7-release.Dockerfile#L24

**Comment by ychy00001** [comment]
> hi @ychy00001
> 
> 看上去是 nasm版本有些低，ippcp要求nasm>=2.15 ，可以升级再尝试一下吗？
> 
> 具体的版本要求在这里 https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux
> 
> nasm 编译安装详见
> 
> https://github.com/secretflow/secretflow/blob/dbfe8c3f8bf4691f51f080f3985beee8cc339882/docker/sf-gcc11-centos7-release.Dockerfile#L24


搞定，非常感谢，附上CentOS的简易安装流程，有需要的话自取


# 概述
• 操作系统：CentOS 7.9
• 使用用户（自己创建）：app
• Secretflow安装目录： /data/mpc
• 依赖工具安装目录：/data/opt
• Python虚拟环境（自己安装）：Miniconda（https://conda.io/projects/conda/en/latest/user-guide/install/linux.html）
• Python 3.8
• Bazel 5.1.1
• gcc (GCC)  11.2.1
• cmake  3.23.2
• ninjia  1.12.0.git
• NASM 2.15.05

> 备注：下面安装命令中vim命令后面内容，均为添加至编辑文件的内容，非命令

# 初始化Python环境
```shell
cd /data/mpc
git clone https://github.com/secretflow/secretflow.git

sudo mkdir /data/conda_env
sudo chmod 777 /data/conda_env

cd secretflow
conda create -p /data/conda_env/secretflow python=3.8

conda activate /data/conda_env/secretflow
（退出）conda deactivate

pip install --upgrade pip
```

# 安装Bazel 5.1.1
```shell
cd /data/opt
curl -sLO --retry 5 --retry-max-time 10 \
https://storage.googleapis.com/bazel/5.1.1/release/bazel-5.1.1-installer-linux-x86_64.sh
mkdir /data/opt/bazel

chmod 755 bazel-5.1.1-installer-linux-x86_64.sh && \
./bazel-5.1.1-installer-linux-x86_64.sh --prefix=/data/opt/bazel

sudo vim /etc/profile
export BAZEL_HOME=/data/opt/bazel
export PATH=$PATH:$BAZEL_HOME/bin
```

# 升级GCC
```shell
sudo yum -y install centos-release-scl
sudo yum -y install devtoolset-11-gcc*
scl enable devtoolset-11 bash
gcc -v
```

# 安装CMake
```shell
cd /data/opt
wget https://cmake.org/files/v3.23/cmake-3.23.2.tar.gz
tar -zxvf cmake-3.23.2.tar.gz
cd cmake-3.23.2
sudo ./bootstrap --prefix=/usr/local
sudo make && sudo make install

vi ~/.bash_profile
PATH=/usr/local/bin:$PATH:$HOME/bin

cmake --version
```

# 安装ninja
```shell
git clone https://github.com/ninja-build/ninja.git
cd ninja
cmake -Bbuild-cmake
cmake --build build-cmake

sudo vim /etc/profile
export NINJA_HOME=/data/opt/ninja/build-cmake
export PATH=$PATH:$NINJA_HOME

source /etc/profile
```


# 安装NASM
```shell
cd /data/opt
wget --no-check-certificate https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.gz
tar zxvf nasm-2.15.05.tar.gz
cd nasm-2.15.05
./configure
make
sudo make install

vim ~/.bash_profile
PATH=$PATH:/usr/local/bin/

source ~/.bash_profile
nasm -v
```

# 清理已有编译缓存
```shell
sudo rm -rf /data/mpc/secretflow/build/
sudo rm -rf /home/app/.cache/bazel/*
```

# 编译安装SecretFlow
```shell
scl enable devtoolset-11 bash
conda activate /data/conda_env/secretflow

python3 setup.py bdist_wheel
python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ dist/*.whl
```

# 测试
```python
$ python
>>> import secretflow as sf
>>> sf.init(['alice', 'bob', 'carol'], num_cpus=8, log_to_driver=True)
>>> dev = sf.PYU('alice')
>>> import numpy as np
>>> data = dev(np.random.rand)(3, 4)
>>> data
<secretflow.device.device.pyu.PYUObject object at 0x7f5f5294ea30>
```

**Comment by ychy00001** [comment]
已解决
