### ISSUE TITLE
cc1plus: fatal error: secretflow_lib/binding/binding.cc: Permission denied

### ISSUE THREAD

**Issue by hushanxue** [secretflow/secretflow#183]
ubuntu 22.04

download source: git clone --recursive [secretflow git url]

I use this command [python setup.py build_ext] to compile the code.

Error :   cc1plus: fatal error: secretflow_lib/binding/binding.cc: Permission denied

bazel: 4.3.2、5.1.1、6.0.0 pre

**Comment by anakinxc** [comment]
Hi,

Can you try `bazel clean --expunge`?

Thanks

**Comment by hushanxue** [comment]
> 

I try **bazel clean --expunge**, then  **python setup.py build_ext** but it does not work.  

gcc and g++  v11.3

**Comment by anakinxc** [comment]
It's kind of bizzare to have this kind of permission error during compilation.

Out of curiosity, can you paste output of `ls -la secretflow_lib/binding/binding.cc ` here?

Thanks

**Comment by hushanxue** [comment]
> 
output:
-rwxrwxrwx 1 hsx hsx 228 Nov  3 22:38 secretflow_lib/binding/binding.cc

**Comment by hushanxue** [comment]
> It's kind of bizzare to have this kind of permission error during compilation.
> 
> Out of curiosity, can you paste output of `ls -la secretflow_lib/binding/binding.cc ` here?
> 
> Thanks

I use  root to compile the code.

**Comment by anakinxc** [comment]
> > It's kind of bizzare to have this kind of permission error during compilation.
> > Out of curiosity, can you paste output of `ls -la secretflow_lib/binding/binding.cc ` here?
> > Thanks
> 
> I use root to compile the code.

Is there any specific reason to use root here?

**Comment by hushanxue** [comment]
> > > It's kind of bizzare to have this kind of permission error during compilation.
> > > Out of curiosity, can you paste output of `ls -la secretflow_lib/binding/binding.cc ` here?
> > > Thanks
> > 
> > 
> > I use root to compile the code.
> 
> Is there any specific reason to use root here?

No，just for bazel.

**Comment by anakinxc** [comment]
> > > > It's kind of bizzare to have this kind of permission error during compilation.
> > > > Out of curiosity, can you paste output of `ls -la secretflow_lib/binding/binding.cc ` here?
> > > > Thanks
> > > 
> > > 
> > > I use root to compile the code.
> > 
> > 
> > Is there any specific reason to use root here?
> 
> No，just for bazel.

So, with root build works fine? If that's the case can you also check bazel execution_root's permission?

You can get the path through `bazel info execution_root`

**Comment by hushanxue** [comment]
> > > > > It's kind of bizzare to have this kind of permission error during compilation.
> > > > > Out of curiosity, can you paste output of `ls -la secretflow_lib/binding/binding.cc ` here?
> > > > > Thanks
> > > > 
> > > > 
> > > > I use root to compile the code.
> > > 
> > > 
> > > Is there any specific reason to use root here?
> > 
> > 
> > No，just for bazel.
> 
> So, with root build works fine? If that's the case can you also check bazel execution_root's permission?
> 
> You can get the path through `bazel info execution_root`
not use root ,  it works, 3ks

I change to
