### ISSUE TITLE
源码安装问题

### ISSUE THREAD

**Issue by relinda2019** [secretflow/secretflow#184]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

secretflow 0.7.7b1

### OS Platform and Distribution

macOS Catalina 10.15.4

### Python version

3.8.5

### Bazel version

5.1.1

### GCC/Compiler version

Apple clang version 12.0.0 (clang-1200.0.32.29)

### What happend and What you expected to happen.

```shell
源码安装执行最后一条安装命令时出错。
ERROR: secretflow-0.7.7b1-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

### Reproduction code to reproduce the issue.

```shell
运行： pip install dist/*.whl 

报错：

ERROR: secretflow-0.7.7b1-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

**Comment by zhouaihui** [comment]
看起来是你的macOS版本比较低，SF对macOS的最低要求是11（Big Sur）

**Comment by anakinxc** [comment]
Hi @relinda2019,

macOS 我们要求 11.0 以上

**Comment by relinda2019** [comment]
好的，谢谢，想问下对linux系统版本也有要求吗？还有如果用docker的方式安装也是要求mac的在11.0以上吗？

**Comment by anakinxc** [comment]
Docker 对 host OS 没有要求

如果用 docker 的话可以考虑用我们官方提供的[镜像](https://hub.docker.com/r/secretflow/secretflow-anolis8/tags)

**Comment by relinda2019** [comment]
好的，多谢

**Comment by peiji1981** [comment]
hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1

**Comment by peiji1981** [comment]
> Hi @relinda2019,
> 
> macOS 我们要求 11.0 以上

hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1

**Comment by anakinxc** [comment]
> > Hi @relinda2019,
> > macOS 我们要求 11.0 以上
> 
> hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1

试一下 sync 到最新的代码，应该没有这个问题了

**Comment by peiji1981** [comment]
> > > Hi @relinda2019,
> > > macOS 我们要求 11.0 以上
> > 
> > 
> > hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1
> 
> 试一下 sync 到最新的代码，应该没有这个问题了

谢谢快速回复，现在编译完之后是secretflow-0.7.11b3-cp38-cp38-macosx_10_16_x86_64.whl， 但是pip install dist/*.whl 之后是ERROR: Could not find a version that satisfies the requirement secretflow-ray==2.0.0.dev1 (from secretflow) (from versions: 2.0.0.dev0)这个问题

**Comment by anakinxc** [comment]
> > > > Hi @relinda2019,
> > > > macOS 我们要求 11.0 以上
> > > 
> > > 
> > > hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1
> > 
> > 
> > 试一下 sync 到最新的代码，应该没有这个问题了
> 
> 谢谢快速回复，现在编译完之后是secretflow-0.7.11b3-cp38-cp38-macosx_10_16_x86_64.whl， 但是pip install dist/*.whl 之后是ERROR: Could not find a version that satisfies the requirement secretflow-ray==2.0.0.dev1 (from secretflow) (from versions: 2.0.0.dev0)这个问题

这是一个 conda 在 macOS 上的 known bug。。。这个包我们等下重新发一下

与此同时，你可以先这样绕过

`SYSTEM_VERSION_COMPAT=0 && pip install dist/*.whl`

**Comment by peiji1981** [comment]
> > > > > Hi @relinda2019,
> > > > > macOS 我们要求 11.0 以上
> > > > 
> > > > 
> > > > hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1
> > > 
> > > 
> > > 试一下 sync 到最新的代码，应该没有这个问题了
> > 
> > 
> > 谢谢快速回复，现在编译完之后是secretflow-0.7.11b3-cp38-cp38-macosx_10_16_x86_64.whl， 但是pip install dist/*.whl 之后是ERROR: Could not find a version that satisfies the requirement secretflow-ray==2.0.0.dev1 (from secretflow) (from versions: 2.0.0.dev0)这个问题
> 
> 这是一个 conda 在 macOS 上的 known bug。。。这个包我们等下重新发一下
> 
> 与此同时，你可以先这样绕过
> 
> `SYSTEM_VERSION_COMPAT=0 && pip install dist/*.whl`

绕不过，手动装secretflow-ray == 2.0.0.dev0 是OK的

**Comment by anakinxc** [comment]
> > > > > > Hi @relinda2019,
> > > > > > macOS 我们要求 11.0 以上
> > > > > 
> > > > > 
> > > > > hello， 我这边macos 是12.4的版本，intel版本，也遇到这个问题，自动创建的 build目录下是 lib.macosx-10.9-x86_64-cpython-38, python是3.8.15， bazel 5.1.1
> > > > 
> > > > 
> > > > 试一下 sync 到最新的代码，应该没有这个问题了
> > > 
> > > 
> > > 谢谢快速回复，现在编译完之后是secretflow-0.7.11b3-cp38-cp38-macosx_10_16_x86_64.whl， 但是pip install dist/*.whl 之后是ERROR: Could not find a version that satisfies the requirement secretflow-ray==2.0.0.dev1 (from secretflow) (from versions: 2.0.0.dev0)这个问题
> > 
> > 
> > 这是一个 conda 在 macOS 上的 known bug。。。这个包我们等下重新发一下
> > 与此同时，你可以先这样绕过
> > `SYSTEM_VERSION_COMPAT=0 && pip install dist/*.whl`
> 
> 绕不过，手动装secretflow-ray == 2.0.0.dev0 是OK的

ok, 这个我们下次迭代的时候修复一下
