### ISSUE TITLE
如何查看通信消耗

### ISSUE THREAD

**Issue by junzlovegood** [secretflow/secretflow#187]
使用多方安全计算或者联邦模型等后，如何查看参与方之间的通信消耗？

**Comment by rivertalk** [comment]
Hi @junzlovegood ，这是个很好的问题
对于多方安全计算和联邦学习，统计方法是不同的

对于多方安全计算，SPU使用内部的通信信道来传输（MPC协议）数据，之后会逐步开放统计接口（目前还没有python接口可以查看）
对于联邦学习，多方之间数据使用Ray 来通信，可以通过  /tmp/ray/session_{date}/logs 日志查看

**Comment by libratiger** [comment]
@rivertalk 是否可以有统一的方法来查看呢？另外Ray的这个通信是包括的所有数据量吗？还是只是数据+模型的，并不包括控制平面的。

**Comment by rivertalk** [comment]
> @rivertalk 是否可以有统一的方法来查看呢？另外Ray的这个通信是包括的所有数据量吗？还是只是数据+模型的，并不包括控制平面的。

目前架构下没有统一的方法可以查看，之后可以考虑开放一些专门的统计接口

Ray这块请 @zhouaihui 来回答一下哈

**Comment by libratiger** [comment]
@zhouaihui 看起来这个数据量完全是Ray自己的，并不是算法层面更细致的。另外目前Ray不能统一MPC层面的传输，是有什么特殊的原因码？

**Comment by zhouaihui** [comment]
SF除了SPU外，其他通信是基于Rey RemoteObject，所以日志里的RemoteObject传输是包含了ray本身和SF的通信。

至于SPU没有选择用ray，主要是出于性能考虑。
