### ISSUE TITLE
secretflow.ml.nn.FLModel保存和加载模型

### ISSUE THREAD

**Issue by cs1317** [secretflow/secretflow#196]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.7

### OS Platform and Distribution

ubuntu

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
Traceback (most recent call last):
  File "FLmodel_save.py", line 126, in <module>
    fl_model.save_model({alice:"/chengsai1/chengsai1/privacy_detection/model",bob:"/fds/chengsai1/model"})
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 631, in save_model
    wait(res)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 180, in wait
    reveal([o.device(lambda o: None)(o) for o in objs])
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 142, in reveal
    all_object = ray.get(all_object_refs)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(IsADirectoryError): ray::_run() (pid=2853994, ip=xx)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::PYUFedAvgW.save_model() (pid=2854135, ip=xx, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7fca93084160>)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/proxy.py", line 71, in wrapper
    return method(*args, **kwargs)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 301, in save_model
    torch.save(self.model, model_path)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/chengsai1/chengsai1/privacy_detection/model'
```

### Reproduction code to reproduce the issue.

```shell
from secretflow.ml.nn import FLModel
fl_model = FLModel(
    server=server,
    device_list=device_list,
    model=model_def,
    aggregator=aggregator,
    strategy='fed_avg_w', # fl strategy
    backend="torch", # backend support ['tensorflow', 'torch']
)
fl_model.save_model({alice:"/chengsai1/chengsai1/privacy_detection/model",bob:"/fds/chengsai1/model"})
```

**Comment by zhangxingmeng** [comment]
IsADirectoryError: [Errno 21] Is a directory: '/chengsai1/chengsai1/privacy_detection/model'
麻烦检查一下你这个路径是不是一个directory

**Comment by cs1317** [comment]
是一个文件夹

**Comment by zhangxingmeng** [comment]
torch保存模型不支持文件夹，请给一个正确的目标文件路径

**Comment by cs1317** [comment]
但是不管我传的是文件夹的路径还是文件的路径，都会被视为文件夹路径
这是secretflow中FLModel.save_model的定义
https://secretflow.readthedocs.io/en/latest/_modules/secretflow/ml/nn/fl/fl_model.html#FLModel.save_model
![1](https://user-images.githubusercontent.com/50541363/202107638-c1ce2c8c-8d1f-4ecb-bf90-3007a43b4d84.png)

**Comment by zhangxingmeng** [comment]
您这边是本地模拟的吗？如果是这种情况，可以增加is_test=True

**Comment by cs1317** [comment]
不是，是在搭建好的ray集群上训练了一个图像分类模型，然后再保存模型时报错

**Comment by zhangxingmeng** [comment]
我本地在Ray的多进程模拟的环境下复现出了你这个问题，但是在多机场景下暂时还没有复现出来
建议您先增加'''is_test=True'''尝试一下，看看能不能解决

**Comment by cs1317** [comment]
加上 is_test=True 后，报错：
Traceback (most recent call last):
  File "FLmodel_save.py", line 126, in <module>
    fl_model.save_model({alice:"/chengsai1/chengsai1/privacy_detection/secretflow-test/model/fl.pt",bob:"/fds/chengsai1/model/fl.pt"},is_test=True)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 631, in save_model
    wait(res)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 180, in wait
    reveal([o.device(lambda o: None)(o) for o in objs])
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 142, in reveal
    all_object = ray.get(all_object_refs)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(PicklingError): ray::_run() (pid=2854709, ip=xx)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::PYUFedAvgW.save_model() (pid=2854850, ip=xx, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7fce134c3040>)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/proxy.py", line 71, in wrapper
    return method(*args, **kwargs)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 301, in save_model
    torch.save(self.model, model_path)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/chengsai1/chengsai1/anaconda3/envs/sf/lib/python3.8/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <class '__main__.ConvNet'>: attribute lookup ConvNet on __main__ failed

**Comment by cs1317** [comment]
请问bug已经修复了吗？如果修复了请告知一下，谢谢！

**Comment by 6fj** [comment]
请等待：https://github.com/secretflow/secretflow/pull/198

**Comment by zhouaihui** [comment]
hi， @cs1317 ，你可以更新到0.7.11b1版本。

**Comment by cs1317** [comment]
已更新到0.7.11b2版本，但还是报相同的错误

**Comment by zhangxingmeng** [comment]
麻烦贴一下报错信息和代码吧

**Comment by 6fj** [comment]
请查看一下secretflow目前的版本：

```
pip freeze | grep secretflow
```

感谢！

**Comment by cs1317** [comment]
何时是尽头
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] secretflow.ml.nn.FLModel保存和加载模型 (Issue #196)





 
请查看一下secretflow目前的版本：
 pip freeze | grep secretflow  
感谢！

**Comment by cs1317** [comment]
![1](https://user-images.githubusercontent.com/50541363/202994701-2fed5733-a738-4b4a-9807-b8920eec8ebc.png)

**Comment by anakinxc** [comment]
Reopen issue based on recent comments

**Comment by cs1317** [comment]
代码:[ImageClassfyPytorch.txt](https://github.com/secretflow/secretflow/files/10054509/ImageClassfyPytorch.txt)
![2](https://user-images.githubusercontent.com/50541363/202995733-cf091411-ca70-42fe-bd81-1266fa01007d.png)

**Comment by zhangxingmeng** [comment]
![image](https://user-images.githubusercontent.com/103552200/202995885-c6195283-ba87-410b-bcd4-781500d4b3ee.png)
你这个文件夹删除过吗？

**Comment by zhangxingmeng** [comment]
Hi @cs1317 
请问下还报错吗？

**Comment by cs1317** [comment]
出现了一个新问题:
![3](https://user-images.githubusercontent.com/50541363/203000570-746aaf16-7c87-45a3-9e5b-76d79afddef9.png)
网上说的解决办法是：把网络的定义单独写在一个文件里,然后通过from xx import xx导入
但我把网络单独定义后，又有新的问题出现：
![4](https://user-images.githubusercontent.com/50541363/203001741-ee608450-d011-4c26-90fe-4699885c98cf.png)

**Comment by zhangxingmeng** [comment]
save模型问题解决了吗？如果解决了，我们在新的issue讨论模型定义的问题。

你模型定义参考一下我们给出的tutorial，FLModel能接受的只是模型定义的方法，而不是定义好的模型，需要把方法传入到worker才可以

**Comment by cs1317** [comment]
不是模型的定义问题，还是模型的保存，我的模型能完成训练的过程了，但保存的时候还是会报错

**Comment by zhangxingmeng** [comment]
https://discuss.pytorch.org/t/picklingerror-when-using-torch-save/3362
参考这个讨论，这里如果提供save_state_dict是不是可以满足你的要求

**Comment by cs1317** [comment]
这是secretflow官网提供的示例，我将例子中的本地init()替换为集群，然后加了模型的保存
![5](https://user-images.githubusercontent.com/50541363/203004076-0a0b5b90-e45c-46c6-889a-08e0d3c285c5.png)

**Comment by cs1317** [comment]
pytorch提供了两种模型保存方式:
第一种:(保存模型的参数+模型的定义)
torch.save(model, PATH)
model = torch.load(PATH)
model.eval()
第二种:（仅保存模型的参数，加载时需要先定义模型，然后加载模型的参数）
torch.save(model.state_dict(), PATH)
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()

**Comment by zhangxingmeng** [comment]
目前的代码更多考虑的是开发阶段，实际场景中只允许某几方保存模型这个需求是非常合理的。
框架暂时还不支持，是因为这个功能需要配合模型授权校验分发才能使用。
会在后续的版本去实现的。

**Comment by cs1317** [comment]
好的，那咱们就先解决一下上面的报错问题，您那边有没有解决方案呢？

**Comment by zhangxingmeng** [comment]
我在看这个问题，暂时还没有很好的解法
看起来是torch下一个很古老的遗留问题，我这边解决了会及时同步你的

**Comment by zhangxingmeng** [comment]
这个问题我参考网上的讨论解决了：
1、新开一个文件用来配置模型
`
from torch import nn, optim
import torch
from secretflow.ml.nn.fl.backend.torch.utils import BaseModule
class ConvNet(BaseModule):
    def __init__(self):
        super(ConvNet,self).__init__()
        self.model=nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=(3, 3)),
            nn.ReLU(),
            nn.MaxPool2d((2, 2)),
            nn.Conv2d(32, 64, kernel_size=(3, 3)),
            nn.ReLU(),
            nn.MaxPool2d((2, 2)),
            nn.Conv2d(64, 16, kernel_size=(3, 3)),
            nn.ReLU(),
            nn.MaxPool2d((2, 2)),
            nn.Flatten(),
            nn.Dropout(),
            nn.Linear(16 * 28 * 28, 5),
            nn.Softmax()
        )

    def forward(self,x):
        x=x.permute(0,3,1,2)
        x=x.float()/255
        x=self.model(x)
        return x`

然后在创建FLModel的地方import就可以解决
`from conv_net import ConvNet
loss_fn = nn.CrossEntropyLoss
optim_fn = optim_wrapper(optim.Adam, lr=1e-2)
model_def = TorchModel(
    model_fn=ConvNet,
    loss_fn=loss_fn,
    optim_fn=optim_fn,
    metrics=[
        metric_wrapper(Accuracy, num_classes=5, average='micro'),
        metric_wrapper(Precision, num_classes=5, average='micro'),
    ],
)`

**Comment by cs1317** [comment]
这个方法我试过了，在alice这边定义的Net.py，在bob那边找不到
![4](https://user-images.githubusercontent.com/50541363/203038169-3ea95a27-7a8c-43ac-a877-825330dd8586.png)

**Comment by zhangxingmeng** [comment]
你的driver是和alice在一方吗，你在bob的对应位置也创建这么个文件可以解决吗？

**Comment by cs1317** [comment]
是的,driver和alice在一方，这个训练的代码也在alice这边，但bob那边没有这个代码，哪bob那边我在哪放这个文件(Net.py)呢？

**Comment by zhangxingmeng** [comment]
这个问题我们已经修复，会在下个迭代同步到github。修改之前的直接torch.save模式为save state_dict
参考https://pytorch.org/docs/master/notes/serialization.html#id5

**Comment by cs1317** [comment]
好的，麻烦把对应的模型加载方式load_state_dict也更新
torch.save(model.state_dict(), PATH)
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))

**Comment by cs1317** [comment]
请问是否已修复模型保存问题？我可以使用哪个版本的secretflow继续研究？

**Comment by zhangxingmeng** [comment]
这个问题在最新版本的发布中已经修复，请再尝试下

**Comment by cs1317** [comment]
以成功保存模型，并使用pytorch加载训练出的模型
fl_model.save_model({alice:'/home/xxx/mnist/mnist_classify.pth',bob:'/home/mi/PycharmProjects/SecretflowDemo/mnist/mnist_classify.pth'})
module=ConvNet()
module.load_state_dict(torch.load('../../mnist/mnist_classify.pth')['model_state_dict'])
