### ISSUE TITLE
spu PSI超过三方时无法解析cluster_def

### ISSUE THREAD

**Issue by lidh15** [secretflow/secretflow#218]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.11b2

### OS Platform and Distribution

Linux

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
secretflow/utils/testing.py, line 53, in cluster_def
AssertionError: Runtime config is not provided or couldn't be deduced
```

### Reproduction code to reproduce the issue.

```shell
按照官方文档步骤执行，只是在`['alice', 'bob', 'carol']`后面加了一位'david'（叫'daniel'也不行），`sf.init`是可以的，`sf.utils.testing.cluster_def`会报错
```

**Comment by 6fj** [comment]
Hi @lidh15 

请贴一下相关的代码，感谢

**Comment by zhouaihui** [comment]
hi, @lidh15 , `sf.utils.testing.cluster_def`是方便测试用的一个helper方法，仅支持两方或者三方。

如果需要更多方，请参考[spu](https://secretflow.readthedocs.io/zh_CN/latest/source/secretflow.device.device.html#secretflow.device.device.spu.SPU.__init__)自行构造。

**Comment by lidh15** [comment]
```python
import secretflow as sf
alice, bob, carol, david = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol'), sf.PYU('david')
sf.init(['alice', 'bob', 'carol', 'david'], num_cpus=8, log_to_driver=True)
cluster = sf.utils.testing.cluster_def(['alice', 'bob', 'carol', 'david'])
```

**Comment by 6fj** [comment]
Hi @lidh15 

可以这样修改为
```
import secretflow as sf
alice, bob, carol, david = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol'), sf.PYU('david')
sf.init(['alice', 'bob', 'carol', 'david'], num_cpus=8, log_to_driver=True)

SEMI2K_RUNTIME_CONFIG = {
    'protocol': spu.spu_pb2.SEMI2K,
    'field': spu.spu_pb2.FM128,
}

cluster = sf.utils.testing.cluster_def(['alice', 'bob', 'carol', 'david'], SEMI2K_RUNTIME_CONFIG)
```

**Comment by lidh15** [comment]
> Hi @lidh15
> 
> 可以这样修改为
> 
> ```
> import secretflow as sf
> alice, bob, carol, david = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol'), sf.PYU('david')
> sf.init(['alice', 'bob', 'carol', 'david'], num_cpus=8, log_to_driver=True)
> 
> SEMI2K_RUNTIME_CONFIG = {
>     'protocol': spu.spu_pb2.SEMI2K,
>     'field': spu.spu_pb2.FM128,
> }
> 
> cluster = sf.utils.testing.cluster_def(['alice', 'bob', 'carol', 'david'], SEMI2K_RUNTIME_CONFIG)
> ```

```python3
spu_4pc = sf.SPU(cluster)
spu_4pc.psi_csv('uid', {alice: 'test.csv', bob: 'test.csv', carol: 'test.csv', david: 'test.csv', }, {alice: 'a.csv', bob: 'b.csv', carol: 'c.csv', david: 'd.csv', }, 'alice', protocol='ECDH_PSI_3PC')
```
报错：
spu/binding/psi.py, line 39, in bucket_psi
report_str = _lib.libs.bucket_psi(link, config.SerializeToString())
RuntimeError: what:
[Enforce fail at spu/psi/memory_psi.cc:52] lctx_->WorldSize() == 3. psi_type:4, only three parties supported, got 4
protocol换成别的也一样。

**Comment by zhanglei486** [comment]
> > Hi @lidh15
> > 可以这样修改为
> > ```
> > import secretflow as sf
> > alice, bob, carol, david = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol'), sf.PYU('david')
> > sf.init(['alice', 'bob', 'carol', 'david'], num_cpus=8, log_to_driver=True)
> > 
> > SEMI2K_RUNTIME_CONFIG = {
> >     'protocol': spu.spu_pb2.SEMI2K,
> >     'field': spu.spu_pb2.FM128,
> > }
> > 
> > cluster = sf.utils.testing.cluster_def(['alice', 'bob', 'carol', 'david'], SEMI2K_RUNTIME_CONFIG)
> > ```
> 
> ```python
> spu_4pc = sf.SPU(cluster)
> spu_4pc.psi_csv('uid', {alice: 'test.csv', bob: 'test.csv', carol: 'test.csv', david: 'test.csv', }, {alice: 'a.csv', bob: 'b.csv', carol: 'c.csv', david: 'd.csv', }, 'alice', protocol='ECDH_PSI_3PC')
> ```
> 
> 报错： spu/binding/psi.py, line 39, in bucket_psi report_str = _lib.libs.bucket_psi(link, config.SerializeToString()) RuntimeError: what: [Enforce fail at spu/psi/memory_psi.cc:52] lctx_->WorldSize() == 3. psi_type:4, only three parties supported, got 4 protocol换成别的也一样。

目前只支持2方或3方PSI，还不支持大于3方的PSI

**Comment by lidh15** [comment]
期待后续支持
