### ISSUE TITLE
Add SecureBoost

### ISSUE THREAD

**Issue by icavan** [secretflow/secretflow#222]
MPC-XGB from [CIKM](https://arxiv.org/pdf/2005.08479.pdf) requires oblivious splitting for each node by default, which means the computation effort grows exponentially as the tree's max depth increases.

Although there are some known [attacks](https://arxiv.org/pdf/2011.09290.pdf) on SecureBoost, we still need to add one which outperforms MPC-XGB for deeper tree depths.

Pros: HE helps reduce bandwidth, and it is deep-depth friendly
Cons: SecureBoost does not provide provable security, and there exists known attacks

**Comment by usafchn** [comment]
Preview: SecureBoost has been developed and will be released in March

**Comment by da-niao-dan** [comment]
Released
