### ISSUE TITLE
what's different between secretflow-ray and ray, where can I pull the code of secretflow-ray?

### ISSUE THREAD

**Issue by HurleyWu** [secretflow/secretflow#226]
what's different between secretflow-ray and ray, where can I pull the code of secretflow-ray?

**Comment by zhouaihui** [comment]
`secretflow-ray` is based on ray with security enhanced. Sorry that the code is not open now. 
`secretflow-ray` will  be deprecated in the upcoming release and then ray will be used.

**Comment by HurleyWu** [comment]
@zhouaihui thank you very much! Does You mean that the  security features of secretflow-ray will be merged into the upcoming release of ray?

**Comment by zhouaihui** [comment]
We plan to publish it this month :)
