### ISSUE TITLE
install secretflow  on windows

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#227]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow0.7.11b3

### OS Platform and Distribution

Windows10

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
虽然你们提供了docker容器可以供windows用户体验或者使用secretflow，但是我发现通过使用基于WSL2在Windows上提供的Linux环境，也能够运行你们给出的单机环境的横向联邦学习的图像分类代码，是否开发社区可以通过进一步实验，证明secretflow能够完整的在WSL2上的环境上使用，这样可以实现在windows上使用secretflow，能够提高更多人使用secretflow，并且可以在readme.md添加一种新的方式。如果WSL2不能完全支持secretflow，那么也可以把它作为体验环境的demo，给出适用范围。无论何种方式，都可以考虑将WSL2作为secret安装环境的补充。谢谢。
```

### Reproduction code to reproduce the issue.

```shell
WSL2安装教程：https://learn.microsoft.com/zh-cn/windows/wsl/install
```

**Comment by rivertalk** [comment]
非常感谢您的宝贵建议！

我们目前没有WSL2的环境，但是理论上只要有Docker或者是WSL，secretflow都是可以跑起来的，之后等我们准备好环境验证过后会加上更多的文档

祝您生活愉快～

PS: 隐语非常欢迎社区的共建，也随时欢迎你一起共建社区教程哈 :P

**Comment by zhouaihui** [comment]
hi, @Mingbo-Lee , WSL2文档可参见 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/installation.html#option-4-from-wsl
