### ISSUE TITLE
tensorflow+secretflow使用的问题

### ISSUE THREAD

**Issue by linhaibo123** [secretflow/secretflow#23]
您好，目前有tensorflow或者pytorch自定义算法与模型，然后如何结合secretflow使用的例子吗？

**Comment by linhaibo123** [comment]
不好意思，看到了

**Comment by wuxibin89** [comment]
目前在（水平、垂直）联邦学习算法中，我们支持了tensorflow自定义算法和模型，pytorch的支持正在进行中。垂直MPC算法中，则是支持了JAX作为前端。
