### ISSUE TITLE
请问spu中的ref2k是什么协议？有相关资料吗？

### ISSUE THREAD

**Issue by Anerle** [secretflow/secretflow#234]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

latest

### Python version

3.7

### What happend and What you expected to happen.

```shell
如题
```

### Reproduction code to reproduce the issue.

```shell
spu/spu/mpc/ref2k/
```

**Comment by rivertalk** [comment]
谢谢提问 @Anerle 

Ref2k 全称是 Reference implementation for Mod 2k protocol，是 mod 2k协议的一个「参考实现」。它本身没有任何密码安全，所有的kernel都是用明文在 Ring 2k上进行演算的，目的是给其他协议一个参考，只要其他协议实现了相关的kernel，就可以变成一个完整的SPU协议

祝您生活愉快
