### ISSUE TITLE
docker 集群下，运行测试代码，报错

### ISSUE THREAD

**Issue by onelyfly** [secretflow/secretflow#238]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

0.7

### OS Platform and Distribution

centos7

### Python version

Python 3.8 

### What happend and What you expected to happen.

```shell
报错如下：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1020, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 232, in psi_csv
    return ray.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=421, ip=10.0.152.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe9e10876a0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 235, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yasl/yasl/link/transport/channel_brpc.cc:120] brpc server failed start
stacktrace: 
#0 yasl::link::FactoryBrpc::CreateContext()+0x7fe9fa797017
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fe9f93199ce
#2 pybind11::cpp_function::dispatcher()+0x7fe9f9309062
#3 PyCFunction_Call+0x4dfd82
```

### Reproduction code to reproduce the issue.

```shell
运行代码：
import spu
import secretflow as sf

sf.init(address="10.0.152.10:7001")
alice, bob = sf.PYU('alice'), sf.PYU('bob')

# 因为在同一服务器下面，以host模式启动，所以此处端口不要冲突
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Use the address and port of alice instead.
            # Please choose a unused port.
            'address': '10.0.152.10:7001',
        },
        {
            'party': 'bob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose a unused port.
            'address': '10.0.152.10:7001',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
spu = sf.SPU(cluster_def=cluster_def)
input_path = {alice: 'id_1000000.csv', bob: 'id_1000000.csv'}
output_path = {alice: './alice_psi.csv', bob: './bob_psi.csv'}
spu.psi_csv('id', input_path, output_path, 'alice')
```

**Comment by onelyfly** [comment]
我创建两个容器：
docker run --network=mynet --ip 10.0.152.10 --restart=always -itd --shm-size="6g" --name secretflow01 secretflow/secretflow-anolis8:latest
docker run --network=mynet --ip 10.0.152.11 --restart=always -itd --shm-size="6g" --name secretflow02 secretflow/secretflow-anolis8:latest

**Comment by 6fj** [comment]
hi @onelyfly 

看上去你的所有ip：port都是一样的，这个是不行的。
请参考：https://github.com/secretflow/secretflow/issues/219 ， 感谢。

**Comment by onelyfly** [comment]
> hi @onelyfly
> 
> 看上去你的所有ip：port都是一样的，这个是不行的。 请参考：#219 ， 感谢。

按#219 去改了IP port，也一样问题。
import secretflow as sf 
from secretflow.device.device.spu import spu

# 就别管实际IP是多少了，这里这个是别人的
sf.init(address="10.0.152.10:7001")  

alice, bob = sf.PYU('alice'), sf.PYU('bob')

# Alice Bob Carol在三个IP上，但是端口一致
# link_desc是None，没办法，文档里就只说了有哪些参数，又没有example
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': 'localhost:0',
            'address': '10.0.152.10:7002',
        },
        {
            'party': 'bob',
            'id': 'localhost:1',
            'address': '10.0.152.11:7002',
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
spu_3pc = sf.SPU(cluster_def=cluster_def)
# 这个路径肯定是对的，权限也都有
input_path = {alice: '/data/alice.csv', bob: '/data/bob.csv'}
output_path = {alice: '/data/alice_psi.csv', bob: '/data/bob_psi.csv'}
# 这个uid也是没问题的
spu_3pc.psi_csv('uid', input_path, output_path, 'alice', protocol='ECDH_PSI_3PC')


问题：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1020, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 232, in psi_csv
    return ray.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=228, ip=10.0.152.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f74609c66d0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 456, in psi_csv
    report = psi.bucket_psi(self.link, config)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 39, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString())
RuntimeError: what: 
        [Enforce fail at spu/psi/memory_psi.cc:52] lctx_->WorldSize() == 3. psi_type:4, only three parties supported, got 2
stacktrace: 
#0 spu::psi::MemoryPsi::MemoryPsi()+0x7f7476682cd7
#1 spu::psi::BucketPsi::Init()+0x7f7476679c5e
#2 spu::psi::BucketPsi::BucketPsi()+0x7f747667a1ef
#3 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f747532523d
#4 pybind11::cpp_function::dispatcher()+0x7f7475309062
#5 PyCFunction_Call+0x4dfd82
>>> 2022-12-26 05:55:13,220     ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.psi_csv() (pid=106, ip=10.0.152.11, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f651e7aa6a0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 456, in psi_csv
    report = psi.bucket_psi(self.link, config)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 39, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString())
RuntimeError: what: 
        [Enforce fail at spu/psi/memory_psi.cc:52] lctx_->WorldSize() == 3. psi_type:4, only three parties supported, got 2
stacktrace:

**Comment by 6fj** [comment]
> [Enforce fail at spu/psi/memory_psi.cc:52] lctx->WorldSize() == 3. psi_type:4, only three parties supported, got 2

请换一种2pc的psi，比如 **ECDH_PSI_2PC**，需要修改psi_csv的protocol。

**Comment by onelyfly** [comment]
还是一样的问题，感觉问题不在点上。
![image](https://user-images.githubusercontent.com/25855448/209521384-e6c840bd-2452-4f07-b309-19cefcda0c1e.png)


还有input_path = {alice: '/root/data/alice.csv', bob: '/root/data/bob.csv'}  这种数据哪里可下载？

**Comment by 6fj** [comment]
1. 网络无法联通是常见问题，请问你的两个容器之间可以相互ping通吗？
2. input_path = {alice: '/root/data/alice.csv', bob: '/root/data/bob.csv'}  这个是input文件，是需要你这边提供的

**Comment by onelyfly** [comment]
1.网络是通的
2.ray status
![image](https://user-images.githubusercontent.com/25855448/209525663-35049df2-1fd0-4494-9998-d278a454d3f5.png)
3.数据刚才也生成了份。

然后问题还是那问题：
话说docker集群版，有没测通过文档之类？

**Comment by onelyfly** [comment]
![image](https://user-images.githubusercontent.com/25855448/209525988-f688f836-4360-4d58-a262-6f8e850ad235.png)

**Comment by 6fj** [comment]
hi @onelyfly 

可以参考一下 https://github.com/secretflow/secretflow/issues/131#issuecomment-1272447679 ， 
添加一下listen_address 吗？

**Comment by onelyfly** [comment]
> 

也按上面的测了，也不行。甚至我容器重新删除，重新创建。都有问题
1.网络可以通
![image](https://user-images.githubusercontent.com/25855448/209745696-42483543-2db6-4107-9958-f5f22c8cb981.png)

2.但是直接用
ray.init(address='ray://10.0.152.10:7001')
都连接不了

![image](https://user-images.githubusercontent.com/25855448/209746100-c4538f0f-eea1-4d50-b749-e5aef8892d0f.png)

**Comment by zhouaihui** [comment]
试试`ray.init(address='10.0.152.10:7001')`

**Comment by onelyfly** [comment]
> 
这是head 
![image](https://user-images.githubusercontent.com/25855448/209747623-a37afcb1-ca4d-4e4d-bf18-f5cd2f4a4d3f.png)



![image](https://user-images.githubusercontent.com/25855448/209747728-c5c788c2-4cd4-4df1-9fc0-8206a67fab4b.png)

**Comment by jovany-wang** [comment]
https://github.com/secretflow/secretflow/issues/238#issuecomment-1366320610
这里的两个图是在同一个容器里吗？ 可以先介绍一下集群结构吗

**Comment by onelyfly** [comment]
集群容器：
docker run --network=mynet --ip 10.0.152.10 -d -e RAY_DISABLE_REMOTE_CODE=true -e RAY_USE_TLS=0 -v /root/data:/root/data -v /root/data/config/config.yml:/root/data/config/config.yml  -itd --shm-size="6g" --restart=always --name secretflow01 --privileged secretflow/secretflow-anolis8:latest

docker run --network=mynet --ip 10.0.152.11 -d -e RAY_DISABLE_REMOTE_CODE=true -e RAY_USE_TLS=0 -v /root/data:/root/data -v /root/data/config/config.yml:/root/data/config/config.yml  -itd --shm-size="6g" --restart=always --name secretflow02 --privileged secretflow/secretflow-anolis8:latest

10容器是head
ray start --head --node-ip-address="10.0.152.10" --port="7001" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
11容器是节点
ray start --address="10.0.152.10:7001"  --node-ip-address="10.0.152.11"  --resources='{"bob": 8}' --disable-usage-stats
这是head图运行：
![image](https://user-images.githubusercontent.com/25855448/209892736-c9471801-e4bd-458c-877c-28d84645cdea.png)

以下图是11节点容器运行：
1.网络是通的
![image](https://user-images.githubusercontent.com/25855448/209892799-cbeb7490-2497-464d-92e8-3efd6ef95baf.png)
2.运行ray.init(address='10.0.152.10:7001')失败
![image](https://user-images.githubusercontent.com/25855448/209892842-a5acbcc6-d580-4bfe-8768-69f6dd32d06a.png)


> [#238 (comment)](https://github.com/secretflow/secretflow/issues/238#issuecomment-1366320610) 这里的两个图是在同一个容器里吗？ 可以先介绍一下集群结构吗

**Comment by zhouaihui** [comment]
另外，@onelyfly ，你可以升级到最新的secretflow再试试，目前最新版本是0.7.18b0

**Comment by onelyfly** [comment]
> `mynet`这个是怎么创建的？用的是bridge模式还是？

这个是自定义的桥接模式：
docker network create --subnet=10.0.152.0/24 mynet

**Comment by onelyfly** [comment]
> 另外，@onelyfly ，你可以升级到最新的secretflow再试试，目前最新版本是0.7.18b0

用最新版，集群还是不行：
![a11b7b39317fd60fa896e740fdf2a8d](https://user-images.githubusercontent.com/25855448/216921445-79bca47b-ed7d-419a-b872-cbb11bc9aa9a.png)

 话说:单台服务器多docker集群部署，有没有联通过的？

**Comment by zhouaihui** [comment]
无法复现你的问题，步骤如下：(Docker版本20.10.17)


```bash
> docker network create --subnet=10.0.152.0/24 mynet
> docker run -it --network=mynet --ip 10.0.152.10 --name secretflow01 secretflow/secretflow-anolis8:latest
(secretflow) bash-4.4# ray start --head --node-ip-address="10.0.152.10" --port="7001" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 10.0.152.10

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='10.0.152.10:7001'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _node_ip_address='10.0.152.10')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
  
  To see the status of the cluster, use
    ray status
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
```

再启动另一个容器
```bash
> docker run -it --network=mynet --ip 10.0.152.11 --name secretflow02 secretflow/secretflow-anolis8:latest
(secretflow) bash-4.4# ray start --address="10.0.152.10:7001" --node-ip-address="10.0.152.11" --resources='{"bob": 8}' --disable-usage-stats
Local node IP: 10.0.152.11

--------------------
Ray runtime started.
--------------------

To terminate the Ray runtime, run
  ray stop
(secretflow) bash-4.4# python
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init(address='10.0.152.10:7001')
2023-02-06 09:23:04,373 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.0.152.10:7001...
2023-02-06 09:23:04,389 INFO worker.py:1538 -- Connected to Ray cluster.
RayContext(dashboard_url='', python_version='3.8.13', ray_version='2.2.0', ray_commit='d10509847a5256fa5d191f3f6db5c60026b5d6b8', address_info={'node_ip_address': '10.0.152.11', 'raylet_ip_address': '10.0.152.11', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2023-02-06_09-22-03_359943_18/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2023-02-06_09-22-03_359943_18/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2023-02-06_09-22-03_359943_18', 'metrics_export_port': 55439, 'gcs_address': '10.0.152.10:7001', 'address': '10.0.152.10:7001', 'dashboard_agent_listen_port': 52365, 'node_id': '102ff6a23df57fe7f32ecf095c8fe555fd4dfb680d148959a222d711'})
```

**Comment by zhouaihui** [comment]
使用 `ray.init(address='10.0.152.10:7001')`
