### ISSUE TITLE
有没有一启动docker容器，就能自启动ray，该如何配置？

### ISSUE THREAD

**Issue by onelyfly** [secretflow/secretflow#239]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

0.7

### OS Platform and Distribution

centos7

### Python version

Python 3.8 

### What happend and What you expected to happen.

```shell
有没有一启动docker容器，就能自启动ray，该如何配置？
不想每次启动容器，再进入容器里去执行：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=1 \
RAY_TLS_SERVER_CERT=servercert.pem \
RAY_TLS_SERVER_KEY=serverkey.pem \
RAY_TLS_CA_CERT=cacert.pem \
ray start --head --node-ip-address="ip" --port="port" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
来启动ray
```

### Reproduction code to reproduce the issue.

```shell
有没自启动脚本之类，如何配置？
```

**Comment by 6fj** [comment]
如果你想要基于docker做部署工作，有很多不同的选择, 包括docker compose，k8s 等。

目前，隐语并没有提供此类文档。
