### ISSUE TITLE
sf初始化如何设置存储路径

### ISSUE THREAD

**Issue by cuill30** [secretflow/secretflow#241]
### Issue Type

Feature Request

### Source

source

### Secretflow Version

secretflow 0.7.11b3

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在执行拆分学习demo时候，执行初始化步骤
import secretflow as sf
sf.init(['alice', 'bob'], num_cpus=8, log_to_driver=True)
alice, bob = sf.PYU('alice'), sf.PYU('bob')

返回：
WARNING services.py:2010 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm.

期望：如何能制定存储路径，看过init()参数，并没有相关路径的设置
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
sf.init(['alice', 'bob'], num_cpus=8, log_to_driver=True)
alice, bob = sf.PYU('alice'), sf.PYU('bob')
```

**Comment by 6fj** [comment]
请问你这边所说的存储路径指的是什么？

是指模型的存储路径吗？

**Comment by cuill30** [comment]
![image](https://user-images.githubusercontent.com/38411096/209608679-4c229db3-9677-4ac2-a51e-668c15c983c7.png)
路径指的是/dev/shm，想手动设置到指定位置，刚刚学习sf，目前尚不清楚此路径存储什么，但是日志建议10.24G，感觉存的东西不会少，所以想手动设置到空间到的路径下

**Comment by zhouaihui** [comment]
这个是ray的建议，ray底层使用了共享内存减少拷贝。这个warning只是提示/dev/shm太小了，ray会使用磁盘来存储数据。
如果只是测试，可以忽略哈，对你的功能基本无影响。
如果比较在意，可以看看你的环境能不能把/dev/shm设置大一点。
