### ISSUE TITLE
how to load local data

### ISSUE THREAD

**Issue by turbominxi** [secretflow/secretflow#244]
### Issue Type

Others

### Source

source

### Secretflow Version

latest

### OS Platform and Distribution

centos 7

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
看到secretflow里面集成了很多内置的额数据集，但是没有看到如何读取本地数据集的例子，有比较简单的方式直接读取本地数据集然后再进行处理吗，还是必须要在固定函数的基础上进行修改呢
```

### Reproduction code to reproduce the issue.

```shell
wu
```

**Comment by zhouaihui** [comment]
hi, @turbominxi , SecretFlow提供了PYU（python runtime），可以通过PYU执行函数达成你要的读取文件的目的。
示例 
```python
import secretflow as sf

sf.init(...)

alice = sf.PYU('alice')

# 你可以在函数里实现你想要的文件读取逻辑
def load_alice_data():
    import pandas as pd
    return pd.read_csv('alice.csv')

alice_data = alice(load_alice_data)()
```

**Comment by 6fj** [comment]
hi @turbominxi 

如果你是联邦学习场景，可以使用我们提供的dataframe：https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/preprocessing/DataFrame.html

否则，你可以使用任意函数通过PYU device读取和处理本地数据

**Comment by turbominxi** [comment]
> hi, @turbominxi , SecretFlow提供了PYU（python runtime），可以通过PYU执行函数达成你要的读取文件的目的。 示例
> 
> ```python
> import secretflow as sf
> 
> sf.init(...)
> 
> alice = sf.PYU('alice')
> 
> # 你可以在函数里实现你想要的文件读取逻辑
> def load_alice_data():
>     import pandas as pd
>     return pd.read_csv('alice.csv')
> 
> alice_data = alice
