### ISSUE TITLE
secretflow里面有与train_test_split功能相同的函数吗

### ISSUE THREAD

**Issue by turbominxi** [secretflow/secretflow#250]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

centos 7

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
HDataFrame如何进行数据拆分
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by zhouaihui** [comment]
You can use [train_test_split](https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.data.html#secretflow.data.split.train_test_split)
