### ISSUE TITLE
想问下reshape函数在哪里呢

### ISSUE THREAD

**Issue by turbominxi** [secretflow/secretflow#251]
### Issue Type

Bug

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

centos 7

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
x_valid = x_train.reshape((330, 28, 28, 1))
想实现这个功能，但是显示'HDataFrame' object has no attribute 'reshape'
```

### Reproduction code to reproduce the issue.

```shell
x_train = x_train.reshape((765, 28, 28, 1))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[88], line 1
----> 1 x_train = x_train.reshape((765, 28, 28, 1))
```

**Comment by turbominxi** [comment]
还有to_categorical函数想知道在哪里

**Comment by 6fj** [comment]
Hi @turbominxi 

请阅读HDataFrame的API文档：https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.data.horizontal.html#secretflow.data.horizontal.HDataFrame

**Comment by turbominxi** [comment]
没有找到reshape呢，意思是没有这个函数吗




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] 想问下reshape函数在哪里呢 (Issue #251)





 
Hi @turbominxi
 
请阅读HDataFrame的API文档：https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.data.horizontal.html#secretflow.data.horizontal.HDataFrame

**Comment by zhouaihui** [comment]
SecretFlow的联邦DataFrame提供的是全局视角概念下的DataFrame，联邦的数据核心是不可动。
在全局视角对数据做reshape是一件不好理解的事情，比如一个列可能跨了好几个机构，reshape之后的行为是未定义的，因此SecretFlow不提供此类操作。

**Comment by turbominxi** [comment]
好的，谢谢




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] 想问下reshape函数在哪里呢 (Issue #251)





 
SecretFlow的联邦DataFrame提供的是全局视角概念下的DataFrame，联邦的数据核心是不可动。
 在全局视角对数据做reshape是一件不好理解的事情，比如一个列可能跨了好几个机构，reshape之后的行为是未定义的，因此SecretFlow不提供此类操作。

**Comment by turbominxi** [comment]
那意思是图像数据必须要提前处理好再用secretflow进行操作吗




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] 想问下reshape函数在哪里呢 (Issue #251)





 
SecretFlow的联邦DataFrame提供的是全局视角概念下的DataFrame，联邦的数据核心是不可动。
 在全局视角对数据做reshape是一件不好理解的事情，比如一个列可能跨了好几个机构，reshape之后的行为是未定义的，因此SecretFlow不提供此类操作。

**Comment by turbominxi** [comment]
这部分应该是做过处理封装了，那如果是自己的数据必须要先按照源代码封装一下吗，这样很不灵活呢




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] 想问下reshape函数在哪里呢 (Issue #251)





 
SecretFlow的联邦DataFrame提供的是全局视角概念下的DataFrame，联邦的数据核心是不可动。
 在全局视角对数据做reshape是一件不好理解的事情，比如一个列可能跨了好几个机构，reshape之后的行为是未定义的，因此SecretFlow不提供此类操作。

**Comment by zhangxingmeng** [comment]
图像数据是多维度的建议用fedndarray吧

**Comment by turbominxi** [comment]
好的，谢谢




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] 想问下reshape函数在哪里呢 (Issue #251)





 
图像数据是多维度的建议用fedndarray吧
