### ISSUE TITLE
ValueError: The first argument to `Layer.call` must always be passed.

### ISSUE THREAD

**Issue by turbominxi** [secretflow/secretflow#254]
### Issue Type

Bug

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

centos 7

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 2 of 2). These functions will not be directly callable after loading.
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 2 of 2). These functions will not be directly callable after loading.

(pid=12216) 2023-01-09 14:40:04.757496: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=12216) 2023-01-09 14:40:04.794284: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=12254) 2023-01-09 14:40:05.350921: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=12254) 2023-01-09 14:40:05.388450: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=12216) 2023-01-09 14:40:05.536396: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=12216) 2023-01-09 14:40:05.536480: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=12216) 2023-01-09 14:40:05.536491: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(pid=12254) 2023-01-09 14:40:06.135486: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=12254) 2023-01-09 14:40:06.135570: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=12254) 2023-01-09 14:40:06.135582: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(PYUFedAvgW pid=12216) 2023-01-09 14:40:06.810806: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
(PYUFedAvgW pid=12216) 2023-01-09 14:40:06.810844: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
(PYUFedAvgW pid=12216) WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
(PYUFedAvgW pid=12216) 2023-01-09 14:40:07,286  ERROR worker.py:451 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PYUFedAvgW.__init__() (pid=12216, ip=172.30.166.62, repr=<secretflow.ml.nn.fl.backend.tensorflow.strategy.fed_avg_w.PYUFedAvgW object at 0x7efec32c2fa0>)
(PYUFedAvgW pid=12216)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/tensorflow/fl_base.py", line 61, in __init__
(PYUFedAvgW pid=12216)     super().__init__(builder_base)
(PYUFedAvgW pid=12216)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/tensorflow/fl_base.py", line 34, in __init__
(PYUFedAvgW pid=12216)     self.model_base = builder_base() if builder_base is not None else None
(PYUFedAvgW pid=12216)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
(PYUFedAvgW pid=12216)     raise e.with_traceback(filtered_tb) from None
(PYUFedAvgW pid=12216)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/keras/utils/layer_utils.py", line 812, in split_out_first_arg
(PYUFedAvgW pid=12216)     raise ValueError(
(PYUFedAvgW pid=12216) ValueError: The first argument to `Layer.call` must always be passed.
(PYUFedAvgW pid=12254) 2023-01-09 14:40:07.412224: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
(PYUFedAvgW pid=12254) 2023-01-09 14:40:07.412260: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
(PYUFedAvgW pid=12254) WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
(PYUFedAvgW pid=12254) 2023-01-09 14:40:07,885  ERROR worker.py:451 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PYUFedAvgW.__init__() (pid=12254, ip=172.30.166.62, repr=<secretflow.ml.nn.fl.backend.tensorflow.strategy.fed_avg_w.PYUFedAvgW object at 0x7f8ab39d7fa0>)
(PYUFedAvgW pid=12254)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/tensorflow/fl_base.py", line 61, in __init__
(PYUFedAvgW pid=12254)     super().__init__(builder_base)
(PYUFedAvgW pid=12254)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/tensorflow/fl_base.py", line 34, in __init__
(PYUFedAvgW pid=12254)     self.model_base = builder_base() if builder_base is not None else None
(PYUFedAvgW pid=12254)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
(PYUFedAvgW pid=12254)     raise e.with_traceback(filtered_tb) from None
(PYUFedAvgW pid=12254)   File "/usr/local/python/python-3.8.15/lib/python3.8/site-packages/keras/utils/layer_utils.py", line 812, in split_out_first_arg
(PYUFedAvgW pid=12254)     raise ValueError(
(PYUFedAvgW pid=12254) ValueError: The first argument to `Layer.call` must always be passed.
```

### Reproduction code to reproduce the issue.

```shell
执行水平联邦nn案例这段代码时报错
fed_model = FLModel(server=charlie,
                    device_list=device_list,
                    model=model,
                    aggregator=secure_aggregator,
                    strategy="fed_avg_w",
                    backend = "tensorflow")
```

**Comment by zhangxingmeng** [comment]
代码贴一下吧

**Comment by turbominxi** [comment]
import secretflow as sf


# In case you have a running secretflow runtime already.
sf.shutdown()


sf.init(['alice', 'bob', 'cherry', 'charlie'],num_cpus=8)
alice, bob, cherry, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('cherry'),sf.PYU('charlie')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob','cherry']))






#构造水平联邦数据
import sys
import time
import logging


from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay
from secretflow.ml.linear.ss_sgd import SSRegression
from secretflow.data.ndarray import train_test_split
from sklearn.metrics import roc_auc_score
import numpy as np
# Horizontal partitioning.
X_train1 = np.load("/usr/local/python/wppcc/data/X_train1.npy")
y_train1 = np.load("/usr/local/python/wppcc/data/y_train1.npy")


X_train2 = np.load("/usr/local/python/wppcc/data/X_train2.npy")
y_train2 = np.load("/usr/local/python/wppcc/data/y_train2.npy")


X_train3 = np.load("/usr/local/python/wppcc/data/X_train3.npy")
y_train3 = np.load("/usr/local/python/wppcc/data/y_train3.npy")




x = FedNdarray(
&nbsp; &nbsp; partitions={
&nbsp; &nbsp; &nbsp; &nbsp; alice: X_train1,
&nbsp; &nbsp; &nbsp; &nbsp; bob: X_train2,
&nbsp; &nbsp; &nbsp; &nbsp; cherry: X_train3,
&nbsp; &nbsp; },
&nbsp; &nbsp; partition_way=PartitionWay.HORIZONTAL,
)
# Y label belongs to alice
y =&nbsp; FedNdarray(
&nbsp; &nbsp; partitions={alice: y_train1,
&nbsp; &nbsp; &nbsp; &nbsp; bob: y_train2,
&nbsp; &nbsp; &nbsp; &nbsp; cherry: y_train3,},
&nbsp; &nbsp; partition_way=PartitionWay.VERTICAL,
)


#数组拆分




x_train,x_valid=train_test_split(x, 0.3, random_state = 512, shuffle=False)
y_train,y_valid=train_test_split(y, 0.3, random_state = 512, shuffle=False)




num_classes = 8
input_shape = (80, 80, 3)&nbsp; &nbsp;&nbsp;
from secretflow.security.aggregation import SPUAggregator, SecureAggregator
from secretflow.ml.nn import FLModel
from tensorflow import keras
from tensorflow.keras import layers
&nbsp; &nbsp; &nbsp; &nbsp; # Create model
model = keras.Sequential([
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; keras.Input(shape=input_shape),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.MaxPooling2D(pool_size=(2, 2)),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.MaxPooling2D(pool_size=(2, 2)),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.Flatten(),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.Dropout(0.5),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layers.Dense(num_classes, activation="softmax")])
		
		
model.compile(loss='categorical_crossentropy',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; optimizer='adam',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; metrics=["accuracy"])
					&nbsp;&nbsp;
					&nbsp;&nbsp;
					&nbsp;&nbsp;
device_list = [alice, bob, cherry]


secure_aggregator = SecureAggregator(charlie, [alice, bob, cherry])
spu_aggregator = SPUAggregator(spu)




fed_model = FLModel(server=charlie,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; device_list=device_list,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; model=model,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; aggregator=secure_aggregator,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; strategy="fed_avg_w",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; backend = "tensorflow")





陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] ValueError: The first argument to `Layer.call` must always be passed. (Issue #254)





 
代码贴一下吧

**Comment by zhangxingmeng** [comment]
> 

可以调整下格式吗？

**Comment by turbominxi** [comment]
格式有什么问题呢，有调整的建议吗




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] ValueError: The first argument to `Layer.call` must always be passed. (Issue #254)





   
可以调整下格式吗？

**Comment by zhangxingmeng** [comment]
你需要把模型定义warp在一个函数里面，可以参考一下tutorial里面的例子
