### ISSUE TITLE
Split nn 是否支持一方全部 feature 另一方只有 label ?

### ISSUE THREAD

**Issue by nkhklholyf** [secretflow/secretflow#256]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow v0.7.11b3

### OS Platform and Distribution

linux debian9

### Python version

3.8

### What happend and What you expected to happen.

```shell
有一种应用场景，是 bob 拥有全部特征，alice 拥有标签，希望使用 split-nn 来训练纵向神经网络模型
理论上这种只需要一方配置 base model 另一方配置 fuse model 
但是发现 base model 必须双方都有，model 无论设置为 None 或者不写都会报错
请问现在有没有方法可以支持这个场景？
```

### Reproduction code to reproduce the issue.

```shell
# raise error
base_model_dict = {
    alice: None,
    bob:   model_base_bob
}
# raise error
base_model_dict = {
    bob:   model_base_bob
}
```

**Comment by zhangxingmeng** [comment]
这个目前还没办法支持。如果某一方只是提供label，没有basenet的话，对于label信息几乎就是泄露掉了

**Comment by FelixZheng1** [comment]
如果只是想在隐语中单纯实现这个模型，可以在两方均定义base model，Alice这边构造假数据，例如zero array，同时fuse net对hidden layers进行sum（Alice 的hidden layer也是zero array）

**Comment by FelixZheng1** [comment]
目前隐语中的拆分学习只面向了最通用的数据垂直切分的场景，欢迎contribute其它framework到隐语中

**Comment by nkhklholyf** [comment]
> 如果只是想在隐语中单纯实现这个模型，可以在两方均定义base model，Alice这边构造假数据，例如zero array，同时fuse net对hidden layers进行sum（Alice 的hidden layer也是zero array）

谢谢，这个可能是个可行方案，还有个问题，split nn 里面 DP 策略配置参数有文档吗？另外有啥办法可以不使用 DP 而是 Plain Text ?

**Comment by nkhklholyf** [comment]
> 这个目前还没办法支持。如果某一方只是提供label，没有basenet的话，对于label信息几乎就是泄露掉了

谢谢。这个结论有依据吗，就是如果一方有 label + feature，可以避免泄露吗

**Comment by FelixZheng1** [comment]
> > 如果只是想在隐语中单纯实现这个模型，可以在两方均定义base model，Alice这边构造假数据，例如zero array，同时fuse net对hidden layers进行sum（Alice 的hidden layer也是zero array）
> 
> 谢谢，这个可能是个可行方案，还有个问题，split nn 里面 DP 策略配置参数有文档吗？另外有啥办法可以不使用 DP 而是 Plain Text ?

DP参数的设定可以参看开发者文档
定义SL_model时，令dp_strategy_dict=None即为plain text

**Comment by zhangxingmeng** [comment]
> 这个目前还没办法支持。如果某一方只是提供label，没有basenet的话，对于label信息几乎就是泄露掉了

FYI：目前SLModel已经支持一方特征一方标签的模式
