### ISSUE TITLE
可信性证明

### ISSUE THREAD

**Issue by Wyyyb** [secretflow/secretflow#26]
请问secretflow有提供示例来验证可信性吗？看到spu设备用reveal方法就可以获取原文。

**Comment by Wyyyb** [comment]
在生产环境中，数据提供方会把存有数据的spu设备共享给其他参与方吗

**Comment by Wyyyb** [comment]
或者可否提供一个生产代码的示例。

**Comment by 6fj** [comment]
Hi @Wyyyb ,

spu基于MPC，本身是安全可证的，请查看https://github.com/secretflow/spu。

当通过secretflow创建和调用spu device时，我们并不会限制pyu设备(数据提供方)和spu设备的关系。当spu设备和pyu设备隔离的时候，我们称之为outsourcing模式(https://spu.readthedocs.io/en/beta/development/runtime.html#outsourcing)；当spu设备和pyu设备在同一个host的时候，我们称之为colocated模式(https://spu.readthedocs.io/en/beta/development/runtime.html#colocated)。

在业务场景中选择何种模式部署spu设备需要综合考虑多种因素，需要用户自行决定。

**Comment by wuxibin89** [comment]
> 在生产环境中，数据提供方会把存有数据的spu设备共享给其他参与方吗

隐语采用的是集中式、单控制编程模型，即由一个driver驱动所有的数据参与方、计算方，这一点要和MPI SPMD模式相区分。Driver所执行的程序是用户编写的算法流程，在生产环境中位于一个中心化的平台。
因此，数据提供方会把存有数据的spu设备共享给其他参与方吗？不会，数据提供方只是被动接受指令的角色。
那如何保证driver不会作恶呢？有两种思路：
1. Driver的代码高度固化，用户通过图形化组件构建workflow
2. Driver的代码经过各参与方peer review才能执行，常用于联邦学习场景

以上两种思路不论采用哪种方法，都可以严格限制`reveal`的使用。

**Comment by Wyyyb** [comment]
> 

<img width="831" alt="image" src="https://user-images.githubusercontent.com/20929360/178395726-9f2b91e7-b12b-4af9-9c49-2ffdfc92fd0e.png">
以Tutorial中提供的逻辑回归为例，请问例程对应的实际生产代码中，load_train_dataset传输的是什么呢？需要将明文传输给driver还是以某种设备的形式提供给driver?

**Comment by Wyyyb** [comment]
或者数据提供方是不需要写代码的，而是给运行driver的中心化平台一个授权？那这个授权是允许driver明文形式访问的吗？

**Comment by wuxibin89** [comment]
> 请问例程对应的实际生产代码中，load_train_dataset传输的是什么呢？

这段的含义是说将`load_train_dataset`调度到数据提供方alice, bob执行，返回值x1, x2是DeviceObject。DeviceObject可以理解为指向alice, bob的远程数据指针。Driver拿到的是数据指针，alice, bob没有将任何数据传输给driver。

> 数据提供方是不需要写代码的，而是给运行driver的中心化平台一个授权？

是的，算法由driver中心化编程，数据提供方不需要写代码。

> 那这个授权是允许driver以明文形式访问的吗？

不允许，driver不应该获取任何数据提供方的数据，它只是在逻辑设备上(SPU/HEU/TEE/PYU)上进行任务编排，获取的DeviceObject是远程数据指针。

**Comment by Wyyyb** [comment]
> DeviceObject可以理解为指向alice, bob的远程数据指针。Driver拿到的是数据指针，alice, bob没有将任何数据传输给driver。

是不是可以理解为创建spu的时候用的是数据指针，而在spu(fit)(x1, x2)等计算函数执行的时候，会从数据提供方请求一些以某种协议加密好的数据(通信过程)，而这些加密协议和对加密数据的操作是由spu、heu等抽象设备底层实现好的，使用者不需要对其编码。

**Comment by wuxibin89** [comment]
你的理解基本上是对的，不过数据从`提供方`(alice, bob)传输到`计算方`(spu)，不是在spu(fit)(x1, x2)计算时发生的，而是在`DeviceObject.to`执行的时候发生的。这个过程有点像把一个数据从CPU加载进GPU：
```
alice, bob = PYU("alice"), PYU("bob")      # PYU device表示数据提供方
x1, x2 = alice(load_train_dataset)("data.csv"), alice(load_train_dataset)("data.csv")    # x1, x2是PYUObject，远程数据指针
x1_, x2_ = x1.to(spu), x2.to(spu)    # x1_, x2_是SPUObject，此时数据提供方的明文数据以secret sharing协议拆分到SPU
losses = spu(fit)(x1_, x2_)  # 在SPU上执行fit函数
```
SecretFlow的整体设计思想是把数据提供方，计算方抽象成逻辑设备PYU、SPU、HEU、TEE，用户在逻辑设备上进行编程，构建出一张逻辑计算图。在这张计算图中，当发生跨设备数据流动的时候，就会按照(源设备，目标设备)预定的转换协议对数据进行转换。

**Comment by Wyyyb** [comment]
明白了，感谢两位老师的耐心解答。

**Comment by LeoneChen** [comment]
> > 在生产环境中，数据提供方会把存有数据的spu设备共享给其他参与方吗
> 
> 隐语采用的是集中式、单控制编程模型，即由一个driver驱动所有的数据参与方、计算方，这一点要和MPI SPMD模式相区分。Driver所执行的程序是用户编写的算法流程，在生产环境中位于一个中心化的平台。 因此，数据提供方会把存有数据的spu设备共享给其他参与方吗？不会，数据提供方只是被动接受指令的角色。 那如何保证driver不会作恶呢？有两种思路：
> 
> 1. Driver的代码高度固化，用户通过图形化组件构建workflow
> 2. Driver的代码经过各参与方peer review才能执行，常用于联邦学习场景
> 
> 以上两种思路不论采用哪种方法，都可以严格限制`reveal`的使用。

您好~

但是隐私计算方依然可以不依赖UI组件来实现计算任务，通过python脚本调API。就算代码被review了，计算方依然可以在review之后加上一行reveal代码。我的理解还是需要有实体来做访问控制，但是这就涉及如何禁止直接数据访问并施加访问控制，然后还有实施访问控制的主体是谁

**Comment by 6fj** [comment]
Hi @LeoneChen 

简单的做法是，我们可以给代码加上signature来确保执行的代码和之前review的是同一份代码。

**Comment by LeoneChen** [comment]
> Hi @LeoneChen
> 
> 简单的做法是，我们可以给代码加上signature来确保执行的代码和之前review的是同一份代码。

您好~

想继续问一下应该谁来验证签名呢？

**Comment by 6fj** [comment]
我想可能都不需要签名。

假设alice邀请bob执行代码，bob收到代码只需计算并保存checksum即可。等后续执行时，只需校验下发的代码和之前的checksum是否一致即可。

**Comment by 6fj** [comment]
这里的本质问题是数据的转移是sender push 到 reciver 而不是 reciever pull from sender。如果确保是前者，那么即使reciever独自执行的reveal到本方的代码也没有意义-因为sender不会配合。

**Comment by LeoneChen** [comment]
如果数据指的是reveal出来的数据。bob在验证alice代码符合预期后，允许把数据发给alice，那么bob如何验证alice代码符合预期呢，bob应该只能通过网络拿到alice发送的代码，但是alice可以执行与发送的代码（符合bob预期）不一样的代码（恶意的reveal）

**Comment by 6fj** [comment]
在你上面的例子里，如果执行reveal bob的数据到alice的操作，是需要bob主动发送给alice吗？

**Comment by LeoneChen** [comment]
![image](https://github.com/secretflow/secretflow/assets/35480440/d9529d9f-9881-4431-9c21-d04ae1fef17c)


我还在看reveal的代码逻辑，它里面的注释看起来像是bob所在的本地节点（要么bob的PYU，要么对应的SPU）会提供数据，有点担心

**Comment by 6fj** [comment]
你应该看的是rayfed中的get，如果你再往下阅读几行，你应该就能得到答案 :)

anyway, 最重要的是数据是不是owner主动send。

**Comment by LeoneChen** [comment]
https://github.com/secretflow/secretflow/blob/ba97f9d45ecfc249a72dbf81e275916e5fefa5b6/secretflow/device/driver.py#L115-L162

对，因为reveal到get中间没有任何权限之类的检查

**Comment by LeoneChen** [comment]
> 这里的本质问题是数据的转移是sender push 到 reciver 而不是 reciever pull from sender。如果确保是前者，那么即使reciever独自执行的reveal到本方的代码也没有意义-因为sender不会配合。

感谢~我大概理解了。 Alice reveal bob数据时会处于recv状态，等待数据到来，此时必须bob reveal自己的数据才会将数据分发给其它节点比如alice，alice在收到数据后会退出阻塞状态，返回数据
