### ISSUE TITLE
隐语支持分布式计算吗

### ISSUE THREAD

**Issue by hust-suwb** [secretflow/secretflow#264]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.7.18

### OS Platform and Distribution

Debian 11

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
从文档来看，cluster的部署模式指的是参与方A和B在不同的机器上部署，从而组成的一个隐私计算的集群。那请问对于参与方A单方而言，是否可以集群化部署计算节点，实现分布式计算呢。
目前我有查阅到两个信息，似乎有些冲突。
请问下面两个描述是否有问题。如果都是对的，怎么理解，单参与方是否可以集群化部署以实现分布式计算。
```

### Reproduction code to reproduce the issue.

```shell
#1：https://github.com/secretflow/secretflow/discussions/115 里提到「目前SPU仅支持standalone模式（单个party内只有一个进程）」。意思是单方不能分布式计算。
#2：https://www.yuque.com/secret-flow/admin/mp1q3m 里提到对于MPC服务或者FL服务等，都可以部署1台以上的机器，似乎单方又是支持分布式计算的。
```

**Comment by zhouaihui** [comment]
hi, @hust-suwb, 
1. 当前SPU只能支持单机版本，所以如果要使用spu的话，ray只能启动一个节点。多节点ray集群支持SPU还在研发中，会在后续版本发布。
2. 如果不使用SPU的话，则机构内的ray可以是多节点集群。

**Comment by hust-suwb** [comment]
> hi, @hust-suwb,
> 
> 1. 当前SPU只能支持单机版本，所以如果要使用spu的话，ray只能启动一个节点。多节点ray集群支持SPU还在研发中，会在后续版本发布。
> 2. 如果不使用SPU的话，则机构内的ray可以是多节点集群。

@zhouaihui 你好。所以如果是heu的话，则可以支持多节点的ray集群的是吧。那这其中密文设备这一层做了哪些事情，ray又做了哪些事情呢。

**Comment by zhouaihui** [comment]
hi, @hust-suwb , ray作为分布式执行引擎执行计算任务（actor or function）。
密文设备除了SPU有独立通信链路外，HEU的通信是走rayfed的，和明文设备等是一样的。
