### ISSUE TITLE
RayFed failed to setup connection

### ISSUE THREAD

**Issue by imwangyt** [secretflow/secretflow#266]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.18

### OS Platform and Distribution

secretflow-anolis8:0.7.18

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
1、两个主机192.168.12.13 & 192.168.12.14
2、docker run --network host -it secretflow/secretflow-anolis8:0.7.18
3、分别使用9913、9914启动各自的head node
(secretflow) bash-4.4# ray start --head --node-ip-address="192.168.12.14" --port="9914" --include-dashboard=False --disable-usage-stats
4、分别使用9923、9924初始化secretflow
5、在alice侧，使用9933、9934构建spu，报错：
>>> spudev.(SPURuntime pid=4349) 2023-01-13 06:55:54,416        ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=4349, ip=192.168.12.13, repr=<secretflow.device.device.spu.SPURuntime object at 0x7faf98f02a30>)
(SPURuntime pid=4349)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=4349)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=4349) RuntimeError: what: 
(SPURuntime pid=4349)   [external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=1
(SPURuntime pid=4349) stacktrace: 
(SPURuntime pid=4349) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fafa8f40519
(SPURuntime pid=4349) #1 pybind11::cpp_function::dispatcher()+0x7fafa8f2ac5b
(SPURuntime pid=4349) #2 PyCFunction_Call+0x4dfd82

6、在alice侧，spu配置中的bob端口换成9924（bob集群的ray::RecverPro），报相同错误。
```

### Reproduction code to reproduce the issue.

```shell
# RayFed集群配置
cluster_config ={
    'parties': {
        'alice': {
            'address': '192.168.12.13:9923'
        },
        'bob': {
            'address': '192.168.12.14:9924'
        },
    },
    'self_party': 'bob'
}
import secretflow as sf
sf.init(address='192.168.12.14:9914', cluster_config=cluster_config)

import spu
cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '192.168.12.13:9933'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '192.168.12.14:9934'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spudev = sf.SPU(cluster_def=cluster_def)
```

**Comment by imwangyt** [comment]
还有几个相关的疑问：

疑问1：每个party的ray cluster集群，目前只能启动head node节点；比如alice，如果有另外机器192.168.12.15，执行ray start --address='192.168.12.13.9913'后，马上ray status可以看到有两个node，但大概30s后，只能看到head node了，而且ray stop时，只有一个进程：Stopped all 1 Ray processes.

疑问2：RayFed初始化时，必须在alice和bob侧都启动Driver进行初始化，否则无法启动ray::RecverPro。那问题来了，这个初始化RayFed用的driver进程进行必须常驻，不能关闭？感觉逻辑不对，ray::RecverPro（Proxy）应该是Long-time service，类似ray node。

疑问3：spu构建时，非本方party的访问地址应该就是ray::RecverPro（Proxy），那就不应该重新指定端口。

**Comment by zhouaihui** [comment]
可以看一下两边SPURuntime的启动时间吗？是否可能是启动时间差别大，导致连接失败。如果是这种情况，可以调整[SPU
 link_desc](https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.html#secretflow.SPU.__init__)。

**Comment by zhouaihui** [comment]
疑问1：这个问题看起来只和ray有关系，可以发一下ray的日志吗？/tmp/ray/session_{时间}/logs

**Comment by zhouaihui** [comment]
疑问2：
目前设计上的确是SendProxy和drvier的生命周期绑定。后续版本会考虑做成常驻的Actor。

**Comment by zhouaihui** [comment]
疑问3：
可以描述的更清晰吗？没看懂问题，spu的通信是单独的，不经过proxy

**Comment by zhouaihui** [comment]
再补充一下，目前版本SPU是单独通信，所以如果要使用SPU的话，ray只能是单节点集群。后续会发布支持SPU的单机构内部集群版rayfed。

**Comment by imwangyt** [comment]
> 

意思是SPU参与方的通信，不经过RayFed么？

**Comment by imwangyt** [comment]
> 疑问3： 可以描述的更清晰吗？没看懂问题，spu的通信是单独的，不经过proxy

意思是SPU参与方之间的通信，不走RayFed么？

**Comment by imwangyt** [comment]
> 再补充一下，目前版本SPU是单独通信，所以如果要使用SPU的话，ray只能是单节点集群。后续会发布支持SPU的单机构内部集群版rayfed。
没太明白，我描述一下场景：有两个参与方（机构）alice和bob，各自有两台主机alice1、alice2、bob1和bob2，打算各自组成Ray集群进行联合计算，分别是AliceCluster(alice1, alice2)和BobCluster(bob1, bob2)，假如alice1和bob1分别是各自的Head Node。
您说的`单节点集群`、`单机构内部集群版rayfed`分别指什么？现有的RayFed能支持什么样的部署结构？

**Comment by imwangyt** [comment]
> 疑问1：这个问题看起来只和ray有关系，可以发一下ray的日志吗？/tmp/ray/session_{时间}/logs

有点诡异，换了另外一台机器，可以顺利保持与head node的通信，ray status也正常。

ray日志如下，有检查系统时间是同步的：
secretflow) bash-4.4# cat /tmp/ray/session_latest/logs/raylet.err 
[2023-01-13 09:48:25,183 C 51 51] (raylet) node_manager.cc:1060: [Timeout] Exiting because this node manager has mistakenly been marked as dead by the GCS: GCS didn't receive heartbeats from this node for 30000 ms. This is likely because the machine or raylet has become overloaded.
*** StackTrace Information ***
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x4fa17a) [0x555db811a17a] ray::operator<<()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x4fbc52) [0x555db811bc52] ray::SpdLogMessage::Flush()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x4fbf67) [0x555db811bf67] ray::RayLog::~RayLog()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x27e543) [0x555db7e9e543] ray::raylet::NodeManager::NodeRemoved()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x3ee1cf) [0x555db800e1cf] ray::gcs::NodeInfoAccessor::HandleNotification()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x4ddf96) [0x555db80fdf96] EventTracker::RecordExecution()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x47869e) [0x555db809869e] std::_Function_handler<>::_M_invoke()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x478bf6) [0x555db8098bf6] boost::asio::detail::completion_handler<>::do_complete()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0xa4a87b) [0x555db866a87b] boost::asio::detail::scheduler::do_run_one()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0xa4c041) [0x555db866c041] boost::asio::detail::scheduler::run()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0xa4c270) [0x555db866c270] boost::asio::io_context::run()
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x15b1a9) [0x555db7d7b1a9] main
/lib64/libc.so.6(__libc_start_main+0xf3) [0x7f84030ed493] __libc_start_main
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet(+0x19b1b7) [0x555db7dbb1b7]

**Comment by imwangyt** [comment]
> 可以看一下两边SPURuntime的启动时间吗？是否可能是启动时间差别大，导致连接失败。如果是这种情况，可以调整[SPU link_desc](https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.html#secretflow.SPU.__init__)。

先跟您确认一下，目前是机构alice和机构bob分别使用alice1和bob1作为ray head node节点，所以alice1和bob1要准备三组port，分别是：
- ray gcs port = 9913、9914
- rayfed cluster port = 9923、9924
- secretflow spu port = 9933、9934
这个没问题吧？

**Comment by zhouaihui** [comment]
> > 疑问3： 可以描述的更清晰吗？没看懂问题，spu的通信是单独的，不经过proxy
> 
> 您的意思是SPU参与方之间的通信，不走RayFed么？如果是的话，那我这个问题就不存在了。 我理解的Proxy是等同机构的gateway，机构之间的通信都要通过gateway，机构内部Ray集群成员之间不需要经过gateway。这样子可以简化机构之间的通信，也减少机构的安全暴露面。

现状是这样的，SPU有独立通信链路，不经过rayfed。所有通信统一到gateway，这个是比较理想的状态，SecretFlow正在开发这块的能力。

**Comment by zhouaihui** [comment]
> > 再补充一下，目前版本SPU是单独通信，所以如果要使用SPU的话，ray只能是单节点集群。后续会发布支持SPU的单机构内部集群版rayfed。
> 
> 没太明白，我描述一下场景：有两个参与方（机构）alice和bob，各自有两台主机alice1、alice2、bob1和bob2，打算各自组成Ray集群进行联合计算，分别是AliceCluster(alice1, alice2)和BobCluster(bob1, bob2)，假如alice1和bob1分别是各自的Head Node。 您说的`单节点集群`、`单机构内部集群版rayfed`分别指什么？现有的RayFed能支持什么样的部署结构？

SecretFlow目前支持的多控制器模式（rayfed）可以理解为：每个机构都有一个单独的ray集群，每个机构同时执行代码，代码通过ray进行调度执行。

在上面这个前提下，ray理论上可以是单节点或者多节点。但是现在由于SPU的通信链路是独立的，SPU在构建实例时需要提前给出各方的通信地址，当ray是多个节点的时候，这个通信地址无法提前预判，因为ray可能把spu调度到任一节点上。这也是前面说的为什么如果使用SPU，则ray不能是多个节点的原因。

所以你前面提到的通信统一到gateway是比较理想的状态，目前的proxy还没有这么强大的能力，未来版本会补齐。

**Comment by zhouaihui** [comment]
> > 可以看一下两边SPURuntime的启动时间吗？是否可能是启动时间差别大，导致连接失败。如果是这种情况，可以调整[SPU link_desc](https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.html#secretflow.SPU.__init__)。
> 
> 先跟您确认一下，目前是机构alice和机构bob分别使用alice1和bob1作为ray head node节点，所以alice1和bob1要准备三组port，分别是：
> 
> * ray gcs port = 9913、9914
> * rayfed cluster port = 9923、9924
> * secretflow spu port = 9933、9934
>   这个没问题吧？

只要不冲突就可以的，看着ok。目前SPU只能部署单节点ray哈，抱歉得记住这个前提。

**Comment by imwangyt** [comment]
解决。有一台未检查防火墙导致。
