### ISSUE TITLE
开源了哪些模块？是否方便列一下？

### ISSUE THREAD

**Issue by ChrisYuan** [secretflow/secretflow#267]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow latest

### OS Platform and Distribution

UBT

### Python version

3.8

### What happend and What you expected to happen.

```shell
请问贵公司开源的 secretflow 都开源了哪些模块？github readme 结构图上的所有模块都开源了吗？
```

### Reproduction code to reproduce the issue.

```shell
fyi
```

**Comment by Chrisdehe** [comment]
您好，ChrisYuan！
我们是有整体的开源计划的，您可以关注我们的VX公众号：隐语的小剧场
B站up主：隐语SecretFlow
隐语小助手wx号：secretflow01 （需要加群可以找小助手） 
隐语邮箱：secretflow-contact@service.alipay.com
当中的内容会比较详细，我想可以能够帮助到您！
祝您新年快乐！
