### ISSUE TITLE
提供真实多方MPC读取本地数据和模型的应用实例，而不是简化用单一程序模拟多方交互

### ISSUE THREAD

**Issue by gcrocky** [secretflow/secretflow#269]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

20.04

### Python version

3.8

### What happend and What you expected to happen.

```shell
是否可以提供模拟多方MPC的应用例子，因为多方独行执行算子或者模型的时候，读取的本地自己数据/加载本地自己模型，但是我们看到例子，都是一个程序完成数据和模型的加载，这种例子不能满足数据不离开本地，数据可用不可见的特性。 
建议提供 真正意义上的 多方MPC的应用例子，而不是一个程序就处理所有的演示，谢谢
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by zhouaihui** [comment]
hi, @gcrocky , SecretFlow的一大特色是集中式编程，跨机构分布式执行。
通俗一点解释，你看到的代码实际执行的时候，读取数据/加载模型仍然是发生在机构本地的，数据并没有出域。比如下面这段代码
```
import secretflow as sf

alice = sf.PYU('alice')

def load_data(data_of_alice):
    pass

alice(load_data)('/path/of/alice/data')
```

上面代码表示alice读取alice本地的文件（'/path/of/alice/data'）。

文档中的例子，为了方便模拟，给的可能是单机模拟的例子，是用单机模拟了多个机构。
如果你想变成多机构执行，则可以按照多机构多机部署的方式部署SecretFlow，参考 [SecretFlow生产模式](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#production)。
你的代码几乎可以无缝迁移成生产模式。

快速仿真的代码和生产部署几乎无gap，这也是SecretFlow的特色。

**Comment by gcrocky** [comment]
隐语的设计理念，我明白了，谢谢。
假如我们编写一个如下模型代码，代码中是顺序加载多方数据，然后直接执行后续PSI或者训练逻辑。
但是有2个问题，
1） 在任意一方执行这个代码逻辑都是应该报错的，因为他只能读取自己的数据，这个怎么处理或者解释；
2）在我们执行类似PSI动作时，如果只有一方准备好数据，当前系统处于什么状态，异常退出，还是等待对方数据到位，还是超时退出？
```
input_path = {alice: '.data/alice.csv', bob: '.data/bob.csv'}
output_path = {alice: '.data/alice_psi.csv', bob: '.data/bob_psi.csv'}
spu.psi_csv('uid', input_path, output_path, 'alice')
```

**Comment by icavan** [comment]
> 隐语的设计理念，我明白了，谢谢。 假如我们编写一个如下模型代码，代码中是顺序加载多方数据，然后直接执行后续PSI或者训练逻辑。 但是有2个问题， 1） 在任意一方执行这个代码逻辑都是应该报错的，因为他只能读取自己的数据，这个怎么处理或者解释； 2）在我们执行类似PSI动作时，如果只有一方准备好数据，当前系统处于什么状态，异常退出，还是等待对方数据到位，还是超时退出？
> 
> ```
> input_path = {alice: '.data/alice.csv', bob: '.data/bob.csv'}
> output_path = {alice: '.data/alice_psi.csv', bob: '.data/bob_psi.csv'}
> spu.psi_csv('uid', input_path, output_path, 'alice')
> ```

你调用的是隐语封装过的 API，这些 API 都是 global view 的，不是 local 能直接执行的，这些 global 语义 API 内部会进一步把任务拆成 alice/bob local 可以运行的任务去继续执行。并不是直接在 local evaluate 这个 global function.

1、 spu.psi_csv('uid', input_path, output_path, 'alice')
这里 spu device 的 psi_csv 源码实际上内部就是让多方同时执行 SPURuntime::psi_csv ( https://github.com/secretflow/secretflow/blob/main/secretflow/device/device/spu.py#L1187 ) ， 这个函数进一步是进入到 cpp  层进行 psi 的工作，然后 alice side 读取 alice 自己的数据进入算法流程，bob 类似。
2、 这是一个工程处理的问题，我们假设目前 alice 数据准备好， bob 数据文件不存在。实际的行为两边各自同时跑， alice 会进入正常流程，直到等待 bob 的一阶加密密文过来，但由于 bob 发现本地数据文件不存在，因此 bob 执行流会直接异常退出。导致 alice 等待 bob 失败/超时，因此 alice 也会因为这个超时/接收异常退出。

**Comment by gcrocky** [comment]
谢谢，还有一个问题，场景如下： alice\bob\carol各自设置为PYU，alice\bob设置为SPU，对于我们执行备注中的程序：alice与bob隐私求交，正常情况的下求交结果只能alice和bob可以访问到，但是如果这个程序被carol执行(窃取的程序)，他是否会通过类似的方法alice(pd.read_csv)(output_path[alice])读取alice或者bob的数据？

import secretflow as sf
cluster = {
    'parties': {
        'alice': {'address': f'{alice_address}:{alice_port}'},
        'bob': {'address': f'{bob_address}:{bob_port}'},
        'carol': {'address': f'{carol_address}:{carol_port}'}
    },
    'self_party': self_party
}

sf.init(address=f'{self_party_address}:{self_party_port}', cluster_config=cluster)
alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')

spu_cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': f'{alice_address}:{alice_port + 1000}',
            'listen_addr': f'0.0.0.0:{alice_port + 1000}'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': f'{bob_address}:{bob_port + 1000}',
            'listen_addr': f'0.0.0.0:{bob_port + 1000}'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu_cluster = sf.SPU(cluster_def=spu_cluster_def)
input_path = {alice: f'{alice_input_path}', bob: f'{bob_input_path}'}
output_path = {alice: f'{alice_output_path}', bob: f'{bob_output_path}'}
spu_cluster.psi_join_csv('column2', input_path, output_path, 'alice', 'bob')

alice_result = alice(pd.read_csv)(output_path[alice])
bob_result = bob(pd.read_csv)(output_path[bob])

**Comment by zhouaihui** [comment]
@gcrocky , 在生成模式下，每一个参与方都是一个独立的ray集群，代码需要所有参与方同时执行才能完成协作。
所以按照你的假设，carol偷偷跑了一段代码，但是只要alice没有跑这段代码，是没有任何作用的。

**Comment by gcrocky** [comment]
谢谢，
问题1: 每一个参与方都是一个独立的ray集群，这个能详细解释下吗？对于alice\bob\carol这三个机构，则需要部署3个集群，每个集群上都有可能部署多个服务器？
问题2: 您提到：“carol偷偷跑了一段代码，但是只要alice没有跑这段代码，是没有任何作用的”， 但是我们编写的程序调用的API都是global view，这些 global 语义 API 内部会进一步把任务拆成 alice/bob local 可以运行的任务去继续执行，所以它并不需要一定在alice中执行，基于此，我的理解 carol是可以完整的执行该程序。

**Comment by zhouaihui** [comment]
Q1: 前面提到的[SecretFlow生产模式](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#production)有介绍如何部署。
Q2：你的理解仅在仿真模式下成立，仿真模式是用单个ray集群模拟多个机构。生产模式下是需要所有方一起跑代码才能work的。
Q3：send是隐藏在SecretFlow通信底层，不直接对用户暴露。
比如
```
alice_data = alice(load_data)('/path/of/data')
# 下面这个to其实就是alice send data给bob。
alice_data.to(bob)
```

**Comment by gcrocky** [comment]
非常感谢，还有一个问题，应该也是最后一个问题了，
对于问题2的进一步讨论，我的理解是：无论生产模式还是仿真模式，我们编写的程序从外部来看，仅仅被执行一次，应该是我们隐语的底层去驱动不同机构执行不同逻辑代码，所以carol是可以完整的执行该程序。 但是您提到需要所有方一起跑代码才能work的，只要双方数据准备到位，服务正常的话，就一定可以work.  所以，该问题还是困惑，谢谢

**Comment by zhouaihui** [comment]
@gcrocky 感谢你的提问。

隐语提供了站在全局集中视角写分布式代码，但是并没有代码仅执行一次的概念。可能这个观念来自于你运行我们的教程文档？为了方便用户体验，隐语的教程文档都是默认用仿真模式以减少用户上手成本。

> 隐语的底层去驱动不同机构执行不同逻辑代码
这件事情在仿真模式下，是单一的driver驱动。但是在生产模式下，是多个driver驱动的（每个机构一个）。

**Comment by gcrocky** [comment]
谢谢您的解答，也请您确认下，在生产模式，我们这样处理是否正确， 唯一的不同是self_party,  这两个程序在各自Ray集群中发布并执行
对于alice的ray集群，我们发布并执行如下程序：
```cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': 'ip:port',
            'listen_addr': '0.0.0.0:port'
        },
        'bob': {
            # replace with bob's real address.
            'address': 'ip:port',
            'listen_addr': '0.0.0.0:port'
        },
    },
    'self_party': alice
}

```

对于bob的ray集群，我们发布并执行如下程序：
```cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': 'ip:port',
            'listen_addr': '0.0.0.0:port'
        },
        'bob': {
            # replace with bob's real address.
            'address': 'ip:port',
            'listen_addr': '0.0.0.0:port'
        },
    },
    'self_party': alice
}

```

**Comment by onelyfly** [comment]
对于bob的ray集群，代码块里，alice_result = alice(pd.read_csv)(output_path[alice]) 这行代码其实是无效的或拿不到值？

**Comment by zhouaihui** [comment]
> 对于bob的ray集群，代码块里，alice_result = alice(pd.read_csv)(output_path[alice]) 这行代码其实是无效的或拿不到值？

是的。bob不会真的执行这行代码，因为bob并没有能力去执行。
