### ISSUE TITLE
源码安装出现错误

### ISSUE THREAD

**Issue by muou55555** [secretflow/secretflow#272]
我想用源码安装secureflow，在执行python setup.py bdist_wheel时，出现以下错误：
![image](https://user-images.githubusercontent.com/5515510/212881970-ad87552c-e854-4241-8f41-ca190d1f3a12.png)
我的机器环境 centos 7.9, 已安装bazel 5.11、devtoolset-11、cmake 4.2.1

**Comment by rivertalk** [comment]
可以尝试一下，先
```bash
bazel clean --expunge
```

再bazel build试试看

**Comment by muou55555** [comment]
> 

试过，包括rm build及.cashe下面的内容都是一样的报错

**Comment by anakinxc** [comment]
Hi @muou55555 

看起来你的用户名里有一个反斜杠。。有没有可能创建一个不包含反斜杠的账户？然后 build

**Comment by anakinxc** [comment]
@muou55555 推荐按照 [posix 标准](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437)来设定用户名

**Comment by muou55555** [comment]
> 

非常感谢，果然是用户名的规范问题，已解决！
