### ISSUE TITLE
隐语的上层原子化产品能力（如可视化操作等）计划什么时候开源开放？

### ISSUE THREAD

**Issue by luckymlog** [secretflow/secretflow#274]
### Issue Type

Others

### Source

source

### Secretflow Version

0.7.18

### OS Platform and Distribution

linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
上层原子化产品能力（如可视化操作等）什么时候开源开放？
```

### Reproduction code to reproduce the issue.

```shell
上层原子化产品能力（如可视化操作等）什么时候开源开放？
```

**Comment by Chrisdehe** [comment]
您好，luckymlog！
我们是有整体的开源计划的：
您可以关注我们的VX公众号：隐语的小剧场（当中的内容会比较详细，我想可以能够帮助到您！）
以及：
B站up主：隐语SecretFlow
隐语小助手wx号：secretflow01 （需要加群可以找小助手）
隐语邮箱：[secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com)
祝您新年快乐！

**Comment by miluoalbert** [comment]
Hi，@luckmlog
目前隐语的交互平台层SecretPad已开源，可关注：https://github.com/secretflow/secretpad
