### ISSUE TITLE
使用SPU进行运算时如何打印中间变量

### ISSUE THREAD

**Issue by nantsing** [secretflow/secretflow#276]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 0.7.18b0

### OS Platform and Distribution

Linux centos 3.10.0

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
我在使用SPU进行计算时发现使用CPU和SPU计算得到的结果有较大的出入，请问：
1. 在使用SPU计算时有没有什么办法可以打印中间变量的值方便debug
2. 使用SPU计算时哪些计算可能会出问题？应该避免使用那些算子？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by anakinxc** [comment]
Hi @nantsing 

1. 在使用SPU计算时有没有什么办法可以打印中间变量的值方便debug
   SPU 暂时没有非常方便的方式打印中间值，这里有一些安全上的考虑。
   不过提供一个思路就是把关心的中间变量作为返回值传回来，然后显示的 reveal 出来

2. 使用SPU计算时哪些计算可能会出问题？应该避免使用那些算子？
   SPU 在计算精度上的[问题](https://www.secretflow.org.cn/docs/spu/en/reference/fxp.html)文档在这里。
   总体来说分两类，一种是定点数本身的值域，比如nonfinite numbers(inf/nan)或者非常小的值(1e-10)，前者无解，后者可以尝试一下用 FM128 来看看结果是不是正确的。还有一种是拟合精度的问题，上面的文档里对不少的拟合算子精度范围都有过总结，这类问题通常可以计算顺序的调整来规避

如果可以的话麻烦提供一个可以复现这个问题的代码，我们也可以来看看是不是一个 bug

谢谢

**Comment by nantsing** [comment]
感谢回答！
我后来发现应该是我是用的 jnp.nanmean() 出了问题，我手动求平均值之后问题就解决了！

**Comment by anakinxc** [comment]
> 感谢回答！
> 我后来发现应该是我是用的 jnp.nanmean() 出了问题，我手动求平均值之后问题就解决了！

mean 其实也会有问题🤣

mean 的计算 sum(x)/len(x) 会被优化成 sum(x)*constant(1/len(x))，在 len(x) 特别大的情况下 1/len(x) 会小于 fxp 的 epsilon，导致计算直接飞

anyway，这个问题我们记录了，争取在后续版本改进

顺便问一下，用 nanmean 是因为输入数据里有 nan 吗？

**Comment by nantsing** [comment]
> > 感谢回答！
> > 我后来发现应该是我是用的 jnp.nanmean() 出了问题，我手动求平均值之后问题就解决了！
> 
> mean 其实也会有问题🤣
> 
> mean 的计算 sum(x)/len(x) 会被优化成 sum(x)*constant(1/len(x))，在 len(x) 特别大的情况下 1/len(x) 会小于 fxp 的 epsilon，导致计算直接飞
> 
> anyway，这个问题我们记录了，争取在后续版本改进
> 
> 顺便问一下，用 nanmean 是因为输入数据里有 nan 吗？

不是，是我用 jnp.where() 的时候引入的 🤡
