### ISSUE TITLE
from secretflow.ml.nn import SLModelTF引入失败

### ISSUE THREAD

**Issue by Wyyyb** [secretflow/secretflow#28]
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/20929360/178254330-ed3096c5-ce1c-4d2e-a56c-a50cd176bc07.png">

如图，from secretflow.ml.nn import SLModelTF报错

**Comment by wuxibin89** [comment]
hi，请问一下你是什么操作系统？如果是linux的话，麻烦通过pip升级到secretflow==0.6.13b1

**Comment by Wyyyb** [comment]
是使用的registry.hub.docker.com/secretflow/spu-gcc11-anolis-dev:latest镜像

**Comment by Wyyyb** [comment]
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/20929360/178255732-ba4fc021-0758-4d70-8518-4de5c0d4cc6f.png">
如果直接在centos7上pip安装也会报错

**Comment by wuxibin89** [comment]
这个问题已经在https://github.com/secretflow/secretflow/pull/18 修复了哈。我们已经降低了GLIBC版本依赖，你现在可以直接在宿主机安装了。我刚才尝试在centos7安装了一次是可以的，麻烦检查一下你的python是不是3.8哈。

**Comment by Wyyyb** [comment]
升级之后可以了，感谢耐心解答
