### ISSUE TITLE
how to integrate an existing tee-based PPC system into secretflow?

### ISSUE THREAD

**Issue by qsmen** [secretflow/secretflow#287]
### Discussed in https://github.com/secretflow/secretflow/discussions/285

<div type='discussions-op-text'>

<sup>Originally posted by **qsmen** January 31, 2023</sup>
in secretflow,  spu supports many kinds of backend, like MPC, HE and TEE.  As for MPC and HE, as they are software implementation, we can use them directly.  But for TEE, as it is a hardware implementation, I want to know the requirement on TEE when integrating an existing TEE-based PPC system into secretflow?</div>

**Comment by icavan** [comment]
> ### Discussed in #285
> Originally posted by **qsmen** January 31, 2023 in secretflow, spu supports many kinds of backend, like MPC, HE and TEE. As for MPC and HE, as they are software implementation, we can use them directly. But for TEE, as it is a hardware implementation, I want to know the requirement on TEE when integrating an existing TEE-based PPC system into secretflow?

Could you describe more on "integrating an existing TEE-based PPC system"? Which TEE are you targeting? What's the expected usage after the integration?

MPC and HE run on standard servers. TEE does require special machines. In the TEE device(not open-sourced yet), SecretFlow tries to dispatch secret computation logic into TEE as the user requires. In this way, SecretFlow acts as a TEE user. SecretFlow simplifies the process of remote attestation and allows dynamic functions to be evaluated in TEE.

**Comment by qsmen** [comment]
An existing TEE-based PPC system is developed based on intel sgx or hygon csv,  and is an independent ppc system that can be used for privacy preserving computation. 
Integrating it means that I will take it as a device in secretflow. 
 The targeted TEE maybe Intel sgx or Hygon csv. After the integration, the usage is the same  as before.
 From your descripition, a user only provides a dynamic function and some data and  send them to TEE device.  Here I have one doubt.   It seems that all works with aim to protection security between users and TEE are done by secretflow,  how secretflow to ensure the security of all kinds of cryptographic keys?

> > ### Discussed in #285
> > Originally posted by **qsmen** January 31, 2023 in secretflow, spu supports many kinds of backend, like MPC, HE and TEE. As for MPC and HE, as they are software implementation, we can use them directly. But for TEE, as it is a hardware implementation, I want to know the requirement on TEE when integrating an existing TEE-based PPC system into secretflow?
> 
> Could you describe more on "integrating an existing TEE-based PPC system"? Which TEE are you targeting? What's the expected usage after the integration?
> 
> MPC and HE run on standard servers. TEE does require special machines. In the TEE device(not open-sourced yet), SecretFlow tries to dispatch secret computation logic into TEE as the user requires. In this way, SecretFlow acts as a TEE user. SecretFlow simplifies the process of remote attestation and allows dynamic functions to be evaluated in TEE.

An existing TEE-based PPC system is developed based on intel sgx or hygon csv,  and is an independent ppc system that can be used for privacy preserving computation. 
Integrating it means that I will take it as a device in secretflow. 
 The targeted TEE maybe Intel sgx or Hygon csv. After the integration, the usage is the same  as before.
 From your descripition, a user only provides a dynamic function and some data and  send them to TEE device.  Here I have one doubt.   It seems that all works with aim to protection security between users and TEE are done by secretflow,  how secretflow to ensure the security of all kinds of cryptographic keys?

**Comment by icavan** [comment]
> An existing TEE-based PPC system is developed based on intel sgx or hygon csv, and is an independent ppc system that can be used for privacy preserving computation. Integrating it means that I will take it as a device in secretflow. The targeted TEE maybe Intel sgx or Hygon csv. After the integration, the usage is the same as before. From your descripition, a user only provides a dynamic function and some data and send them to TEE device. Here I have one doubt. It seems that all works with aim to protection security between users and TEE are done by secretflow, how secretflow to ensure the security of all kinds of cryptographic keys?
> 
> > > ### Discussed in #285
> > > Originally posted by **qsmen** January 31, 2023 in secretflow, spu supports many kinds of backend, like MPC, HE and TEE. As for MPC and HE, as they are software implementation, we can use them directly. But for TEE, as it is a hardware implementation, I want to know the requirement on TEE when integrating an existing TEE-based PPC system into secretflow?
> > 
> > 
> > Could you describe more on "integrating an existing TEE-based PPC system"? Which TEE are you targeting? What's the expected usage after the integration?
> > MPC and HE run on standard servers. TEE does require special machines. In the TEE device(not open-sourced yet), SecretFlow tries to dispatch secret computation logic into TEE as the user requires. In this way, SecretFlow acts as a TEE user. SecretFlow simplifies the process of remote attestation and allows dynamic functions to be evaluated in TEE.

> It seems that all works with aim to protection security between users and TEE are done by secretflow

SecretFlow's TEE device only simplifies the process by providing some helpful APIs.

The user needs to guarantee at least two parts. First, the device user needs to decide which part of logic will be put into the secret world. Second, the device user needs to check whether this `dynamic` python function will lead to privacy concerns (via Remote Attestation + Dynamic Logic Limitation Controls). Say Bob requires the TEE to execute `select * from alice_table`. Although the computation procedure has been protected by TEE, the execution result has revealed raw data of Alice.

SecretFlow cannot help the user to make these decisions. SecretFlow will provide some APIs to help you make the above checks. 

Back to how to integrate, things might get more clear after we've released the TEE device features. If you're urgent, let's have an offline discussion.

**Comment by qsmen** [comment]
Thanks for your explaining. I look forward to the tee release.

**Comment by qsmen** [comment]
> > An existing TEE-based PPC system is developed based on intel sgx or hygon csv, and is an independent ppc system that can be used for privacy preserving computation. Integrating it means that I will take it as a device in secretflow. The targeted TEE maybe Intel sgx or Hygon csv. After the integration, the usage is the same as before. From your descripition, a user only provides a dynamic function and some data and send them to TEE device. Here I have one doubt. It seems that all works with aim to protection security between users and TEE are done by secretflow, how secretflow to ensure the security of all kinds of cryptographic keys?
> > > > ### Discussed in #285
> > > > Originally posted by **qsmen** January 31, 2023 in secretflow, spu supports many kinds of backend, like MPC, HE and TEE. As for MPC and HE, as they are software implementation, we can use them directly. But for TEE, as it is a hardware implementation, I want to know the requirement on TEE when integrating an existing TEE-based PPC system into secretflow?
> > > 
> > > 
> > > Could you describe more on "integrating an existing TEE-based PPC system"? Which TEE are you targeting? What's the expected usage after the integration?
> > > MPC and HE run on standard servers. TEE does require special machines. In the TEE device(not open-sourced yet), SecretFlow tries to dispatch secret computation logic into TEE as the user requires. In this way, SecretFlow acts as a TEE user. SecretFlow simplifies the process of remote attestation and allows dynamic functions to be evaluated in TEE.
> 
> > It seems that all works with aim to protection security between users and TEE are done by secretflow
> 
> SecretFlow's TEE device only simplifies the process by providing some helpful APIs.
> 
> The user needs to guarantee at least two parts. First, the device user needs to decide which part of logic will be put into the secret world. Second, the device user needs to check whether this `dynamic` python function will lead to privacy concerns (via Remote Attestation + Dynamic Logic Limitation Controls). Say Bob requires the TEE to execute `select * from alice_table`. Although the computation procedure has been protected by TEE, the execution result has revealed raw data of Alice.
> 
> SecretFlow cannot help the user to make these decisions. SecretFlow will provide some APIs to help you make the above checks.
> 
> Back to how to integrate, things might get more clear after we've released the TEE device features. If you're urgent, let's have an offline discussion.

Thanks for your explaining. I look forward to the tee release.
