### ISSUE TITLE
changelog说明有误

### ISSUE THREAD

**Issue by aisnnu** [secretflow/secretflow#288]
### Issue Type

Documentation Bug

### Source

binary

### Secretflow Version

0.6.5

### OS Platform and Distribution

os

### Python version

3.8

### What happend and What you expected to happen.

```shell
Q:secureboost算法在0.6.5里已经集成了吗
A:change log 大概率写的不准确。 有可能指的是ss-xgb或者homoboost，不是secureboost。
```

### Reproduction code to reproduce the issue.

```shell
change log 大概率写的不准确。 有可能指的是ss-xgb或者homoboost，不是secureboost。
```

**Comment by da-niao-dan** [comment]
Hi,
We will fix the changelog in the next release.
The line "secureboost optimization" will be corrected to "SFXgboost optimization." 
It was SFXgboost, a.k.a homo boost, that actually got optimized.
Thank you for spotting this typo.
