### ISSUE TITLE
通过源代码构建安装包实现tensorflow的GPU兼容，安装时numpy不兼容

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#289]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.7.18b0

### OS Platform and Distribution

WSL-Ubuntu22.04LTS

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
目前[tensorflow官方](https://tensorflow.google.cn/install/source?hl=zh-cn)经过测试的结果表明：cuda所支持的tensforflow GPU加速最新版本为tensorflow-2.6.0，目前Secretflow默认依赖的tensorflow版本为2.10.0，因此我希望通过自行修改tensorflow的依赖版本，安装tensorflow-2.6.0，来测试GPU对secretflow的加速实验。然而我遇到了以下报错：


The conflict is caused by:
    secretflow 0.7.18b0 depends on numpy>=1.22.0
    scikit-learn 1.1.3 depends on numpy>=1.17.3
    sf-heu 0.3.2b1 depends on numpy>=1.22.0
    spu 0.3.1b9 depends on numpy>=1.22.0
    jax 0.4.1 depends on numpy>=1.20
    jaxlib 0.4.1 depends on numpy>=1.20
    statsmodels 0.13.2 depends on numpy>=1.17
    tensorflow 2.6.0 depends on numpy~=1.19.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

我已经尝试直接安装了numpy-1.22.0或者numpy-1.23.0都不能解决问题，所以想请教一下如何才能解决依赖冲突，或者能否给我提供一个支持tensorflow-2.6.0的Secretflow的whl安装包。
```

### Reproduction code to reproduce the issue.

```shell
修改requirement.txt文件，使之依赖的tensorflow-2.10.0为tensorflow-2.6.0，并且借助Secretflow提供的[开发镜像](https://hub.docker.com/r/secretflow/secretflow-gcc11-anolis-dev/tags)成功完成构建，生成*.whl文件后，使用pip install secretflow-*.whl进行安装。
```

**Comment by 6fj** [comment]
hi @Mingbo-Lee 

看上去tf 2.6.0只能使用1.19.*的numpy，因此你可以：
1. 升高tf的版本
2. 直接使用早期的secertflow
3. 如果你想要自行编译secertflow，你可以选择早期的heu，spu，或者自行编译这两个库以降低jax，jaxlib的版本。

感谢。

**Comment by Mingbo-Lee** [comment]
hi @6fj 
非常感谢你的回复和指导；
1. tf的版本不能再升高了，tf2.6是经过测试可以实现加速的最新版本；
2. 我试试早期的secretflow版本；
3. 这一条目前看起来难度较大，我先试试方案2。

**Comment by zhouaihui** [comment]
hi @Mingbo-Lee, TF2.6如果跑在numpy1.22上，是否可能也是可行的？
一种tricky的安装方式是 
1. 先安装secretflow
2. 安装tf2.6，这个时候pip应该会自动帮你把numpy改成1.19版本
3. 再手动安装1.22 numpy

**Comment by anakinxc** [comment]
Hi @Mingbo-Lee 

补充一下 @zhouaihui 的，简单试了一下，需要以下几步

`pip install secretflow`
`pip install tensorflow==2.6.0`
`pip install numpy==1.22.0`
`pip install typing_extensions -U`

然后 import tensorflow 和 import secretflow 可以正常工作，不过可能需要多测试测试

**Comment by Mingbo-Lee** [comment]
hi! @zhouaihui @anakinxc 目前我已经通过别的方案实现隐语环境下的GPU兼容过程，目前正在进行相关测试实验，实验结果目前初步具备说服力，等待实验成功，我将提交PR。
