### ISSUE TITLE
static_argnames要传什么参数

### ISSUE THREAD

**Issue by Wyyyb** [secretflow/secretflow#29]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/20929360/178396944-d63d2b64-8eb8-4eb1-8538-4109b1304b69.png">
看到tutorial中逻辑回归的示例中，在device()()中第一个括号里除了传要执行计算的函数以外还要传一个static_argnames参数，请问什么时候需要传这个参数呢？我试过传[“epochs”, "learning_rate"]也是可以的，但是如果不传static_argnames或者传一个空数组就不可以，请问这个参数有相关的解释吗？

**Comment by wuxibin89** [comment]
这里的`static_argnames`与[jax.jit](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html#jax.jit)相同。通常需要将control flow(if/for/while)所依赖的常量声明为static_argnames。在上面的例子中，for-loop依赖epochs，因此要将其声明为static_argnames，而learning_rate则不用。

**Comment by Wyyyb** [comment]
明白了，感谢解答！

**Comment by anakinxc** [comment]
同时可以看一下 https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-autodiff 这里的对于为什么要 static args 有比较详细的解释
