### ISSUE TITLE
多容器部署环境下，psi实现报错

### ISSUE THREAD

**Issue by zhouhansheng** [secretflow/secretflow#293]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow0.7.18b0

### OS Platform and Distribution

容器中执行

### Python version

3.8.0

### What happend and What you expected to happen.

```shell
容器1ray配置：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --head --node-ip-address="10.56.132.65" --port="9326" --resources='{"alice": 32}' --include-dashboard=False --disable-usage-stats --num-cpus=16
容器2ray配置：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --address="10.56.132.65:9326" --resources='{"bob": 32}' --disable-usage-stats --num-cpus=16

两方求交数据：
alice.csv
id
3
0

bob.csv:
id
4
0

psi代码如下：
import spu
import secretflow as sf

sf.init(parties=['alice', 'bob'],address="10.56.132.65:9326") 

alice, bob = sf.PYU('alice'), sf.PYU('bob')

# 因为在同一服务器下面，以host模式启动，所以此处端口不要冲突
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Use the address and port of alice instead.
            # Please choose a unused port.
            'address': '10.56.132.65:9327',
        },
        {
            'party': 'bob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose a unused port.
            'address': '10.56.132.65:9328',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
input_path = {alice:'./alice.csv',bob:'./bob.csv'}
output_path = {alice: './alice_psi.csv', bob: './bob_psi.csv'}
spu.psi_csv('id', input_path, output_path, 'alice')

报错如下：
(secretflow) bash-4.4# python3 psi.py
2023-02-02 09:52:55,001 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.56.132.65:9326...
2023-02-02 09:52:55,017 INFO worker.py:1538 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "psi.py", line 36, in <module>
    spu.psi_csv('id', input_path, output_path, 'alice')
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1225, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 263, in psi_csv
    return sfd.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get
    return ray.get(object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=3389, ip=10.56.132.65, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fa0d77b0a60>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 577, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 48, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
        [Enforce fail at spu/psi/utils/csv_checker.cc:92] token.size(). empty token in row=2 field=id
stacktrace: 
#0 std::_Function_handler<>::_M_invoke()+0x7fa0e7adf409
#1 std::__future_base::_State_baseV2::_M_do_set()+0x7fa0e6d7607f
#2 __pthread_once_slow+0x7fa266059dd7
(SPURuntime pid=50375) 2023-02-02 09:53:01.807 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=50375) 2023-02-02 09:53:01.807 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: ./alice.csv, precheck_switch:true
(SPURuntime pid=50375) 2023-02-02 09:53:01.809 [info] [csv_checker.cc:CsvChecker:125] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=. --stable selected-keys.1675331581807899421 | LC_ALL=C uniq -d > duplicate-keys.1675331581807899421
(SPURuntime pid=50375) 2023-02-02 09:53:01.840 [info] [bucket_psi.cc:Run:121] End sanity check for input file: ./alice.csv, size=2
(SPURuntime pid=3389) 2023-02-02 09:53:01.807 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=3389) 2023-02-02 09:53:01.807 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: ./bob.csv, precheck_switch:true
```

### Reproduction code to reproduce the issue.

```shell
alice方跑的psi代码

import spu
import secretflow as sf

sf.init(parties=['alice', 'bob'],address="10.56.132.65:9326") 

alice, bob = sf.PYU('alice'), sf.PYU('bob')

# 因为在同一服务器下面，以host模式启动，所以此处端口不要冲突
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Use the address and port of alice instead.
            # Please choose a unused port.
            'address': '10.56.132.65:9327',
        },
        {
            'party': 'bob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose a unused port.
            'address': '10.56.132.65:9328',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
input_path = {alice:'./alice.csv',bob:'./bob.csv'}
output_path = {alice: './alice_psi.csv', bob: './bob_psi.csv'}
spu.psi_csv('id', input_path, output_path, 'alice')
```

**Comment by zhouhansheng** [comment]
也会出现如下报错：
(secretflow) bash-4.4# python3 psi.py
2023-02-02 10:10:17,773 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.56.132.65:9326...
2023-02-02 10:10:17,787 INFO worker.py:1538 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "psi.py", line 36, in <module>
    spu.psi_csv('id', input_path, output_path, 'alice', protocol="KKRT_PSI_2PC")
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1225, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 263, in psi_csv
    return sfd.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get
    return ray.get(object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=3572, ip=10.56.132.65, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f275ee33ac0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 577, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 48, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
        [external/yacl/yacl/io/stream/file_io.cc:46] Open for read error on file './alice.csv', failure 'basic_ios::clear: iostream error', error msg 'No such file or directory', error code 2
stacktrace: 
#0 spu::psi::io::BuildInputStream()+0x7f277001b801
#1 spu::psi::CsvChecker::CsvChecker()+0x7f276fef956d
#2 std::_Function_handler<>::_M_invoke()+0x7f276fee2409
#3 std::__future_base::_State_baseV2::_M_do_set()+0x7f276f17907f
#4 __pthread_once_slow+0x7f28ed6e8dd7
(SPURuntime pid=3573) 2023-02-02 10:10:24.455 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=3573) 2023-02-02 10:10:24.455 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: ./bob.csv, precheck_switch:true
(SPURuntime pid=3572) 2023-02-02 10:10:24.455 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=3572) 2023-02-02 10:10:24.455 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: ./alice.csv, precheck_switch:true

**Comment by Krout0n** [comment]
Hi @zhouhansheng! I'm not a committer, but I had the same experience, so I'll answer on your behalf until a committer comes along. The way the cluster mode works has changed since version 0.7.18b0.  I suggest you take a look at the links below and learn a new way.
- https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html
- https://github.com/secretflow/rayfed

**Comment by Krout0n** [comment]
What you should change is
- Start ray head node for Bob
- Launch as **the new cluster mode**. If you give the `parties` argument for `sf.init`, it starts as standalone mode.
You can see its behavior here
https://github.com/secretflow/secretflow/blob/cbc2dc90f211205d3ebb77539c93e11d03681928/secretflow/device/driver.py#L294

**Comment by zhanglei486** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/47308800/216304594-ca671051-9890-4c85-9e19-b4cb060d386e.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/47308800/216304500-1b315f55-c5c2-4f6f-9809-06afd6f3bf2b.png">
看上面的错误信息，从PSI的角度看有两个问题：
第一个报错，csv_check 检查数据时报错，数据有问题，建议检查一下数据
第二个报错，异常信息是读不到./alice.csv，建议使用绝对路径

**Comment by zhouhansheng** [comment]
> What you should change is
> 
> * Start ray head node for Bob
> * Launch as **the new cluster mode**. If you give the `parties` argument for `sf.init`, it starts as standalone mode.
>   You can confirm its behavior here
>   https://github.com/secretflow/secretflow/blob/cbc2dc90f211205d3ebb77539c93e11d03681928/secretflow/device/driver.py#L294

ray部署方式变了吗
我是按照以前方式配置的：
alice容器配置：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --head --node-ip-address="10.56.132.65" --port="9326" --resources='{"alice": 32}' --include-dashboard=False --disable-usage-stats --num-cpus=16

bob容器配置：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --address="10.56.132.65:9326" --resources='{"bob": 32}' --disable-usage-stats --num-cpus=16

**Comment by zhouhansheng** [comment]
> <img alt="image" width="798" src="https://user-images.githubusercontent.com/47308800/216304500-1b315f55-c5c2-4f6f-9809-06afd6f3bf2b.png">
> 
> <img alt="image" width="753" src="https://user-images.githubusercontent.com/47308800/216304594-ca671051-9890-4c85-9e19-b4cb060d386e.png">
> 
> 看上面的错误信息，从PSI的角度看有两个问题：
> 
> 第一个报错，csv_check 检查数据时报错，数据有问题，建议检查一下数据
> 
> 第二个报错，异常信息是读不到./alice.csv，建议使用绝对路径

用在测试集群上跑通的数据来做的，用绝对路径试过，还是报错，请问你有在最新版本下用多容器测试过psi吗（我之前在0.7.7b1版本时，是跑通的）

**Comment by zhouhansheng** [comment]
> > > <img alt="image" width="798" src="https://user-images.githubusercontent.com/47308800/216304500-1b315f55-c5c2-4f6f-9809-06afd6f3bf2b.png">
> > > <img alt="image" width="753" src="https://user-images.githubusercontent.com/47308800/216304594-ca671051-9890-4c85-9e19-b4cb060d386e.png">
> > > 看上面的错误信息，从PSI的角度看有两个问题：
> > > 第一个报错，csv_check 检查数据时报错，数据有问题，建议检查一下数据
> > > 第二个报错，异常信息是读不到./alice.csv，建议使用绝对路径
> > 
> > 
> > 用在测试集群上跑通的数据来做的，用绝对路径试过，还是报错，请问你有在最新版本下用多容器测试过psi吗（我之前在0.7.7b1版本时，是跑通的）
> 
> 目前看到的报错信息还是psi协议执行前的csv数据读取报的异常信息
> 
> 多容器测试的环境问题建议找其他同学看一下

我又试了一些例子，第一个错误确实可能是数据弄错了，现在还是报第二个错误，只有两容器中同时存在两方数据，才能正常跑（这明显不满足场景要求）

**Comment by zhouaihui** [comment]
![Uploading image.png…]()
Bob's ip should not be same with alice since bob is on another machine, can you correct it?

**Comment by zhouhansheng** [comment]
> ![image](https://user-images.githubusercontent.com/34807769/216502952-f3f9a26b-7311-4706-bb57-9d867feceb78.png) Bob's ip should not be same with alice since bob is on another machine, can you correct it?

单机多容器部署的，ip不都是本地ip吗

**Comment by zhouaihui** [comment]
Ok, it's fine to use same ip when docker network is host. Can you show the latest detailed error message?

**Comment by zhouhansheng** [comment]
> Ok, it's fine to use same ip when docker network is host. Can you show the latest detailed error message?

目前的报错：

(secretflow) bash-4.4# python3 psi.py
2023-02-03 02:39:34,738 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.56.132.65:9326...
2023-02-03 02:39:34,750 INFO worker.py:1538 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "psi.py", line 36, in <module>
    spu.psi_csv('ID', input_path, output_path, 'alice')
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1225, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 263, in psi_csv
    return sfd.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get
    return ray.get(object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=4948, ip=10.56.132.65, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f4d1ce45ac0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 577, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 48, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
        [external/yacl/yacl/io/stream/file_io.cc:46] Open for read error on file '/root/data/alice.csv', failure 'basic_ios::clear: iostream error', error msg 'No such file or directory', error code 2
stacktrace: 
#0 spu::psi::io::BuildInputStream()+0x7f4d2e028801
#1 spu::psi::CsvChecker::CsvChecker()+0x7f4d2df0656d
#2 std::_Function_handler<>::_M_invoke()+0x7f4d2deef409
#3 std::__future_base::_State_baseV2::_M_do_set()+0x7f4d2d18607f
#4 __pthread_once_slow+0x7f4eab6ebdd7
(SPURuntime pid=4948) 2023-02-03 02:39:41.525 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=4948) 2023-02-03 02:39:41.525 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: /root/data/alice.csv, precheck_switch:true
(SPURuntime pid=4949) 2023-02-03 02:39:41.525 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=4949) 2023-02-03 02:39:41.525 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: /root/data/bob.csv, precheck_switch:true
(SPURuntime pid=4949) 2023-02-03 02:39:41.528 [info] [csv_checker.cc:CsvChecker:125] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=/root --stable selected-keys.1675391981526160427 | LC_ALL=C uniq -d > duplicate-keys.1675391981526160427
(SPURuntime pid=4949) 2023-02-03 02:39:41.553 [info] [bucket_psi.cc:Run:121] End sanity check for input file: /root/data/bob.csv, size=2

**Comment by zhouaihui** [comment]
Can you paste the result of the following python?
``` python
>>> import ray
>>> ray.init(address='10.56.132.65:9326')
>>> ray.nodes()
```

**Comment by zhouhansheng** [comment]
> ```python
> ray.init(address='10.56.132.65:9326')
> ```

>>> import ray 
>>> ray.init(address='10.56.132.65:9326')
2023-02-03 09:21:22,912 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.56.132.65:9326...
2023-02-03 09:21:22,965 INFO worker.py:1538 -- Connected to Ray cluster.
RayContext(dashboard_url='', python_version='3.8.13', ray_version='2.2.0', ray_commit='d10509847a5256fa5d191f3f6db5c60026b5d6b8', address_info={'node_ip_address': '10.56.132.65', 'raylet_ip_address': '10.56.132.65', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536', 'metrics_export_port': 54221, 'gcs_address': '10.56.132.65:9326', 'address': '10.56.132.65:9326', 'dashboard_agent_listen_port': 52365, 'node_id': 'd661065ace302fc689d9f452e5bb137d4b8dc14824e795eee300a3a1'})
>>> ray.nodes()
[{'NodeID': 'd661065ace302fc689d9f452e5bb137d4b8dc14824e795eee300a3a1', 'Alive': True, 'NodeManagerAddress': '10.56.132.65', 'NodeManagerHostname': 'LIN-3E326DAF712.zte.intra', 'NodeManagerPort': 41397, 'ObjectManagerPort': 44243, 'ObjectStoreSocketName': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536/sockets/raylet', 'MetricsExportPort': 54221, 'NodeName': '10.56.132.65', 'alive': True, 'Resources': {'memory': 7240276379.0, 'object_store_memory': 3620138188.0, 'CPU': 16.0, 'alice': 32.0, 'node:10.56.132.65': 1.0}}, {'NodeID': '8f80d1ec94a36191c8e7bd016536b8a8a4b076063844590286effc84', 'Alive': True, 'NodeManagerAddress': '10.56.132.65', 'NodeManagerHostname': 'LIN-3E326DAF712.zte.intra', 'NodeManagerPort': 34337, 'ObjectManagerPort': 34655, 'ObjectStoreSocketName': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2023-02-02_09-46-52_017337_44536/sockets/raylet', 'MetricsExportPort': 54843, 'NodeName': '10.56.132.65', 'alive': True, 'Resources': {'memory': 8753974477.0, 'object_store_memory': 3751703347.0, 'CPU': 16.0, 'node:10.56.132.65': 1.0, 'bob': 32.0}}]

**Comment by onelyfly** [comment]
我也遇到过一样，单机多容器部署，一直联通不了。我用的是桥接模式。[@238](https://github.com/secretflow/secretflow/issues/238)

**Comment by zhouaihui** [comment]
hi, @zhouhansheng , can you paste the command to start your docker container? And make sure that alice.csv is in alice's container and bob.csv is in bob's container. We can not reproduce your problem and it works as expecpted.

**Comment by zhouhansheng** [comment]
> hi, @zhouhansheng , can you paste the command to start your docker container? And make sure that alice.csv is in alice's container and bob.csv is in bob's container. We can not reproduce your problem and it works as expected.

你们可以实现单机多容器psi过程吗，那麻烦看一下是否是我实施流程弄错了。
下面再复述一下我的实现过程：
1、启动两容器
容器1：
`docker run  --net=host -itd secretflow/secretflow-anolis8:0.7.18b0`
容器2：
`docker run  --net=host -itd secretflow/secretflow-anolis8:0.7.18b0`

2、容器内配置ray参数（本地ip为：10.56.132.65）
容器1内：
```
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --head --node-ip-address="10.56.132.65" --port="9326" --resources='{"alice": 32}' --include-dashboard=False --disable-usage-stats --num-cpus=16
```
容器2内：
```
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --address="10.56.132.65:9326" --resources='{"bob": 32}' --disable-usage-stats --num-cpus=16
```
查看节点状态：
`ray status`
显示：
```
(secretflow) bash-4.4# ray status
======== Autoscaler status: 2023-02-07 03:07:16.089809 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_bff0ac6b656ae167b0e97d8811a2d39cd8097966885a04bffde2d669
 1 node_ace6792fb96f29921eb3e163eadd2129c83aef9e9fd3260c33d1480b
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/32.0 CPU
 0.00/15.066 GiB memory
 0.00/6.950 GiB object_store_memory
 0.0/32.0 bob
 0.00/15.066 GiB memory
 0.00/6.950 GiB object_store_memory

```

3、本地数据
alice:
![image](https://user-images.githubusercontent.com/52910765/217145037-26c53e24-b468-4edf-9c3d-67fe554f4a2c.png)
bob:
![image](https://user-images.githubusercontent.com/52910765/217145077-00b4a6e6-1964-4803-882e-783675aacabd.png)

4、alice端执行如下脚本
```
import spu
import secretflow as sf

sf.init(parties=['alice', 'bob'],address="10.56.132.65:9326") 
alice, bob = sf.PYU('alice'), sf.PYU('bob')

# 因为在同一服务器下面，以host模式启动，所以此处端口不要冲突
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Use the address and port of alice instead.
            # Please choose a unused port.
            'address': '10.56.132.65:9327',
        },
        {
            'party': 'bob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose a unused port.
            'address': '10.56.132.65:9328',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
input_path = {alice:'/root/alice.csv',bob:'/root/bob.csv'}
output_path = {alice: '/root/alice_psi.csv', bob: '/root/bob_psi.csv'}
spu.psi_csv('ID', input_path, output_path, 'alice')
```

报错：
```
secretflow) bash-4.4# python3 psi.csv
2023-02-07 03:15:23,363 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.56.132.65:9326...
2023-02-07 03:15:23,378 INFO worker.py:1538 -- Connected to Ray cluster.
(SPURuntime pid=425) 2023-02-07 03:15:27.197 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=425) 2023-02-07 03:15:27.197 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: /root/bob.csv, precheck_switch:true
(SPURuntime pid=423) 2023-02-07 03:15:27.197 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=423) 2023-02-07 03:15:27.198 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: /root/alice.csv, precheck_switch:true
Traceback (most recent call last):
  File "psi.csv", line 36, in <module>                                                                                            
    spu.psi_csv('ID', input_path, output_path, 'alice')
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1225, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 263, in psi_csv
    return sfd.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get
    return ray.get(object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=423, ip=10.56.132.65, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fc4b1da0a00>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 577, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 48, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
        [Enforce fail at spu/psi/utils/csv_checker.cc:92] token.size(). empty token in row=2 field=ID
stacktrace: 
#0 std::_Function_handler<>::_M_invoke()+0x7fc4c2e40409
#1 std::__future_base::_State_baseV2::_M_do_set()+0x7fc4c20d707f
#2 __pthread_once_slow+0x7fc63db54dd7
```

如果将output_path路径改成相对路径：
`output_path = {alice: './alice_psi.csv', bob: './bob_psi.csv'}`
报如下错：
```
(secretflow) bash-4.4# python3 psi.csv                                                                                                 
2023-02-07 03:18:12,226 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.56.132.65:9326...                
2023-02-07 03:18:12,241 INFO worker.py:1538 -- Connected to Ray cluster.                                                            
(SPURuntime pid=208) 2023-02-07 03:18:16.032 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576                             
(SPURuntime pid=208) 2023-02-07 03:18:16.032 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: /root/alice.csv, precheck_switch:true                                                                                                                         
Traceback (most recent call last):                                                                                                   
  File "psi.csv", line 36, in <module>                                                                                                
    spu.psi_csv('ID', input_path, output_path, 'alice')                                                                               
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1225, in psi_csv          
    return dispatch(                                                                                                                    
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch      
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)                                                         
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch     
    return self._ops[device_type][name](*args, **kwargs)                                                                             
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 263, in psi_csv        
    return sfd.get(res)                                                                                                            
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get         
    return ray.get(object_refs)                                                                                                    
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper       
    return func(*args, **kwargs)                                                                                                    
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get                      
    raise value.as_instanceof_cause()                                                                                                   
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=208, ip=10.56.132.65, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fcd008fcbb0>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 577, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/psi.py", line 48, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
        [external/yacl/yacl/io/stream/file_io.cc:46] Open for read error on file '/root/alice.csv', failure 'basic_ios::clear: iostream error', error msg 'No such file or directory', error code 2
stacktrace: 
#0 spu::psi::io::BuildInputStream()+0x7fcd11ae7801
#1 spu::psi::CsvChecker::CsvChecker()+0x7fcd119c556d
#2 std::_Function_handler<>::_M_invoke()+0x7fcd119ae409
#3 std::__future_base::_State_baseV2::_M_do_set()+0x7fcd10c4507f
#4 __pthread_once_slow+0x7fce8f5a2dd7
(SPURuntime pid=590) 2023-02-07 03:18:16.031 [info] [bucket_psi.cc:Init:211] bucket size set to 1048576
(SPURuntime pid=590) 2023-02-07 03:18:16.031 [info] [bucket_psi.cc:Run:103] Begin sanity check for input file: /root/bob.csv, precheck_switch:true
```

**Comment by zhouaihui** [comment]
1. Use absolute path please.
2. Could you remove the trailing blank line in csv and try again?

**Comment by zhouhansheng** [comment]
> 1. Use absolute path please.
> 2. Could you remove the trailing blank line in csv and try again?

可以运行了，感谢回复！
总结一下该issue的解决：
输入和输出文件都需要是绝对路径，且两方数据不能出现空行。
如果执行了一次程序，本地生成了alice_psi.csv会报找不到/root/alice.csv的错，需要删除之前生成的alice_psi.csv和bob_psi.csv文件。

**Comment by zhouhansheng** [comment]
@zhouaihui 除了尾行有空行报错的问题，还希望能够解决：第二次执行上述psi脚本，因为已经有alice_psi.csv会报错的问题，或者希望可以将报错信息调整一下。

**Comment by zhouaihui** [comment]
@zhouhansheng , could you create a new issue for the second problem?

**Comment by zhouhansheng** [comment]
> @zhouhansheng , could you create a new issue for the second problem?

ok
