### ISSUE TITLE
TEE开源

### ISSUE THREAD

**Issue by charlesZ125** [secretflow/secretflow#295]
您好，请问TEE部分现在开源了吗？谢谢。

**Comment by zhouaihui** [comment]
hi @charlesZ125 ，我们计划在近期开源TEE Device，敬请期待！

**Comment by charlesZ125** [comment]
> hi @charlesZ125 ，我们计划在近期开源TEE Device，敬请期待！

OK，了解，期待，谢谢。

**Comment by mingo0117** [comment]
> hi @charlesZ125 ，我们计划在近期开源TEE Device，敬请期待！

是基于HyperEnclave吗

**Comment by anakinxc** [comment]
Resolved in 0.8.2b0+
