### ISSUE TITLE
基于TEE的多方MPC计算解决方案

### ISSUE THREAD

**Issue by gklab** [secretflow/secretflow#31]
现阶段MPC协议算子在通信量和通信次数上可能会存在局限性，特别是在多方(n>3)，公网环境上性能损耗明显。想问下TEE-based multi-party computation 会是多方安全计算的一种更优的解决方案么，你们怎么看？

**Comment by icavan** [comment]
TEE 集群里跑 MPC 确实是一种新颖的方式，相比较纯 TEE 方案有一些有点，比如这种模式下，除了通信变同网的优点外，TEE进出的数据都是统计学上无差别的随机数，因此能够有效抵御一部分侧信道攻击。

隐语当然会支持这种新颖的模式，不过目前 TEE 结合 MPC 的方案还未开放，预计年底左右会开放 TEE + MPC 的 TECC 设备，敬请关注期待。

**Comment by zhouaihui** [comment]
此类问题更适合移步[Discussions](https://github.com/secretflow/secretflow/discussions)讨论。
