### ISSUE TITLE
Colab中通过pip安装隐语，报错No module named 'secretflow.ml.nn.sl.backend.tensorflow.strategy'

### ISSUE THREAD

**Issue by human20** [secretflow/secretflow#310]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.7.18b2

### OS Platform and Distribution

Linux  Ubuntu 18.05

### Python version

3.8.10

### What happend and What you expected to happen.

```shell
在colab中使用pip安装secretflow后，使用import secretflow as sf导入可以正常使用。在使用from secretflow.ml.nn import FLModel是报错，显示ModuleNotFoundError: No module named 'secretflow.ml.nn.sl.backend.tensorflow.strategy'。
```

### Reproduction code to reproduce the issue.

```shell
在colab中的jupyter中使用pip install secretflow进行安装。安装成功后，执行from secretflow.ml.nn import FLMode报错。
```

**Comment by anakinxc** [comment]
@human20 

您好，麻烦检查一下运行目录下面有没有叫 secretflow 的文件夹

**Comment by human20** [comment]
@anakinxc 
在cloab中好像开通pro才能看到运行目录
后续我在本地Linux上，通过pypi安装，最后因为安装包之间相互冲突安装失败。（py3.8，Ubuntu 18.04，pip>=19)
通过源码安装，执行“python setup.py bdist_wheel”报错“error: command 'bazel' failed: No such file or directory”

**Comment by anakinxc** [comment]
> 后续我在本地Linux上，通过pypi安装，最后因为安装包之间相互冲突安装失败。（py3.8，Ubuntu 18.04，pip>=19)

问一下是哪个包冲突了呀

**Comment by human20** [comment]
ERROR: Cannot install secretflow==0.6.13b0, secretflow==0.6.13b1, secretflow==0.7.11b0, secretflow==0.7.11b1, secretflow==0.7.11b2, secretflow==0.7.11b3, secretflow==0.7.18b0, secretflow==0.7.18b1, secretflow==0.7.18b2, secretflow==0.7.7b0 and secretflow==0.7.7b1 because these package versions have conflicting dependencies.

The conflict is caused by:
    secretflow 0.7.18b2 depends on secretflow-rayfed==0.1.0b1
    secretflow 0.7.18b1 depends on secretflow-rayfed==0.1.0b1
    secretflow 0.7.18b0 depends on secretflow-rayfed==0.1.0b1
    secretflow 0.7.11b3 depends on spu==0.3.0
    secretflow 0.7.11b2 depends on spu==0.3.0
    secretflow 0.7.11b1 depends on spu==0.3.0
    secretflow 0.7.11b0 depends on spu==0.3.0
    secretflow 0.7.7b1 depends on secretflow-ray==2.0.0.dev1
    secretflow 0.7.7b0 depends on secretflow-ray==2.0.0.dev1
    secretflow 0.6.13b1 depends on secretflow-ray==2.0.0.dev0
    secretflow 0.6.13b0 depends on spu==0.1.0b0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
安装命令：pip install secretflow未指定版本

**Comment by anakinxc** [comment]
试一下 `pip uninstall spu secretflow secretflow-ray secretflow-rayfed ray` 然后再重新安装呢

**Comment by human20** [comment]
卸载时，全部跳过因为没有安装。后续重新安装出现相同的情况。

**Comment by anakinxc** [comment]
@human20 可以试一下更新 pip 到最新的然后再安装吗

**Comment by human20** [comment]
@anakinxc 
pip已经更新到22.3.1，重新安装还是相同的结果。

**Comment by zhouaihui** [comment]
试一下指定版本号 `pip install secretflow=0.7.18b2`

**Comment by prehisle** [comment]
我碰到了同样的错误提示，使用docker镜像版本是`secretflow/secretflow-anolis8   0.7.18b2   3228321f467d   3 days ago   6.27GB
`
![image](https://user-images.githubusercontent.com/2081344/218368367-86646836-5ae8-42d9-ad2f-4d1657640524.png)

**Comment by miluoalbert** [comment]
@human20 @prehisle 
请更新到0.7.18b3版本，修复了这个问题
