### ISSUE TITLE
PIR部分开源

### ISSUE THREAD

**Issue by charlesZ125** [secretflow/secretflow#311]
请问PIR部分近期会开源吗，谢谢。

**Comment by zhanglei486** [comment]
PIR 的C++实现在SPU已经开源
PIR 在secretflow层的python支持，具体计划还在排期中

**Comment by charlesZ125** [comment]
> PIR 的C++实现在SPU已经开源 PIR 在secretflow层的python支持，具体计划还在排期中

好的，多谢。

**Comment by anakinxc** [comment]
Resolved in latest release
