### ISSUE TITLE
关于当前ray框架在隐语中的作用？

### ISSUE THREAD

**Issue by dreaminglwj** [secretflow/secretflow#313]
请教如下问题：
1.spu中会调用ray的remote函数，意图是否是用ray进行任务分发？
2.PSI使用ray的目的是需要ray做应用分发（将PSI应用从Alice分发到Bob，从而完成在Bob端的应用启动）？还是单纯借助ray在本地节点启动应用？
3.如https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/mpc_ml/linear_model.html链接中提到的进入密态，进入密态意味着什么？是否意味着调用了sh.SPU接下来的一切都是安全的？
4.如https://github.com/secretflow/spu/blob/main/examples/python/psi/simple_psi.py链接，例子中提供了两个IP地址，这段代码的执行，只需要在127.0.0.1:9307上启动一次，就可以通过ray根据配置再起一个副本到127.0.0.1:9308上执行吗？还是需要手动起两次？如果换成两台物理机呢？
5.secretFlow是否可以做到根据配置的两个不同的IP地址，如127.0.0.1:9308，127.0.0.2:9308，自动将PSI任务分发到两台机器上运行，完成一次PSI？

**Comment by zhouaihui** [comment]
1和2：
SecretFlow使用ray的remote语义进行计算任务分发。从SecretFlow调度层来看，PSI和其他计算任务并没有特殊之处，也是把计算任务调度给ray执行。

3.  数据进入SPU之后，在SPU上进行的计算是安全的。

4. spu的example麻烦在[spu repo](https://github.com/secretflow/spu)下提一个？spu本身不涉及到ray，SecretFlow集成并透出SPU才涉及到ray。

5. 可以的，这个属于集群仿真。参见https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#cluster-mode-for-simulation
