### ISSUE TITLE
一主机部署2容器集群，之间通信太不稳定了问题

### ISSUE THREAD

**Issue by onelyfly** [secretflow/secretflow#316]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.718

### OS Platform and Distribution

centos7

### Python version

Python 3.8 

### What happend and What you expected to happen.

```shell
>>> (SPURuntime pid=4566, ip=10.0.152.10) 2023-02-13 02:18:36.196 [error] [server.cpp:BRPC:969] Fail to listen 10.0.152.11:7002
(SPURuntime pid=4566, ip=10.0.152.10) 2023-02-13 02:18:36,230   ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=4566, ip=10.0.152.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f01676e0b80>)
(SPURuntime pid=4566, ip=10.0.152.10)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=4566, ip=10.0.152.10)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=4566, ip=10.0.152.10) RuntimeError: what: 
(SPURuntime pid=4566, ip=10.0.152.10)   [external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=4566, ip=10.0.152.10) stacktrace: 
(SPURuntime pid=4566, ip=10.0.152.10) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f0177c260c1
(SPURuntime pid=4566, ip=10.0.152.10) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0176a6f510
(SPURuntime pid=4566, ip=10.0.152.10) #2 pybind11::cpp_function::dispatcher()+0x7f0176a59c5b
(SPURuntime pid=4566, ip=10.0.152.10) #3 PyCFunction_Call+0x4dfd82

>>> 
>>> 
>>> (SPURuntime pid=4565, ip=10.0.152.10) 2023-02-13 02:18:46,069       ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=4565, ip=10.0.152.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f3cbb06dbb0>)
(SPURuntime pid=4565, ip=10.0.152.10)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=4565, ip=10.0.152.10)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=4565, ip=10.0.152.10) RuntimeError: what: 
(SPURuntime pid=4565, ip=10.0.152.10)   [external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=1
(SPURuntime pid=4565, ip=10.0.152.10) stacktrace: 
(SPURuntime pid=4565, ip=10.0.152.10) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f3ccaa6f519
(SPURuntime pid=4565, ip=10.0.152.10) #1 pybind11::cpp_function::dispatcher()+0x7f3ccaa59c5b
(SPURuntime pid=4565, ip=10.0.152.10) #2 PyCFunction_Call+0x4dfd82
```

### Reproduction code to reproduce the issue.

```shell
连上后，杀掉python进程
然后重新运行
import secretflow as sf
from secretflow.device.device.spu import spu

sf.shutdown()
sf.init(parties=['alice', 'bob'], address='10.0.152.10:7001')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.0.152.10:7002'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.0.152.11:7002'
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
spu = sf.SPU(cluster_def=cluster_def)

就连不上了。
按理同台主机，算是局域网之间的通信。
docker 版本是也不低
docker -v
Docker version 20.10.1, build 831ebea
```

**Comment by onelyfly** [comment]
端口也没被占用：
 ss -ntlp
State                 Recv-Q                Send-Q                               Local Address:Port                                Peer Address:Port               Process                                         
LISTEN                0                     128                                        0.0.0.0:64708                                    0.0.0.0:*                   users:(("python",pid=288,fd=12))               
LISTEN                0                     128                                        0.0.0.0:43019                                    0.0.0.0:*                   users:(("raylet",pid=210,fd=30))               
LISTEN                0                     128                                        0.0.0.0:44398                                    0.0.0.0:*                   users:(("raylet",pid=210,fd=24))               
LISTEN                0                     128                                        0.0.0.0:10001                                    0.0.0.0:*                   users:(("python",pid=96,fd=5))                 
LISTEN                0                     128                                        0.0.0.0:37364                                    0.0.0.0:*                   users:(("python",pid=121,fd=11))               
LISTEN                0                     128                                     127.0.0.11:43608                                    0.0.0.0:*                                                                  
LISTEN                0                     128                                        0.0.0.0:7001                                     0.0.0.0:*                   users:(("gcs_server",pid=44,fd=16))            
(secretflow) bash-4.4# 


python -m http.server 7002
curl 10.0.152.10:7002
也是通的

**Comment by anakinxc** [comment]
看起来和 #296 是一样的问题
@onelyfly 麻烦试一下 #296 里的解决方式，谢谢

**Comment by zhouaihui** [comment]
试试升级到0.7.18b2版本

**Comment by onelyfly** [comment]
> 看起来和 #296 是一样的问题 @onelyfly 麻烦试一下 #296 里的解决方式，谢谢

按这个方案去改代码了，还是一样问题：
`import secretflow as sf
from secretflow.device.device.spu import spu

sf.shutdown()
#sf.init(parties=['alice', 'bob'], address='10.0.152.10:7001')
alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_config ={
    'parties': {
        'alice': {
            'address': '10.0.152.10:7002',
            'listen_addr': '0.0.0.0:7002'
        },
        'bob': {
            'address': '10.0.152.11:7002',
            'listen_addr': '0.0.0.0:7002'
        },
    },
    'self_party': 'alice' #bob
}
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.0.152.10:7003'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.0.152.11:7003'
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
sf.init(address='10.0.152.10:7001', cluster_config=cluster_config)
spu = sf.SPU(cluster_def=cluster_def)`

问题：
>>> sf.init(address='10.0.152.10:7001', cluster_config=cluster_config)
2023-02-13 06:48:04,903 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.0.152.10:7001...
2023-02-13 06:48:04,920 INFO worker.py:1538 -- Connected to Ray cluster.
2023-02-13 06:48:06 INFO fed.barriers [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=4749, ip=10.0.152.10) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-02-13 06:48:07 INFO fed.barriers [alice] --  SendProxy was successfully created.
>>> 
>>> 
>>> 
>>> 
>>> spu = sf.SPU(cluster_def=cluster_def)
>>> (SPURuntime pid=30590) 2023-02-13 06:48:33.327 [error] [server.cpp:BRPC:969] Fail to listen 10.0.152.10:7003
(SPURuntime pid=30590) 2023-02-13 06:48:33,361  ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=30590, ip=10.0.152.11, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f5c8ac6aaf0>)
(SPURuntime pid=30590)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=30590)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=30590) RuntimeError: what: 
(SPURuntime pid=30590)  [external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=30590) stacktrace: 
(SPURuntime pid=30590) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f5c9bc260c1
(SPURuntime pid=30590) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f5c9aa6f510
(SPURuntime pid=30590) #2 pybind11::cpp_function::dispatcher()+0x7f5c9aa59c5b
(SPURuntime pid=30590) #3 PyCFunction_Call+0x4dfd82

**Comment by onelyfly** [comment]
然后我试了生产环境部署：
# 在secretflow01 运行
import secretflow as sf
from secretflow.device.device.spu import spu

sf.shutdown()
alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_config ={
    'parties': {
        'alice': {
            'address': '10.0.152.10:7002'
        },
        'bob': {
            'address': '10.0.152.11:7002'
        },
    },
    'self_party': 'alice' #bob
}
sf.init(address='10.0.152.10:7001', cluster_config=cluster_config)

>>> sf.init(address='10.0.152.10:7001', cluster_config=cluster_config)
2023-02-13 07:21:39,281 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.0.152.10:7001...
2023-02-13 07:21:39,298 INFO worker.py:1538 -- Connected to Ray cluster.
2023-02-13 07:21:40 INFO fed.barriers [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=4952) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-02-13 07:21:42 INFO fed.barriers [alice] --  SendProxy was successfully created.

==================
# 在secretflow02 运行
import secretflow as sf
from secretflow.device.device.spu import spu

sf.shutdown()
alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_config ={
    'parties': {
        'alice': {
            'address': '10.0.152.10:7002'
        },
        'bob': {
            'address': '10.0.152.11:7002'
        },
    },
    'self_party': 'bob' #alice
}
sf.init(address='10.0.152.10:7001', cluster_config=cluster_config)

>>> sf.init(address='10.0.152.10:7001', cluster_config=cluster_config)
2023-02-13 07:21:58,282 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.0.152.10:7001...
2023-02-13 07:21:58,301 INFO worker.py:1538 -- Connected to Ray cluster.
2023-02-13 07:22:00 INFO fed.barriers [bob] --  RecverProxy was successfully created.
(RecverProxyActor pid=5055, ip=10.0.152.10) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-02-13 07:22:01 INFO fed.barriers [bob] --  SendProxy was successfully created.

然后在在secretflow02 运行
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.0.152.10:7003'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.0.152.11:7003'
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
spu = sf.SPU(cluster_def=cluster_def)
就报连接不上
>>> (SPURuntime pid=5159, ip=10.0.152.10) 2023-02-13 07:22:52.864 [error] [server.cpp:BRPC:969] Fail to listen 10.0.152.11:7003
(SPURuntime pid=5159, ip=10.0.152.10) 2023-02-13 07:22:52,896   ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=5159, ip=10.0.152.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f04d686db50>)
(SPURuntime pid=5159, ip=10.0.152.10)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=5159, ip=10.0.152.10)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=5159, ip=10.0.152.10) RuntimeError: what: 
(SPURuntime pid=5159, ip=10.0.152.10)   [external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=5159, ip=10.0.152.10) stacktrace: 
(SPURuntime pid=5159, ip=10.0.152.10) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f04e78fd0c1
(SPURuntime pid=5159, ip=10.0.152.10) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f04e6746510
(SPURuntime pid=5159, ip=10.0.152.10) #2 pybind11::cpp_function::dispatcher()+0x7f04e6730c5b
(SPURuntime pid=5159, ip=10.0.152.10) #3 PyCFunction_Call+0x4dfd82

**Comment by zhouaihui** [comment]
生产模式是每个机构一个单独的ray集群。在secretflow02 运行时，你应该连接10.0.152.11上的ray，而不是10.0.152.10。

**Comment by Chrisdehe** [comment]
Stale issue message
Close
