### ISSUE TITLE
如何在仿真集群环境把SPU计算的自定义函数计算结果通过文件形式输出给PYU.

### ISSUE THREAD

**Issue by shifengbj** [secretflow/secretflow#323]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow/secretflow-anolis8:0.7.11b2

### OS Platform and Distribution

Ubuntu18

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
仿真集群下，两个DOCKER容器，一个是NEWALICE,一个是NEWBOB，现在在SPU中进行自定义函数计算，已经取到结果，但是SPU.TO的时候如何以结果文件形式给到PYU？ 

初始代码如下：
cluster_def={
    'nodes': [
        {
            'party': 'newalice',
            'id': '0',
            # Use the ip and port of alice instead.
            # Please choose an unused port.
            'address': '10.1.120.48:13945',
            'listen_addr': '0.0.0.0:13945'
        },
        {
            'party': 'newbob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose an unused port.
            'address': '10.1.120.48:13946',
            'listen_addr': '0.0.0.0:13946'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

def init():
    # Use ray head adress please.
    sf.init(parties=['newalice', 'newbob'], address='10.1.120.48:4567')
    spu = sf.SPU(cluster_def=cluster_def)
    newalice, newbob = sf.PYU('newalice'), sf.PYU('newbob')
    return newalice, newbob, spu



测试计算代码如下：

'''
Class: Main Testing
Author: Stone
02/21/2023
Version: 0.2
'''

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)


def get_result(alice_assets, bob_assets):
    return (alice_assets * bob_assets) / 2 * 15

if __name__ == "__main__":

    print('[1] to init sf server')
    newalice,newbob,spu = init()

    h_df = h_read_csv({newalice: '/root/alice_cal.csv', newbob: '/root/bob_cal.csv'},
                    aggregator=PlainAggregator(newalice))
    alice_assets = h_df.partitions[newalice].values
    bob_assets = h_df.partitions[newbob].values

    print('[2] to compute result')
    result = spu(get_result)(alice_assets, bob_assets)
    print(sf.reveal(result))
    result.to(newbob)
```

### Reproduction code to reproduce the issue.

```shell
仿真集群下，两个DOCKER容器，一个是NEWALICE,一个是NEWBOB，现在在SPU中进行自定义函数计算，已经取到结果，但是SPU.TO的时候如何以结果文件形式给到PYU？ 

初始代码如下：
cluster_def={
    'nodes': [
        {
            'party': 'newalice',
            'id': '0',
            # Use the ip and port of alice instead.
            # Please choose an unused port.
            'address': '10.1.120.48:13945',
            'listen_addr': '0.0.0.0:13945'
        },
        {
            'party': 'newbob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose an unused port.
            'address': '10.1.120.48:13946',
            'listen_addr': '0.0.0.0:13946'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

def init():
    # Use ray head adress please.
    sf.init(parties=['newalice', 'newbob'], address='10.1.120.48:4567')
    spu = sf.SPU(cluster_def=cluster_def)
    newalice, newbob = sf.PYU('newalice'), sf.PYU('newbob')
    return newalice, newbob, spu



测试计算代码如下：

'''
Class: Main Testing
Author: Stone
02/21/2023
Version: 0.2
'''

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)


def get_result(alice_assets, bob_assets):
    return (alice_assets * bob_assets) / 2 * 15

if __name__ == "__main__":

    print('[1] to init sf server')
    newalice,newbob,spu = init()

    h_df = h_read_csv({newalice: '/root/alice_cal.csv', newbob: '/root/bob_cal.csv'},
                    aggregator=PlainAggregator(newalice))
    alice_assets = h_df.partitions[newalice].values
    bob_assets = h_df.partitions[newbob].values

    print('[2] to compute result')
    result = spu(get_result)(alice_assets, bob_assets)
    print(sf.reveal(result))
    result.to(newbob)
```

**Comment by shifengbj** [comment]
补充，日志如下：
2023-02-21 11:11:24,793 INFO worker.py:1538 -- Connected to Ray cluster.

[2] to compute result
(_run pid=10727) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
(_run pid=10727) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=10727) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=10727) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=10727) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=10727) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=25849) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
(_run pid=25849) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=25849) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=25849) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=25849) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=25849) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[[30.]]

**Comment by shifengbj** [comment]
日志倒是正常，另外计算结果已经拿到，但是如何将结果以文件形式输出至PYU。

**Comment by ian-huu** [comment]
SPU 的计算结果会以分片的形式存在于 SPU 各个参与方的内存中。请问你是希望：
1. 把 SPU 内存中的分片先保存成文件，再把文件传输给 PYU
2. 把 SPU 的结果以某种方式保存到其中一方

如果是 1 的话，目前 SPU 还不支持把分片数据保存成文件。
如果是 2 的话，你可以在 `result.to(newbob)` 之后，写一段把 result 保存成文件的代码再让 newbob 来执行：
```
bob_result = result.to(newbob)

def save_to_file(data):
    ...

newbob(save_to_file)(bob_result)
```
