### ISSUE TITLE
是否能支持基于安全多方计算的LightGBM模型训练和XGBoost模型训练算法？

### ISSUE THREAD

**Issue by Stu-Yang** [secretflow/secretflow#324]
### Issue Type

Others

### Source

source

### Secretflow Version

secretflow 0.7.18b0

### OS Platform and Distribution

Ubuntu 20.04

### Python version

Python 3.7.0

### Bazel version

Bazel 5.1.1

### GCC/Compiler version

GCC 7.3.0

### What happend and What you expected to happen.

```shell
目前我正在已经实现了一个LightGBM模型训练算法和XGBoost模型训练算法（均为明文）
现在想将其转换到密文状态下进行。想知道在隐语框架是否支持基于安全多方计算的LightGBM & XGBoost模型训练算法
是否有相关文档可以参考？
```

### Reproduction code to reproduce the issue.

```shell
如题
```

**Comment by ian-huu** [comment]
目前 Secretflow 支持基于秘密分享的 [XGB](https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/mpc_ml/decision_tree.html#ss-xgb-training) 算法，源码在[此处](https://github.com/secretflow/secretflow/tree/main/secretflow/ml/boost/ss_xgb_v)，欢迎试用
