### ISSUE TITLE
生产模式reveal方法执行无响应且多控制器代码执行无效

### ISSUE THREAD

**Issue by shinobi6xp** [secretflow/secretflow#325]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.7.18b3  secretflow-ray  2.2.0 secretflow-rayfed  0.1.0b1 spu  0.3.1b9

### OS Platform and Distribution

Linux version 3.10.0-693.el7.x86_64

### Python version

3.8.13 

### GCC/Compiler version

gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

### What happend and What you expected to happen.

```shell
我在使用生产部署方式部署了一个先本地求随机数组平均值，再两方通过aby3求平均值的demo。执行后发现在sf.reveal(pt)的部分卡住了，前面的日志正常打印。手动终止进程后，提示日志
File "avg2-pro.py", line 101, in <module>
    reciver(recive)(sf.reveal(pt))
  File "/data/projects/common/miniconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 151, in reveal
    all_object = sfd.get(all_object_refs)
  File "/data/projects/common/miniconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 47, in get
    return fed.get(object_refs)
  File "/data/projects/common/miniconda3/envs/sf/lib/python3.8/site-packages/fed/api.py", line 361, in get
    values = ray.get(ray_refs)
  File "/data/projects/common/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/data/projects/common/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py", line 2305, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/data/projects/common/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py", line 670, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 1554, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 195, in ray._raylet.check_status
KeyboardInterrupt
个人感觉前面输出的日志像是只说明spu的计算调度命令发出去了，也得到了指针，但是并未真正执行，当执行到sf.reveal(pt)需要等到其他人结果的时候发现找不到objects了，麻烦解答一下
```

### Reproduction code to reproduce the issue.

```shell
import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'reciver'
}
sf.init(address='172.16.4.63:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': '1639995892',
            'id': '1639995892:0',
            'address': '172.16.4.61:8222',
        },
        {
            'party': '1639998474',
            'id': '1639998474:0',
            'address': '172.16.4.62:8222',
        },
        {
            'party': '1640046801',
            'id': '1640046801:0',
            'address': '172.16.4.63:8222',
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

spu.shutdown()
sf.shutdown()
```

**Comment by ian-huu** [comment]
spu 的 party 和 sf.init 中的 parties 需要对应，否则 spu 没有办法在这个 sf 集群中建立起来。
比如，你可以将 spu 的 party 设置为 alice、bob、reciver

**Comment by shinobi6xp** [comment]
你好，我将spu的config改成
spu_config = {
      'nodes': [
          {
              'party': 'alice',
              'id': 's1',
              'address': '172.16.4.61:8222',
          },
          {
              'party': 'bob',
              'id': 's2',
              'address': '172.16.4.62:8222',
          },
          {
              'party': 'reciver',
              'id': 's3',
              'address': '172.16.4.63:8222',
          }
      ],
      'runtime_config': {
          'protocol': spu.spu_pb2.ABY3,
          'field': spu.spu_pb2.FM128
      }
}
后还是同样卡住的效果，可以从哪里的日志看到spu被成功建立起来吗

**Comment by shinobi6xp** [comment]
> spu 的 party 和 sf.init 中的 parties 需要对应，否则 spu 没有办法在这个 sf 集群中建立起来。 比如，你可以将 spu 的 party 设置为 alice、bob、reciver (或者反过来)

你好，我将spu的config改成
spu_config = {
'nodes': [
{
'party': 'alice',
'id': 's1',
'address': '172.16.4.61:8222',
},
{
'party': 'bob',
'id': 's2',
'address': '172.16.4.62:8222',
},
{
'party': 'reciver',
'id': 's3',
'address': '172.16.4.63:8222',
}
],
'runtime_config': {
'protocol': spu.spu_pb2.ABY3,
'field': spu.spu_pb2.FM128
}
}
后还是同样卡住的效果，可以从哪里的日志看到spu被成功建立起来吗

**Comment by ian-huu** [comment]
能提供一下 3 方的代码吗？需要确保 3 个参与方的代码都是正确的，并且几乎同时执行

**Comment by shinobi6xp** [comment]
> 能提供一下 3 方的代码吗？需要确保 3 个参与方的代码都是正确的，并且几乎同时执行

第一方：import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
class timecollect:

    def start(self):
        self.start = time.time()

    def end(self):
        return time.time()-self.start
timecollect = timecollect()

timecollect.start()
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            # replace with bob's real address.
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            # replace with bob's real address.
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'alice'
}
sf.init( address='172.16.4.61:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': 'alice',
            'id': 's1',
            # The address for other peers.
            'address': '172.16.4.61:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'bob',
            'id': 's2',
            # The address for other peers.
            'address': '172.16.4.62:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'reciver',
            'id': 's3',
            'address': '172.16.4.63:8222',
            # 'listen_address': ''
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
# result = sf.reveal()
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

timecost = timecollect.end()
print(f"timecost = {timecost}")

with open('./avg2_timecost', 'w') as f1:
    f1.write(f"avg2 time cost {timecost}")
print("over")
spu.shutdown()
sf.shutdown()
第二方：
import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
class timecollect:

    def start(self):
        self.start = time.time()

    def end(self):
        return time.time()-self.start
timecollect = timecollect()

timecollect.start()
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            # replace with bob's real address.
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            # replace with bob's real address.
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'bob'
}
sf.init( address='172.16.4.62:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': 'alice',
            'id': 's1',
            # The address for other peers.
            'address': '172.16.4.61:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'bob',
            'id': 's2',
            # The address for other peers.
            'address': '172.16.4.62:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'reciver',
            'id': 's3',
            'address': '172.16.4.63:8222',
            # 'listen_address': ''
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
# result = sf.reveal()
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

timecost = timecollect.end()
print(f"timecost = {timecost}")

with open('./avg2_timecost', 'w') as f1:
    f1.write(f"avg2 time cost {timecost}")
print("over")
spu.shutdown()
sf.shutdown()
第三方：
import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
class timecollect:

    def start(self):
        self.start = time.time()

    def end(self):
        return time.time()-self.start
timecollect = timecollect()

timecollect.start()
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            # replace with bob's real address.
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            # replace with bob's real address.
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'reciver'
}
sf.init( address='172.16.4.63:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': 'alice',
            'id': 's1',
            # The address for other peers.
            'address': '172.16.4.61:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'bob',
            'id': 's2',
            # The address for other peers.
            'address': '172.16.4.62:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'reciver',
            'id': 's3',
            'address': '172.16.4.63:8222',
            # 'listen_address': ''
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
# result = sf.reveal()
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

timecost = timecollect.end()
print(f"timecost = {timecost}")

with open('./avg2_timecost', 'w') as f1:
    f1.write(f"avg2 time cost {timecost}")
print("over")
spu.shutdown()
sf.shutdown()

**Comment by shinobi6xp** [comment]
> 能提供一下 3 方的代码吗？需要确保 3 个参与方的代码都是正确的，并且几乎同时执行

第一方：import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
class timecollect:

    def start(self):
        self.start = time.time()

    def end(self):
        return time.time()-self.start
timecollect = timecollect()

timecollect.start()
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            # replace with bob's real address.
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            # replace with bob's real address.
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'alice'
}
sf.init( address='172.16.4.61:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': 'alice',
            'id': 's1',
            # The address for other peers.
            'address': '172.16.4.61:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'bob',
            'id': 's2',
            # The address for other peers.
            'address': '172.16.4.62:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'reciver',
            'id': 's3',
            'address': '172.16.4.63:8222',
            # 'listen_address': ''
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
# result = sf.reveal()
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

timecost = timecollect.end()
print(f"timecost = {timecost}")

with open('./avg2_timecost', 'w') as f1:
    f1.write(f"avg2 time cost {timecost}")
print("over")
spu.shutdown()
sf.shutdown()
第二方：
import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
class timecollect:

    def start(self):
        self.start = time.time()

    def end(self):
        return time.time()-self.start
timecollect = timecollect()

timecollect.start()
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            # replace with bob's real address.
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            # replace with bob's real address.
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'bob'
}
sf.init( address='172.16.4.62:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': 'alice',
            'id': 's1',
            # The address for other peers.
            'address': '172.16.4.61:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'bob',
            'id': 's2',
            # The address for other peers.
            'address': '172.16.4.62:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'reciver',
            'id': 's3',
            'address': '172.16.4.63:8222',
            # 'listen_address': ''
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
# result = sf.reveal()
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

timecost = timecollect.end()
print(f"timecost = {timecost}")

with open('./avg2_timecost', 'w') as f1:
    f1.write(f"avg2 time cost {timecost}")
print("over")
spu.shutdown()
sf.shutdown()
第三方：
import time

import requests
import spu as spu

import secretflow as sf
import numpy as np
import pandas as pd
import jax.numpy as jnp
class timecollect:

    def start(self):
        self.start = time.time()

    def end(self):
        return time.time()-self.start
timecollect = timecollect()

timecollect.start()
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '172.16.4.61:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'bob': {
            # replace with bob's real address.
            'address': '172.16.4.62:6325',
            'listen_addr': '0.0.0.0:6325'
        },
        'reciver': {
            # replace with bob's real address.
            'address': '172.16.4.63:6325',
            'listen_addr': '0.0.0.0:6325'
        },
    },
    'self_party': 'reciver'
}
sf.init( address='172.16.4.63:6324', cluster_config=cluster_config)
alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')

def make_data():
    nl = np.random.rand(10000000, 1)
    return np.average(nl)


def process(a, b):
    return jnp.average(jnp.array([a, b]))

a = alice(make_data)()
b = bob(make_data)()
c = reciver(make_data)()

spu_config = {
    'nodes': [
        {
            'party': 'alice',
            'id': 's1',
            # The address for other peers.
            'address': '172.16.4.61:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'bob',
            'id': 's2',
            # The address for other peers.
            'address': '172.16.4.62:8222',
            # The listen address of this node.
            # Optional. Address will be used if listen_address is empty.
            # 'listen_address': ''
        },
        {
            'party': 'reciver',
            'id': 's3',
            'address': '172.16.4.63:8222',
            # 'listen_address': ''
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128
    }
}
spu = sf.SPU(spu_config)

print("avg2 ready")
# result = sf.reveal()
sa = spu(process)(a, b)
pt = sa.to(reciver)
print(f"result={pt}")

def recive(result_array):
    df = pd.DataFrame(result_array.tolist())
    df.to_csv('/data/secretflow/avg2_result', index=False)
reciver(recive)(sf.reveal(pt))

timecost = timecollect.end()
print(f"timecost = {timecost}")

with open('./avg2_timecost', 'w') as f1:
    f1.write(f"avg2 time cost {timecost}")
print("over")
spu.shutdown()
sf.shutdown()

**Comment by shinobi6xp** [comment]
> 能提供一下 3 方的代码吗？需要确保 3 个参与方的代码都是正确的，并且几乎同时执行

另外我也尝试过单方启动，进程会在几秒钟后因为超时而终止，所以我确定我肯定是三方差不多同时启动的

**Comment by ian-huu** [comment]
`alice, bob, reciver = sf.PYU('1639995892'), sf.PYU('1639998474'), sf.PYU('1640046801')`
也需要改成 
`alice, bob, reciver = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('reciver')`

我们会在后续逐步优化 rayfed 的 debug 日志，目前还是建议先在单控制器模式下调试代码，然后（修改 ip 端口后）部署到多控制器模式

**Comment by shinobi6xp** [comment]
> alice

我将ray集群的启动指令也统一成alice bob reciver，修改设置后可以了。
1.目前来说ray start --head --node-ip-address="172.16.4.61" --port="6324" --resources='{"1639995892": 8}' --include-dashboard=False --disable-usage-stats
中的resources里面的key，和sf.init中的cluster_config中的party，以及spu的config中的party，都设置成统一的就不会有错了吧。
2.spu的config中nodes里面和party同级的id是可以随意配置的吗？
spu_config = {
'nodes': [
{
'party': 'alice',
'id': 's1',
'address': '172.16.4.61:8222',
},
{
'party': 'bob',
'id': 's2',
'address': '172.16.4.62:8222',
},
{
'party': 'reciver',
'id': 's3',
'address': '172.16.4.63:8222',
}
],
'runtime_config': {
'protocol': spu.spu_pb2.ABY3,
'field': spu.spu_pb2.FM128
}
}

**Comment by ian-huu** [comment]
1. 多控制器模式下 ray 集群启动时不需要设置  --resources
2. spu config 中的 party 需要和 sf.init 中的 parties 对应，id 可以任意配(只要不冲突即可)
