### ISSUE TITLE
SQL部分开源计划

### ISSUE THREAD

**Issue by hhq326781458** [secretflow/secretflow#326]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

/

### OS Platform and Distribution

/

### Python version

/

### What happend and What you expected to happen.

```shell
SQL部分计划什么时候开源？现在重点是在跨特征还是跨样本呢？底层也是调用SPU吗？谢谢
```

### Reproduction code to reproduce the issue.

```shell
/
```

**Comment by pchyuan** [comment]
SQL目前是计划Q1会开源，目前实现的是跨特征，底层也是基于SPU的。
