### ISSUE TITLE
文档中的图像分类联邦学习的源代码错误bug

### ISSUE THREAD

**Issue by kavenmo** [secretflow/secretflow#33]
在开发文档的demo中，图像分类联邦学习的源代码，导入FL模型部分代码似乎是错误，
原代码：
from secretflow.security.aggregation import SpuAggregator, SecureAggregator
from secretflow.ml.nn import FLModelTF

正确代码：
from secretflow.security.aggregation import SPUAggregator, SecureAggregator
from secretflow.ml.nn import FLModelTF

改为上述代码后，运行报错：
File ~/miniconda3/envs/tensorflow2/lib/python3.8/site-packages/secretflow/security/privacy/mechanism/tensorflow/layers.py:23, in <module>
     17 from abc import ABC, abstractmethod
     19 from secretflow.security.privacy.accounting.rdp_accountant import (
     20     get_rdp,
     21     get_privacy_spent_rdp,
     22 )
---> 23 import secretflow.security.privacy._lib.random as random
     26 class EmbeddingDP(tf.keras.layers.Layer, ABC):
     27     def __init__(self) -> None:

ModuleNotFoundError: No module named 'secretflow.security.privacy._lib'

请问如何解决？

**Comment by zhouaihui** [comment]
请问你是macOS还是linux？

**Comment by kavenmo** [comment]
macos，是 from secretflow.ml.nn import FLModelTF 
这个导入报错了

**Comment by wuxibin89** [comment]
@kavenmo macos的包问题修复了，麻烦升级到`secretflow==0.6.13b1`试试
