### ISSUE TITLE
Ray zero-copy on self-defined objects.

### ISSUE THREAD

**Issue by zhouaihui** [secretflow/secretflow#336]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

0.7.18

### OS Platform and Distribution

Linux

### Python version

3.8

### What happend and What you expected to happen.

Ray supports zero-copy on [numpy arrays](https://docs.ray.io/en/latest/ray-core/objects/serialization.html#numpy-arrays), is it possible to add self-defined objects, e.g. HEUObject, to zero-copy list? This will benefit the performance of many algorithms based on HE.

**Comment by zhouaihui** [comment]
cc @usafchn

**Comment by usafchn** [comment]
> cc @usafchn

This optimization relies on Ray to open zero-copy api
