### ISSUE TITLE
隐语框架是否支持密文状态下的全过程模型训练？

### ISSUE THREAD

**Issue by Stu-Yang** [secretflow/secretflow#337]
### Issue Type

Others

### Source

source

### Secretflow Version

secretflow 0.7.18b3

### OS Platform and Distribution

Ubuntu 20.04

### Python version

Python 3.8.16

### Bazel version

Bazel 5.1.1

### GCC/Compiler version

GCC 11.2.0

### What happend and What you expected to happen.

```shell
请问一下，隐语框架是否支持基于安全多方计算的模型融合？还是只能支持单一模型训练？
```

### Reproduction code to reproduce the issue.

```shell
例如，利用隐语框架中基于安全多方计算的模型训练算法，训练出model1和model2，请问是否支持model1和model2在密文状态下进行模型融合？
```

**Comment by rivertalk** [comment]
hi @Stu-Yang 感谢提问

请教一下具体的模型融合过程是指？融合两个模型有具体的算法吗

**Comment by Stu-Yang** [comment]
@rivertalk 十分感谢您的回复，我之前以为目前的模型融合是存在多个模型间的参数传递和共享，但我上周确认了一下自己的模型融合的具体算法，其实是模型预测结果的加权平均，现在已经没有问题了，十分感谢～

**Comment by Stu-Yang** [comment]
不过在我学习的过程中，我了解到隐私保护机器学习训练过程中其他的问题，不知道能否给予解答：
基于密码学（如安全多方计算、同态加密等）可以实现**密文状态下的模型训练和预测**，然而针对经典机器学习浅层模型（以XGBoost模型为例），其进行模型训练和预测的前提是做好**特征工程**，因此对于隐私保护XGBoost模型训练而言，其实还需要**密文状态下的特征工程**，而这一过程并未在许多工作中考虑，请问隐语框架是否支持密文状态下的全过程模型训练（特征工程+模型训练和预测）？

**Comment by rivertalk** [comment]
Hi @Stu-Yang  这是个非常好的问题!

> 请问隐语框架是否支持密文状态下的全过程模型训练（特征工程+模型训练和预测）？

简而言之：是也不是

“是” 是因为隐语提供密态下的通用计算能力，理论上使用numpy写出来的算法，隐语SPU都可以编译到密态环境下之行，从而保护整个计算过程。所以，特征工程，模型训练，预测 单独看都是在密文状态下做的

“不是” 是因为 特征工程 往往需要对数据本身进行一定的分析，譬如进行特征筛选的时候，往往需要计算VIF（方差膨胀因子），CORR（相关系数矩阵）等数据，虽然这些计算本身是密文下做的（保护原始数据），但是计算出来的结果是需要告知建模人员的（不保护特征工程输出）。所以严格意思上来讲，将 特征工程+训练+预测 看成整体，其过程并不是全密态的，不过特征过程的输出往往是高阶抽象的数据，本身不会泄漏原始数据信息

**Comment by Stu-Yang** [comment]
@rivertalk 十分感谢你的回复，我差不多理解了你的意思，但是还有一个小小的疑惑：

> 特征过程的输出往往是高阶抽象的数据，本身不会泄漏原始数据信息

当我在做机器学习项目过程中（明文计算，原始数据可见），对原始数据进行特征工程后，得到的结构化训练数据其实还是会包含原始数据，只不过我进行了特征选择以及预处理，因此特征工程的输出是会包含部分原始数据的。你所叙述的是否是说：在实际的工程项目中，可以实现在原始数据经过特征工程后，得到的结构化的训练数据是原始数据的统计分析信息，而这些信息是高阶抽象的，因此不会泄漏原始数据信息？

**Comment by rivertalk** [comment]
我理解不太一样。这里的“特征工程的输出”，具体来讲包含了两个方面
1. 原始数据的统计分析信息，这部分信息会暴露给建模人员来进行后续的筛选和处理，他是高阶抽象和降维的，不会暴露原始数据
2. 根据步骤一进行的特征选择和预处理，这个步骤本身是保密的，所以处理之后的特征也是密文。这部分数据信息量和维度与原始数据相当，甚至可以反推原始数据，是不能暴露出来的

**Comment by Stu-Yang** [comment]
@rivertalk 好的，我现在理解了，我最后的疑惑在于：将 特征工程输出 披露给 建模人员 是否可以避免？

以安全多方计算为例，根据安全多方计算的理论结果可知：任何函数都可以安全计算。因此是否可以实现基于安全多方计算的特征工程算法，也就是说目前是否可能能够实现基于安全多方计算的全过程特征工程+模型训练+预测？我个人理解是该问题在理论上是可行的，可能目前在业界存在一定瓶颈（比如许多特征需要进行人的先验知识，因此特征需要被“看见”），不知道我的理论是否是对的？

**Comment by rivertalk** [comment]
> 将 特征工程输出 披露给 建模人员 是否可以避免？

我理解这个过程也是可以避免的，就是将建模人员的特征筛选/处理的规则编码并且交给密态执行，譬如某两个特征相关性大于某阈值时，剔除其中一个。

这样做有些问题，我暂时能想到的比如：
- 可解释性会进一步降低，整体过程性能也会下降
- 剔除某一列本身如果是密态的话，那么feature.shape 就必须加密，否则“是否剔除”这个行为本身会泄漏“是否有相关性”信息（但的确可以保护“剔除了那一列”这个信息）。PS: 目前所有计算的shape都是明文的，使用密文shape性能看起来会有比较大的性能折损

不过这的确是个很有趣的问题 :P

**Comment by Stu-Yang** [comment]
@rivertalk 感谢您的回复，我觉得我大体明白了这个问题了，十分感谢～
