### ISSUE TITLE
隐语有没有实现基于同态的psi

### ISSUE THREAD

**Issue by knao1** [secretflow/secretflow#338]
### Issue Type

Others

### Source

binary

### Secretflow Version

.

### OS Platform and Distribution

.

### Python version

.

### What happend and What you expected to happen.

```shell
.
```

### Reproduction code to reproduce the issue.

```shell
.
```

**Comment by zhanglei486** [comment]
spu代码库有基于同态的labeled psi的c++封装，底层实现依赖microsoft APSI，
secretflow代码库目前还没集成spu中的labeled psi

**Comment by Chrisdehe** [comment]
Stale issue message
Close
