### ISSUE TITLE
安全聚合的疑问

### ISSUE THREAD

**Issue by Wyyyb** [secretflow/secretflow#34]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/20929360/178641234-c26b9f9d-3595-4a1f-b712-54e3acc22d21.png">
如图，用“安全聚合模块”和“定义函数编译生成静态计算图”两种方式都可以达到聚合的效果，请问两者有什么不同呢？

**Comment by Wyyyb** [comment]
补充一个问题：定义函数编译生成静态计算图的方法里是不能进行一些指数、三角函数等非线性运算的？如果需要做这些运算应该怎么做呢？

**Comment by zhouaihui** [comment]
第一个问题：
两者其实是一样的，SpuAggregator只是对spu(np.sum)/spu(npaverage)的封装。

**Comment by wuxibin89** [comment]
> 定义函数编译生成静态计算图的方法里是不能进行一些指数、三角函数等非线性运算的？

SPU支持[JAX](https://jax.readthedocs.io/en/latest/)前端，所以只要JAX支持的操作，都可以编译至SPU执行
```python
def selu(x, alpha=1.67, lmbda=1.05):
  return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

res = spu(selu)(x)
```

BTW. 后续使用上的问题请移步[secretflow discussions](https://github.com/secretflow/secretflow/discussions)，issues用于bug report/feature request。

**Comment by Wyyyb** [comment]
> secretflow discussions

```
arr0, arr1 = np.random.rand(2, 3), np.random.rand(2, 3)
a = alice(lambda: arr0)()
b = bob(lambda: arr1)()
aa = sf.to(spu, a)
bb = sf.to(spu, b)

def nonlinear1(x, y):
    return jnp.exp(x) + jnp.tan(y)

e = nonlinear1(arr0, arr1)
print("明文非线性函数", e)

f = spu(nonlinear1)(aa, bb)
print("非线性函数 ", sf.reveal(f))
```

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/20929360/178644373-aea6d732-f8fb-4d80-95cd-17afc8c7b4c8.png">
这个例子似乎JAX可以支持，但是不能编译通过。

**Comment by Wyyyb** [comment]
> BTW. 后续使用上的问题请移步[secretflow discussions](https://github.com/secretflow/secretflow/discussions)，issues用于bug report/feature request。 

好的

**Comment by anakinxc** [comment]
三角函数和双曲函数里现在暂时只实现了 tanh，其他会在后续迭代中陆续添加

jax numpy 大体上的支持情况可以看一下这个[测试文件](https://github.com/secretflow/spu/blob/beta/spu/binding/tests/jnp_testbase.py)

**Comment by Wyyyb** [comment]
> 

好的明白了，期待后续迭代。
