### ISSUE TITLE
关于隐语提供的PSI测试示例（simple_psi.py）的一些疑问

### ISSUE THREAD

**Issue by Ant1proton** [secretflow/secretflow#343]
对于隐语提供的关于PSI的例子
（https://github.com/secretflow/spu/blob/v0.3.2b1/examples/python/psi/simple_psi.py）
有如下几个问题，麻烦各位老师解答一下：
1.是否执行PSI都必须要有‘field_names’参数，我试图将其置空值，结果报错。有没有什么可以不设置field_names执行PSI的方法
2.bucketsize在例子中被设置为1048576，是指每次求交集分桶的大小是1048576吗？这个参数怎么选取的？
3.似乎请求要先由发送方发起，否则会报错（如下图所示）
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/35170378/222318491-8d318a49-b516-4343-90c9-47c19ab0c006.png">

**Comment by zhanglei486** [comment]
1. ‘field_names’参数，是待求交输入csv文件的列名，需要指定
2. bucketsize只适用于kkrt等内存占用量大的PSI协议，参数选择是根据机器上的内存大小和安全需求来定的
ecdh psi可以分批读入和处理数据，bucket_size对ecdh_psi没有作用
3. PSI协议一般都是把两发角色定义为发起方和接收方，手动运行simple_psi 两方启动时间间隔太大会报错，可以尝试通过secretflow来调用，会自动拉起两方任务

**Comment by Ant1proton** [comment]
> 1. ‘field_names’参数，是待求交输入csv文件的列名，需要指定
> 2. bucketsize只适用于kkrt等内存占用量大的PSI协议，参数选择是根据机器上的内存大小和安全需求来定的
>    ecdh psi可以分批读入和处理数据，bucket_size对ecdh_psi没有作用
> 3. PSI协议一般都是把两发角色定义为发起方和接收方，手动运行simple_psi 两方启动时间间隔太大会报错，可以尝试通过secretflow来调用，会自动拉起两方任务

1.也就是必须设置‘field_names’,是吗？
2.bucketsize即根据本地情况制定的分桶大小
3.PSI协议一般都是把两方角色定义为发起方和接收方，我测试多次，在隐语中，相同时间间隔内（不超过1s），同样的脚本，由发起方发起则运行成功，由接收方先行发起任务则失败。但原本的libpsi协议似乎不存在这个发起方和接收方谁先发起协议的问题，由任意一方发起均可顺利执行协议。

**Comment by zhanglei486** [comment]
看上面的异常日志，显示create_brpc报错，应该和spu内部使用的网络连接库底层建立网络连接的处理方式逻辑有关系，还没到psi协议的处理逻辑
<img width="438" alt="image" src="https://user-images.githubusercontent.com/47308800/222341011-35c6f244-3c69-4e11-9ecc-00b1bf96acf0.png">
可以适当调大下面两个参数试一下：

- connect_retry_times
- connect_retry_interval_ms

**Comment by Ant1proton** [comment]
> 看上面的异常日志，显示create_brpc报错，应该和spu内部使用的网络连接库底层建立网络连接的处理方式逻辑有关系，还没到psi协议的处理逻辑 <img alt="image" width="438" src="https://user-images.githubusercontent.com/47308800/222341011-35c6f244-3c69-4e11-9ecc-00b1bf96acf0.png"> 可以适当调大下面两个参数试一下：
> 
> * connect_retry_times
> * connect_retry_interval_ms

好的谢谢
