### ISSUE TITLE
提供下windos的源

### ISSUE THREAD

**Issue by laoyu01** [secretflow/secretflow#349]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow==0.7.18b2

### OS Platform and Distribution

windows

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
需要windows的源
```

### Reproduction code to reproduce the issue.

```shell
需要windows的源
```

**Comment by laoyu01** [comment]
https://mirrors.aliyun.com/pypi/simple/secretflow/

**Comment by anakinxc** [comment]
windows 用户推荐使用 wsl 来安装

参见 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/installation.html#option-4-from-wsl

**Comment by laoyu01** [comment]
windows本地环境开发无法pip install secretflow

**Comment by laoyu01** [comment]
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting secretflow
  Using cached https://mirrors.aliyun.com/pypi/packages/3c/d6/90e65201b1dbcf357de5ce233117da0cde9ed1612c0a5e05148de84467cd/secretflow-0.7.7b0.tar.gz (163 kB)
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\AppData\Local\Temp\pip-install-yn8onqpm\secretflow_2418efe06e1f4454b2a31ba8cb9db5cb\setup.py", line 100, in <module>
          install_requires=read_requirements(),
        File "C:\Users\A\AppData\Local\Temp\pip-install-yn8onqpm\secretflow_2418efe06e1f4454b2a31ba8cb9db5cb\setup.py", line 17, in read_requirements
          with open('./requirements.txt') as file:
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by laoyu01** [comment]
只有0.7.7b0版本,可以提供下高版本吗

**Comment by zhouaihui** [comment]
> windows 用户推荐使用 wsl 来安装
> 
> 参见 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/installation.html#option-4-from-wsl

hi, @laoyu01 , SecretFlow目前并不支持支持Windows，可以通过wsl获得linux环境来体验。具体见上。
