### ISSUE TITLE
attributeError

### ISSUE THREAD

**Issue by ASTER71** [secretflow/secretflow#352]
### Issue Type

Bug

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

MACos

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
运行heu / heu/ pylib / phe_test.py
报错AttributeError: heu. phe. Hekit" object has no attribute 'batch_integer_encoder'
```

### Reproduction code to reproduce the issue.

```shell
运行heu / heu/ pylib / phe_test.py
报错AttributeError: heu. phe. Hekit" object has no attribute 'batch_integer_encoder'
```

**Comment by usafchn** [comment]
您好，HEU main 分支上的接口有些变更，以下两种修复方法二选一：

方法一：按照以下文档重新编译安装 HEU：
https://www.secretflow.org.cn/docs/heu/zh_CN/getting_started/installation.html#id3  （从源码安装）

方法二：直接通过 bazel 命令运行 phe_test.py：
bazel run heu/ pylib:phe_test

附：接口变更详情：
https://www.secretflow.org.cn/docs/heu/zh_CN/references/upgrade_guide.html#heu-0-3-x-0-4-x

**Comment by usafchn** [comment]
报错的截图需要重新贴一下，通过 email 回复的 issue 好像显示不了图片
