### ISSUE TITLE
请问如何将woe_rules 中每桶的ivs取出来，然后对ivs求和？

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#353]
### Issue Type

Others

### Source

source

### Secretflow Version

0.7.18b0

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
通过woe_rules = binning.binning(）语句返回得到woes和ivs
返回数据类型是Dict[PYU, PYUObject]

sf.reveal(woe_rules[alice])

我的需求：
我想得到数据分桶后的ivs并对ivs求和

我的问题：
目前dict的常规操作无法获取到woe_rules[alice]中的ivs,请问该怎么操作？
```

### Reproduction code to reproduce the issue.

```shell
binning = VertWoeBinning(spu)
woe_rules = binning.binning(
    vdf,
    binning_method="quantile", # how to bin number type features. Options: “quantile”(equal frequency)/”chimerge”(ChiMerge from AAAI92-019) Default: “quantile”
    bin_num=5,# max bin counts for one features. Range: (0, ∞] Default: 10
    bin_names={alice: ["y4","y5","y6"], bob: ["x1","x2","x3"]},# which features should be binned
    label_name="y",# label column name.
)

ivs = woe_rules[alice]
print('iiiivs',ivs)
ivscol = sf.reveal(ivs[0]['ivs']) # 获得某一列数据计算出来的ivs,但这是一个无效操作
sumIvs = np.sum(ivscol)
```

**Comment by 6fj** [comment]
hi @SZU-czw 

你可以尝试reveal一下alice一方的woe_rules：
```
print(sf.reveal(woe_rules[alice]))
```
观察一下数据结构是否符合你的预期。

另外sf.reveal的input只能是device object。

**Comment by SZU-czw** [comment]
执行print(sf.reveal(woe_rules[alice]))得到如下数据，但是里面的单个ivs 有办法取出来求和吗？

**Comment by SZU-czw** [comment]
你好，我想把reveal 后的结果，如下图x1 ，x2 ，x3 分别对应的ivs(一个list)取出来求和，有办法吗？
woe_rules for alice:
 {'variables': [{'name': **'x1'**, 'type': 'numeric', 'split_points': [-0.6048731088638305, -0.2093792676925656, 0.1864844083786014, 0.59245548248291], 'woes': [0.13818949789069251, 0.1043626580338657, 0.012473718947119546, -0.08312553911263658, -0.16055365315128886], '**ivs**': [0.003719895277030594, 0.0021358508878795324, 3.104792224414912e-05, 0.001402356358949689, 0.005298781871642081], 'total_counts': [2000, 2000, 2000, 2000, 2000], 'else_woe': -0.7620562438001163, 'else_iv': 6.385923806287768e-05, 'else_counts': 0}, {'name': **'x2**', 'type': 'numeric', 'split_points': [-0.6180597543716427, -0.21352910995483343, 0.18739376068115243, 0.5941788196563724], 'woes': [-0.5795513521445242, -0.17800092651085536, 0.02175062133493428, 0.32061945260518093, 0.5508555713857505], 'ivs': [0.07282166470764677, 0.006530977061248972, 9.424153452104671e-05, 0.019271267842100412, 0.05393057944296773], 'total_counts': [2000, 2000, 2000, 2000, 2000], 'else_woe': -0.7620562438001163, 'else_iv': 6.385923806287768e-05, 'else_counts': 0}, {'name': 'x3', 'type': 'numeric', 'split_points': [-0.5902724504470824, -0.19980529546737677, 0.2072824716567998, 0.6102998018264773], 'woes': [-0.5371125119817587, -0.25762552591997334, -0.022037294110497735, 0.3445721198562295, 0.6304998785437507], 'ivs': [0.062290057806557865, 0.013846189451494859, 9.751520288052276e-05, 0.022140413942886045, 0.06928418076454097], 'total_counts': [2000, 2000, 2000, 2000, 2000], 'else_woe': -0.7620562438001163, 'else_iv': 6.385923806287768e-05, 'else_counts': 0}]}

**Comment by 6fj** [comment]
hi @SZU-czw ,

你可以用PYU device来完成
```
def parse_rule(rule):
  # your logic

sumIvs=alice(parse_rule)(woe_rules[alice])

#reveal
sf.reveal(sumIvs)
```

**Comment by SZU-czw** [comment]
明天上班后，可以帮我看看吗？我如下取ivs操作方式可能是错误的,但我不知道如何改正
import secretflow as sf
import numpy as np
# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], address='local')
alice = sf.PYU('alice')
bob = sf.PYU('bob')

# woe binning use SPU or HEU device to protect label
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

# Only support binary classification label dataset for now.
# use linear dataset as example
from secretflow.utils.simulation.datasets import load_linear
vdf = load_linear(parts={alice: (1, 4), bob: (18, 22)})
print(f"orig ds in alice:\n {sf.reveal(vdf.partitions[alice].data)}")
print(f"orig ds in bob:\n {sf.reveal(vdf.partitions[bob].data)}")

from secretflow.preprocessing.binning.vert_woe_binning import VertWoeBinning

binning = VertWoeBinning(spu)
woe_rules = binning.binning(
    vdf,
    binning_method="quantile",
    bin_num=5,
    bin_names={alice: ["x1", "x2", "x3"], bob: ["x18", "x19", "x20"]},
    label_name="y",
)

print(f"woe_rules for alice:\n {sf.reveal(woe_rules[alice])}")
print(f"woe_rules for bob:\n {sf.reveal(woe_rules[bob])}")

#from secretflow.preprocessing.binning.vert_woe_substitution import VertWOESubstitution

#woe_sub = VertWOESubstitution()
#sub_data = woe_sub.substitution(vdf, woe_rules)

#print(f"substituted ds in alice:\n {sf.reveal(sub_data.partitions[alice].data)}")
#print(f"substituted ds in bob:\n {sf.reveal(sub_data.partitions[bob].data)}")

# 执行到到这里就会报错
def parse_rule(rule):
  # your logic
  sum = np.sum(rule)
  return sum

#取某一列特征并计算ivs然后对ivs求和
sumIvs=alice(parse_rule)(woe_rules[alice]['variables'][0]['ivs'])

#woe_rules[alice] 返回的数据类型
''' 
{
    "variables":[
        {
            "name": str, # feature name
            "type": str, # "string" or "numeric", if feature is discrete or continuous
            "categories": list[str], # categories for discrete feature
            "split_points": list[float], # left-open right-close split points
            "total_counts": list[int], # total samples count in each bins.
            "else_counts": int, # np.nan samples count
            "woes": list[float], # woe values for each bins.
            "else_woe": float, # woe value for np.nan samples.
            "ivs": list[float], # iv values for each bins.
            "else_iv": float, # iv value for np.nan samples.
        },
        # ... others feature
    ]
}
'''
#reveal
print('ivs sum :',sf.reveal(sumIvs))

**Comment by SZU-czw** [comment]
明天上班的时候可以帮我看看吗？我取某一个特征的ivs方式可能是错误的操作。
import secretflow as sf
import numpy as np
 In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], address='local')
alice = sf.PYU('alice')
bob = sf.PYU('bob')

 woe binning use SPU or HEU device to protect label
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

 Only support binary classification label dataset for now.
 use linear dataset as example
from secretflow.utils.simulation.datasets import load_linear
vdf = load_linear(parts={alice: (1, 4), bob: (18, 22)})
print(f"orig ds in alice:\n {sf.reveal(vdf.partitions[alice].data)}")
print(f"orig ds in bob:\n {sf.reveal(vdf.partitions[bob].data)}")

from secretflow.preprocessing.binning.vert_woe_binning import VertWoeBinning

binning = VertWoeBinning(spu)
woe_rules = binning.binning(
    vdf,
    binning_method="quantile",
    bin_num=5,
    bin_names={alice: ["x1", "x2", "x3"], bob: ["x18", "x19", "x20"]},
    label_name="y",
)
'''
print(f"woe_rules for alice:\n {sf.reveal(woe_rules[alice])}")
print(f"woe_rules for bob:\n {sf.reveal(woe_rules[bob])}")

from secretflow.preprocessing.binning.vert_woe_substitution import VertWOESubstitution

woe_sub = VertWOESubstitution()
sub_data = woe_sub.substitution(vdf, woe_rules)

print(f"substituted ds in alice:\n {sf.reveal(sub_data.partitions[alice].data)}")
print(f"substituted ds in bob:\n {sf.reveal(sub_data.partitions[bob].data)}")
'''


# 执行到到这里就会报错
def parse_rule(rule):
  # your logic
  sum = np.sum(rule)
  return sum

取某一列特征并计算ivs然后对ivs求和
sumIvs=alice(parse_rule)(woe_rules[alice]['variables'][0]['ivs'])

woe_rules[alice] 返回的数据类型
''' 
{
    "variables":[
        {
            "name": str, # feature name
            "type": str, # "string" or "numeric", if feature is discrete or continuous
            "categories": list[str], # categories for discrete feature
            "split_points": list[float], # left-open right-close split points
            "total_counts": list[int], # total samples count in each bins.
            "else_counts": int, # np.nan samples count
            "woes": list[float], # woe values for each bins.
            "else_woe": float, # woe value for np.nan samples.
            "ivs": list[float], # iv values for each bins.
            "else_iv": float, # iv value for np.nan samples.
        },
        # ... others feature
    ]
}
'''
reveal
print('ivs sum :',sf.reveal(sumIvs))

**Comment by SZU-czw** [comment]
明天上班的时候可以帮我看看吗？我取某一个特征的ivs方式可能是错误的操作。
import secretflow as sf
import numpy as np
 In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], address='local')
alice = sf.PYU('alice')
bob = sf.PYU('bob')

 woe binning use SPU or HEU device to protect label
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

 Only support binary classification label dataset for now.
 use linear dataset as example
from secretflow.utils.simulation.datasets import load_linear
vdf = load_linear(parts={alice: (1, 4), bob: (18, 22)})
print(f"orig ds in alice:\n {sf.reveal(vdf.partitions[alice].data)}")
print(f"orig ds in bob:\n {sf.reveal(vdf.partitions[bob].data)}")

from secretflow.preprocessing.binning.vert_woe_binning import VertWoeBinning

binning = VertWoeBinning(spu)
woe_rules = binning.binning(
    vdf,
    binning_method="quantile",
    bin_num=5,
    bin_names={alice: ["x1", "x2", "x3"], bob: ["x18", "x19", "x20"]},
    label_name="y",
)
'''
print(f"woe_rules for alice:\n {sf.reveal(woe_rules[alice])}")
print(f"woe_rules for bob:\n {sf.reveal(woe_rules[bob])}")

from secretflow.preprocessing.binning.vert_woe_substitution import VertWOESubstitution

woe_sub = VertWOESubstitution()
sub_data = woe_sub.substitution(vdf, woe_rules)

print(f"substituted ds in alice:\n {sf.reveal(sub_data.partitions[alice].data)}")
print(f"substituted ds in bob:\n {sf.reveal(sub_data.partitions[bob].data)}")
'''


 执行到到这里就会报错
def parse_rule(rule):
   your logic
  sum = np.sum(rule)
  return sum

取某一列特征并计算ivs然后对ivs求和
sumIvs=alice(parse_rule)(woe_rules[alice]['variables'][0]['ivs'])

woe_rules[alice] 返回的数据类型
''' 
{
    "variables":[
        {
            "name": str, # feature name
            "type": str, # "string" or "numeric", if feature is discrete or continuous
            "categories": list[str], # categories for discrete feature
            "split_points": list[float], # left-open right-close split points
            "total_counts": list[int], # total samples count in each bins.
            "else_counts": int, # np.nan samples count
            "woes": list[float], # woe values for each bins.
            "else_woe": float, # woe value for np.nan samples.
            "ivs": list[float], # iv values for each bins.
            "else_iv": float, # iv value for np.nan samples.
        },
        
    ]
}
'''
reveal
print('ivs sum :',sf.reveal(sumIvs))

**Comment by SZU-czw** [comment]
大佬，明天有空帮我看看哈。我的对ivs的操作估计是错误的。
import secretflow as sf
import numpy as np
 
sf.shutdown()

sf.init(['alice', 'bob'], address='local')
alice = sf.PYU('alice')
bob = sf.PYU('bob')


spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))


 
from secretflow.utils.simulation.datasets import load_linear
vdf = load_linear(parts={alice: (1, 4), bob: (18, 22)})
print(f"orig ds in alice:\n {sf.reveal(vdf.partitions[alice].data)}")
print(f"orig ds in bob:\n {sf.reveal(vdf.partitions[bob].data)}")

from secretflow.preprocessing.binning.vert_woe_binning import VertWoeBinning

binning = VertWoeBinning(spu)
woe_rules = binning.binning(
    vdf,
    binning_method="quantile",
    bin_num=5,
    bin_names={alice: ["x1", "x2", "x3"], bob: ["x18", "x19", "x20"]},
    label_name="y",
)



'''执行到到这里就会报错'''
def parse_rule(rule):
  sum = np.sum(rule)
  return sum

'''取某一列特征并计算ivs然后对ivs求和'''
sumIvs=alice(parse_rule)(woe_rules[alice]['variables'][0]['ivs'])


''' 
woe_rules[alice] return data type as follow
{
    "variables":[
        {
            "name": str, # feature name
            "type": str, # "string" or "numeric", if feature is discrete or continuous
            "categories": list[str], # categories for discrete feature
            "split_points": list[float], # left-open right-close split points
            "total_counts": list[int], # total samples count in each bins.
            "else_counts": int, # np.nan samples count
            "woes": list[float], # woe values for each bins.
            "else_woe": float, # woe value for np.nan samples.
            "ivs": list[float], # iv values for each bins.
            "else_iv": float, # iv value for np.nan samples.
        },
        # ... others feature
    ]
}
'''

print('ivs sum :',sf.reveal(sumIvs))

**Comment by 6fj** [comment]
改成：
```
def parse_rule(rule):
  sum = np.sum(rule['variables'][0]['ivs'])
  return sum

sumIvs=alice(parse_rule)(woe_rules[alice])
```
试试呢

**Comment by SZU-czw** [comment]
方案可行，大佬牛逼
