### ISSUE TITLE
最新镜像secretflow/secretflow-anolis8:0.7.18b3，按照文档构建隐语环境报错

### ISSUE THREAD

**Issue by chaogaofeng** [secretflow/secretflow#355]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/23396178/223310626-66b6df51-957f-497e-b1a8-89d4157d7773.png">

**Comment by Chrisdehe** [comment]
hi，[chaogaofeng](https://github.com/chaogaofeng)
目前的信息不能够使我快速定位问题，您可以将整体的部署过程发出来吗？
另外，我想给您一些注意事项，希望可以帮助到您：
1、Ray、RayFed、SPU三者之间保证port不冲突，没有被占用。
2、如果你想用仿真模式，则不需要填cluster_config
sf.init(parties=['alice', 'bob'], address='sf-1-secretflow:8000 ')；
如果你想用多ray集群模式（生产模式），则不要填parties参数。填了parties表示仿真模式。
sf.init(address='sf-1-secretflow:8000 ', cluster_config=cluster_config)；
3、如果在生产模式下，需要参与方都同时跑代码，这里代码是指所有的代码。

**Comment by chaogaofeng** [comment]
启动了三个容器，一个ray head，两个ray worker。ray status显示ray网络有三个节点。ray start时，并没有指定resource参数。
容器sf-secretflow:     ray start --head --node-ip-address 0.0.0.0 --include-dashboard=False --disable-usage-stats
容器sf-1-secretflow:  ray start --address sf-secretflow:6379 --node-ip-address 0.0.0.0 --disable-usage-stats
容器sf-2-secretflow:  ray start --address sf-secretflow:6379 --node-ip-address 0.0.0.0 --disable-usage-stats

想通过cluster_config初始环境sf.init， 从报错信息看是init没有定义cluster_config参数。而且worker.py 是最新镜像才有的文件

**Comment by Chrisdehe** [comment]
请问您是在做集群仿真还是生产模式？
这里可以多解释一下，生产模式下，每个机构（容器）都是独立的ray集群，Ray集群不对外部机构暴露，所以访问ray集群其实是机构内部的网络。跨机构的通信是通过rayfed进行的。

**Comment by chaogaofeng** [comment]
集群仿真环境，想通过cluster_config 定义隐语环境

**Comment by Chrisdehe** [comment]
如果你想用仿真模式，则不需要填cluster_config
sf.init(parties=['alice', 'bob'], address='sf-1-secretflow:8000 ')；
如果你想用多ray集群模式（生产模式），则不要填parties参数。填了parties表示仿真模式。
sf.init(address='sf-1-secretflow:8000 ', cluster_config=cluster_config)；
两种模式不能混用，可参考https://github.com/secretflow/secretflow/issues/348

**Comment by zhouaihui** [comment]
> 集群仿真环境，想通过cluster_config 定义隐语环境

如果你希望使用仿真集群，建议阅读[集群仿真](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#cluster-mode-for-simulation)
