### ISSUE TITLE
SecretFlow隐语RGB图像加载问题

### ISSUE THREAD

**Issue by Wangxu930123** [secretflow/secretflow#358]
### Issue Type

Documentation Feature Request

### Source

source

### Secretflow Version

secretflow-main

### OS Platform and Distribution

centos7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
SecretFlow的Dataloader仅定义了几个官方数据集，对于RGB图像加载支持不友好，能否以RGB图像为例，提供一个可以自定义数据集的范例
```

### Reproduction code to reproduce the issue.

```shell
SecretFlow的Dataloader仅定义了几个官方数据集，对于RGB图像加载支持不友好，能否以RGB图像为例，提供一个可以自定义数据集的范例
```

**Comment by songyueran** [comment]
我也是群里同样的问题，SecretFlow的Dataloader仅定义了几个官方数据集，在拆分学习场景下只定义了csv数据集和图数据集。对于RGB图像加载支持不友好，能否以RGB图像为例，提供一个可以自定义数据集的范例。

**Comment by Wangxu930123** [comment]
下面这段代码报错“RuntimeError: expected scalar type Long but found Float”，能否帮忙定位一下相关问题。

#为适配NCHW，N=total num的图像，修改了create_ndarray代码
def create_ndarray(
    source: Union[str, np.ndarray, Callable],
    parts: Union[List[PYU], Dict[PYU, Union[float, tuple]]],
    axis: int = 0,
    shuffle: bool = False,
    random_state: int = None,
    allow_pickle: bool = False,
) -> FedNdarray:

    assert parts, 'Parts should not be none or empty!'

    if isinstance(source, str):
        arr = np.load(source, allow_pickle=allow_pickle)
    elif isinstance(source, np.ndarray):
        arr = source
        print("ori_arr_type: ", arr.dtype)
        print("ori_arr_shape: ", arr.shape)
    elif isinstance(source, Callable):
        arr = source()
        assert isinstance(
            arr, np.ndarray
        ), f'Callable source must return a ndarray but got {type(arr)}'
    else:
        raise InvalidArgumentError(
            f'Unknown source type, expect a file or ndarray or callable but got {type(source)}'
        )

    if shuffle:
        arr = np.random.default_rng(random_state).shuffle(arr)

    total_num = arr.shape[0] if axis == 0 else arr.shape[1]
    print("total_num: ", total_num)
    assert total_num >= len(
        parts
    ), f'Total samples/columns {total_num} is less than parts number {len(parts)}.'

    indexes = cal_indexes(parts=parts, total_num=total_num)
    print("indexes: ", indexes)
    for device, index in indexes.items():
        device: device(lambda df: df[index[0]: index[1]])(arr)
        feature = arr[index[0]: index[1]]
        print("device: ", device)
        print("feature_shape: ", feature.shape)
        print("feature_type: ", feature.dtype)

    if axis == 0:
        return FedNdarray(
            partitions={
                device: device(lambda df: df[index[0] : index[1]])(arr)
                for device, index in indexes.items()
            },
            partition_way=PartitionWay.HORIZONTAL,
        )

    else:
        return FedNdarray(
            partitions={
                device: device(lambda df: df[:, index[0] : index[1]])(arr)
                for device, index in indexes.items()
            },
            partition_way=PartitionWay.VERTICAL,
        )


#由存放路径获取标签（我已将数据按label存放，上级目录为label）
def get_cls_label(file_path):
    label_dir, file_name = os.path.split(file_path)
    hospital_dir, label = os.path.split(label_dir)

    return label

#获取np.array数据及label
def RGBClsImage(srcpath):
    dataset = {"image": [], "label": []}
    for roots, dirs, files in os.walk(srcpath):
        for file in files:
            file_path = os.path.join(roots, file)
            label = int(get_cls_label(file_path))
            image = cv2.imread(file_path)
            image = cv2.resize(image, (32, 32))
            mean = np.array([0.485, 0.456, 0.406],
                            dtype=np.float).reshape(1, 1, 3)
            std = np.array([0.229, 0.224, 0.225],
                           dtype=np.float).reshape(1, 1, 3)
            img = (image.astype(np.float) / 255.)
            img = (img - mean) / std
            img = img.transpose(2, 0, 1)

            dataset['image'].append(img)
            dataset['label'].append(label)
    dataset['label'] = np.array((dataset['label'])).astype(np.float)

    return dataset

if __name__ == "__main__":
# 加载数据，np.array转换为FedNdarray
    srcpath_train = "/home/wangx/data/02_Haemocytes/01_a"
    srcpath_test = "/home/wangx/data/02_Haemocytes/02_b"
    dataset_train = RGBClsImage(srcpath_train)
    dataset_test = RGBClsImage(srcpath_test)
    x_train = np.array(dataset_train['image'])
    y_train = np.array(dataset_train['label'])
    x_test = np.array(dataset_test['image'])
    y_test = np.array(dataset_test['label'])

    sf.init(['alice', 'bob', 'charlie'], address='local')
    alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')

#数据适配在上面重写修改了create_ndarray
    x_train = create_ndarray(x_train, parts={alice: 0.4, bob: 0.6}, axis=0, shuffle=False)
    y_train = create_ndarray(y_train, parts={alice: 0.4, bob: 0.6}, axis=0, shuffle=False)
    x_test = create_ndarray(x_test, parts={alice: 0.4, bob: 0.6}, axis=0, shuffle=False)
    y_test = create_ndarray(y_test, parts={alice: 0.4, bob: 0.6}, axis=0, shuffle=False)

#定义网络
    class Net(BaseModule):
        def __init__(self) -> None:
            super(Net, self).__init__()
            self.conv1 = nn.Conv2d(3, 6, 5)
            self.pool = nn.MaxPool2d(2, 2)
            self.conv2 = nn.Conv2d(6, 16, 5)
            self.fc1 = nn.Linear(16 * 5 * 5, 120)
            self.fc2 = nn.Linear(120, 84)
            self.fc3 = nn.Linear(84, 10)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            x = self.pool(F.relu(self.conv1(x)))
            x = self.pool(F.relu(self.conv2(x)))
            x = x.view(-1, 16 * 5 * 5)
            x = F.relu(self.fc1(x))
            x = F.relu(self.fc2(x))
            x = self.fc3(x)
            return x

# 后面照搬secretFlow官方示例
    loss_fn = nn.CrossEntropyLoss
    optim_fn = optim_wrapper(optim.Adam, lr=1e-2)
    model_def = TorchModel(
        model_fn=Net,
        loss_fn=loss_fn,
        optim_fn=optim_fn,
        metrics=[
            metric_wrapper(Accuracy, num_classes=10, average='micro'),
            metric_wrapper(Precision, num_classes=10, average='micro'),
        ],
    )

    device_list = [alice, bob]
    server = charlie

    aggregator = SecureAggregator(server, [alice, bob])

    # spcify params
    fl_model = FLModel(
        server=server,
        device_list=device_list,
        model=model_def,
        aggregator=aggregator,
        strategy='fed_avg_w',  # fl strategy
        backend="torch",  # backend support ['tensorflow', 'torch']
    )

    history = fl_model.fit(
        x_train,
        y_train,
        validation_data=(x_test, y_test),
        epochs=20,
        batch_size=32,
        aggregate_freq=1,
    )

**Comment by zhangxingmeng** [comment]
hi，我看了你的报错，这里大概率的问题是，你把label也转成了float，pytorch不支持float类型的label，你这里需要手动将label转成np.int64

**Comment by Wangxu930123** [comment]
> 
框架里面要求的l数据类型一致不是data和label一致啊

**Comment by Wangxu930123** [comment]
> hi，我看了你的报错，这里大概率的问题是，你把label也转成了float，pytorch不支持float类型的label，你这里需要手动将label转成np.int64

label转成np.int64之后出现相同的问题，而且你们官方load_mnist由create_ndarray函数将label转FedNdarray的过程中也是float64类型的label
![图片](https://user-images.githubusercontent.com/37038134/223608474-3b753959-e03e-4a47-97a1-28a58815e072.png)

**Comment by zhangxingmeng** [comment]
你把你的代码文件，和数据样例发一下吧，我在本地复现下

**Comment by Wangxu930123** [comment]
> 你把你的代码文件，和数据样例发一下吧，我在本地复现下

[06_SecretFlow.zip](https://github.com/secretflow/secretflow/files/10917147/06_SecretFlow.zip)

**Comment by songyueran** [comment]
好的，我用的代码是隐语的样例代码，数据集打算用Mnist与CIFAR10进行测试
&nbsp;


AD钙奶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 中午12:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [secretflow/secretflow] SecretFlow隐语RGB图像加载问题 (Issue #358)





  
你把你的代码文件，和数据样例发一下吧，我在本地复现下
  
06_SecretFlow.zip

**Comment by songyueran** [comment]
AD钙奶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "secretflow/secretflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [secretflow/secretflow] SecretFlow隐语RGB图像加载问题 (Issue #358)





  
你把你的代码文件，和数据样例发一下吧，我在本地复现下
  
06_SecretFlow.zip

**Comment by zhangxingmeng** [comment]
我先给出一个转成fedndarray的样例，可以不block你的流程.
其他用法可以看下过几天更新的tutorial

flower_dataset = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
下载解压后根目录存在 Root = "flower_photos"
```
import os, glob
import numpy as np
import cv2 #依赖需要自行安装 pip install opencv-python

root = 'flower_photos'
classes = ['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']
img_paths = []  # 保存所有图片路径
labels = []  # 保存图片的类别标签(0,1,2,3,4)
for i, label in enumerate(classes):
    cls_img_paths = glob.glob(os.path.join(root, label, "*.jpg"))
    img_paths.extend(cls_img_paths)
    labels.extend([i] * len(cls_img_paths))

# 图片->numpy
img_numpys = []
labels = np.array(labels)
for img_path in img_paths:
    img_numpy = cv2.imread(img_path)
    img_numpy = cv2.resize(img_numpy, (240, 240))
    img_numpy = np.reshape(img_numpy, (1, 240, 240, 3))
    # If use Pytorch backend dimension should be exchanged
    # img_numpy = np.transpose(img_numpy, (0,3,1,2))
    img_numpys.append(img_numpy)

images = np.concatenate(img_numpys, axis=0)
print(images.shape)  
print(labels.shape)  


# 给两个节点分配images和labels，各分配50%的数据
per=0.5
alice_images=images[:int(per*images.shape[0]),:,:,:]
alice_label=labels[:int(per*images.shape[0])]
bob_images=images[int(per*images.shape[0]):,:,:,:]
bob_label=labels[int(per*images.shape[0]):]
print(f"alice images shape = {alice_images.shape}, alice labels shape = {alice_label.shape}")  
print(f"bob images shape = {bob_images.shape}, bob labels shape = {bob_label.shape}")  

# 分别保存为npz，然后发送给两台机器
np.savez("flower_alice.npz",image=alice_images,label=alice_label)
np.savez("flower_bob.npz",image=bob_images,label=bob_label)

```


 # 怎样加载呢？
from secretflow.data.ndarray import load
fed_flower_npz = load({alice:"./flower_alice.npz",bob:"./flower_bob.npz"},allow_pickle=True)
image = fed_flower_npz["image"]
label = fed_flower_npz["label"]

**Comment by Wangxu930123** [comment]
> 我先给出一个转成fedndarray的样例，可以不block你的流程. 其他用法可以看下过几天更新的tutorial
> 
> flower_dataset = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz" 下载解压后根目录存在 Root = "flower_photos"
> 
> ```
> import os, glob
> import numpy as np
> import cv2 #依赖需要自行安装 pip install opencv-python
> 
> root = 'flower_photos'
> classes = ['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']
> img_paths = []  # 保存所有图片路径
> labels = []  # 保存图片的类别标签(0,1,2,3,4)
> for i, label in enumerate(classes):
>     cls_img_paths = glob.glob(os.path.join(root, label, "*.jpg"))
>     img_paths.extend(cls_img_paths)
>     labels.extend([i] * len(cls_img_paths))
> 
> # 图片->numpy
> img_numpys = []
> labels = np.array(labels)
> for img_path in img_paths:
>     img_numpy = cv2.imread(img_path)
>     img_numpy = cv2.resize(img_numpy, (240, 240))
>     img_numpy = np.reshape(img_numpy, (1, 240, 240, 3))
>     # If use Pytorch backend dimension should be exchanged
>     # img_numpy = np.transpose(img_numpy, (0,3,1,2))
>     img_numpys.append(img_numpy)
> 
> images = np.concatenate(img_numpys, axis=0)
> print(images.shape)  
> print(labels.shape)  
> 
> 
> # 给两个节点分配images和labels，各分配50%的数据
> per=0.5
> alice_images=images[:int(per*images.shape[0]),:,:,:]
> alice_label=labels[:int(per*images.shape[0])]
> bob_images=images[int(per*images.shape[0]):,:,:,:]
> bob_label=labels[int(per*images.shape[0]):]
> print(f"alice images shape = {alice_images.shape}, alice labels shape = {alice_label.shape}")  
> print(f"bob images shape = {bob_images.shape}, bob labels shape = {bob_label.shape}")  
> 
> # 分别保存为npz，然后发送给两台机器
> np.savez("flower_alice.npz",image=alice_images,label=alice_label)
> np.savez("flower_bob.npz",image=bob_images,label=bob_label)
> ```
> 
> # 怎样加载呢？
> 
> from secretflow.data.ndarray import load fed_flower_npz = load({alice:"./flower_alice.npz",bob:"./flower_bob.npz"},allow_pickle=True) image = fed_flower_npz["image"] label = fed_flower_npz["label"]

我这边用BaseMoudle定义VGG16测试仍出现该问题，能否提供一个继承自BaseModule可以跑通3通道RGB的网络
