### ISSUE TITLE
aggr = SecureAggregator(device=alice, participants=[alice, bob]) 无限期执行

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#36]
### Issue Type

Others

### Source

binary

### Secretflow Version

beta

### What happend and What you expected to happen.

```shell
按照官方文档的例子，执行到aggr = SecureAggregator(device=alice, participants=[alice, bob]) 之后，无限期执行下去，没有结果，请问怎么查找问题？
```

### Reproduction code to reproduce the issue.

```shell
按照官方文档的例子，执行到aggr = SecureAggregator(device=alice, participants=[alice, bob]) 之后，无限期执行下去，没有结果，请问怎么查找问题？
```

**Comment by zhouaihui** [comment]
请把复现的完整代码贴一下，以及日志等信息。另外，补充下你的具体secretflow具体版本号，以及OS信息。

**Comment by holdbelief** [comment]
> 请把复现的完整代码贴一下，以及日志等信息。另外，补充下你的secretflow具体版本号，以及OS信息。

我知道问题了，是虚拟机的cpu个数设置成1个导致的，我将虚机的cpu设置成8个，然后可以了
