### ISSUE TITLE
请问在隐语执行过程中是否可以强制关闭某个执行任务。

### ISSUE THREAD

**Issue by shifengbj** [secretflow/secretflow#363]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow/secretflow-anolis8:0.7.11b2

### OS Platform and Distribution

Ubuntu18

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
比如我在SPU执行PSI时或者我在做数据准备比如数据准备及统计时是否有命令或方法可以执行强制中断？
```

### Reproduction code to reproduce the issue.

```shell
比如我在SPU执行PSI时或者我在做数据准备比如数据准备及统计时是否有命令或方法可以执行强制中断？
```

**Comment by 6fj** [comment]
不太理解你说的强制执行是指什么？

如果是让程序停止的话，可以 Ctrl + C，为了保证所有进程被清除，可以执行
```
ray stop --force
```

**Comment by shifengbj** [comment]
我的意思是说比如我现在在一个工作流中， 这时实际运行在PYTHON中，举个例子，比如我执行下列代码：


    print('[1] to init sf server')
    newalice,newbob,spu = init_api.to_init()

    # data psi module
    print('[2] calulate PSI data from PART A & PART B')
    #psi_data = read_csv(psi_temp)
    psi_data = predata_api.to_psi('/root/alice_csv', '/root/bob_csv','uid', newalice, newbob, spu)  《 -- 比如在这里，用户可以主动触发强制中断PSI
    print(sf.reveal(psi_data.columns))

    print('[3] psi data statistic')
    statistic_status = predata_api.to_statistic(psi_data) 《 --或者用户在这里强制中断数据统计。
    print(statistic_status)

    print('[4] replace psi data')
    psi_data = predata_api.to_replace(psi_data, 'loan', 'no', 0)
    psi_data = predata_api.to_replace(psi_data, 'loan', 'yes', 1)
    psi_data = predata_api.to_replace(psi_data, 'loan','unknown', np.NaN)

    psi_data = predata_api.to_replace(psi_data, 'default', 'no', 0)

**Comment by shifengbj** [comment]
补充一下： 
第一种是说我直接强制关掉这个PYTHON进程，本身底层SF这块上下文环境或者数据是否能彻底清除？
第二种是说比如我在SPU执行PSI时，像这种操作是否有现成的CLOSE或者DESTORY函数可以直接把这个动作强制关掉？
