### ISSUE TITLE
跨机构构建SPU设备遇到了creation task的问题+跨机构grpc通信配置TLS遇到的问题

### ISSUE THREAD

**Issue by hanweidong** [secretflow/secretflow#364]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.18b3

### OS Platform and Distribution

CentOS Linux release 7.7.1908 (Core)

### Python version

3.8

### What happend and What you expected to happen.

```shell
构建SPU时遇到的问题：
2023-03-10 10:35:53 INFO fed.api [alice] --  Shutdowned ray.
2023-03-10 10:35:53,554	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.3.70.138:9800...
2023-03-10 10:35:53,559	INFO worker.py:1538 -- Connected to Ray cluster.
2023-03-10 10:35:54 INFO fed.barriers [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=11144, ip=10.3.70.140) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-03-10 10:35:55 INFO fed.barriers [alice] --  SendProxy was successfully created.
(SPURuntime pid=14973) 2023-03-10 10:36:07,828	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=14973, ip=10.3.70.138, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f13307be7c0>)
(SPURuntime pid=14973)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=14973)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=14973) RuntimeError: what: 
(SPURuntime pid=14973) 	[external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=1
(SPURuntime pid=14973) stacktrace: 
(SPURuntime pid=14973) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f13407c5519
(SPURuntime pid=14973) #1 pybind11::cpp_function::dispatcher()+0x7f13407afc5b
(SPURuntime pid=14973) #2 PyCFunction_Call+0x55b2bbf2bf8e


配置TLS时遇到的问题：
2023-03-10 10:47:12 INFO fed.api [alice] --  Shutdowned ray.
2023-03-10 10:47:12,815	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.3.70.138:9800...
2023-03-10 10:47:12,820	INFO worker.py:1538 -- Connected to Ray cluster.
2023-03-10 10:47:13 INFO fed.barriers [alice] --  RecverProxy was successfully created.
2023-03-10 10:47:13,838	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RecverProxyActor.run_grpc_server() (pid=17414, ip=10.3.70.140, repr=<fed.barriers.RecverProxyActor object at 0x7fc8a406f2b0>)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/fed/barriers.py", line 249, in run_grpc_server
    return await _run_grpc_server(
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/fed/barriers.py", line 98, in _run_grpc_server
    ca_cert, private_key, cert_chain = fed_utils.load_server_certs(tls_config)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/fed/utils.py", line 119, in load_server_certs
    return _load_from_cert_config(server_cert_config)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/fed/utils.py", line 103, in _load_from_cert_config
    private_key_file = cert_config["key"]
TypeError: string indices must be integers
2023-03-10 10:47:14 INFO fed.barriers [alice] --  SendProxy was successfully created.
```

### Reproduction code to reproduce the issue.

```shell
import spu
import secretflow as sf
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.3.70.138:9300',
            'listen_addr': '0.0.0.0:9300'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.3.70.140:9400',
            'listen_addr': '0.0.0.0:9400'
        },
    },
    'self_party': 'alice'
}

# tls_config = {
#     "ca_cert": "ca root cert of other parites (e.g. bob)",
#     "cert": "server cert of alice in pem",
#     "key": "server key of alice in pem",
# }

# Use ray head adress please.
sf.init(address='10.3.70.138:9800', 
        cluster_config=cluster_config
)

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.3.70.138:9100',
            'listen_addr': '0.0.0.0:9100'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.3.70.140:9200',
            'listen_addr': '0.0.0.0:9200'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
```
```

**Comment by Chrisdehe** [comment]
您好，[hanweidong](https://github.com/hanweidong)
请问同样的代码在bob机器上执行了吗？
具体请参考[345](https://github.com/secretflow/secretflow/issues/345)

**Comment by zhouaihui** [comment]
hi @hanweidong ，你可以升级到0.7.18b4，修复了TLS配置问题。
另外，新的配置写法请注意查看部署说明文档 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#suggestions-for-production

**Comment by hanweidong** [comment]
> 您好，[hanweidong](https://github.com/hanweidong) 请问同样的代码在bob机器上执行了吗？ 具体请参考[345](https://github.com/secretflow/secretflow/issues/345)
你好，感谢回答，两份代码我在两边都执行了，但是仍提示无法初始化spu，我注意到还提示[error] [server.cpp:BRPC:969] Fail to listen 10.3.70.140:9200

Alice方代码是：
```
import spu
import secretflow as sf
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.3.70.138:9300',
            'listen_addr': '0.0.0.0:9300'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.3.70.140:9400',
            'listen_addr': '0.0.0.0:9400'
        },
    },
    'self_party': 'alice'
}

# Use ray head adress please.
sf.init(address='10.3.70.138:9800', 
        cluster_config=cluster_config
)

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.3.70.138:9100',
            'listen_addr': '0.0.0.0:9100'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.3.70.140:9200',
            'listen_addr': '0.0.0.0:9200'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
```
Bob方代码是：
```
import spu
import secretflow as sf
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.3.70.138:9300',
            'listen_addr': '0.0.0.0:9300'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.3.70.140:9400',
            'listen_addr': '0.0.0.0:9400'
        },
    },
    'self_party': 'bob'
}


# Use ray head adress please.
sf.init(address='10.3.70.138:9800', 
        cluster_config=cluster_config
)

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.3.70.138:9100',
            'listen_addr': '0.0.0.0:9100'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.3.70.140:9200',
            'listen_addr': '0.0.0.0:9200'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
```
完整的错误提示：
```
INFO:root:Run secretflow in production mode.
2023-03-10 13:44:07,366	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.3.70.138:9800...
2023-03-10 13:44:07,374	INFO worker.py:1538 -- Connected to Ray cluster.
2023-03-10 13:44:08 INFO barriers.py:331 [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=26195) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-03-10 13:44:10 INFO barriers.py:368 [alice] --  SendProxy was successfully created.
(SPURuntime pid=26557) 2023-03-10 13:44:12.601 [error] [server.cpp:BRPC:969] Fail to listen 10.3.70.140:9200
(SPURuntime pid=26557) 2023-03-10 13:44:12,624	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=26557, ip=10.3.70.138, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f53a1e32250>)
(SPURuntime pid=26557)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=26557)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=26557) RuntimeError: what: 
(SPURuntime pid=26557) 	[external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=26557) stacktrace: 
(SPURuntime pid=26557) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f53b2fdf0c1
(SPURuntime pid=26557) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f53b1e28510
(SPURuntime pid=26557) #2 pybind11::cpp_function::dispatcher()+0x7f53b1e12c5b
(SPURuntime pid=26557) #3 PyCFunction_Call+0x564c2d7c5f8e

```

**Comment by hanweidong** [comment]
> hi @hanweidong ，你可以升级到0.7.18b4，修复了TLS配置问题。 另外，新的配置写法请注意查看部署说明文档 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#suggestions-for-production

感谢你的回答，如果要配置TLS的话那我需要先去购买认证证书么

**Comment by Chrisdehe** [comment]
在您的Bob执行代码中，我发现了
sf.init(address='10.3.70.138:9800', cluster_config=cluster_config)
注意，这里填写的是bob的头节点地址，请不要填写成alice的。
配置方法请参阅[部署文档](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#production)

**Comment by hanweidong** [comment]
> 在您的Bob执行代码中，我发现了 sf.init(address='10.3.70.138:9800', cluster_config=cluster_config) 注意，这里填写的是bob的头节点地址，请不要填写成alice的。 配置方法请参阅[部署文档](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#production)

我发现了自己的问题，在跨机构部署时应该是每一方启动自己的ray集群。
另外我发现listen_addr参数是什么意思呢，它一定需要配置么

**Comment by Chrisdehe** [comment]
address 是告知 对方 访问自己 时使用的地址
listen_address 是自己 listen （自己）机器的地址
因为云上 listen 地址是自己租户机器的地址，和访问的（公网）地址是不同的，所以需要分开配置
PS: 以后我们可能会做一些优化来去掉 listen_address，祝您生活愉快

**Comment by hanweidong** [comment]
> address 是告知 对方 访问自己 时使用的地址 listen_address 是自己 listen （自己）机器的地址 因为云上 listen 地址是自己租户机器的地址，和访问的（公网）地址是不同的，所以需要分开配置 PS: 以后我们可能会做一些优化来去掉 listen_address，祝您生活愉快
感谢您的耐心回答。
那意味着我在两台物理机部署时，其实是不需要配置listen_address

**Comment by hanweidong** [comment]
> address 是告知 对方 访问自己 时使用的地址 listen_address 是自己 listen （自己）机器的地址 因为云上 listen 地址是自己租户机器的地址，和访问的（公网）地址是不同的，所以需要分开配置 PS: 以后我们可能会做一些优化来去掉 listen_address，祝您生活愉快

我发现bob端spu构建成功后（可以监听到spu的端口），但是过一阵又会提示Exception raised in creation task错误。这个问题在Alice端就没有发生。

**Comment by 6fj** [comment]
可以放一下详细的log吗？

**Comment by hanweidong** [comment]
你好，完整的日志是这样的：
```
(SPURuntime pid=28694) 2023-03-10 14:19:50,743	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=28694, ip=10.3.70.140, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f89c1269370>)
(SPURuntime pid=28694)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=28694)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=28694) RuntimeError: what: 
(SPURuntime pid=28694) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=connect_0
(SPURuntime pid=28694) stacktrace: 
(SPURuntime pid=28694) #0 yacl::link::Context::RecvInternal()+0x7f89d24896e2
(SPURuntime pid=28694) #1 yacl::link::Context::ConnectToMesh()+0x7f89d248b253
(SPURuntime pid=28694) #2 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f89d12c2519
(SPURuntime pid=28694) #3 pybind11::cpp_function::dispatcher()+0x7f89d12acc5b
(SPURuntime pid=28694) #4 PyCFunction_Call+0x55d3904eaf8e
```

**Comment by hanweidong** [comment]
我重启了下，过了几分钟再发现Alice和Bob的SPU都挂掉了。
Alice方的日志：
```
(SPURuntime pid=32627) 2023-03-10 14:28:43,388	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=32627, ip=10.3.70.138, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f71f520b2e0>)
(SPURuntime pid=32627)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=32627)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=32627) RuntimeError: what: 
(SPURuntime pid=32627) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=connect_1
(SPURuntime pid=32627) stacktrace: 
(SPURuntime pid=32627) #0 yacl::link::Context::RecvInternal()+0x7f72063c06e2
(SPURuntime pid=32627) #1 yacl::link::Context::ConnectToMesh()+0x7f72063c2253
(SPURuntime pid=32627) #2 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f72051f9519
(SPURuntime pid=32627) #3 pybind11::cpp_function::dispatcher()+0x7f72051e3c5b
(SPURuntime pid=32627) #4 PyCFunction_Call+0x55761a48df8e
```
Bob方的日志：
```
(SPURuntime pid=29342) 2023-03-10 14:31:02,157	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=29342, ip=10.3.70.140, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f29b40a3310>)
(SPURuntime pid=29342)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 282, in __init__
(SPURuntime pid=29342)     self.runtime = spu.Runtime(self.link, self.conf)
(SPURuntime pid=29342)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/spu/binding/api.py", line 37, in __init__
(SPURuntime pid=29342)     self._vm = _lib.RuntimeWrapper(link, config.SerializeToString())
(SPURuntime pid=29342) RuntimeError: what: 
(SPURuntime pid=29342) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=root:1:ALLGATHER
(SPURuntime pid=29342) stacktrace: 
(SPURuntime pid=29342) #0 yacl::link::Context::RecvInternal()+0x7f29c52c96e2
(SPURuntime pid=29342) #1 yacl::link::AllGatherImpl<>()+0x7f29c52c5415
(SPURuntime pid=29342) #2 yacl::link::AllGather()+0x7f29c52c57c4
(SPURuntime pid=29342) #3 spu::mpc::PrgState::PrgState()+0x7f29c5139f73
(SPURuntime pid=29342) #4 spu::mpc::makeSemi2kProtocol()+0x7f29c50d9403
(SPURuntime pid=29342) #5 spu::mpc::Factory::CreateCompute()+0x7f29c4e29d53
(SPURuntime pid=29342) #6 spu::HalContext::HalContext()+0x7f29c4e28963
(SPURuntime pid=29342) #7 spu::RuntimeWrapper::RuntimeWrapper()+0x7f29c410fbe6
(SPURuntime pid=29342) #8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f29c410ffda
(SPURuntime pid=29342) #9 pybind11::cpp_function::dispatcher()+0x7f29c40ecc5b
(SPURuntime pid=29342) #10 PyCFunction_Call+0x55fce8f43f8e
```

**Comment by Chrisdehe** [comment]
您可以升级到我们最新的0.7.18b4版本，这个问题应该就不会有了。

**Comment by hanweidong** [comment]
> 您可以升级到我们最新的0.7.18b4版本，这个问题应该就不会有了。

目前我的版本就是0.7.18b4哈

**Comment by hanweidong** [comment]
SPU初始化完成后，隐语有配置这种关闭SPU服务的策略么

**Comment by Chrisdehe** [comment]
您在两方的代码中加一个sf.shutdown()看看？

**Comment by zhouaihui** [comment]
> 我重启了下，过了几分钟再发现Alice和Bob的SPU都挂掉了。 Alice方的日志：
> 
> ```
> (SPURuntime pid=32627) 2023-03-10 14:28:43,388	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=32627, ip=10.3.70.138, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f71f520b2e0>)
> (SPURuntime pid=32627)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
> (SPURuntime pid=32627)     self.link = spu_link.create_brpc(desc, rank)
> (SPURuntime pid=32627) RuntimeError: what: 
> (SPURuntime pid=32627) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=connect_1
> (SPURuntime pid=32627) stacktrace: 
> (SPURuntime pid=32627) #0 yacl::link::Context::RecvInternal()+0x7f72063c06e2
> (SPURuntime pid=32627) #1 yacl::link::Context::ConnectToMesh()+0x7f72063c2253
> (SPURuntime pid=32627) #2 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f72051f9519
> (SPURuntime pid=32627) #3 pybind11::cpp_function::dispatcher()+0x7f72051e3c5b
> (SPURuntime pid=32627) #4 PyCFunction_Call+0x55761a48df8e
> ```
> 
> Bob方的日志：
> 
> ```
> (SPURuntime pid=29342) 2023-03-10 14:31:02,157	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=29342, ip=10.3.70.140, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f29b40a3310>)
> (SPURuntime pid=29342)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 282, in __init__
> (SPURuntime pid=29342)     self.runtime = spu.Runtime(self.link, self.conf)
> (SPURuntime pid=29342)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/spu/binding/api.py", line 37, in __init__
> (SPURuntime pid=29342)     self._vm = _lib.RuntimeWrapper(link, config.SerializeToString())
> (SPURuntime pid=29342) RuntimeError: what: 
> (SPURuntime pid=29342) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=root:1:ALLGATHER
> (SPURuntime pid=29342) stacktrace: 
> (SPURuntime pid=29342) #0 yacl::link::Context::RecvInternal()+0x7f29c52c96e2
> (SPURuntime pid=29342) #1 yacl::link::AllGatherImpl<>()+0x7f29c52c5415
> (SPURuntime pid=29342) #2 yacl::link::AllGather()+0x7f29c52c57c4
> (SPURuntime pid=29342) #3 spu::mpc::PrgState::PrgState()+0x7f29c5139f73
> (SPURuntime pid=29342) #4 spu::mpc::makeSemi2kProtocol()+0x7f29c50d9403
> (SPURuntime pid=29342) #5 spu::mpc::Factory::CreateCompute()+0x7f29c4e29d53
> (SPURuntime pid=29342) #6 spu::HalContext::HalContext()+0x7f29c4e28963
> (SPURuntime pid=29342) #7 spu::RuntimeWrapper::RuntimeWrapper()+0x7f29c410fbe6
> (SPURuntime pid=29342) #8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f29c410ffda
> (SPURuntime pid=29342) #9 pybind11::cpp_function::dispatcher()+0x7f29c40ecc5b
> (SPURuntime pid=29342) #10 PyCFunction_Call+0x55fce8f43f8e
> ```

生产模式SPU需要多方同时启动，如果时差过大，会导致连接失败。
可以设置连接参数，参考 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#how-to-setup-spu-for-production

**Comment by hanweidong** [comment]
> > 我重启了下，过了几分钟再发现Alice和Bob的SPU都挂掉了。 Alice方的日志：
> > ```
> > (SPURuntime pid=32627) 2023-03-10 14:28:43,388	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=32627, ip=10.3.70.138, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f71f520b2e0>)
> > (SPURuntime pid=32627)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
> > (SPURuntime pid=32627)     self.link = spu_link.create_brpc(desc, rank)
> > (SPURuntime pid=32627) RuntimeError: what: 
> > (SPURuntime pid=32627) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=connect_1
> > (SPURuntime pid=32627) stacktrace: 
> > (SPURuntime pid=32627) #0 yacl::link::Context::RecvInternal()+0x7f72063c06e2
> > (SPURuntime pid=32627) #1 yacl::link::Context::ConnectToMesh()+0x7f72063c2253
> > (SPURuntime pid=32627) #2 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f72051f9519
> > (SPURuntime pid=32627) #3 pybind11::cpp_function::dispatcher()+0x7f72051e3c5b
> > (SPURuntime pid=32627) #4 PyCFunction_Call+0x55761a48df8e
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Bob方的日志：
> > ```
> > (SPURuntime pid=29342) 2023-03-10 14:31:02,157	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=29342, ip=10.3.70.140, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f29b40a3310>)
> > (SPURuntime pid=29342)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 282, in __init__
> > (SPURuntime pid=29342)     self.runtime = spu.Runtime(self.link, self.conf)
> > (SPURuntime pid=29342)   File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/spu/binding/api.py", line 37, in __init__
> > (SPURuntime pid=29342)     self._vm = _lib.RuntimeWrapper(link, config.SerializeToString())
> > (SPURuntime pid=29342) RuntimeError: what: 
> > (SPURuntime pid=29342) 	[external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=root:1:ALLGATHER
> > (SPURuntime pid=29342) stacktrace: 
> > (SPURuntime pid=29342) #0 yacl::link::Context::RecvInternal()+0x7f29c52c96e2
> > (SPURuntime pid=29342) #1 yacl::link::AllGatherImpl<>()+0x7f29c52c5415
> > (SPURuntime pid=29342) #2 yacl::link::AllGather()+0x7f29c52c57c4
> > (SPURuntime pid=29342) #3 spu::mpc::PrgState::PrgState()+0x7f29c5139f73
> > (SPURuntime pid=29342) #4 spu::mpc::makeSemi2kProtocol()+0x7f29c50d9403
> > (SPURuntime pid=29342) #5 spu::mpc::Factory::CreateCompute()+0x7f29c4e29d53
> > (SPURuntime pid=29342) #6 spu::HalContext::HalContext()+0x7f29c4e28963
> > (SPURuntime pid=29342) #7 spu::RuntimeWrapper::RuntimeWrapper()+0x7f29c410fbe6
> > (SPURuntime pid=29342) #8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f29c410ffda
> > (SPURuntime pid=29342) #9 pybind11::cpp_function::dispatcher()+0x7f29c40ecc5b
> > (SPURuntime pid=29342) #10 PyCFunction_Call+0x55fce8f43f8e
> > ```
> 
> 生产模式SPU需要多方同时启动，如果时差过大，会导致连接失败。 可以设置连接参数，参考 https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#how-to-setup-spu-for-production

感谢您的耐心回答，我的问题目前看是解决啦
