### ISSUE TITLE
隐语框架是否支持基于ABY2.0协议的神经网络训练？

### ISSUE THREAD

**Issue by Stu-Yang** [secretflow/secretflow#367]
[ABY2.0](https://eprint.iacr.org/2020/1225)是一个高效的两方安全计算协议，其支持神经网络模型训练，想问一下隐语框架是否支持基于ABY2.0协议的神经网络训练？

**Comment by icavan** [comment]
如果有人贡献了 ABY 2.0 到 SPU 里的话，理论上是支持的（包括其他应用， SS-XGB 、 LR 等）。

但是 ABY 2.0 的设定是抗一方恶意的，因此理论会比 ABY3 的半诚实方案更慢，只是会比 ABY3 的抗一方恶意快（隐语目前给出的是 ABY3 的半诚实实现，没有提供抗一方恶意的实现）。

**Comment by Stu-Yang** [comment]
@icavan 感谢你的回复，目前主要是想在本地测试一下基于2PC的神经网络训练的时间和通信量，看到ABY2.0协议是目前比较好的一个方案，所以想看一下基于ABY2.0协议的神经网络训练。

不过，我也看到隐语框架支持ABY3（三方框架），想问一下能否基于ABY3测试一下基于2PC的神经网络训练的时间和通信量大小，还是说由于参与方不一致实际上没有可比性？

**Comment by icavan** [comment]
> @icavan 感谢你的回复，目前主要是想在本地测试一下基于2PC的神经网络训练的时间和通信量，看到ABY2.0协议是目前比较好的一个方案，所以想看一下基于ABY2.0协议的神经网络训练。
> 
> 不过，我也看到隐语框架支持ABY3（三方框架），想问一下能否基于ABY3测试一下基于2PC的神经网络训练的时间和通信量大小，还是说由于参与方不一致实际上没有可比性？

2PC 天然难度比较大，耗时一般是 honest majority 协议（如 ABY3）的一个数量级以上，也因此被认为在数据规模大到一定程度的时候，落地上存在明显困难，会优先在 LR 等简单应用上先实践。

方便确认下您这边是技术上的研究，还是希望用到业务上？

如果确实希望是纯两方协议去跑，可以先试试 Cheetah 协议，Cheetah 目前估计是市面上开源最快的 2PC 了。

**Comment by Stu-Yang** [comment]
@icavan 你好，我现在还是学生，主要是进行技术研究，目前正在研究基于2PC的神经网络训练和预测。

我也关注到了[OpenCheetah](https://github.com/Alibaba-Gemini-Lab/OpenCheetah)，目前也有考虑基于[OpenCheetah](https://github.com/Alibaba-Gemini-Lab/OpenCheetah)进行开发，但是我看到其关注神经网络模型推理，而我也还需要关注**基于2PC的神经网络训练**，因此也想咨询一下隐语框架下是否能够进行神经网络训练？

**Comment by icavan** [comment]
> 

好的，可以用隐语做纯密态的 2PC 神经网络的训练

**Comment by Stu-Yang** [comment]
好的，十分感谢你的回答！
