### ISSUE TITLE
生产模式下的拆分XGB如何定义aby3_cluster

### ISSUE THREAD

**Issue by hanweidong** [secretflow/secretflow#371]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.18b4

### OS Platform and Distribution

CentOS Linux release 7.7.1908 (Core)

### Python version

3.8

### What happend and What you expected to happen.

```shell
你好，我目前在两台机器上搭建了生产模式的隐语，在执行vert_ss_xgb时，我发现官方提供的XGB需要使用ABY3协议，那是否意味着我需要在第三台机器搭建隐语。（目前我的场景是两方进行跨机构的拆分学习）
```

### Reproduction code to reproduce the issue.

```shell
def aby3_cluster():
    return {
        'nodes': [
            {
                'party': 'alice',
                'id': 'local:0',
                'address': f'127.0.0.1:{unused_tcp_port()}',
            },
            {
                'party': 'bob',
                'id': 'local:1',
                'address': f'127.0.0.1:{unused_tcp_port()}',
            },
            {
                'party': 'carol',
                'id': 'local:2',
                'address': f'127.0.0.1:{unused_tcp_port()}',
            },
        ],
        'runtime_config': {
            'protocol': spu.spu_pb2.ABY3,
            'field': spu.spu_pb2.FM64,
            'enable_pphlo_profile': False,
            'enable_hal_profile': False,
            'enable_pphlo_trace': False,
            'enable_action_trace': False,
        },
    }
```
```

**Comment by 6fj** [comment]
Hi @hanweidong 

如果你想使用ABY3协议，你需要搭建一个三方的secretflow cluster。
如果你只想搭建一个两方的集群，你需要将protocol设为 `spu.spu_pb2.SEMI2K` 或者 `spu.spu_pb2.CHEETAH`。

你可能需要关注不同协议的对比：https://www.secretflow.org.cn/docs/spu/en/reference/mpc_status.html

**Comment by hanweidong** [comment]
> Hi @hanweidong
> 
> 如果你想使用ABY3协议，你需要搭建一个三方的secretflow cluster。 如果你只想搭建一个两方的集群，你需要将protocol设为 `spu.spu_pb2.SEMI2K` 或者 `spu.spu_pb2.CHEETAH`。
> 
> 你可能需要关注不同协议的对比：https://www.secretflow.org.cn/docs/spu/en/reference/mpc_status.html

感谢你的回答，隐语的拆分XGB目前也是支持spu.spu_pb2.SEMI2K和spu.spu_pb2.CHEETAH协议的么？

**Comment by 6fj** [comment]
能发一下你看到的示例程序的链接吗？

**Comment by hanweidong** [comment]
你好，我在test_vert_ss_xgb.py中发现定义了xgb02 = Xgb([self.spu, self.spu02])。这里定义两个SPU的意义是什么呢

**Comment by hanweidong** [comment]
> 能发一下你看到的示例程序的链接吗？

你好，链接在这里：
https://github.com/secretflow/secretflow/blob/main/tests/ml/boost/ss_xgb_v/test_vert_ss_xgb.py

**Comment by 6fj** [comment]
你可以在这里更换spu的协议。

**Comment by 6fj** [comment]
> 你好，我在test_vert_ss_xgb.py中发现定义了xgb02 = Xgb([self.spu, self.spu02])。这里定义两个SPU的意义是什么呢

提供两个spu可以加快执行速度。

**Comment by hanweidong** [comment]
> 你可以在这里更换spu的协议。

好的，官方目前支持的三种SPU协议中，拆分XGB目前安全和效率最好的是哪个呢？
我看到关于Semi2k-SPDZ中提到'Hence, it should be used for debugging purposes only.'，这是说不建议在真实生产时使用么

**Comment by 6fj** [comment]
Semi2k-SPDZ暂时不建议在生产环境使用。
ABY3（三方）和Cheetah（两方）可以在生产环境使用，但是ABY3速度要比Cheetah要快。

**Comment by hanweidong** [comment]
> > 你好，我在test_vert_ss_xgb.py中发现定义了xgb02 = Xgb([self.spu, self.spu02])。这里定义两个SPU的意义是什么呢
> 
> 提供两个spu可以加快执行速度。

我看到这两个SPU的初始化配置都是一样的，有两个问题想请教下：
1、SPU数量的增加为什么可以会加快执行速度？
2、SPU数量的上限是和机构数量相关么？

**Comment by warriorpaw** [comment]
1、在树模型建模过程中，耗时最高的部分为分桶梯度求和，如果提供多组SPU，xgb组件会按样本维度分块并行这一计算，以达到加速效果。
树模型的算法细节，以及在mpc上如何完成树模型训练，请看下下面的文档：
https://www.secretflow.org.cn/docs/secretflow/en/components/mpc_ml/decision_tree.html

2、SPU上限和机构数无关，和机构提供的计算资源/带宽等能够并发多少计算有关。SPU是个虚拟设备，对应的在每个机构都有MPC计算节点，节点间通过MPC协议进行交互完成计算。多组SPU设备是每个机构都启动多组对等的MPC计算节点，这些节点在物理资源上可以是独立的互不影响的，可以并发进行不同的计算。关于SPU的基本概念，请看这个文档：
https://www.secretflow.org.cn/docs/spu/en/development/basic_concepts.html#

**Comment by hanweidong** [comment]
> Semi2k-SPDZ暂时不建议在生产环境使用。 ABY3（三方）和Cheetah（两方）可以在生产环境使用，但是ABY3速度要比Cheetah要快。

Semi2k协议不建议在生产环境使用的原因是因为协议有被恶意攻击的可能么，还是因为在数据交换就有一部分数据泄露的可能呢

**Comment by hanweidong** [comment]
> 1、在树模型建模过程中，耗时最高的部分为分桶梯度求和，如果提供多组SPU，xgb组件会按样本维度分块并行这一计算，以达到加速效果。 树模型的算法细节，以及在mpc上如何完成树模型训练，请看下下面的文档： https://www.secretflow.org.cn/docs/secretflow/en/components/mpc_ml/decision_tree.html
> 
> 2、SPU上限和机构数无关，和机构提供的计算资源/带宽等能够并发多少计算有关。SPU是个虚拟设备，对应的在每个机构都有MPC计算节点，节点间通过MPC协议进行交互完成计算。多组SPU设备是每个机构都启动多组对等的MPC计算节点，这些节点在物理资源上可以是独立的互不影响的，可以并发进行不同的计算。关于SPU的基本概念，请看这个文档： https://www.secretflow.org.cn/docs/spu/en/development/basic_concepts.html#

你好，假如我现在有两个机构进行拆分XGB，如果我还想用效率更高的ABY3协议，那两个机构必须协商找到一个可信的第三方搭建隐语么

**Comment by 6fj** [comment]
> > Semi2k-SPDZ暂时不建议在生产环境使用。 ABY3（三方）和Cheetah（两方）可以在生产环境使用，但是ABY3速度要比Cheetah要快。
> 
> Semi2k协议不建议在生产环境使用的原因是因为协议有被恶意攻击的可能么，还是因为在数据交换就有一部分数据泄露的可能呢

semi2k需要第三方作为beaver triple provider，默认的实现是进行运算的其中一方充当这个角色，因此是不安全的。生产环境下，必须让一个可信第三方做beaver triple provider。换句话说，可以用做生产的semi2k实际上是一个三方协议。

**Comment by 6fj** [comment]
> > 1、在树模型建模过程中，耗时最高的部分为分桶梯度求和，如果提供多组SPU，xgb组件会按样本维度分块并行这一计算，以达到加速效果。 树模型的算法细节，以及在mpc上如何完成树模型训练，请看下下面的文档： https://www.secretflow.org.cn/docs/secretflow/en/components/mpc_ml/decision_tree.html
> > 2、SPU上限和机构数无关，和机构提供的计算资源/带宽等能够并发多少计算有关。SPU是个虚拟设备，对应的在每个机构都有MPC计算节点，节点间通过MPC协议进行交互完成计算。多组SPU设备是每个机构都启动多组对等的MPC计算节点，这些节点在物理资源上可以是独立的互不影响的，可以并发进行不同的计算。关于SPU的基本概念，请看这个文档： https://www.secretflow.org.cn/docs/spu/en/development/basic_concepts.html#
> 
> 你好，假如我现在有两个机构进行拆分XGB，如果我还想用效率更高的ABY3协议，那两个机构必须协商找到一个可信的第三方搭建隐语么

是的。如果没有办法找到可信第三方，就只能使用cheetah协议。

**Comment by hanweidong** [comment]
> > > 1、在树模型建模过程中，耗时最高的部分为分桶梯度求和，如果提供多组SPU，xgb组件会按样本维度分块并行这一计算，以达到加速效果。 树模型的算法细节，以及在mpc上如何完成树模型训练，请看下下面的文档： https://www.secretflow.org.cn/docs/secretflow/en/components/mpc_ml/decision_tree.html
> > > 2、SPU上限和机构数无关，和机构提供的计算资源/带宽等能够并发多少计算有关。SPU是个虚拟设备，对应的在每个机构都有MPC计算节点，节点间通过MPC协议进行交互完成计算。多组SPU设备是每个机构都启动多组对等的MPC计算节点，这些节点在物理资源上可以是独立的互不影响的，可以并发进行不同的计算。关于SPU的基本概念，请看这个文档： https://www.secretflow.org.cn/docs/spu/en/development/basic_concepts.html#
> > 
> > 
> > 你好，假如我现在有两个机构进行拆分XGB，如果我还想用效率更高的ABY3协议，那两个机构必须协商找到一个可信的第三方搭建隐语么
> 
> 是的。如果没有办法找到可信第三方，就只能使用cheetah协议。

好的，感谢你的耐心回答。
