### ISSUE TITLE
关于PIR，PSI和隐语SQL的问题

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/secretflow#375]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 0.6.13b0

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
隐语的MPC SQL中的join和filter有用到PSI和PIR的技术吗，数据库中的连接和过滤操作和这两者有联系吗
```

### Reproduction code to reproduce the issue.

```shell
#
```

**Comment by CodeWilliamHuang** [comment]
我们的实现用到了 PSI 技术。
连接与过滤是独立操作，可以结合或独立使用。
更多细节，近期开源后欢迎关注。
