### ISSUE TITLE
关于在VM虚拟机中实现集群仿真模式时无法创建SPU

### ISSUE THREAD

**Issue by zhangjiahuang** [secretflow/secretflow#376]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 0.7.18b4

### OS Platform and Distribution

Linux centos 7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
两台centos7 VM虚拟机，网络通信正常，http协议正常，ray集群启动正常，spu无法创建。报错如下：
spu = sf.SPU(cluster_def=cluster_def)
>>> (SPURuntime pid=5651) 2023-03-19 19:58:36.611 [error] [server.cpp:BRPC:969] Fail to listen 192.168.0.10:9330
(SPURuntime pid=5651) 2023-03-19 19:58:36,624	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=5651, ip=192.168.0.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7eff9e5d22b0>)
(SPURuntime pid=5651)   File "/home/secretflow/miniconda3/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=5651)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=5651) RuntimeError: what: 
(SPURuntime pid=5651) 	[external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=5651) stacktrace: 
(SPURuntime pid=5651) #0 yacl::link::FactoryBrpc::CreateContext()+0x7effaf7a10c1
(SPURuntime pid=5651) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7effae5ea510
(SPURuntime pid=5651) #2 pybind11::cpp_function::dispatcher()+0x7effae5d4c5b
(SPURuntime pid=5651) #3 PyCFunction_Call+0x4e1172
(SPURuntime pid=3746, ip=192.168.0.20) 2023-03-19 19:58:36.721 [error] [server.cpp:BRPC:969] Fail to listen 192.168.0.20:9331
(SPURuntime pid=3746, ip=192.168.0.20) 2023-03-19 19:58:36,733	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=3746, ip=192.168.0.20, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f964335a370>)
(SPURuntime pid=3746, ip=192.168.0.20)   File "/home/secretflow/miniconda3/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=3746, ip=192.168.0.20)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=3746, ip=192.168.0.20) RuntimeError: what: 
(SPURuntime pid=3746, ip=192.168.0.20) 	[external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=3746, ip=192.168.0.20) stacktrace: 
(SPURuntime pid=3746, ip=192.168.0.20) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f965451c0c1
(SPURuntime pid=3746, ip=192.168.0.20) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9653365510
(SPURuntime pid=3746, ip=192.168.0.20) #2 pybind11::cpp_function::dispatcher()+0x7f965334fc5b
(SPURuntime pid=3746, ip=192.168.0.20) #3 PyCFunction_Call+0x4e1172
```

### Reproduction code to reproduce the issue.

```shell
测试代码：
import secretflow as sf
import spu
sf.shutdown()
sf.init(parties=['alice', 'bob'], address='192.168.0.10:9326')

alice = sf.PYU('alice')
bob = sf.PYU('bob')

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Please choose an unused port.
            'address': '192.168.0.10:9330',
            'listen_addr': '127.0.0.1:9330'
        },
        {
            'party': 'bob',
            'id': '1',
            # Please choose an unused port.
            'address': '192.168.0.20:9330',
            'listen_addr': '127.0.0.1:9330'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

spu = sf.SPU(cluster_def=cluster_def)
```

**Comment by miluoalbert** [comment]
日志中看起来是分别在`192.168.0.10:9330`和`192.168.0.20:9331`建立监听的过程中报错，请确认一下两台设备上这两个端口是否有报错

**Comment by zhangjiahuang** [comment]
> 日志中看起来是分别在`192.168.0.10:9330`和`192.168.0.20:9331`建立监听的过程中报错，请确认一下两台设备上这两个端口是否有报错

经测试，端口监听没有问题，切换不同端口后问题依然存在

**Comment by zhangjiahuang** [comment]
运行代码前端口未被占用，运行后端口情况如下：
tcp        0      0 192.168.0.10:9330       0.0.0.0:*               LISTEN      9364/ray::SPURuntim 
tcp        0      0 192.168.0.10:9330       192.168.0.20:48794      ESTABLISHED 9364/ray::SPURuntim

tcp        0      0 192.168.0.20:9331       0.0.0.0:*               LISTEN      9993/ray::SPURuntim 
tcp        0      0 192.168.0.20:9331       192.168.0.10:58188      ESTABLISHED 9993/ray::SPURuntim

**Comment by 6fj** [comment]
Hi @zhangjiahuang 

我们首先确认一下http协议是否可以联通

1 在alice这边建立一个http server
```
python -m http.server 9330
```
2 在bob这侧访问server,成功之后关闭alice的server
```
curl 192.168.0.10:9330
```
3 在bob这侧做同样的测试，确保192.168.0.20:9330可以在192.168.0.10这边可以被访问。

**Comment by 6fj** [comment]
另外
1. 你的cluster config里面没有9331这个端口啊
2. 如果你当前的模式是[集群模式仿真](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#cluster-mode-for-simulation), 那么**127.0.0.1**应该是**0.0.0.0**, cc @zhouaihui

**Comment by zhangjiahuang** [comment]
> Hi @zhangjiahuang
> 
> 我们首先确认一下http协议是否可以联通
> 
> 1 在alice这边建立一个http server
> 
> ```
> python -m http.server 9330
> ```
> 
> 2 在bob这侧访问server,成功之后关闭alice的server
> 
> ```
> curl 192.168.0.10:9330
> ```
> 
> 3 在bob这侧做同样的测试，确保192.168.0.20:9330可以在192.168.0.10这边可以被访问。

HTTP协议测试正常，cluster config参数经过多次测试，端口换过多个，127.0.0.1和0.0.0.0都测试过，都有问题

**Comment by 6fj** [comment]
请问你这边是如何测试http协议的呢？

**Comment by zhangjiahuang** [comment]
> 请问你这边是如何测试http协议的呢？

用您发的代码进行了测试

**Comment by 6fj** [comment]
可以尝试将spu的协议改成http吗？现在默认应该是baidu_std。
```
spu = sf.SPU(cluster_def=cluster_def,
                       link_desc={
                           "brpc_channel_protocol": "http",
                           "brpc_channel_connection_type": "pooled",
                       })
```

**Comment by zhangjiahuang** [comment]
> 可以尝试将spu的协议改成http吗？现在默认应该是baidu_std。
> 
> ```
> spu = sf.SPU(cluster_def=cluster_def,
>                        link_desc={
>                            "brpc_channel_protocol": "http",
>                            "brpc_channel_connection_type": "pooled",
>                        })
> ```

测试报错：（虚拟机系统时间没有同步(base) [secretflow@alice ~]$ date
Mon Mar 20 19:25:41 PDT 2023）
(SPURuntime pid=94269) 2023-03-20 19:24:25.720 [error] [server.cpp:BRPC:969] Fail to listen 192.168.0.10:9330
(SPURuntime pid=94269) 2023-03-20 19:24:25,736	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=94269, ip=192.168.0.10, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f55de9de250>)
(SPURuntime pid=94269)   File "/home/secretflow/miniconda3/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=94269)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=94269) RuntimeError: what: 
(SPURuntime pid=94269) 	[external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=94269) stacktrace: 
(SPURuntime pid=94269) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f55efbb70c1
(SPURuntime pid=94269) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f55eea00510
(SPURuntime pid=94269) #2 pybind11::cpp_function::dispatcher()+0x7f55ee9eac5b
(SPURuntime pid=94269) #3 PyCFunction_Call+0x4e1172
(SPURuntime pid=37067, ip=192.168.0.20) 2023-03-20 19:24:25.829 [error] [server.cpp:BRPC:969] Fail to listen 192.168.0.20:9331
(SPURuntime pid=37067, ip=192.168.0.20) 2023-03-20 19:24:25,866	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=37067, ip=192.168.0.20, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f19ea54d1f0>)
(SPURuntime pid=37067, ip=192.168.0.20)   File "/home/secretflow/miniconda3/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=37067, ip=192.168.0.20)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=37067, ip=192.168.0.20) RuntimeError: what: 
(SPURuntime pid=37067, ip=192.168.0.20) 	[external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=37067, ip=192.168.0.20) stacktrace: 
(SPURuntime pid=37067, ip=192.168.0.20) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f19fb70d0c1
(SPURuntime pid=37067, ip=192.168.0.20) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f19fa556510
(SPURuntime pid=37067, ip=192.168.0.20) #2 pybind11::cpp_function::dispatcher()+0x7f19fa540c5b
(SPURuntime pid=37067, ip=192.168.0.20) #3 PyCFunction_Call+0x4e1172

**Comment by zhangjiahuang** [comment]
集群仿真模式时，同一任务同一时间只能执行一次，执行不同任务需要用不同的端口，感谢各位老师答疑解惑!
