### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement spu==0.1.0b1 (from secretflow) (from versions: none)

### ISSUE THREAD

**Issue by licyclone** [secretflow/secretflow#38]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.6.13

### What happend and What you expected to happen.

```shell
你好。。pip install -U secretflow报错，需要怎么处理？
ERROR: Could not find a version that satisfies the requirement spu==0.1.0b1 (from secretflow) (from versions: none)
```

### Reproduction code to reproduce the issue.

```shell
ERROR: Could not find a version that satisfies the requirement spu==0.1.0b1 (from secretflow) (from versions: none)
```

**Comment by anakinxc** [comment]
麻烦提供一下 os 版本（包括 cpu 类型，比如 macOS 12.4 x64）以及 python 版本

**Comment by anakinxc** [comment]
试一下手动下载
https://files.pythonhosted.org/packages/ab/ee/5c8187728d4f55849256c63ef09375f168fdb0551c0c16eb2fc9b2a44dc6/spu-0.1.0.b1-cp38-cp38-manylinux_2_17_x86_64.whl
然后用 pip 安装

**Comment by licyclone** [comment]
pip install  spu-0.1.0.b1-cp38-cp38-manylinux_2_17_x86_64.whl
ERROR: spu-0.1.0.b1-cp38-cp38-manylinux_2_17_x86_64.whl is not a supported wheel on this platform.

**Comment by 6fj** [comment]
请问你的glibc版本是什么？

**Comment by licyclone** [comment]
> @licyclone 为了防止万一
> 
> `python3 -m pip install spu-0.1.0.b1-cp38-cp38-manylinux_2_17_x86_64.whl`

执行报同样错误。

**Comment by anakinxc** [comment]
pip 也更新一下试试？

`pip install -u pip`

**Comment by 6fj** [comment]
Hi @licyclone ,

If this still doesn't work for you, could you please use the offical docker image: https://github.com/secretflow/spu#docker.

Thanks.

**Comment by licyclone** [comment]
> 

th

> pip 也更新一下试试？
> 
> `pip install -u pip`
pip install -U pip 可以。pip从20升级到22.1.2即可。谢谢！

**Comment by licyclone** [comment]
> Hi @licyclone ,
> 
> If this still doesn't work for you, could you please use the offical docker image: https://github.com/secretflow/spu#docker.
> 
> Thanks.

谢谢！问题已解决，已安装成功，后续可以试一下。
