### ISSUE TITLE
隐语框架的模型存储与加载

### ISSUE THREAD

**Issue by hanweidong** [secretflow/secretflow#381]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.18b4

### OS Platform and Distribution

CentOS Linux release 7.7.1908 (Core)

### Python version

3.8

### What happend and What you expected to happen.

```shell
你好，我在使用隐语进行一个纵向联邦比赛，比赛中要求训练和预测阶段分开执行，这要求隐语支持模型的存储和加载。但是我发现隐语目前支持保存加载NN的模型，其他的（XGB、LR）都不支持。有一些过渡方案可以实现这部分功能么？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by icavan** [comment]
@warriorpaw  

Since most competitions require a separate AUC evaluation for the test dataset.

Please add the save/load support for LR/XGB models.

**Comment by hanweidong** [comment]
@6fj 你好，保存模型的需求隐语暂时还不能支持么？
比赛还有另外一个要求，需要根据两方的数据交互日志判断安全性，隐语目前的数据交互日志有导出的方式么

**Comment by 6fj** [comment]
@hanweidong 模型保存我们尚未支持。

日志交互的需求请另开一个issue，感谢！
