### ISSUE TITLE
可以多做一些布道交流活动吗？

### ISSUE THREAD

**Issue by yucongcong654** [secretflow/secretflow#387]
我看secretflow开源也有一段时间了，可以多办一些开发者交流活动吗？

**Comment by pchyuan** [comment]
> 

> 我看secretflow开源也有一段时间了，可以多办一些开发者交流活动吗？

您说的开发者交流活动是指什么样的？
目前隐语举办了meetup，同时和信通院合作多次介绍了隐语的技术实现思路的活动，本周六（3.25日）还有一个信通院的星河杯隐私计算比赛的"技术分享会"中隐语也会做介绍，欢迎关注。

**Comment by yucongcong654** [comment]
我看到了官网上3.29活动日历，没看到您说的3.25的活动，社区活动的发布渠道都是在官网或者公众号吗？我说的开发者活动，除了技术roadmap交流之外，希望也可以讨论一些社区治理与社区激励的话题，我看到官网也制定了相应的社区架构，希望不要荒废

**Comment by pchyuan** [comment]
> 我看到了官网上3.29活动日历，没看到您说的3.25的活动，社区活动的发布渠道都是在官网或者公众号吗？我说的开发者活动，除了技术roadmap交流之外，希望也可以讨论一些社区治理与社区激励的话题，我看到官网也制定了相应的社区架构，希望不要荒废

本周末的活动是隐私计算联盟发布的，可以在其公众号中查看相关信息。或查看参考：https://mp.weixin.qq.com/s/yUWKJeAB8Gpt1Qka2WGLzQ

社区活动可以通过公众号或者隐语小助手获取。

社区治理和社区激励的相关问题，也在设计中，欢迎提供好的建议。你可以添加下小助手微信号：SecretFlow01。

**Comment by yucongcong654** [comment]
好的，非常感谢，我添加了 @pchyuan
