### ISSUE TITLE
PYU问题

### ISSUE THREAD

**Issue by 472002463** [secretflow/secretflow#391]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.6.13

### OS Platform and Distribution

Ubuntu 18.4

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
Pyu我这边理解为是一个明文设备，但这个明文设备能够读取别人的PYUObject?

比如这里有alice 和bob 两个设备
alice,bob = sf.PYU('alice'),sf.PYU('bob')
spu = alice+bob
比如我这边用spu.psi_df求交后。返回一个长度为2的数组，分别为alice设备的PYUObject 和bob设备的PYUObject
我要将求交结果保存成某型形态比如csv或test，如下
def save_csv(data,filepath):
    print(data.data)
    data.to_csv(file)
#alice_pyu_data 、#bob_pyu_data是两个pyu设备读取的数据
psi_data = spu.psi_df(key=psi_key,dfs= [alice_pyu_data, bob_pyu_data],
                      receiver= 'alice',protocol='KKRT_PSI_2PC')

那么这里就是问题所在
alice(save_csv)(psi_data[0].data,'test.csv')
alice(save_csv)(psi_data[1].data,'test.csv')
好像都能保存到alice设备上，不应该psi_data[1]实在bob设备上吗，为啥alice能读取。
```

### Reproduction code to reproduce the issue.

```shell
------
```

**Comment by 6fj** [comment]
Hi @472002463 

隐语并不会处理数据权限，将会有其他模块和组件处理这些部分。

**Comment by 472002463** [comment]
> Hi @472002463
> 
> 隐语并不会处理数据权限，将会有其他模块和组件处理这些部分。

权限这一块是需要自己开发吗。
还是后续会有对应模块开源

**Comment by 472002463** [comment]
@6fj 
感谢回答。
那么请问下数据权限这块是需要自己去开发吗。
还是后续会有开源的模块直接插拔式接入

**Comment by 6fj** [comment]
Hi @472002463 

后续会有开源项目负责数据鉴权、发起隐语任务等功能。
secretflow（本repo）是隐语技术栈中的计算引擎，本身不会处理上述功能。
