### ISSUE TITLE
SCQL可以在secretflow中调用么？

### ISSUE THREAD

**Issue by martin2384798** [secretflow/secretflow#399]
还是我需要按照[Quickstart — SCQL  documentation](https://www.secretflow.org.cn/docs/scql/en/getting_started/quickstart.html)做docker-compose

**Comment by tongke6** [comment]
你好，目前还不能在 secretflow 中调用 SCQL。可以按照上面的 quickstart 文档尝试一下 ^_^

**Comment by martin2384798** [comment]
> 你好，目前还不能在 secretflow 中调用 SCQL。可以按照上面的 quickstart 文档尝试一下 ^_^

好的，我这边跑起来了。
SCQL在secretflow中的调用支持，有计划实现的时间节点可以告知么？

**Comment by jingshi-ant** [comment]
你好，感谢关注，目前暂无明确时间节点。
