### ISSUE TITLE
cluster模式下，启动ray失败

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#40]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

latest

### What happend and What you expected to happen.

```shell
按照官方的文档
《https://secretflow.readthedocs.io/en/latest/getting_started/deployment.html》

RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=1 \
RAY_TLS_SERVER_CERT=servercert.pem \
RAY_TLS_SERVER_KEY=serverkey.pem \
RAY_TLS_CA_CERT=cacert.pem \
ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats

192.168.137.4 6379是本机的redis的ip和port

执行ray start的时候抛出异常如下：


(yinyu) [root@alice secretflow_cluster]# ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 192.168.137.4
2022-07-14 07:02:52,453	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2022-07-14 07:03:08,419	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2022-07-14 07:05:37,765	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.


请问这是什么造成的呢？（redis确定是可以连接成功的）
```

### Reproduction code to reproduce the issue.

```shell
按照官方的文档
《https://secretflow.readthedocs.io/en/latest/getting_started/deployment.html》

RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=1 \
RAY_TLS_SERVER_CERT=servercert.pem \
RAY_TLS_SERVER_KEY=serverkey.pem \
RAY_TLS_CA_CERT=cacert.pem \
ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats

192.168.137.4 6379是本机的redis的ip和port

执行ray start的时候抛出异常如下：


(yinyu) [root@alice secretflow_cluster]# ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 192.168.137.4
2022-07-14 07:02:52,453	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2022-07-14 07:03:08,419	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2022-07-14 07:05:37,765	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.


请问这是什么造成的呢？（redis确定是可以连接成功的）
```

**Comment by longshan-ant** [comment]
是同一台机器上？ 以及如何连接redis的？

**Comment by holdbelief** [comment]
> 

是同一台机器，如何连接redis？如下：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=1 \
RAY_TLS_SERVER_CERT=servercert.pem \
RAY_TLS_SERVER_KEY=serverkey.pem \
RAY_TLS_CA_CERT=cacert.pem \
ray start --head **--node-ip-address="192.168.137.4" --port="6379"** --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats

使用命令行和其他工具连接redis都成功了

**Comment by holdbelief** [comment]
> 是同一台机器上？ 以及如何连接redis的？

是同一台机器，如何连接redis？如下：
RAY_DISABLE_REMOTE_CODE=true
RAY_SECURITY_CONFIG_PATH=config.yml
RAY_USE_TLS=1
RAY_TLS_SERVER_CERT=servercert.pem
RAY_TLS_SERVER_KEY=serverkey.pem
RAY_TLS_CA_CERT=cacert.pem
ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats

使用命令行和其他工具连接redis都成功了

**Comment by zhouaihui** [comment]
可以检查下ip是否正确（你填写的是192.168.137.4），以及端口号6379是否被占用（也可以换个端口）。

**Comment by wuxibin89** [comment]
可能是证书的问题，`servercert.pem`是由`cacert.pem`签发的自签证书吗？

**Comment by wuxibin89** [comment]
参考[这个教程](https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority/21340898)生成自签证书，尤其注意将`alternate_names`设置为主机IP地址，X509证书会对`Subject Alternative Name`进行校验。

**Comment by wuxibin89** [comment]
或者如果你只是测试的话，可以把mTLS双向认证关闭，即将`RAY_USE_TLS`设置为0

**Comment by holdbelief** [comment]
> 或者如果你只是测试的话，可以把mTLS双向认证关闭，即将`RAY_USE_TLS`设置为0

我确实将RAY_USE_TLS`设置为0了，但是不管用，感觉不像是证书的问题

**Comment by holdbelief** [comment]
> 参考[这个教程](https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority/21340898)生成自签证书，尤其注意将`alternate_names`设置为主机IP地址，X509证书会对`Subject Alternative Name`进行校验。

我将RAY_USE_TLS`设置为0，应该就不用证书了，

我最终这样成功了，但是整个过程中就没有使用redis，然后各种算法也成功了，但是让我感觉非常奇怪，我的ray的使用方法和教程不一样啊

在header node节点执行
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --head --node-ip-address="192.168.137.4" --port="7000" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats



在其他两个节点执行：
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --address="192.168.137.4:7000" --resources='{"bob": 8}' --disable-usage-stats

和
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=0 \
ray start --address="192.168.137.4:7000" --resources='{"charlie": 8}' --disable-usage-stats

**Comment by wuxibin89** [comment]
> 我最终这样成功了，但是整个过程中就没有使用redis，然后各种算法也成功了

redis是ray后端的GCS存储，作为用户不用关心。

> 如此使用ray成功倒是成功了，但是和官方的用法不一样

这里的不一样是指没有使用`redis_password`吧，如果你不指定的话，会使用默认的password
