### ISSUE TITLE
Bug about the 'to' method

### ISSUE THREAD

**Issue by MrCapricornLiu** [secretflow/secretflow#402]
### Issue Type

Bug

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
When using the 'to' method, the following error occurred.
```

### Reproduction code to reproduce the issue.

```shell
import numpy as np
import pandas as pd
import secretflow as sf
import tempfile
import os
from sklearn.datasets import load_iris
from secretflow.data.vertical import read_csv as v_read_csv

sf.shutdown()

sf.init(['alice', 'bob', 'carol'], address='local')
alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))

iris = load_iris(as_frame=True)
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

temp_dir = tempfile.mkdtemp()
v_alice, v_bob, v_carol = df.iloc[:100, :2], df.iloc[:100, 2:3], df.iloc[:100, 3:]
v_alice_path = os.path.join(temp_dir, 'v_alice.csv')
v_bob_path = os.path.join(temp_dir, 'v_bob.csv')
v_carol_path = os.path.join(temp_dir, 'v_carol.csv')
v_alice.to_csv(v_alice_path, index=False)
v_bob.to_csv(v_bob_path, index=False)
v_carol.to_csv(v_carol_path, index=False)

vdf = v_read_csv({alice: v_alice_path, bob: v_bob_path, carol: v_carol_path})

vdf.partitions[alice].to(self.spu)  # this is the line that fails


*****The following is the error message*****
$python justforissue.py 
INFO:root:Run secretflow in simulation mode.
2023-03-30 23:58:38,033 INFO worker.py:1538 -- Started a local Ray instance.
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    vdf.partitions[alice].to(self.spu)
AttributeError: 'Partition' object has no attribute 'to'
```

**Comment by ian-huu** [comment]
Partition is not a device object, you can use [Partition.data](https://www.secretflow.org.cn/docs/secretflow/en/source/secretflow.data.html#secretflow.data.base.Partition) instead:
`vdf.partitions[alice].data.to(self.spu)`

**Comment by MrCapricornLiu** [comment]
I want to design some other functions referencing the ml module of SecretFlow, so I followed the writing style of SSRegression in the ML module. In the process of one iteration in SSRegression, there is an operation like the following.(secretflow/ml/linear/ss_sgd/model.py,  line336)The x in this code is also Union[FedNdarray, VDataFrame] if I'm not mistaken.

spu_x = self.spu(_concatenate, static_argnames=('axis'))(
    [x.partitions[pyu].to(self.spu) for pyu in x.partitions], axis=1
)

**Comment by ian-huu** [comment]
Nice catch! I think it's a bug of ss_sgd. FedNdarray and VDataFrame have different APIs and need to be treated differently.
Currently you can use FedNdarray to implement your new functions. 

@zhouaihui @warriorpaw Or shall we and `to` for DataFrames?

**Comment by MrCapricornLiu** [comment]
Question solved, thx.
