### ISSUE TITLE
Handshake一直报错，请问怎么设置

### ISSUE THREAD

**Issue by hnjiakai** [secretflow/secretflow#408]
(SendProxyActor pid=38233) E0331 16:02:14.754179219   38347 ssl_transport_security.cc:1501] Handshake failed with fatal error SSL_ERROR_SSL: error:04000073:RSA routines:OPENSSL_internal:DATA_TOO_LARGE_FOR_MODULUS.
(SendProxyActor pid=38233) E0331 16:02:16.437539554   38347 ssl_transport_security.cc:1501] Handshake failed with fatal error SSL_ERROR_SSL: error:04000073:RSA routines:OPENSSL_internal:DATA_TOO_LARGE_FOR_MODULUS.
(SendProxyActor pid=38233) E0331 16:02:18.522677678   38347 ssl_transport_security.cc:1501] Handshake failed with fatal error SSL_ERROR_SSL: error:04000073:RSA routines:OPENSSL_internal:DATA_TOO_LARGE_FOR_MODULUS.

**Comment by hnjiakai** [comment]
tls_config = {
  "ca_cert": "ca root cert of other parites (e.g. bob)",  #对方的ca
  "cert": "server cert of alice in pem",
  "key": "server key of alice in pem",
}

ca_cert修改为对方的ca证书后不再报错

@miluoalbert  感谢大家的耐心指导 ：）

**Comment by oeqqwq** [comment]
> @miluoalbert 虽然戳openssl错误，但是却有psi结果，请问下这个过程计算时数据是否安全传输：）
> 
> (SPURuntime pid=101287) 2023-04-03 15:50:01.520 [info] [bucket_psi.cc:Run:216] End post filtering, in=.data/alice.csv, out=.data/alice_psi.csv
> 
> (SendProxyActor pid=101248) E0403 15:50:02.537831755 101360 ssl_transport_security.cc:1501] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.

@hnjiakai 
非常抱歉，由于文档同步错误，当前版本secretflow的并未开放SPU的TLS配置项。
secretflow计划会在下周有新的版本发布会包含这部份内容，烦请届时重试相关case

**Comment by hnjiakai** [comment]
> > tls_config = { "ca_cert": "ca root cert of other parites (e.g. bob)", #对方的ca "cert": "server cert of alice in pem", "key": "server key of alice in pem", }
> > ca_cert修改为对方的ca证书后不再报错
> > @miluoalbert 感谢大家的耐心指导 ：）
> 
> 好的，确认下最开始的`DATA_TOO_LARGE_FOR_MODULUS`这个报错是什么原因啊？ 我这里只复现了`BLOCK_TYPE_IS_NOT_01`这个报错

@miluoalbert  'DATA_TOO_LARGE_FOR_MODULUS'这个错误是两个条件，1、secretflow使用的是0.8.0b1以前的版本  2、tls_config 的 "ca_cert" 用的是自己的ca.crt，在这俩条件下，alice、bob（psi计算后） 一方会报BLOCK_TYPE_IS_NOT_01错误，另一方会报DATA_TOO_LARGE_FOR_MODULUS错误。 昨天用pip install -U secretflow升级后，secretflow为0.8.0b1，然后将tls_config 的 "ca_cert" 改成对方的ca.crt(alice用bob的ca.crt，bob用alice的ca.crt) 运行psi计算，不再报错。
secretflow为0.8.0b1+如下配置，psi计算不再报错
tls_config = {
    "ca_cert": other_party + "_certs/ca.crt", #对方ca证书
    "cert": self_party + "_certs/server.crt",
    "key": self_party + "_certs/server.key",
}

**Comment by miluoalbert** [comment]
好的，多谢补充！
