### ISSUE TITLE
拆分学习生产环境如何进行关联

### ISSUE THREAD

**Issue by zhaorui-ruiz** [secretflow/secretflow#409]
生产环境的拆分学习，如何保证不同数据源在安全的前提下进行关联。在示例中好像数据本身就是一一对应的。

**Comment by ian-huu** [comment]
一般会在训练之前先做一次 [隐私求交](https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/psi.html)，可以使用  [secretflow.data.vertical.read_csv](https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.data.vertical.html#secretflow.data.vertical.read_csv) 来加载数据，给 read_csv 传入一个 spu 后，内部会先做一次隐私求交
