### ISSUE TITLE
多个节点配置

### ISSUE THREAD

**Issue by humeng1832596901** [secretflow/secretflow#410]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

0.8.0.b1

### OS Platform and Distribution

Linux Centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
想咨询一下secretflow有没有类似服务发现的功能或者开发计划，在做三个节点隐私求交的时候发现每台机器都要去配置访问地址，那如果是在一些边缘计算场景节点数可能非常多，这个时候手动去配置似乎有点麻烦
```

### Reproduction code to reproduce the issue.

```shell
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': 'ip:port of alice',
            'listen_addr': '0.0.0.0:port'
        },
        'bob': {
            # replace with bob's real address.
            'address': 'ip:port of bob',
            'listen_addr': '0.0.0.0:port'
        },
    },
    'self_party': 'alice'
}
```

**Comment by warriorpaw** [comment]
这是个好问题，现阶段手写配置的确比较麻烦，后续我们会开源调度框架能够自动完成配置生成和下发。

然后，边缘计算是典型的弱网多设备场景，该场景下是不适合进行MPC计算的；如果使用联邦学习就是典型的 cross-device 联邦学习，目前隐语不支持。隐语支持的是cross-silo联邦。

**Comment by humeng1832596901** [comment]
好的，谢谢解答
