### ISSUE TITLE
应该考虑为隐语添加版本号__version__ 属性的支持

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#414]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow 0.8.0b1

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
对于Pypi包，通常可以通过package_name.__version 获得版本号的输出，比如numpy，pandas和PyTorch对于这些都做到了默认支持；
import numpy
import pandas
import torch
print('numpy version: ',numpy.__version__)
print('pandas version: ',pandas.__version__)
print('torch version: ',torch.__version__)

将获得输出
```
numpy version:  1.23.5
pandas version:  1.5.3
torch version:  2.0.0+cu117
```
但是目前隐语对这一基本属性却没有完善
运行代码：
```
import secretflow
print('secretflow version: ',secretflow.__version__)
```
将获得报错
```
Traceback (most recent call last):
  File "/home/limingbo/sf/src/version.py", line 14, in <module>
    print('secretflow version: ',secretflow.__version__)
AttributeError: module 'secretflow' has no attribute '__version__'
```
```

### Reproduction code to reproduce the issue.

```shell
import secretflow
print('secretflow version: ',secretflow.__version__)
```

**Comment by ian-huu** [comment]
Good suggestion, we will consider it.

**Comment by Mingbo-Lee** [comment]
You are welcome!

**Comment by anakinxc** [comment]
Hi @Mingbo-Lee 

To track this enhancement, I'll keep this issue open

Thanks

**Comment by Mingbo-Lee** [comment]
I just close the issue conveniently. I'm sorry  for the inconvenience. @anakinxc . I will follow your suggestion.
