### ISSUE TITLE
关于集群三节点下，中间输出了一些error日志，是怎么回事呢？

### ISSUE THREAD

**Issue by xiaoran33** [secretflow/secretflow#425]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.0b0

### OS Platform and Distribution

centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
以下是demo程序运转打印的日志：
INFO:root:Run secretflow in simulation mode.
2023-04-11 09:39:38,517 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 192.168.207.195:6379...
2023-04-11 09:39:38,531 INFO worker.py:1538 -- Connected to Ray cluster.
(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:49.593 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=192.168.207.195:6337} (0x0x3874640): Connection refused [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:41.431 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=192.168.207.195:6337} (0x0x4967c80): Connection refused [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(_run pid=27553) INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=27553) INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=27553) INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=27553) INFO:jax._src.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=27553) WARNING:jax._src.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=6464, ip=192.168.207.249) INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=6464, ip=192.168.207.249) INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=6464, ip=192.168.207.249) INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=6464, ip=192.168.207.249) INFO:jax._src.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=6464, ip=192.168.207.249) WARNING:jax._src.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
--------------------------------------------
obj: <secretflow.device.device.spu.SPUObject object at 0x7f45286084c0>
--------------------------------------------
(_run pid=25996, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=25996, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=25996, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=25996, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=25996, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=25996, ip=192.168.207.196) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:50.594 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:42.431 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:51.594 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:43.432 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:52.595 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:44.432 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
[10 12 10 12]
```

**Comment by anakinxc** [comment]
Hi @xiaoran33 

这些只是 jax 的 warning message 而已，可以直接忽略

**Comment by xiaoran33** [comment]
> Hi @xiaoran33
> 
> 这些只是 jax 的 warning message 而已，可以直接忽略

(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:50.594 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:42.431 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:51.594 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:43.432 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:52.595 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
(SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:44.432 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0

这种error的也是可以直接忽略的吗？

**Comment by anakinxc** [comment]
> > Hi @xiaoran33
> > 这些只是 jax 的 warning message 而已，可以直接忽略
> 
> (SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:50.594 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 (SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:42.431 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 (SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:51.594 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 (SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:43.432 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 (SPURuntime pid=6462, ip=192.168.207.249) 2023-04-11 09:42:52.595 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 (SPURuntime pid=25995, ip=192.168.207.196) 2023-04-11 09:39:44.432 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R1][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R2][E112]Not connected to 192.168.207.195:6337 yet, server_id=0 [R3][E112]Not connected to 192.168.207.195:6337 yet, server_id=0
> 
> 这种error的也是可以直接忽略的吗？

这些是节点A在连接到节点B失败的时候打出来的 message，但是 SPU 在连接失败以后会进行几次重试。如果一个节点拉起时间比较长，就会看到几个这样的 error message，但是如果最终连接成功了就可以忽略

这个 message 比较有误导性，我们也已经注意到了，会在下次更新的时候解决
