### ISSUE TITLE
提供一下水平逻辑回归建模方案

### ISSUE THREAD

**Issue by nainai123** [secretflow/secretflow#427]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

0.8.0b1

### OS Platform and Distribution

linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
文档更多的是两方垂直数据去建模。没看到水平数据去建模的例子，请问有水平数据逻辑回归  或决策树的例子吗
```

### Reproduction code to reproduce the issue.

```shell
目前只发现图像深度学习的例子
```

**Comment by Chrisdehe** [comment]
hi @nainai123 
这是官网的例子，请参考
https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/mpc_ml/index.html

**Comment by Mingbo-Lee** [comment]
Hi @nainai123 
水平联邦XGBoost，请参考：https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/federated_learning/horizontal_federated_learning/tree.html

**Comment by nainai123** [comment]
> 你好@nainai123 这是官网的例子，请参考 https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/mpc_ml/index.html

你好感谢你的回复，但是在这个例子中我在读取数据集的过程中发现了一个问题：
def get_data(path,train):   
    # x：iloc[:,1:-1]   y：iloc[:,-1:]
    from sklearn.preprocessing import StandardScaler
    import numpy as np
    data = pd.read_csv(path, encoding='utf-8')
    if train:
        data = data.iloc[:,1:-1]
        scaler = StandardScaler()
        x = scaler.fit_transform(data)
        return x
    else:
        data = data.iloc[:,-1:]
        y = np.array(data)
        return y

v_data = FedNdarray(### 
    partitions={
        np1: np1(get_data)(path='/root/data/train1.csv',train = True),
        np2: np2(get_data)(path='/root/data/train2.csv',train = True),
    },
    partition_way=PartitionWay.VERTICAL,
)



我原始数据集维度为(517, 9)

但是实际我得到的(259,18)

我想请问一下  隐语是否支持numpy  或pandas 的一些数据合并的函数如：np.vstack()  或者pd.mergr 这类的函数

**Comment by zhouaihui** [comment]
hi， @nainai123 
1. 你可以直接用代码在你的原始数据上运行一下，验证下结果，SF只是执行你写的代码。
2. 目前不支持。

**Comment by nainai123** [comment]
> hi， @nainai123
> 
> 1. 你可以直接用代码在你的原始数据上运行一下，验证下结果，SF只是执行你写的代码。
> 2. 目前不支持。

from secretflow.data import FedNdarray, PartitionWay
感谢您的回复  FedNdarray  函数的  partition_way 参数可以对数据读取的水平或垂直进行设置   目前问题解决

**Comment by nainai123** [comment]
`import sys
import time
import logging

import spu
import secretflow as sf
from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay
from secretflow.ml.linear.ss_sgd import SSRegression
import pandas as pd
from sklearn.metrics import roc_auc_score

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'np1', 'id': 'np1', 'address': '192.168.0.254:12945', 'listen_address': '0.0.0.0:12945'},
        {'party': 'np2', 'id': 'np2', 'address': '192.168.0.254:12946', 'listen_address': '0.0.0.0:12946'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
# init all nodes in local Standalone Mode.
sf.shutdown()
sf.init(['np1', 'np2'], address='192.168.0.254:9001',ignore_reinit_error=True)
np1 = sf.PYU('np1')
np2 = sf.PYU('np2')
spud = sf.SPU(cluster_def)

def get_data(path,train):
    # x：iloc[:,1:-1]   y：iloc[:,-1:]
    from sklearn.preprocessing import StandardScaler
    ##  二分类变量 不进行归一
    import numpy as np
    data = pd.read_csv(path, encoding='utf-8')
    if train:
        data = data.iloc[:,1:-1]
        scaler = StandardScaler()
        x = scaler.fit_transform(data)
        return x
    else:
        data = data.iloc[:,-1:]
        y = np.array(data)
        return y
v_data = FedNdarray(###  数据合并  HORIZONTAL
    partitions={
        np1: np1(get_data)(path='/root/data/train1.csv',train = True),
        np2: np2(get_data)(path='/root/data/train2.csv',train = True),
    },
    partition_way=PartitionWay.HORIZONTAL,
)
label_data = FedNdarray(###  y数据合并？？？？
    partitions={
        np1: np1(get_data)(path='/root/data/train1.csv',train = False),
        np2: np2(get_data)(path='/root/data/train2.csv',train = False),
    },
    partition_way=PartitionWay.HORIZONTAL,
)
wait([p.data for p in v_data.partitions.values()])
wait([p.data for p in label_data.partitions.values()])
# SSRegression use spu to fit model.
model = SSRegression(spud)
start = time.time()
model.fit(
    v_data,      # x
    label_data,  # y
    20,           # epochs
    0.3,         # learning_rate
    32,          # batch_size
    't1',        # sig_type
    'logistic',  # reg_type
    'l2',        # penalty
    0.1,         # l2_norm
)
`
报错原因
AssertionError                            Traceback (most recent call last)
Cell In[10], line 4
      2 model = SSRegression(spud)
      3 start = time.time()
----> 4 model.fit(
      5     v_data,      # x
      6     label_data,  # y
      7     20,           # epochs
      8     0.3,         # learning_rate
      9     32,          # batch_size
     10     't1',        # sig_type
     11     'logistic',  # reg_type
     12     'l2',        # penalty
     13     0.1,         # l2_norm
     14 )

File /usr/local/lib/python3.8/site-packages/secretflow/ml/linear/ss_sgd/model.py:408, in SSRegression.fit(self, x, y, epochs, learning_rate, batch_size, sig_type, reg_type, penalty, l2_norm)
    368 def fit(
    369     self,
    370     x: Union[FedNdarray, VDataFrame],
   (...)
    378     l2_norm: float = 0.5,
    379 ) -> None:
    380     """
    381     Fit the model according to the given training data.
    382 
   (...)
    406         Final weights in SPUObject.
    407     """
--> 408     self._pre_check(
    409         x,
    410         y,
    411         epochs,
    412         learning_rate,
    413         batch_size,
    414         sig_type,
    415         reg_type,
    416         penalty,
    417         l2_norm,
    418     )
    420     spu_w = self.spu(_init_w, static_argnames=('base', 'num_feat'))(
    421         base=0, num_feat=self.num_feat
    422     )
    424     self.batch_cache = {}

File /usr/local/lib/python3.8/site-packages/secretflow/ml/linear/ss_sgd/model.py:268, in SSRegression._pre_check(self, x, y, epochs, learning_rate, batch_size, sig_type, reg_type, penalty, l2_norm)
    250 def _pre_check(
    251     self,
    252     x: Union[FedNdarray, VDataFrame],
   (...)
    260     l2_norm: float,
    261 ):
    262     """
    263     Parameter validity check
    264 
    265     Args:
    266         see fit()
    267     """
--> 268     self.x, shape = self._prepare_dataset(x)
    269     self.samples, self.num_feat = shape
    270     assert self.samples > 0 and self.num_feat > 0, "input dataset is empty"

File /usr/local/lib/python3.8/site-packages/secretflow/ml/linear/ss_sgd/model.py:246, in SSRegression._prepare_dataset(self, ds)
    244 shapes = ds.partition_shape()
    245 assert len(shapes) > 0, "input dataset is empty"
--> 246 assert ds.partition_way == PartitionWay.VERTICAL
    248 return ds, ds.shape

AssertionError: 
数据读取方式改变就建模失败  能帮忙看一下问题吗

**Comment by warriorpaw** [comment]
SSRegression仅支持垂直切分数据集的训练，目前没有提供可以直接使用的水平切分LR。

可以参考下面的文档，通过FLMODEL构造水平LR：
https://www.secretflow.org.cn/docs/secretflow/zh_CN/components/federated_learning/horizontal_federated_learning/fl_model.html
