### ISSUE TITLE
调用PSI_CSV方法，传参报错「KeyError: 'id'」

### ISSUE THREAD

**Issue by minihu-crypto** [secretflow/secretflow#432]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.0b1

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
按照PSI_Benchmark的实例代码，通过 spu.psi_csv() 方法调用KKRT两方PSI，提示错误信息：KeyError:'id'

alice和bob节点分别运行在两台容器中（alice:192.168.10.11  bob: 192.168.10.12)
两台服务器通过ray连接，运行在simulation mode下

完整错误信息：
RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=172965, ip=192.168.10.11, repr=)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 272, in __init__
    desc.add_party(node['id'], node['listen_address'])
KeyError: 'id'
```

### Reproduction code to reproduce the issue.

```shell
input_path = {
    alice: '/alice/A_PSI.csv',
    bob: '/bob/B_PSI.csv'
}
select_keys = {
        alice: ['id'],
        bob: ['id'],
}
reports = dev.psi_csv(
    key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='KKRT_PSI_2PC',	# psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
)


// alice.psi
id
826847020227493888
438974841157058565
622726628847386633
...
```

**Comment by zhanglei486** [comment]
看报错信息的提示，应该是cluster_def的定义有问题，麻烦检查一下cluster_def的定义，或者贴到这里，一起看一下。

**Comment by minihu-crypto** [comment]
cluster_def = {
    'nodes': [
        {'party': 'alice', 'address': '192.168.10.11:10001', 'listen_address': '0.0.0.0:10001'},
        {'party': 'bob', 'address': '192.168.10.12:10002', 'listen_address': '0.0.0.0:10002'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

**Comment by Chrisdehe** [comment]
辛苦将执行代码贴的再完整一些

**Comment by minihu-crypto** [comment]
// 是直接参考PSI_Benchmark写的

alice = sf.PYU('alice')
bob = sf.PYU('bob')
input_path = {
    alice: '/alice/A_PSI.csv',
    bob: '/bob/B_PSI.csv'
}
output_path={
    alice: '/alice/psi_output.csv',
    bob: '/bob/psi_output.csv'
}
select_keys = {
        alice: ['id'],
        bob: ['id'],
}
cluster_def = {
    'nodes': [
        {'party': 'alice','address': '192.168.10.11:10001', 'listen_address': '0.0.0.0:10001'},
        {'party': 'bob', 'address': '192.168.10.12:10002', 'listen_address': '0.0.0.0:10002'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
dev = sf.SPU(cluster_def)
start = time.time()

reports = dev.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='KKRT_PSI_2PC',	# psi protocol
)
print(f"psi reports: {reports}")
print(f"cost time: {time.time() - start}")
sf.shutdown()

**Comment by zhanglei486** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/47308800/231672931-1afb0156-ee19-463e-ad2c-ceb6095bffae.png">
https://mp.weixin.qq.com/s/TvY4morH-dRsaCm5JI6eig
微信公众号里面cluster_def定义是有id定义的，麻烦再检查一下是否拷贝正确。

**Comment by minihu-crypto** [comment]
好的，谢谢。不过还有一个问题，按照这个教程，在sf.init的时候就会直接挂掉了，因为即没有提供parties，也没有提供cluster_config

**Comment by minihu-crypto** [comment]
我把init参数改成  sf.init(parties=['alice', 'bob'],address='192.168.10.11:10000')  才能够正常初始化（simulation mode）

前面的问题，我按照公众号的教程添加 'id': 'local:0' 和 'id': 'local:1' 以后，之前的错误已经解决，十分感谢。（官网中没有这两个参数，为了方便大家使用，麻烦更新一下官网教程）

**Comment by 6fj** [comment]
Hi @minihu-crypto 

可以升级一下secretflow到最新版吗：[v0.8.1b0](https://github.com/secretflow/secretflow/releases/tag/v0.8.1b0)

id在新的版本中已经不需要了，但是之前的secretflow是需要的。

**Comment by Chrisdehe** [comment]
您也可以关注我们的官网，尝试使用[其他用例](https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/index.html)来验证。
祝好！
