### ISSUE TITLE
> 请更新到最新版本，0.7.18b3 版本有一个调度的 bug 可能造成这个问题

### ISSUE THREAD

**Issue by likeIronic** [secretflow/secretflow#437]
> 请更新到最新版本，0.7.18b3 版本有一个调度的 bug 可能造成这个问题

在一台ubuntu 18.04 server进行单机仿真的时候，使用的secretflow 0.7.18不b3，也出现了同样的问题。请问你解决了嘛

_Originally posted by @likeIronic in https://github.com/secretflow/secretflow/issues/377#issuecomment-1507839118_

**Comment by 6fj** [comment]
那请问具体是哪个版本呢

**Comment by likeIronic** [comment]
> 那请问具体是哪个版本呢

secretflow 0.7.18b3

**Comment by 6fj** [comment]
@likeIronic 

烦请升级到最新的secretflow，如果bug仍然出现，请补充一下细节，感谢！

**Comment by likeIronic** [comment]
已解决
