### ISSUE TITLE
集群模式下，两方的ecdh psi求交出现如下错误

### ISSUE THREAD

**Issue by lvying0019** [secretflow/secretflow#449]
### Issue Type

Bug

### Source

binary

### Secretflow Version

最新版

### OS Platform and Distribution

anolis

### Python version

3.8

### What happend and What you expected to happen.

```shell
在集群模式下，两方的ecdh psi求交出现如下错误，bc22和kkrt可正常运行。
---------------------------------------------------------------------------
RayTaskError(RuntimeError)                Traceback (most recent call last)
Cell In[34], line 2
      1 start_time = time.time()
----> 2 spu_psi.psi_csv('id', input_path, output_path
      3                 , 'alice'
      4                 ,protocol='ECDH_PSI_2PC'
      5                 # ,broadcast_result=False
      6                )
      7 ecdh_comsume_time = time.time()-start_time
      8 ecdh_comsume_time

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py:1426, in SPU.psi_csv(self, key, input_path, output_path, receiver, protocol, precheck_input, sort, broadcast_result, bucket_size, curve_type, preprocess_path, ecdh_secret_key_path, dppsi_bob_sub_sampling, dppsi_epsilon)
   1381 def psi_csv(
   1382     self,
   1383     key: Union[str, List[str], Dict[Device, List[str]]],
   (...)
   1396     dppsi_epsilon=3,
   1397 ):
   1398     """Private set intersection with csv file.
   1399 
   1400     Args:
   (...)
   1423         List[Dict]: PSI reports output by SPU with order reserved.
   1424     """
-> 1426     return dispatch(
   1427         'psi_csv',
   1428         self,
   1429         key,
   1430         input_path,
   1431         output_path,
   1432         receiver,
   1433         protocol,
   1434         precheck_input,
   1435         sort,
   1436         broadcast_result,
   1437         bucket_size,
   1438         curve_type,
   1439         preprocess_path,
   1440         ecdh_secret_key_path,
   1441         dppsi_bob_sub_sampling,
   1442         dppsi_epsilon,
   1443     )

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py:111, in dispatch(name, self, *args, **kwargs)
    101 def dispatch(name: str, self, *args, **kwargs):
    102     """Dispatch device kernel.
    103 
    104     Args:
   (...)
    109         Kernel execution result.
    110     """
--> 111     return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py:80, in Registrar.dispatch(self, device_type, name, *args, **kwargs)
     78 if name not in self._ops[device_type]:
     79     raise KeyError(f'device: {device_type}, op: {name} not registered')
---> 80 return self._ops[device_type][name](*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/kernels/spu.py:300, in psi_csv(device, key, input_path, output_path, receiver, protocol, precheck_input, sort, broadcast_result, bucket_size, curve_type, preprocess_path, ecdh_secret_key_path, dppsi_bob_sub_sampling, dppsi_epsilon)
    280         res.append(
    281             actor.psi_csv.remote(
    282                 k,
   (...)
    296             )
    297         )
    299 # wait for all tasks done
--> 300 return sfd.get(res)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:75, in get(object_refs)
     73     return fed.get(object_refs)
     74 else:
---> 75     return ray.get(object_refs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=240171, ip=172.25.143.242, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f2c5c66bc40>)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
stacktrace: 
#0 yacl::link::ChannelBase::SendAsync()+0x7f2c68aaf4c2
#1 yacl::link::Context::SendAsyncInternal()+0x7f2c68aa871b
#2 yacl::link::Context::SendAsync()+0x7f2c68aa889e
#3 spu::psi::(anonymous namespace)::SendBatchImpl<>()+0x7f2c689b76ca
#4 spu::psi::EcdhPsiContext::SendBatch()+0x7f2c689b7a85
#5 spu::psi::EcdhPsiContext::MaskSelf()+0x7f2c689bbd35
#6 std::_Function_handler<>::_M_invoke()+0x7f2c689bc280
#7 std::__future_base::_State_baseV2::_M_do_set()+0x7f2c67f166ee
#8 __pthread_once_slow+0x7f360060fe57
2023-04-18 16:35:11,926	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.psi_csv() (pid=1804673, ip=172.25.143.241, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fd172f64d00>)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
stacktrace: 
#0 yacl::link::ChannelBase::SendAsync()+0x7fd18a1964c2
#1 yacl::link::Context::SendAsyncInternal()+0x7fd18a18f71b
#2 yacl::link::Context::SendAsync()+0x7fd18a18f89e
#3 spu::psi::(anonymous namespace)::SendBatchImpl<>()+0x7fd18a09e6ca
#4 spu::psi::EcdhPsiContext::SendBatch()+0x7fd18a09ea85
#5 spu::psi::EcdhPsiContext::MaskSelf()+0x7fd18a0a2d35
#6 std::_Function_handler<>::_M_invoke()+0x7fd18a0a3280
#7 std::__future_base::_State_baseV2::_M_do_set()+0x7fd1895fd6ee
#8 __pthread_once_slow+0x7fdb1020fe57
```

### Reproduction code to reproduce the issue.

```shell
spu_psi.psi_csv('id', input_path, output_path, 'alice',protocol='ECDH_PSI_2PC')
```

**Comment by Chrisdehe** [comment]
Hi，@lvying0019
请问psi的数据集大小是多少？
辛苦在sf.init 加上log_to_driver=True跑一次，贴一下日志信息。

**Comment by lvying0019** [comment]
> 
数据集是100W*100W
日志如下：
2023-04-18 20:19:21.659 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
2023-04-18 20:19:21.659 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: ./PSI/A_PSI_DATA.csv, precheck_switch:true
2023-04-18 20:19:21.889 [info] [csv_checker.cc:CsvChecker:121] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=./PSI --stable selected-keys.1681820361659401270 | LC_ALL=C uniq -d > duplicate-keys.1681820361659401270
2023-04-18 20:19:22.207 [info] [bucket_psi.cc:Run:115] End sanity check for input file: ./PSI/A_PSI_DATA.csv, size=1000000
2023-04-18 20:19:22.207 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=1000000
2023-04-18 20:19:22.207 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
2023-04-18 20:19:22.207 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
2023-04-18 20:19:22.249 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
2023-04-18 20:21:23.480 [error] [ecdh_psi.cc:RunEcdhPsi:247] Error in mask self: [external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
2023-04-18 20:21:23.480 [error] [ecdh_psi.cc:RunEcdhPsi:254] Error in mask peer: [external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
2023-04-18 20:21:23.486 [error] [ecdh_psi.cc:RunEcdhPsi:261] Error in recv peer: [external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=root-0:P2P-142:1->0

**Comment by zhanglei486** [comment]
试一下增加参数curve_type=CURVE_FOURQ

**Comment by lvying0019** [comment]
> 试一下增加参数curve_type=CURVE_FOURQ
可以正常运行

**Comment by lvying0019** [comment]
> 试一下增加参数curve_type=CURVE_FOURQ
> 可以正常运行

请问这个是什么问题吗？

**Comment by zhanglei486** [comment]
psi两方的机器cpu型号麻烦发一下
cat /proc/cpuinfo

**Comment by lvying0019** [comment]
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 106
model name	: Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
stepping	: 6
microcode	: 0x1
cpu MHz		: 2699.998
cache size	: 49152 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs mmio_stale_data eibrs_pbrsb
bogomips	: 5399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 57 bits virtual
power management:

**Comment by zhanglei486** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/47308800/233523052-5368aecd-8dcb-445a-8acf-13f717b2963d.png">
看上面的报错信息，显示在执行数据加密时报了异常，所以建议换了一条曲线进行加密。

请问一下是在一台机器上模拟的两方psi吗

**Comment by lvying0019** [comment]
用的两台机器

**Comment by zhanglei486** [comment]
https://github.com/secretflow/secretflow/issues/456
建议参考上面的issue，排查一下网络带宽、延迟，发一下详细的运行日志，CPU和网络的监控数据

**Comment by lvying0019** [comment]
> #456 建议参考上面的issue，排查一下网络带宽、延迟，发一下详细的运行日志，CPU和网络的监控数据
<img width="745" alt="截屏2023-04-21 16 34 57" src="https://user-images.githubusercontent.com/62459458/233587903-ca9ab939-7f6b-4675-98dc-253ef10382a0.png">

运行时
<img width="878" alt="截屏2023-04-21 16 42 45" src="https://user-images.githubusercontent.com/62459458/233589698-c46fa0d5-97e7-47ed-a9c9-bd0a050303a2.png">
<img width="924" alt="截屏2023-04-21 16 42 53" src="https://user-images.githubusercontent.com/62459458/233589780-457c243f-8576-4c5b-aa67-a705ff418da8.png">

(SPURuntime pid=1025322) 2023-04-21 16:42:33.835 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=1025322) 2023-04-21 16:42:33.835 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: ./PSI/A_PSI_DATA.csv, precheck_switch:true
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:33.836 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:33.836 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: ./PSI/B_PSI_DATA.csv, precheck_switch:true
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:34.065 [info] [csv_checker.cc:CsvChecker:121] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=./PSI --stable selected-keys.1682066553836315638 | LC_ALL=C uniq -d > duplicate-keys.1682066553836315638
(SPURuntime pid=1025322) 2023-04-21 16:42:34.065 [info] [csv_checker.cc:CsvChecker:121] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=./PSI --stable selected-keys.1682066553835519750 | LC_ALL=C uniq -d > duplicate-keys.1682066553835519750
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:34.383 [info] [bucket_psi.cc:Run:115] End sanity check for input file: ./PSI/B_PSI_DATA.csv, size=1000000
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:34.383 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=1000000
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:34.383 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:34.384 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:42:34.399 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
(SPURuntime pid=1025322) 2023-04-21 16:42:34.383 [info] [bucket_psi.cc:Run:115] End sanity check for input file: ./PSI/A_PSI_DATA.csv, size=1000000
(SPURuntime pid=1025322) 2023-04-21 16:42:34.384 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=1000000
(SPURuntime pid=1025322) 2023-04-21 16:42:34.384 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
(SPURuntime pid=1025322) 2023-04-21 16:42:34.384 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
(SPURuntime pid=1025322) 2023-04-21 16:42:34.398 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:44:35.578 [error] [ecdh_psi.cc:RunEcdhPsi:247] Error in mask self: [external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:44:35.578 [error] [ecdh_psi.cc:RunEcdhPsi:254] Error in mask peer: [external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
(SPURuntime pid=1831923, ip=172.25.143.241) 2023-04-21 16:44:35.584 [error] [ecdh_psi.cc:RunEcdhPsi:261] Error in recv peer: [external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=root-0:P2P-136:0->1
---------------------------------------------------------------------------
RayTaskError(RuntimeError)                Traceback (most recent call last)
Cell In[174], line 2
      1 start_time = time.time()
----> 2 spu_psi.psi_csv('id', input_path, output_path
      3                 , 'alice'
      4                 ,protocol='ECDH_PSI_2PC'
      5                 # ,broadcast_result=False
      6                 # , curve_type='CURVE_FOURQ'
      7                )
      8 ecdh_comsume_time = time.time()-start_time
      9 ecdh_comsume_time

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py:1426, in SPU.psi_csv(self, key, input_path, output_path, receiver, protocol, precheck_input, sort, broadcast_result, bucket_size, curve_type, preprocess_path, ecdh_secret_key_path, dppsi_bob_sub_sampling, dppsi_epsilon)
   1381 def psi_csv(
   1382     self,
   1383     key: Union[str, List[str], Dict[Device, List[str]]],
   (...)
   1396     dppsi_epsilon=3,
   1397 ):
   1398     """Private set intersection with csv file.
   1399 
   1400     Args:
   (...)
   1423         List[Dict]: PSI reports output by SPU with order reserved.
   1424     """
-> 1426     return dispatch(
   1427         'psi_csv',
   1428         self,
   1429         key,
   1430         input_path,
   1431         output_path,
   1432         receiver,
   1433         protocol,
   1434         precheck_input,
   1435         sort,
   1436         broadcast_result,
   1437         bucket_size,
   1438         curve_type,
   1439         preprocess_path,
   1440         ecdh_secret_key_path,
   1441         dppsi_bob_sub_sampling,
   1442         dppsi_epsilon,
   1443     )

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py:111, in dispatch(name, self, *args, **kwargs)
    101 def dispatch(name: str, self, *args, **kwargs):
    102     """Dispatch device kernel.
    103 
    104     Args:
   (...)
    109         Kernel execution result.
    110     """
--> 111     return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py:80, in Registrar.dispatch(self, device_type, name, *args, **kwargs)
     78 if name not in self._ops[device_type]:
     79     raise KeyError(f'device: {device_type}, op: {name} not registered')
---> 80 return self._ops[device_type][name](*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/kernels/spu.py:300, in psi_csv(device, key, input_path, output_path, receiver, protocol, precheck_input, sort, broadcast_result, bucket_size, curve_type, preprocess_path, ecdh_secret_key_path, dppsi_bob_sub_sampling, dppsi_epsilon)
    280         res.append(
    281             actor.psi_csv.remote(
    282                 k,
   (...)
    296             )
    297         )
    299 # wait for all tasks done
--> 300 return sfd.get(res)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:75, in get(object_refs)
     73     return fed.get(object_refs)
     74 else:
---> 75     return ray.get(object_refs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=1025322, ip=172.25.143.242, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f98c20f40d0>)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
stacktrace: 
#0 yacl::link::ChannelBase::SendAsync()+0x7f98ce5114c2
#1 yacl::link::Context::SendAsyncInternal()+0x7f98ce50a71b
#2 yacl::link::Context::SendAsync()+0x7f98ce50a89e
#3 spu::psi::(anonymous namespace)::SendBatchImpl<>()+0x7f98ce4196ca
#4 spu::psi::EcdhPsiContext::SendBatch()+0x7f98ce419a85
#5 spu::psi::EcdhPsiContext::MaskSelf()+0x7f98ce41dd35
#6 std::_Function_handler<>::_M_invoke()+0x7f98ce41e280
#7 std::__future_base::_State_baseV2::_M_do_set()+0x7f98cd9786ee
#8 __pthread_once_slow+0x7fa26220fe57
(SPURuntime pid=1025322) 2023-04-21 16:44:35.583 [error] [ecdh_psi.cc:RunEcdhPsi:247] Error in mask self: [external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
(SPURuntime pid=1025322) 2023-04-21 16:44:35.583 [error] [ecdh_psi.cc:RunEcdhPsi:254] Error in mask peer: [external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
(SPURuntime pid=1025322) 2023-04-21 16:44:35.583 [error] [ecdh_psi.cc:RunEcdhPsi:261] Error in recv peer: [external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=root-0:P2P-136:1->0
2023-04-21 16:44:40,973	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.psi_csv() (pid=1831923, ip=172.25.143.241, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f57f0390d00>)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:284] Throttle window wait timeout
stacktrace: 
#0 yacl::link::ChannelBase::SendAsync()+0x7f57fc79e4c2
#1 yacl::link::Context::SendAsyncInternal()+0x7f57fc79771b
#2 yacl::link::Context::SendAsync()+0x7f57fc79789e
#3 spu::psi::(anonymous namespace)::SendBatchImpl<>()+0x7f57fc6a66ca
#4 spu::psi::EcdhPsiContext::SendBatch()+0x7f57fc6a6a85
#5 spu::psi::EcdhPsiContext::MaskSelf()+0x7f57fc6aad35
#6 std::_Function_handler<>::_M_invoke()+0x7f57fc6ab280
#7 std::__future_base::_State_baseV2::_M_do_set()+0x7f57fbc056ee
#8 __pthread_once_slow+0x7f618bc0fe57

**Comment by zhanglei486** [comment]
方便把执行的脚本和脱敏后的数据发一下吗，我们再排查一下

**Comment by lvying0019** [comment]
[data.zip](https://github.com/secretflow/secretflow/files/11294205/data.zip)

**Comment by zhanglei486** [comment]
bob端，172.25.143.241这台机器，CPU也是8369B吗？

**Comment by lvying0019** [comment]
<img width="1544" alt="截屏2023-04-21 17 13 30" src="https://user-images.githubusercontent.com/62459458/233597147-0b460283-7aab-4455-b9d1-0c3a97eae108.png">

**Comment by zhanglei486** [comment]
> 从日志上看，bob端，172.25.143.241这台机器，收发数据异常，但没法定位具体原因
> 
> 可以排查一下两台机器上，配置的cluste_def 定义spu link端口，收发数据是否正常，系统是否有防火墙规则阻断了数据
> 
> 方便把执行的脚本和脱敏后的数据发一下吗，我们再排查一下

@lvying0019 麻烦把测试脚本也发一下吧

**Comment by lvying0019** [comment]
'''python
import time
import secretflow as sf
import spu
sf.shutdown()
sf.init(parties=['alice', 'bob'], address='172.25.143.242:10000',log_to_driver=True, logging_level='debug')
alice = sf.PYU('alice')
bob = sf.PYU('bob')
cluster_def={
    'nodes': [
        {
            'party': 'alice',
            # Please choose an unused port.
            'address': '172.25.143.242:9891',
            'listen_addr': '0.0.0.0:9891'
        },
        {
            'party': 'bob',
            # Please choose an unused port.
            'address': '172.25.143.241:9891',
            'listen_addr': '0.0.0.0:9891'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128
    }
}

# tls_config = {
#     "ca_cert": "ca root cert of other parties (e.g. bob)",
#     "cert": "server cert of alice in pem",
#     "key": "server key of alice in pem",
# }

spu_psi = sf.SPU(cluster_def=cluster_def)
input_path = {alice: './PSI/A_PSI_DATA.csv', bob: './PSI/B_PSI_DATA.csv'}
output_path = {alice: './PSI/alice_psi.csv', bob: './PSI/bob_psi.csv'}
start_time = time.time()
spu_psi.psi_csv('id', input_path, output_path
                , 'alice'
                ,protocol='ECDH_PSI_2PC'
                # ,broadcast_result=False
                # , curve_type='CURVE_FOURQ'
               )
ecdh_comsume_time = time.time()-start_time
ecdh_comsume_time
'''

**Comment by zhanglei486** [comment]
link_desc = {
    'throttle_window_size': 64,
    'recv_timeout_ms': 2400000,
}

spu = sf.SPU(cluster_def, link_desc)

试一下增加上面link的配置参数

**Comment by lvying0019** [comment]
> link_desc = { 'throttle_window_size': 256, 'recv_timeout_ms': 2400000, }
> 
> spu_psi = sf.SPU(cluster_def, link_desc)
> 
> 试一下增加上面link的配置参数

OK，加上之后就成功了！感谢！回头找到具体是啥问题，也请告知一下！

**Comment by zhanglei486** [comment]
建议测一下机器间的网络延时，可能延时太大，所以上面的参数加大了window_size

**Comment by zhanglei486** [comment]
另外也可以试下降低throttle_window_size，看一下出错的临界值是多少
