### ISSUE TITLE
在集群模式下，参考baseline中pir脚本，编写pir任务脚本的一些问题

### ISSUE THREAD

**Issue by sswdaytoy** [secretflow/secretflow#450]
部署模式：
集群，conda安装

任务：
pir

Secretflow Version
最新版
<img width="554" alt="5fffc9b9423e2e6fb85b072de9cfe8c" src="https://user-images.githubusercontent.com/62001897/232769475-b4002ebb-e90f-4be7-82c7-e1b9aa3a7238.png">

OS Platform and Distribution
anolis

Python version
3.8

Bazel version
No response

GCC/Compiler version
No response

执行代码：
import os
import sys
import time
import logging
import multiprocess
from absl import app
import spu
import secretflow as sf
#import random
# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
# SPU settings
# alice as pir client
# bob as pir server
cluster_def = {
    'nodes': [
        {
            'party': 'alice', 
            'id': 'local:0', 
            'address': '172.25.143.242:10021', 
        },
        {
            'party': 'bob', 
            'id': 'local:1', 
            'address': '172.25.143.241:10022', 
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
link_desc = {
    'recv_timeout_ms': 3600000,
}
sf.shutdown()
sf.init(['alice','bob'],address='172.25.143.242:10000',log_to_driver=True,omp_num_threads=multiprocess.cpu_count())
# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
alice = sf.PYU('alice')
bob = sf.PYU('bob')
key_columns = ['id']
label_columns = ['register_date','age']
spu = sf.SPU(cluster_def, link_desc)
pir_input_path = './ssw/bob/B_PIR_DATA.csv'
pir_oprf_key_path = './ssw/bob/oprf_key.bin'
pir_setup_path = './ssw/bob/sf_setup_path'
start = time.time()
# server setup
reports = spu.pir_setup(
        server='bob',
        input_path=pir_input_path,
        key_columns=key_columns,
        label_columns=label_columns,
        oprf_key_path=pir_oprf_key_path,
        setup_path=pir_setup_path,
        num_per_query=1,
        label_max_len=18,
    )
#print(f"psi reports: {reports}")
logging.info(f"offline psi reports: {reports}")
logging.info(f"cost time: {time.time() - start}")

alice_input_path = './ssw/alice/A_PIR_ID.csv'
# client config
alice_config = {
        'input_path': alice_input_path,
        'key_columns': key_columns,
        'output_path': './ssw/output/sf_pir_out.csv',
    }
# server config
bob_config = {
        'oprf_key_path': pir_oprf_key_path,
        'setup_path': pir_setup_path,
    }
query_config = {
        alice: alice_config,
        bob: bob_config,
    }
start = time.time()
reports = spu.pir_query(
        server='bob',
        config=query_config,
    )

logging.info(f"online pir reports: {reports}")
logging.info(f"cost time: {time.time() - start}")
sf.shutdown()

执行结果：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 97
     94 start = time.time()
     96     # server setup
---> 97 reports = spu.pir_setup(
     98         server='bob',
     99         input_path=pir_input_path,
    100         key_columns=key_columns,
    101         label_columns=label_columns,
    102         oprf_key_path=pir_oprf_key_path,
    103         setup_path=pir_setup_path,
    104         num_per_query=1,
    105         label_max_len=18,
    106     )
    108     #print(f"psi reports: {reports}")
    109 logging.info(f"offline psi reports: {reports}")

AttributeError: 'SPU' object has no attribute 'pir_setup'

问题：1.参考baseline写了spu.pir_setup，但报错是没有这个方法
            2.对于这两个配置不了解
              pir_oprf_key_path = './ssw/bob/oprf_key.bin'
              pir_setup_path = './ssw/bob/sf_setup_path'
             在我的从节点bob上的/ssw/bob/下，文件结构是这样（不知道是不是缺少一些文件）
<img width="256" alt="3839c5299c5d6d2cd0bb7cacbb10982" src="https://user-images.githubusercontent.com/62001897/232762455-aca8ce53-d7a9-4688-9610-6fff06ae86e7.png">

**Comment by Chrisdehe** [comment]
Hi，@sswdaytoy ！
secret flow python版本目前只发出了代码，pip whl包还未支持，预计本周内发出，敬请期待。
