### ISSUE TITLE
ECDH-2PSI性能测试数据复现失败

### ISSUE THREAD

**Issue by ZeroAntelope** [secretflow/secretflow#456]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow0.8.1b0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.9

### What happend and What you expected to happen.

```shell
测试环境：两台服务器配置 Intel® Xeon® Gold 6338 Processor  CPU：16核 内存：32G 硬盘：500G 带宽1000Mbps
pip-version 22.3.1
测试ecdh-2PSI算法方案：
（1）单台服务器测试————1千万数据求交约50s，1亿数据求交约500秒（双方CPU均为800%左右），和benckmark的8核16G下的测试数据基本一致；
（2）两台服务器联机测试————1千万数据求交约100s，1亿数据求交约1000秒（单机测试的2倍，观察到双方CPU均为400%左右），是benckmark的2倍。
怎样才能复现管方提供的性能数据呢？我的测试动作哪里操作不正确嘛？猜想，是不是和cpu_nums设置有关呢，但是设置该参数没有什么变化？
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging
import multiprocess
from absl import app
import spu
import secretflow as sf

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
    'nodes': [
        # <<< !!! >>> replace <192.168.0.1:12945> to alice node's local ip & free port
        {'party': 'alice', 'id': 'local:0', 'address': '192.168.1.250:12945', 'listen_address': '0.0.0.0:12945'},
        # <<< !!! >>> replace <192.168.0.2:12946> to bob node's local ip & free port
        {'party': 'bob', 'id': 'local:1', 'address': '192.168.1.251:12946', 'listen_address': '0.0.0.0:12946'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}


def main(_):

    # sf init
    # <<< !!! >>> replace <192.168.0.1:9394> to your ray head
    # two parties secretflow>=0.7.18b3 need to add <sf.init(parties=['alice', 'bob']>
    sf.init(parties=['alice', 'bob'], address='192.168.1.250:9394',log_to_driver=True)
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')

    # <<< !!! >>> replace path to real parties local file path.
    input_path = {
        alice: 'psi_1.csv',
        bob: 'psi_2.csv',
    }
    output_path = {
        alice: 'psi_output.csv',
        bob: 'psi_output.csv',
    }
    select_keys = {
        alice: ['id'],
        bob: ['id'],
    }
    spu = sf.SPU(cluster_def)

    # prepare data
    start = time.time()
    print(sodium_runtime_has_avx)
    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='ECDH_PSI_2PC',        # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
    )
    print(f"psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")

    sf.shutdown()

if __name__ == '__main__':
    app.run(main)
```

**Comment by zhanglei486** [comment]
带宽1000Mbps，有测过延时吗
辛苦发一下运行日志
最好能CPU和网络的监控数据

**Comment by ZeroAntelope** [comment]
经排查：

- 带宽1000Mbps，延迟0.7ms

**Comment by ZeroAntelope** [comment]
经排查：
     - 带宽1000Mbps，延迟0.7ms
     - 两台服务器联机测试在本地系统进行
     - 但是我们基于iperf3工具测试，发现服务器之间的带宽在40mbps左右
1亿数据单机测试，复现日志如下：
(tutorial-env) (sf-benchmark) root@ppcptest01:/home/nlsa/sf-benchmark/sf-benchmark# python3 benchmark2.py
2023-04-20 08:30:18,322	INFO worker.py:1538 -- Started a local Ray instance.
(SPURuntime pid=105661) 2023-04-20 08:30:21.278 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=127.0.0.1:38775} (0x0x4c4c7c0): Connection refused [R1][E112]Not connected to 127.0.0.1:38775 yet, server_id=0 [R2][E112]Not connected to 127.0.0.1:38775 yet, server_id=0 [R3][E112]Not connected to 127.0.0.1:38775 yet, server_id=0
(SPURuntime pid=105661) 2023-04-20 08:30:22.289 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=105661) 2023-04-20 08:30:22.289 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: psi_1.csv, precheck_switch:false
(SPURuntime pid=105667) 2023-04-20 08:30:22.288 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=105667) 2023-04-20 08:30:22.288 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: psi_2.csv, precheck_switch:false
(SPURuntime pid=105667) 2023-04-20 08:30:50.818 [info] [bucket_psi.cc:Run:115] End sanity check for input file: psi_2.csv, size=100000000
(SPURuntime pid=105661) 2023-04-20 08:30:50.819 [info] [bucket_psi.cc:Run:115] End sanity check for input file: psi_1.csv, size=100000000
(SPURuntime pid=105661) 2023-04-20 08:30:50.819 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=100000000
(SPURuntime pid=105661) 2023-04-20 08:30:50.819 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
(SPURuntime pid=105661) 2023-04-20 08:30:50.819 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
(SPURuntime pid=105667) 2023-04-20 08:30:50.819 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=100000000
(SPURuntime pid=105667) 2023-04-20 08:30:50.819 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
(SPURuntime pid=105667) 2023-04-20 08:30:50.819 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
(SPURuntime pid=105661) 2023-04-20 08:30:50.856 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
(SPURuntime pid=105667) 2023-04-20 08:30:50.856 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
(SPURuntime pid=105661) 2023-04-20 08:37:44.826 [info] [ecdh_psi.cc:MaskPeer:113] MaskPeer:root--finished, batch_count=24415
(SPURuntime pid=105667) 2023-04-20 08:37:44.808 [info] [ecdh_psi.cc:MaskSelf:74] MaskSelf:root--finished, batch_count=24415
(SPURuntime pid=105661) 2023-04-20 08:37:47.660 [info] [ecdh_psi.cc:MaskSelf:74] MaskSelf:root--finished, batch_count=24415
(SPURuntime pid=105661) 2023-04-20 08:37:47.665 [info] [ecdh_psi.cc:RecvDualMaskedSelf:138] root recv last batch finished, batch_count=24415
(SPURuntime pid=105667) 2023-04-20 08:37:47.664 [info] [ecdh_psi.cc:MaskPeer:113] MaskPeer:root--finished, batch_count=24415
(SPURuntime pid=105661) 2023-04-20 08:39:13.831 [info] [bucket_psi.cc:Run:178] Begin post filtering, indices.size=50000000, should_sort=false
psi reports: [{'party': 'alice', 'original_count': 100000000, 'intersection_count': 50000000}, {'party': 'bob', 'original_count': 100000000, 'intersection_count': -1}]
I0420 08:39:26.672246 139715101102720 benchmark2.py:74] cost time: 547.1085178852081


1亿数据联机测试，复现日志如下：
       (tutorial-env) (sf-benchmark) root@ppcptest01:/home/nlsa/sf-benchmark/sf-benchmark# python3 benchmark1.py
2023-04-20 08:10:11,923	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 192.168.1.250:9394...
2023-04-20 08:10:11,937	INFO worker.py:1538 -- Connected to Ray cluster.
(SPURuntime pid=103837) 2023-04-20 08:10:13.669 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=192.168.1.251:12946} (0x0x400c500): Connection refused [R1][E112]Not connected to 192.168.1.251:12946 yet, server_id=0 [R2][E112]Not connected to 192.168.1.251:12946 yet, server_id=0 [R3][E112]Not connected to 192.168.1.251:12946 yet, server_id=0
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:14.692 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:14.692 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: psi_2.csv, precheck_switch:false
(SPURuntime pid=103837) 2023-04-20 08:10:14.679 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=103837) 2023-04-20 08:10:14.679 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: psi_1.csv, precheck_switch:false
(SPURuntime pid=103837) 2023-04-20 08:10:39.623 [info] [bucket_psi.cc:Run:115] End sanity check for input file: psi_1.csv, size=100000000
(SPURuntime pid=103837) 2023-04-20 08:10:39.623 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=100000000
(SPURuntime pid=103837) 2023-04-20 08:10:39.623 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
(SPURuntime pid=103837) 2023-04-20 08:10:39.623 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:39.636 [info] [bucket_psi.cc:Run:115] End sanity check for input file: psi_2.csv, size=100000000
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:39.637 [info] [bucket_psi.cc:RunPsi:419] Run psi protocol=1, self_items_count=100000000
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:39.637 [info] [cryptor_selector.cc:GetIppCryptor:37] Using IPPCP
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:39.637 [info] [cipher_store.cc:DiskCipherStore:33] Disk cache choose num_bins=64
(SPURuntime pid=103837) 2023-04-20 08:10:39.681 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:10:39.695 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 15
(SPURuntime pid=103837) 2023-04-20 08:25:28.267 [info] [ecdh_psi.cc:MaskSelf:74] MaskSelf:root--finished, batch_count=24415
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:25:28.464 [info] [ecdh_psi.cc:MaskPeer:113] MaskPeer:root--finished, batch_count=24415
(SPURuntime pid=103837) 2023-04-20 08:25:28.586 [info] [ecdh_psi.cc:RecvDualMaskedSelf:138] root recv last batch finished, batch_count=24415
(SPURuntime pid=25479, ip=192.168.1.251) 2023-04-20 08:25:28.708 [info] [ecdh_psi.cc:MaskSelf:74] MaskSelf:root--finished, batch_count=24415
(SPURuntime pid=103837) 2023-04-20 08:25:28.888 [info] [ecdh_psi.cc:MaskPeer:113] MaskPeer:root--finished, batch_count=24415
(SPURuntime pid=103837) 2023-04-20 08:26:57.164 [info] [bucket_psi.cc:Run:178] Begin post filtering, indices.size=50000000, should_sort=false
(SPURuntime pid=103837) 2023-04-20 08:27:08.157 [info] [bucket_psi.cc:Run:216] End post filtering, in=psi_1.csv, out=psi_output.csv
psi reports: [{'party': 'alice', 'original_count': 100000000, 'intersection_count': 50000000}, {'party': 'bob', 'original_count': 100000000, 'intersection_count': -1}]
I0420 08:27:08.244268 140059256799872 benchmark1.py:73] cost time: 1016.2250134944916

**Comment by ZeroAntelope** [comment]
联机网络监控数据：

**Comment by ZeroAntelope** [comment]
网络监控：
（1）Incoming  
<img width="123" alt="1681954683059" src="https://user-images.githubusercontent.com/65222957/233325619-f5a322dc-398b-4600-a930-8df1f8126e6c.png">
（2）outcoming：
![image](https://user-images.githubusercontent.com/65222957/233325967-ef4a49df-23a8-41e8-90c8-bd5f4067238d.png)
单机测试cpu：
<img width="459" alt="1681955005405" src="https://user-images.githubusercontent.com/65222957/233327305-610cdeb1-0117-4b26-b3d0-f2c31c987376.png">

连机两服务器cpu：
<img width="407" alt="1681954888578" src="https://user-images.githubusercontent.com/65222957/233326504-c1146008-8a2d-4e6a-80c2-cb964d8fae68.png">
<img width="410" alt="1681954937145" src="https://user-images.githubusercontent.com/65222957/233326793-05bfff80-76cb-42ee-a81f-9cf873e94e95.png">

**Comment by zhanglei486** [comment]
感谢提供相关的排查信息，
- 但是我们基于iperf3工具测试，发现服务器之间的带宽在40mbps左右
参考两台机器iperf的测试结果40mbps，两台机器性能1016，应该是合理的，ecdh-psi传输峰值差不多是100M多些，
带宽40mbps时，ecdh-psi性能确实会下降一半

建议排查一下服务器间通信为什么只有40mbps，是不是交换机时百兆，或者有限速

**Comment by ZeroAntelope** [comment]
解决了，就是带宽限制得问题，感谢感谢

**Comment by ZeroAntelope** [comment]
是的，基本一致
