### ISSUE TITLE
隐语隐匿查询是否支持不可区分度的设置？

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#457]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.18b0

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
#隐匿查询是否支持不可区分度的设置？

学习隐语的过程中，遇到一些疑惑，请大佬帮忙解惑。

在链接https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw里面提到在半诚实敌手模型下，保证查询方的查询目标不被泄露（不可区分度与样本量相同），查询方不能获得查询结果之外的其他信息。

如果隐语支持：是否有对应的文档或者demo?
如果不支持：是否今后考虑支持，不支持的原因是什么嘞？
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by zhanglei486** [comment]
问题中链接对应的文档是隐语开源社区针对赛题，包括PSI和PIR两个子赛题，给出了参考方案
每个子赛题文档里面包含：基本原理，参考文献，测试代码，和性能数据，均能达到或超过赛题中的各项要求

**Comment by SZU-czw** [comment]
> 问题中链接对应的文档是隐语开源社区针对赛题，包括PSI和PIR两个子赛题，给出了参考方案 每个子赛题文档里面包含：基本原理，参考文献，测试代码，和性能数据，均能达到或超过赛题中的各项要求

大佬好，上面我的问题没有阐述清楚。

我的问题是：一亿样本百万级不可区分度，隐语支不支持？

**Comment by SZU-czw** [comment]
好的，明白了。感谢回复。

**Comment by SZU-czw** [comment]
> 目前不支持手动数据拆分，建议自己把数据拆分后，多次调用

大佬好，我网上找了一圈，不可区分度资料很少。
请问，隐语不可区分度有相关资料（文档）或者代码吗？
