### ISSUE TITLE
学习SPU基础教程中碰到问题

### ISSUE THREAD

**Issue by huyz1117** [secretflow/secretflow#468]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.1b0

### OS Platform and Distribution

Centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在学习[SPU基础](https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/spu_basics.html)的过程中，有几个问题不是很明白：
首先，执行完`spu_device = sf.SPU(aby3_config)`出现以下错误:
(SPURuntime pid=58338) 2023-04-24 14:57:56.175 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=127.0.0.1:47609} (0x0x562ef0799d40): Connection refused [R1][E112]Not connected to 127.0.0.1:47609 yet, server_id=0 [R2][E112]Not connected to 127.0.0.1:47609 yet, server_id=0 [R3][E112]Not connected to 127.0.0.1:47609 yet, server_id=0
然后，将Python Object从Host传到SPU时，查看`bank_account_spu.meta`时，输出以下内容`ObjectRef(e0dc174c83599034ffffffffffffffffffffffff0100000001000000)`，而不是像教程中可以输出原始结构，想问的问题是这里的Host是什么概念，与下文的**将一个PYU Object从PYU传给SPU**内容有什么不同
```

### Reproduction code to reproduce the issue.

```shell
# 以下代码在jupyter notebook中执行
import secretflow as sf
sf.shutdown()
sf.init(["alice", "bob", "carol", "dave"], address="local")
alice, dave = sf.PYU("alice"), sf.PYU("dave")

aby3_config = sf.utils.testing.cluster_def(parties=["alice", "bob", "carol"])
spu_device = sf.SPU(aby3_config)

##### 将一个Python Object从Host传到SPU #####
bank_account = [{'id': 12345, 'deposit': 1000.25}, {'id': 12345, 'deposit': 100000.25}]
bank_account_spu = sf.to(alice, bank_account).to(spu_device)
bank_account_spu.meta    # 输出：ObjectRef(e0dc174c83599034ffffffffffffffffffffffff0100000001000000)
assert len(bank_account_spu.shares_name) == 3
bank_account_spu.shares_name[0]#输出:ObjectRef(f4402ec78d3a260733f73708933dbc44ef7687130100000001000000)

##### 将一个PYU Object从PYU传给SPU #####
def debit_amount():
    return 10

debit_amount_pyu = alice(debit_amount)()
debit_amount_spu = debit_amount_pyu.to(spu_device)
debit_amount_spu.meta # 输出：ObjectRef(80e22aed7718a125ffffffffffffffffffffffff0100000001000000)
```

**Comment by 6fj** [comment]
Hi @huyz1117 

这段代码是用单机仿真模式启动sf： https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#standalone-mode-for-simulation

现在遇到的问题是sf.utils.testing.cluster_def中选择的port好像无法被连接上。

请问你遇到的问题是每次都会复现的吗？

**Comment by huyz1117** [comment]
> Hi @huyz1117
> 
> 这段代码是用单机仿真模式启动sf： https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#standalone-mode-for-simulation
> 
> 现在遇到的问题是sf.utils.testing.cluster_def中选择的port好像无法被连接上。
> 
> 请问你遇到的问题是每次都会复现的吗？

是的，都会出现连接不上这个问题

**Comment by 6fj** [comment]
请用以下代码代替 **aby3_config = sf.utils.testing.cluster_def(parties=["alice", "bob", "carol"])**

```
aby3_config ={
    'nodes': [
        {
            'party': 'alice',
            # Please choose an unused port.
            'address': 'ip:port of alice',
            'listen_addr': '0.0.0.0:port'
        },
        {
            'party': 'bob',
            # Please choose an unused port.
            'address': 'ip:port of bob',
            'listen_addr': '0.0.0.0:port'
        },
        {
            'party': 'carol',
            # Please choose an unused port.
            'address': 'ip:port of carol',
            'listen_addr': '0.0.0.0:port'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.ABY3,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
```

**Comment by huyz1117** [comment]
> 请用以下代码代替 **aby3_config = sf.utils.testing.cluster_def(parties=["alice", "bob", "carol"])**
> 
> ```
> aby3_config ={
>     'nodes': [
>         {
>             'party': 'alice',
>             # Please choose an unused port.
>             'address': 'ip:port of alice',
>             'listen_addr': '0.0.0.0:port'
>         },
>         {
>             'party': 'bob',
>             # Please choose an unused port.
>             'address': 'ip:port of bob',
>             'listen_addr': '0.0.0.0:port'
>         },
>         {
>             'party': 'carol',
>             # Please choose an unused port.
>             'address': 'ip:port of carol',
>             'listen_addr': '0.0.0.0:port'
>         },
>     ],
>     'runtime_config': {
>         'protocol': spu.spu_pb2.ABY3,
>         'field': spu.spu_pb2.FM128,
>         'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
>     }
> }
> ```

问题解决了，谢谢
请问第二个问题中Host是指哪一方

**Comment by 6fj** [comment]
这个Host是secretflow driver程序，就是这份python代码
