### ISSUE TITLE
采用TLS之后，联邦两方无法连接

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#469]
hi, @hnjiakai, 这里有一个bug，临时修复的话，你可以把下面这行代码先注释掉。
https://github.com/secretflow/secretflow/blob/main/secretflow/device/driver.py/#L407

附：如何找到driver.py
执行`pip show secretflow`，可以得到secretflow安装的地址，类似`xxx/lib/python3.8/site-packages`，那么文件的位置就是 `xxx/lib/python3.8/site-packages/secretflow/device/driver.py`

_Originally posted by @zhouaihui in https://github.com/secretflow/secretflow/issues/465#issuecomment-1519014279_
            

在通过上述方式，注释407行代码之后，通过老式的TLS配置之后，程序没有报错，但是双方已经无法连接了，如图所示
alice主机的后台日志
![image](https://user-images.githubusercontent.com/44387768/233944377-9eb0cced-fa58-4c19-8b1f-2ff0422e0199.png)
bob主机的后台日志
![image](https://user-images.githubusercontent.com/44387768/233944473-503acaea-35ae-4e6e-9ab2-eb3fd601f311.png)

而在代码中，在sf.init中，没有添加tls_config可以完成两方连接和运行，添加了tls_config参数之后，无法连接，双方配置如下图所示
alice的配置
![image](https://user-images.githubusercontent.com/44387768/233945026-c4bbcff1-9603-443e-952e-6b3f813de4c8.png)

bob的配置
![image](https://user-images.githubusercontent.com/44387768/233944839-8ee373a0-df82-4268-b58c-71d3d8e94ef7.png)

**Comment by zhouaihui** [comment]
hi, @Niclouge , 这个是GRPC TLS本身的报错，看起来是证书生成有问题。
仅供参考 https://stackoverflow.com/questions/44815573/in-python-grpc-i-got-a-exception-no-match-found-for-server-name

**Comment by Niclouge** [comment]
> hi, @Niclouge , 这个是GRPC TLS本身的报错，看起来是证书生成有问题。 仅供参考 https://stackoverflow.com/questions/44815573/in-python-grpc-i-got-a-exception-no-match-found-for-server-name


证书生成方式是基于椭圆算法，这个是否有影响，还是一定需要RSA的。
（证书是通过脚本生成，生成的证书已经证明在其他地方可以正常使用）

**Comment by zhouaihui** [comment]
和算法并没有关系，这个错误看着是证书里的CN并不包含你的ip，在其他机器能使用并不一定能在这台机器使用。

**Comment by miluoalbert** [comment]
请参考：https://github.com/secretflow/secretflow/issues/412#issuecomment-1495648410

**Comment by Niclouge** [comment]
> 

 
已经解决问题了，谢谢，在生成证书的时候，没有带上自己的IP，所以导致匹配不上，带上IP之后重新生成证书之后就可以了
