### ISSUE TITLE
下载Secretflow代码后，在windows上的pycharm运行tests/test_psi.py问题

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#471]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

git最新代码

### OS Platform and Distribution

windows11

### Python version

3.10

### What happend and What you expected to happen.

```shell
下载Secretflow代码后，在windows上的pycharm运行tests/test_psi.py问题

日志：
F:\downloadFromD\secretflow-main\venv\Scripts\python.exe "D:/python_professional_install_dir/PyCharm 2023.1/plugins/python/helpers/pycharm/_jb_unittest_runner.py" --path F:\downloadFromD\secretflow-main\tests\device\test_psi.py 
Testing started at 8:47 ...
Launching unittests with arguments python -m unittest F:\downloadFromD\secretflow-main\tests\device\test_psi.py in F:\downloadFromD\secretflow-main\tests\device


Error
Traceback (most recent call last):
  File "D:\python_install_dir\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_psi
Traceback (most recent call last):
  File "D:\python_install_dir\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "F:\downloadFromD\secretflow-main\tests\device\test_psi.py", line 6, in <module>
    import spu
ModuleNotFoundError: No module named 'spu'




Ran 1 test in 0.090s

FAILED (errors=1)

进程已结束,退出代码1
---------------------------------------------------

找不到spu库
```

### Reproduction code to reproduce the issue.

```shell
其他库能安装的都安装了，spu库实在找不到
```

**Comment by wjwJack** [comment]
![图片](https://user-images.githubusercontent.com/8414952/234439015-7f995259-bc6e-4ef7-a7ba-c12c4ab68701.png)

**Comment by anakinxc** [comment]
Hi @wjwJack 

我们并不支持 Windows，如果要在 Windows 上使用，请尝试通过 wsl 来跑

**Comment by anakinxc** [comment]
参见[这里](https://github.com/secretflow/secretflow/blob/58620ac57920c4d8b4b794f53289a3f723214916/docs/getting_started/installation.md?plain=1#L78) 的步骤

**Comment by wjwJack** [comment]
> Hi @wjwJack
> 
> 我们并不支持 Windows，如果要在 Windows 上使用，请尝试通过 wsl 来跑

你好，我想问下，开发secretflow，也是需要按照这四个方式之一实现吗
![图片](https://user-images.githubusercontent.com/8414952/234443904-b1e64bc0-3801-4b7e-ada7-d4c40b9f2935.png)

**Comment by anakinxc** [comment]
无论是基于 sf 开发，还是为 sf 添加功能，都需要在 sf 支持的环境中进行

**Comment by wjwJack** [comment]
> 无论是基于 sf 开发，还是为 sf 添加功能，都需要在 sf 支持的环境中进行

好的

**Comment by wjwJack** [comment]
@anakinxc 想问下你们正常开发sf的环境是什么，能详细说说吗

**Comment by anakinxc** [comment]
> Author

Linux 可以参考一下[这里](https://github.com/secretflow/devtools/blob/main/dockerfiles/ubuntu-base-ci.DockerFile)

macOS 可以参考一下 [Apple Silicon](https://github.com/secretflow/secretflow/blob/58620ac57920c4d8b4b794f53289a3f723214916/.circleci/config.yml#L73) [Intel](https://github.com/secretflow/secretflow/blob/58620ac57920c4d8b4b794f53289a3f723214916/.circleci/config.yml#L130)，然后记得安装 Xcode
