### ISSUE TITLE
基于secretFlow尝试PIR功能

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#475]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.18b0

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
目前在尝试PIR的功能，但是文档中只有bazel使用的PIR。

Q1:请问有没有基于容器方式的PIR使用方式？

Q2:PIR涉及的B_PIR_DATA.csv数据集会提供吗，还是自己手动生成？

Q3:基本的操作步骤可以给我讲讲吗？

Q4:你们那个PIR的性能对比图画的很好看，不知道是怎么实现的？

目前我的思路是，启动双方sf容器，一方当做client,另一方当做server.再server中跑pir_server.py脚本，在client中跑pir_client.py，不过这个pir_setup.py这个脚本又是用来干什么的？
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by zhanglei486** [comment]
对上面问题的回复：
1. 目前开源的都是pir的功能接口，调用方式用户可以自己设计部署，隐语的docker部署管理，可以咨询负责开源或运营的同学，了解详细的开源计划；
2. 目前微信公众号的文章是针对星河杯比赛提供的baseline，B_PIR_DATA.csv是星河杯比赛提供的一个样本数据，可以在星河杯官网了解下载方式，spu examples也提供了测试数据的生成脚本
3. 基本操作先执行setup，对服务端数据文件csv格式，进行预处理；后面就可以执行客户端和服务器之间的查询。具体内容可以参考我们的baseline文档和星河杯的开发实践视频
4. 性能对比图是用excel做的

**Comment by Chrisdehe** [comment]
Hi @SZU-czw 
数据集可在“星河杯”[官网](https://www.datafountain.cn/competitions/627/datasets)下载；
操作流程可参考微信公众号发布的“[黑名单共享查询](https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw)”赛题的baseline；
