### ISSUE TITLE
请问一下SPU运行PIR正确的操作步骤是什么？

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#482]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.18b0

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.13

### Bazel version

5.4.1

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
#我的目标：正确的跑通如下PIR的python脚本
比如：
python pir_setup.py --in_path examples/data/pir_server_data.csv --key_columns id --label_columns label \
--count_per_query 1 -max_label_length 256 \
--oprf_key_path oprf_key.bin --setup_path setup_path

我的操作系统
Linux 的Centos8

root模式下，我已经完成了如下步骤
# step1
## start container
docker run -d -it --name spu-gcc11-anolis-dev-$(whoami) \
         --mount type=bind,source="$(pwd)",target=/home/admin/dev/ \
         -w /home/admin/dev \
         --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
         --cap-add=NET_ADMIN \
         --privileged=true \
         secretflow/spu-ci:latest

#step2
## attach to build container
docker exec -it spu-gcc11-anolis-dev-$(whoami) bash

#step3
dd if=/dev/urandom of=oprf_key.bin bs=32 count=1

# step4是什么？
我尝试了
bazel build //examples/cpp/pir/... -c opt   不行，报错

我又尝试了
bash build_wheel_entrypoint.sh   还是不行，报错

于是我直接运行下面的代码，不行，报错
python examples/python/pir/pir_setup.py --in_path examples/data/pir_server_data.csv \\
    --oprf_key_path oprf_key.bin  --key_columns id --label_columns label \\
    --count_per_query 256 --max_label_length 40  \\
    --setup_path pir_setup_dir
最后尝试了，下面的，这个成功了，但是没啥用。
python3 -m pip install -r requirements.txt
python3 -m pip install -r requirements-dev.txt
```

### Reproduction code to reproduce the issue.

```shell
求助
```

**Comment by Chrisdehe** [comment]
Hi，@SZU-czw 
1、client 用A_PIR_ID.csv，server用B_PIR_DATA.csv，spu whl用0.3.2b12，examples/python/pir/*.py 可以从spu github下载（git clone https://github.com/secretflow/spu/tree/main/examples/python/pir）
2、在server机器执行dd if=/dev/urandom of=oprf_key.bin bs=32 count=1生成安全方案
3、首先在server机器执行setup，对服务端数据文件csv格式，进行预处理；后面在客户端（client）和服务器（server）同时进行server跟client脚本。
PS：--partyips ip0:port0,ip1:port1 --rank 0/1
指定本方是rank 0 时，必须有ip0, 端口port0没有被占用
指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

**Comment by SZU-czw** [comment]
> Hi，@SZU-czw 1、client 用A_PIR_ID.csv，server用B_PIR_DATA.csv，spu whl用0.3.2b12，examples/python/pir/*.py 可以从spu github下载（git clone [https://github.com/secretflow/spu/tree/main/examples/python/pir）](https://github.com/secretflow/spu/tree/main/examples/python/pir%EF%BC%89) 2、在server机器执行dd if=/dev/urandom of=oprf_key.bin bs=32 count=1生成安全方案 3、首先在server机器执行setup，对服务端数据文件csv格式，进行预处理；后面在客户端（client）和服务器（server）同时进行server跟client脚本。 PS：--partyips ip0:port0,ip1:port1 --rank 0/1 指定本方是rank 0 时，必须有ip0, 端口port0没有被占用 指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

大佬，强。很清晰明白了。我的问题是我上面提到的step4该怎么操作呢？因为执行了很多都报错没有成功，目前还没有到执行脚本的步骤

**Comment by 6fj** [comment]
@SZU-czw 

你的网络不太好

**Comment by SZU-czw** [comment]
> @SZU-czw
> 
> 你的网络不太好

# 您好，我想在单机非容器上验证PIR的功能。

我已经完成的操作
1.依赖拉取  通过
pip install  -U secretflow
pip install spu==0.3.3b0

2.bazel编译  通过
bash build_wheel_entrypoint.sh
![image](https://user-images.githubusercontent.com/49868033/236591174-b061f479-cc43-4475-9f5c-a2bf02b45076.png)

3.生成随机私钥  通过
dd if=/dev/urandom of=oprf_key.bin bs=32 count=1

4.初始化setup  通过
```
python examples/python/pir/pir_setup.py --in_path examples/data/pir_server_data.csv \
    --oprf_key_path oprf_key.bin  --key_columns id --label_columns label \
    --count_per_query 256 --max_label_length 40  \
    --setup_path pir_setup_dir
```

5.单机启动两个ray节点     不知道是否是这样启动
shell1  
ray start --head --node-ip-address="127.0.0.1" --port="9308"  --include-dashboard=False --disable-usage-stats
shell2
ray start --address="127.0.0.1:9308"  --disable-usage-stats

6.启动server 报错 ，启动client端也是报错
sever
```
python examples/python/pir/pir_server.py --party_ips 127.0.0.1:9308 --rank 0 --setup_path pir_setup_dir  --oprf_key_path oprf_key.bin
```
client
```
python examples/python/pir/pir_client.py --party_ips --party_ips 127.0.0.1:9308 -rank 1  -in_path examples/data/pir_client_data.csv.csv  -key_columns id -out_path pir_out.csv
```

**报错如下**
无法连接上节点
ID127.0.0.1:9307
ID127.0.0.1:9308

请问单机环境下可以验证PIR吗？如果可以，我上面那个步骤有问题。
还是一定要多机实现PIR功能

**Comment by zhanglei486** [comment]
secretflow升级到0.8.2b1，使用baseline文档中secretflow python脚本，该脚本就是使用单机仿真模式，不需要启动ray节点。
https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw
<img width="268" alt="image" src="https://user-images.githubusercontent.com/47308800/236592682-75ddaaea-5ce5-48da-8ffd-1dd136ab4d24.png">

后续对隐语的部署模式熟悉了可以进一步修改脚本到集群仿真和多集群的部署

**Comment by SZU-czw** [comment]
> secretflow升级到0.8.2b1，使用baseline文档中secretflow python脚本，该脚本就是使用单机仿真模式，不需要启动ray节点。 https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw <img alt="image" width="268" src="https://user-images.githubusercontent.com/47308800/236592682-75ddaaea-5ce5-48da-8ffd-1dd136ab4d24.png">
> 
> 后续对隐语的部署模式熟悉了可以进一步修改脚本到集群仿真和多集群的部署

感谢您耐心的解答。我已进成功基于keyword pir 完成了验证，我想进一步进行探索：

我的问题是
Q1:keyword pir 模式下 如何体现出 批量查询 呢？

Q2:baseline中提到了两种模式，请问另一种模式index pir  隐语中如何实现？

**Comment by SZU-czw** [comment]
> Q1: pir setup的参数：count_per_query可以指定每次查询的数量，pir_query阶段，会根据csv文件中的大小，执行多次查询
> 
> Q2: baseline中提到了两种模式，应该是指keyword pir的部署模式，index pir目前只有c++的core，还没有封装对外接口

https://www.secretflow.org.cn/docs/spu/en/development/pir.html从这里我找到了Run keyword PIR c++ example，请问run 
SealPIR IndexPIR 有对应的example 步骤吗？

**Comment by zhanglei486** [comment]
可以参考sealPIR的单测代码
https://github.com/secretflow/spu/blob/main/libspu/pir/seal_pir_test.cc
