### ISSUE TITLE
隐语部署问题

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#494]
1.隐语集群模式仿真部署时，我这里按照官网一步步执行,	最后到启动SPU时出现报错，下面是我的执行过程：
ray start --head --node-ip-address="172.17.0.2" --port="30211" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats：
![图片](https://user-images.githubusercontent.com/8414952/235101654-6bdb229d-9b27-476a-8e8c-99df715ba583.png)

ray start --address="172.17.0.2:30211" --resources='{"bob": 16}' --disable-usage-stats：
![图片](https://user-images.githubusercontent.com/8414952/235101721-357daa34-ea1e-472b-abcb-16ce6b7eeaae.png)

![图片](https://user-images.githubusercontent.com/8414952/235101746-e798e569-8f2c-4839-97c9-5cbded786df7.png)

引入spu时，我的相关配置如下：关于alice与bob的节点配置，根据官网上文并未给出bob相关IP端口信息这个是自定义么？
![图片](https://user-images.githubusercontent.com/8414952/235101883-7fcbd235-7dfd-42b9-ab39-a152115e480a.png)

下面执行中的报错，是跟我的配置有关么？还是我缺少执行某些关键命令?
![图片](https://user-images.githubusercontent.com/8414952/235101922-a8815f4e-2cc8-4af5-aa74-869ea79ab12d.png)
![图片](https://user-images.githubusercontent.com/8414952/235101934-47bf0eef-d999-44b6-a90b-d3dbb86f2460.png)

**Comment by da-niao-dan** [comment]
typo in address. what is 'of bob'?

**Comment by pchyuan** [comment]
![image](https://user-images.githubusercontent.com/38313295/235115271-88d2085d-bec5-46dc-8fc5-276db565da40.png)

**Comment by da-niao-dan** [comment]
IP address should not contain text. Use '172.....:30222'.
IP地址不接受带文字，把of bob 去掉

**Comment by wjwJack** [comment]
> IP address should not contain text. Use '172.....:30222'. IP地址不接受带文字，把of bob 去掉

好嘞

**Comment by dyx0001** [comment]
@da-niao-dan  我按照上边去掉'of bob'的配置，集群模式下启动SPU, 报出下图中的错误，请问是哪里出问题了？
<img width="937" alt="01191a23a052e8de848f6750f38ee1c" src="https://user-images.githubusercontent.com/132547242/236132525-f58a8e2d-0797-469f-a629-b4e52e0e0463.png">

**Comment by dyx0001** [comment]
我是在一台虚拟机上通过docker方式启动的secretflow镜像，在镜像里面看到的IP是172.17.0.2，我虚拟机IP是10.200.3.116

**Comment by Chrisdehe** [comment]
可以在创建容器过程中配置下 --net=host，它能够使docker和host共享所有网络端口。

**Comment by dyx0001** [comment]
目前我虚拟机的IP是网络是这样的，而且防火墙也关闭了。
<img width="762" alt="1ecd1d543a04c1a0884d3ae3107bd36" src="https://user-images.githubusercontent.com/132547242/236150051-73d36db2-abe0-4acc-8f36-bc55a54b69fb.png">
<img width="949" alt="d2845f2c1e3625f981229d8b30751a9" src="https://user-images.githubusercontent.com/132547242/236150078-58281f65-de66-4abc-a92c-2a3f41b9d4d7.png">

**Comment by zhouaihui** [comment]
> 我是在一台虚拟机上通过docker方式启动的secretflow镜像，在镜像里面看到的IP是172.17.0.2，我虚拟机IP是10.200.3.116

`listen_addr`保持`0.0.0.0：30222`，这个是服务的监听地址。`address`填写你的虚拟机ip，这个是对端访问的地址。

**Comment by Chrisdehe** [comment]
看上去是sf.init中address的端口号与spu配置中Alice的address端口号重复了
请详细阅读[仿真部署SPU配置](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#optional-how-to-setup-an-spu-in-cluster-mode)

**Comment by dyx0001** [comment]
@Chrisdehe SPU我这里已经可以正常启动了。现有个问题想咨询一下，那个隐语框架的计算层如SPU、PYU、HEU等是否可以不依赖框架独立部署？

**Comment by anakinxc** [comment]
> @Chrisdehe SPU我这里已经可以正常启动了。现有个问题想咨询一下，那个隐语框架的计算层如SPU、PYU、HEU等是否可以不依赖框架独立部署？

SPU 和 HEU 都有独立的包，理论上都可以独立部署

**Comment by dyx0001** [comment]
那ray可以远程调用独立部署的SPU和HEU么？

**Comment by dyx0001** [comment]
那个独立的包我在哪里可以下到？

**Comment by zhouaihui** [comment]
> 那ray可以远程调用独立部署的SPU和HEU么？

如果你不希望使用SecretFlow的框架（ray），想单独部署SPU或者HEU，那么可以直接使用spu/heu的包，`pip install -U sf-heu spu`即可，你可以直接裸用相关的接口。
如果你想使用SecretFlow框架，那建议直接使用SecretFlow里的HEU/SPU的概念，SF提供了一些封装让使用SPU、HEU更简单。
