### ISSUE TITLE
文档：拆分学习：银行营销中文文档夹杂英文

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#498]
### Issue Type

Documentation Bug

### Source

binary

### Secretflow Version

/

### OS Platform and Distribution

/

### Python version

/

### What happend and What you expected to happen.

```shell
文档：https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/Split_Learning_for_bank_marketing.html  小结部分， 中文文档存在英文。
```

### Reproduction code to reproduce the issue.

```shell
https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/Split_Learning_for_bank_marketing.html
```

**Comment by zhangxingmeng** [comment]
感谢反馈，这个问题我们会尽快处理
