### ISSUE TITLE
按照方式4: 通过WSL的方式，完成了Secretflow的安装，请问后面怎么用，如何使用sf开发？

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#501]
![图片](https://user-images.githubusercontent.com/8414952/236147977-dc8b82e9-3692-4f7d-a558-dd62b344cf94.png)
环境：
Python 3.8.16
pip 23.0.1

按照方式4: 通过WSL的方式，完成了Secretflow的安装，请问后面怎么用，如何使用sf开发？

**Comment by Niclouge** [comment]
可以先看他的各种例子，跑一下

**Comment by Mingbo-Lee** [comment]
通过使用Pycharm Professional 或者VScode连接WSL进行开发：
 Pycharm Professional： 
- https://www.jetbrains.com/help/pycharm/using-wsl-as-a-remote-interpreter.html


VScode: 
- https://learn.microsoft.com/zh-cn/windows/wsl/tutorials/wsl-vscode
- https://code.visualstudio.com/docs/remote/wsl#:~:text=Start%20VS%20Code.%20Press%20F1%2C%20select%20Remote-WSL%3A%20New,You%20will%20be%20prompted%20which%20distro%20to%20use.

供您参考

**Comment by wjwJack** [comment]
> 通过使用Pycharm Professional 或者VScode连接WSL进行开发： Pycharm Professional：
> 
>     * https://www.jetbrains.com/help/pycharm/using-wsl-as-a-remote-interpreter.html
> 
> 
> VScode:
> 
>     * https://learn.microsoft.com/zh-cn/windows/wsl/tutorials/wsl-vscode
> 
>     * https://code.visualstudio.com/docs/remote/wsl#:~:text=Start%20VS%20Code.%20Press%20F1%2C%20select%20Remote-WSL%3A%20New,You%20will%20be%20prompted%20which%20distro%20to%20use.
> 
> 
> 供您参考

赞
