### ISSUE TITLE
安装secretflow失败

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/secretflow#504]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

pip install -U secretflow

### OS Platform and Distribution

Ubuntu 20.04.6 LTS（windows上安装的wsl，64位操作系统）

### Python version

Python 3.8.16

### What happend and What you expected to happen.

```shell
pip install -U secretflow
安装失败

(sf-benchmark) root@lishihao:/home/lsh# pip install -U secretflow
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9456f2f640>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9456f2f9a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9456f2fca0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9456f2fe80>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9456f2ff70>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
ERROR: Could not find a version that satisfies the requirement secretflow (from versions: none)
ERROR: No matching distribution found for secretflow
```

### Reproduction code to reproduce the issue.

```shell
pip install -U secretflow
```

**Comment by anakinxc** [comment]
`Failed to establish a new connection:` 看起来是网络问题，试一下用个 mirror 呢

**Comment by daydayuphere** [comment]
@anakinxc 麻烦给个地址

**Comment by daydayuphere** [comment]
换了国内镜像，问题还是一样的 @anakinxc 
(sf-benchmark) root@lishihao:/home/lsh# pip install secretflow -i https://pypi.mirrors.ustc.edu.cn/simple/
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5549e3f730>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5549e3fa30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5549e3fcd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5549e3fee0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5549de7040>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/secretflow/
ERROR: Could not find a version that satisfies the requirement secretflow (from versions: none)
ERROR: No matching distribution found for secretflow

**Comment by anakinxc** [comment]
> 

试一下[这个](https://github.com/microsoft/WSL/issues/4020)呢

**Comment by daydayuphere** [comment]
过去了，又出现一个新问题
(base) root@lishihao:/home/lsh# pip install -U secretflow
Collecting secretflow
  Using cached secretflow-0.7.7b0.tar.gz (163 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4qttol2u/secretflow_a112ccc143ff4e16ab04a02477813e70/setup.py", line 100, in <module>
          install_requires=read_requirements(),
        File "/tmp/pip-install-4qttol2u/secretflow_a112ccc143ff4e16ab04a02477813e70/setup.py", line 17, in read_requirements
          with open('./requirements.txt') as file:
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by daydayuphere** [comment]
试了下这条命令，后来过去了
echo "export PATH=\"${HOME}/.local/bin:$PATH\"" >>"${HOME}"/.bashrc

出现了新问题 No such file or directory
(sf-benchmark) root@lishihao:/home/lsh# python
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import secretflow as sf
W0506 08:47:06.083735   299 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:434] Fail to open /proc/self/io: No such file or directory
>>>

**Comment by anakinxc** [comment]
> 试了下这条命令，后来过去了 echo "export PATH="${HOME}/.local/bin:$PATH"" >>"${HOME}"/.bashrc
> 
> 出现了新问题 No such file or directory (sf-benchmark) root@lishihao:/home/lsh# python Python 3.8.16 (default, Mar 2 2023, 03:21:46) [GCC 11.2.0] :: Anaconda, Inc. on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import secretflow as sf
> > > > W0506 08:47:06.083735   299 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:434] Fail to open /proc/self/io: No such file or directory


这是个 wsl 的 issue，在[这个](https://learn.microsoft.com/en-us/windows/wsl/release-notes#build-19013)版本应该已经fix了

**Comment by daydayuphere** [comment]
ok，多谢
