### ISSUE TITLE
关于PIR文档的说明

### ISSUE THREAD

**Issue by 472002463** [secretflow/secretflow#505]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

Ubuntu 18.4

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
请问下PIR这一块的文档只有API文档和SPU PIRquartstart那一块吗。
我看了关于星河杯PIR的Baseline https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw
其中提到自己可以设计对应的密码套件，那是如何接入呢
而且关于spu.pir_setup中的oprf_key_path这个参数的作用是什么呢，这里不应该是非对称密钥吗，我也没看到公钥在哪。
整个PIR的流程会在后续中的文档补充吗，我这边想了解的主要是加密的行为会在哪些步骤中体现。
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by zhanglei486** [comment]
[“星河杯”隐私计算大赛技术分享会](https://mp.weixin.qq.com/s/M2KZU2UNhZMFk7UbORlZvw)和隐语发布的Baseline对PIR的基本原理都有简单介绍，详细的原理介绍我们也列了参考文献

Baseline提到的选择密码套件是指设置通信安全的tls协议参数
<img width="484" alt="image" src="https://user-images.githubusercontent.com/47308800/236592135-42cc71a3-0437-4e79-ac27-54caa50b5d9b.png">

上面是labeled psi大体的协议流程，oprf_key_path用于对双方的数据oprf和prf，避免CLR17中可能的信息泄漏
oprf后面的步骤是进行FHE的加密，和密文的计算，会用到FHE的公钥

**Comment by 472002463** [comment]
我去看了下视频，加密类型是哪个参数呢，我看支持比如SM2，是在哪里配置

**Comment by zhanglei486** [comment]
目前透出的参数还不包含 oprf的曲线选择，代码里默认使用了CURVE_FOURQ，选择SM2的话，可以修改代码
https://github.com/secretflow/spu/blob/main/libspu/psi/core/labeled_psi/sender_db.cc#L764
https://github.com/secretflow/spu/blob/main/libspu/psi/core/labeled_psi/receiver.cc#L140

将对应的CURVE_FOURQ改为CURVE_SM2

**Comment by 472002463** [comment]
```python
    config = pir.PirSetupConfig(
        pir_protocol=pir.PirProtocol.Value('KEYWORD_PIR_LABELED_PSI'),
        store_type=pir.KvStoreType.Value('LEVELDB_KV_STORE'),
        input_path=pir_input_path,
        key_columns=key_columns,
        label_columns=label_columns,
        num_per_query=1,
        label_max_len=18,
        oprf_key_path=pir_oprf_key_path,
        setup_path=pir_setup_path,
    )

    report = pir.pir_setup(config)
```
这个代码除了会生成预处理文件之外，还会再当前目录生成一个 temp_file_*的目录，这是什么目录，为什么用secretflow.spu.pir_setup没这个目录呢
```python
    reports = spu.pir_setup(
        server='bob',
        input_path=pir_input_path,
        key_columns=key_columns,
        label_columns=label_columns,
        oprf_key_path=pir_oprf_key_path,
        setup_path=pir_setup_path,
        num_per_query=1,
        label_max_len=18,
    )
```

![image](https://user-images.githubusercontent.com/33944862/236614314-13999159-5f36-4f07-b397-6a6e86dfe6b5.png)

**Comment by zhanglei486** [comment]
这是服务端数据预处理过程中生成的一个中间数据目录，目录名称是随机生成的，目前调试用途没有把它设成用完删除，
可以修改下面的代码，将参数false设为true，会自动删除该临时文件夹。

https://github.com/secretflow/spu/blob/main/libspu/psi/core/labeled_psi/sender_db.cc#L1152

std::shared_ptr<yacl::io::KVStore> kv_store =
      std::make_shared<yacl::io::LeveldbKVStore>(false);

**Comment by dyx0001** [comment]
@zhanglei486 关于匿踪查询，目前只是针对双方的一种数据查询么？有没有多方参与的实现呢，就是说数据源来自多方，从不同数据源可获取不同属性数据的那种，类似数据库中多表联查的情景？

**Comment by zhanglei486** [comment]
PIR协议只是客户端 对 服务端的两方协议，只能查询服务端的一个数据源

**Comment by dyx0001** [comment]
@zhanglei486  基于Index PIR与Keyword PIR实现的匿踪查询是否用到了隐私求交的内容？

**Comment by dyx0001** [comment]
@Chrisdehe 我这里理解的keyword PIR匿踪查询的过程是：客户端将同态加密后的查询条件发给服务端，服务端先将其带入到判断是否存在key的多项式中进行计算，然后再将其带入获取查询结果的多项始终进行计算，最后将两个结果同时返回，客户端再对计算结果进行解密得到自己要查询的内容是否存在以及具体的结果。是这么一个流程么？

**Comment by Chrisdehe** [comment]
hi，@dyx0001 
是的，大致可以这么理解
spu / labeled psi / README.md里面有两个slide和相关视频
可以参考一下
https://github.com/secretflow/spu/blob/main/libspu/psi/core/labeled_psi/README.md
