### ISSUE TITLE
WOE分箱时提示“list of cases must be same length as list of conditions”

### ISSUE THREAD

**Issue by hanweidong** [secretflow/secretflow#510]
### Issue Type

Others

### Source

binary

### Secretflow Version

v0.8.2b1

### OS Platform and Distribution

CentOS Linux release 7.7.1908 (Core)

### Python version

3.8

### What happend and What you expected to happen.

```shell
你好，我在使用woe进行分箱时，提示“ValueError: list of cases must be same length as list of conditions
”，详细的错误日志如下：

(_run pid=6199) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=6199) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=6199) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=6199) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=6199) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=6199) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-05-06 16:13:33,190	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::VertWOESubstitutionPyuWorker.sub() (pid=6741, ip=10.3.70.138, repr=<secretflow.preprocessing.binning.vert_woe_substitution.VertWOESubstitutionPyuWorker object at 0x7f610e325250>)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/preprocessing/binning/vert_woe_substitution.py", line 69, in sub
    data[v] = np.select(condlist, choicelist, rule["else_woe"])
  File "<__array_function__ internals>", line 180, in select
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/numpy/lib/function_base.py", line 810, in select
    raise ValueError(
ValueError: list of cases must be same length as list of conditions
```
```


### Reproduction code to reproduce the issue.

```shell
我的代码如下：

import spu
import secretflow as sf
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.3.70.138:9923',
            'listen_addr': '0.0.0.0:9923'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.3.70.140:9924',
            'listen_addr': '0.0.0.0:9924'
        },
    },
    'self_party': 'alice'
}

# Use ray head adress please.
sf.init(address='10.3.70.138:9913', 
        cluster_config=cluster_config
)

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.3.70.138:9933',
            'listen_addr': '0.0.0.0:9933'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.3.70.140:9934',
            'listen_addr': '0.0.0.0:9934'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}


link_desc = {
    'connect_retry_times': 60,
    'recv_timeout_ms': 60 * 60 * 1000,
}

spu = sf.SPU(cluster_def=cluster_def, link_desc=link_desc)


alice, bob = sf.PYU('alice'), sf.PYU('bob')
# 转换成VDF
from secretflow.data.vertical import read_csv as v_read_csv

vdf = v_read_csv({alice: '/home/hwd/competition/code/competition/scam_call/data/alice_train_standard.csv', bob: '/home/hwd/competition/code/competition/scam_call/data/bob_train_standard.csv'})
vdf
from secretflow.preprocessing.binning.vert_woe_binning import VertWoeBinning

binning = VertWoeBinning(spu)
woe_rules = binning.binning(
    vdf,
    binning_method="chimerge",
    bin_num=4,
    bin_names={alice: alice_woe, bob: []},
    label_name="label",
)

print(f"woe_rules for alice:\n {sf.reveal(woe_rules[alice])}")

from secretflow.preprocessing.binning.vert_woe_substitution import VertWOESubstitution

woe_sub = VertWOESubstitution()
sub_data = woe_sub.substitution(vdf, woe_rules)

# print(sf.reveal(sub_data.partitions[alice].data))
```
```

**Comment by da-niao-dan** [comment]
您好，可以看一下`print(f"woe_rules for alice:\n {sf.reveal(woe_rules[alice])}")`的结果吗

**Comment by Niclouge** [comment]
我也碰到相同的问题，下面是woe_rules的结果

woe_rules for alice:
 {'variables': [{'name': 'mean radius', 'type': 'numeric', 'split_points': [11.366, 12.726, 14.058000000000002, 17.067999999999998], 'woes': [3.504202183627523, 2.0628480453246048, 0.8986675460509075, -0.8756945247885339, -5.248537325819967], 'ivs': [1.0662990366384157, 0.5346549767069321, 0.13581416668952853, 0.16146500044162557, 2.782867638441804], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'mean texture', 'type': 'numeric', 'split_points': [15.656, 17.912, 19.968, 22.44], 'woes': [2.0628480453246048, 0.8542157834800737, 0.2391369762899473, -0.9996397502306807, -1.1616529541821499], 'ivs': [0.5346549767069321, 0.12506692427385835, 0.01097039772843266, 0.21158011150236872, 0.27857937104812136], 'total_counts': [114, 114, 113, 115, 113], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'mean perimeter', 'type': 'numeric', 'split_points': [73.292, 81.938, 91.42, 111.68], 'woes': [4.206238311604714, 2.2057691782989663, 1.0157177124916383, -1.0226292684553795, -5.248537325819967], 'ivs': [1.3115456095814129, 0.5882808898045113, 0.16877630611879452, 0.219310497017854, 2.782867638441804], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'y', 'type': 'numeric', 'split_points': [], 'woes': [0.0], 'ivs': [0.0], 'total_counts': [569], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}]}

下面是bob的woe_rules
woe_rules for bob:
 {'variables': [{'name': 'compactness error', 'type': 'numeric', 'split_points': [0.0118, 0.01702, 0.024480000000000005, 0.03619800000000001], 'woes': [1.3759704777782547, 0.8431659472934887, 0.041944545204120845, -0.8396032382261612, -0.8756945247885339], 'ivs': [0.28806950240997364, 0.121087292969887, 0.00034748731360635996, 0.14849808343765386, 0.16146500044162557], 'total_counts': [115, 113, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'concavity error', 'type': 'numeric', 'split_points': [0.013212000000000002, 0.020456000000000002, 0.030544, 0.046404], 'woes': [2.793036497564899, 1.22034812733954, -0.3970968584376477, -0.8756945247885339, -1.0226292684553795], 'ivs': [0.8079006792015587, 0.23372107850783036, 0.032535246804765244, 0.16146500044162557, 0.219310497017854], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'worst fractal dimension', 'type': 'numeric', 'split_points': [0.069654, 0.076852, 0.08320200000000001, 0.09593400000000002], 'woes': [0.6009932789706772, 0.648921745542628, 0.36436956609977483, -0.13028319842061503, -1.2943393953411082], 'ivs': [0.06540062160565639, 0.07549489944377728, 0.024933539226662627, 0.003453148565505971, 0.3456975917951635], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}]}

![image](https://github.com/secretflow/secretflow/assets/44387768/7c8e1007-5ffd-4c9c-a3d2-0cf59ff0965b)

**Comment by warriorpaw** [comment]
> @da-niao-dan 我也碰到相同的问题，下面是woe_rules的结果
> 
> woe_rules for alice: {'variables': [{'name': 'mean radius', 'type': 'numeric', 'split_points': [11.366, 12.726, 14.058000000000002, 17.067999999999998], 'woes': [3.504202183627523, 2.0628480453246048, 0.8986675460509075, -0.8756945247885339, -5.248537325819967], 'ivs': [1.0662990366384157, 0.5346549767069321, 0.13581416668952853, 0.16146500044162557, 2.782867638441804], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'mean texture', 'type': 'numeric', 'split_points': [15.656, 17.912, 19.968, 22.44], 'woes': [2.0628480453246048, 0.8542157834800737, 0.2391369762899473, -0.9996397502306807, -1.1616529541821499], 'ivs': [0.5346549767069321, 0.12506692427385835, 0.01097039772843266, 0.21158011150236872, 0.27857937104812136], 'total_counts': [114, 114, 113, 115, 113], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'mean perimeter', 'type': 'numeric', 'split_points': [73.292, 81.938, 91.42, 111.68], 'woes': [4.206238311604714, 2.2057691782989663, 1.0157177124916383, -1.0226292684553795, -5.248537325819967], 'ivs': [1.3115456095814129, 0.5882808898045113, 0.16877630611879452, 0.219310497017854, 2.782867638441804], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'y', 'type': 'numeric', 'split_points': [], 'woes': [0.0], 'ivs': [0.0], 'total_counts': [569], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}]}
> 
> 下面是bob的woe_rules woe_rules for bob: {'variables': [{'name': 'compactness error', 'type': 'numeric', 'split_points': [0.0118, 0.01702, 0.024480000000000005, 0.03619800000000001], 'woes': [1.3759704777782547, 0.8431659472934887, 0.041944545204120845, -0.8396032382261612, -0.8756945247885339], 'ivs': [0.28806950240997364, 0.121087292969887, 0.00034748731360635996, 0.14849808343765386, 0.16146500044162557], 'total_counts': [115, 113, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'concavity error', 'type': 'numeric', 'split_points': [0.013212000000000002, 0.020456000000000002, 0.030544, 0.046404], 'woes': [2.793036497564899, 1.22034812733954, -0.3970968584376477, -0.8756945247885339, -1.0226292684553795], 'ivs': [0.8079006792015587, 0.23372107850783036, 0.032535246804765244, 0.16146500044162557, 0.219310497017854], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}, {'name': 'worst fractal dimension', 'type': 'numeric', 'split_points': [0.069654, 0.076852, 0.08320200000000001, 0.09593400000000002], 'woes': [0.6009932789706772, 0.648921745542628, 0.36436956609977483, -0.13028319842061503, -1.2943393953411082], 'ivs': [0.06540062160565639, 0.07549489944377728, 0.024933539226662627, 0.003453148565505971, 0.3456975917951635], 'total_counts': [114, 114, 113, 114, 114], 'else_woe': -0.5211495071076266, 'else_iv': 0.0004992249255496925, 'else_counts': 0}]}
> 
> ![image](https://user-images.githubusercontent.com/44387768/237551770-7c8e1007-5ffd-4c9c-a3d2-0cf59ff0965b.png)

不要在Y标上做分箱

**Comment by Niclouge** [comment]
好的，修改之后程序运行正确，这里确实没有注意到，我觉得楼主的问题可能也是这个原因引起的
