### ISSUE TITLE
通过spu进行函数计算出现混乱问题

### ISSUE THREAD

**Issue by hy928302776** [secretflow/secretflow#511]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow/secretflow-anolis8:0.7.18b2

### OS Platform and Distribution

Centos7 4c32g

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
将SPU和sf初始化后，通过SPU进行函数运算，然后sf.reveal出计算结果，出现的结果混乱，循环前几次是对的，后边就开始乱了，看着像是缓存的问题，代码如下：
import json
import re
import sys
import secretflow as sf
import numpy as np
import pandas as pd
from dvadmin.dev_centre.sflib.item.init_data import init

def getFunAndElements(formulas: list):
    """
    将公式转为函数返回
    """
    map: dict = {}
    if formulas and len(formulas) > 0:
        for formula in formulas:
            formulaArray: list = formula.split("=")
            elements = re.findall(r'[a-zA-Z]+(?:_+[a-zA-Z]+)?\d*', formulaArray[1])
            map.update({formulaArray[0]: {"func": eval(f"(lambda {','.join(elements)}:{formulaArray[1]})"),
                                          "elements": elements}})
    return map


initdata = {
    "deviceList": [
        {
            "node_alias": "alice",
            "ip": "127.0.0.1",
            "port": "10003"
        },
        {
            "node_alias": "bob",
            "ip": "127.0.0.1",
            "port": "10004"
        }
    ],
    "address": "local",
    "selfDevice": {
        "node_alias": "alice",
        "ip": "127.0.0.1",
        "port": "10003"
    },
    "projectId": 000,
    "flowId": "flowId"
}
print(f"初始化数据：{initdata}")
spu, pyuMap, selfPyu = init(initdata)

for item in range(1, 11):
    df=pd.DataFrame({'A':['1','2','3'],'B':['2','3','4']})
    print(f"df:{df}")
    #df.eval('C=A+B',inplace=True)
    funAndElement = getFunAndElements(['C=A+B','D=A-B'])
    funcC = funAndElement['C']["func"]
    funcD = funAndElement['D']["func"]
    data ={'A':pd.to_numeric(df['A']),'B':pd.to_numeric(df['B'])}
    spuObjC =spu(funcC)(**data)
    spuObjD =spu(funcD)(**data)

    item_result_C = np.round(sf.reveal(spuObjC), 2).astype(str)
    item_result_D = np.round(sf.reveal(spuObjD), 2).astype(str)
    print(f"item_result_C:{item_result_C}")
    print(f"item_result_D:{item_result_D}")
```

### Reproduction code to reproduce the issue.

```shell
结果如下：
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['3' '5' '7']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['3' '5' '7']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['3' '5' '7']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['3' '5' '7']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['3' '5' '7']
```

**Comment by Chrisdehe** [comment]
hi，@hy928302776 
辛苦更新下版本哈～
目前最新的版本是[0.8.2b1](https://www.secretflow.org.cn/docs/secretflow/en/getting_started/installation.html)

**Comment by hy928302776** [comment]
刚才升级到了新的版本[0.8.2b1]，还是不行
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['-1' '-1' '-1']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['3' '5' '7']
item_result_D:['3' '5' '7']
df:   A  B
0  1  2
1  2  3
2  3  4
item_result_C:['-1' '-1' '-1']
item_result_D:['3' '5' '7']

**Comment by hy928302776** [comment]
升级之后还出现了以下问题：
(_spu_compile pid=73109) W0509 11:54:49 12291 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
W0509 11:54:50  6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
(_spu_compile pid=73109) W0509 11:54:50 12291 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
W0509 11:54:51  6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
(_spu_compile pid=73109) W0509 11:54:51 12291 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
W0509 11:54:52  6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
(_spu_compile pid=73109) W0509 11:54:52 12291 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
W0509 11:54:53  6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument

**Comment by anakinxc** [comment]
> 升级之后还出现了以下问题：
> (_spu_compile pid=73109) W0509 11:54:[49 12291](tel:49 12291) external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> W0509 11:54:50 6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> (_spu_compile pid=73109) W0509 11:54:[50 12291](tel:50 12291) external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> W0509 11:54:51 6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> (_spu_compile pid=73109) W0509 11:54:[51 12291](tel:51 12291) external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> W0509 11:54:52 6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> (_spu_compile pid=73109) W0509 11:54:[52 12291](tel:52 12291) external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
> W0509 11:54:53 6919 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument

这个是 macOS 的 warning，但是我看你反馈的是 centos

**Comment by hy928302776** [comment]
1、 Fail to proc_pid_rusage: Invalid argument这个错误是本地升级到0.8.2b1后出现的，我在macOS上测试的，这个可以关掉吗？为啥会出现这个呢
2、上边计算结果混乱的问题还是没有解决，辛苦看下怎么解决下

**Comment by anakinxc** [comment]
> 1、 Fail to proc_pid_rusage: Invalid argument这个错误是本地升级到0.8.2b1后出现的，我在macOS上测试的，这个可以关掉吗？为啥会出现这个呢 2、上边计算结果混乱的问题还是没有解决，辛苦看下怎么解决下

第一个 warning 是 brpc 的，我们后续尝试 patch 一下
第二个问题我们在定位

**Comment by hy928302776** [comment]
这个问题是否解决了，我需要做什么

**Comment by anakinxc** [comment]
> 这个问题是否解决了，我需要做什么

等 secretflow 发新版本以后更新就行

**Comment by hy928302776** [comment]
非常感谢，计算混乱问题已经解决，，

这个问题还有

(_spu_compile pid=86152) W0510 14:27:20 20483 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
(_spu_compile pid=86146) W0510 14:27:20 20739 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
W0510 14:27:21 10243 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument
W0510 14:27:22 10243 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument

**Comment by anakinxc** [comment]
> 非常感谢，计算混乱问题已经解决，，
> 
> 这个问题还有
> 
> (_spu_compile pid=86152) W0510 14:27:20 20483 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument (_spu_compile pid=86146) W0510 14:27:20 20739 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument W0510 14:27:21 10243 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument W0510 14:27:22 10243 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:453] Fail to proc_pid_rusage: Invalid argument

Hi @hy928302776 

能提供一下你机器的具体配置和 OS 信息吗

**Comment by hy928302776** [comment]
型号名称：	MacBook Pro
  型号标识符：	MacBookPro18,1
  芯片：	Apple M1 Pro
  核总数：	10（8性能和2能效）
  内存：	16 GB
  系统固件版本：	7459.141.1
  操作系统加载程序版本：	7459.141.1

  激活锁状态：	已启用

**Comment by hy928302776** [comment]
macos Monterey 版本 12.5
