### ISSUE TITLE
多机构部署启动SPU进行求交问题

### ISSUE THREAD

**Issue by xiaohuangpian** [secretflow/secretflow#516]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

openEuler release 20.03  &&  BigCloud Enterprise Linux release 7.8.2105

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
两个机构独立部署后初始化spu时出现问题。
(SPURuntime pid=1062) 2023-05-09 07:05:12.303 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=10.10.167.226:6868} (0x0x4033540): Connection refused [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
(SPURuntime pid=1062) 2023-05-09 07:05:13.304 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
(SPURuntime pid=1062) 2023-05-09 07:05:14.304 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
(SPURuntime pid=1062) 2023-05-09 07:05:15.304 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
```

### Reproduction code to reproduce the issue.

```shell
spu = sf.SPU(cluster_def,link_desc)
```

**Comment by Chrisdehe** [comment]
你好，@xiaohuangpian 
可以贴下执行代码吗？

**Comment by xiaohuangpian** [comment]
-- 初始化secretflow
--A ray 集群节点
ray start --head --node-ip-address="10.10.167.226" --port="58581" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

--B ray 集群节点
ray start --head --node-ip-address="10.4.114.88" --port="58581" --resources='{"bob": 16}' --include-dashboard=False --disable-usage-stats

--检查hash值是否相同
ray status

-- A主节点初始化

python

import secretflow as sf
cluster_config ={
    'parties': {
        'alice': {
            'address': '10.10.167.226:5858',
            'listen_addr': '10.4.114.88:5858'
        },
        'bob': {
            'address': '10.4.114.88:5858',
            'listen_addr': '10.10.167.226:5858'
        },
    },
    'self_party': 'alice'
}
sf.init(address='10.10.167.226:58581', cluster_config=cluster_config)



-- B主节点初始化


python

import secretflow as sf
cluster_config ={
    'parties': {
        'alice': {
            'address': '10.10.167.226:5858',
            'listen_addr': '10.4.114.88:5858'
        },
        'bob': {
            'address': '10.4.114.88:5858',
            'listen_addr': '10.10.167.226:5858'
        },
    },
    'self_party': 'bob'
}
sf.init(address='10.4.114.88:58581', cluster_config=cluster_config)

**Comment by xiaohuangpian** [comment]
-- A节点SPU设备初始化
import spu
cluster_def={
	'nodes': [
		{
			'party': 'alice',
			'address': '10.10.167.226:6868',
			'listen_addr': '10.4.114.88:6868'
		},
		{
			'party': 'bob',
			'address': '10.4.114.88:6868',
			'listen_addr': '10.10.167.226:6868'
		}
	],
	'runtime_config': {
		'protocol': spu.spu_pb2.SEMI2K,
		'field': spu.spu_pb2.FM128,
		'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
	}
}

link_desc = {
'recv_timeout_ms': 3600000,
}
spu = sf.SPU(cluster_def,link_desc)






-- B节点SPU设备初始化
import spu
cluster_def={
    'nodes': [
		{
            'party': 'bob',
            'address': '10.4.114.88:6868',
            'listen_addr': '10.10.167.226:6868'
        },
        {
            'party': 'alice',
            'address': '10.10.167.226:6868',
            'listen_addr': '10.4.114.88:6868'
        }
        
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

link_desc = {
'recv_timeout_ms': 3600000,
}
spu = sf.SPU(cluster_def,link_desc)

**Comment by xiaohuangpian** [comment]
文档上写的是同时执行代码，SPU初始化分别是B端先、A端后执行；
    B端提示：
(SPURuntime pid=1062) 2023-05-09 07:05:12.303 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=10.10.167.226:6868} (0x0x4033540): Connection refused [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
(SPURuntime pid=1062) 2023-05-09 07:05:13.304 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
(SPURuntime pid=1062) 2023-05-09 07:05:14.304 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0
(SPURuntime pid=1062) 2023-05-09 07:05:15.304 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R1][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R2][E112]Not connected to 10.10.167.226:6868 yet, server_id=0 [R3][E112]Not connected to 10.10.167.226:6868 yet, server_id=0

   A端没任何log；后我再等B端打完log后，在次在B端重新执行spu = sf.SPU(cluster_def,link_desc)，无任何log。
后续我再准备测试数据：
-- A、B端都执行
import numpy as np
from sklearn.datasets import load_iris
data, target = load_iris(return_X_y=True, as_frame=True)
data['uid'] = np.arange(len(data)).astype('str')
data['month'] = ['Jan'] * 75 + ['Feb'] * 75
--  A端执行
import os
os.makedirs('.data', exist_ok=True)
da = data.sample(frac=0.9)
da.to_csv('.data/alice.csv', index=False)
-- B端执行
import os
os.makedirs('.data', exist_ok=True)
db = data.sample(frac=0.8)
db.to_csv('.data/bob.csv', index=False)
-- A端执行
bob = sf.PYU('bob')
alice = sf.PYU('alice')
input_path = {alice: '.data/alice.csv', bob: '.data/bob.csv'}
output_path = {alice: '.data/alice_psi.csv', bob: '.data/bob_psi.csv'}
spu.psi_csv('id', input_path, output_path, 'alice')

在等待A端结果后得到log：
(SPURuntime pid=401) 2023-05-09 06:59:29.572 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=401) 2023-05-09 06:59:29.572 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: .data/alice.csv, precheck_switch:true
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1622, in psi_csv
    return dispatch(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 300, in psi_csv
    return sfd.get(res)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 73, in get
    return fed.get(object_refs)
  File "/usr/local/lib/python3.8/site-packages/fed/api.py", line 411, in get
    values = ray.get(ray_refs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=401, ip=10.10.167.226, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f74f78439a0>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/usr/local/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=root:3:ALLGATHER
stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7f750ea72997
#1 yacl::link::AllGatherImpl<>()+0x7f750ea6d51d
#2 yacl::link::AllGather()+0x7f750ea6dab3
#3 spu::psi::SyncWait<>()+0x7f750e8b092a
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f750d7a8688
#5 pybind11::cpp_function::dispatcher()+0x7f750d7835c6
#6 PyCFunction_Call+0x4e0212
2023-05-09 07:59:30 WARNING cleanup.py:59 [alice] --  Failed to send ObjectRef(82891771158d68c18ce3259815516e1f6e896fc20100000001000000) with error: ray::SendProxyActor.send() (pid=341, ip=10.10.167.226, repr=<fed.barriers.SendProxyActor object at 0x7f45e861f2e0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.psi_csv() (pid=401, ip=10.10.167.226, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f74f78439a0>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/usr/local/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=root:3:ALLGATHER
stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7f750ea72997
#1 yacl::link::AllGatherImpl<>()+0x7f750ea6d51d
#2 yacl::link::AllGather()+0x7f750ea6dab3
#3 spu::psi::SyncWait<>()+0x7f750e8b092a
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f750d7a8688
#5 pybind11::cpp_function::dispatcher()+0x7f750d7835c6
#6 PyCFunction_Call+0x4e0212
2023-05-09 07:59:30 WARNING cleanup.py:62 [alice] --  Signal self to exit.
*** SIGTERM received at time=1683619170 on cpu 3 ***
PC: @     0x7f024ce0e838  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f024ce12ce0  (unknown)  (unknown)
[2023-05-09 07:59:30,118 E 251 251] logging.cc:361: *** SIGTERM received at time=1683619170 on cpu 3 ***
[2023-05-09 07:59:30,118 E 251 251] logging.cc:361: PC: @     0x7f024ce0e838  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2023-05-09 07:59:30,118 E 251 251] logging.cc:361:     @     0x7f024ce12ce0  (unknown)  (unknown)
2023-05-09 07:59:30 INFO cleanup.py:66 [alice] --  Check sending thread was exited.

**Comment by Chrisdehe** [comment]
'listen_addr'改为'0.0.0.0:xxxx'

**Comment by xiaohuangpian** [comment]
改完后重新执行一次后，还是同样的log。老师您看，还有可能是什么问题呢？

**Comment by Chrisdehe** [comment]
> 'listen_addr'改为'0.0.0.0:xxxx'

这里指的是全部的listen_addr都要改为0.0.0.0:xxxx哈

**Comment by Chrisdehe** [comment]
> 改完后重新执行一次后，还是同样的log。老师您看，还有可能是什么问题呢？> 改完后重新执行一次后，还是同样的log。老师您看，还有可能是什么问题呢？
看起来是csv文件的问题，辛苦检查一下。

**Comment by xiaohuangpian** [comment]
是的老师，全部更改为0.0.0.0:xxxx了。然后关于csv文件问题，是这样的老师，根据官方文档**[准备数据集](https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/PSI_On_SPU.html )**

**Comment by Chrisdehe** [comment]
> 
发现了一个问题。
请注意，PSI求交只需要在一端执行即可。

**Comment by Chrisdehe** [comment]
隐私求交也可以参考一下我们官网的[隐语PSI Benchmark白皮书](https://www.secretflow.org.cn/docs/secretflow/zh_CN/developer/benchmark/psi_benchmark.html)
介绍的会更详细一些，希望可以帮助到您。

**Comment by Chrisdehe** [comment]
我发现您是在python中分段执行的，这可能会出现超时的错误，建议将文档代码放入一个脚本来执行。
另外，为了更好的解决此issue，辛苦您添加下我们隐语小助手的微信（secretflow01）
祝好

**Comment by xiaohuangpian** [comment]
好的，谢谢老师。确实是分段执行的。因为是两个独立的服务器，总会有先后执行的可能性，且在初始化secretflow的时候，时间差都在1秒内，能够正确显示log已连接的状态；初始化两个服务器的spu的时候，也是时间差在1秒内，这会产生超时错误吗？
隐语小助手上个月已经添加了
再次感谢老师解答问题。

**Comment by Chrisdehe** [comment]
是的，因为不是一个整体的话会有超时错误发生，您可以尝试一下。
另外您的微信名是？或者辛苦跟小助手打个招呼？
