### ISSUE TITLE
多方PSI详情了解

### ISSUE THREAD

**Issue by Niyci** [secretflow/secretflow#520]
![image](https://github.com/secretflow/secretflow/assets/87159755/de806788-6f90-41e6-958c-4eaebd9bba37)
隐语PSI Benchmark白皮书提到三方PSI中会泄漏两方交集大小，根据这个情况看本协议应该是通过多次双方PSI实现的。
我有几个问题：
1）该三方PSI方案是否有扩展为多方（三方以上）可能，贵公司有没有相关用例。
2）白皮书内提到（如下图）三方PSI使用了百万分桶，请问百万分桶是分为一百万个桶还是一个桶内有一百万个元素
![image](https://github.com/secretflow/secretflow/assets/87159755/db22cc51-24bd-47cb-aeb1-37eeda126664)
3）同样是分桶的问题，交集数据的交集比例大约在多少（结果数量是多少）

**Comment by zhanglei486** [comment]
1) 可以扩展到三方以上，但协议交互相对复杂
2）一个桶内有一百万个元素
3）交集数据的交集比例 不同数据集会有不同的比例，benchmark是按50%交集数量生成的测试数据

**Comment by Niyci** [comment]
感谢

**Comment by dyx0001** [comment]
@zhanglei486 有多方PSI的测试案例么，且测试案例的数据源是多列那种？

**Comment by zhanglei486** [comment]
> @zhanglei486 有多方PSI的测试案例么，且测试案例的数据源是多列那种？

参见：
https://github.com/secretflow/secretflow/blob/main/tests/device/test_psi.py#L507

**Comment by dyx0001** [comment]
好的
