### ISSUE TITLE
生产模式下，常驻服务中多次执行错误

### ISSUE THREAD

**Issue by allenkang** [secretflow/secretflow#529]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

centos7.9

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
生产模式，三个参与方ABC，分别有一个ecs部署docker环境。启动示例：
alice：
docker run -it -d -p 9881:9881 -v /root/sf/:/root/sf/ --shm-size=2.09gb --network host secretflow/secretflow-anolis8:0.8.2b1
ray start --head --port=31231 --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

每个参与方的ecs都部署了一个restful接口服务，接口提供了求平均等聚合功能。

同时调用AB参与方接口（即同时执行driver程序），正常执行，接口都能获取到平均值。完成后，同时调用AC参与方的接口，则A参与方执行时，rayfed会往B参与方发送数据，但B却不存在集群（AC）。报错如下：
<class 'secretflow.device.device.spu.SPU'>
====================================================
{'parties': {'alice': {'address': '192.168.0.98:40345', 'listen_addr': '0.0.0.0:40345'}, 'carol': {'address': '192.168.0.133:40345', 'listen_addr': '0.0.0.0:40345'}}, 'self_party': 'alice'}
2023-05-11 10:02:51 INFO cleanup.py:103 [alice] --  Notify check sending thread to exit.
2023-05-11 10:02:51 INFO cleanup.py:66 [alice] --  Check sending thread was exited.
2023-05-11 10:02:52 INFO api.py:235 [alice] --  Shutdowned ray.
192.168.0.98:31231
2023-05-11 10:02:52,353 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 192.168.0.98:31231...
2023-05-11 10:02:52,358 INFO worker.py:1538 -- Connected to Ray cluster.
2023-05-11 10:02:52 INFO api.py:202 [alice] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': {'address': '192.168.0.98:40345', 'listen_addr': '0.0.0.0:40345'}, 'carol': {'address': '192.168.0.133:40345', 'listen_addr': '0.0.0.0:40345'}}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600}
2023-05-11 10:02:53 INFO barriers.py:353 [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=3383) 2023-05-11 10:02:53 INFO barriers.py:114 [alice] --  Successfully start Grpc service without credentials.
2023-05-11 10:02:54 INFO barriers.py:388 [alice] --  SendProxy was successfully created.
2023-05-11 10:02:54 INFO barriers.py:463 [alice] --  Try ping ['carol'] at 0 attemp, up to 3600 attemps.
2023-05-11 10:02:54 INFO barriers.py:449 [alice] --  Failed to ping carol on 192.168.0.133:40345, this could be normal, the possible reason is carol has not yet started.
2023-05-11 10:02:56 INFO barriers.py:463 [alice] --  Try ping ['carol'] at 1 attemp, up to 3600 attemps.
2023-05-11 10:02:56 INFO barriers.py:449 [alice] --  Failed to ping carol on 192.168.0.133:40345, this could be normal, the possible reason is carol has not yet started.
2023-05-11 10:02:58 INFO barriers.py:463 [alice] --  Try ping ['carol'] at 2 attemp, up to 3600 attemps.
2023-05-11 10:02:58 INFO barriers.py:444 [alice] --  Succeeded to ping carol on 192.168.0.133:40345, the result: OK.
{'nodes': [{'party': 'alice', 'id': 'local:0', 'address': '192.168.0.98:43345', 'listen_addr': '0.0.0.0:43345'}, {'party': 'carol', 'id': 'local:1', 'address': '192.168.0.133:43345', 'listen_addr': '0.0.0.0:43345'}], 'runtime_config': {'protocol': 4, 'field': 3, 'sigmoid_mode': 3}}
<secretflow.device.device.spu.SPU object at 0x7f039f65eb50>
====================================================
[['alice', '/root/sf/01/wages1.csv'], ['carol', '/root/sf/03/wages3.csv']]
<secretflow.security.aggregation.spu_aggregator.SPUAggregator object at 0x7f034f8ef8e0>
2023-05-11 10:02:58 INFO cleanup.py:85 [alice] --  Start check sending thread.
(SPURuntime pid=3460) 2023-05-11 10:02:59.755 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=192.168.0.133:43345} (0x0x3b5a500): Connection refused [R1][E112]Not connected to 192.168.0.133:43345 yet, server_id=0 [R2][E112]Not connected to 192.168.0.133:43345 yet, server_id=0 [R3][E112]Not connected to 192.168.0.133:43345 yet, server_id=0
2023-05-11 10:03:00 WARNING cleanup.py:59 [alice] --  Failed to send ObjectRef(f4b89186c91aaa5cdb5eb18b20eccb46383752480d00000001000000) with error: ray::SendProxyActor.send() (pid=3421, ip=192.168.0.98, repr=<fed.barriers.SendProxyActor object at 0x7f49b05242b0>)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/fed/barriers.py", line 218, in send
    assert (
AssertionError: Failed to find bob in cluster {'alice': {'address': '192.168.0.98:40345', 'listen_addr': '0.0.0.0:40345'}, 'carol': {'address': '192.168.0.133:40345', 'listen_addr': '0.0.0.0:40345'}}.
2023-05-11 10:03:00 WARNING cleanup.py:62 [alice] --  Signal self to exit.
*** SIGTERM received at time=1683799380 on cpu 4 ***
2023-05-11 10:03:00 INFO cleanup.py:66 [alice] --  Check sending thread was exited.
PC: @     0x7f03a0b2fa07  (unknown)  epoll_wait
    @     0x7f03a1a12ce0  2031565456  (unknown)
    @           0x710f80  (unknown)  (unknown)
[2023-05-11 10:03:00,052 E 3080 3080] logging.cc:361: *** SIGTERM received at time=1683799380 on cpu 4 ***
[2023-05-11 10:03:00,052 E 3080 3080] logging.cc:361: PC: @     0x7f03a0b2fa07  (unknown)  epoll_wait
[2023-05-11 10:03:00,055 E 3080 3080] logging.cc:361:     @     0x7f03a1a12ce0  2031565456  (unknown)
[2023-05-11 10:03:00,061 E 3080 3080] logging.cc:361:     @           0x710f80  (unknown)  (unknown)

C端执行日志如下：
<class 'secretflow.device.device.spu.SPU'>
====================================================
{'parties': {'carol': {'address': '192.168.0.133:40345', 'listen_addr': '0.0.0.0:40345'}, 'alice': {'address': '192.168.0.98:40345', 'listen_addr': '0.0.0.0:40345'}}, 'self_party': 'carol'}
192.168.0.133:31233
2023-05-11 10:02:55,794 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 192.168.0.133:31233...
2023-05-11 10:02:55,806 INFO worker.py:1538 -- Connected to Ray cluster.
2023-05-11 10:02:55 INFO api.py:202 [carol] --  Started rayfed with {'CLUSTER_ADDRESSES': {'carol': {'address': '192.168.0.133:40345', 'listen_addr': '0.0.0.0:40345'}, 'alice': {'address': '192.168.0.98:40345', 'listen_addr': '0.0.0.0:40345'}}, 'CURRENT_PARTY_NAME': 'carol', 'TLS_CONFIG': {}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600}
2023-05-11 10:02:56 INFO barriers.py:353 [carol] --  RecverProxy was successfully created.
(RecverProxyActor pid=19897) 2023-05-11 10:02:56 INFO barriers.py:114 [carol] --  Successfully start Grpc service without credentials.
2023-05-11 10:02:57 INFO barriers.py:388 [carol] --  SendProxy was successfully created.
2023-05-11 10:02:57 INFO barriers.py:463 [carol] --  Try ping ['alice'] at 0 attemp, up to 3600 attemps.
2023-05-11 10:02:57 INFO barriers.py:444 [carol] --  Succeeded to ping alice on 192.168.0.98:40345, the result: OK.
{'nodes': [{'party': 'carol', 'id': 'local:0', 'address': '192.168.0.133:43345', 'listen_addr': '0.0.0.0:43345'}, {'party': 'alice', 'id': 'local:1', 'address': '192.168.0.98:43345', 'listen_addr': '0.0.0.0:43345'}], 'runtime_config': {'protocol': 4, 'field': 3, 'sigmoid_mode': 3}}
<secretflow.device.device.spu.SPU object at 0x7f8032a79fa0>
====================================================
[['alice', '/root/sf/01/wages1.csv'], ['carol', '/root/sf/03/wages3.csv']]
<secretflow.security.aggregation.spu_aggregator.SPUAggregator object at 0x7f8013a82fd0>
(SPURuntime pid=19975) 2023-05-11 10:04:59,940  ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=19975, ip=192.168.0.133, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f2705adcdc0>)
(SPURuntime pid=19975)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 306, in __init__
(SPURuntime pid=19975)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=19975) RuntimeError: what: 
(SPURuntime pid=19975)  [external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=connect_0
(SPURuntime pid=19975) stacktrace: 
(SPURuntime pid=19975) #0 yacl::link::ChannelBase::TestRecv()+0x7f2711ee6c43
(SPURuntime pid=19975) #1 yacl::link::Context::ConnectToMesh()+0x7f2711ee1e34
(SPURuntime pid=19975) #2 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f2710c093ed
(SPURuntime pid=19975) #3 pybind11::cpp_function::dispatcher()+0x7f2710bf05c6
(SPURuntime pid=19975) #4 PyCFunction_Call+0x4e0212
```

### Reproduction code to reproduce the issue.

```shell
接口代码：

def sf_init(ccfg,sf):
    sf.shutdown()
    print(settings.party_ip + ':' + str(settings.party_ray_port))
    sf.init(address=settings.party_ip + ':' + str(settings.party_ray_port), cluster_config=ccfg)


def sf_spu(cdef,sf):
    sfspu = sf.SPU(cluster_def=cdef)
    return sfspu

@app.post(base_url + "/aggregator", summary='求平均(mean)、求和(sum)、最小(min)、最大(max)、计数(count)', tags=["测试"])
async def average(item: Item):
    #result = await sync_to_async(func=averagefunc(item))()
    result = await aioify(averagefunc(item))(name="World"+str(item.port))
    return result

def averagefunc(item: Item):
    import secretflow as sf
    import spu
    from secretflow.data.horizontal import read_csv as h_read_csv
    from secretflow.data.vertical import read_csv as v_read_csv
    from secretflow.security.aggregation import SPUAggregator
    from secretflow.security.compare import SPUComparator

    print(sf.SPU)
    print("====================================================")
    parties01 = settings.party_name
    parties02 = item.unionname
    ccfg = sf_config(item.unionaddress, item.port, parties02, parties01)
    print(ccfg)
    # sf.init(address=settings.party_ip + ':' + str(settings.party_ray_port), cluster_config=ccfg)
    sf_init(ccfg,sf)
    cdef = spu_config(item.unionaddress, item.port + 3000, parties02, parties01,spu)
    print(cdef)
    # 构建两方计算密文设备
    spu_2pc = sf_spu(cdef,sf)  # sf.SPU(cluster_def=cdef)
    print(spu_2pc)
    # 两参与方，明文设备
    parties = [[parties01, item.csvpath], [parties02, item.unioncsvpath]]
    parties.sort()
    print("====================================================")
    print(parties)
    party01, party02 = sf.PYU(parties[0][0]), sf.PYU(parties[1][0])
    # 安全聚合
    comp = SPUComparator(spu_2pc)
    aggr = SPUAggregator(spu_2pc)
    print(aggr)

    hvdf = {}
    t0 = time.time()
    if 'vertical' == item.dataframe:
        hvdf = v_read_csv({party01: parties[0][1], party02: parties[1][1]},
                          aggregator=aggr,
                          comparator=comp)
    else:
        # 读取两方数据为横向dataframe
        hvdf = h_read_csv({party01: parties[0][1], party02: parties[1][1]},
                          aggregator=aggr,
                          comparator=comp)
    result = {}
    print("aggregator type:" + item.type)
    if "mean" == item.type:
        result = sf.reveal(hvdf.mean(numeric_only=True))
    elif "sum" == item.type:
        result = sf.reveal(hvdf.sum(numeric_only=True))
    elif "min" == item.type:
        result = sf.reveal(hvdf.min(numeric_only=True))
    elif "max" == item.type:
        result = sf.reveal(hvdf.max(numeric_only=True))
    elif "count" == item.type:
        result = sf.reveal(hvdf.count(numeric_only=True))
    else:
        result = sf.reveal(hvdf.sum(numeric_only=True))
    t1 = time.time()
    print(result)
    print("time cost:\n", float(t1 - t0) * 1000.0, "ms")
    # sf.shutdown()
    return str(result)
```

**Comment by allenkang** [comment]
采用单机仿真部署，多次执行无异常
import secretflow as sf
sf.init(parties=['alice', 'bob'], address='local')

**Comment by Chrisdehe** [comment]
hi,@allenkang 
请检查IP是否互相可ping的到，port是否为未被占用的（Ray节点启动、RayFed、SPU三者之间的port不可重复）
祝好

**Comment by allenkang** [comment]
> hi,@allenkang 请检查IP是否互相可ping的到，port是否为未被占用的（Ray节点启动、RayFed、SPU三者之间的port不可重复） 祝好

网络都是没用问题的，目前看是rayfed会查找历史集群的参与方导致的

**Comment by allenkang** [comment]
> 采用单机仿真部署，多次执行无异常 import secretflow as sf sf.init(parties=['alice', 'bob'], address='local')

采用多机仿真部署，多次执行验证也无异常

**Comment by ian-huu** [comment]
> > hi,@allenkang 请检查IP是否互相可ping的到，port是否为未被占用的（Ray节点启动、RayFed、SPU三者之间的port不可重复） 祝好
> 
> 网络都是没用问题的，目前看是rayfed会查找历史集群的参与方导致的

有具体的报错信息吗，如果确认是 rayfed 的问题可以在 [rayfed](https://github.com/ray-project/rayfed) 提一个 issue

**Comment by allenkang** [comment]
> > > hi,@allenkang 请检查IP是否互相可ping的到，port是否为未被占用的（Ray节点启动、RayFed、SPU三者之间的port不可重复） 祝好
> > 
> > 
> > 网络都是没用问题的，目前看是rayfed会查找历史集群的参与方导致的
> 
> 有具体的报错信息吗，如果确认是 rayfed 的问题可以在 [rayfed](https://github.com/ray-project/rayfed) 提一个 issue

不确定是哪里问题，只是目前追踪代码是fed里报的assert，AssertionError: Failed to find bob in cluster {'alice': {'address': '192.168.0.98:40345', 
'listen_addr': '0.0.0.0:40345'}, 'carol': {'address': '192.168.0.133:40345', 'listen_addr': '0.0.0.0:40345'}}.
2023-05-11 10:03:00 WARNING cleanup.py:62 [alice] --  Signal self to exit. 

issue里有两参与方同时执行的日志

**Comment by NKcqx** [comment]
@allenkang  Hello 我是 Rayfed 的成员，rayfed 的连续 init+shutdown 目前还不支持，仍正在开发中。
从日志中我推测大概是shutdown 时消息队列未清空导致的，但是所提供的复现代码并不能运行以及复现问题，能否麻烦您再提供一个真的可复现的代码以便验证问题呢～

**Comment by allenkang** [comment]
> @allenkang Hello 我是 Rayfed 的成员，rayfed 的连续 init+shutdown 目前还不支持，仍正在开发中。 从日志中我推测大概是shutdown 时消息队列未清空导致的，但是所提供的复现代码并不能运行以及复现问题，能否麻烦您再提供一个真的可复现的代码以便验证问题呢～

抱歉，才看到。我用到的测试代码如下：
main-test.py ======>

import logging
import time
from fastapi import FastAPI
from pydantic import BaseModel


from config import settings

logger = logging.getLogger(__name__)

base_url = '/sf'

app = FastAPI(
    title="隐语执行器服务",
    version="1.0",  # 版本
    description="隐语执行器服务",  # 描述
    docs_url=base_url + '/docs',  # swagger url
    redoc_url=base_url + '/redoc',  # redoc url
    openapi_url=base_url + '/openapi.json',  # OpenAPI url
    swagger_ui_oauth2_redirect_url=base_url + "/docs/oauth2-redirect"
)


class Item(BaseModel):
    dataframe: str = "horizontal"
    type: str = "sum"
    csvpath: str = "/root/sf/01/wages1.csv"
    port: int = 40345
    unionname: str = "bob"
    unioncsvpath: str = "/root/sf/02/wages2.csv"
    unionaddress: str = "192.168.0.20"


def sf_config(address, port, unionname, partyname):
    ccfg = {
        'parties': {
            partyname: {
                'address': settings.party_ip + ':' + str(port),
                'listen_addr': '0.0.0.0:' + str(port)
            },
            unionname: {
                'address': address + ':' + str(port),
                'listen_addr': '0.0.0.0:' + str(port)
            },
        },
        'self_party': partyname
    }
    return ccfg


def spu_config(address, port, unionname, partyname,spu):
    cdef = {
        'nodes': [
            {'party': partyname, 'id': 'local:0', 'address': settings.party_ip + ':' + str(port),
             'listen_addr': '0.0.0.0:' + str(port)},
            {'party': unionname, 'id': 'local:1', 'address': address + ':' + str(port),
             'listen_addr': '0.0.0.0:' + str(port)},
        ],
        'runtime_config': {
            'protocol': spu.spu_pb2.CHEETAH,
            'field': spu.spu_pb2.FM128,
            'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
        },
    }
    return cdef


@app.get(base_url + "/info", summary='获取环境信息', tags=["环境"])
def info():
    return {
        "party_name": settings.party_name,
        "party_ip": settings.party_ip,
        "party_ray_port": settings.party_ray_port
    }


def sf_init(ccfg,sf):
    sf.shutdown()
    print(settings.party_ip + ':' + str(settings.party_ray_port))
    sf.init(address=settings.party_ip + ':' + str(settings.party_ray_port), cluster_config=ccfg)


def sf_spu(cdef,sf):
    sfspu = sf.SPU(cluster_def=cdef)
    return sfspu

@app.post(base_url + "/aggregator", summary='求平均(mean)、求和(sum)、最小(min)、最大(max)、计数(count)', tags=["测试"])
def averagefunc(item: Item):
    import secretflow as sf
    import spu
    from secretflow.data.horizontal import read_csv as h_read_csv
    from secretflow.data.vertical import read_csv as v_read_csv
    from secretflow.security.aggregation import SPUAggregator
    from secretflow.security.compare import SPUComparator

    print(sf.SPU)
    print("====================================================")
    parties01 = settings.party_name
    parties02 = item.unionname
    ccfg = sf_config(item.unionaddress, item.port, parties02, parties01)
    print(ccfg)
    # sf.init(address=settings.party_ip + ':' + str(settings.party_ray_port), cluster_config=ccfg)
    sf_init(ccfg,sf)
    cdef = spu_config(item.unionaddress, item.port + 3000, parties02, parties01,spu)
    print(cdef)
    # 构建两方计算密文设备
    spu_2pc = sf_spu(cdef,sf)  # sf.SPU(cluster_def=cdef)
    print(spu_2pc)
    # 两参与方，明文设备
    parties = [[parties01, item.csvpath], [parties02, item.unioncsvpath]]
    parties.sort()
    print("====================================================")
    print(parties)
    party01, party02 = sf.PYU(parties[0][0]), sf.PYU(parties[1][0])
    # 安全聚合
    comp = SPUComparator(spu_2pc)
    aggr = SPUAggregator(spu_2pc)
    print(aggr)

    hvdf = {}
    t0 = time.time()
    if 'vertical' == item.dataframe:
        hvdf = v_read_csv({party01: parties[0][1], party02: parties[1][1]},
                          aggregator=aggr,
                          comparator=comp)
    else:
        # 读取两方数据为横向dataframe
        hvdf = h_read_csv({party01: parties[0][1], party02: parties[1][1]},
                          aggregator=aggr,
                          comparator=comp)
    result = {}
    print("aggregator type:" + item.type)
    if "mean" == item.type:
        result = sf.reveal(hvdf.mean(numeric_only=True))
    elif "sum" == item.type:
        result = sf.reveal(hvdf.sum(numeric_only=True))
    elif "min" == item.type:
        result = sf.reveal(hvdf.min(numeric_only=True))
    elif "max" == item.type:
        result = sf.reveal(hvdf.max(numeric_only=True))
    elif "count" == item.type:
        result = sf.reveal(hvdf.count(numeric_only=True))
    else:
        result = sf.reveal(hvdf.sum(numeric_only=True))
    t1 = time.time()
    print(result)
    print("time cost:\n", float(t1 - t0) * 1000.0, "ms")
    spu_2pc.shutdown()
    return str(result)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    import uvicorn
    print_hi('start')
    uvicorn.run(app, debug=True, reload=True)

config.py ======>

from pydantic import BaseSettings

class Settings(BaseSettings):
    party_name: str = "nobody"
    party_ray_port: str = "32345"
    party_ip: str = ""

settings = Settings()


环境：
准备三台ecs做为三个参与方ABC的节点，执行：
alice：
docker run -it -d -p 9881:9881 -v /root/sf/:/root/sf/ --shm-size=2.09gb --network host secretflow/secretflow-anolis8:0.8.2b1
进入docker： docker exec -it ***** bash
ray start --head --port=31231 --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

bob:
docker run -it -d -p 9882:9882 -v /root/sf/:/root/sf/ --shm-size=2.09gb --network host secretflow/secretflow-anolis8:0.8.2b1
进入docker：docker exec -it ***** bash
 ray start --head --port=31232 --resources='{"bob": 16}' --include-dashboard=False --disable-usage-stats

carol:
docker run -it -d -p 9883:9883 -v /root/sf/:/root/sf/ --shm-size=2.09gb --network host secretflow/secretflow-anolis8:0.8.2b1
进入docker： docker exec -it ***** bash
ray start --head --port=31233 --resources='{"carol": 16}' --include-dashboard=False --disable-usage-stats

分别进入docker启动常驻服务（非后台启动，ctrl+c退出服务）：
pip install uvicorn && pip install FastAPI

PARTY_NAME="alice" PARTY_RAY_PORT="31231" PARTY_IP="192.168.0.98" uvicorn main-test:app --host '0.0.0.0' --port 9881 --reload
PARTY_NAME="bob" PARTY_RAY_PORT="31232"  PARTY_IP="192.168.0.156" uvicorn main-test:app --host '0.0.0.0' --port 9882 --reload
PARTY_NAME="carol" PARTY_RAY_PORT="31233"  PARTY_IP="192.168.0.133" uvicorn main-test:app --host '0.0.0.0' --port 9883 --reload

具体执行测试时，在各个参与方节点的常驻服务同时调用测试聚合接口（/sf/aggregator）即可，url：http://{参与方ip}:9881/sf/docs#/ 。参数如图：
![image](https://github.com/secretflow/secretflow/assets/622497/18ba4ad6-12c0-47f0-b790-b22a3c588be3)

**Comment by ian-huu** [comment]
好的，我们尝试线下复现一下
