### ISSUE TITLE
隐私大赛

### ISSUE THREAD

**Issue by hanweidong** [secretflow/secretflow#530]
### Issue Type

Others

### Source

binary

### Secretflow Version

v0.8.2b1

### OS Platform and Distribution

CentOS Linux release 7.7.1908 (Core)

### Python version

3.8

### What happend and What you expected to happen.

```shell
你好，我看到隐语为隐私大赛提供的baseline（https://mp.weixin.qq.com/s/doyXpIRaERnvCJeZYkeS3w），想问下数据处理是怎么操作的呢
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by llCurious** [comment]
Hey, @hanweidong.

数据处理分为两步：
1. 使用PSI基于标识id进行对齐。这一步可以直接使用隐语提供的接口实现
2. 数据预处理。这里涉及到ML里面的一些特征工程方法，目前我们是将类别数值进行了onehot编码，同时结合PCA进行了降维。这里可以用的方法比较多，比如WOE等（垂直场景下的WOE隐语有提供API，可以参考[链接](https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/data_preprocessing_with_data_frame.html)

**Comment by hanweidong** [comment]
> 
赛方提供的数据看起来已经进行了样本对齐，还需要再做psi么

**Comment by llCurious** [comment]
如果假设数据已经事先对齐过，那么PSI就不是必须的。不过在实际的建模中，这个假设是不成立的。因此一般PSI是垂直场景下的前置步骤
