### ISSUE TITLE
SGB算法，预测结果和id没对应上

### ISSUE THREAD

**Issue by magic-hya** [secretflow/secretflow#532]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

docker-latest

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
训练使用baseline代码auc达到95%，模型加载后预测使用训练数据，得到auc只有50%不到
```

### Reproduction code to reproduce the issue.

```shell
两台机器训练，生产模式
部分训练代码:
train_data_dict = {
    alice: "/data/2023fl/submit/train_output/alice_train.csv",
    bob: "/data/2023fl/submit/train_output/bob_train.csv",
}
test_data_dict = {
    alice: "/data/2023fl/submit/train_output/alice_train.csv",
    bob: "/data/2023fl/submit/train_output/bob_train.csv",
}
logging.info(f"main auc: {roc_auc_score(y_test_, yhat)}")
[alice] --  main auc: 0.9935234654394716
saving_path_dict = {
    # in production we may use remote oss, for example.
    alice: '/data/2023fl/submit/train_output/sgbmodel',
    bob: '/data/2023fl/submit/train_output/sgbmodel'
}
model.save_model(saving_path_dict)
部分预测代码：
predict_data_dict = {
    alice: "/data/2023fl/submit/train_output/alice_train.csv",
    bob: '/data/2023fl/submit/train_output/bob_train.csv'
}
predict_vdf = v_read_csv(
    predict_data_dict,
    keys=args.id,
    drop_keys=args.id,
    spu=my_spu,
)
model_path_dict = {alice: '/data/2023fl/submit/train_output/sgbmodel',
 bob: '/data/2023fl/submit/train_output/sgbmodel'}

model_loaded = load_model(model_path_dict, alice)
fed_yhat_loaded = model_loaded.predict(predict_vdf, alice)
yhat_loaded = reveal(fed_yhat_loaded.partitions[alice])
df = pd.read_csv("/data/2023fl/submit/train_output/alice_train.csv")

roc_auc_score(df['label'], yhat_loaded)
0.48960090398666944
```

**Comment by da-niao-dan** [comment]
你好， df和predict_vdf的y的确有可能不一样。原因是v read csv中会有PSI操作。

用`fed_yhat_loaded = model_loaded.predict(predict_vdf, alice)`
预测以后，需要取predict_vdf的y label来测量。而不是df的y label。

大概如下：
```
label_data = vdf['label']
true_y = reveal(
      label_data.partitions[alice].data
  ).values
roc_auc_score(true_y, yhat_loaded)
```

另外，这个和SGB预测应该没有关系，
可以尝试把df的label和vdf的label做auc，如果顺序不变应该是1。但是实际情况应该是一个比较低的值。

**Comment by magic-hya** [comment]
> 你好， df和predict_vdf的y的确有可能不一样。原因是v read csv中会有PSI操作。
> 
> 用`fed_yhat_loaded = model_loaded.predict(predict_vdf, alice)` 预测以后，需要取predict_vdf的y label来测量。而不是df的y label。
> 
> 大概如下：
> 
> ```
> label_data = vdf['label']
> true_y = reveal(
>       label_data.partitions[alice].data
>   ).values
> roc_auc_score(true_y, yhat_loaded)
> ```
> 
> 另外，这个和SGB预测应该没有关系， 可以尝试把df的label和vdf的label做auc，如果顺序不变应该是1。但是实际情况应该是一个比较低的值。


y_label = predict_vdf[args.label]
y_label_ = reveal(y_label.partitions[alice].data)
roc_auc_score(y_label_, yhat_loaded)
0.9935234654394716


我之所以这么测试，是想验证我的想法，模型预测的时候，会使原有数据的顺序发生变化
实际生产过程中，预测的结果需要跟id列对齐，然而在v read csv中id列已经被删除，导致无法获取求交后的id标签顺序
求交后的id顺序无法获取，导致输出的预测结果无意义

**Comment by warriorpaw** [comment]
可以考虑首先进行单独的psi，再执行read_csv
```
psi_output_file = {
    pyu: f'{path}.psi_output' for pyu, path in predict_data_dict.items()
}
my_spu.psi_csv(
    key=args.id,
    input_path=predict_data_dict,
    output_path=psi_output_file,
    receiver="alice",
    sort=True,
)
predict_vdf = v_read_csv(
    predict_data_dict,
    drop_keys=args.id,
)
```
这样，在psi_output_file的输出文件中，id列是保留的

**Comment by magic-hya** [comment]
好的，感谢
