### ISSUE TITLE
请求获取论文副本：Privacy-Preserving End-to-End Spoken Language Understanding

### ISSUE THREAD

**Issue by UbiquitousLearning** [secretflow/secretflow#533]
尊敬的蚂蚁隐语团队：  
您好，我是来自北京邮电大学的博士生蔡栋琪，，在csdn博客上看到贵团队今年在IJCAI上发表了一篇题为“Privacy-Preserving End-to-End Spoken Language Understanding”的学术论文，恭喜！

我的研究方向是关于语音大模型的隐私保护，因此对该篇论文的研究内容十分感兴趣，请问贵司能否提供改论文的电子副本，我将只用于学术研究用途，万分感谢🙏  

最诚挚的问候，
蔡栋琪

我的邮箱：cdq@bupt.edu.cn

**Comment by user2311717757** [comment]
谢谢同学关注。我们目前正在整理最终版本，随后会公开发布的。由于ijcai会议还没召开，如果它没有针对公开时间的限制，我们会提前发布的。
