### ISSUE TITLE
The random problem against split learning.

### ISSUE THREAD

**Issue by ZeroWalker10** [secretflow/secretflow#534]
1. In handle_data()(location: secretflow.ml.nn.sl_model.py), the buffer size should be equal or greater than the dataset size rather batch_size * 8, because tensorflow shuffle the buffered instances. 
2. In build_dataset_from_numeric()(location: secretflow.ml.nn.backend.tensorflow.sl_base.py), the call sequence should be shuffle() first and then batch(), or in each batch the instances are sequential.

**Comment by zhangxingmeng** [comment]
Hi ZeroWalker10,
Thank you for reporting this issue, we will fix it in the future release. If you are interested, you can also submit a pull request to fix it.
Thank you.
