### ISSUE TITLE
多方多列隐私求交

### ISSUE THREAD

**Issue by dyx0001** [secretflow/secretflow#535]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow-anolis8:latest

### OS Platform and Distribution

centos 7.9

### Python version

Python 3.8.15

### What happend and What you expected to happen.

```shell
我这里按照官网的“隐语PSI Benchmark白皮书”https://www.secretflow.org.cn/docs/secretflow/zh_CN/developer/benchmark/psi_benchmark.html，已经实现了双方单键隐私求交，现在想实现双方多键以及三方多键的隐私求交我这里需要改动哪些配置？
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging
from absl import app
import spu
import secretflow as sf
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
cluster_def = {
    'nodes': [
        {'party': 'alice', 'address': '192.168.0.10:3021', 'listen_address': '0.0.0.0:3021'},
        {'party': 'bob', 'address': '192.168.0.20:3022', 'listen_address': '0.0.0.0:3022'},
        # {'party': 'carol', 'address': '127.0.0.1:12347'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}


def main(_):
    sf.init(['alice','bob'], address='192.168.0.10:3029')
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    #carol = sf.PYU('carol')
    input_path = {
        alice: '/.data/alice.csv',
        bob: '/.data/bob.csv',
        # carol: '/.data/psi_3.csv',
    }
    output_path = {
        alice: '/.data/psi_output.csv',
        bob: '/.data/psi_output.csv',
        # carol: '/.data/psi_output.csv',
    }
    select_keys = {
        alice: ['uid', 'month'],
        bob: ['uid', 'month'],
        # carol: ['uid', 'month'],
    }
    spu = sf.SPU(cluster_def)
    start = time.time()
    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',
        protocol='KKRT_PSI_2PC',
        precheck_input=False,
        sort=False,
        broadcast_result=False,
    )
    print(f"psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")
    sf.shutdown()


if __name__ == '__main__':
    app.run(main)
这种配置实现双方多键求交是否可行？
```

**Comment by Chrisdehe** [comment]
嗨，@dyx0001 多方PSI参见 #520

**Comment by dyx0001** [comment]
@Chrisdehe  由于python语言用的不是很熟练，就是有没有详细步骤指导一下该如何配置，验证一下相关隐私计算。

**Comment by zhanglei486** [comment]
上面的脚本还是两方的脚本，一般多方PSI是指3方以上，可以参考官网文档中的提示，去掉carol的注释，使用3个节点运行3方PSI协议

**Comment by dyx0001** [comment]
我是不是可以参照这里的配置https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/PSI_On_SPU.html#SPU%E9%9A%90%E7%A7%81%E6%B1%82%E4%BA%A4，进行测试验证

**Comment by zhanglei486** [comment]
> 我是不是可以参照这里的配置[https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/PSI_On_SPU.html#SPU%E9%9A%90%E7%A7%81%E6%B1%82%E4%BA%A4，进行测试验证](https://www.secretflow.org.cn/docs/secretflow/zh_CN/tutorial/PSI_On_SPU.html#SPU%E9%9A%90%E7%A7%81%E6%B1%82%E4%BA%A4%EF%BC%8C%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95%E9%AA%8C%E8%AF%81)

可以的

**Comment by dyx0001** [comment]
我刚才试了多节点多键的隐私求交，结果也正常输出了。我现在有两个问题想咨询一下：
1.  隐语隐私求交的结果是同步生成的，还是异步生成的，或者生成方式是可配的？
2.  我这里试了三方多键隐私求交，发现求交的结果并不能获取己方没有的字段的数据，如下图：
我按照官网上生成数据的方式，将alice的源数据删除了两列，同样bob及carol的源数据的也各删除了一列，然后做隐私求交：
![1684142328516](https://github.com/secretflow/secretflow/assets/132547242/7a08aac7-081b-46a2-965c-5f155a6f58ff)
![1684142278204](https://github.com/secretflow/secretflow/assets/132547242/dfd56fcb-0831-4ca3-9b49-a20e47aad5bd)
<img width="357" alt="1684142438529" src="https://github.com/secretflow/secretflow/assets/132547242/d224808f-05b7-4028-ae3e-78feaffbd879">

在alice节点获取的求交结果，依然是alice的四列数据，并没有获取到bob、carol的独有字段，这个是需要配置还是隐语就不支持获取其他方的独有数据？

**Comment by zhanglei486** [comment]
1. 麻烦解释一下您这里同步、异步具体是指什么；
2. psi只是根据指定的id得到交集，第2个问题的需求我理解是想得到其他参与方交集id对应的其他列信息，不是标准psi的功能，
属于labeled psi的需求，labeled psi协议是2方协议

**Comment by dyx0001** [comment]
@zhanglei486  同步是指大量数据经过隐私计算同时将结果写入输出文件，异步就是计算完成后还需要等待结果写入输出文件中。

**Comment by dyx0001** [comment]
我们这里的结果输出是同步的还是异步的，或者是可配的就是根据数据量进行配置采用何种方式

**Comment by zhanglei486** [comment]
PSI协议交互的通信和计算完成后，将结果写入输出文件

**Comment by dyx0001** [comment]
@zhanglei486 这个labeled psi协议的应用，隐语有相关用例么？

**Comment by Chrisdehe** [comment]
hi，@dyx0001  
labeled psi协议参见：[星河杯“黑名单共享查询”赛题基于隐语实现baseline](https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw)

**Comment by dyx0001** [comment]
@Chrisdehe  两方隐私求交，从建立链接到求出结果，两个节点的交互共有几次？分别进行什么任务？

**Comment by dyx0001** [comment]
@Chrisdehe  两方隐私求交，从建立链接到求出结果，两个节点的交互共有几次？分别进行什么任务？

**Comment by Chrisdehe** [comment]
hi，@dyx0001 
不同的 PSI 算法流程不一样，因此可能需要明确这里的加密内容指的是什么 PSI 算法的哪个阶段的加密内容。比如，限定指 ECDH-PSI 的二次 DH 加密密文。
详细的内容可参考：
1、隐语的小剧场公众号发布的隐语小课文档[《PSI特征、算法机器典型应用场景》(https://mp.weixin.qq.com/s/mJex5FXEORO6VjBOVi7JfQ)
2、[隐语官网—组件—隐私求交集合](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/psi)

**Comment by Chrisdehe** [comment]
hi，@dyx0001
不同的 PSI 算法流程不一样，因此可能需要明确这里的加密内容指的是什么 PSI 算法的哪个阶段的加密内容。比如，限定指 ECDH-PSI 的二次 DH 加密密文。
详细的内容可参考：
1、隐语的小剧场公众号发布的隐语小课文档[《PSI特征、算法机器典型应用场景》](https://mp.weixin.qq.com/s/mJex5FXEORO6VjBOVi7JfQ)
2、[隐语官网—组件—隐私求交集合](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/psi)

**Comment by dyx0001** [comment]
@Chrisdehe  采用ECDH-PSI，三方隐私求交（a、b、c三方）握手阶段，如果a方发起请求，b、c两方同时响应么？还是a、b先求交，完成求交重新与c方进行握手？
<img width="378" alt="1685006595724" src="https://github.com/secretflow/secretflow/assets/132547242/8e5c648c-e18e-4483-978a-df4cf65483fb">

**Comment by usafchn** [comment]
@dyx0001 你的截图是隐语互联互通版本的 ECDH-PSI，互联互通因为是跟外部平台通信需要先握手对齐参数，内部版本是假设参数已经对齐了的，没有握手直接跑算法主体的。现在互联互通版 ECDH-PSI 还只支持两方。

**Comment by dyx0001** [comment]
@usafchn  你说的外部平台是指除隐语外的其他隐私计算框架构建的平台么 ？而内部本版指的是隐语框架构建的平台？

**Comment by usafchn** [comment]
> @usafchn 你说的外部平台是指除隐语外的其他隐私计算框架构建的平台么 ？而内部本版指的是隐语框架构建的平台？

对，是的，正常如果两方做计算，两边都应该部署隐语，ECDH-PSI在内部模式下运行；互联互通模式指的是一边部署隐语，另一边部署的是其它厂商平台，我们现在有跟一些外部厂商合作，双方通过约定相同的算法协议接口来实现算法（例如 ECDH-PSI）跨平台互通。

**Comment by dyx0001** [comment]
@usafchn 我看到三方隐私求交的逻辑是先两方求交，求出的交集再与第三方进行求交，最后得到三方交集。那要是多方大于三的情况下，求交的逻辑是否可以类推成先两方求，求交结果与第三方求交，然后前三方交集再与第四方求，依此类推最终求得多方的交集？

**Comment by Jamie-Cui** [comment]
hi @dyx0001 我们实现的基于 DH 的 3 方协议的运行细节和

从“多方隐私求交集”的功能上来说这样是可行的，

**Comment by Jamie-Cui** [comment]
Hi @dyx0001 这些问题我可以简单解释一下

**Comment by dyx0001** [comment]
@Jamie-Cui  针对多方隐私求交：
1. 如果其中一方没有相关交集数据，比如针对某个UID求交，只有一家没有这个UID，其他参与方都有交集，那隐语的计算结果是否有交集？
2. 如果没有交集的话，我这里是否可以控制每次的求交结果都可以返给参与方，即A跟B交集返一次结果给A、B，A、B的交集与C求交结果再返一次结果给A、B、C，以此类推？
3. 或者大多数有交集，是否可以通过参数控制排除掉小部分没有交集的参与方的求交计算？

**Comment by Jamie-Cui** [comment]
> 如果其中一方没有相关交集数据，比如针对某个UID求交，只有一家没有这个UID，其他参与方都有交集，那隐语的计算结果是否有交集？

在这个 case 下是没有交集的

> 如果没有交集的话，我这里是否可以控制每次的求交结果都可以返给参与方，即A跟B交集返一次结果给A、B，A、B的交集与C求交结果再返一次结果给A、B、C，以此类推？

在不考虑协议安全性的前提下，考虑协议流程的优化是没有意义的。如果你确认在你的 case 下可以使用 https://github.com/secretflow/secretflow/issues/535#issuecomment-1567844048 中的第二个安全定义，那么是可以的。学术层面的多方隐私求交一般实用的是第一个安全定义。

> 或者大多数有交集，是否可以通过参数控制排除掉小部分没有交集的参与方的求交计算？

同样，在不考虑安全性情况下是可行的。需要给一个明确的基于场景的安全定义来进行协议修改。
