### ISSUE TITLE
[awesome-pets] Move LLAMA from 2PC to 3PC

### ISSUE THREAD

**Issue by vincehong** [secretflow/secretflow#537]
[secretflow/docs/awesome-pets/papers/applications/ppml/ppml_crypto.md](https://github.com/secretflow/secretflow/blob/main/docs/awesome-pets/papers/applications/ppml/ppml_crypto.md)

LLAMA is 2PC with dealer distributing FSS keys, so it's more like 3PC, listing it in 2PC might be unfair.

**Comment by llCurious** [comment]
Hey @vincehong . Thanks for your suggestion. This issue has been fixed in PR #539
