### ISSUE TITLE
教程能否提供一个HEU运算的例子

### ISSUE THREAD

**Issue by mingo0117** [secretflow/secretflow#54]
### Issue Type

Documentation Feature Request

### Source

source

### Secretflow Version

latest

### What happend and What you expected to happen.

```shell
看源码感觉HEU初始化和SPU差别比较大，也没有看到专门的教程，这块能否提供一个小案例（如加法）便于上手呢，谢谢
```

### Reproduction code to reproduce the issue.

```shell
同上
```

**Comment by usafchn** [comment]
Hi，@mingo0117 

HEU 分为两部分，第一他是 secretflow 中的一个 device，第二他本身也是一个同态加密的 library

如果是后者，把 HEU 单独当做 lib 使用，是有文档的，参见 https://heu.readthedocs.io/

如果是前者，把 HEU 当做 device 使用，这部分还是实验性的，当前有一个基于 [HEU + SPU 的 LR 实现](https://github.com/secretflow/secretflow/blob/beta/secretflow/ml/linear/hess/model.py)，其教程有所欠缺，我们后面会补充相关文档。如果你着急的话，可参考 [HESS-LR 的单测](https://github.com/secretflow/secretflow/blob/beta/tests/ml/linear/test_hess.py)获取其用法。

**Comment by mingo0117** [comment]
> Hi，@mingo0117 感谢关注
> 
> HEU 分为两部分，第一他是 secretflow 中的一个 device，第二他本身也是一个同态加密的 library
> 
> 如果是后者，把 HEU 单独当做 lib 使用，是有文档的，参见 https://heu.readthedocs.io/
> 
> 如果是前者，把 HEU 当做 device 使用，这部分还是实验性的，不建议用户直接操纵 device，而是使用更上层的 ML 算法，比如当前有一个基于 [HEU + SPU 的 LR 实现 (即 HESS-LR)](https://github.com/secretflow/secretflow/blob/beta/secretflow/ml/linear/hess/model.py)，但其教程有所欠缺，我们会尽快补充相关文档。如果你着急的话，可参考 [HESS-LR 的单测](https://github.com/secretflow/secretflow/blob/beta/tests/ml/linear/test_hess.py)获取 HESS-LR 的调用方法。

所以目前是不能按如下这样执行吗？参考的test_heu
![image](https://user-images.githubusercontent.com/29568891/180355582-94c4d816-479f-4010-a7bd-5723c1f9a44e.png)
报错如下：
![image](https://user-images.githubusercontent.com/29568891/180355611-abb8e3e3-928f-48de-bb72-3100d4cf7c78.png)

**Comment by zhouaihui** [comment]
试一下 `'schema': 'ou'`   -> `'schema': 'zpaillier'`

**Comment by mingo0117** [comment]
> 试一下 `'schema': 'ou'` -> `'schema': 'zpaillier'`

可以了，感谢
