### ISSUE TITLE
sgb审计日志获取

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#544]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 0.8.2b1

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
如何获取sgb训练时候的审计日志？在API接口中，train()加上audit_paths参数就可以获取审计日志，但是在实际运行过程中，日志的内容为空。
```

### Reproduction code to reproduce the issue.

```shell
sgb = Sgb(heu)
model = sgb.train(params=params,
                  dtrain=train_data,
                  label=label_data,
                  audit_paths={
                     "party_1": "/root/logs/audit.log",
                     "party_2": "/root/logs/audit.log"
                  })
```

**Comment by da-niao-dan** [comment]
audit log 大多是一些关键信息点，会以pickle形式保存到指定路径，不会print到屏幕上。

**Comment by Niclouge** [comment]
好的，谢谢！

建议可以完善一下文档，在看API文档时，以为审计日志会直接输入到log文件中。
