### ISSUE TITLE
多个多方任务问题

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/secretflow#546]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.1b1

### OS Platform and Distribution

Ubuntu 20.04.6 LTS（windows上安装的wsl，64位操作系统）

### Python version

Python 3.8.16

### What happend and What you expected to happen.

```shell
import secretflow as sf
sf.init(parties=['alice', 'bob'], address='192.168.0.10:9001')

我是A方，需要和B方做一个求交任务，也需要和C方做一个隐匿查询任务，两个任务互相独立。
sf的初始化，这种情况下应该怎么操作？
```

### Reproduction code to reproduce the issue.

```shell
na
```

**Comment by ian-huu** [comment]
建议把 secretflow 当做一个“计算引擎”来看，每个任务（或每组相关的任务）建立一个独立的 secretflow 集群，完成任务后关闭这个集群；不同的任务间用容器等方式来做隔离

**Comment by daydayuphere** [comment]
生产模式下，那我在A方部署一套共享的ray集群，然后对B方的任务和对C方的任务分别用独立的python进程初始化sf然后下任务，您看这样行吗

**Comment by ian-huu** [comment]
1. 理论上是可以行的
2. 关于端口的问题，我们会在调度框架（另一个项目）层面解决，secretflow 目前专注于“计算”的部分。如果希望只用 secretflow 并且控制端口数量，可以在企业入口加入一些代理（如 nginx 或 envoy），并根据任务动态配置转发规则来实现

**Comment by daydayuphere** [comment]
谢谢您的答复
