### ISSUE TITLE
DAG图执行问题

### ISSUE THREAD

**Issue by 472002463** [secretflow/secretflow#554]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

Ubuntu 18.4

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
请问下secretflow本身自带并行计算吗,因为我看ray本身自带dag图并行计算。

比如执行
我只是假设，对双方进行两次psi求交，因为这两次psi互不影响。我看日志里面，并不会，都需要等待上一次psi完成后才进行下一次PSI，所以这类操作数据的类似spark中Action类型的操作其实是阻塞的，是需要我自己在另一个线程中执行吗?类似下面
```

### Reproduction code to reproduce the issue.

```shell
spu.psi_csv('uid', input_path, output_path, 'alice')
from threading import Thread
def target01(args1, args2):
    path = {alice: '.data/alice_psi1.csv', bob: '.data/bob_psi1.csv'}
    spu.psi_csv('uid', input_path, path, 'alice')


thread01 = Thread(target=target01, args="参数", name="线程1")

thread01.start()
```

**Comment by ian-huu** [comment]
secretflow 的确用到了 ray 的 dag 图并行计算能力（或者叫异步执行能力），但是需要说明的是：
对于大部分 secretflow 封装好的算法来说，整个算法是一个 dag 图，但是中间会有一些“同步点”，所以虽然在局部上是异步执行的，但是到了“同步点”会需要等待所有参与方都执行到此处。这就使得对于大部分算法来说，整个算法的执行过程看起来像是“同步”的，也就是执行两个算法的时候是先执行一个再执行另一个。

回到你的另一个问题，如果有两个无关的任务，如何并行执行：
1. 首先不能在一段 driver 代码中使用多线程或者多进程，原因可以看[这篇文章](https://www.secretflow.org.cn/docs/secretflow/zh_CN/developer/design/programming_in_secretflow.html)
2. 需要执行两个无关任务的时候，建议直接执行两段 driver 代码（两段 python 脚本）

**Comment by 472002463** [comment]
>需要执行两个无关任务的时候，建议直接执行两段 driver 代码（两段 python 脚本）

这个估计不太可能，换而言之，就是drinver代码不允许自己开启多线程执行。
那有个问题，前面说的`同步点`，怎么区分呢，是那种需要操作数据的行为叫做同步点吗，比如psi、model.train这种实际执行的时候吗，那么我有个疑惑，隐喻平台中也是这样的吗，比如下面这种按照实际可以按照多个并行任务进行执行，难道都是单线程吗，这是我从文档中的查看的，实际没登陆过平台，所以不太清楚是否可以
![image](https://github.com/secretflow/secretflow/assets/33944862/49837893-5629-4084-984c-3b801616df04)

**Comment by 472002463** [comment]
>需要执行两个无关任务的时候，建议直接执行两段 driver 代码（两段 python 脚本）

这个估计不太可能，换而言之，就是drinver代码不允许自己开启多线程执行。
那有个问题，前面说的`同步点`，怎么区分呢，是那种需要操作数据的行为叫做同步点吗，比如psi、model.train这种实际执行的时候吗，那么我有个疑惑，隐喻平台中也是这样的吗，比如下面这种按照实际可以按照多个并行任务进行执行，难道都是单线程吗，这是我从文档中的查看的，实际没登陆过平台，所以不太清楚是否可以。如果可以并行的话，那些是操作或者所算子是可以的。
![image](https://github.com/secretflow/secretflow/assets/33944862/49837893-5629-4084-984c-3b801616df04)

**Comment by zhangxingmeng** [comment]
Hi
1、你这边展示的这个图是任务级别的dag图，在实际每个任务下面还有自己的dag图。上面说的同步点是任务层级的dag图里面存在的，ray进行调度是异步延迟的。其中有一些同步语义比如wait等就是同步点，会要求参与方在这一步进行同步。
2、driver端只是负责发起任务，实际执行会由具体的device来进行，device端的代码不是单线程，底层实现都是多线程来进行执行的。
3、如果你需要driver端的并发，可以尝试增加device配置来进行，比如init多个`SPU`来进行psi，这样就可以做到任务级的并发。

**Comment by 472002463** [comment]
@zhangxingmeng 
是不是可以这么理解，比如`逻辑回归`算子自己执行的时候本身内部就是dag多线程执行，
但是你要想是多算子级别的异步执行，就需要定义多个device来并行执行，类似下面，就需要定义3个spu设备进行对应的并行计算。
```mermaid
graph TD;
    分箱转换-->相关系数矩阵;
    分箱转换-->VIF指标计算;
    分箱转换-->逻辑回归;
```
这里就有个问题，那这样数据不是膨胀了吗，比如输入是3W的数据，最终会生成3W*3的密文数据

**Comment by zhangxingmeng** [comment]
输入数据3W，提交多个任务中间结果膨胀是无法避免的，包括你的计算资源也需要更多。
最终生成，相关系数矩阵是一个n*n的矩阵，和样本量无关，VIF也是和特征数量相关的。逻辑回归生成的是模型。

**Comment by zhouaihui** [comment]
补充一下。
1. 产品形态下的组件DAG，目前实现是每一个组件对应一个SecretFlow集群，所以你理解的并发可以理解为多个SecretFlow集群的并发，每个集群其实只执行一个组件。
2. 如果需求在一个SecretFlow集群中执行多个组件（即多段独立的driver代码），目前隐语暂不支持这种模式，主要原因之一是会涉及到一些端口冲突。

**Comment by 472002463** [comment]
我现在探讨的也只是单个DAG图下的运行，所以根据上面所述，
我可理解为，上面的图中，若想要同时进行三种运算，我需要定义三个device进行运行是吗.
  -   分箱转换-->相关系数矩阵;   device1.
  -  分箱转换-->VIF指标计算;   device2
  -  分箱转换-->逻辑回归;   device3

**Comment by da-niao-dan** [comment]
你好，
是的。

**Comment by 472002463** [comment]
好的，感谢！

>如果需求在一个SecretFlow集群中执行多个组件（即多段独立的driver代码），目前隐语暂不支持这种模式，主要原因之一是会涉及到一些潜在的通信冲突

这个后续会开放吗。
而且我感觉现在secretflow需要配置的端口太多了假设由m方参与，假设根据图划分，需要由n个spu，那么我就需要配置n*m个端口，再加上secretflow的端口，至少需要 n*m+m个端口，这还不包括ray的一些端口

**Comment by 472002463** [comment]
> 你好， 可以这么写
> 
> ```
> r = 分箱转换
> 相关系数矩阵(r); device1.
> VIF指标计算(r); device2
> 逻辑回归(r); device3
> ```
> 
> r先执行，后面三个并行。

@da-niao-dan 
请问下，SPU Object可以通用吗，比如再另外三个spu设备中使用，
还是需要先转成PYU，然后再传到对应的SPU里面

**Comment by zhouaihui** [comment]
> 好的，感谢！
> 
> > 如果需求在一个SecretFlow集群中执行多个组件（即多段独立的driver代码），目前隐语暂不支持这种模式，主要原因之一是会涉及到一些潜在的通信冲突
> 
> 这个后续会开放吗。 而且我感觉现在secretflow需要配置的端口太多了假设由m方参与，假设根据图划分，需要由n个spu，那么我就需要配置n_m个端口，再加上secretflow的端口，至少需要 n_m+m个端口，这还不包括ray的一些端口

隐语即将开源调度架构kuscia，包含了多端口的归一能力，机构只需要开放一个端口即可。

**Comment by da-niao-dan** [comment]
> 



> > 你好， 可以这么写
> > ```
> > r = 分箱转换
> > 相关系数矩阵(r); device1.
> > VIF指标计算(r); device2
> > 逻辑回归(r); device3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > r先执行，后面三个并行。
> 
> @da-niao-dan 请问下，SPU Object可以通用吗，比如再另外三个spu设备中使用， 还是需要先转成PYU，然后再传到对应的SPU里面

你好，不能通用，但是也不用to pyu
`SPU1Object.to(SPU2)`即可。

**Comment by 472002463** [comment]
好的，感谢回答
