### ISSUE TITLE
想问下隐语开放平台会开源吗

### ISSUE THREAD

**Issue by onelyfly** [secretflow/secretflow#555]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.718

### OS Platform and Distribution

centos7

### Python version

Python 3.8 

### What happend and What you expected to happen.

```shell
想问下隐语开放平台会开源吗？如若开源，会是什么时候？
```

### Reproduction code to reproduce the issue.

```shell
想问下隐语开放平台会开源吗？如若开源，会是什么时候？
```

**Comment by miluoalbert** [comment]
Hi, @onelyfly 

目前隐语开放平台层已开源，可关注：https://github.com/secretflow/secretpad
