### ISSUE TITLE
机器学习后台随机端口号范围

### ISSUE THREAD

**Issue by meisir5648** [secretflow/secretflow#557]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

centos7

### Python version

3.8.0

### What happend and What you expected to happen.

```shell
想问一下机器学习的后台随机端口号的取值范围是多少？
```

### Reproduction code to reproduce the issue.

```shell
想问一下机器学习的后台随机端口号的取值范围是多少？
```

**Comment by meisir5648** [comment]
> 这个是 Linux 内核参数指定的：
> 
> ```
> cat /proc/sys/net/ipv4/ip_local_port_range 
> ```

感谢回答。再问一个问题：机器学习是否使用到了临时随机端口？

**Comment by zhouaihui** [comment]
机器学习这个范畴很大，如果你问的是隐语，那么答案是yes。目前隐语可以指定SPU的端口、Rayfed通信端口以及Ray的主节点端口，除此之外，ray系统本身会随机使用本地端口。

**Comment by meisir5648** [comment]
> 机器学习这个范畴很大，如果你问的是隐语，那么答案是yes。目前隐语可以指定SPU的端口、Rayfed通信端口以及Ray的主节点端口，除此之外，ray系统本身会随机使用本地端口。

明白了，感谢解答。
