### ISSUE TITLE
监听算子日志

### ISSUE THREAD

**Issue by 472002463** [secretflow/secretflow#564]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

Ubuntu 18.4

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
请问下，如果我要想要监听各个算子要怎么做。我尝试去看 /tmp/ray目录里面的日志，有点混乱
比如PSI，alice方能够知道PSI的日志。
因为secretflow日志打印的是整个driver的日志。
是通过采集的方式来获取对应算子的日志吗，如果是，那根据什么来区分日志是属于什么操作的呢。
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by zhouaihui** [comment]
secretflow目前是基于ray的日志功能，对于driver打印的日志，也是通过ray来实现的（有兴趣可以了解ray的log_to_driver参数）。
ray默认会在日志前面加上工作进程worker的信息，比如 类似
` (RecverProxyActor pid=xxx, ip=xxx)`, `(SPURuntime pid=xxx, ip=xxx)`，通过前缀标识可以区分是哪一个worker。

详细日志默认是记录在/tmp/ray/session_xxx/logs下面，可以阅读最https://docs.ray.io/en/latest/ray-observability/ray-logging.html#logging-directory-structure。

**Comment by 472002463** [comment]
这个好像没法满足我想要的场景，
>通过前缀标识可以区分是哪一个worker

首先我执行`spu.psi()`的时候，日志虽然有打印`SPURuntime pid=xxx, ip=xxx`类似这样的东西，如果由多个spu进行执行，那怎么判断此work是前面的spu的日志呢，比如能传入什么标识吗。我看spu里面有个`log_options`，因为没注释，所以也不太清楚是做什么

**Comment by oeqqwq** [comment]
> 这个好像没法满足我想要的场景，
> 
> > 通过前缀标识可以区分是哪一个worker
> 
> 首先我执行`spu.psi()`的时候，日志虽然有打印`SPURuntime pid=xxx, ip=xxx`类似这样的东西，如果由多个spu进行执行，那怎么判断此work是前面的spu的日志呢，比如能传入什么标识吗。我看spu里面有个`log_options`，因为没注释，所以也不太清楚是做什么

`log_options`是对应`spu_logging.LogOptions`，可设置如日志等级、日志路径等，例如：
```
log_options = spu_logging.LogOptions()
log_options.system_log_path = "./tmp/spu.log"
log_options.log_level = spu_logging.LogLevel.INFO
```
定义可以参考这里https://github.com/secretflow/spu/blob/main/spu/libspu.cc#LL512C6-L550C6
注释后续我们补充一下
