### ISSUE TITLE
What is the relationship between PPU and SPU?

### ISSUE THREAD

**Issue by NDBTjay** [secretflow/secretflow#57]
I saw some article introducing scretflow on the Internet , some explain the PPU with the picture of SPU, I am doubting about the relationship between PPU and SPU.

**Comment by NDBTjay** [comment]
Sorry, I found that you have write it to your  development docs that the SPU is a new name of PPU. But why do you rename it, does it make sense?

**Comment by icavan** [comment]
> Sorry, I found that you have write it to your development docs that the SPU is a new name of PPU. But why do you rename it, does it make sense?

Hi @NDBTjay , there is an internal product (inside our company) that already occupies the `PPU` naming. Hence, we've to rename `PPU` to `SPU` to avoid confusion.

Personally, I do like the `PPU` naming.

**Comment by 6fj** [comment]
Hi @NDBTjay ,

As of July 2022, **PPU** was renamed to **SPU**. This decision is part of our brand strategy. No further details are available at this moment.

Thank you for your attention to SecretFlow.
