### ISSUE TITLE
求医疗方面图像处理的代码案例

### ISSUE THREAD

**Issue by Endeavor-FYC** [secretflow/secretflow#577]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2b2

### OS Platform and Distribution

Centos 7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
请问，基于secretflow框架，有没有医疗方面，图像处理的代码案例
```

### Reproduction code to reproduce the issue.

```shell
请问，基于secretflow框架，有没有医疗方面，图像处理的代码案例
```

**Comment by zhouaihui** [comment]
官网上我们有给出水平联邦图像案例（非医疗图像，不过可以通用），具体参考 https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification

加载图像数据还可以参考  https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTorch#%E4%B8%8B%E8%BD%BD%E6%95%B0%E6%8D%AE
