### ISSUE TITLE
萌新提问

### ISSUE THREAD

**Issue by chengY666** [secretflow/secretflow#6]
请问有交流群么？

**Comment by pchyuan** [comment]
欢迎关注：
wx公众号：隐语的小剧场
B站up主：隐语SecretFlow
隐语小助手wx号：secretflow01 （加群可以请小助手帮拉）
隐语邮箱：secretflow-ci@service.alipay.com

**Comment by ywh254** [comment]
这个为什么不放到中文的readme里面

**Comment by yeshuchen323** [comment]
> 这个为什么不放到中文的readme里面

放好了~😆
