### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Hiramdu** [secretflow/secretflow#60]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

latest

### What happend and What you expected to happen.

```shell
When I use "pip install -U secretflow":
ERROR: Could not find a version that satisfies the requirement secretflow (from versions: none)
ERROR: No matching distribution found for secretflow
```

### Reproduction code to reproduce the issue.

```shell
pip install -U secretflow
```

**Comment by anakinxc** [comment]
Hi Hiramdu,

Can you fill-in OS Platform info in issue template?

Best

**Comment by Hiramdu** [comment]
x86_64

**Comment by anakinxc** [comment]
> x86_64

Could you also provide OS and Python version? 

All those informations in the issue template can really help us identify issues in time.

Thanks
~A

**Comment by Hiramdu** [comment]
Linux
VERSION="2018.03"
Python 3.6.13
Is it what you ask?

**Comment by anakinxc** [comment]
> Linux VERSION="2018.03" Python 3.6.13 Is it what you ask?

Yes. Secretflow requires Python 3.8, you can use [miniconda](https://docs.conda.io/en/latest/miniconda.html) to setup a Python 3.8 virtual env
