### ISSUE TITLE
确定XGBoost的最优学习轮次，已训练好的XGBoost模型怎么再进行优化

### ISSUE THREAD

**Issue by Endeavor-FYC** [secretflow/secretflow#625]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2b2

### OS Platform and Distribution

Centos 7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
如何确定XGBoost的最优学习轮次，已训练好的XGBoost模型怎么再进行优化
```

### Reproduction code to reproduce the issue.

```shell
如何确定XGBoost的最优学习轮次，已训练好的XGBoost模型怎么再进行优化
```

**Comment by 6fj** [comment]
请问你现在使用的是ss-xgb还是联邦学习中的xgb（水平/垂直分割）？

感谢

**Comment by Endeavor-FYC** [comment]
联邦学习中的xgb，ss-xgb和联邦学习中的xgb在调参方面有什么不同吗

**Comment by Endeavor-FYC** [comment]
联邦学习中的xgb，ss-xgb和联邦学习中的xgb在调参方面有什么不同吗
