### ISSUE TITLE
我自己打的Docker 镜像过大

### ISSUE THREAD

**Issue by zouhuan1215** [secretflow/secretflow#629]
### Issue Type

Feature Request

### Source

source

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

ubuntu 22.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
我对 secretflow 和 spu 的源码进行了一些简单的修改（没有引入额外的依赖）。我想从 `spu-cli:latest` 作为 base image 将改后的源码打包，具体步骤为：
（1）将 `spu-cli: latest` 作为 base-image，将修改后的源码 secretflow 和 spu 源码 copy 到容器中，导出一个新的镜像 new-base
（2）运行 new-base，在 new-base container 中，切换到 secretflow 目录下运行源码安装的命令（python setup.py 和 pip install），然后再切换到 spu 目录下运行源码安装命令
（3）安装完成后，从 new-base container 导出打包好的镜像

但按照上述步骤导出的镜像有 17.5 GB，比 secretflow 发布的官方镜像（约 6 GB）大太多了。
请问有什么减小镜像大小的方法吗？
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by zhouaihui** [comment]
1. 官方镜像目前已经下降到4.4GB了，并且提供了secretflow-lite（docker pull secretlfow/secretflow-lite-anolis8:latest）的基础版本镜像(约1.3GB)，欢迎试用。
2. 你自己打镜像可以参考官方的[dockerfile](https://github.com/secretflow/secretflow/blob/main/docker/release/anolis.Dockerfile)，大部分原因是没有及时清理缓存/临时文件之类的原因。

**Comment by zouhuan1215** [comment]
感谢回答～我参考官方的 dockerfile 清了一下缓存，然后镜像大概小了七个 G 左右。
另外，官方的 dockerfile 安装 secretflow 的方式可能是先把 secretflow 上传到 PyPI 上然后用 pip install 安装，但我们自己打镜像的话应该就不能像官方那样安装 secretflow 了吧？我是按照 secretflow 源码安装的方式安装的 secretflow 的，但用源码安装出来的 secretflow 有 9.56 个 G。
我感觉造成自己打的镜像膨胀那么多的原因应该是有些缓存我还没清掉，目前我只清理了 /root/.cache 。对此，您有什么建议吗？

**Comment by zhouaihui** [comment]
你可以本地打wheel包，然后使用COPY命令拷贝到docker build环境中，直接安装wheel即可。其余步骤可以几乎完全参考官方dockerfile。

打包命令：
`python setup.py sdist_wheel`
