### ISSUE TITLE
ray占用文件过大

### ISSUE THREAD

**Issue by huyz1117** [secretflow/secretflow#637]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.1b0

### OS Platform and Distribution

Centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在运行SGB代码时，会在/tmp/ray目录下产生临时文件，而且比较大，有18个G，非常占用空间，请问有解决办法吗？
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by huyz1117** [comment]
![snapshot3](https://github.com/secretflow/secretflow/assets/45112669/24f5af26-710a-4d23-a4d9-6e254e0bfcd3)

**Comment by zhouaihui** [comment]
ray object store默认使用共享内存做性能加速（如果是macOS，则会直接使用磁盘上的/tmp/）。如果object store内存满了，则会存储到磁盘上。具体原理可以参考 https://docs.ray.io/en/latest/ray-core/scheduling/memory-management.html 

一些优化的手段：
1. 配置更大的shared memory (/dev/shm)
2. 在ray start的时候设置[--object-store-memory](https://docs.ray.io/en/master/cluster/cli.html#cmdoption-ray-start-object-store-memory)。按照ray官方解释，object-store-memory默认是20GB，如果共享内存比这个大，则可以设置的更大。

另外，跑完任务，你可以手动清理掉/tmp/ray/session_xxx目录，一般是用不着了。

**Comment by da-niao-dan** [comment]
最近版本：纵向联邦学习去掉了ray 依赖 不会在有此问题出现。
