### ISSUE TITLE
验证 SecretFlow “快速开始”文档，包括文档流程和示例代码

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#638]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow “[快速开始](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started)”文档，包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by BIGWJZ** [comment]
BIGWJZ Give it to me

**Comment by BIGWJZ** [comment]
**安装验证成功，GPU docker有问题**
### 1. 安装
#### 1.1 本地安装 （成功）
pip _or_ source code complie _or_ WSL


![Image](https://github.com/secretflow/secretflow/assets/49031111/ca1de276-d975-4a08-b9ac-705e65d672df)


#### 1.2 Docker （成功）


![Image](https://github.com/secretflow/secretflow/assets/49031111/6c5a205d-0885-43e6-9daf-35e9b26c962f)

#### 1.3 Use with GPU（有问题）
（1）文档中的命令无法拉取，因为GPU dockerhub没有latest tag，但可以通过版本号拉取。


![Image](https://github.com/secretflow/secretflow/assets/49031111/f6dcd129-4901-4e37-9307-b6007ef99c55)

（2）目前main的git拉下来后，无法根据文档中的命令构建GPU镜像



![Image](https://github.com/secretflow/secretflow/assets/49031111/79e44c67-e9cc-4941-891c-d659bd196859)

**Comment by Mingbo-Lee** [comment]
您好 ！@BIGWJZ 
关于(1) 没有latest tag 的问题，还请 @zhouaihui 帮忙解答一下；
关于(2)，我们近期已经重构了Dockerfile 的文件夹，详情见：https://github.com/secretflow/secretflow/pull/685;
所以出现了文档不对应的问题，感谢您的验证指出的宝贵错误，我们已经提交PR进行修正：https://github.com/secretflow/secretflow/pull/704  马上就会更新。
再次感谢您的工作！

**Comment by Mingbo-Lee** [comment]
```
2.3 Docker仿真
类似2.2，不过在docker中通过bridge network连接，如下图。WSL原理也类似。
```
使用WSL(Windows Subsystem for Linux)部署仿真SecretFlow，这里还需要单独附上截图验证吗？ @zhouaihui

**Comment by zhouaihui** [comment]
源文档中有WSL2部署的章节，是需要验证一遍的。

**Comment by zhouaihui** [comment]
另外，最新的文档还有kuscia部署章节，麻烦看一下最新的部署页面。

**Comment by Mingbo-Lee** [comment]
> 源文档中有WSL2部署的章节，是需要验证一遍的。

@BIGWJZ  麻烦对照WSL2部署的章节，进行验证

**Comment by Mingbo-Lee** [comment]
> 另外，最新的文档还有kuscia部署章节，麻烦看一下最新的部署页面。

@BIGWJZ  这里也一样

**Comment by BIGWJZ** [comment]
### 补充：WSL仿真验证
#### 1. 使用Ray连接两个WSL节点
![image](https://github.com/secretflow/secretflow/assets/49031111/d784800e-5297-4ab2-8b27-425142a26eab)
#### 2. 验证secretflow
![image](https://github.com/secretflow/secretflow/assets/49031111/8af0c4b3-9007-4f4a-aaca-60947a3fd968)
#### 3. 验证SPU使用
![image](https://github.com/secretflow/secretflow/assets/49031111/9fe29d9b-2919-4947-aae5-9b1874160070)
![image](https://github.com/secretflow/secretflow/assets/49031111/64caeff3-83b8-4fd7-bea1-93959ac0e841)

**Comment by Mingbo-Lee** [comment]
> ### 补充：WSL仿真验证
> #### 1. 使用Ray连接两个WSL节点
> ![image](https://user-images.githubusercontent.com/49031111/252979623-d784800e-5297-4ab2-8b27-425142a26eab.png)
> 
> #### 2. 验证secretflow
> ![image](https://user-images.githubusercontent.com/49031111/252980040-8af0c4b3-9007-4f4a-aaca-60947a3fd968.png)
> 
> #### 3. 验证SPU使用
> ![image](https://user-images.githubusercontent.com/49031111/252984551-9fe29d9b-2919-4947-aae5-9b1874160070.png) ![image](https://user-images.githubusercontent.com/49031111/252985356-64caeff3-83b8-4fd7-bea1-93959ac0e841.png)

WSL,  LGTM

**Comment by BIGWJZ** [comment]
### 补充：基于Kuscia部署secretflow
#### 1. 中心化组网并提交两方PSI作业
![image](https://github.com/secretflow/secretflow/assets/49031111/3f37bdeb-7f83-4647-b881-9ba9af9e2f11)
#### 2. P2P组网并提交作业，查看结果
![image](https://github.com/secretflow/secretflow/assets/49031111/31200b74-b2ab-4146-b1fb-7713ad59c461)

**Comment by zhouaihui** [comment]
LGTM ~ Nice work
