### ISSUE TITLE
验证 SecretFlow “组件/预处理”和“组件/隐私集合求交”文档及对应教程，包括文档流程和示例代码

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#639]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow“[组件/预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/preprocessing)”目录和“[组件/隐私集合求交](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/psi)”文档及对应教程（[教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame) [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/PSI_On_SPU)），包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by magic-hya** [comment]
magic-hya Give it to me

**Comment by magic-hya** [comment]
【验证成功】
【容器版本】：secretflow/secretflow-anolis8:latest
1.组件/预处理/Dataframe
![2023-06-19_150831](https://github.com/secretflow/secretflow/assets/85269941/a73f9d58-ed8b-4c8c-bff4-78d23fc462ff)

**Comment by magic-hya** [comment]
2.组件/预处理
![2023-06-19_151025](https://github.com/secretflow/secretflow/assets/85269941/d8ffaff4-6f2b-4530-99af-731d7275919a)

**Comment by magic-hya** [comment]
2.【教程2】-【SPU隐私求交】
![2023-06-19_151126](https://github.com/secretflow/secretflow/assets/85269941/4f72f2c7-2590-4e5a-b884-d5d3e314a04b)

**Comment by magic-hya** [comment]
【教程2】-【SPU隐私求交】，测试执行过程中，求交结果是有输出的，该输出能够展示求交的输入数据条数，求交的输出结果条数，个人建议将该结果也显示在教程文档中，有3个部分，单列求交，多列求交和3方求交
下图是参考样例：
【原教程】
![image](https://github.com/secretflow/secretflow/assets/85269941/aba66cae-94dd-4b31-b6db-66ef4c74b25e)
【测试效果】
![image](https://github.com/secretflow/secretflow/assets/85269941/94e54a50-6e92-47dc-b737-92fa6ee7bcec)
![image](https://github.com/secretflow/secretflow/assets/85269941/d73a63c8-29ce-44c1-b73b-3048dfa10b63)

**Comment by 6fj** [comment]
Hi @magic-hya 

psi结束之后函数会返回运行报告，就是你看到的out[5], 求交结果会保存在输出文件中，而不是作为函数的输出（数据量太大了）。

感谢。
