### ISSUE TITLE
萌新提问：ray start 的时候 resources 起名字和不起名字的区别

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#64]
### Issue Type

Others

### Source

source

### Secretflow Version

beta

### OS Platform and Distribution

Centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
我看咱们隐语的官方教程中，启动ray start resource和代码中init ray的时候都有一个名字——alice bob charlie，可是ray的官方教程中的例子都没有在resources中指定名字。
请问这两种情况下（起名、不起名），在使用时有什么区别吗？

我先说我个人的理解，不起名字时候，ray是一个集群，并没有party的概念，一个task中的所有fun会通过调度分散在集群中的不同节点上执行——即每个节点运行一部分fun

起名之后才有了party的概念，一个task会被submit到不同的party上面执行，而每个party都会运行task中所有的fun？

不知道这么理解是否正确？如下图

```
![image](https://user-images.githubusercontent.com/14867598/181455516-51c0e0fd-b17c-4bba-b89f-d1865f5f0d98.png)

### Reproduction code to reproduce the issue.

```shell
ray start --head --node-ip-address="192.168.137.3" --port="7000" --resources='{"alice": 8}' 
ray start --address="172.16.4.140:6379" --resources='{"bob": 8}'
ray start --address="172.16.4.140:6379" --resources='{"charlie": 8}'
```

**Comment by zhouaihui** [comment]
你的理解基本是对的。

关于这张图片，可以再补充一点：
A/B/C可以执行全部或者部分func，并不要求要运行所有的func，具体哪个party执行哪些func，取决于task的编排。
