### ISSUE TITLE
验证 SecretFlow “组件/联邦学习/水平联邦”文档及对应教程，包括文档流程和代码示例

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#641]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow “[组件/联邦学习/水平联邦](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/federated_learning/horizontal_federated_learning)”目录文档及对应教程（[教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification) [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federated_Learning_with_Pytorch_backend) [教程3](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federated_Xgboost)）“，包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by hengzi** [comment]
hengzi  Give it to me

**Comment by songyueran** [comment]
songyueran give it to me

**Comment by Candicepan** [comment]
目前一个任务仅支持一位社区开发者认领哟～可以优先选择其他未被认领的任务哈 可以在这里的 【Need Triage】中查看哈 https://github.com/orgs/secretflow/projects/1/views/1

**Comment by Candicepan** [comment]
> songyueran give it to me

目前一个任务仅支持一位社区开发者认领哟～可以优先选择其他未被认领的任务哈 可以在这里的 【Need Triage】中查看哈 https://github.com/orgs/secretflow/projects/1/views/1

**Comment by songyueran** [comment]
好的&nbsp;


AD钙奶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月11日(星期天) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [secretflow/secretflow] 验证 SecretFlow “组件/联邦学习/水平联邦”文档及对应教程，包括文档流程和代码示例 (Issue #641)





 
目前一个任务仅支持一位社区开发者认领哟～可以优先选择其他未被认领的任务哈 可以在这里的 【Need Triage】中查看哈 https://github.com/orgs/secretflow/projects/1/views/1

**Comment by hengzi** [comment]
教程1 验证成功
![image](https://github.com/secretflow/secretflow/assets/1209435/4c0a109b-e913-4fe2-81f5-512984bf2f25)
![image](https://github.com/secretflow/secretflow/assets/1209435/02a373f1-3cc3-4b5d-b1ca-742c01d87226)
![image](https://github.com/secretflow/secretflow/assets/1209435/7f07fa40-d016-4953-992c-3da02da9753b)

**Comment by hengzi** [comment]
教程1 验证成功

![image](https://github.com/secretflow/secretflow/assets/1209435/28f305f8-b8bd-46dd-b033-4dbbdc3d0f6b)
![image](https://github.com/secretflow/secretflow/assets/1209435/925aa6a3-9e7e-4d41-9875-568661ae75a5)

**Comment by hengzi** [comment]
部分文档需要修改 #688
