### ISSUE TITLE
验证 SecretFlow “组件/联邦学习/垂直联邦学习”和“组件/联邦学习/混合联邦”文档及对应教程，包括文档流程和代码示例

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#642]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow “[组件/联邦学习/垂直联邦学习](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/federated_learning/vertical_federated_learning)”和“[组件/联邦学习/混合联邦](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/components/federated_learning/mix_federated_learning)”文档及对应教程（[教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing) [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/split_learning_gnn) [教程3](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/SecureBoost) [教程4](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/mix_lr)）“，包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by Lia0409** [comment]
Lia0409 Give it to me

**Comment by Lia0409** [comment]
#@- [ ] [教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing)
验证成功
![1 8](https://github.com/secretflow/secretflow/assets/94959553/10406e53-0909-497f-bf00-d943307f5a17)
![1 9](https://github.com/secretflow/secretflow/assets/94959553/599545d7-d0d4-48a2-9240-b1eafdf92a08)
![1 10](https://github.com/secretflow/secretflow/assets/94959553/aba38b69-0e59-4799-ae15-7c058e9e5c37)
![1 12](https://github.com/secretflow/secretflow/assets/94959553/7c54bc01-9921-4b41-b9c1-504859e4e278)

**Comment by Lia0409** [comment]
[教程3](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/SecureBoost)
验证成功
![3 1](https://github.com/secretflow/secretflow/assets/94959553/d4dc53c4-2b34-4ddf-875f-7138ac71f207)
![3 2](https://github.com/secretflow/secretflow/assets/94959553/9e844ee5-cad6-4cbf-afa9-8f1060f7d748)

**Comment by Lia0409** [comment]
[教程4](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/mix_lr)
验证成功
![4444](https://github.com/secretflow/secretflow/assets/94959553/afa10492-b24e-4e39-bcc0-330bad958b2f)

**Comment by Lia0409** [comment]
[教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/split_learning_gnn)
对Split Learning for Graph Neural Network的验证过程出现了两个小问题：
1：在pycharm+jupyter中编译代码时，from tensorflow.keras import activations 等相关语句会标红（但不影响训练），原因是安装tensorflow环境下的keras有中间路径，可以根据情况修改为from tensorflow.python.keras import activations

2：在全部图数据上进行实验，使内存消耗极大，不足以训练完10个epoch，在这个过程会被提示worker dead
![2 0](https://github.com/secretflow/secretflow/assets/94959553/6985df49-e6c7-4856-a98c-5ab98b0c995b)
尝试调小epoch的数量，代码可成功运行
![2222](https://github.com/secretflow/secretflow/assets/94959553/ae02ed50-7137-4e94-af36-a42ab46d92d9)
