### ISSUE TITLE
验证 SecretFlow ”数据加载“相关教程，包括文档流程和代码示例

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#643]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow “数据加载相关教程（[教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/FedDataFrameDataLoader) [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/FedNdarrayDataLoader) [教程3](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTF) [教程4](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTorch) [教程5](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)）“，包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by WildWolfBang** [comment]
【WildWolfBang + Give it to me】

**Comment by WildWolfBang** [comment]
- [x] [教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/FedDataFrameDataLoader) 验证正常
![image](https://github.com/secretflow/secretflow/assets/17874410/f7447c5a-963d-4e33-ba2e-6a6bbfb00fd7)

- [x] [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/FedNdarrayDataLoader) 验证正常
![image](https://github.com/secretflow/secretflow/assets/17874410/6a5ff875-1ce3-4389-992f-d21e4ddef3b8)

- [ ] [教程3](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTF) 遇到环境问题暂未解决，稍后处理
![image](https://github.com/secretflow/secretflow/assets/17874410/a6d29e14-5ebd-4382-b60e-bbebbc6a4006)

- [ ] [教程4](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTorch) 未开始
- [ ] [教程5](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL) 未开始

**Comment by BJTUpupil** [comment]
教程4需要有一个小小的修改是在对utlis包文件导入的时候，目前的版本是：
from secretflow.ml.nn.fl.backend.torch.utils import BaseModule
需要修改为
from secretflow.ml.nn.utils import BaseModule

**Comment by zhangxingmeng** [comment]
@BJTUpupil 
Hi，感谢参与验证，在验证过程中，发现有问题需要修改的部分，或者描述还不够清晰的部分，可以直接提pr进行修改，我们会在稍后进行review，感谢

**Comment by zhangxingmeng** [comment]
感谢@WildWolfBang 同学的验证，这个issue就暂时关闭啦，在使用过程中有其他问题可以随时提issue，有修改的想法也可以提pr。期待您的参与共建。
