### ISSUE TITLE
验证 SecretFlow “SPU” 相关教程，包括文档流程和代码示例

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#644]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow “SPU 相关教程（[教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/spu_basics) [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/lr_with_spu) [教程3](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/nn_with_spu) [教程4](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/numpy_with_spu)）“，包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by magic-hya** [comment]
magic-hya    Give it to me

**Comment by imwangyt** [comment]
imwangyt Give it to me

**Comment by imwangyt** [comment]
@zhouaihui “Pass a Python Object from Host to SPU”好像不存在，因为不能直接使用sf.to(spu, pyobject)，必须借助sf.to(pyu, pyobject)得到PYUObject，然后在pyuobject.to(spu)；而且这时候查看spuobject的meta和shares都是ObjectRef，和“Pass a PYU Object from PYU to SPU”是一样的。


![Image](https://github.com/secretflow/secretflow/assets/6252890/6cca8409-1aa8-4f73-bf1d-637698d2c963)

**Comment by imwangyt** [comment]
@zhouaihui 
哈喽，我查看了一下历史版本，在 0.7.11b3 时，sf.to 是允许直接从 Host/Driver 传递数据给 SPU，也是在 Host 调用 SPUIO 并构建 SPUObject 的，因此，可以在 Host 查看 SPUValueMeta 及 shares。

```python
    if isinstance(device, SPU):
        vtype = Visibility.VIS_PUBLIC if spu_vis == 'public' else Visibility.VIS_SECRET
        io = SPUIO(device.conf, device.world_size)
        meta, *shares = io.make_shares(data, vtype)
        return SPUObject(device, meta, shares)
```

现在的版本既然已经禁止从 Host 直接传递给 SPU ，[SPU 基础](https://www.secretflow.org.cn/docs/secretflow/latest/en-US/tutorial/spu_basics#Pass-Values-to-SPU-device)中关于“Pass a Python Object from Host to SPU”的相关说明是否调整/移除比较合适？

```python
    if isinstance(device, SPU):
        raise ValueError(
            "You cannot put data to SPU directly, "
            "try put it to PYU and then move to SPU"
        )
```

**Comment by 6fj** [comment]
Hi @imwangyt 

Nice catch！

在引入[rayfed](https://github.com/ray-project/rayfed) 之后，secretflow不再支持从host将数据传给spu device。当时只调整了所有代码部分，而没有关注文档的文本部分。

烦请发起pr更改，感谢！

**Comment by 6fj** [comment]
#678

**Comment by 6fj** [comment]
Hi @imwangyt 

我已经更新了notebook，由于官网文档并不会立即生效，烦请直接阅读代码来验证文档。

感谢。

**Comment by imwangyt** [comment]
验证成功！

验证环境：secretflow 0.8.3b0 @ wsl Ubuntu-22.04

# SPU基础
![image](https://github.com/secretflow/secretflow/assets/6252890/d9557659-9edd-4250-8e6e-54de7c7905ae)

# LR@SPU
![image](https://github.com/secretflow/secretflow/assets/6252890/f591be5a-e981-4e12-822c-a4b020fb5881)

# NN@SPU
![image](https://github.com/secretflow/secretflow/assets/6252890/e8a0ead5-0e35-44eb-b16a-76129eef00db)

# Numpy@SPU
![image](https://github.com/secretflow/secretflow/assets/6252890/5dc131fa-e5cd-4292-a39f-6ac01d6f0694)

**Comment by imwangyt** [comment]
Numpy@SPU部分，做了些格式修复。

**Comment by BJTUpupil** [comment]
我部署的环境无法运行SPU计算，异常信息显示中是ray的任务管理出问题了，异常如下：
worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=329, ip=10.102.2.5, repr=SPURuntime(device_id=None, party=bob))
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_spu_compile() (pid=32488, ip=10.102.2.5)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1377, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 148, in compile
    ir_text, output = _jax_compilation(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 75, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/api.py", line 555, in computation_maker
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/interpreters/mlir.py", line 646, in lower_jaxpr_to_module
    raise ValueError(f"Unknown platform {platform}")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Unknown platform interpreter

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

**Comment by 6fj** [comment]
hi @BJTUpupil 

烦请将你的问题重新发一个issue。

感谢。
