### ISSUE TITLE
验证 SecretFlow 部分教程，包括文档流程和代码示例

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#645]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：验证 SecretFlow “部分教程（[教程1](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/risk_control_scenario) [教程2](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/practical_case_walkthrough_using_sf_with_spu)）“，包括文档流程和示例代码
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求
请基于 SecretFlow 最新版本进行上述文档的操作流程和代码验证，确认代码是否能够成功运行。在验证代码逻辑的同时，也欢迎对文档内容通顺（语句与错别字等）进行修正。

- 若代码能够成功运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若代码无法跑通，请在本 ISSUE 下反馈具体问题，并尝试解决该问题，将能够成功运行的代码通过 PR 形式提交并关联本 ISSUE（比如 [#445](https://github.com/secretflow/secretflow/pull/445) 或者 [#561](https://github.com/secretflow/secretflow/pull/561)）
- 涉及代码修改，需符合代码规范，参照主 repo [要求](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#formatter)
- 若要更新文档内容（语句与错别字等），需同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)

## 能力要求
- 了解基本 git 操作
- 对 SecretFlow 有一定了解，成功运行过部分示例

## 参考范例
- [#439](https://github.com/secretflow/secretflow/pull/439)
- [#420](https://github.com/secretflow/secretflow/pull/420)

**Comment by Zhang-gong** [comment]
Zhang-gong Give it to me

**Comment by Zhang-gong** [comment]
验证成功

## 教程1


![Image](https://github.com/secretflow/secretflow/assets/74176806/f4302215-b0d0-467f-8614-20271cb80a5d)
![Image](https://github.com/secretflow/secretflow/assets/74176806/851b2315-0a11-4fc6-9d93-baca5dcecf8d)
![Image](https://github.com/secretflow/secretflow/assets/74176806/9676fb82-1f35-4b0a-89cf-3d8a70c6cc41)


## 教程2
![Image](https://github.com/secretflow/secretflow/assets/74176806/cdf6ca24-28fa-4803-98a4-a90dadcf7aa4)
![Image](https://github.com/secretflow/secretflow/assets/74176806/3e8d7e78-abe2-445b-acc4-873da20c7170)
![Image](https://github.com/secretflow/secretflow/assets/74176806/23bd4c8e-0446-4f73-ac58-d60520a6669e)
![Image](https://github.com/secretflow/secretflow/assets/74176806/5d99d240-0929-4770-afd7-2f5f8359fef3)
