### ISSUE TITLE
请问ray网络的生命周期——Head节点的高可用怎么做

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#65]
### Issue Type

Others

### Source

source

### Secretflow Version

beta

### OS Platform and Distribution

Centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
请问是先创建ray网络，还是先执行任务。
如果先创建ray网络，如果header节点宕机了，高可用怎么做？

1、创建ray网络
ray start --head --node-ip-address="192.168.137.3" --port="7000" --resources='{"alice": 8}'
ray start --address="172.16.4.140:6379" --resources='{"bob": 8}' 

2、执行任务
import secretflow as sf
import spu

sf.shutdown()
sf.init(address='alice's ip:8881')
alice = sf.PYU('alice')
bob = sf.PYU('bob')
device = sf.SPU({
……
```

### Reproduction code to reproduce the issue.

```shell
1、创建ray网络
ray start --head --node-ip-address="192.168.137.3" --port="7000" --resources='{"alice": 8}'
ray start --address="172.16.4.140:6379" --resources='{"bob": 8}' 

2、执行任务
import secretflow as sf
import spu

sf.shutdown()
sf.init(address='alice's ip:8881')
alice = sf.PYU('alice')
bob = sf.PYU('bob')
device = sf.SPU({
……
```

**Comment by zhouaihui** [comment]
> 请问是先创建ray网络，还是先执行任务。 

需要首先创建ray集群，再执行任务。

关于ray head HA，目前我们了解到的是ray有计划在支持HA，参见 [ray 2.0](https://github.com/ray-project/ray/issues/22833)提到的`Cluster Fault Tolerance`。

目前secretflow的主要使用方式是离线式计算任务，对HA的要求有限。

**Comment by holdbelief** [comment]
> 需要首先创建ray集群，再执行任务。
> 
> 关于ray head HA，目前我们了解到的是ray有计划在支持HA，参见 [ray 2.0](https://github.com/ray-project/ray/issues/22833)提到的`Cluster Fault Tolerance`。
> 
> 目前secretflow的主要使用方式是离线式计算任务，对HA的要求有限

请问有推理的例子吗？
