### ISSUE TITLE
隐语“官网”新版上线！回复issue参与互动，有机会赢取社区周边好礼🎉

### ISSUE THREAD

**Issue by halosecret00** [secretflow/secretflow#652]
### 活动规则说明

距 2022 年 7 月隐语开源马上就要 1 周年啦🎉～隐语官网也迎来了 2.0 全新大改版！

为了感谢社区小伙伴对隐语的支持，社区特别准备了彩蛋活动。❤️

1⃣️「**在本条 issue 界面回复留言，写下对隐语社区的“寄语”，即有机会获得社区周边好礼**」
（对隐语的期望、鼓励、建议都可以留言分享呀～将在活动结束后选取有趣、认真留言的小伙伴送出社区周边哟）

2⃣️  **弹幕墙**：留言内容将在1小时后在活动页🔗弹幕墙显示，记得回来查看你的专属留言噢～～
🔗直达链接：https://www.secretflow.org.cn/events/202306

👉**隐语代码仓**：欢迎小伙伴点击右上角🌟 Star，收藏隐语 repo，及时获取开源项目最新动态。

🏠**隐语官网**：https://www.secretflow.org.cn

⏰**活动时间**：2023/6/12 08:00 - 2023/6/21 12:00 (GTM+8)

✈️**活动礼品：**

- 隐语社区周边：限量定制T恤 X 3 件
- 隐语社区周边：充电宝礼盒装 X 2 份
- 蚂蚁庄园小鸡公仔 X 2 份
- 蚂蚁公仔桌面摆件 X 1 份
- 禁止焦虑系列马克杯 X 1 份

<img width="372" alt="image" src="https://github.com/secretflow/secretflow/assets/109133653/593b640d-99a5-424e-8775-bef91614ad8a">

😄隐语 1 周年线下活动计划在 7 月 22 日上海进行，[欢迎大家点击报名，锁定名额。
](https://www.wjx.top/vm/mpP0iXr.aspx# )

**Comment by 6fj** [comment]
希望隐语可以收获更多小伙伴的✨
&
小鸡公仔感觉很不错～

**Comment by Chrisdehe** [comment]
从隐语框架开源就一直关注， 隐语在整个隐私计算开源方面做出了卓越的贡献，无论是在使用还是在算法上都是无与伦比的，非常感谢隐语对我技术实现上的支持，在这里祝隐语一周年活动顺利举办成功，祝愿隐语开源平台茁壮成长，体验越来越好，用户越来越多！

**Comment by halosecret00** [comment]
❤️希望隐语能为各个行业的数据安全和隐私问题提供切实可行的解决方案，帮助行业实现更好的发展，推动隐私计算技术普及和应用。

**Comment by yohacai** [comment]
一直在关注隐语的发展，真的是越来越好了

**Comment by xqdoudou** [comment]
希望隐语在未来，可以打破行业壁垒，不断拓展技术边界，为数据共享、数据协同和数据价值挖掘提供更多可能性。

**Comment by Candicepan** [comment]
哇偶～预祝“隐语宝宝”一周岁快乐🎂 也希望有更多小伙伴可以加入隐语社区的共建呀，跟“隐语宝宝”一起茁壮成长，可以✨ star 关注动态 & 参与[「隐语 OSCP」](https://github.com/orgs/secretflow/discussions/647) 活动，快来认领任务呀 😏

**Comment by lili12589** [comment]
希望隐语越来越好，能为隐私计算行业贡献出最大的价值（ps：蚂蚁超人看着好帅）

**Comment by Candicepan** [comment]
> 希望隐语可以收获更多小伙伴的✨ & 小鸡公仔感觉很不错～

小鸡公仔真的好可爱嗷

**Comment by yeshuchen323** [comment]
许愿1.0版早点出来，特别是框架这块还有前端交互组件啥的~

**Comment by zhouaihui** [comment]
看着自己娃长大，继续努力!!!

**Comment by chenbuhua** [comment]
祝隐语一周岁快乐～希望隐语1.0能给隐私计算行业注入新的能量～

**Comment by nainai123** [comment]
哇哦  ，希望支持更多的算法 ，同时也希望隐语越做越好

**Comment by suhang1111** [comment]
一直都有关注隐语社区的发展，社区作为隐私计算入门的“引路人”与“布道者”，希望隐语社区“做大做强，再创辉煌”。

**Comment by zhangxingmeng** [comment]
希望隐语能够在不远的未来成为隐私计算行业的旗帜。未来一定会越来越好的！

**Comment by wyinggui** [comment]
希望隐语开源更多的技术模态，不求最好只求更好

**Comment by zhanglei486** [comment]
祝隐语一周岁快乐，后续功能更完善，更好的促进和服务隐私计算行业发展

**Comment by XiaoHwei** [comment]
一直关注隐语发展，希望隐语越来越完善，能有更多更强大的功能

**Comment by chenbuhua** [comment]
小鸡公仔冲～

**Comment by usafchn** [comment]
祝隐语一周岁快乐~

**Comment by NewByVector** [comment]
Run! Don’t walk. You are either running for food or running from being food.

**Comment by liang-xiaojian** [comment]
隐语一周年快乐！😄希望隐语能支持更多算法～不断推动隐私计算行业发展～

**Comment by xfap** [comment]
隐语一周年冲冲冲！

**Comment by ian-huu** [comment]
一周年快乐，小鸡冲冲冲 🤩

**Comment by Mingbo-Lee** [comment]
隐语开源一周年快乐！希望隐语的应用范围越来越广！限量定制T恤非常棒！浓厚的社区归属感！

**Comment by sswdaytoy** [comment]
祝隐语一岁生日快乐鸭~通过隐语和隐语的开发支持人员，学到了很多东西，希望能在接下来一起陪伴，一起成长~

**Comment by anakinxc** [comment]
希望隐语越做越好，成为行业标准~

**Comment by tpppppub** [comment]
希望隐语越做越好，生日快乐🎂

**Comment by bubkoo** [comment]
隐语的生日是每年的7月7号吗，也正是一年中的小暑，预示着盛夏的到来。

**Comment by halosecret00** [comment]
> 

是7月4日哈哈～😁

**Comment by halosecret00** [comment]
> 隐语的生日是每年的7月7号吗，也正是一年中的暑假，预示着盛夏的到来。

是7月4号 哈哈～

**Comment by NewByVector** [comment]
<script>alert('隐语生日快乐！')</script>

**Comment by chenbuhua** [comment]
希望隐语越做越好，助力隐私计算行业更上一层楼～

**Comment by Angelii** [comment]
给隐语打 call！
祝越来越好！

**Comment by TengFei-zju** [comment]
隐语越来越好~

**Comment by imwangyt** [comment]
希望隐语社区人气爆棚、共建涌现、茁壮成长，驱动隐语开源PR天天有、Meetup月月来、Star节节高~~
还有，小剧场Post天天发、篇篇靓~~

**Comment by novioleo** [comment]
恭喜恭喜！！祝越来越好。明年继续来。

**Comment by shazi4399** [comment]
祝福隐语越来越好，功能更加完善和强大，隐私计算行业有更广阔的发展前景。

**Comment by WildWolfBang** [comment]
隐私计算大有可为，隐语社区做大做强

**Comment by blue-moon-dreamer** [comment]
恭喜隐语！希望隐语能为隐私计算领域贡献更大的力量！同时希望我们也能和隐语一起成长，共建隐私计算的未来！

**Comment by Endeavor-FYC** [comment]
一周岁快乐乐乐乐！！祝隐语越来越好，做大做强，做优做精！

**Comment by hhq326781458** [comment]
祝隐语越来越好。一周岁快乐！

**Comment by Lia0409** [comment]
隐语开源一周年快乐！！希望能和隐语一起成长，不断完善和充实自己，这简直泰酷辣！

**Comment by JosieZhu** [comment]
周年快乐！！！感觉隐语社区就像一个属于隐私计算的游乐园hh
希望隐语越办越好！一起向隐私计算的未来迈进！！！

**Comment by whitesleep333** [comment]
希望隐语越来越好，打造一个功能完备，性能优异，平台易用的开源框架，造福所有人

**Comment by yekai1003** [comment]
准备加入隐私计算赛道了，希望隐语能够带我起飞~~~~！

**Comment by dalongguo** [comment]
secretflow & alice $ bob forever

**Comment by halosecret00** [comment]
> 准备加入隐私计算赛道了，希望隐语能够带我起飞~~~~！

一起冲冲冲✈️

**Comment by halosecret00** [comment]
> 隐语开源一周年快乐！！希望能和隐语一起成长，不断完善和充实自己，这简直泰酷辣！

👀太酷太酷啦～

**Comment by gjj0725** [comment]
数据文明的探索正由聚焦数据本身的价值进化为通过共享实现增值。我们正在加速买进数据密态时代。
我们产品对于隐私计算的需求比较强烈，作为技术研发，调研了很多同类产品。对比下来，隐语还是非常有优势的。加油，祝隐语越来越好！

**Comment by halosecret00** [comment]
> 希望隐语社区人气爆棚、共建涌现、茁壮成长，驱动隐语开源PR天天有、Meetup月月来、Star节节高~~ 还有，小剧场Post天天发、篇篇靓~~

✌️说得太好啦～感谢一直以来对隐语的支持❤️一起upupup～

**Comment by pomelo-nwu** [comment]
一周年，冲冲冲！

**Comment by Yank3l** [comment]
希望自己能够和隐语一起成长，毕业后能够加入隐语团队

**Comment by Angelii** [comment]
希望隐语越来越好，隐语加油。

**Comment by wxjweb** [comment]
希望隐语得到越来越多的小伙伴的支持，让隐语在隐私计算领域发扬光大

**Comment by llCurious** [comment]
隐语一步一个脚印，做大做强！

**Comment by LzyloveRila** [comment]
太牛了！

**Comment by gxx777** [comment]
SPU yyds！

**Comment by youngerwiz** [comment]
secretflow /lgtm /approved

**Comment by Angelii** [comment]
限量定制T恤，有点心动

**Comment by CHEN-CONGCONG** [comment]
隐语加油~

**Comment by gujinyue1010** [comment]
加油，很看好这个隐私计算方向

**Comment by zhifeng110** [comment]
祝隐语小宝宝一周岁快乐

**Comment by bigdadel** [comment]
隐语加油，一起加油！

**Comment by manchester-club** [comment]
祝福隐语越办越好，大家一起加油！

**Comment by lidh15** [comment]
祝早日推出1.0！

**Comment by LianghuaFL** [comment]
感谢隐语一年以来所做的贡献，作为隐私计算的科研小白，真的学到很多，感谢！希望尽早推出2.0版本🎉

**Comment by Niclouge** [comment]
一起加油！助力隐私保护与隐私保护生态建设，也希望联邦学习能够越做越好

**Comment by HopeDevote** [comment]
希望隐语发展越来越好，相关应用能快快应用它呀

**Comment by Nickzhong789** [comment]
祝隐语发展越来越好，社区越来越壮大！感谢隐语让我学到了很多隐私计算相关的知识！

**Comment by dazhuao** [comment]
一周年快乐！希望社区越来越壮大！隐私计算哪家强？隐语必须算得上！

**Comment by IvvvyGao** [comment]
关键词检索功能太好用太方便了～期待隐语快速更新！

**Comment by luojiashanxia** [comment]
祝隐语一周年生日快乐！在老师指导的一篇智联网综述的文章中了解到隐私计算！希望社区越来越壮大！希望以后有机会进公司！

**Comment by halosecret00** [comment]
本次彩蛋活动期间共收到 60+ 条来自社区用户的留言祝福❤️，我们从中选取了9位幸运小伙伴，送上小礼品🎁一份，记得私信联系隐语小助手（SecreFlow01）领取礼品呀！🎉 @WildWolfBang @Mingbo-Lee @Lia0409 @whitesleep333 @imwangyt @xqdoudou @NewByVector @gjj0725 @IvvvyGao

**Comment by nnjdksskskn** [comment]
祝隐语一周年生日快乐~

**Comment by Ankh97** [comment]
希望隐语能够在不远的未来成为隐私计算行业的旗帜。未来一定会越来越好的！

**Comment by HopeDevote** [comment]
您好，您的文件我已收到！

**Comment by HopeDevote** [comment]
您好，您的文件我已收到！

**Comment by lidh15** [comment]
您好，您的文件我已收到！

**Comment by HopeDevote** [comment]
您好，您的文件我已收到！

**Comment by lidh15** [comment]
您好，您的文件我已收到！
