### ISSUE TITLE
指定列求交 & 使用单列求交，是否存在性能差异？

### ISSUE THREAD

**Issue by chenyouPomelo** [secretflow/secretflow#654]
【使用simple_psi.py进行指定列求交】
假设有一份n列的数据集，指定第3列去求交和直接对只有单列的数据集求交，请问二者是否有性能差异？
（i.e.，指定列求交时是单独发送列还是整行都被发送？如果是整行的话我们担心传输的字节数可能会大很多）

”simple_psi.py“
selected_fields = FLAGS.field_names.split(",")

    config = psi.BucketPsiConfig(
        psi_type=psi.PsiType.Value(FLAGS.protocol),
        broadcast_result=True if FLAGS.receiver_rank < 0 else False,
        receiver_rank=FLAGS.receiver_rank if FLAGS.receiver_rank >= 0 else 0,
        input_params=psi.InputParams(
            path=FLAGS.in_path,
            select_fields=selected_fields,
            precheck=FLAGS.precheck_input,
        ),
        output_params=psi.OutputParams(
            path=FLAGS.out_path, need_sort=FLAGS.output_sort
        ),
        bucket_size=FLAGS.bucket_size,
        curve_type=psi.CurveType.CURVE_25519,
    )

**Comment by zhanglei486** [comment]
介绍一下对于指定列的处理方式：读取csv的多列拼接在一起，进行hash处理，hash处理的结果参与PSI协议的处理
所以单列或多列只影响数据读取时的性能，并不影响PSI协议执行过程的性能

**Comment by chenyouPomelo** [comment]
> 介绍一下对于指定列的处理方式：读取csv的多列拼接在一起，进行hash处理，hash处理的结果参与PSI协议的处理 所以单列或多列只影响数据读取时的性能，并不影响PSI协议执行过程的性能

好的，谢谢您～
