### ISSUE TITLE
请问有没有纵向联邦回归算法的例子啊？

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#67]
官网上面的例子都是横向的：“Federate Learning for Image Classification”、“Federate Xgboosts”
有一个例子数据是纵向的，但是算法用的是mpc：“Logistic Regression with SPU”

有没有纵向联邦回归算法的例子啊？

**Comment by zhouaihui** [comment]
我猜你想找的是[Split Learning示例](https://secretflow.readthedocs.io/en/latest/tutorial/Split_Learning_for_bank_marketing.html) 。

**Comment by holdbelief** [comment]
谢谢
