### ISSUE TITLE
PIR运行时报错

### ISSUE THREAD

**Issue by dyx0001** [secretflow/secretflow#680]
造了一些PIR的数据，在运行匿踪查询时报错:
[root@bogon path]# python pir_two_parties3.py
2023-06-16 05:56:46,543 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.200.3.116:3029...
2023-06-16 05:56:46,555 INFO worker.py:1538 -- Connected to Ray cluster.
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.324 [info] [ecdh_oprf_selector.cc:CreateEcdhOprfServer:32] use fourq
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.326 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 7
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.338 [info] [sender_db.cc:DispatchInsertOrAssign:652] Launching 1 insert-or-assign worker tasks
I0616 05:57:03.698022 140136276382720 pir_two_parties3.py:58] offline psi reports: [{'party': 'bob', 'data_count': 120}]
I0616 05:57:03.698410 140136276382720 pir_two_parties3.py:59] cost time: 17.06573748588562
(SPURuntime pid=31689) 2023-06-16 05:57:03.729 [info] [receiver.cc:RequestQuery:203] cuckoo table_size:341
(SPURuntime pid=31689) 2023-06-16 05:57:03.729 [info] [receiver.cc:RequestQuery:228] Finished inserting items with 1 hash functions; cuckoo table fill-rate: 0.002932551319648094
(SPURuntime pid=31689) 2023-06-16 05:57:03.732 [info] [receiver.cc:RequestQuery:280] plain_powers size:1, using_keyswitching:false
(SPURuntime pid=31689) INFO:root:rank:0 recv 9 sync status
(SPURuntime pid=31689) 2023-06-16 05:57:03.741 [info] [receiver.cc:RequestQuery:305] encrypted_powers size: 20
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.695 [info] [sender_db.cc:DispatchInsertOrAssign:670] Finished insert-or-assign worker tasks
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.696 [info] [sender_db.cc:InsertOrAssign:1278] Finished inserting 120 items in SenderDB
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.704 [info] [pir.cc:LabeledPirServer:226] table_params hash_func_count:1
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.720 [info] [ecdh_oprf_selector.cc:CreateEcdhOprfServer:32] use fourq
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.720 [info] [pir.cc:LabeledPirServer:237] db GetItemCount:120
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.728 [info] [pir.cc:LabeledPirServer:265] client data size: 1
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.728 [info] [ecdh_oprf_selector.cc:CreateEcdhOprfServer:32] use fourq
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.749 [info] [sender.cc:SenderRunQuery:287] Start processing query request on database with 120 items
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.749 [info] [sender.cc:reset_powers_dag:114] Configured PowersDag with depth 0
(SPURuntime pid=2124, ip=10.200.3.117) 2023-06-16 05:57:03.771 [info] [sender.cc:SenderRunQuery:381] Finished processing query request
(SPURuntime pid=2124, ip=10.200.3.117) INFO:root:rank:1 send 9 sync status
Traceback (most recent call last):
  File "pir_two_parties3.py", line 96, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "pir_two_parties3.py", line 84, in main
    reports = spu.pir_query(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1802, in pir_query
    return dispatch(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 527, in pir_query
    return sfd.get(res)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 75, in get
    return ray.get(object_refs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_query() (pid=31689, ip=10.200.3.116, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fc81bc8b700>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1179, in pir_query
    report = pir.pir_client(self.link, config)
  File "/usr/local/lib/python3.8/site-packages/spu/pir.py", line 48, in pir_client
    report_str = libspu.libs.pir_client(link, config.SerializeToString())
RuntimeError: what:
        [Enforce fail at libspu/psi/utils/utils.cc:179] (proto.ParseFromArray(data.data(), data.size())).
stacktrace:
#0 spu::psi::LabelPsiReceiver::ProcessQueryResult()+0x7fc827dc4a44
#1 std::_Function_handler<>::_M_invoke()+0x7fc827dc5073
#2 std::_Function_handler<>::_M_invoke()+0x7fc827a8002b
#3 yacl::internal::_parallel_run()+0x7fc8280a47a8
#4 yacl::parallel_for()+0x7fc827a8aaf7
#5 spu::psi::LabelPsiReceiver::RequestQuery()+0x7fc827dc8ffb
#6 spu::pir::LabeledPirClient()+0x7fc827db2c9e
#7 spu::pir::PirClient()+0x7fc827db4054
#8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fc826e3044f
#9 pybind11::cpp_function::dispatcher()+0x7fc826e0a6d6
#10 PyCFunction_Call+0x4e0212
请问我造的数据表头是中文，有18个字段，而且数据中有很多中文，这个错是否是数据超长了？

**Comment by zhanglei486** [comment]
辛苦发一下secertflow和spu 的版本号
建议更新到最新的版本试一下

**Comment by dyx0001** [comment]
我这里是docker模式部署，secertflow镜像是我6月6号下载的latest版本，这个需要再下载一次镜像么？

**Comment by Chrisdehe** [comment]
是的，latest版本仅是当前最新版本，您还需要再一次下载，目前最新版本为[secretflow 0.8.3b0](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation)

**Comment by dyx0001** [comment]
好的

**Comment by dyx0001** [comment]
@Chrisdehe 官方提供的这个地址：https://hub.docker.com/r/secretflow/secretflow-anolis8/tags ，为什么无法打开，我记得之前是可以访问的，而且现在用docker pull secretflow/secretflow-anolis8:0.8.3b0 总是报以下错误：
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
是否还有其他下载镜像的方法？

**Comment by Chrisdehe** [comment]
可以配置下docker镜像加速器
操作方法：
创建或修改 /etc/docker/daemon.json：
sudo mkdir -p /etc/docker 
sudo tee /etc/docker/daemon.json 

{
    "registry-mirrors": [
        "https://docker.m.daocloud.io",
        "https://dockerproxy.com",
        "https://docker.mirrors.ustc.edu.cn",
        "https://docker.nju.edu.cn"
    ]
}

sudo systemctl daemon-reload
sudo systemctl restart docker

**Comment by Chrisdehe** [comment]
可以按照这个方法配置下docker镜像加速哈
https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6?permalink_comment_id=4601317#gistcomment-4601317
