### ISSUE TITLE
hdf.mean in tutorial/DataFrame.ipynb appears to have output different from true value

### ISSUE THREAD

**Issue by come2ry** [secretflow/secretflow#69]
### Issue Type

Documentation Bug

### Source

binary

### Secretflow Version

0.6.13b1

### OS Platform and Distribution

Anolis OS release 8.6

### Python version

3.8.12

### What happend and What you expected to happen.

I was looking at tutorial's DataFrame.ipynb and noticed that the hdf.mean(numeric_only=True) and vdf.mean(numeric_only=True) results are different, is this expected behavior?

I thought the result of mean would be the same whether the division method is horizontal or vertical, am I misunderstanding something?

Thinking it might be a typo in the documentation, I tried to reproduce it using [spu's Dockerfile ](https://github.com/secretflow/spu/blob/beta/docker/spu-gcc11-anolis-amd64-dev.Dockerfile) and confirmed that the output is as follows, just as in the documentation.

```shell
>>> hdf.mean(numeric_only=True)
sepal length (cm)    1.168667
sepal width (cm)     0.611467
petal length (cm)    0.751600
petal width (cm)     0.239867
target               0.200000
dtype: float64

>>> vdf.mean(numeric_only=True)
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64

>> data.mean(numeric_only=True)
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64
```

### Reproduction code to reproduce the issue.

```shell
Can be reproduced by running https://github.com/secretflow/secretflow/blob/beta/docs/tutorial/DataFrame.ipynb
```

**Comment by zhouaihui** [comment]
Yes, it's a bug. `hdf.mean` and `vdf.mean` should be same.
We will fix it soon. Thank you for reporting this bug.

**Comment by come2ry** [comment]
@zhouaihui 
I can't reply to [your message on this PR](https://github.com/secretflow/secretflow/pull/68#issuecomment-1199045066), so I will reply here.

I have included my contact information on my GitHub profile, so please feel free to contact me anytime.
