### ISSUE TITLE
请教关于逻辑回归模型加载和评估出现的问题

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#690]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.15

### Bazel version

5.4.1

### GCC/Compiler version

11.2

**Comment by da-niao-dan** [comment]
你好，你说你的模型是两方训练的，具体是怎么训练、保存的可以看看吗？

另外可以在同一台机器，新起一个terminal，跑一下ray status看看。

**Comment by SZU-czw** [comment]
> 你好，你说你的模型是两方训练的，具体是怎么训练、保存的可以看看吗？
> 
> 另外可以在同一台机器，新起一个terminal，跑一下ray status看看。

模型权重保存代码如下
```
 model = SSRegression(spu)
    start = time.time()

    random_state = 1234
    split_factor = 0.8

    v_train_data, v_test_data = train_test_split(
       v_data_train, train_size=split_factor, random_state=random_state)

    v_train_label, v_test_label = train_test_split(
        label_data_train, train_size=split_factor, random_state=random_state)
    
    model.fit(
        v_data_train,          # x
        label_data_train,      # y
        int(epochs),           # epochs
        float(learning_rate),  # learning_rate
        int(batch_size),       # batch_size
        sig_type,              # sig_type
        reg_type,              # reg_type
        'l2',                  # penalty
        0.1,                   # l2_norm
    )

    print(f"lr train time: {time.time() - start}")

    # 逻辑回归方程系数
    lr_weights = reveal(model.save_model().weights)
    lr_weights_to_csv = pd.DataFrame(lr_weights)

    dirs = "/home/secretflow/result"
    if not os.path.exists(dirs):   # 如果不存在result路径，则创建这个路径
        os.makedirs(dirs)
    lr_weights_to_csv.to_csv(dirs+"/model_lr.csv",index=None)
```
将模型权重参数保存成为了csv文件

**Comment by da-niao-dan** [comment]
你好，现在官方还没有支持SSRegression的模型权重的保存，但是reveal了保存起来后面复用应该也是可行的。

我观察到
```
test_x = FedNdarray(
    partitions={alice: alice(load_data_alice_feature)(test_file)},
    partition_way=PartitionWay.VERTICAL,
)
```
测试的时候好像没用bob的数据，这个是否有遗漏？

另外ray status 可以看一下节点资源有哪些？

ray status的样例输出如下
```
Node status
---------------------------------------------------------------
Healthy:
 1 node_ab1434ed8d6e25722ff04c588e9a89970fcbd862dbdf7e2543330024
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 2.0/64.0 CPU
 1.0/64.0 alice
 1.0/64.0 bob
 0.00/71.735 GiB memory
 0.00/34.735 GiB object_store_memory

```

**Comment by SZU-czw** [comment]
好的，谢谢大佬

**Comment by SZU-czw** [comment]
各位好，目前使用隐语遇到如下问题,请教一下
情形1：在数据集相同的情况下。读取训练集和测试集。alice,bob 使用mpc进行联合逻辑回归训练和预测，将预测结果reveal出来和本地不使用隐语的逻辑回归进行预测值比较，两者结果相同。这正是正确的结果

情形2,:  载数据集相同的情况下。现在两方使用隐语逻辑回归采用两个阶段 
第一阶段保存模型权重，LRmodel.save_model().weights,保存权重为一个csv文件并reveal出来，
第二阶段 加载模型权重 ，重新生成模型
   modelWeigth=LinearModel(spu_weight, reg_type,sig_type)
    lrmodel=SSRegression(spu)
    lrmodel.load_model(modelWeigth)
    然后再进行预测lrmodel.predict(x=v_data_test, batch_size=batch_size,to_pyu=alice)
    目前是采用两阶段进行的模型保存，模型加载，模型预测思路下，最后的预测结果和本地不使用隐语的逻辑回归进行预测值比较不相同，产生了差异。这不是想要的结果。
    请问，保存模型权重后，然后再读进来需要进行权重参数行列的转换吗？ 可能是什么原因造成这样预测结果有差异。 
    请帮忙解答一下

**Comment by da-niao-dan** [comment]
你好，可以提供可以复现的源码吗？ 可以用随机数据
