### ISSUE TITLE
横向XGB的API——SFXgboost中，没有预测接口，那么如何预测？

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#693]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

secretflow 0.8.2b1

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
在查看水平联邦XGBoost案例的时候（案例链接如下），发现只有训练过程，并没有预测过程；
https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federated_Xgboost
于是看了SFXgboost接口，只有train\save_mode\dump_model\eval，其中eval接口也是对训练过程进行评估，并没有看到模型预测的过程；
不知道是我没有了解清楚还是说本身没有做这个接口？
```

### Reproduction code to reproduce the issue.

```shell
同上所述，如何在完成训练之后，来了新的数据之后对其预测呢？
```

**Comment by zhangxingmeng** [comment]
Hi
是这样的，我们提供的水平联邦xgb各方产出的模型是相同的，而且这个模型我们是兼容原生xgboost的，你可以直接通过原生xgboost的预测来进行预测就可以。
祝好

**Comment by zhangxingmeng** [comment]
水平各方保存的模型是一致的
这个问题，xgboost有类似的issue，我也会跟进处理这个问题
感谢反馈

**Comment by Niclouge** [comment]
> 水平各方保存的模型是一致的 这个问题，xgboost有类似的[issue](https://github.com/dmlc/xgboost/issues/40)， 我也会跟进处理这个问题 感谢反馈

感谢反馈！
还有最后一个问题，在reveal这一块，
在纵向联邦学习当中，可以清楚知道特征和标签属于哪一方，因此可以对数据很简单的reveal，
那么在横向当中，如果通过secretflow.data.split.train_test_split对整个数据集分割之后，如何对分割的数据进行reveal呢？

**Comment by zhangxingmeng** [comment]
想知道您这边reveal的需求是什么呢？

**Comment by Niclouge** [comment]
> 想知道您这边reveal的需求是什么呢？

在做横向联邦的时候，想得到指标，如AUC，ACC等

**Comment by zhangxingmeng** [comment]
你可以使用自己单方的数据来计算auc或者acc
也可以准备一份第三方数据来计算auc和acc
不建议reveal别人的数据来计算（这个功能在产品中是会被禁掉的，仅限debug）

**Comment by Niclouge** [comment]
了解了
