### ISSUE TITLE
利用SPU进行逻辑回归算法抛出异常ray::_spu_compile()             

### ISSUE THREAD

**Issue by BJTUpupil** [secretflow/secretflow#694]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.3b0

### OS Platform and Distribution

Ubuntu 18.04.1 LTS

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
参考代码：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/lr_with_spu
进行学习，在运行到最后一步时使用sf.reveal(W_)函数报错，报错显示RayTaskError
---------------------------------------------------------------------------
RayTaskError                              Traceback (most recent call last)
Cell In[13], line 1
----> 1 auc = validate_model(sf.reveal(W_), sf.reveal(b_), X_test, y_test)
      2 print(f'auc={auc}')

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py:155, in reveal(func_or_object, heu_encoder)
    152         logging.debug(f'Getting teeu data from TEEU {x.device.party}.')
    154 cur_idx = 0
--> 155 all_object = sfd.get(all_object_refs)
    157 new_flatten_val = []
    158 for x in flatten_val:

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:75, in get(object_refs)
     73     return fed.get(object_refs)
     74 else:
---> 75     return ray.get(object_refs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook..wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError: ray::SPURuntime.run() (pid=2862, ip=10.102.2.5, repr=SPURuntime(device_id=None, party=alice))
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_spu_compile() (pid=2558, ip=10.102.2.5)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1377, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 148, in compile
    ir_text, output = _jax_compilation(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 75, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/api.py", line 555, in computation_maker
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/interpreters/mlir.py", line 646, in lower_jaxpr_to_module
    raise ValueError(f"Unknown platform {platform}")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Unknown platform interpreter

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::_spu_compile() (pid=2558, ip=10.102.2.5)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1377, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 148, in compile
    ir_text, output = _jax_compilation(
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 75, in _jax_compilation
    cfn, output = jax.xla_computation(
ValueError: Unknown platform interpreter

During handling of the above exception, another exception occurred:

ray::_spu_compile() (pid=2558, ip=10.102.2.5)
  File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1389, in _spu_compile
    raise ray.exceptions.WorkerCrashedError()
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```

### Reproduction code to reproduce the issue.

```shell
代码与https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/lr_with_spu教程提供代码一致
```

**Comment by anakinxc** [comment]
> ### Issue Type
> Bug
> 
> ### Source
> binary
> 
> ### Secretflow Version
> 0.8.3b0
> 
> ### OS Platform and Distribution
> Ubuntu 18.04.1 LTS
> 
> ### Python version
> 3.8.17
> 
> ### Bazel version
> _No response_
> 
> ### GCC/Compiler version
> _No response_
> 
> ### What happend and What you expected to happen.
> ```shell
> 参考代码：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/lr_with_spu
> 进行学习，在运行到最后一步时使用sf.reveal(W_)函数报错，报错显示RayTaskError
> ---------------------------------------------------------------------------
> RayTaskError                              Traceback (most recent call last)
> Cell In[13], line 1
> ----> 1 auc = validate_model(sf.reveal(W_), sf.reveal(b_), X_test, y_test)
>       2 print(f'auc={auc}')
> 
> File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py:155, in reveal(func_or_object, heu_encoder)
>     152         logging.debug(f'Getting teeu data from TEEU {x.device.party}.')
>     154 cur_idx = 0
> --> 155 all_object = sfd.get(all_object_refs)
>     157 new_flatten_val = []
>     158 for x in flatten_val:
> 
> File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:75, in get(object_refs)
>      73     return fed.get(object_refs)
>      74 else:
> ---> 75     return ray.get(object_refs)
> 
> File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook..wrapper(*args, **kwargs)
>     103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
>     104         return getattr(ray, func.__name__)(*args, **kwargs)
> --> 105 return func(*args, **kwargs)
> 
> File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
>    2307     worker.core_worker.dump_object_store_memory_usage()
>    2308 if isinstance(value, RayTaskError):
> -> 2309     raise value.as_instanceof_cause()
>    2310 else:
>    2311     raise value
> 
> RayTaskError: ray::SPURuntime.run() (pid=2862, ip=10.102.2.5, repr=SPURuntime(device_id=None, party=alice))
>   At least one of the input arguments for this task could not be computed:
> ray.exceptions.RayTaskError: ray::_spu_compile() (pid=2558, ip=10.102.2.5)
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1377, in _spu_compile
>     executable, output_tree = spu_fe.compile(
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 148, in compile
>     ir_text, output = _jax_compilation(
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
>     v = func(*args, **kwargs)
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 75, in _jax_compilation
>     cfn, output = jax.xla_computation(
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
>     return fun(*args, **kwargs)
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/api.py", line 555, in computation_maker
>     lowering_result = mlir.lower_jaxpr_to_module(
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/interpreters/mlir.py", line 646, in lower_jaxpr_to_module
>     raise ValueError(f"Unknown platform {platform}")
> jax._src.traceback_util.UnfilteredStackTrace: ValueError: Unknown platform interpreter
> 
> The stack trace below excludes JAX-internal frames.
> The preceding is the original exception that occurred, unmodified.
> 
> --------------------
> 
> The above exception was the direct cause of the following exception:
> 
> ray::_spu_compile() (pid=2558, ip=10.102.2.5)
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1377, in _spu_compile
>     executable, output_tree = spu_fe.compile(
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 148, in compile
>     ir_text, output = _jax_compilation(
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
>     v = func(*args, **kwargs)
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 75, in _jax_compilation
>     cfn, output = jax.xla_computation(
> ValueError: Unknown platform interpreter
> 
> During handling of the above exception, another exception occurred:
> 
> ray::_spu_compile() (pid=2558, ip=10.102.2.5)
>   File "/home/Kervin/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1389, in _spu_compile
>     raise ray.exceptions.WorkerCrashedError()
> ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
> ```
> 
> ### Reproduction code to reproduce the issue.
> ```shell
> 代码与https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/lr_with_spu教程提供代码一致
> ```

这是个 jax 兼容性问题，我们会在下一个版本修复，目前可以这么修复

```sh
pip uninstall jax jaxlib
pip install jax==0.4.12 jaxlib==0.4.12
```

**Comment by BJTUpupil** [comment]
非常感谢！已解决~
