### ISSUE TITLE
有社区支持钉钉群和中文文档么

### ISSUE THREAD

**Issue by jfly0902** [secretflow/secretflow#7]

**Comment by pchyuan** [comment]
目前还没有钉钉群，有问题可以直接提issue，我们会有专门同学来及时跟进；中文文档在制作中，

**Comment by deadlywing** [comment]
> 

借楼问一下，现在是不是只支持x86的linux？有没有具体的操作系统要求或者dependence？

**Comment by zhouaihui** [comment]
https://secretflow.readthedocs.io/en/latest/getting_started/install.html#environment

OS的要求看这里。
macOS的支持在路上了，windows暂无计划。

**Comment by jfly0902** [comment]
> 

大佬们，社区群搞起来啊，隔壁的fate社区支持不够。我都准备弃用了

**Comment by zhouaihui** [comment]
macOS（>= 10.16） intel芯片已支持，m1芯片在路上了

**Comment by deadlywing** [comment]
速度很快，点赞;
BTW，readme中可以把python版本>=3.8改成==3.8；昨天在虚拟机里安装了3.9的python，发现pip install不了，我一开始还以为是裸机有什么dependence没装，，后来看了一下pypi发现只有3.8版本的包，，可能会造成大家的困扰。

**Comment by zhouaihui** [comment]
感谢指正，我们修正一下readme。目前确实暂时只支持3.8

**Comment by halosecret00** [comment]
有微信群SecretFlow01

**Comment by 6fj** [comment]
> 服务器最少8核16g吗？ 我找了一个2g服务器装不上，报内存错误，是不是这个原因。

Hi @xpdgit ,

隐语推荐的最低配置是8c16g。如果你暂时无法满足这个配置，建议可以使用阿里云完成部署。

感谢。

**Comment by xpdgit** [comment]
好的多谢
