### ISSUE TITLE
将 SecretFlow《在SecretFlow中使用自定义DataBuilder（Torch）》中文文档逐句翻译成英文文档

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#701]
> **加码任务来啦～**此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍

- 任务名称：将 SecretFlow《[在SecretFlow中使用自定义DataBuilder（Torch）](https://www.secretflow.org.cn/docs/secretflow/latest/en-US/tutorial/CustomDataLoaderTorch)》中文文档逐句翻译成英文文档
- 技术方向：SF/docs
- 任务难度：基础

## 详细要求

将 SecretFlow《[在SecretFlow中使用自定义DataBuilder（Torch）](https://www.secretflow.org.cn/docs/secretflow/latest/en-US/tutorial/CustomDataLoaderTorch)》中文文档逐句翻译成英文文档，以完善英文文档内容

- 操作指引：[文档翻译贡献流程（中译英）](https://www.yuque.com/secret-flow/admin/kgglql2fqgorhr4p) 中有 step by step 的操作介绍，可按照文档方式进行实现
- 文档对应 ipynb 文件：https://github.com/secretflow/secretflow/blob/main/docs/tutorial/CustomDataLoaderTorch.ipynb
- 文档范例：《[水平联邦：图像分类](https://www.secretflow.org.cn/docs/secretflow/latest/en-US/tutorial/Federate_Learning_for_Image_Classification)》文档对应的 [英文文档源文件链接](https://github.com/secretflow/secretflow/blob/main/docs/tutorial/Federate_Learning_for_Image_Classification.ipynb) 以及 [中文文档源文件链接](https://github.com/secretflow/secretflow/blob/main/docs/locales/zh_CN/LC_MESSAGES/tutorial/Federate_Learning_for_Image_Classification.po)
- 提交要求：请在完成整篇文章翻译后，再提交 PR；并将翻译后的中英文文档全文截图在提交的 PR 下同步

## 能力要求
- 了解基本 git 操作
 - 外语水平良好

**Comment by Zhang-gong** [comment]
Zhang-gong give it to me.
