### ISSUE TITLE
运行官方文档Move JAX program to SPU出错

### ISSUE THREAD

**Issue by fairyto2** [secretflow/secretflow#71]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

macos 12.4

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
https://spu.readthedocs.io/en/beta/getting_started/quick_start.html
运行Move JAX program to SPU时报错ModuleNotFoundError: No module named '__mp_main__'
```

### Reproduction code to reproduce the issue.

```shell
# run make_rand on P1, the value is visible for P1 only.
x = ppd.device("P1")(make_rand)()

# run make_rand on P2, the value is visible for P2 only.
y = ppd.device("P2")(make_rand)()

# run greater on SPU, it automatically fetches x/y from P1/P2 (as ciphertext), and compute the result securely.
ans = ppd.device("SPU")(greater)(x, y)


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [22], in <cell line: 2>()
      1 # run make_rand on P1, the value is visible for P1 only.
----> 2 x_ = ppd.device("P1")(make_rand)()
      4 # run make_rand on P2, the value is visible for P2 only.
      5 y_ = ppd.device("P2")(make_rand)()

File ~/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/util/distributed.py:373, in PYU.Function.__call__(self, *args, **kwargs)
    367     return pyfunc(*args, **kwargs)
    369 args, kwargs = tree_map(prep_objref, (args, kwargs))
    371 return tree_map(
    372     partial(PYU.Object, self.device),
--> 373     self.device.node_client.run(server_fn, *args, **kwargs),
    374 )

File ~/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/util/distributed.py:152, in NodeClient.run(self, fn, *args, **kwargs)
    150 """Run a function on the corresponding node server"""
    151 self._check_args(*args, **kwargs)
--> 152 return self._call(self._stub.Run, fn, *args, **kwargs)

File ~/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/util/distributed.py:143, in NodeClient._call(self, stub_method, fn, *args, **kwargs)
    139 rsp_gen = stub_method(
    140     RunRequest(data=split) for split in split_message(payload)
    141 )
    142 rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
--> 143 result = pickle.loads(rsp_data)
    144 if isinstance(result, Exception):
    145     raise Exception("remote exception", result)

ModuleNotFoundError: No module named '__mp_main__'
```

**Comment by 6fj** [comment]
Hi @fairyto2,

可否贴一下完整的代码？

**Comment by fairyto2** [comment]
使用示例中的代码
`import spu.binding.util.distributed as ppd
ppd.init(ppd.SAMPLE_NODES_DEF,ppd.SAMPLE_DEVICES_DEF)

import numpy as np
import jax.numpy as jnp

def make_rand():
    np.random.seed()
    return np.random.randint(100, size=(10, 1))

def greater(x, y):
    return jnp.greater(x, y)

x = make_rand()
y = make_rand()
ans = greater(x, y)

# run make_rand on P1, the value is visible for P1 only.
x_ = ppd.device("P1")(make_rand)()

# run make_rand on P2, the value is visible for P2 only.
y_ = ppd.device("P2")(make_rand)()

# run greater on SPU, it automatically fetches x/y from P1/P2 (as ciphertext), and compute the result securely.
ans_ = ppd.device("SPU")(greater)(x_, y_)
`

**Comment by 6fj** [comment]
Hi @fairyto2 ,

能否试着在一个干净的python3.8环境安装secretflow来执行程序，目前看上去是python的问题。我推荐使用anaconda。
感谢。

**Comment by fairyto2** [comment]
@6fj 是昨天安装的一个新环境，安装包如下
`
(secretflow) [~] python --version                                     11:12:21
Python 3.8.13
(secretflow) [~] pip list                                             11:12:31
Package                      Version
---------------------------- -----------
absl-py                      1.0.0
aiobotocore                  2.1.2
aiohttp                      3.8.1
aioitertools                 0.10.0
aiosignal                    1.2.0
appnope                      0.1.3
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
asttokens                    2.0.5
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        21.4.0
backcall                     0.2.0
beautifulsoup4               4.11.1
bleach                       5.0.1
botocore                     1.23.24
cachetools                   5.2.0
certifi                      2022.6.15
cffi                         1.15.1
charset-normalizer           2.1.0
click                        8.0.4
cloudpickle                  2.0.0
coverage                     6.4.2
cycler                       0.11.0
debugpy                      1.6.2
decorator                    5.1.1
defusedxml                   0.7.1
distlib                      0.3.5
elastic-transport            8.1.2
elasticsearch                6.8.0
entrypoints                  0.4
executing                    0.9.1
fastjsonschema               2.16.1
filelock                     3.7.1
flatbuffers                  2.0
fonttools                    4.34.4
frozenlist                   1.3.0
fsspec                       2022.1.0
gast                         0.4.0
google-auth                  2.9.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.47.0
h5py                         3.7.0
idna                         3.3
importlib-metadata           4.12.0
importlib-resources          5.9.0
ipykernel                    6.15.1
ipython                      8.4.0
ipython-genutils             0.2.0
ipywidgets                   7.7.1
jax                          0.3.7
jaxlib                       0.3.7
jedi                         0.18.1
Jinja2                       3.1.2
jmespath                     0.10.0
joblib                       1.1.0
jsonschema                   4.7.2
jupyter                      1.0.0
jupyter-client               7.3.4
jupyter-console              6.4.4
jupyter-core                 4.11.1
jupyterlab-pygments          0.2.2
jupyterlab-widgets           1.1.1
keras                        2.7.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
libclang                     14.0.1
loguru                       0.6.0
lxml                         4.9.1
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.5.2
matplotlib-inline            0.1.3
mistune                      0.8.4
msgpack                      1.0.4
multidict                    6.0.2
nbclient                     0.6.6
nbconvert                    6.5.0
nbformat                     5.4.0
nest-asyncio                 1.5.5
notebook                     6.4.12
numpy                        1.22.3
oauthlib                     3.2.0
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.4.0
pandocfilters                1.5.0
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.2.0
pip                          22.1.2
platformdirs                 2.5.2
prometheus-client            0.14.1
prompt-toolkit               3.0.30
protobuf                     3.19.4
psutil                       5.9.1
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycparser                    2.21
Pygments                     2.12.0
pyparsing                    3.0.9
pyrsistent                   0.18.1
python-dateutil              2.8.2
pytz                         2022.1
PyYAML                       6.0
pyzmq                        23.2.0
qtconsole                    5.3.1
QtPy                         2.1.0
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
s3fs                         2022.1.0
scikit-learn                 1.0.2
scipy                        1.8.1
secretflow                   0.6.13b1
secretflow-ray               2.0.0.dev0
Send2Trash                   1.8.0
setuptools                   61.2.0
sf_heu                       0.1.0b1
six                          1.16.0
soupsieve                    2.3.2.post1
spu                          0.1.0b1
stack-data                   0.3.0
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.1
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
terminado                    0.15.0
threadpoolctl                3.1.0
tinycss2                     1.1.1
torch                        1.10.1
torchvision                  0.11.2
tornado                      6.2
tqdm                         4.62.3
traitlets                    5.3.0
typing_extensions            4.3.0
unittest-xml-reporting       3.2.0
urllib3                      1.26.10
validator.py                 1.3.0
virtualenv                   20.15.1
wcwidth                      0.2.5
webencodings                 0.5.1
Werkzeug                     2.2.0
wheel                        0.37.1
widgetsnbextension           3.6.1
wrapt                        1.14.1
xgboost                      1.5.2
yarl                         1.7.2
zipp                         3.8.1
`

**Comment by 6fj** [comment]
Hi @fairyto2 ,

I have confirmed this issue and would update here later. 

However, you could continue to check other examples or evaluate with official docker image.

**Comment by 6fj** [comment]
Hi @fairyto2，

看起来是因为multiprocessing这个库在mac上面的问题，请参考https://stackoverflow.com/questions/72766345/attributeerror-cant-pickle-local-object-in-multiprocessing。

我们将会switch到[multiprocess](https://pypi.org/project/multiprocess/)以解决这个问题。

同时，我们非常感谢你发现的这一issue。Have a nice day~
