### ISSUE TITLE
请问官方有推理的例子吗？

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#72]
请问官方有推理的例子吗？

**Comment by zhouaihui** [comment]
目前有离线推理的示例，比如[Federate_Learning_for_Image_Classification](https://secretflow.readthedocs.io/en/latest/tutorial/Federate_Learning_for_Image_Classification.html#Federate-learning-on-SecretFlow)，[Split_Learning_for_bank_marketing](https://secretflow.readthedocs.io/en/latest/tutorial/Split_Learning_for_bank_marketing.html#Create-Split-Learning-Model)中有提供`model.evulate`的使用示例。

在线推理目前还没有。
