### ISSUE TITLE
怎么用secretflow实现多机集群pir

### ISSUE THREAD

**Issue by hlysf** [secretflow/secretflow#720]
我想使用docker部署secretflow，生产模式下实现pir，但是我不知道如何通过代码实现，以下是我的一些尝试。
以alice为client，bob为server。
alice.py代码如下：
```
import os
import sys
import time
import logging
import multiprocess
from absl import app

import spu
import secretflow as sf

sf.shutdown()
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)


alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_config ={
    'parties': {
        'alice': {
            'address': '10.229.208.37:3545',
            'listen_addr': '0.0.0.0:3545'
        },
        'bob': {
            'address': '10.229.208.36:3544',
            'listen_addr': '0.0.0.0:3544'
        },
    },
    'self_party': 'alice'
}

cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'address': f'10.229.208.37:3457',
        },
        {
            'party': 'bob',
            'address':  f'10.229.208.36:3458',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    }
}

link_desc = {
    'recv_timeout_ms': 3600000,
}


logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

sf.init(address='10.229.208.37:3456', cluster_config=cluster_config)

key_columns = ['id']
label_columns = ['register_date','age']
spu = sf.SPU(cluster_def, link_desc)

pir_input_path = '/root/B_PIR_DATA.csv'
pir_oprf_key_path = '/root/oprf_key.bin'
pir_setup_path = '/root/setup_path'

alice_input_path = '/root/A_PIR_ID.csv'  

alice_config = {
    'input_path': alice_input_path,
    'key_columns': key_columns,
    'output_path': '/root/sf_pir_out.csv',
}

bob_config = {
    'oprf_key_path': pir_oprf_key_path,
    'setup_path': pir_setup_path,
}

query_config = {
    alice: alice_config,
    bob: bob_config,
}

start = time.time()

reports = spu.pir_query(
    server='bob',
    config=query_config,
    protocol='KEYWORD_PIR_LABELED_PSI'
)

logging.info(f"online pir reports: {reports}")
logging.info(f"pir query cost time: {time.time() - start}")

sf.shutdown()
```

bob.py：
```import time
import logging
import multiprocess

import spu
import secretflow as sf

sf.shutdown()

alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_config ={
    'parties': {
        'alice': {
            'address': '10.229.208.37:3545',
            'listen_addr': '0.0.0.0:3545'
        },
        'bob': {
            'address': '10.229.208.36:3544',
            'listen_addr': '0.0.0.0:3544'
        },
    },
    'self_party': 'bob'
}


cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'address': f'10.229.208.37:3457',
        },
        {
            'party': 'bob',
            'address':  f'10.229.208.36:3458',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}


link_desc = {
    'recv_timeout_ms': 3600000,
}

sf.init(address='10.229.208.36:3556', cluster_config=cluster_config)

key_columns = ['id']
label_columns = ['register_date','age']
spu = sf.SPU(cluster_def=cluster_def)

pir_input_path = '/root/B_PIR_DATA.csv'
pir_oprf_key_path = '/root/oprf_key.bin'
pir_setup_path = '/root/setup_path'


start = time.time()

reports = spu.pir_setup(
    server='bob',
    input_path=pir_input_path,
    key_columns=key_columns,
    label_columns=label_columns,
    oprf_key_path=pir_oprf_key_path,
    setup_path=pir_setup_path,
    num_per_query=1,
    label_max_len=18,
)

logging.info(f"offline pir reports: {reports}")
logging.info(f"setup cost time: {time.time() - start}")
```

脚本运行后，bob.py退出
![image](https://github.com/secretflow/secretflow/assets/66900073/94092cb2-c444-4e3b-b010-16df02f17795)

alice.py停在这里：
![image](https://github.com/secretflow/secretflow/assets/66900073/7b394b98-5df2-48f5-8063-37752d3e8d86)
请问我应该如何修改？

**Comment by zhanglei486** [comment]
第一步，offline 数据预处理
按上面bob 端的脚本，执行offline阶段的数据预处理，调用的是pir_setup，单方任务，提前执行
第二部，online 查询阶段
alice和bob都执行上面alice端的脚本，执行query函数，双方交互完成查询

**Comment by hlysf** [comment]
> 第一步，offline 数据预处理 按上面bob 端的脚本，执行offline阶段的数据预处理，调用的是pir_setup，单方任务，提前执行 第二部，online 查询阶段 alice和bob都执行上面alice端的脚本，执行query函数，双方交互完成查询

如果直接执行bob端脚本，会报错连接不上alice端，因为sf.init使用的cluster_config中有alice，需要都去掉只留下bob的吗？

**Comment by zhanglei486** [comment]
> > 第一步，offline 数据预处理 按上面bob 端的脚本，执行offline阶段的数据预处理，调用的是pir_setup，单方任务，提前执行 第二部，online 查询阶段 alice和bob都执行上面alice端的脚本，执行query函数，双方交互完成查询
> 
> 如果直接执行bob端脚本，会报错连接不上alice端，因为sf.init使用的cluster_config中有alice，需要都去掉只留下bob的吗？

@zhouaihui zhou 看一下，只留bob是不是可以执行单方集群的任务
sf.init(address='10.229.208.36:3556', cluster_config=cluster_config)

**Comment by zhouaihui** [comment]
可以在`sf.init`设置参数 `enable_waiting_for_other_parties_ready=False`，这样不会去等待其他方启动。
具体参考API说明 https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow#secretflow.init

**Comment by hlysf** [comment]
> 可以在`sf.init`设置参数 `enable_waiting_for_other_parties_ready=False`，这样不会去等待其他方启动。 具体参考API说明 https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow#secretflow.init

此时我将bob端脚本只做了上述init参数的修改，运行时报错：
![image](https://github.com/secretflow/secretflow/assets/66900073/24ea8ca9-08ce-47ff-a3b1-89e03232e20f)
![image](https://github.com/secretflow/secretflow/assets/66900073/2b6e0f6c-12bd-49f2-82e5-ee9d0ee9111e)

**Comment by hlysf** [comment]
> > 第一步，offline 数据预处理 按上面bob 端的脚本，执行offline阶段的数据预处理，调用的是pir_setup，单方任务，提前执行 第二部，online 查询阶段 alice和bob都执行上面alice端的脚本，执行query函数，双方交互完成查询
> 
> 因为你使用了SPU，SPU还是需要互相连接的。 建议按照前面的建议，在bob的脚本上加上online查询。

数据预处理，调用的pir_setup是需要使用spu的，所以setup和query不能分开吗？每次新的client查询都要server端重新运行setup和query？

**Comment by hlysf** [comment]
> > 第一步，offline 数据预处理 按上面bob 端的脚本，执行offline阶段的数据预处理，调用的是pir_setup，单方任务，提前执行 第二部，online 查询阶段 alice和bob都执行上面alice端的脚本，执行query函数，双方交互完成查询
> 
> 因为你使用了SPU，SPU还是需要互相连接的。 建议按照前面的建议，在bob的脚本上加上online查询。

alice脚本不变，我现在把bob端的setup和query放在了一个脚本中，如下：
```
import os
import sys
import time
import logging
import multiprocess
from absl import app

import spu
import secretflow as sf

sf.shutdown()
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)


alice, bob = sf.PYU('alice'), sf.PYU('bob')

cluster_config ={
    'parties': {
        'alice': {
            'address': '10.229.208.37:3545',
            'listen_addr': '0.0.0.0:3545'
        },
        'bob': {
            'address': '10.229.208.36:3544',
            'listen_addr': '0.0.0.0:3544'
        },
    },
    'self_party': 'bob'
}

cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'address': f'10.229.208.37:3457',
        },
        {
            'party': 'bob',
            'address':  f'10.229.208.36:3458',
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    }
}

link_desc = {
    'recv_timeout_ms': 3600000,
}


# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

sf.init(address='10.229.208.36:3556', cluster_config=cluster_config, enable_waiting_for_other_parties_ready=False)


key_columns = ['id']
label_columns = ['register_date','age']
spu = sf.SPU(cluster_def=cluster_def)

# server dataset
pir_input_path = '/root/B_PIR_DATA.csv'
pir_oprf_key_path = '/root/oprf_key.bin'
pir_setup_path = '/root/setup_path'


start = time.time()

# server setup
reports = spu.pir_setup(
    server='bob',
    input_path=pir_input_path,
    key_columns=key_columns,
    label_columns=label_columns,
    oprf_key_path=pir_oprf_key_path,
    setup_path=pir_setup_path,
    num_per_query=1,
    label_max_len=18,
)

#print(f"psi reports: {reports}")
logging.info(f"offline pir reports: {reports}")
logging.info(f"setup cost time: {time.time() - start}")


# client data query
alice_input_path = '/root/A_PIR_ID.csv'  

# client config
alice_config = {
    'input_path': alice_input_path,
    'key_columns': key_columns,
    'output_path': '/root/sf_pir_out.csv',
}

# server config
bob_config = {
    'oprf_key_path': pir_oprf_key_path,
    'setup_path': pir_setup_path,
}

query_config = {
    alice: alice_config,
    bob: bob_config,
}

start = time.time()

reports = spu.pir_query(
    server='bob',
    config=query_config,
    protocol='KEYWORD_PIR_LABELED_PSI'
)

logging.info(f"online pir reports: {reports}")
logging.info(f"pir query cost time: {time.time() - start}")

sf.shutdown()
```
同时运行两方脚本，但是停在了这里不会退出，已经有了查询结果。运行完该如何退出？
![image](https://github.com/secretflow/secretflow/assets/66900073/0d86412c-c61e-4812-a130-53709998c957)

**Comment by zhanglei486** [comment]
bob可以参照下面的代码，执行单方任务，做offline数据预处理，offline完成后双方再执行online query
https://github.com/secretflow/spu/blob/main/examples/python/pir/pir_setup.py

**Comment by hlysf** [comment]
> bob可以参照下面的代码，执行单方任务，做offline数据预处理，offline完成后双方再执行online query https://github.com/secretflow/spu/blob/main/examples/python/pir/pir_setup.py

好的，谢谢。我将setup过程单独写了一个脚本，成功进行了预处理。
还有2个问题：
1、具体的查询仍然使用前面的alice脚本，两方同时执行？
2、server端的数据是否只需要一次数据预处理，后期只需要两方执行查询脚本交互？

**Comment by zhanglei486** [comment]
> > bob可以参照下面的代码，执行单方任务，做offline数据预处理，offline完成后双方再执行online query https://github.com/secretflow/spu/blob/main/examples/python/pir/pir_setup.py
> 
> 好的，谢谢。我将setup过程单独写了一个脚本，成功进行了预处理。 还有2个问题： 1、具体的查询仍然使用前面的alice脚本，两方同时执行？ 2、server端的数据是否只需要一次数据预处理，后期只需要两方执行查询脚本交互？

回答：
1. 是的，两方执行上面有pir_query的脚本
2. 是的预处理一次，可以双方可以多次指定query，但需要注意的是server预处理需要一个32B的oprf_key，实际使用时建议定期更新oprf_key并重新执行预处理

**Comment by hlysf** [comment]
> > > bob可以参照下面的代码，执行单方任务，做offline数据预处理，offline完成后双方再执行online query https://github.com/secretflow/spu/blob/main/examples/python/pir/pir_setup.py
> > 
> > 
> > 好的，谢谢。我将setup过程单独写了一个脚本，成功进行了预处理。 还有2个问题： 1、具体的查询仍然使用前面的alice脚本，两方同时执行？ 2、server端的数据是否只需要一次数据预处理，后期只需要两方执行查询脚本交互？
> 
> 回答：
> 
> 1. 是的，两方执行上面有pir_query的脚本
> 2. 是的预处理一次，可以双方可以多次执行query，但需要注意的是server预处理需要一个32B的oprf_key，实际使用时建议定期更新oprf_key并重新执行预处理

好的，非常感谢各位解答~
