### ISSUE TITLE
spu网络通讯有开启tls加密的选项吗

### ISSUE THREAD

**Issue by enidastronomical** [secretflow/secretflow#734]
您好，请问spu的网络通讯有没有开启tls加密的选项呀？如果有的话，请问能否提供一下使用方法或者文档呢？感谢～

**Comment by enidastronomical** [comment]
我在spu下找到了mem_psi.py里关于tls的字段

flags.DEFINE_bool("enable_tls", False, "whether to enable tls for link")
flags.DEFINE_string("link_server_certificate", "", "link server certificate file path")
flags.DEFINE_string("link_server_private_key", "", "link server private key file path")
flags.DEFINE_string(
    "link_server_ca", "", "ca file used to verify other's link server certificate"
)
flags.DEFINE_string("link_client_certificate", "", "link client certificate file path")
flags.DEFINE_string("link_client_certificate", "", "link client private key file path")
flags.DEFINE_string(
    "link_client_ca", "", "ca file used to verify other's link client certificate"
)
FLAGS = flags.FLAGS

请问如果我想要在simple_psi.py里使用tls的话，是不是只需要把在这部分加到simple_psi.py里面，修改"enable_tls"为true，并且指定"link_server_certificate""link_client_certificate"证书，"link_server_private_key""link_client_certificate"私钥文件的位置就可以了呢？
还需要对源码进行什么修改吗？
谢谢老师们

**Comment by Chrisdehe** [comment]
hi,@enidastronomical 
我们支持开启TLS加密，可以参考下API文档：
https://www.secretflow.org.cn/docs/secretflow/latest/en-US/source/secretflow#secretflow.SPU

**Comment by oeqqwq** [comment]
secretflow中spu的tls相关配置可参考这里https://www.secretflow.org.cn/docs/secretflow/latest/en-US/source/secretflow#secretflow.SPU.__init__

想在simple_psi.py中开启tls，只需要执行脚本时，将tls相关配置作为命令行执行参数指定好即可，不需要修改代码

**Comment by enidastronomical** [comment]
> 

您好，我不太清楚
（1）这里的“作为命令行执行参数指定”，是在simple_psi.py的哪个部分指定呢？可以麻烦老师指导一下嘛
（2）我尝试了直接在mem_psi.py中指定flags参数
flags.DEFINE_bool("enable_tls", True, "whether to enable tls for link")
flags.DEFINE_string("link_server_certificate", "server.crt", "link server certificate file path")
flags.DEFINE_string("link_server_private_key", "server.key", "link server private key file path")
flags.DEFINE_string(
"link_server_ca", "ca.crt", "ca file used to verify other's link server certificate"
)
flags.DEFINE_string("link_client_certificate", "client.crt", "link client certificate file path")
flags.DEFINE_string("link_client_private_key", "client.key", "link client private key file path")
flags.DEFINE_string(
"link_client_ca", "ca.crt", "ca file used to verify other's link client certificate"
)
FLAGS = flags.FLAGS
但是会报错说AttributeError: 'spu.binding._lib.link.Desc' object has no attribute 'server_ssl_opts'，想了解一下这是什么原因呢

**Comment by oeqqwq** [comment]
1、https://www.secretflow.org.cn/docs/secretflow/latest/en-US/source/secretflow#secretflow.SPU.__init__ 描述的是secretfow中的spu，它是sf中的SPUDevice抽象封装，如果你想在sf中使用psi，可以参考https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/PSI_On_SPU，并在创建SPU时指定TlsOptions。对于直接使用SPU Repo中的simple_psi.py，你可以直接使用python ./examples/python/psi/simple_psi.py --help 参看脚本支持的所有参数

2、建议直接使用最新版本的spu

3、spu之间使用brpc进行网络交互，默认使用baidu_std作为rpc的协议

**Comment by enidastronomical** [comment]
> 1、https://www.secretflow.org.cn/docs/secretflow/latest/en-US/source/secretflow#secretflow.SPU.__init__ 描述的是secretfow中的spu，它是sf中的SPUDevice抽象封装，如果你想在sf中使用psi，可以参考https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/PSI_On_SPU ， 并在创建SPU时指定TlsOptions。对于直接使用SPU Repo中的simple_psi.py，你可以直接使用python ./examples/python/psi/simple_psi.py --help 参看脚本支持的所有参数
> 
> 2、建议直接使用最新版本的spu
> 
> 3、spu之间使用brpc进行网络交互，默认使用baidu_std作为rpc的协议

老师您好，我看到simple_psi.py中暂时是不支持tls相关的参数的，所以我对simple_psi.py进行了改造，把mem_psi.py中tls相关的配置添加到了simple_psi.py中。执行时不会报错，但是抓包时抓不到tls相关的包。想请问您能否指点一下是哪里出了问题呢？
（下面是我们修改后的simple_psi.py & 生成证书的脚本）
===============================================
------simple_psi.py如下------
from absl import app, flags

import spu.psi as psi
import spu.libspu.link as link
import spu.libspu.logging as logging

flags.DEFINE_string("protocol", "ECDH_PSI_2PC", "psi protocol, see `spu/psi/psi.proto`")
flags.DEFINE_integer("rank", 0, "rank: 0/1/2...")
#flags.DEFINE_string("party_ips", "127.0.0.1:9307,127.0.0.1:9308", "party addresses")
flags.DEFINE_string("party_ips", "10.88.167.99:9306,10.83.206.224:9306", "party addresses")
flags.DEFINE_string("in_path", "data.csv", "data input path")
flags.DEFINE_string("field_names", "id", "csv file filed name")
flags.DEFINE_string("out_path", "simple_psi_out.csv", "data output path")
flags.DEFINE_integer("receiver_rank", -1, "main party for psi, will get result")
flags.DEFINE_bool("output_sort", True, "whether to sort result")
flags.DEFINE_bool("precheck_input", True, "whether to precheck input dataset")
flags.DEFINE_integer("bucket_size", 1048576, "hash bucket size")
flags.DEFINE_bool("ic_mode", False, "whether to run in interconnection mode")
flags.DEFINE_integer("broadcast_result", 0, "whether to broadcast the intersection results to both parties")

#tls config
flags.DEFINE_bool("enable_tls", True, "whether to enable tls for link")
flags.DEFINE_string("link_server_certificate", "server.crt", "link server certificate file path")
flags.DEFINE_string("link_server_private_key", "server.key", "link server private key file path")
flags.DEFINE_string(
    "link_server_ca", "ca.crt", "ca file used to verify other's link server certificate"
)
flags.DEFINE_string("link_client_certificate", "client.crt", "link client certificate file path")
flags.DEFINE_string("link_client_private_key", "client.key", "link client private key file path")
flags.DEFINE_string(
    "link_client_ca", "ca.crt", "ca file used to verify other's link client certificate"
)
FLAGS = flags.FLAGS

def setup_link(rank):
    lctx_desc = link.Desc()
    lctx_desc.id = f"root"

    lctx_desc.recv_timeout_ms = 2 * 60 * 1000
    lctx_desc.connect_retry_times = 180
    if FLAGS.ic_mode:
        lctx_desc.brpc_channel_protocol = "h2:grpc"

    ips = FLAGS.party_ips.split(",")
    for i, ip in enumerate(ips):
        lctx_desc.add_party(f"id_{i}", ip)
        print(f"id_{i} = {ip}")

    if FLAGS.enable_tls:
        # two-way authentication
        print(f"enable tls")
        lctx_desc.server_ssl_opts.cert.certificate_path = FLAGS.link_server_certificate
        lctx_desc.server_ssl_opts.cert.private_key_path = FLAGS.link_server_private_key
        lctx_desc.server_ssl_opts.verify.ca_file_path = FLAGS.link_server_ca
        lctx_desc.server_ssl_opts.verify.verify_depth = 1
        lctx_desc.client_ssl_opts.cert.certificate_path = FLAGS.link_client_certificate
        lctx_desc.client_ssl_opts.cert.private_key_path = FLAGS.link_client_private_key
        lctx_desc.client_ssl_opts.verify.ca_file_path = FLAGS.link_client_ca
        lctx_desc.client_ssl_opts.verify.verify_depth = 1

    return link.create_brpc(lctx_desc, rank)

def main(_):
    opts = logging.LogOptions()
    opts.system_log_path = "./tmp/spu.log"
    opts.enable_console_logger = True
    opts.log_level = logging.LogLevel.INFO
    logging.setup_logging(opts)

    selected_fields = FLAGS.field_names.split(",")

    config = psi.BucketPsiConfig(
        psi_type=psi.PsiType.Value(FLAGS.protocol),
        broadcast_result=True if FLAGS.broadcast_result > 0 else False,
        receiver_rank=1,
        input_params=psi.InputParams(
            path=FLAGS.in_path,
            select_fields=selected_fields,
            precheck=FLAGS.precheck_input,
        ),
        output_params=psi.OutputParams(
            path=FLAGS.out_path, need_sort=FLAGS.output_sort
        ),
        bucket_size=FLAGS.bucket_size,
        curve_type=psi.CurveType.CURVE_25519,
    )

    if FLAGS.protocol == "DP_PSI_2PC":
        config.dppsi_params.bob_sub_sampling = 0.9
        config.dppsi_params.epsilon = 3

    report = psi.bucket_psi(setup_link(FLAGS.rank), config, FLAGS.ic_mode)
    print(
        f"original_count: {report.original_count}, intersection_count: {report.intersection_count}"
    )

    #print(f"{FLAGS.broadcast_result}")

if __name__ == '__main__':
    app.run(main)


===============================================
-----生成证书的脚本如下（client.crt和server.crt共用同一个ca.crt证书）------
-----生成client证书脚本------
domain=localhost
openssl genrsa -out ca.key 2048
openssl req -new -x509 -days 36500 -key ca.key -out ca.crt<<EOF
cn
bj
bj
m
m
m
m@m.com
EOF

openssl genrsa -out client.pem 2048  && openssl rsa -in client.pem -out client.key

openssl req -new -key client.pem -out client.csr<<EOF
cn
bj
bj
m
m
${domain}
${domain}@m.com
EOF

openssl x509 -req -sha256 -extfile /etc/pki/tls/openssl.cnf -extensions v3_req -in client.csr -CA ca.crt -CAkey ca.key -CAcreateserial -days 36500 -out client.crt

openssl verify -CAfile ca.crt client.crt

-----生成server证书脚本------
domain=localhost

openssl genrsa -out server.pem 2048  && openssl rsa -in server.pem -out server.key

openssl req -new -key server.pem -out server.csr<<EOF
cn
bj
bj
m
m
${domain}
${domain}@m.com
EOF

openssl x509 -req -sha256 -extfile openssl.cnf -extensions v3_req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -days 36500 -out server.crt

openssl verify -CAfile ca.crt server.crt

==============================================
接收方的文件
-rw-r--r-- 1 root root   1330 Jul 24 06:58 ca.crt
-rw------- 1 root root   1679 Jul 24 06:58 ca.key
-rw-r--r-- 1 root root     41 Jul 24 08:35 ca.srl
-rw-r--r-- 1 root root   1285 Jul 24 06:58 client.crt
-rw-r--r-- 1 root root   1029 Jul 24 06:58 client.csr
-rw------- 1 root root   1675 Jul 24 06:58 client.key
-rw------- 1 root root   1675 Jul 24 06:58 client.pem
-rwxr-xr-x 1 root root    744 Jul 24 08:26 generate_crt_key_client.sh*
-rwxr-xr-x 1 root root    645 Jul 24 08:26 generate_crt_key_server.sh*
-rw-r--r-- 1 root root  10923 Jul 24 06:53 openssl.cnf
-rw-r--r-- 1 root root   1281 Jul 24 08:35 server.crt
-rw-r--r-- 1 root root   1029 Jul 24 08:35 server.csr
-rw------- 1 root root   1679 Jul 24 08:35 server.key
-rw------- 1 root root   1679 Jul 24 08:35 server.pem

发送方的文件
-rw-r--r-- 1 root root   1330 Jul 24 08:31 ca.crt
-rw-r--r-- 1 root root   1679 Jul 24 08:31 ca.key
-rw-r--r-- 1 root root     41 Jul 24 08:33 ca.srl
-rw-r--r-- 1 root root   1273 Jul 24 08:32 client.crt
-rw-r--r-- 1 root root   1021 Jul 24 08:32 client.csr
-rw------- 1 root root   1679 Jul 24 08:32 client.key
-rw------- 1 root root   1679 Jul 24 08:32 client.pem
-rwxr-xr-x 1 root root    640 Jul 24 08:30 generate_crt_key_client.sh*
-rw-r--r-- 1 root root  10923 Jul 24 08:27 openssl.cnf
-rw-r--r-- 1 root root   1273 Jul 24 08:33 server.crt
-rw-r--r-- 1 root root   1021 Jul 24 08:33 server.csr
-rw------- 1 root root   1675 Jul 24 08:33 server.key
-rw------- 1 root root   1675 Jul 24 08:33 server.pem
-rwxr-xr-x 1 root root    737 Jul 24 08:30 generate_crt_key_server.sh*
