### ISSUE TITLE
Docker 镜像下载失败

### ISSUE THREAD

**Issue by Hisaft** [secretflow/secretflow#738]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow 1.0.0b3

### OS Platform and Distribution

Linux Ubuntu 18.04.5 LTS

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
在试图使用docker创建网络容器的时候，按照隐语官网的配置方法，运行“docker run -it --network sfnet --ip 192.168.0.10 --name secretflow1 secretflow/secretflow-anolis8:latest bash“命令后会返回错误，无法找到镜像，以至于无法运行容器，想询问一下该如何解决。
```

### Reproduction code to reproduce the issue.

```shell
Unable to find image 'secretflow/secretflow-anolis8:latest' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/secretflow/secretflow-anolis8/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Asecretflow%2Fsecretflow-anolis8%3Apull&service=registry.docker.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```

**Comment by Chrisdehe** [comment]
hi,@Hisaft 
需要先执行下：
export version=secretflow 1.0.0b3
去选择镜像，之后再执行docker run哈

**Comment by Hisaft** [comment]
@Chrisdehe 好的，我试一下

**Comment by Chrisdehe** [comment]
@Hisaft 
抱歉我需要更改下
export version=secretflow 1.0.0b3
》 》
export version=1.0.0b3

**Comment by zhouaihui** [comment]
`secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:latest`
你的网络不太好，访问不了docker io。可以使用上面的镜像。

**Comment by Hisaft** [comment]
@Chrisdehe @zhouaihui 问题已解决，感谢。
