### ISSUE TITLE
在 SecretFlow 中实现新的通讯量化压缩算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#742]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：在Secretflow中实现新的通讯量化压缩算法
- 技术方向：联邦学习和人工智能
- 任务难度：热身🌟

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 参考现有的模型量化算法，在 SecretFlow 联邦学习中，实现对 embedding 和 gradient 的压缩；
  - 基于 Compressor 实现压缩代码，并对模型的拆分逻辑进行封装，提交代码到 secretflow/utils/compressor.py中
  - 需要同时提交 tutorial，example 代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，与明文结果对比，AUC 差值不应超过 0.05
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码至 https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation
  - 整理完整实现过程为文档，并提交到 https://github.com/secretflow/secretflow/tree/main/docs/tutorial

## 能力要求
- 熟悉拆分学习，熟悉量化模型压缩算法
- 熟悉 TensorFlow 或者 PyTorch

**Comment by ues1df** [comment]
ues1df give it to me

**Comment by ues1df** [comment]
尝试在隐语官网的“拆分学习：银行营销”demo中加入compressor
不加入compressor能跑通的，加入compressor后，代码报错.

Traceback (most recent call last):
  File "/home/yasuo/test_sl.py", line 130, in <module>
    history = sl_model.fit(train_data,
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/sl_model.py", line 351, in fit
    scatter_gradients = self.agglayer.backward(gradients)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/agglayer/agg_layer.py", line 408, in backward
    gradient = self.device_y(self.handle_sparse_gradients)(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper
    sfd.remote(self._run)
  File "/usr/local/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 108, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 98, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PYUSLTFModel.fuse_net() (pid=17968, ip=172.17.0.3, repr=<secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel object at 0x7f33e26cd280>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 472, in fuse_net
    assert h.hidden is not None, f"hidden cannot be found in forward_data[{i}]"
AttributeError: 'list' object has no attribute 'hidden'

我觉得原因可能是agg_layer的forward调用 self.handle_sparse_hiddens后，返回的是一个PYUObject，而非多个parties的PYUObject数组，导致后面的代码处理出错了。

**Comment by Candicepan** [comment]
> 尝试在隐语官网的“拆分学习：银行营销”demo中加入compressor 不加入compressor能跑通的，加入compressor后，代码报错.
> 
> Traceback (most recent call last): File "/home/yasuo/test_sl.py", line 130, in history = sl_model.fit(train_data, File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/sl_model.py", line 351, in fit scatter_gradients = self.agglayer.backward(gradients) File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/agglayer/agg_layer.py", line 408, in backward gradient = self.device_y(self.handle_sparse_gradients)( File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper sfd.remote(self._run) File "/usr/local/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote return func_cls._remote(args=args, kwargs=kwargs, **updated_options) File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 108, in _remote args, kwargs = _resolve_args(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 98, in _resolve_args actual_vals = ray.get(list(refs.values())) File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper return func(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get raise value.as_instanceof_cause() ray.exceptions.RayTaskError(AttributeError): ray::PYUSLTFModel.fuse_net() (pid=17968, ip=172.17.0.3, repr=<secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel object at 0x7f33e26cd280>) File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper return method(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 472, in fuse_net assert h.hidden is not None, f"hidden cannot be found in forward_data[{i}]" AttributeError: 'list' object has no attribute 'hidden'
> 
> 我觉得原因可能是agg_layer的forward调用 self.handle_sparse_hiddens后，返回的是一个PYUObject，而非多个parties的PYUObject数组，导致后面的代码处理出错了。

感谢你的反馈，相关问题在修复中啦，预计今日能够完成，修复后将在这里跟你同步，辛苦届时在拉一下最新的代码进行任务开发

**Comment by Candicepan** [comment]
> 尝试在隐语官网的“拆分学习：银行营销”demo中加入compressor 不加入compressor能跑通的，加入compressor后，代码报错.
> 
> Traceback (most recent call last): File "/home/yasuo/test_sl.py", line 130, in history = sl_model.fit(train_data, File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/sl_model.py", line 351, in fit scatter_gradients = self.agglayer.backward(gradients) File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/agglayer/agg_layer.py", line 408, in backward gradient = self.device_y(self.handle_sparse_gradients)( File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper sfd.remote(self._run) File "/usr/local/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote return func_cls._remote(args=args, kwargs=kwargs, **updated_options) File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 108, in _remote args, kwargs = _resolve_args(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 98, in _resolve_args actual_vals = ray.get(list(refs.values())) File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper return func(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get raise value.as_instanceof_cause() ray.exceptions.RayTaskError(AttributeError): ray::PYUSLTFModel.fuse_net() (pid=17968, ip=172.17.0.3, repr=<secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel object at 0x7f33e26cd280>) File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper return method(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 472, in fuse_net assert h.hidden is not None, f"hidden cannot be found in forward_data[{i}]" AttributeError: 'list' object has no attribute 'hidden'
> 
> 我觉得原因可能是agg_layer的forward调用 self.handle_sparse_hiddens后，返回的是一个PYUObject，而非多个parties的PYUObject数组，导致后面的代码处理出错了。

hello～已经完成修复哈～辛苦拉一下最新的代码进行任务开发哈
