### ISSUE TITLE
DeepFM 相关文档翻译任务

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#743]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：DeepFM 相关文档翻译任务
- 技术方向：联邦学习和人工智能
- 任务难度：热身🌟

## 详细要求

- 功能性：本任务需要对 [DeepFM 相关文档](https://github.com/secretflow/secretflow/blob/main/docs/tutorial/sl_rec_deepfm.ipynb)翻译到英文：
  - 翻译 DeepFM 拆分方案原理文档
  - 翻译教程 tutorial
- 具体操作说明可见[文档翻译贡献流程（中译英）](https://www.yuque.com/secret-flow/admin/kgglql2fqgorhr4p)
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点），翻译准确，需保证渲染出来的效果是正确的。
- 提交说明：
  - 关联该 issue 并提交代码至 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
  - 整理完整实现过程为文档，并提交到 https://github.com/secretflow/secretflow/tree/main/docs/tutorial

## 能力要求
- 英文能力良好
- 熟悉 DeepFM，熟悉拆分学习
- 熟悉 TensorFlow 或者 PyTorch

**Comment by DMJYY** [comment]
give it to me
