### ISSUE TITLE
在 SecretFlow 中实现水平联邦目标识别 example

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#746]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：在 SecretFlow 中实现水平联邦目标识别 example
- 技术方向：联邦学习和人工智能
- 任务难度：进阶🌟🌟

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 实现任意一种目标检测方法
  - 提供联邦数据集拆分的逻辑
  - 提交 tutorial，example 代码，数据下载，拆分和预处理代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，最好有与明文结果（PyTorch 或者 TensorFlow）的对比
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码 https://github.com/secretflow/secretflow/tree/main/examples/app/h_cv/object_detection
  - 整理完整实现过程为文档 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
 
## 能力要求
- 熟悉目标检测相关技术，包括但不限于 R-CNN，SSD，YOLO 等
- 熟悉 TensorFlow 或者 PyTorch

## 操作说明
- 操作指引：具体操作可参考[操作指引](https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation/deep_fm)进行
- 参考内容：
  - [数据读取](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)
  - [数据预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
  - [联邦模型开发教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)

## 认领说明
本任务可有多种实现方式，故支持有多位开发者进行认领，请在认领任务后，在本 issue 下 comment 你的具体设计思路。

设计思路需要包括以下内容：

1. 计划在什么样的数据集上实现哪一个模型
2. 计划如何进行数据拆分
3. 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
4. 计划选择哪一个联邦策略，是如何考虑的

> 当同一任务有多位开发者提交设计思路时：
> - 若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> - 若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

**Comment by BJTUpupil** [comment]
BJTUpupil give it to me

**Comment by Candicepan** [comment]
> 设计思路

感谢认领～Next Step：请按照认领说明在您的回复下 再更新您计划的设计思路哈～

**Comment by BJTUpupil** [comment]
BJTUpupil设计思路
---
1.模型选择与数据集：主要集中在yolov3，可能会尝试yolov3-tiny、yolov3-320和yolov3-416，数据集采用PASCAL VOC
---
2.数据分割
整个PASCAL VOC原始数据集我们分为两个子集:数据子集A和数据子集B。
数据子集A包含训练集的50%和验证集的50%，包含所有类型，分配给Client 1。
数据子集B包含训练集的50%和验证集的50%，包含所有类型，分配给Client 2。
如果时间多的话会设计更多参与方的联邦学习
---
3.数据预处理
1.如果使用预训练权重,所有客户端需要使用一致的预训练模型初始化
2.使用相同的图像增强策略,例如随机裁剪、镜像、改变亮度/对比度等
---
4.联邦学习策略
fedavg，因为数据是均衡划分的

**Comment by Candicepan** [comment]
> | 设计思路 BJTUpupil设计思路
> 
> 1.模型选择与数据集：主要集中在yolov3，可能会尝试yolov3-tiny、yolov3-320和yolov3-416，数据集采用PASCAL VOC
> 
> 2.数据分割 整个PASCAL VOC原始数据集我们分为两个子集:数据子集A和数据子集B。 数据子集A包含训练集的50%和验证集的50%，包含所有类型，分配给Client 1。 数据子集B包含训练集的50%和验证集的50%，包含所有类型，分配给Client 2。 如果时间多的话会设计更多参与方的联邦学习
> 
> 3.数据预处理 1.如果使用预训练权重,所有客户端需要使用一致的预训练模型初始化 2.使用相同的图像增强策略,例如随机裁剪、镜像、改变亮度/对比度等
> 
> 4.联邦学习策略 fedavg，因为数据是均衡划分的

LGTM 请在新的子 issue 下再次发送 【give it to me】，将会把该任务的该种实现方式 assign 给你哈～https://github.com/secretflow/secretflow/issues/780

**Comment by Mingbo-Lee** [comment]
Mingbo-Lee Give it to me

**Comment by Mingbo-Lee** [comment]
设计思路：
基于[https://keras.io/examples/vision/object_detection_using_vision_transformer/#object-detection-with-vision-transformers](https://keras.io/examples/vision/object_detection_using_vision_transformer/#object-detection-with-vision-transformers) 为例改写成隐语的联邦学习教程，体现隐语对 keras example的兼容，充分展现隐语的易用性和兼容性
数据分割：按照参与方均匀分割
模型:  [Vision Transformer (ViT)](https://arxiv.org/abs/2010.11929)
数据集：[Caltech 101 dataset](http://www.vision.caltech.edu/datasets/)
联邦策略：充分对齐隐语现有API，只要隐语支持的，理论上都可以支持

**Comment by Candicepan** [comment]
> 设计思路： 基于https://keras.io/examples/vision/object_detection_using_vision_transformer/#object-detection-with-vision-transformers 为例改写成隐语的联邦学习教程，体现隐语对 keras example的兼容，充分展现隐语的易用性和兼容性 数据分割：按照参与方均匀分割 模型: [Vision Transformer (ViT)](https://arxiv.org/abs/2010.11929) 数据集：[Caltech 101 dataset](http://www.vision.caltech.edu/datasets/) 联邦策略：充分对齐隐语现有API，只要隐语支持的，理论上都可以支持

LGTM 请在新的子 issue 下再次发送 【give it to me】，将会把该任务的该种实现方式 assign 给你哈～https://github.com/secretflow/secretflow/issues/856
