### ISSUE TITLE
在 SecretFlow 中实现水平联邦 Audio classification example

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#748]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：在 SecretFlow 中实现水平联邦 Audio classification example
- 技术方向：联邦学习和人工智能
- 任务难度：进阶🌟🌟

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 实现任意一种 audio classification 模型
  - 提供联邦数据集拆分的逻辑
  - 提供语音数据集的处理逻辑 
  - 提交 tutorial，example 代码，数据下载，拆分和预处理代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，最好有与明文结果（PyTorch 或者 TensorFlow）的对比
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码 https://github.com/secretflow/secretflow/tree/main/examples/app/h_audio
  - 整理完整实现过程为文档 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
 
## 能力要求
- 熟悉语音识别技术
- 熟悉 TensorFlow 或者 PyTorch

## 操作说明
- 操作指引：具体操作可参考[操作指引](https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation/deep_fm)进行
- 参考内容：
  - [数据读取](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)
  - [数据预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
  - [联邦模型开发教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)

## 认领说明
本任务可有多种实现方式，故支持有多位开发者进行认领，请在认领任务后，在本 issue 下 comment 你的具体设计思路。

设计思路需要包括以下内容：

1. 计划在什么样的数据集上实现哪一个模型
2. 计划如何进行数据拆分
3. 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
4. 计划选择哪一个联邦策略，是如何考虑的

> 当同一任务有多位开发者提交设计思路时：
> - 若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> - 若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

**Comment by Mingbo-Lee** [comment]
Mingbo-Lee Give it to me

**Comment by Mingbo-Lee** [comment]
设计思路：
考虑到这是一个example，因此基于TensorFlow的example 而改写，可以使得开发者对比两种实现方式的难易和省去一些介绍；

具体来说：
基于 https://github.com/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb 回答以下问题：
- 计划在什么样的数据集上实现哪一个模型
数据集和模型，tutorial都已经给出
- 计划如何进行数据拆分
按照参与方的数目，对数据进行均分
- 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
数据预处理方式，tutorial已经给出，主要给出如何在SecretFlow的场景下进行数据预处理的代码转换
- 计划选择哪一个联邦策略，是如何考虑的
充分对齐隐语现有API，只要隐语支持的，理论上都可以支持

**Comment by zhangxingmeng** [comment]
直接用tensorflow的example移植过来是一个很好地想法。整体方案没什么问题，
数据拆分这里进一步考虑下能不能切成Non_IID来进行后续试验（加分非强制项）。
最终可以参考tf的tutorial给出一个相对详细的隐语迁移tutorial。
LGTM

**Comment by Mingbo-Lee** [comment]
好的，我先完成后完美，先考虑完成基本盘，然后再考虑Non_IID形成对比增强实验

**Comment by Candicepan** [comment]
> 设计思路： 考虑到这是一个example，因此基于TensorFlow的example 而改写，可以使得开发者对比两种实现方式的难易和省去一些介绍；
> 
> 具体来说： 基于 https://github.com/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb 回答以下问题：
> 
> * 计划在什么样的数据集上实现哪一个模型，具体来说，这是一个demo，模型结构比较简单，就是一个[ASR](https://%5Ben.wikipedia.org%5D(https://en.wikipedia.org/wiki/Speech_recognition)/wiki/Speech_recognition)模型，但是涉及到一个`tf.keras.layers.Normalization` 层的实例化，可能需要考虑到数据隐私原因，需要适当改变；数据集使用 [speech_commands](https://www.tensorflow.org/datasets/catalog/speech_commands)，tutorial都已经给出
> * 计划如何进行数据拆分
>   按照参与方的数目，对数据进行均分
> * 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
>   数据预处理方式，tutorial已经给出，主要给出如何在SecretFlow的场景下进行数据预处理的代码转换
> * 计划选择哪一个联邦策略，是如何考虑的
>   充分对齐隐语现有API，只要隐语支持的，理论上都可以支持

因该设计方案比较完整，故本任务不进行拆分，直接 assign 给此设计方案的提交开发者～

**Comment by zhangxingmeng** [comment]
> 好的，我先完成后完美，先考虑完成基本盘，然后再考虑Non_IID形成对比增强实验

在tutorial中可以强调下我们的易用性，目的是让看到这个教程的人，都有想把明文example迁移过来的冲动

**Comment by Mingbo-Lee** [comment]
> > 设计思路： 考虑到这是一个example，因此基于TensorFlow的example 而改写，可以使得开发者对比两种实现方式的难易和省去一些介绍；
> > 具体来说： 基于 https://github.com/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb 回答以下问题：
> > 
> > * 计划在什么样的数据集上实现哪一个模型，具体来说，这是一个demo，模型结构比较简单，就是一个[ASR](https://%5Ben.wikipedia.org%5D(https://en.wikipedia.org/wiki/Speech_recognition)/wiki/Speech_recognition)模型，但是涉及到一个`tf.keras.layers.Normalization` 层的实例化，可能需要考虑到数据隐私原因，需要适当改变；数据集使用 [speech_commands](https://www.tensorflow.org/datasets/catalog/speech_commands)，tutorial都已经给出
> > * 计划如何进行数据拆分
> >   按照参与方的数目，对数据进行均分
> > * 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
> >   数据预处理方式，tutorial已经给出，主要给出如何在SecretFlow的场景下进行数据预处理的代码转换
> > * 计划选择哪一个联邦策略，是如何考虑的
> >   充分对齐隐语现有API，只要隐语支持的，理论上都可以支持
> 
> 因该设计方案比较完整，故本任务不进行拆分，直接 assign 给此设计方案的提交开发者～

@Candicepan  还是拆分出一个 子issue用于[tensorflow-example] 吧；


@zhangxingmeng ,  
1. 考虑到[huggingface](https://huggingface.co/models?pipeline_tag=audio-classification&sort=trending) 同样是一个有影响力的社区，我想，这种基于example的 迁移，是不是可以再来一个 基于 [audio classifacation demo](https://huggingface.co/docs/transformers/main/en/model_doc/audio-spectrogram-transformer#transformers.ASTModel.forward.example)的也同样来一个，因为后续隐语必然需要实现联邦学习模型权重预加载的支持，来减小训练成本，而大量的预训练权重模型在[https://huggingface.co](https://huggingface.co)

2. 同时迁移TensorFlow的代码实现和基于PyTorch的实现是不一样的，甚至难度也不一样，我们是不是可以考虑预留 [PyTorch-example] ?


我目前基本完成[tensorflow-example] 的测试，我准备顺便完成[huggingface-example] ，[huggingface-example] 的实现我觉得也是可行的，主要是基于tensorflow加载大模型，省去自定义网络结构的部分，所以这issue 可以拆分成至少3份，然后[tensorflow-example]和 [huggingface-example] assign 给我，[Pytorch-example] 我可以后续考虑实现和测试

**Comment by zhangxingmeng** [comment]
> huggingface大模型目前的支持度可能并不是很好，在后几个月是有计划去支持的。主要是gpu的支持，单机多卡的支持等。
可以先尝试下，有遇到什么问题，及时反馈给我们

**Comment by Mingbo-Lee** [comment]
好的，那我先反馈一下目前 tensorflow-example 的一些问题

**Comment by Mingbo-Lee** [comment]
Q1:
在[CustomDataLoaderTF](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTF#2.%E5%B0%86%E5%BC%80%E5%8F%91%E5%AE%8C%E6%88%90%E7%9A%84DataBuilder%E8%BF%9B%E8%A1%8C%E5%8C%85%E8%A3%85(wrap))中，使用`len(data_set[1].file_paths)`获取数据集的样本数据，其中`data_set` 由
```
data_set = tf.keras.utils.image_dataset_from_directory(
            folder_path,
            validation_split=0.2,
            subset="both",
            seed=123,
            image_size=(img_height, img_width),
            batch_size=batch_size,
        )
```
加载而来，但是当数据集由`tf.keras.utils.audio_dataset_from_directory()`加载而来是，并不支持这一属性调用，并且两者处于相同的开发环境
```
dataset = tf.keras.utils.audio_dataset_from_directory(
directory=dataset_path,
batch_size=32,
validation_split=0.2,
seed=0,
output_sequence_length=16000,
subset='both')
```
- Images:
![image](https://github.com/secretflow/secretflow/assets/51162830/1c3248aa-0a87-4641-a700-21d65cd216e6)
- Audio:
![image](https://github.com/secretflow/secretflow/assets/51162830/8044dd7c-ea79-4f60-9fd2-2c2db5049f75)
![image](https://github.com/secretflow/secretflow/assets/51162830/4f1d7d88-8c9c-4647-8e81-dc1e7a4149dd)

所以CustomDataLoaderTF可能需要更加通用化的实现或者这里需要换一种方式加载自定义语音数据。

**Comment by ligw1998** [comment]
> > > 设计思路： 考虑到这是一个example，因此基于TensorFlow的example 而改写，可以使得开发者对比两种实现方式的难易和省去一些介绍；
> > > 具体来说： 基于 https://github.com/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb 回答以下问题：
> > > 
> > > * 计划在什么样的数据集上实现哪一个模型，具体来说，这是一个demo，模型结构比较简单，就是一个[ASR](https://%5Ben.wikipedia.org%5D(https://en.wikipedia.org/wiki/Speech_recognition)/wiki/Speech_recognition)模型，但是涉及到一个`tf.keras.layers.Normalization` 层的实例化，可能需要考虑到数据隐私原因，需要适当改变；数据集使用 [speech_commands](https://www.tensorflow.org/datasets/catalog/speech_commands)，tutorial都已经给出
> > > * 计划如何进行数据拆分
> > >   按照参与方的数目，对数据进行均分
> > > * 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
> > >   数据预处理方式，tutorial已经给出，主要给出如何在SecretFlow的场景下进行数据预处理的代码转换
> > > * 计划选择哪一个联邦策略，是如何考虑的
> > >   充分对齐隐语现有API，只要隐语支持的，理论上都可以支持
> > 
> > 
> > 因该设计方案比较完整，故本任务不进行拆分，直接 assign 给此设计方案的提交开发者～
> 
> @Candicepan 还是拆分出一个 子issue用于[tensorflow-example] 吧；
> 
> @zhangxingmeng ,
> 
> 1. 考虑到[huggingface](https://huggingface.co/models?pipeline_tag=audio-classification&sort=trending) 同样是一个有影响力的社区，我想，这种基于example的 迁移，是不是可以再来一个 基于 [audio classifacation demo](https://huggingface.co/docs/transformers/main/en/model_doc/audio-spectrogram-transformer#transformers.ASTModel.forward.example)的也同样来一个，因为后续隐语必然需要实现联邦学习模型权重预加载的支持，来减小训练成本，而大量的预训练权重模型在https://huggingface.co
> 2. 同时迁移TensorFlow的代码实现和基于PyTorch的实现是不一样的，甚至难度也不一样，我们是不是可以考虑预留 [PyTorch-example] ?
> 
> 我目前基本完成[tensorflow-example] 的测试，我准备顺便完成[huggingface-example] ，[huggingface-example] 的实现我觉得也是可行的，主要是基于tensorflow加载大模型，省去自定义网络结构的部分，所以这issue 可以拆分成至少3份，然后[tensorflow-example]和 [huggingface-example] assign 给我，[Pytorch-example] 我可以后续考虑实现和测试

这边还是需要具体定义好audio classification任务和asr (speech recognition)任务的区别，你这边提到的huggingface example其实是一个在audioset上pretrained的一个类似于vit的feature extractor，这个model对于asr任务是没有直接帮助的，也无法用于进行speech的特征处理，注意看他的官方demo，其实他在librispeech上进行测试，在过这个transformer后，classifier得出的结果是该sample是'speech'类，这与我们的目标asr任务不符。

**Comment by Mingbo-Lee** [comment]
> > > > 设计思路： 考虑到这是一个example，因此基于TensorFlow的example 而改写，可以使得开发者对比两种实现方式的难易和省去一些介绍；
> > > > 具体来说： 基于 https://github.com/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb 回答以下问题：
> > > > 
> > > > * 计划在什么样的数据集上实现哪一个模型，具体来说，这是一个demo，模型结构比较简单，就是一个[ASR](https://%5Ben.wikipedia.org%5D(https://en.wikipedia.org/wiki/Speech_recognition)/wiki/Speech_recognition)模型，但是涉及到一个`tf.keras.layers.Normalization` 层的实例化，可能需要考虑到数据隐私原因，需要适当改变；数据集使用 [speech_commands](https://www.tensorflow.org/datasets/catalog/speech_commands)，tutorial都已经给出
> > > > * 计划如何进行数据拆分
> > > >   按照参与方的数目，对数据进行均分
> > > > * 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
> > > >   数据预处理方式，tutorial已经给出，主要给出如何在SecretFlow的场景下进行数据预处理的代码转换
> > > > * 计划选择哪一个联邦策略，是如何考虑的
> > > >   充分对齐隐语现有API，只要隐语支持的，理论上都可以支持
> > > 
> > > 
> > > 因该设计方案比较完整，故本任务不进行拆分，直接 assign 给此设计方案的提交开发者～
> > 
> > 
> > @Candicepan 还是拆分出一个 子issue用于[tensorflow-example] 吧；
> > @zhangxingmeng ,
> > 
> > 1. 考虑到[huggingface](https://huggingface.co/models?pipeline_tag=audio-classification&sort=trending) 同样是一个有影响力的社区，我想，这种基于example的 迁移，是不是可以再来一个 基于 [audio classifacation demo](https://huggingface.co/docs/transformers/main/en/model_doc/audio-spectrogram-transformer#transformers.ASTModel.forward.example)的也同样来一个，因为后续隐语必然需要实现联邦学习模型权重预加载的支持，来减小训练成本，而大量的预训练权重模型在https://huggingface.co
> > 2. 同时迁移TensorFlow的代码实现和基于PyTorch的实现是不一样的，甚至难度也不一样，我们是不是可以考虑预留 [PyTorch-example] ?
> > 
> > 我目前基本完成[tensorflow-example] 的测试，我准备顺便完成[huggingface-example] ，[huggingface-example] 的实现我觉得也是可行的，主要是基于tensorflow加载大模型，省去自定义网络结构的部分，所以这issue 可以拆分成至少3份，然后[tensorflow-example]和 [huggingface-example] assign 给我，[Pytorch-example] 我可以后续考虑实现和测试
> 
> 这边还是需要具体定义好audio classification任务和asr (speech recognition)任务的区别，你这边提到的huggingface example其实是一个在audioset上pretrained的一个类似于vit的feature extractor，这个model对于asr任务是没有直接帮助的，也无法用于进行speech的特征处理，注意看他的官方demo，其实他在librispeech上进行测试，在过这个transformer后，classifier得出的结果是该sample是'speech'类，这与我们的目标asr任务不符。

哦哦，我深入细致研究一下

**Comment by zhangxingmeng** [comment]
> Q1: 在[CustomDataLoaderTF](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTF#2.%E5%B0%86%E5%BC%80%E5%8F%91%E5%AE%8C%E6%88%90%E7%9A%84DataBuilder%E8%BF%9B%E8%A1%8C%E5%8C%85%E8%A3%85(wrap))中，使用`len(data_set[1].file_paths)`获取数据集的样本数据，其中`data_set` 由
> 
> ```
> data_set = tf.keras.utils.image_dataset_from_directory(
>             folder_path,
>             validation_split=0.2,
>             subset="both",
>             seed=123,
>             image_size=(img_height, img_width),
>             batch_size=batch_size,
>         )
> ```
> 
> 加载而来，但是当数据集由`tf.keras.utils.audio_dataset_from_directory()`加载而来是，并不支持这一属性调用，并且两者处于相同的开发环境
> 
> ```
> dataset = tf.keras.utils.audio_dataset_from_directory(
> directory=dataset_path,
> batch_size=32,
> validation_split=0.2,
> seed=0,
> output_sequence_length=16000,
> subset='both')
> ```
> 
> * Images:
>   ![image](https://user-images.githubusercontent.com/51162830/263890635-1c3248aa-0a87-4641-a700-21d65cd216e6.png)
> * Audio:
>   ![image](https://user-images.githubusercontent.com/51162830/263890338-8044dd7c-ea79-4f60-9fd2-2c2db5049f75.png)
>   ![image](https://user-images.githubusercontent.com/51162830/263890406-4f1d7d88-8c9c-4647-8e81-dc1e7a4149dd.png)
> 
> 所以CustomDataLoaderTF可能需要更加通用化的实现或者这里需要换一种方式加载自定义语音数据。

这里可以把数据集的大小直接填进去，然后计算step_per_epoch

**Comment by Mingbo-Lee** [comment]
> > Q1: 在[CustomDataLoaderTF](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTF#2.%E5%B0%86%E5%BC%80%E5%8F%91%E5%AE%8C%E6%88%90%E7%9A%84DataBuilder%E8%BF%9B%E8%A1%8C%E5%8C%85%E8%A3%85(wrap))中，使用`len(data_set[1].file_paths)`获取数据集的样本数据，其中`data_set` 由
> > ```
> > data_set = tf.keras.utils.image_dataset_from_directory(
> >             folder_path,
> >             validation_split=0.2,
> >             subset="both",
> >             seed=123,
> >             image_size=(img_height, img_width),
> >             batch_size=batch_size,
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 加载而来，但是当数据集由`tf.keras.utils.audio_dataset_from_directory()`加载而来是，并不支持这一属性调用，并且两者处于相同的开发环境
> > ```
> > dataset = tf.keras.utils.audio_dataset_from_directory(
> > directory=dataset_path,
> > batch_size=32,
> > validation_split=0.2,
> > seed=0,
> > output_sequence_length=16000,
> > subset='both')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Images:
> >   ![image](https://user-images.githubusercontent.com/51162830/263890635-1c3248aa-0a87-4641-a700-21d65cd216e6.png)
> > * Audio:
> >   ![image](https://user-images.githubusercontent.com/51162830/263890338-8044dd7c-ea79-4f60-9fd2-2c2db5049f75.png)
> >   ![image](https://user-images.githubusercontent.com/51162830/263890406-4f1d7d88-8c9c-4647-8e81-dc1e7a4149dd.png)
> > 
> > 所以CustomDataLoaderTF可能需要更加通用化的实现或者这里需要换一种方式加载自定义语音数据。
> 
> 这里可以把数据集的大小直接填进去，然后计算step_per_epoch


是的，理论上可以这么做，但是这样的话，所实现的Dataloader 没有通用性，而且如果各个参与方的数据集样本不同的话，还需要分离出一个函数形参进行控制。

**Comment by Mingbo-Lee** [comment]
我同时基于微软的[使用 PyTorch 进行音频分类简介教程](https://learn.microsoft.com/zh-cn/training/modules/intro-audio-classification-pytorch/)  实现以PyTorch为后端的水平联邦 Audio classification example，麻烦进行一下issue 拆分

**Comment by Mingbo-Lee** [comment]
> > > Q1: 在[CustomDataLoaderTF](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderTF#2.%E5%B0%86%E5%BC%80%E5%8F%91%E5%AE%8C%E6%88%90%E7%9A%84DataBuilder%E8%BF%9B%E8%A1%8C%E5%8C%85%E8%A3%85(wrap))中，使用`len(data_set[1].file_paths)`获取数据集的样本数据，其中`data_set` 由
> > > ```
> > > data_set = tf.keras.utils.image_dataset_from_directory(
> > >             folder_path,
> > >             validation_split=0.2,
> > >             subset="both",
> > >             seed=123,
> > >             image_size=(img_height, img_width),
> > >             batch_size=batch_size,
> > >         )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 加载而来，但是当数据集由`tf.keras.utils.audio_dataset_from_directory()`加载而来是，并不支持这一属性调用，并且两者处于相同的开发环境
> > > ```
> > > dataset = tf.keras.utils.audio_dataset_from_directory(
> > > directory=dataset_path,
> > > batch_size=32,
> > > validation_split=0.2,
> > > seed=0,
> > > output_sequence_length=16000,
> > > subset='both')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * Images:
> > >   ![image](https://user-images.githubusercontent.com/51162830/263890635-1c3248aa-0a87-4641-a700-21d65cd216e6.png)
> > > * Audio:
> > >   ![image](https://user-images.githubusercontent.com/51162830/263890338-8044dd7c-ea79-4f60-9fd2-2c2db5049f75.png)
> > >   ![image](https://user-images.githubusercontent.com/51162830/263890406-4f1d7d88-8c9c-4647-8e81-dc1e7a4149dd.png)
> > > 
> > > 所以CustomDataLoaderTF可能需要更加通用化的实现或者这里需要换一种方式加载自定义语音数据。
> > 
> > 
> > 这里可以把数据集的大小直接填进去，然后计算step_per_epoch
> 
> 是的，理论上可以这么做，但是这样的话，所实现的Dataloader 没有通用性，而且如果各个参与方的数据集样本不同的话，还需要分离出一个函数形参进行控制。

问题已经解决了在 https://github.com/secretflow/secretflow/pull/923 @zhangxingmeng

**Comment by Candicepan** [comment]
> 我同时基于微软的[使用 PyTorch 进行音频分类简介教程](https://learn.microsoft.com/zh-cn/training/modules/intro-audio-classification-pytorch/) 实现以PyTorch为后端的水平联邦 Audio classification example，麻烦进行一下issue 拆分

该 issue 将直接 assign 给你哈～该种实现方案直接关联本 issue 即可哈
