### ISSUE TITLE
Install .Build and Code Fail

### ISSUE THREAD

**Issue by shenghuoli** [secretflow/secretflow#75]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow 最新版

### OS Platform and Distribution

Ubuntu18.04/Ubuntu22.04

### Python version

python3.8.13

### What happend and What you expected to happen.

```shell
操作系统Ubuntu18.04下
如果使用 pip install -U secretflow，报错为：
Requirement already satisfied: aiohttp<=4 in ./.local/lib/python3.8/site-packages (from s3fs==2022.1.0->secretflow) (3.8.1)
Collecting aiobotocore~=2.1.0
Downloading http://pypi.doubanio.com/packages/4e/8d/01035d9b56893bd3b5d6eb4505d3ed1383d124b1c9c2b6024c175681c64b/aiobotocore-2.1.2.tar.gz (58 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.7/58.7 kB 3.0 MB/s eta 0:00:00
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
ERROR: Can not execute setup.py since setuptools is not available in the build environment.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

在源码下pip install -r requirement,报错为：

Collecting jax==0.3.7
Downloading http://pypi.doubanio.com/packages/d7/ef/8ff361f49244956f48c3528a42c392c31bdbcbb9af5399eba19e153a5c26/jax-0.3.7.tar.gz (944 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 944.2/944.2 kB 3.0 MB/s eta 0:00:00
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
ERROR: Can not execute setup.py since setuptools is not available in the build environment.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


在Ubuntu22.04下：
安装没有发生错误，但是运行简单的例子，出现错误：
(secretflow) shenghuo@shenghuo-machine:~/src$ python test.py
Traceback (most recent call last):
File "test.py", line 1, in
import secretflow as sf
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/init.py", line 15, in
from . import data, device, ml, preprocessing, security, utils
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/data/init.py", line 15, in
from . import horizontal, vertical
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/data/horizontal/init.py", line 15, in
from .dataframe import HDataFrame
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/data/horizontal/dataframe.py", line 21, in
from secretflow.data.base import DataFrameBase, Partition
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/data/base.py", line 23, in
from secretflow.device import PYUObject, reveal
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/init.py", line 15, in
from .device import *
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/init.py", line 16, in
from .heu import HEU
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/heu.py", line 17, in
from secretflow.device.device.spu import PyTreeLeaf
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 31, in
import spu
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/init.py", line 33, in
from .binding.api import Io, Runtime, compile
File "/home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/api.py", line 21, in
from . import _lib
ImportError: /home/shenghuo/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/_lib.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
sf.init(['alice', 'bob', 'carol'], num_cpus=8, log_to_driver=True)
dev = sf.PYU('alice')
import numpy as np
data = dev(np.random.rand)(3, 4)
data
```

**Comment by anakinxc** [comment]
> ERROR: Can not execute setup.py since setuptools is not available in the build environment.

试一下 pip install setuptools

**Comment by shenghuoli** [comment]
不是这个问题，setuptools 已安装了，看错误更像是某个依赖库没有安装对。
能不能更明确的从一个干净的Ubuntu18.04到能安装secretflow之间所有依赖包的更新过程


> > ERROR: Can not execute setup.py since setuptools is not available in the build environment.
> 
> 试一下 pip install setuptools

**Comment by anakinxc** [comment]
直接 pip install secretflow 应该会自己安装所有的 dependencies

方便 check 一下 pip 和 setuptools 的版本吗

**Comment by shenghuoli** [comment]
Ubuntu22.04下：
python：3.8.13
pip list的执行结果如下：
absl-py                      1.0.0
aiobotocore                  2.1.2
aiohttp                      3.8.1
aioitertools                 0.10.0
aiosignal                    1.2.0
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        21.4.0
botocore                     1.23.24
cachetools                   5.2.0
certifi                      2022.6.15
charset-normalizer           2.1.0
chex                         0.1.3
click                        8.0.4
cloudpickle                  2.0.0
coverage                     6.4.2
cycler                       0.11.0
dill                         0.3.4
distlib                      0.3.5
dm-tree                      0.1.7
filelock                     3.7.1
flatbuffers                  2.0
flax                         0.4.1
fonttools                    4.34.4
frozenlist                   1.3.0
fsspec                       2022.1.0
gast                         0.4.0
google-auth                  2.9.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.56.4
grpcio                       1.47.0
h5py                         3.7.0
idna                         3.3
importlib-metadata           4.12.0
importlib-resources          5.9.0
jax                          0.3.7
jaxlib                       0.3.7
jmespath                     0.10.0
joblib                       1.1.0
jsonschema                   4.7.2
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
libclang                     14.0.1
loguru                       0.6.0
lxml                         4.9.1
Markdown                     3.4.1
matplotlib                   3.5.2
msgpack                      1.0.4
multidict                    6.0.2
numpy                        1.22.3
oauthlib                     3.2.0
opt-einsum                   3.3.0
optax                        0.1.3
packaging                    21.3
pandas                       1.4.2
Pillow                       9.2.0
pip                          22.2
platformdirs                 2.5.2
promise                      2.3
protobuf                     3.19.4
psutil                       5.9.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
pyrsistent                   0.18.1
python-dateutil              2.8.2
pytz                         2022.1
PyYAML                       6.0
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
s3fs                         2022.1.0
scikit-learn                 1.0
scipy                        1.8.1
secretflow                   0.6.13b1
secretflow-ray               2.0.0.dev0
setuptools                   63.2.0
sf_heu                       0.1.0b1
six                          1.16.0
spu                          0.1.0b1
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.2
tensorflow-datasets          4.5.2
tensorflow-estimator         2.8.0
tensorflow-io-gcs-filesystem 0.26.0
tensorflow-metadata          1.9.0
termcolor                    1.1.0
threadpoolctl                3.1.0
toolz                        0.12.0
torch                        1.10.1
torchvision                  0.11.2
tqdm                         4.62.3
typing_extensions            4.3.0
unittest-xml-reporting       3.2.0
urllib3                      1.26.10
validator.py                 1.3.0
virtualenv                   20.15.1
Werkzeug                     2.1.2
wheel                        0.37.1
wrapt                        1.14.1
xgboost                      1.5.2
xmlrunner                    1.7.7
yarl                         1.7.2
zipp                         3.8.1

-----------------------------------------
Ubuntu18.04下：
Package            Version
------------------ -------
aiobotocore        2.3.4
aiohttp            3.8.1
aioitertools       0.10.0
aiosignal          1.2.0
async-timeout      4.0.2
attrs              21.4.0
botocore           1.24.21
charset-normalizer 2.1.0
frozenlist         1.3.0
idna               3.3
jmespath           1.0.1
multidict          6.0.2
pip                22.2.1
python-dateutil    2.8.2
setuptools         56.0.0
six                1.16.0
typing_extensions  4.3.0
urllib3            1.26.11
wrapt              1.14.1
yarl               1.7.2

**Comment by anakinxc** [comment]
setuptools 看起来比较老，试一下最新的吧

**Comment by tong901023041** [comment]
@anakinxc 我的Ubuntu22.04版本遇到了同样的问题，安装没有报错，但是运行时出了上面描述的问题，请问有什么解决方法吗？setuptools 版本已经是61.2.0了

**Comment by anakinxc** [comment]
@tong901023041 先直接用我们的 docker 跑吧

`https://hub.docker.com/r/secretflow/spu-gcc11-anolis-dev`

Ubuntu 22.04 用的 glibc 2.35 版本太高了，我们后续再考虑兼容吧

**Comment by shenghuoli** [comment]
> @tong901023041 先直接用我们的 docker 跑吧
> 
> `https://hub.docker.com/r/secretflow/spu-gcc11-anolis-dev`
> 
> Ubuntu 22.04 用的 glibc 2.35 版本太高了，我们后续再考虑兼容吧

升级setuptool后，Ubuntu18.04上已经安装成功了。
现在Ubuntu22.04上还存在glibc的问题。
