### ISSUE TITLE
在 SecretFlow 中实现垂直联邦推荐场景 example

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#752]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：在 SecretFlow 中实现垂直联邦推荐场景 example
- 技术方向：联邦学习和人工智能
- 任务难度：进阶🌟🌟
- 任务期望时间：4-5 周

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 需要引入和推荐场景有关的开源数据集，并提供拆分逻辑
  - 基于 SLModel 实现模型代码，并对模型的拆分逻辑进行封装，提交代码到 nn/sl/application中
  - 提交 tutorial，example 代码，数据下载，拆分和预处理代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，最好有与明文结果（PyTorch 或者 TensorFlow）的对比
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码 https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation
  - 整理完整实现过程为文档 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
 
## 能力要求
- 熟悉拆分学习，熟悉推荐模型
- 熟悉 TensorFlow 或者 PyTorch

## 操作说明
- 操作指引：具体操作可参考[操作指引](https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation/deep_fm)进行
- 参考内容：
  - [数据读取](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)
  - [数据预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
  - [联邦模型开发教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)

## 认领说明
本任务可有多种实现方式，故支持有多位开发者进行认领，请在认领任务后，在本 issue 下 comment 你的具体设计思路。

设计思路需要包括以下内容：

1. 计划在什么样的数据集上实现哪一个模型
2. 计划如何进行数据拆分
3. 计划如何处理联邦数据预处理：如 NLP 任务中需要 tokenize，那么在水平分布式下要怎样做
4. 计划选择哪一个联邦策略，是如何考虑的

> 当同一任务有多位开发者提交设计思路时：
> - 若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> - 若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

**Comment by Lia0409** [comment]
Lia0409 Give it to me

**Comment by Lia0409** [comment]
设计思路：
1. 数据集及模型：
选择开源的电影推荐数据集 MovieLens（100k/1M），其中包含用户对电影的评分信息。模型初步计划选择 MF，根据后续实现情况考虑添加 NCF/LightGCN。
2. 数据拆分方案：
进行垂直拆分将数据分为若干方，例如将用户信息分配给方A，将电影信息分配给方B。确定联邦数据集的拆分逻辑，例如按照用户ID拆分，确保相同用户的信息在同一个拆分方中。
3. 联邦数据预处理：
对于A方，进行数据预处理步骤，例如对用户特征进行标准化或归一化处理。对于B方，可以进行类似的预处理步骤。需要考虑检查数据集中的空值、缺失值或异常值，并根据情况进行处理。
4. 联邦策略选择：
初步考虑选择FedAvg方案，因为其适用性更广泛。

**Comment by ian-huu** [comment]
请确认一下场景是垂直联邦或者[拆分学习](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/user_guide/federated_learning/vertical_federated_learning/split_learning)的场景：一般来说是指两方有同样的样本、不同的特征的场景。

如果对场景的理解一致，那么请再补充一下方案细节：

> 1. 数据集及模型：
>    选择开源的电影推荐数据集 MovieLens（100k/1M），其中包含用户对电影的评分信息。模型初步计划选择 MF，根据后续实现情况考虑添加 NCF/LightGCN。

请大致补充一下模型拆分方案

> 2. 数据拆分方案：
>    进行垂直拆分将数据分为若干方，例如将用户信息分配给方A，将电影信息分配给方B。确定联邦数据集的拆分逻辑，例如按照用户ID拆分，确保相同用户的信息在同一个拆分方中。

请确认：是否两边拥有相同的用户 ID 的数据，只是特征不同

> 4. 联邦策略选择：
>    初步考虑选择FedAvg方案，因为其适用性更广泛。

垂直场景应该不涉及联邦聚合策略

**Comment by Lia0409** [comment]
好的 以下是对设计思路的补充：
1. 数据集及模型：
选择开源的电影推荐数据集 MovieLens（100k/1M），其中包含用户对电影的评分信息。模型初步计划选择 MF，根据后续实现情况考虑添加 NCF/LightGCN。
2. 数据拆分逻辑：
按照用户 ID 拆分，保证两方拥有相同的用户 ID 的数据，但特征不同，如  alice 方拥有 “UserID”, “Gender”, “Age”, “Occupation” 等特征； bob 方拥有 “MovieID”, “Rating”, “Title”, “Genres”, “Timestamp”等特征
3. 模型拆分方案：
alce方训练本地模型 base_model1；因为bob方持有评分标签，需要训练本地模型 base_model2 及 fuse_model,fuse_model 负责合并 basel_model1 的及 base_model2 的输出进行模融合。
4. 是的，如果是拆分学习场景，不需要联邦聚合策略，之前的理解有误。

**Comment by Lia0409** [comment]
好的 以下是对设计思路的补充：
1. 数据集及模型：选择开源的电影推荐数据集 MovieLens（100k/1M），其中包含用户对电影的评分信息。模型初步计划选择 MF，根据后续实现情况考虑添加 NCF/LightGCN。
2. 数据拆分逻辑：按照用户 ID 拆分，保证两方拥有相同的用户 ID 的数据，但特征不同，如  alice 方拥有 “UserID”, “Gender”, “Age”, “Occupation” 等特征； bob 方拥有 “MovieID”, “Rating”, “Title”, “Genres”, “Timestamp”等特征
3. 模型拆分方案：
alce方训练本地模型 base_model1；因为bob方持有评分标签，需要训练本地模型 base_model2 及 fuse_model,fuse_model 负责合并 basel_model1 的及 base_model2 的输出进行模融合。
4. 是的，如果是拆分学习场景，不需要联邦聚合策略，之前的理解有误。

**Comment by Lia0409** [comment]
好的 以下是对设计思路的补充：
1. 数据集及模型：
选择开源的电影推荐数据集 MovieLens（100k/1M），其中包含用户对电影的评分信息。模型初步计划选择 MF，根据后续实现情况考虑添加 NCF/LightGCN。
2. 数据拆分逻辑：
按照用户 ID 拆分，保证两方拥有相同的用户 ID 的数据，但特征不同，如  alice 方拥有 “UserID”, “Gender”, “Age”, “Occupation” 等特征； bob 方拥有 “MovieID”, “Rating”, “Title”, “Genres”, “Timestamp”等特征
3. 模型拆分方案：
alce方训练本地模型 base_model1；因为bob方持有评分标签，需要训练本地模型 base_model2 及 fuse_model,fuse_model 负责合并 basel_model1 的及 base_model2 的输出进行模融合。
4. 是的，如果是拆分学习场景，不需要联邦聚合策略，之前的理解有误。

**Comment by Candicepan** [comment]
> 好的 以下是对设计思路的补充：
> 
> 1. 数据集及模型：
>    选择开源的电影推荐数据集 MovieLens（100k/1M），其中包含用户对电影的评分信息。模型初步计划选择 MF，根据后续实现情况考虑添加 NCF/LightGCN。
> 2. 数据拆分逻辑：
>    按照用户 ID 拆分，保证两方拥有相同的用户 ID 的数据，但特征不同，如  alice 方拥有 “UserID”, “Gender”, “Age”, “Occupation” 等特征； bob 方拥有 “MovieID”, “Rating”, “Title”, “Genres”, “Timestamp”等特征
> 3. 模型拆分方案：
>    alce方训练本地模型 base_model1；因为bob方持有评分标签，需要训练本地模型 base_model2 及 fuse_model,fuse_model 负责合并 basel_model1 的及 base_model2 的输出进行模融合。
> 4. 是的，如果是拆分学习场景，不需要联邦聚合策略，之前的理解有误。

LGTM 请在新的子 issue 下再次发送 【give it to me】，将会把该任务的该种实现方式 assign 给你哈～https://github.com/secretflow/secretflow/issues/798

**Comment by zhangxingmeng** [comment]
![image](https://github.com/secretflow/secretflow/assets/103552200/b74612b8-59cc-4199-a373-4e28cfc326ef)
lightgcn论文里面有三个dataset，希望能够在这几个中进行选择，把新的数据集引入进来，感谢。
NCF可以试着用pinterest数据集来做一下。
