### ISSUE TITLE
增加 SecretFlow 的  PIR 用户指南和使用教程

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#754]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：增加 SecretFlow 的 PIR 用户指南和使用教程
- 技术方向：PSI/PIR
- 任务难度：热身🌟

## 详细要求
请为 SecretFlow 补充以下文档内容，包括：
- PIR 用户指南，包含原理介绍
- PIR 使用教程，包含代码示例和说明，注：代码示例需要符合下述代码规范
  - 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 issue 并提交相应内容至对应地址：
  - PIR 用户指南：https://github.com/secretflow/secretflow/tree/main/docs/user_guide
  - PIR 使用教程：https://github.com/secretflow/secretflow/tree/main/docs/tutorial
## 能力要求
- 熟悉 PIR 原理
- 熟悉 labeled PSI 原理
- 熟悉隐语 PIR 接口

## 参考内容
- [隐私集合求交](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/user_guide/psi)
- [SPU 隐私求交](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/PSI_On_SPU)

**Comment by guzy** [comment]
guzy Give it to me
