### ISSUE TITLE
为 TEEU 添加“标准化”预处理教程

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#757]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：为 TEEU 添加“标准化”预处理教程
- 技术方向：TEE
- 任务难度：进阶 🌟🌟
- 任务期望时间：4-5 周

## 详细要求
TEEU 是隐语的 TEE 密态设备，目前 TEEU 仅提供了基础的运行示例，本任务旨在给 TEEU 添加数据“标准化”预处理教程，包括示例代码与中英文文档教程。
- 能力要求：需要与 sklearn normalization 对齐
- 能力要求：需要和 pandas 能力对齐
- 格式要求：需要使用 notebook 编写
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：教程需包括中英文双语版本，请关联该 issue 并按照[操作说明](https://www.yuque.com/secret-flow/admin/vy40r795gfzhbf33)逐步操作提交 PR 至 https://github.com/secretflow/secretflow/docs/tutorials/teeu/

## 能力要求
- 熟悉隐语密态设备 TEEU

## 参考内容
- 可参考实现：可以参考[隐语已有的预处理教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
- TEEU 操作指引：《[TEEU 上手指南](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/teeu)》

**Comment by C4V1NC3MPT-196883** [comment]
C4V1NC3MPT-196883  give it to me

**Comment by Candicepan** [comment]
> C4V1NC3MPT-196883 give it to me

因未在规定时间内完成，改任务回收啦～欢迎下次继续认领 也欢迎其他小伙伴认领该任务
