### ISSUE TITLE
请问有ABY.3的例子吗

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#76]
请问有ABY.3的例子吗

**Comment by 6fj** [comment]
Hi @holdbelief ，

SPU device支持ABY3协议，只需要在init device的时候设置protocol即可。

**Comment by holdbelief** [comment]
> SPU device支持ABY3协议，只需要在init device的时候设置protocol即可。

![image](https://user-images.githubusercontent.com/14867598/182132039-abbc08d4-d745-4cf8-8d58-5c2111ef67fa.png)
这两个地方还需要修改吗

**Comment by 6fj** [comment]
只需要调整protocol，请参考https://spu.readthedocs.io/en/beta/reference/runtime_config.html#runtimeconfig

**Comment by 6fj** [comment]
另外，请确保SPU device必须由三个节点组成的时候，才可以使用ABY3协议。
