### ISSUE TITLE
实现 TEEU 与 SPU 之间的数据流转

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#764]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- 任务名称：实现 TEEU 与 SPU 之间的数据流转
- 技术方向：TEE、SPU
- 任务难度：挑战 🌟🌟🌟
- 任务期望时间：8 周
- 特别说明：为避免设计思路与正确方案出现偏差导致提交内容不符合任务要求的情况出现，请在认领任务后，在该 issue 下 comment 你的具体设计思路。**具体设计思路**：简单说明您计划如何实现该任务的思路即可。确认您的设计思路没问题，将在该条 comment 下回复您，您即可进入开发阶段。

## 详细要求
TEEU 和 SPU 分别是隐语的 TEE 和 MPC 密态设备，两者均支持以密态形式运行一段程序。目前一段程序只能在 SPU 或 TEEU 中的某一个上运行，而 TEE 和 MPC 各有优势。
为满足潜在的需求，比如部分逻辑使用 SPU 运行，另一部分逻辑使用 TEEU 运行，需要支持 TEEU 和 SPU 之间的数据流转，本任务主要为实现部分的代码开发，具体要求如下：
-  功能性：
  - 支持 SPU 数据传输给 TEEU
  - 支持 TEEU 数据传输给 SPU
- 安全性：
  - SPU 数据 to TEEU，分片传输过程应加密，reveal 数据仅 TEEU 可解密
- 准确性：
  - SPU to TEEU：TEEU 结果数据应该与 SPU reveal 一致
  - TEEU to SPU：SPU reveal 结果数据应该与明文一致
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/secretflow

## 能力要求
- 熟悉隐语密态设备 SPU 与 TEEU
- 熟悉 TEE 技术栈（SGX2、远程认证、Occlum 等）

## 操作说明
- 可参考实现：可以参考隐语已有的不同设备数据流转，比如 [PYU to TEEU](https://github.com/secretflow/secretflow/blob/main/secretflow/device/kernels/pyu.py#L94)
- 操作指引：[了解 TEEU](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/teeu)

**Comment by zhouaihui** [comment]
续一下🐶
