### ISSUE TITLE
TEEU 支持有状态计算实现

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#765]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：TEEU 支持有状态计算实现
- 技术方向：TEE、Ray
- 任务难度：挑战 🌟🌟🌟
- 特别说明：为避免设计思路与正确方案出现偏差导致提交内容不符合任务要求的情况出现，请在认领任务后，在该 issue 下 comment 你的具体设计思路。**具体设计思路**：简单说明您计划如何实现该任务的思路即可。确认您的设计思路没问题，将在该条 comment 下回复您，您即可进入开发阶段。

## 详细要求
TEEU 是隐语的 TEE 密态设备，目前 TEEU 支持以密态形式运行函数，即无状态计算。实际应用中，用户可能需要在 TEE 中进行复杂计算，TEEU 支持有状态计算可以更好的支撑复杂计算。具体要求如下：
- 安全性：TEEU 有状态计算需要保证机密性与完整性
- 功能性：支持 class 形式的 TEEU Actor，接口应简洁易用
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/secretflow

## 能力要求
- 熟悉隐语密态设备 SPU 与 TEEU
- 熟悉 TEE 技术栈（SGX2、远程认证、Occlum 等）
- 熟悉 Ray 的编程模型和接口

## 操作说明
- 可参考实现：
  - 隐语明文设备 PYU 的 Actor 实现，比如 [proxy](https://github.com/secretflow/secretflow/blob/main/secretflow/device/proxy.py)
  - [Ray 的 Actor 计算模型](https://docs.ray.io/en/latest/ray-core/actors.html)
- 操作指引：[TEEU 上手指南](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/teeu)

**Comment by lcc1999** [comment]
lcc1999 Give it to me

**Comment by lcc1999** [comment]
对于用户定义的一个类，TEEU中对应一个继承自此类的ActorClass，其中的构造函数增加获取AuthFrame以及对参数解密的部分，其余函数也需解密参数。
修改TEEU.__call__，使其可传入函数或类。传入类时返回一个继承自TEEUObject的ActorProxy类，其中的data字段为一个在TEE中运行的ActorClass实例。

**Comment by zhouaihui** [comment]
思路挺好的，期待你的PR。

**Comment by lcc1999** [comment]
请问一下ci/circleci没过要怎么处理

**Comment by zhouaihui** [comment]
hi，我们在PR里讨论ci等细节问题吧
