### ISSUE TITLE
[特别任务] 拆分联邦算法实现和拆分学习模型逆向攻击算法实现

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#774]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE *合作任务*，合作开发者可完成，其他开发者欢迎点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择其他你感兴趣的任务，热烈欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：拆分联邦算法实现和拆分学习模型逆向攻击算法实现
- 技术方向：Federated Learning/Split Learning
- 任务难度：挑战🌟🌟🌟

## 详细要求
结合 [SLModel](https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/sl/sl_model.py) 拆分联邦算法实现和拆分学习模型逆向攻击算法实现，实现拆分学习图数据的特征攻击算法实现，进行封装实验和实验报告。
- 安全性：尽量少 reveal
- 功能性：可完整实现某个拆分学习攻防算法的全流程
- 收敛性：包含 simulator 跑出的实验数据并且证明攻击/防御效果
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/secretflow/tree/main/examples/security

## 能力要求
- 网空项目-拆分学习攻防参与同学

## 操作说明
- 可参考 [SecretFlow 实现方式](https://github.com/secretflow/secretflow/blob/main/secretflow/ml/linear/ss_sgd/model.py)
- [拆分学习模型操作指引](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing)

**Comment by zhangzp9970** [comment]
zhangzp9970 give it to me.
