### ISSUE TITLE
woe-ivs计算的时候，当数据集变大，超出spu内存计算

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#777]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.0.0b3

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.13

### Bazel version

5.4.1

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
当我用隐语官方处理的数据，一切正常，
当我把数据集切换为epsilon,出现bug,数据集是40万行



bug 如下：

SendProxyActor pid=281652) 2023-07-21 17:28:29 ERROR barriers.py:240 [alice] --  Failed to send data to seq_id 15 of bob from {upstream_seq_id}, error: <AioRpcError of RPC that terminated with:
(SendProxyActor pid=281652)     status = StatusCode.RESOURCE_EXHAUSTED
(SendProxyActor pid=281652)     details = "Sent message larger than max (1443203851 vs. 524288000)"
(SendProxyActor pid=281652)     debug_error_string = "UNKNOWN:Error received from peer 10.229.207.13:9926 {created_time:"2023-07-21T17:28:28.921012584+08:00", grpc_status:8, grpc_message:"Sent message larger than max (1443203851 vs. 524288000)"}"
(SendProxyActor pid=281652) >

libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/message_lite.cc:450] spu.ValueProto exceeded maximum protobuf size of 2GB: 2560000039

请帮忙看看。
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by zhouaihui** [comment]
可以在`sf.init`中设置参数`cross_silo_messages_max_size_in_bytes`，详情参考[sf.init](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow#secretflow.init)。

**Comment by SZU-czw** [comment]
> ```shell
> 2560000039
> ```
我的数据集是alice和bob 各自为1.9G
当我把参数调到cross_silo_messages_max_size_in_bytes=2*1024**3,直接报错
OverflowError: value too large to convert to int
然后双方一直ping不到对方

然后把它调小一些，后面spu计算报错
 spu.ValueProto exceeded maximum protobuf size of 2GB: 2560000039

是不是超过2G的数据不能计算呢？

**Comment by SZU-czw** [comment]
> 可以在`sf.init`中设置参数`cross_silo_messages_max_size_in_bytes`，详情参考[sf.init](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow#secretflow.init)。

请教问题如上

**Comment by zhouaihui** [comment]
文档中有显示说明，`The size must be strictly less than 2GB, i.e. 2 * (1024 ** 3).`，cross_silo_messages_max_size_in_bytes必须小于这个值，这个是grpc自己的限制。

**Comment by zhouaihui** [comment]
最大支持的数据上限 麻烦@warriorpaw 确认下。

**Comment by warriorpaw** [comment]
请更新到1.0.0b3 版本

**Comment by SZU-czw** [comment]
> 请更新到1.0.0b3 版本

使用版本已经是该最新版本，数据集超过2G直接报错。目测无解

**Comment by warriorpaw** [comment]
> > 请更新到1.0.0b3 版本
> 
> 使用版本已经是该最新版本，数据集超过2G直接报错。目测无解

SPU已经支持大数据量计算，secretflow内部变更还没同步出来，可能需要等待1到2周，下个版本应该可以跑。

**Comment by SZU-czw** [comment]
> > > 请更新到1.0.0b3 版本
> > 
> > 
> > 使用版本已经是该最新版本，数据集超过2G直接报错。目测无解
> 
> SPU已经支持大数据量计算，secretflow内部变更还没同步出来，可能需要等待1到2周，下个版本应该可以跑。

大佬好，时隔两个月，请问这个bug解决了吗？我目前使用的是隐语1.2.0最新版本，数据量是4G以上测试，问题还存在。
