### ISSUE TITLE
请问是否有federated learning的例子（不是split learning）（并且数据是纵向的）

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#78]
请问是否有federated learning的例子（不是split learning）

**Comment by zhouaihui** [comment]
[Federate_Learning_for_Image_Classification](https://secretflow.readthedocs.io/en/latest/tutorial/Federate_Learning_for_Image_Classification.html)

**Comment by holdbelief** [comment]
> Federate_Learning_for_Image_Classification

感谢

**Comment by holdbelief** [comment]
> Federate_Learning_for_Image_Classification

这个例子的数据是横向的，有没有纵向的数据的federated learning的例子

**Comment by pchyuan** [comment]
目前没有纵向数据的FL，该能力通过MPC就可以满足，想问下你的需求场景是？

**Comment by FelixZheng1** [comment]
您指的是https://dl.acm.org/doi/pdf/10.1145/3298981 这个论文中提到的垂直联邦学习吗？
