### ISSUE TITLE
[yolov3] 在 SecretFlow 中实现水平联邦目标识别 example

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#780]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741) https://github.com/secretflow/secretflow/issues/746 子任务，若对该任务感兴趣，欢迎在 https://github.com/secretflow/secretflow/issues/746 提交你的不同设计思路。
> 
> 也欢迎其他开发者点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择其他你感兴趣的任务，热烈欢迎社区开发者参与共建～

## 设计思路

by [BJTUpupil](https://github.com/BJTUpupil)

1. 模型选择与数据集：主要集中在yolov3，可能会尝试yolov3-tiny、yolov3-320和yolov3-416，数据集采用PASCAL VOC

2. 数据分割
- 整个PASCAL VOC原始数据集我们分为两个子集:数据子集A和数据子集B。
- 数据子集A包含训练集的50%和验证集的50%，包含所有类型，分配给Client 1。
- 数据子集B包含训练集的50%和验证集的50%，包含所有类型，分配给Client 2。
- 如果时间多的话会设计更多参与方的联邦学习

3. 数据预处理
- 如果使用预训练权重,所有客户端需要使用一致的预训练模型初始化
- 使用相同的图像增强策略,例如随机裁剪、镜像、改变亮度/对比度等

4. 联邦学习策略
fedavg，因为数据是均衡划分的

## 任务介绍

- 任务名称：在 SecretFlow 中实现水平联邦目标识别 example
- 技术方向：联邦学习和人工智能
- 任务难度：进阶🌟🌟

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 实现任意一种目标检测方法
  - 提供联邦数据集拆分的逻辑
  - 提交 tutorial，example 代码，数据下载，拆分和预处理代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，最好有与明文结果（PyTorch 或者 TensorFlow）的对比
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码 https://github.com/secretflow/secretflow/tree/main/examples/app/h_cv/object_detection
  - 整理完整实现过程为文档 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
 
## 能力要求
- 熟悉目标检测相关技术，包括但不限于 R-CNN，SSD，YOLO 等
- 熟悉 TensorFlow 或者 PyTorch

## 操作说明
- 操作指引：具体操作可参考[操作指引](https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation/deep_fm)进行
- 参考内容：
  - [数据读取](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)
  - [数据预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
  - [联邦模型开发教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)

**Comment by BJTUpupil** [comment]
BJTUpupil Give it to me.

**Comment by Candicepan** [comment]
> BJTUpupil Give it to me.

hello～因任务认领后一直没有进展，故本任务先行回收了哈～如果对隐语社区的贡献感兴趣可以再次认领哈～感谢你的隐语社区的支持
