### ISSUE TITLE
【问题】算法和数据是如何联系到一起的

### ISSUE THREAD

**Issue by ZhouZhaoJi** [secretflow/secretflow#787]
![image](https://github.com/secretflow/secretflow/assets/36101779/ef554be9-f433-4d70-9707-8cf0ae3e8d35)

我看到很多例子都是本地的。如果在真实的三台机器，算法和数据是如何联系起来的？
比如节点1拥有a，节点2拥有b，节点3拥有一个算法get_winner，需要将a和b做一个比较。
但是调用这句话的时候，spu_device2(get_winner)(a, b)，可能这是节点4或者节点3，它是如何拿到这个a和b的？
然后节点1如何初始化自己的a？

**Comment by ZhouZhaoJi** [comment]
get_carol_assets是运行在carol节点的？然后在这个函数中可以直接读取carol节点的文件?

**Comment by 6fj** [comment]
Hi @ZhouZhaoJi 

1. get_carol_assets/get_dave_assets 代表的是一个单方的生成数据任务，实际场景可能是读入csv/本地数据处理/..., 可以看到这些函数都是一个PYU device来执行，比如上面的`carol, dave`。
2. 当需要做mpc计算时，需要init一个SPU device，比如上面的`spu_device2`, 一个spu device是需要多方参与的，比如alice，bob可以setup一个spu device，数据从PYU device发送到SPU device意味着，数据owner需要做数据分片，并且把数据分片发送到每个SPU节点（比如alice和bob）。
3. 在secretflow中，每一方都被称为一个party，基于party可以setup不同的device（PYU device，SPU device，HEU device），数据被称为DeviceObject。但是算法没有owner，每一个party都能看到完整的code，因此你的表述中get_winner是没有owner的，只能说get_winner被`spu_device2`来执行。

感谢。如果有不清楚的问题可以继续comment。

**Comment by ZhouZhaoJi** [comment]
def get_bob_assets():
	f = open("1")
	lines = f.read()
	i = int(lines)
	f.close()
	return i
我懂了，但是这样会不会不安全？比如这份代码可以访问目标节点的文件或者数据库？

**Comment by ZhouZhaoJi** [comment]
如果这个函数要读取的数据非常多，可能会出现问题吗？

**Comment by 6fj** [comment]
这里的数据传递是基于pickle和grpc的，所以如果数据很大是可能出现问题的。
数据的分块是需要算法开发者来处理的，secretflow第一方算法中很多都处理了这个问题。

**Comment by ZhouZhaoJi** [comment]
谢谢回答，我明白了。
