### ISSUE TITLE
pip3 install -U secretflow

### ISSUE THREAD

**Issue by luckymlog** [secretflow/secretflow#79]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow 最新版

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.8.13

### Bazel version

0

### GCC/Compiler version

0

### What happend and What you expected to happen.

```shell
ERROR: Could not find a version that satisfies the requirement secretflow (from versions: none)
ERROR: No matching distribution found for secretflow
```

### Reproduction code to reproduce the issue.

```shell
pip3 install -U secretflow
```

**Comment by Shunliing** [comment]
遇到相同问题

**Comment by anakinxc** [comment]
先试一下更新 pip

`python3 -m pip install -U pip`

**Comment by luckymlog** [comment]
更新pip以后，
pip 22.2.1
还是一样错误

**Comment by anakinxc** [comment]
能不能也提供一下以下命令
`uname -a`
`ldd --version`
的输出呀

**Comment by zhouaihui** [comment]
@luckymlog 按照你提供的环境信息，我们无法复现你的问题。

我们的复现步骤
1. docker run -it ubuntu:22.04
2. apt-get update && apt-get install wget &&  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
3. bash Miniconda3-latest-Linux-x86_64.sh
4. source /root/miniconda3/bin/activate
5. conda create --name secretflow python==3.8.13
6. conda activate secretflow
7. pip install secretflow
以上均顺利完成。

你们也可以试试用上述方法执行。

**Comment by data-alexpan** [comment]
> @luckymlog 按照你提供的环境信息，我们无法复现你的问题。
> 
> 我们的复现步骤
> 
> 1. docker run -it ubuntu:22.04
> 2. apt-get update && apt-get install wget &&  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
> 3. bash Miniconda3-latest-Linux-x86_64.sh
> 4. source /root/miniconda3/bin/activate
> 5. conda create --name secretflow python==3.8.13
> 6. conda activate secretflow
> 7. pip install secretflow
>    以上均顺利完成。
> 
> 你们也可以试试用上述方法执行。

按照这个方法，安装成功，但是在import的时候显示未安装该包

**Comment by luckymlog** [comment]
解决
