### ISSUE TITLE
使用docker环境运行拆分学习：银行营销教程出现问题

### ISSUE THREAD

**Issue by integrationex01** [secretflow/secretflow#794]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.0.0b3

### OS Platform and Distribution

centos7

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
from secretflow.security.privacy import DPStrategy, GaussianEmbeddingDP, LabelDP
ImportError: cannot import name 'GaussianEmbeddingDP' from 'secretflow.security.privacy' (/usr/local/lib/python3.8/site-packages/secretflow/security/privacy/__init__.py)
```

### Reproduction code to reproduce the issue.

```shell
# 教程代码在运行到此处时报错
from secretflow.security.privacy import DPStrategy, GaussianEmbeddingDP, LabelDP
```

**Comment by Chrisdehe** [comment]
@integrationex01 
我们复现一下

**Comment by integrationex01** [comment]
@Chrisdehe 在0.8.2b3上运行好像是没有太大问题的。

**Comment by Chrisdehe** [comment]
可以更新到最新版本secretflow 1.0.0b3

**Comment by zhangxingmeng** [comment]
位置变了,先按照位置以下修改吧，文档稍后更新
```python
from secretflow.security.privacy.mechanism.tensorflow import GaussianEmbeddingDP
from secretflow.security.privacy.mechanism.torch import GaussianEmbeddingDP
from secretflow.security.privacy import DPStrategy, LabelDP
```

**Comment by integrationex01** [comment]
@zhangxingmeng 请问是文档已经更新了吗？按照现在文档上的来就行了吧

**Comment by zhangxingmeng** [comment]
是的，你按照这里的教程跑就行了，https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing
有问题欢迎反馈

**Comment by zhangxingmeng** [comment]
请问还有问题吗？
