### ISSUE TITLE
隐私sql 使用文档

### ISSUE THREAD

**Issue by chengY666** [secretflow/secretflow#8]
目前看隐语的架构有支持sql 方式进行安全聚合分析，请问有相关例子和文档吗

**Comment by pchyuan** [comment]
sql方式的安全聚合分析目前还没发布，一旦发布，我们会及时同步，敬请期待

**Comment by thirtyking** [comment]
SQL的开源工作我们正在紧张进行，因为涉及比较多的剥离和重构工作，预期会在明年初开源。
9月份我们将会上线隐语功能体验平台，上面会提供与未来开源功能基本一致的SQL功能，大家可以申请试用^_^
