### ISSUE TITLE
请问是否有乘法、减法、除法、方差、中位数的例子

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#80]
请问是否有乘法、减法、除法、方差、中位数的例子

**Comment by zhouaihui** [comment]
可以补充下问题描述吗？比如是针对什么场景对数据做哪些计算？

**Comment by icavan** [comment]
> 请问是否有乘法、减法、除法、方差、中位数的例子

BTW we suggest you use existing DataFrame APIs if that works for you. Check https://secretflow.readthedocs.io/en/latest/tutorial/DataFrame.html (say the min & max)
https://secretflow.readthedocs.io/en/latest/tutorial/Preprocessing.html

These APIs will optimize for `vertical` & `horizontal` inputs. They try to put computation in local as much as possible, thus you could reduce the `joint mpc` routines.

**Comment by xpdgit** [comment]
你好，有可以在密文上比较大小的例子吗？

**Comment by 6fj** [comment]
Hi @xpdgit ,

Please check reply from @icavan :

**Comment by 6fj** [comment]
> > 请问是否有乘法、减法、除法、方差、中位数的例子
> 
> If you are trying to find out how to do basic math operations in SecretFlow, the following link might help. Secretflow's SPU aims to provide a standard numpy interface. You could try to replace `jnp.add` with `jnp.multiply` to get a secret multiplication demo.
> 
> https://spu.readthedocs.io/en/beta/getting_started/tutorials/spu_inside.html#Simulation
> 
> BTW, `k-th element` requires something like `sorting` or a specific `k-th element` building block. You might need to wait for a future secretflow version since we're still working on that.

Hi @xpdgit ,

Please check this reply from @icavan

**Comment by 6fj** [comment]
And also check this blog: https://github.com/secretflow/secretflow/discussions/49

**Comment by data-alexpan** [comment]
> And also check this blog: #49

请问有针对逻辑回归多分类问题有案例吗？

**Comment by 6fj** [comment]
> > And also check this blog: #49
> 
> 请问有针对逻辑回归多分类问题有案例吗？

Hi @data-alexpan ,

Please open another issue or reopen your previous #83.

Thanks.
