### ISSUE TITLE
如何使用GPU加速

### ISSUE THREAD

**Issue by huyz1117** [secretflow/secretflow#804]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 0.8.1b0

### OS Platform and Distribution

Centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在复现[水平联邦：图像分类](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)教程时，报了一个关于gpu的错误：`failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`，但是在运行单方模型代码时则可以正常使用gpu训练，请问如何解决
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by zhangxingmeng** [comment]
正在开发支持中，下一期更新会带出来。欢迎持续关注

**Comment by Mingbo-Lee** [comment]
- 除上述提及的问题以外，GPU加速需要特定的环境支持，目前我们提供了基于Docker容器的GPU加速思路：
https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation#gpus-support， 不过你说单方加速是可以的，说明环境没问题
- 目前基于TensorFlow的FL实现是可以使用GPU加速的，PyTorch的加速，楼上的同学还在开发
- > failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

这里的日志输出，可能有点问题，建议你使用`nvidia-smi`看一下显存占用情况。

**Comment by zhangxingmeng** [comment]
> * 除上述提及的问题以外，GPU加速需要特定的环境支持，目前我们提供了基于Docker容器的GPU加速思路：
>   [https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation#gpus-support，](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation#gpus-support%EF%BC%8C) 不过你说单方加速是可以的，说明环境没问题
> * 目前基于TensorFlow的FL实现是可以使用GPU加速的，PyTorch的加速，楼上的同学还在开发
> * > failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
> 
> 这里的日志输出，可能有点问题，建议你使用`nvidia-smi`看一下显存占用情况。

在sf的proxy要增加一个字段来分配gpu资源，在内部才能够真正使用到gpu，后续pr会带出来

**Comment by Mingbo-Lee** [comment]
好的，感谢 @zhangxingmeng 的回复；注意休息，恢复好身体。
