### ISSUE TITLE
sl的模型和数据格式问题

### ISSUE THREAD

**Issue by dongdongzhaoUP** [secretflow/secretflow#818]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.0.0b3

### OS Platform and Distribution

Centos7

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
当尝试使用sl的torch版本的backend实现拆分学习：银行营销的demo时https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing，在执行history = sl_model.fit（）后报错RuntimeError: mat1 and mat2 must have the same dtype，发现base_model的参数是float32类型，提供的训练数据是float64类型，且没有找到能够将数据的dtype统一的方法，请问如何解决？
```

### Reproduction code to reproduce the issue.

```shell
通过torch版本的backend定义的部分模型如下：
class fusemodel(BaseModule):
    def __init__(self):
        super(fusemodel,self).__init__()
        self.layer1=nn.Linear(in_features=128,out_features=64)
        self.layer2=nn.ReLU()
        self.layer3=nn.Linear(64,1)
        self.layer4=nn.Sigmoid()
    def forward(self, x):
        x=self.layer1(x)
        x=self.layer2(x)
        x=self.layer3(x)
        out=self.layer4(x)
        return out
fuse_model = TorchModel(
    model_fn=fusemodel,
    loss_fn=loss_fn,
    optim_fn=optim_fn,
    metrics=[
        metric_wrapper(
            Accuracy, task="multiclass", num_classes=2, average='micro'
        ),
        metric_wrapper(
            Precision, task="multiclass", num_classes=2, average='micro'
        ),
        metric_wrapper(AUROC, task="multiclass", num_classes=2),
    ],
)
```

**Comment by zhangxingmeng** [comment]
赞，很好的尝试，把你的完整代码发出来吧，我帮你改改

**Comment by dongdongzhaoUP** [comment]
感谢您的回复！我把我粗略的代码上传附件了（ipynb），其中使用的是原tf版本的主要框架进行修改的，请指教
[bank_test.zip](https://github.com/secretflow/secretflow/files/12341006/bank_test.zip)

**Comment by dongdongzhaoUP** [comment]
> 请问您最近有时间处理这个问题吗

**Comment by zhangxingmeng** [comment]
[bank_test_fix.ipynb.zip](https://github.com/secretflow/secretflow/files/12495199/bank_test_fix.ipynb.zip)
代码我已经修复，主要是有几个问题：
1、两个mat的类型不一致，这是因为模型参数是float32，而读进来的数据是float64导致的，解决方法就是对FedDataFrame执行astype转一下就好。
2、random_seed报错是因为，你使用的shuffle数据集，但是没有传random_seed,需要在构建SLModel的时候传入randomseed。
3、指标报错是因为，你这里是BCE，是二分类，但是使用了多分类，导致维度不匹配。

**Comment by dongdongzhaoUP** [comment]
> [bank_test_fix.ipynb.zip](https://github.com/secretflow/secretflow/files/12495199/bank_test_fix.ipynb.zip) 代码我已经修复，主要是有几个问题： 1、两个mat的类型不一致，这是因为模型参数是float32，而读进来的数据是float64导致的，解决方法就是对FedDataFrame执行astype转一下就好。 2、random_seed报错是因为，你使用的shuffle数据集，但是没有传random_seed,需要在构建SLModel的时候传入randomseed。 3、指标报错是因为，你这里是BCE，是二分类，但是使用了多分类，导致维度不匹配。

@zhangxingmeng 您好，您上传的bank_test_fix.ipynb.zip文件好像是我之前传的有问题的代码，是不是选错了

**Comment by zhangxingmeng** [comment]
[bank_test.ipynb.zip](https://github.com/secretflow/secretflow/files/12679884/bank_test.ipynb.zip)
看看这个对不对

**Comment by dongdongzhaoUP** [comment]
> [bank_test.ipynb.zip](https://github.com/secretflow/secretflow/files/12679884/bank_test.ipynb.zip) 看看这个对不对

这个文件还是我之前上传的哈哈

**Comment by dongdongzhaoUP** [comment]
> [bank_test_fix.ipynb.zip](https://github.com/secretflow/secretflow/files/12495199/bank_test_fix.ipynb.zip) 代码我已经修复，主要是有几个问题： 1、两个mat的类型不一致，这是因为模型参数是float32，而读进来的数据是float64导致的，解决方法就是对FedDataFrame执行astype转一下就好。 2、random_seed报错是因为，你使用的shuffle数据集，但是没有传random_seed,需要在构建SLModel的时候传入randomseed。 3、指标报错是因为，你这里是BCE，是二分类，但是使用了多分类，导致维度不匹配。

我在修改这三点之后碰到的报错问题是：
File [~/anaconda3/envs/sf-new/lib/python3.8/site-packages/secretflow/ml/nn/sl/sl_model.py:400](https://vscode-remote+ssh-002dremote-002bzizhubaka.vscode-resource.vscode-cdn.net/home/zhd/sf/bank_demo/~/anaconda3/envs/sf-new/lib/python3.8/site-packages/secretflow/ml/nn/sl/sl_model.py:400), in SLModel.fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_data, shuffle, sample_weight, validation_freq, dp_spent_step_freq, dataset_builder, audit_log_dir, audit_log_params, random_seed)
    394     skip_gradient = reveal(
    395         self._workers[self.device_y].get_skip_gradient()
    396     )
    398 if not skip_gradient:
    399     # do agglayer backward
--> 400     scatter_gradients = self.agglayer.backward(gradients)
    401     for device, worker in self._workers.items():
    402         if device in scatter_gradients.keys():

File [~/anaconda3/envs/sf-new/lib/python3.8/site-packages/secretflow/ml/nn/sl/agglayer/agg_layer.py:490](https://vscode-remote+ssh-002dremote-002bzizhubaka.vscode-resource.vscode-cdn.net/home/zhd/sf/bank_demo/~/anaconda3/envs/sf-new/lib/python3.8/site-packages/secretflow/ml/nn/sl/agglayer/agg_layer.py:490), in AggLayer.backward(self, gradient, weights)
    482     gradient = self.device_y(self.compress_gradients)(
...
  File "/home/zhd/anaconda3/envs/sf-new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhd/anaconda3/envs/sf-new/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not list

**Comment by zhangxingmeng** [comment]
[bank_test_new.ipynb.zip](https://github.com/secretflow/secretflow/files/12680965/bank_test_new.ipynb.zip)
抱歉，这个应该是对的，时间有点久了。。
