### ISSUE TITLE
sl的torch版本demo

### ISSUE THREAD

**Issue by dongdongzhaoUP** [secretflow/secretflow#819]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

1.0.0b3

### OS Platform and Distribution

Centos7

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
能否给出一个sl的torch版本的demo（比如使用torch的backend实现拆分学习：银行营销https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Split_Learning_for_bank_marketing）
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by zhangxingmeng** [comment]
可以的，感兴趣的话，我们可以一起来写这个教程。

**Comment by dongdongzhaoUP** [comment]
非常荣幸，与有荣焉

**Comment by zhangzp9970** [comment]
我也遇到了相同的问题，我自己把文档里tensorflow的改写成了pytorch的，但运行不了。这里是我的代码。 #846 
请问你这个问题有解决吗？ @dongdongzhaoUP

**Comment by zhangxingmeng** [comment]
先参考一下单测里面的写法，bank_test我下载了，在处理中了
参考文件：https://github.com/secretflow/secretflow/blob/main/tests/ml/nn/test_sl_model_torch.py

**Comment by zhangxingmeng** [comment]
我在你两外一个pr回复了，代码已修复，你可以查看下，然后尝试写一个tutorial吧。
有一个很好的实践经验，供参考
**先写单机程序，跑通之后，再迁移到联邦框架中，会避免很多不必要的问题**

**Comment by zhangxingmeng** [comment]
> 我也遇到了相同的问题，我自己把文档里tensorflow的改写成了pytorch的，但运行不了。这里是我的代码。 #846 请问你这个问题有解决吗？ @dongdongzhaoUP

https://github.com/secretflow/secretflow/issues/818
看一看看这个pr里的回复

**Comment by zhangzp9970** [comment]
@zhangxingmeng  好的，我正在研究。如果有问题再联系您。

**Comment by dongdongzhaoUP** [comment]
> 我在你两外一个pr回复了，代码已修复，你可以查看下，然后尝试写一个tutorial吧。 有一个很好的实践经验，供参考 **先写单机程序，跑通之后，再迁移到联邦框架中，会避免很多不必要的问题**

感谢，我尽快尝试整理一个tutorial
