### ISSUE TITLE
SLModel是否支持Naive SplitNN架构

### ISSUE THREAD

**Issue by Zhangky11** [secretflow/secretflow#829]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow1.0.0b3

### OS Platform and Distribution

Linux Ubuntu 20.04.2

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
SecretFlow目前的API是否支持Naive的SplitNN架构？即client端接收全部的输入，server端持有标签。
如果支持的话，是否有demo可以参考
```

### Reproduction code to reproduce the issue.

```shell
none
```

**Comment by zhangxingmeng** [comment]
你说的是一方特征一方标签吗？支持的

**Comment by Zhangky11** [comment]
是的 那请问tensorflow版是否有demo可以参考？或者说简单的说明

**Comment by zhangxingmeng** [comment]
![image](https://github.com/secretflow/secretflow/assets/103552200/9042bed6-29d1-4bc5-b70a-b52abbf03f8c)
你只需要在base_model_dict的时候把没有特征的那一方不提供就可以了

**Comment by Zhangky11** [comment]
但是我在划分data并且训练的过程中仍然会出现问题
![32c9ebf1f0696cf0be82e88d400f73b](https://github.com/secretflow/secretflow/assets/79576162/e1720fd1-0ae8-4862-8033-77140365547b)
![832c3dabfb8d51c912ef33727aabe6d](https://github.com/secretflow/secretflow/assets/79576162/6881069d-50cc-4150-a841-aa8a8fcc79bf)
