### ISSUE TITLE
请问Secretflow支持三方以上的多方vertical MPC XGB吗

### ISSUE THREAD

**Issue by hustmf** [secretflow/secretflow#832]
MPC-XGB 的demo是三方版本https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/user_guide/mpc_ml/decision_tree
以及这个版本是否并未用到Large-Scale Secure XGB for Vertical Federated Learning这篇论文中提到的permutation优化方法？

**Comment by warriorpaw** [comment]
MPC-XGB计算时支持多少方，依赖于底层的协议，demo中使用的ABY3协议所以只能支持3方计算。更换使用SEMI2K协议可以支持N>=2个计算方，配置在 https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config#protocolkind

但是数据提供方和计算方不一定要绑定在一起，比如在 https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/spu_basics 中，可以有2个数据提供方和3个MPC计算方。

HEP-XGB 和 CRP-XGB 需要private语意支持，目前开源sf中还没有支持。

**Comment by 6fj** [comment]
Hi @hustmf 

论文中提到的方法我们暂时不会实现。
我会先关闭这个issue，如果你有需求，烦请直接回复并说明你的诉求背景。

感谢！
