### ISSUE TITLE
SS-LR/XGB和HESS-LR/XGB 有什么区别

### ISSUE THREAD

**Issue by xiangguiwang111** [secretflow/secretflow#84]
### Issue Type

Documentation Bug

### Source

source

### Secretflow Version

0.6.13

### OS Platform and Distribution

Ubuntu18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
SS-LR/XGB和HESS-LR/XGB 有什么区别
```

### Reproduction code to reproduce the issue.

```shell
SS-LR/XGB和HESS-LR/XGB 有什么区别
```

**Comment by warriorpaw** [comment]
sslr 使用secret sharing 求解梯度下降方向， ssxgb使用secret sharing 求样本分桶梯度加和。而 hess lr/xgb 使用同态加密进行上述操作。 

secret sharing对带宽和延迟比较敏感，而同态加密方案会消耗更多的cpu算力。 是一种针对不同运算环境的折中：局域网/万兆环境下ss能更快的完成建模，带宽受限且延迟较高的公网环境可以用he提高建模速度 。 

其他部分运算逻辑和算法的安全设定基本一致。
