### ISSUE TITLE
pis与pir双方交互流程图

### ISSUE THREAD

**Issue by dyx0001** [secretflow/secretflow#849]
老师好，目前我们已经跑通了基于ECDH_PSI_2PC的两方psi以及基于ECDH_PSI_3PC的三方psi，还有匿踪查询，已经通过隐语技术支持获取的底层的实现逻辑，但是这个逻辑过于底层整个交互过程还是不太清楚，是否可以给一版这几个模型参与方之间交互的流程图以及交互过程中用到的隐私计算技术。我这里试着画了一份大概的但是不太清楚具体的细节，是否可以补充一下？
![image](https://github.com/secretflow/secretflow/assets/132547242/31a5eadb-2b15-427d-bb73-51e408f6348b)

**Comment by icavan** [comment]
不同的算法其流程交互是不一样的，如果是 ECDH 2方 PSI 的话，可以参考白盒互联互通里的算法流程图和步骤 https://github.com/secretflow/interconnection/blob/main/PPCA/open-protocols/ECDH-PSI.pdf

**Comment by icavan** [comment]
其他的算法都要单独看的，官网其实有大致描述原理，可以参考 https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/user_guide/psi 了解 highlevel 原理，但细到每个交互流程要详细列出，那目前除了已经做了白盒互联互通的算法外，并没有现成的材料。

方便说一下您的具体场景和需求是什么，需要到什么粒度的交互细节，为什么需要？
