### ISSUE TITLE
logo 在 retinal 屏显示模糊，可以直接嵌入 svg 格式的 logo

### ISSUE THREAD

**Issue by bubkoo** [secretflow/secretflow#85]
### Issue Type

Documentation Feature Request

### Source

source

### Secretflow Version

latest

### OS Platform and Distribution

max os

### Python version

3.8

### What happend and What you expected to happen.

```shell
logo 显示模糊
```

### Reproduction code to reproduce the issue.

```shell
在 macos 的 readme 中可以直接复现
```

**Comment by bubkoo** [comment]
如果 svg 源文件不能开源，可以导出 @2x 大小的 png 图片。

**Comment by 6fj** [comment]
Hi @bubkoo ,

Your attention is appreciated. Putting a svg is a good idea here.
