### ISSUE TITLE
关于pis、pir的实现流程

### ISSUE THREAD

**Issue by dyx0001** [secretflow/secretflow#850]
老师好，目前我们已经跑通了基于ECDH_PSI_2PC的两方psi以及基于ECDH_PSI_3PC的三方psi，还有匿踪查询，且已经通过隐语技术支持获取的底层的实现逻辑，但是这个逻辑过于底层整个交互过程还是不太清楚，是否可以给一版这几个模型参与方之间交互的流程图以及交互过程中用到的隐私计算技术。我这里试着画了一份大概的但是不太清楚具体的细节，是否可以补充一下？
![image](https://github.com/secretflow/secretflow/assets/132547242/360240c5-97b8-48cf-bc3b-32e9424a38c4)

**Comment by 6fj** [comment]
Hi @dyx0001 

大体上没有问题，请问你哪一块不清楚细节呢？
