### ISSUE TITLE
python版本

### ISSUE THREAD

**Issue by ceasona** [secretflow/secretflow#852]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.0.0b3

### OS Platform and Distribution

linux

### Python version

3.8.12

### What happend and What you expected to happen.

```shell
你好，请问为啥只支持python3.8呀
```

### Reproduction code to reproduce the issue.

```shell
Environment
Python：3.8

pip: >= 19.3

OS: CentOS 7, Ubuntu 18.04

CPU/Memory: recommended minimum requirement is 8C16G.
```

**Comment by 6fj** [comment]
Hi @ceasona 

我们目前只测试过python3.8，没有其他特殊的原因。

**Comment by zhouaihui** [comment]
hi， @ceasona ， 你这边对python版本有什么需求吗？

**Comment by ceasona** [comment]
> hi， @ceasona ， 你这边对python版本有什么需求吗？

谢谢你的回复，暂时没有特别的需求
