### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Niyci** [secretflow/secretflow#853]
通过pypi安装secretflow
![lQDPJwFCuBnmzozNAtDNBQCwsEJaPaT4PzgE4W2-OgBTAA_1280_720](https://github.com/secretflow/secretflow/assets/87159755/7e7c779b-bcaf-482f-8a82-fd7f6aaf9975)

**Comment by Niyci** [comment]
尝试运行快速开始，报的问题

**Comment by anakinxc** [comment]
Hi @Niyci 

请确保你的 CPU 支持 AVX

**Comment by Niyci** [comment]
这个要看cpu型号，虚拟机与宿主机的cpu是一样的是吧

**Comment by Niyci** [comment]
英特尔w5-3425  CPU（≥12核心，≥4.6GHz睿频） 这个cpu是不行的对吧

**Comment by anakinxc** [comment]
你在虚拟机里看一下 cpuinfo
