### ISSUE TITLE
[keras]在 SecretFlow 中实现水平联邦目标识别 example

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#856]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741) https://github.com/secretflow/secretflow/issues/746 子任务，若对该任务感兴趣，欢迎在 https://github.com/secretflow/secretflow/issues/746 提交你的不同设计思路。
> 
> 也欢迎其他开发者点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择其他你感兴趣的任务，热烈欢迎社区开发者参与共建～

## 设计思路

by [Mingbo-Lee](https://github.com/Mingbo-Lee)

基于 https://keras.io/examples/vision/object_detection_using_vision_transformer/#object-detection-with-vision-transformers 为例改写成隐语的联邦学习教程，体现隐语对 keras example的兼容，充分展现隐语的易用性和兼容性
- 数据分割：按照参与方均匀分割
- 模型: [Vision Transformer (ViT)](https://arxiv.org/abs/2010.11929)
- 数据集：[Caltech 101 dataset](http://www.vision.caltech.edu/datasets/)
- 联邦策略：充分对齐隐语现有API，只要隐语支持的，理论上都可以支持

## 任务介绍

- 任务名称：在 SecretFlow 中实现水平联邦目标识别 example
- 技术方向：联邦学习和人工智能
- 任务难度：进阶🌟🌟

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 实现任意一种目标检测方法
  - 提供联邦数据集拆分的逻辑
  - 提交 tutorial，example 代码，数据下载，拆分和预处理代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，最好有与明文结果（PyTorch 或者 TensorFlow）的对比
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码 https://github.com/secretflow/secretflow/tree/main/examples/app/h_cv/object_detection
  - 整理完整实现过程为文档 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
 
## 能力要求
- 熟悉目标检测相关技术，包括但不限于 R-CNN，SSD，YOLO 等
- 熟悉 TensorFlow 或者 PyTorch

## 操作说明
- 操作指引：具体操作可参考[操作指引](https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation/deep_fm)进行
- 参考内容：
  - [数据读取](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)
  - [数据预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
  - [联邦模型开发教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)

**Comment by Mingbo-Lee** [comment]
Mingbo-Lee Give it to me

**Comment by Mingbo-Lee** [comment]
目前我已经实现整个过程，已经把数据集加载成TensorFlow的BatchDataset的形式，并且同样的数据集在明文状态下可以直接运行，具体可以看先提交的部分PR，但是封装成FL支持的DataLoader是出现报错

**Comment by zhangxingmeng** [comment]
> 目前我已经实现整个过程，已经把数据集加载成TensorFlow的BatchDataset的形式，并且同样的数据集在明文状态下可以直接运行，具体可以看先提交的部分PR，但是封装成FL支持的DataLoader是出现报错

报错是什么呀？可以发出来看下

**Comment by Mingbo-Lee** [comment]
可以看 这里  https://github.com/Mingbo-Lee/secretflow/blob/detect/docs/tutorial/Object%20detection%20with%20Vision%20Transformers.ipynb
