### ISSUE TITLE
集群模式中的ip和端口的含义

### ISSUE THREAD

**Issue by hust-suwb** [secretflow/secretflow#86]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.6.13b1

### OS Platform and Distribution

Debian 11

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
启动一个隐语的计算集群，涉及到好几处的ip和端口。

ray start --head --node-ip-address="ip_1" --port="port_1" 
ray start --address="ip_1:port_1" --node-ip-address="ip_2"

cluster_def = {
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': 'ip_3:port_3'},
        {'party': 'bob', 'id': 'local:1', 'address': 'ip_4:port_4'},
    ],
    'runtime_config': {...}
}

sf.init(address='ip_5:port_5')
```

我有这么几个理解，不确定是否正确，求指教。
1. ip_1 和 port_1 初始化了 ray 的 master，然后 ip_2 加入了 ip_1 声明的这个集群。
2. ip_3 以及 ip_4 是声明的两个 secretflow 的节点，与 ip_1 和 ip_2 并不是强绑定关系（虽然一般情况下都是一致的）。port_3 和 port_4 是声明的两个 secretflow 节点间的通信端口，必须与 port_1 不同，同时还需要与 ray 的通信端口 8881 不同。
3. ip_5 和 port_5 指明 secretflow 去连接 ray 的集群，所以 ip_5 和 port_5 是与 ip_1 和 port_1 一致的。
```


### Reproduction code to reproduce the issue.

```shell
ray start --head --node-ip-address="ip_1" --port="port_1" 
ray start --address="ip_1:port_1" --node-ip-address="ip_2"

cluster_def = {
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': 'ip_3:port_3'},
        {'party': 'bob', 'id': 'local:1', 'address': 'ip_4:port_4'},
    ],
    'runtime_config': {...}
}

sf.init(address='ip_5:port_5')
```

**Comment by zhouaihui** [comment]
是的，你的理解是对的，解释的非常清楚。

一点点小的改进：`同时还需要与 ray 的通信端口 8881 不同`，其实本质上是使用未被占用的端口以免端口冲突。

**Comment by hust-suwb** [comment]
> 是的，你的理解是对的，解释的非常清楚。
> 
> 一点点小的改进：`同时还需要与 ray 的通信端口 8881 不同`，其实本质上是使用未被占用的端口以免端口冲突。

了解了，多谢。
