### ISSUE TITLE
This model(logic regression) support multi-classification?

### ISSUE THREAD

**Issue by Bio-Gas** [secretflow/secretflow#87]
Did this model(logic regression) support multi-classification? i try some multi-classification datasets but it didn't work.

_Originally posted by @data-alexpan in https://github.com/secretflow/secretflow/issues/83#issuecomment-1214507569_

**Comment by rivertalk** [comment]
Hi ~

Could you provide more detailed model information and error message?

Have a nice day.

**Comment by data-alexpan** [comment]
Sure, i just replace the input dataset from original to iris dataset(3 classes), then when i rerun the model,i got some errors

**Comment by 6fj** [comment]
Hi @data-alexpan,

We need the code and detailed outputs from your run in order to understand what has happened.

Thanks.
