### ISSUE TITLE
psi两个函数的使用问题

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/secretflow#873]
psi_csv和psi_join_csv两个函数的区别是什么，分别在什么情况下使用
      
 def psi_csv(
        self,
        key: Union[str, List[str]],
        input_path: str,
        output_path: str,
        receiver: str,
        protocol='KKRT_PSI_2PC',
        precheck_input=True,
        sort=True,
        broadcast_result=True,
        bucket_size=1 << 20,
        curve_type="CURVE_25519",
        preprocess_path=None,
        ecdh_secret_key_path=None,
        dppsi_bob_sub_sampling=0.9,
        dppsi_epsilon=3,
        ic_mode: bool = False,
    ):

 def psi_join_csv(
        self,
        key: Union[str, List[str]],
        input_path: str,
        output_path: str,
        receiver: str,
        join_party: str,
        protocol='KKRT_PSI_2PC',
        bucket_size=1 << 20,
        curve_type="CURVE_25519",
        ic_mode: bool = False,
    ):

**Comment by Chrisdehe** [comment]
hi,@daydayuphere 
psi_csv 要求输入的数据没有重复项，已经做了去重处理
psi_join_csv 输入数据可以有重复项，得到交集结果后还会根据膨胀项进行膨胀，类似数据库的inner join
