### ISSUE TITLE
slmodel训练acc损失过高

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#878]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.1.0.dev20230828

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
在学习了SLmodel的例子之后，自己构建了一个基于DNN的简单多分类算法，此时报了一个ValueError,如下：
ValueError: Except for binary classification, inputs only support onehot form.
在查看错误的时候最终定位到了DPStrategy部分的LabelDP部分，是不是表示SLmodel并不能支持多分类？看XGB和逻辑回归也标注了只支持回归和二分类。
如果都不支持二分类，那么纵向多分类的算法该如何完成。
```

### Reproduction code to reproduce the issue.

```shell
仿真环境代码如下：
import pandas as pd
import secretflow as sf
from secretflow.data.split import train_test_split
from secretflow.data.vertical import read_csv as v_read_csv
from secretflow.ml.nn import SLModel
from secretflow.security.privacy import DPStrategy, LabelDP
from secretflow.security.privacy.mechanism.tensorflow import GaussianEmbeddingDP
from sklearn.datasets import load_iris
from tensorflow import keras
from tensorflow.keras import layers

iris = load_iris()
X = iris.data
y = iris.target

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df[["petal length (cm)", "petal width (cm)", "target"]].to_csv('iris_dataset_alice.csv', index=False)
iris_df[["sepal length (cm)", "sepal width (cm)"]].to_csv('iris_dataset_bob.csv', index=False)

sf.init(['alice', 'bob'], address='local')
alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

data = v_read_csv({
    alice: "./iris_dataset_alice.csv",
    bob: "./iris_dataset_bob.csv"
})

label = data["target"]
data = data.drop(columns=["target"])

random_state = 1234
train_data, test_data = train_test_split(
    data, train_size=0.8, random_state=random_state
)
train_label, test_label = train_test_split(
    label, train_size=0.8, random_state=random_state
)


# 基础模型，包含两层
def create_base_model(input_dim, output_dim, name="base_model"):
    def create_model():
        model = keras.Sequential(
            [
                keras.Input(shape=input_dim),
                keras.layers.Dense(output_dim, activation='relu')
            ]
        )
        model.summary()
        model.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])
        return model

    return create_model


# prepare model
hidden_size = 128

model_base_alice = create_base_model(2, hidden_size)
model_base_bob = create_base_model(2, hidden_size)


# 定义有label的一方，或者server端的模型——fuse_model
def create_fuse_model(input_dim, output_dim, party_numbers, name="fuze_model"):
    def create_model():
        # input
        input_layers = []
        for i in range(party_numbers):
            input_layers.append(
                keras.Input(input_dim)
            )
        merged_layer = layers.concatenate(input_layers)
        fuze_layer = layers.Dense(64, activation='relu')(merged_layer)
        output = layers.Dense(output_dim, activation='softmax')(fuze_layer)

        model = keras.Model(inputs=input_layers, outputs=output)
        model.summary()

        model.compile(
            loss='sparse_categorical_crossentropy',
            optimizer='adam',
            metrics=["accuracy"],
        )
        return model

    return create_model


data_label = sf.reveal(label.partitions[alice].data)
model_fuse = create_fuse_model(input_dim=hidden_size, party_numbers=2, output_dim=len(data_label["target"].unique()))

base_model_dict = {alice: model_base_alice, bob: model_base_bob}

# Define DP operations
train_batch_size = 128
gaussian_embedding_dp = GaussianEmbeddingDP(
    noise_multiplier=0.5,
    l2_norm_clip=1.0,
    batch_size=train_batch_size,
    num_samples=train_data.values.partition_shape()[alice][0],
    is_secure_generator=False,
)
label_dp = LabelDP(eps=64.0)
dp_strategy_alice = DPStrategy(label_dp=label_dp)
dp_strategy_bob = DPStrategy(embedding_dp=gaussian_embedding_dp)
dp_strategy_dict = {alice: dp_strategy_alice, bob: dp_strategy_bob}
dp_spent_step_freq = 10

sl_model = SLModel(
    base_model_dict=base_model_dict,
    device_y=alice,
    model_fuse=model_fuse,
    dp_strategy_dict=dp_strategy_dict,
)

print(sf.reveal(test_data.partitions[alice].data), sf.reveal(
    test_label.partitions[alice].data
))

print(sf.reveal(train_data.partitions[bob].data))
print("****************************************************")
history = sl_model.fit(
    train_data,
    train_label,
    validation_data=(test_data, test_label),
    epochs=10,
    batch_size=train_batch_size,
    shuffle=True,
    verbose=1,
    validation_freq=1,
    dp_spent_step_freq=dp_spent_step_freq,
)
```

**Comment by Niclouge** [comment]
仔细看了参数说明，发现可以不用差分隐私的参数，在去除差分隐私参数之后程序运行成功。
但是不加差分隐私参数，如何保证安全？看代码中并没有使用到SPU或者HEU参与计算。

**Comment by zhangxingmeng** [comment]
建议在使用SLModel之前，先把模型在明文下跑通。这样可以避免很多麻烦。
sparse_categorical_crossentropy的loss 函数，需要label 是onehot形式的，
如果是0或者1，那么请使用binary_crossentropy

**Comment by Niclouge** [comment]
采用拆分学习和完整模型训练对比之后发现准确度损失较高，是否正常？

在上述代码中去除差分参数之后，可以完成训练，训练过程如下所示：
100%|██████████| 1/1 [00:02<00:00,  2.79s/it, epoch: 1/10 -  train_loss:1.1483467817306519  train_accuracy:0.3083333373069763  val_loss:1.0772051811218262  val_accuracy:0.30000001192092896 ]
100%|██████████| 1/1 [00:00<00:00, 27.04it/s, epoch: 2/10 -  train_loss:1.0807273387908936  train_accuracy:0.36666667461395264  val_loss:1.0654195547103882  val_accuracy:0.2666666805744171 ]
100%|██████████| 1/1 [00:00<00:00, 30.47it/s, epoch: 3/10 -  train_loss:1.038149356842041  train_accuracy:0.3499999940395355  val_loss:1.057995319366455  val_accuracy:0.2666666805744171 ]
100%|██████████| 1/1 [00:00<00:00, 20.68it/s, epoch: 4/10 -  train_loss:1.0100301504135132  train_accuracy:0.3499999940395355  val_loss:1.0426708459854126  val_accuracy:0.30000001192092896 ]
100%|██████████| 1/1 [00:00<00:00, 24.09it/s, epoch: 5/10 -  train_loss:0.9841050505638123  train_accuracy:0.40833333134651184  val_loss:1.01884925365448  val_accuracy:0.5333333611488342 ]
100%|██████████| 1/1 [00:00<00:00, 22.52it/s, epoch: 6/10 -  train_loss:0.9572676420211792  train_accuracy:0.6583333611488342  val_loss:0.9857665300369263  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 26.43it/s, epoch: 7/10 -  train_loss:0.9279249906539917  train_accuracy:0.6916666626930237  val_loss:0.95042484998703  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 28.94it/s, epoch: 8/10 -  train_loss:0.8998053073883057  train_accuracy:0.6916666626930237  val_loss:0.9164953231811523  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 25.31it/s, epoch: 9/10 -  train_loss:0.8740797638893127  train_accuracy:0.6916666626930237  val_loss:0.8862411379814148  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 21.93it/s, epoch: 10/10 -  train_loss:0.8513377904891968  train_accuracy:0.6916666626930237  val_loss:0.8605316877365112  val_accuracy:0.5666666626930237 ]
Evaluate Processing:: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s, loss:0.8605316877365112 accuracy:0.5666666626930237]
对测试数据集计算准确度，结果如下：
**{'loss': 0.8605317, 'accuracy': 0.56666666}**

**完整模型训练代码如下**
# 准备数据，假设X是特征矩阵，y是标签
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 输入维度和类别数量
input_dim = X_train.shape[1]
num_classes = len(np.unique(y_train))
# 构建深度神经网络模型
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_dim=input_dim),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(num_classes, activation='softmax')
])
# 编译模型
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 训练模型
epochs = 10
batch_size = 128
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2)
# 评估模型
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")

采用完整的数据集并且完整的模型计算结果如下：
Epoch 1/10
1/1 [==============================] - 1s 504ms/step - loss: 1.2281 - accuracy: 0.3333 - val_loss: 1.1217 - val_accuracy: 0.5417
Epoch 2/10
1/1 [==============================] - 0s 18ms/step - loss: 1.1719 - accuracy: 0.4062 - val_loss: 1.0730 - val_accuracy: 0.6667
Epoch 3/10
1/1 [==============================] - 0s 17ms/step - loss: 1.1184 - accuracy: 0.4271 - val_loss: 1.0269 - val_accuracy: 0.6667
Epoch 4/10
1/1 [==============================] - 0s 18ms/step - loss: 1.0675 - accuracy: 0.4271 - val_loss: 0.9837 - val_accuracy: 0.7500
Epoch 5/10
1/1 [==============================] - 0s 18ms/step - loss: 1.0192 - accuracy: 0.5000 - val_loss: 0.9430 - val_accuracy: 0.8333
Epoch 6/10
1/1 [==============================] - 0s 30ms/step - loss: 0.9738 - accuracy: 0.6771 - val_loss: 0.9046 - val_accuracy: 0.8750
Epoch 7/10
1/1 [==============================] - 0s 52ms/step - loss: 0.9314 - accuracy: 0.7604 - val_loss: 0.8684 - val_accuracy: 0.8750
Epoch 8/10
1/1 [==============================] - 0s 27ms/step - loss: 0.8917 - accuracy: 0.7812 - val_loss: 0.8346 - val_accuracy: 0.8750
Epoch 9/10
1/1 [==============================] - 0s 25ms/step - loss: 0.8544 - accuracy: 0.7812 - val_loss: 0.8032 - val_accuracy: 0.8750
Epoch 10/10
1/1 [==============================] - 0s 19ms/step - loss: 0.8196 - accuracy: 0.7812 - val_loss: 0.7737 - val_accuracy: 0.8750
测试数据集的准备读如下所示：
Test accuracy: 0.9000

**Comment by Niclouge** [comment]
> 建议在使用SLModel之前，先把模型在明文下跑通。这样可以避免很多麻烦。 sparse_categorical_crossentropy的loss 函数，需要label 是onehot形式的， 如果是0或者1，那么请使用binary_crossentropy，同时将最后一层激活函数改成sigmoid。

好的。

还有最后一个问题，上述代码中slmodel去掉差分参数之后能够运行，安全性该如何体现？

**Comment by zhangxingmeng** [comment]
> 

差分隐私只是将传输的内容进行扰动，加不加差分隐私不影响能不能跑通。
如果不加差分隐私，传输的就是原始的embedding和梯度。
如果对安全考虑比较多，可以看看agglayer模块，可以使用spu来进行安全传输聚合和梯度回传逻辑
