### ISSUE TITLE
使用猎豹协议测试2方的万次比较，需要花将近7s的时间，正常吗？

### ISSUE THREAD

**Issue by hust-suwb** [secretflow/secretflow#88]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.6.13b1

### OS Platform and Distribution

Debian 11

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
用万次比较测试了下猎豹的性能，这个时间花销看起来不太合理。

2022-08-15 14:11:25,751	WARNING services.py:2010 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 2146447360 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
dict_values([[{'party': 'alice', 'id': 'local:0', 'address': '127.0.0.1:12345'}, {'party': 'bob', 'id': 'local:1', 'address': '127.0.0.1:12346'}], {'protocol': 4, 'field': 1}])
<secretflow.device.device.pyu.PYUObject object at 0x7ff72230a400>
<secretflow.device.device.pyu.PYUObject object at 0x7ff7223212b0>
<secretflow.device.device.spu.SPUObject object at 0x7ff71a9d99d0>
<secretflow.device.device.spu.SPUObject object at 0x7ff71a9d9a90>
start at 2022-08-15 14:11:27.627
计算完成，当前时间：2022-08-15 14:11:27.630
结果解析完成，当前时间：2022-08-15 14:11:35.024
```

另外，我发现一个现象，在万次比较和万次乘法上都会出现：在执行`device(greater/multiply)(x_, y_)`之前，如果能够`time.sleep()`个几秒钟，那么耗时会减少很多。这又是为什么呢？
```
start at 2022-08-15 14:18:15.149
计算完成，当前时间：2022-08-15 14:18:15.153
结果解析完成，当前时间：2022-08-15 14:18:16.577
```
```


### Reproduction code to reproduce the issue.

```shell
sf.shutdown()

sf.init(['alice', 'bob'])
alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(cluster_def)
print(spu.cluster_def.values())

x = alice(make_rand)()
y = bob(make_rand)()
print(x)
print(y)

device = spu

x_, y_ = (
    x.to(device),
    y.to(device)
)
print(x_)
print(y_)

# time.sleep(10)

print('start at {}'.format((datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])))
res = device(greater)(x_, y_)
print('计算完成，当前时间：{}'.format((datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])))
result = sf.reveal(res)
print('结果解析完成，当前时间：{}'.format((datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])))
```

**Comment by rivertalk** [comment]
你好～ 感谢细致的提问

猎豹是一个纯两房的协议，计算过程中涉及到下层 OT/HE 的计算，速度比ABY3这类协议会慢许多。

加上 time.sleep 之后，并非耗时变少，这里原因是 secretflow 中所有的计算都是异步执行的，总耗时包含
1. Alice和 Bob 上分片的时间
2. Alice和 Bob 将数据发送到 SPU 设备的时间
3. SPU上的执行时间

加上sleep之后，1&2还是在异步执行，所以统计到总时间会变少

**Comment by hust-suwb** [comment]
> 你好～ 感谢细致的提问
> 
> 猎豹是一个纯两房的协议，计算过程中涉及到下层 OT/HE 的计算，速度比ABY3这类协议会慢许多。
> 
> 加上 time.sleep 之后，并非耗时变少，这里原因是 secretflow 中所有的计算都是异步执行的，总耗时包含
> 
> 1. Alice和 Bob 上分片的时间
> 2. Alice和 Bob 将数据发送到 SPU 设备的时间
> 3. SPU上的执行时间
> 
> 加上sleep之后，1&2还是在异步执行，所以统计到总时间会变少

那是否可以这么理解，当我加上sleep后，我碰巧统计出来了`3. SPU上的执行时间`？
另外，有什么更优雅的方式可以统计到SPU执行的时间么。

**Comment by rivertalk** [comment]
> 那是否可以这么理解，当我加上sleep后，我碰巧统计出来了3. SPU上的执行时间？

是的，如果sleep的时间够长，统计出的时间就是 步骤3的时间


> 另外，有什么更优雅的方式可以统计到SPU执行的时间么。

SPU RuntimeConfig(https://github.com/secretflow/spu/blob/a0fa436eb62a62847dcb30bf42f6713e8af3b7a0/spu/spu.proto#L184) 中有精确的统计运行时间的信息，需要在创建设备的时候将相关的flag打开

**Comment by hust-suwb** [comment]
> > 那是否可以这么理解，当我加上sleep后，我碰巧统计出来了3. SPU上的执行时间？
> 
> 是的，如果sleep的时间够长，统计出的时间就是 步骤3的时间
> 
> > 另外，有什么更优雅的方式可以统计到SPU执行的时间么。
> 
> SPU RuntimeConfig(https://github.com/secretflow/spu/blob/a0fa436eb62a62847dcb30bf42f6713e8af3b7a0/spu/spu.proto#L184) 中有精确的统计运行时间的信息，需要在创建设备的时候将相关的flag打开

我把`enable_pphlo_profile = True` 打开后，控制台也并没有输出详细的运行耗时的日志。这个是要在集群模式下去指定目录里看日志吗？

**Comment by 6fj** [comment]
Hi @hust-suwb ,

查看日志，请参考https://github.com/secretflow/secretflow/issues/70#issuecomment-1201932710。
感谢。

**Comment by hust-suwb** [comment]
> Hi @hust-suwb ,
> 
> 查看日志，请参考[#70 (comment)](https://github.com/secretflow/secretflow/issues/70#issuecomment-1201932710) 感谢。

了解，多谢。

**Comment by deadlywing** [comment]
> 你好～ 感谢细致的提问
> 
> 猎豹是一个纯两方的协议，计算过程中涉及到下层 OT/HE 的计算，速度比ABY3这类协议会慢许多。
> 
> 加上 time.sleep 之后，并非耗时变少，这里原因是 secretflow 中所有的计算都是异步执行的，总耗时包含
> 
> 1. Alice和 Bob 上分片的时间
> 2. Alice和 Bob 将数据发送到 SPU 设备的时间
> 3. SPU上的执行时间
> 
> 加上sleep之后，1&2还是在异步执行，所以统计到总时间会变少

那请问两方能使用ABY3协议么？比如让一方相当于承当了两个party的角色。这样会有安全问题吗？

**Comment by 6fj** [comment]
Hi @deadlywing ，

不能，对于ABY3协议来说，如果两方共谋将会得到全部数据信息。

按照你的假设，假设两方分别为alice和bob，alice承担了p1和p2, bob承担了p3, 那么实际上alice可以reveal所有密文，对于bob来说是不可接受的。

**Comment by deadlywing** [comment]
> Hi @deadlywing ，
> 
> 不能，对于ABY3协议来说，如果两方共谋将会得到全部数据信息。
> 
> 按照你的假设，假设两方分别为alice和bob，alice承担了p1和p2, bob承担了p3, 那么实际上alice可以reveal所有密文，对于bob来说是不可接受的。

明白了，多谢。
