### ISSUE TITLE
关于在学习SPU的示例时，运行两方协议出现问题

### ISSUE THREAD

**Issue by ShallMate** [secretflow/secretflow#882]
我直接采用的教程的两方比较大小的代码，如下:
![2023-09-13 20-49-04屏幕截图](https://github.com/secretflow/secretflow/assets/25976948/3f85169a-3c41-439f-ac5e-0ac1b4db7992)
然后出现了以下问题，麻烦能否解答一下，非常感谢～
![2023-09-13 20-49-52屏幕截图](https://github.com/secretflow/secretflow/assets/25976948/012619be-2c99-4e59-bd6f-3d14ec427109)

**Comment by 6fj** [comment]
hi @ShallMate 

从log中没有发现问题，能否提供完整的log？

**Comment by ShallMate** [comment]
@6fj 不好意思，我不是很明白您的意思，这已经是我的完整info了。我确实能够打印最终的结果。我想问的是info中的“Fail to connect”,"socket error"等错误信息难道是正常的吗？这是我第一次使用隐语，如果这是一个很愚蠢的问题请见谅。

**Comment by 6fj** [comment]
没有问题，这个阶段节点之间正在尝试建立连接。
