### ISSUE TITLE
内存持续增长问题

### ISSUE THREAD

**Issue by olivetree123** [secretflow/secretflow#884]
### 测试环境
```
Python3.8
ray==2.2.0
secretflow==0.8.2b3
secretflow-ray==2.2.0
secretflow-rayfed==0.1.1a3

Dockerfile：https://github.com/secretflow/secretflow/blob/main/docker/release/secretflow-gpu.Dockerfile
```

### 测试代码
我们运行了这个案例：https://github.com/secretflow/secretflow/blob/main/docs/tutorial/CustomDataLoaderTorch.ipynb
> 整理后的代码在这里：https://melodious-condor-d48.notion.site/CustomDataLoaderTorch-3d9145da0471424f912a5fa6625f534f

使用`memory_profiler` 定位了内存的增长情况：
```python
# Filepath: dist-packages/ray/remote_function.py

from memory_profiler import profile


@PublicAPI
class RemoteFunction:

    @_tracing_task_invocation
    @profile(stream=open("/var/log/mem.log", "w+"))
    def _remote(self, args=None, kwargs=None, **task_options):
        """Submit the remote function for execution."""
        ...
```

### 问题现象
发现`submit_task` 每次执行的时候内存都会增长：
> 在我们的测试中，该方法调用了32次，一共增长了2GB的内存

![image](https://github.com/secretflow/secretflow/assets/5275647/3a3d0cdc-d45d-4b56-a638-004b978ae95e)
![image](https://github.com/secretflow/secretflow/assets/5275647/0df6f1ee-de2a-4b32-bca8-292dda1c621f)

如果想简单一点测试，可以不用增加 `memory_profiler `，直接观察容器的内存即可

**Comment by ian-huu** [comment]
可以观察一下，submit_task 的内存应当不是无限增长的。在 ray 中每个 worker 都是独立进程，每增加一个 worker 都会有一些内存开销。在 secretflow 的 simulation 模式中为了保证大部分示例能正常运行，worker 数量（num_cpus）给了一个较大的默认值如下：

https://github.com/secretflow/secretflow/blob/22d8fd6486e818d2e93510c696a55a9fb26ed502/secretflow/device/driver.py#L429


如果机器内存比较有限，可以考虑在 sf.init 中指定较小的 num_cpus：
```
sf.init(['alice', 'bob', 'charlie'], address="local", num_cpus=16, log_to_driver=False)
```

**Comment by olivetree123** [comment]
我测试了 num_cpus = 8 和 num_cpus = 32 两种情况，总的内存占用并没有变化，一模一样。
有没有可能用的都是 Actor ？Actor应该都是独立的进程，是不是不受 num_cpus  参数的限制？

**Comment by Chrisdehe** [comment]
这个cpu 数量并不是真的占用的核数，而是ray 能够调度的tasks/actors 数量的上限。

**Comment by olivetree123** [comment]
我知道 ray 是通过限制 worker 数量来限制task的并发量，但它是怎么限制actor的并发量呢？我看官方文档说的是每个actor都有一个独立的进程，应该没有限制actor的进程数量，那它是怎么限制actor的并发数量的？
> [When a new actor is instantiated, a new worker is created](https://docs.ray.io/en/latest/ray-core/key-concepts.html#:~:text=When%20a%20new%20actor%20is%20instantiated%2C%20a%20new%20worker%20is%20created)

**Comment by olivetree123** [comment]
上面的问题希望能解惑一下，感谢。

言归正传
我们现发现 epoch 越大内存占用越多，不太清楚是什么原因，我们希望增加 epoch 不要影响内存的使用，这个能做到吗？

**Comment by olivetree123** [comment]
上面的问题有知道的大佬希望能回答下，感谢。

言归正传
我们现在发现的问题是，设置epoch=1000，一开始的时候内存是一直增长的，当内存用完的时候，内存不再增长，开始使用磁盘，/tmp/ray 目录一直在增大。这种情况正常吗？我们是希望epoch不要影响内存的占用

**Comment by zhouaihui** [comment]
从观察到的现象看，我们怀疑是ray 2.2的内存释放有bug。可以尝试的修复办法（请严格按照下列命令执行）
```bash
pip uninstall secretflow-ray
pip install ray==2.6.0
```

另外，如果对内存使用有介意，可以在sf.init时设置object_store_memory参数，示例：
```
# 限制ray object store内存上限为2GB
sf.init(['alice', 'bob', 'charlie'], address="local", log_to_driver=False, object_store_memory=2 * 1024 * 1024 * 1024)
```

我们会尽快升级secretflow-ray到2.6版本。
