### ISSUE TITLE
关于逻辑回归预测值

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/secretflow#885]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.0

### OS Platform and Distribution

Linux Ubuntu18.04

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
小白提问，大佬好

假如我有如下数据

age,weight,label
19,56,0
23,67,1
65,56,1

经过逻辑回归训练获得模型model,
然后执行预测

y=model.predict(testdata)

reveal后最终获得的预测结果有正数和负数，而且也不是之于0-1之间的概率数据

提问：
1 如何将预测结果和label对齐，也转化成对应的0，1结果 而不是一个概率数据结果，有api方法吗？
2 by the way  为什么预测会有负值呀？
```

### Reproduction code to reproduce the issue.

```shell
如上
```

**Comment by da-niao-dan** [comment]
如果你想将预测结果转化为0和1的结果，可以使用一个阈值来决定如何将概率转化为二进制标签。通常情况下，可以将大于等于0.5的概率转化为1，小于0.5的概率转化为0。你可以使用以下代码实现：
```
import numpy as np

threshold = 0.5
y_binary = np.where(y >= threshold, 1, 0)
```
其中，y是你预测得到的结果，y_binary是转化为二进制标签的结果，隐语中如果y是PYUObject需要将该代码用PYU device执行, reveal 出来后如上执行。



预测结果为负值的原因可能有以下几个方面：
特征的表示：可能你的特征表示存在问题，导致模型无法准确地预测。
样本不平衡：如果你的训练数据中标签为0的样本较多，而标签为1的样本较少，模型可能倾向于预测为0，从而导致预测结果中出现负值。
算法选择：逻辑回归本身是一个线性分类器，对于复杂的数据集可能不足以拟合出准确的模型。
你可以尝试调整特征表示、处理样本不平衡或者尝试其他更复杂的算法来提高预测的准确性。

**Comment by SZU-czw** [comment]
> 如果你想将预测结果转化为0和1的结果，可以使用一个阈值来决定如何将概率转化为二进制标签。通常情况下，可以将大于等于0.5的概率转化为1，小于0.5的概率转化为0。你可以使用以下代码实现：
> 
> ```
> import numpy as np
> 
> threshold = 0.5
> y_binary = np.where(y >= threshold, 1, 0)
> ```
> 
> 其中，y是你预测得到的结果，y_binary是转化为二进制标签的结果，隐语中如果y是PYUObject需要将该代码用PYU device执行, reveal 出来后如上执行。
> 
> 预测结果为负值的原因可能有以下几个方面： 特征的表示：可能你的特征表示存在问题，导致模型无法准确地预测。 样本不平衡：如果你的训练数据中标签为0的样本较多，而标签为1的样本较少，模型可能倾向于预测为0，从而导致预测结果中出现负值。 算法选择：逻辑回归本身是一个线性分类器，对于复杂的数据集可能不足以拟合出准确的模型。 你可以尝试调整特征表示、处理样本不平衡或者尝试其他更复杂的算法来提高预测的准确性。

谢谢大佬
