### ISSUE TITLE
数据分布在多方时，该如何使用

### ISSUE THREAD

**Issue by caozhantao** [secretflow/secretflow#89]
### Issue Type

Feature Request

### Source

source

### Secretflow Version

secretflow 0.6

### OS Platform and Distribution

centos 7.6

### Python version

3.8

### What happend and What you expected to happen.

```shell
目前所有的demo都是在执行测试一方的本地读取数据（本地有了多方数据，隐私计算就没有必要了），然而工业场景，数据应该是分布在不同物理机，这时候怎么取数据呢，能否给个demo或者解决方案呢?
```

### Reproduction code to reproduce the issue.

```shell
input_path = {alice: '.data/alice.csv', bob: '.data/bob.csv'}
output_path = {alice: '.data/alice_psi.csv', bob: '.data/bob_psi.csv'}
spu.psi_csv('uid', input_path, output_path)
```

**Comment by zhouaihui** [comment]
以`output_path = {alice: '.data/alice_psi.csv', bob: '.data/bob_psi.csv'}`为例，这行代码表示alice读取alice本地的data/alice_psi.csv文件，bob读取bob本地的data/bob_psi.csv。

所以只需要集群化启动secretflow集群，读取的就是参与方各自的文件了。
集群化参考[Cluster Mode](https://secretflow.readthedocs.io/en/latest/getting_started/deployment.html#cluster-mode)，以及相关issue #86 #50 可能会有帮助。
