### ISSUE TITLE
[heu_shamir_agg]联邦学习中的安全聚合方案设计及实现

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#892]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741) https://github.com/secretflow/secretflow/issues/879 特别任务的子任务。
> 
> 也欢迎开发者点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择你感兴趣的任务参与隐语社区共建，热烈欢迎社区开发者参与共建～

## 设计思路
by [ZacheryZ](https://github.com/ZacheryZ)
- 在聚合前调整本地梯度数据对称轴使其都变为正数，并扩大数倍使其变成整数。
- 使用PHE库中的paillier算法对本地梯度进行批量加密，每批数量与密钥长度挂钩——此步预计落在fl_base.py中。
- 重写aggregator中的加法算法，使其变为同态加——落地在aggregator中。
- 在fl_model中增加判断，如果全局权重为paillier对象，则调用解密算法再进一步分发至各个worker——此步预计落在fl_model中。

## 任务介绍
- 任务名称：【特别任务】联邦学习中的安全聚合方案设计以及实现
- 技术方向：Federated Learning
- 任务难度：挑战🌟🌟🌟
- 说明：本任务不参与🌟累计哈～

## 详细要求
安全聚合是解决联邦学习中梯度泄露问题的有效手段。然而，现有安全聚合方案仍可能存在“参与方掉线不容忍”、“聚合行为不可控”、“共谋推断不可抗”和“系统效能不实际”等问题。希望同学们能够在这个开放问题下，设计出安全，可行，巧妙的算法来解决联邦学习聚合中遇到的安全问题，效率问题，掉线问题等等。解决方法不限，可以使用 TEE，同态，多方安全计算等各种技术作为辅助。
- 安全性： 尽量少 reveal，设计出的聚合算法没有算法层面的安全问题
- 功能性：可以将实现落到 SecretFlow 的 aggregator 中，可以无缝替换其他的聚合方法。
- 收敛性：聚合结果需要保证正确性
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交要求：关联该 issue 并提交代码，代码提交细节请与蚂蚁导师进行沟通！！

## 能力要求
- 网空项目——安全聚合项目参与同学

## 操作说明
- 可参考 [SecretFlow 中的 aggregator](https://github.com/secretflow/secretflow/tree/main/secretflow/security/aggregation)

**Comment by Starfall-Mundane** [comment]
### 设计思路

- ### 密钥生成阶段

1. 编写并调试pybind和bazel代码，将NewHope密钥交换协议整合到heu模块中
2. 重写aggregator中的密钥交换模块，实现每个设备具备自己的公私钥，且每两个设备间共享一个秘密

- ### 秘密份额生成及分发阶段

1. 编写并调试pybind和bazel代码，将MuS多用秘密共享协议整合到heu模块中
2. 在aggregator中调用mus模块实现秘密份额和更新向量的生成与分发过程

- ### 梯度加密阶段

1. 在aggregator中，为每个设备生成双重掩码，并将双重掩码与模型参数相加
2. 在aggregator中，聚合设备收集至少t个设备的参数加密结果，并将所有在线设备的列表公布给所有参与方

- ### 秘密恢复及消除掩码影响阶段

1. 在aggregator中每个设备解密之前收到的秘密份额。根据在线状态，向聚合设备返回对应秘密份额
2. 聚合设备调用mus模块恢复对应掩码
3. 将聚合结果减去对应掩码。若设备为在线用户，则直接调用mus.Recover函数重构第二层掩码；若设备为离线用户，则先通过mus.Recover还原种子参数，再还原出共享密钥，最后用PRG函数生成对应第一层掩码

- ### 本地更新秘密份额阶段

1. 在aggregator中根据新秘密，更新每个设备分发出的所有秘密份额和接收到的秘密份额
2. 每个设备更新自己的公共参数并reveal给聚合设备
3. 在SecureAggregation中编写函数更新对应的公共参数

- ### 调整代码结构

1. 将上述基本函数功能整理成两个完整的类InitRoundSecureAggregation和ConsRoundSecureAggregation，并测试功能的正确性

**Comment by ZacheryZ** [comment]
ZacheryZ give it to me
