### ISSUE TITLE
[mask_heu_agg]联邦学习中的安全聚合方案设计及实现

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#895]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741) https://github.com/secretflow/secretflow/issues/879 特别任务的子任务。
> 
> 也欢迎开发者点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择你感兴趣的任务参与隐语社区共建，热烈欢迎社区开发者参与共建～

## 设计思路
by [liuzhihaozhengshuai](https://github.com/liuzhihaozhengshuai)
- 参与方在本地生成梯度后，在梯度的部分位置（离输出层最近的全连接层）添加mask，并对mask使用paillier同态加密
- 参与方将带有mask的梯度以及被加密的mask发送至服务器进行聚合
- 服务器对梯度使用加法进行聚合，对密文状态下的mask使用同态加法进行聚合，最后将聚合结果返回至参与方
- 参与方解密mask的聚合值，最终得到无噪声的聚合结果

## 任务介绍
- 任务名称：【特别任务】联邦学习中的安全聚合方案设计以及实现
- 技术方向：Federated Learning
- 任务难度：挑战🌟🌟🌟
- 说明：本任务不参与🌟累计哈～

## 详细要求
安全聚合是解决联邦学习中梯度泄露问题的有效手段。然而，现有安全聚合方案仍可能存在“参与方掉线不容忍”、“聚合行为不可控”、“共谋推断不可抗”和“系统效能不实际”等问题。希望同学们能够在这个开放问题下，设计出安全，可行，巧妙的算法来解决联邦学习聚合中遇到的安全问题，效率问题，掉线问题等等。解决方法不限，可以使用 TEE，同态，多方安全计算等各种技术作为辅助。
- 安全性： 尽量少 reveal，设计出的聚合算法没有算法层面的安全问题
- 功能性：可以将实现落到 SecretFlow 的 aggregator 中，可以无缝替换其他的聚合方法。
- 收敛性：聚合结果需要保证正确性
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交要求：关联该 issue 并提交代码，代码提交细节请与蚂蚁导师进行沟通！！

## 能力要求
- 网空项目——安全聚合项目参与同学

## 操作说明
- 可参考 [SecretFlow 中的 aggregator](https://github.com/secretflow/secretflow/tree/main/secretflow/security/aggregation)

**Comment by liuzhihaozhengshuai** [comment]
liuzhihaozhengshuai  Give it to me
