### ISSUE TITLE
多方计算每次都需要sf.shutdown()+sf.init()么

### ISSUE THREAD

**Issue by mingo0117** [secretflow/secretflow#91]
### Issue Type

Others

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
想问下多方计算运行不同的任务的时候，每次都要sf.shutdown()+sf.init()么？这样后一次会把前面其他正在运行中的task给kill掉吧？还是说这块只能串行呢？
我理解同一个计算集群只需要初始化一次吧，然后再给集群提交不同的task，但是试了下似乎不行，求教，谢谢
```

### Reproduction code to reproduce the issue.

```shell
如题
```

**Comment by zhouaihui** [comment]
在一个python解释器中，其实只需要sf.init一次，后台会启动计算集群，然后可以往该集群提交运行多个task，这个没有限制，shutdown其实会在进程退出时自动调用，所以可以不调用。

教程里的文档加上shutdown是为了避免有人在jupyter notebook打开之后，重复跑sf.init()导致报错。

**Comment by mingo0117** [comment]
明白了，谢谢
