### ISSUE TITLE
[RNN]在 SecretFlow 中实现水平联邦生成模型

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#913]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 设计思路

by [Mingbo-Lee](https://github.com/Mingbo-Lee)
- 基于[https://tensorflow.google.cn/tutorials/audio/music_generation?hl=zh-cn为例改写成隐语的联邦学习教程，体现隐语对](https://tensorflow.google.cn/tutorials/audio/music_generation?hl=zh-cn%E4%B8%BA%E4%BE%8B%E6%94%B9%E5%86%99%E6%88%90%E9%9A%90%E8%AF%AD%E7%9A%84%E8%81%94%E9%82%A6%E5%AD%A6%E4%B9%A0%E6%95%99%E7%A8%8B%EF%BC%8C%E4%BD%93%E7%8E%B0%E9%9A%90%E8%AF%AD%E5%AF%B9) keras example的兼容，充分展现隐语的易用性和兼容性
- 数据分割：按照参与方均匀分割
- 模型: RNN
- 数据集：[MAESTRO 数据集](https://magenta.tensorflow.org/datasets/maestro?hl=zh-cn&_gl=1*1e2j7lp*_ga*MTY2Nzg3NTIxNy4xNjk1NjI2Mjgz*_ga_W0YLR4190T*MTY5NTYyNjI4My4xLjEuMTY5NTYyNjI4My4wLjAuMA..)
- 联邦策略：充分对齐隐语现有API，只要隐语支持的，理论上都可以支持

## 任务介绍

- 任务名称：在 SecretFlow 中实现水平联邦生成模型
- 技术方向：联邦学习和人工智能
- 任务难度：进阶🌟🌟

## 详细要求

- 功能性：在 SecretFlow 中实现以下功能代码以及实现过程文档，功能包括：
  - 实现任意一种生成模型方法，如 GAN 等
  - 提供联邦数据集拆分的逻辑 
  - 提交 tutorial，example 代码，数据下载，拆分和预处理代码
- 收敛性/准确性：包含 simulator 跑出的实验数据并且证明收敛性/准确性，最好有与明文结果（PyTorch 或者 TensorFlow）的对比
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
  - 关联该 issue 并提交代码 https://github.com/secretflow/secretflow/tree/main/examples/app/h_aigc
  - 整理完整实现过程为文档 https://github.com/secretflow/secretflow/tree/main/docs/tutorial
 
## 能力要求
- 熟悉常见的生成模型如 GAN，VAE
- 熟悉 TensorFlow 或者 PyTorch

## 操作说明
- 操作指引：具体操作可参考[操作指引](https://github.com/secretflow/secretflow/tree/main/examples/app/v_recommendation/deep_fm)进行
- 参考内容：
  - [数据读取](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/CustomDataLoaderOnSL)
  - [数据预处理](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/data_preprocessing_with_data_frame)
  - [联邦模型开发教程](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/Federate_Learning_for_Image_Classification)

**Comment by Mingbo-Lee** [comment]
Mingbo-Lee Give it to me
