### ISSUE TITLE
cannot find npz files for honrizontal fl setting

### ISSUE THREAD

**Issue by ziyao002** [secretflow/secretflow#93]
### Issue Type

Feature Request

### Source

source

### Secretflow Version

0.6.13

### OS Platform and Distribution

centos 7

### Python version

3.8

### What happend and What you expected to happen.

```shell
Hi just tried to test fed_mnist.py, but found there are no npz files for this script. Can only find the one for the vertical setting. Really appreciate it if can share the corresponding files. Thanks.
```

### Reproduction code to reproduce the issue.

```shell
FileNotFoundError: [Errno 2] No such file or directory: '../../../../tests/datasets/mnist/horizontal/mnist_alice.npz'
```

**Comment by zhouaihui** [comment]
Try
```bash 
git lfs install 
git lfs pull
```

**Comment by ziyao002** [comment]
> Try
> 
> ```shell
> git lfs install 
> git lfs pull
> ```

Hi thanks for the reply, just tried to pull lfs files, seems still does not include the npz files for mnist in the horizontal setting.

**Comment by zhouaihui** [comment]
Hi, @ziyao002, sorry for your problem. The dataset files are missing for now. We are refactoring the dataset and lfs is going to be deprecated. 

You can try our tutorial [Federate Learning On Mnist](https://secretflow.readthedocs.io/en/latest/tutorial/Federate_Learning_for_Image_Classification.html) instead.

**Comment by zhouaihui** [comment]
Hi, @ziyao002, fed minist example is replaced with tutorial [Federated Learning On Minist](https://secretflow.readthedocs.io/en/latest/tutorial/Federate_Learning_for_Image_Classification.html) already. And SecretFlow now provides built-in datasets including mnist. Hope you have a good try.
