### ISSUE TITLE
对权重操作后返回，初始权重不变

### ISSUE THREAD

**Issue by BlingYYa** [secretflow/secretflow#937]
获取权重后对其进行操作得到新权重U，将U赋予初始权重，初始权重并没有发生改变。                            
U= method(sf.reveal(client_params)[i])
sf.reveal(client_params)[i] = U

**Comment by zhouaihui** [comment]
`sf.reveal(client_params)[i] = U`
这里产生的是一个临时变量，然后你把临时变量修改了，这句话结束之后临时变量的生命周期就结束了，自然不会生效，这是python语法决定的。

正确的写法是使用client_params所在的PYU调用函数进行修改，类似`pyu(lambda x : client_params =x)(x)`（仅示意，请结合你的代际代码修改）。

**Comment by BlingYYa** [comment]
按照给的方法进行尝试，代码改为 sf.PYU(lambda U : sf.reveal(client_params)[i] == U)(U)，其中U需要对client_params的每一层进行修改。然而还是不能修改初始权重，不知问题出在哪里？

**Comment by BlingYYa** [comment]
> `sf.reveal(client_params)[i] = U`这里产生的是一个临时变量，然后你把临时变量修改了，这句话结束之后临时变量的生命周期就结束了，自然不会生效，这是python语法决定的。
> 
> 正确的写法是使用client_params所在的PYU调用函数进行修改，类似（仅示意，请结合你的真实代码修改）。`pyu(lambda x : client_params = x)(x)`

按照给的方法进行尝试，代码改为 sf.PYU(lambda U : sf.reveal(client_params)[i] == U)(U)，其中U需要对client_params的每一层进行修改。然而还是不能修改初始权重，不知问题出在哪里？

**Comment by BlingYYa** [comment]
> `sf.reveal(client_params)[i] = U`这里产生的是一个临时变量，然后你把临时变量修改了，这句话结束之后临时变量的生命周期就结束了，自然不会生效，这是python语法决定的。
> 
> 正确的写法是使用client_params所在的PYU调用函数进行修改，类似（仅示意，请结合你的真实代码修改）。`pyu(lambda x : client_params = x)(x)`

按照给的方法进行尝试，代码改为 sf.PYU(lambda U : sf.reveal(client_params)[i] == U)(U)，我的想法是其中U需要对client_params的每一层进行修改，操作过程中权重维度也将改变。然而还是不能修改初始权重，不知问题出在哪里？

**Comment by zhouaihui** [comment]
你先正常写一个修改client_params的函数
```
def udpate_client_params(client_params, U):
    # 这里补充修改逻辑

```

然后构建你的pyu，让pyu执行这个修改函数。
```
pyu = sf.PYU('client_params所在的参与方')
pyu(update_client_params)(client_params, U)
```

**Comment by BlingYYa** [comment]
> 你先正常写一个修改client_params的函数
> 
> ```
> def udpate_client_params(client_params, U):
>     # 这里补充修改逻辑
> ```
> 
> 然后构建你的pyu，让pyu执行这个修改函数。
> 
> ```
> pyu = sf.PYU('client_params所在的参与方')
> pyu(update_client_params)(client_params, U)
> ```

感谢，我先试试
