### ISSUE TITLE
Bug of 3-channel pictures when using sf-sl torch backend

### ISSUE THREAD

**Issue by dongdongzhaoUP** [secretflow/secretflow#946]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.2.0.dev20230918

### OS Platform and Distribution

Centos7

### Python version

3.8.18

### What happend and What you expected to happen.

```shell
When using sf-sl torch backend to classfy 3-channel pictures(CIFAR-10), the model can run but accuracy is around 10% all time (10-class classification).
```

### Reproduction code to reproduce the issue.

```shell
I will comment with the .ipynb file
```

**Comment by dongdongzhaoUP** [comment]
[cifar10_sl_torch.zip](https://github.com/secretflow/secretflow/files/12868540/cifar10_sl_torch.zip)

**Comment by zhangxingmeng** [comment]
https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html
可以先用明文模型尝试下是否work，然后把这个模型拆分成slmodel就可以了。
