### ISSUE TITLE
secretflow-1.2.0.dev20231016安装错误

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#959]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.11.4

### What happend and What you expected to happen.

```shell
根据https://www.secretflow.org.cn/docs/quickstart/mfbgum8vi3ngs4y9页面中新增组件的教程。
我直接下载的DockerFile来创建镜像并启动了容器。
走到pip install dist/*.whl这一步之后，出现报错提示：
ERROR: Could not find a version that satisfies the requirement spu==0.6.0.dev20230922 (from secretflow) (from versions: 0.3.3b0, 0.3.3b2, 0.4.0b1, 0.4.1b0, 0.4.1b1, 0.5.0b0)
ERROR: No matching distribution found for spu==0.6.0.dev20230922


完整日志如下：
(base) [root@098325d0ff46 secretflow]# pip install dist/*.whl
INFO: pip is looking at multiple versions of secretflow to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 0.55.0 Requires-Python >=3.7,<3.11; 0.55.0rc1 Requires-Python >=3.7,<3.11; 0.55.1 Requires-Python >=3.7,<3.11; 0.55.2 Requires-Python >=3.7,<3.11; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement spu==0.6.0.dev20230922 (from secretflow) (from versions: 0.3.3b0, 0.3.3b2, 0.4.0b1, 0.4.1b0, 0.4.1b1, 0.5.0b0)
ERROR: No matching distribution found for spu==0.6.0.dev20230922
```

### Reproduction code to reproduce the issue.

```shell
ip install dist/*.whl
```

**Comment by Chrisdehe** [comment]
看起来是已配置的pip源没有找到这个版本的SPU，可以尝试换一个pip源。

**Comment by mtl802** [comment]
> 看起来是已配置的pip源没有找到这个版本的SPU，可以尝试换一个pip源。

我在https://pypi.org/project/spu/，下载的spu-0.6.0.dev20231013-cp38-cp38-manylinux2014_x86_64.whl
安装显示：
(base) [root@098325d0ff46 admin]# pip install spu-0.6.0.dev20231013-cp38-cp38-manylinux2014_x86_64.whl 
ERROR: spu-0.6.0.dev20231013-cp38-cp38-manylinux2014_x86_64.whl is not a supported wheel on this platform

**Comment by mtl802** [comment]
即使使用的阿里源也是同样的错误：
(base) [root@098325d0ff46 admin]# pip install spu==0.6.0 -i https://mirrors.aliyun.com/pypi/simple/
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement spu==0.6.0 (from versions: 0.3.3b0, 0.3.3b2, 0.4.0b1, 0.4.1b0, 0.4.1b1, 0.5.0b0)
ERROR: No matching distribution found for spu==0.6.0

**Comment by Chrisdehe** [comment]
请问你使用的是什么platform？

**Comment by mtl802** [comment]
(base) [root@098325d0ff46 docker]# python -c "import sys; print(sys.version)"
3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
(base) [root@098325d0ff46 docker]# python -c "import platform; print(platform.system())"
Linux

**Comment by 6fj** [comment]
hi @mtl802 

目前我们仅支持python3.8

**Comment by mtl802** [comment]
> hi  嗨 @mtl802
> 
> 目前我们仅支持python3.8


我尝试过使用python3.8，但是安装文件名为secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64.whl。
python3.11以下的好像都没办法运行

**Comment by 6fj** [comment]
hi @mtl802 

你在新建组件的时候需要确保环境是python 3.8。
由于你的环境是python 3.11因此打包出来的package是cp11.。由于secretflow有一部分dependency目前只在python3.8下测过，因此需要你使用python 3.8。

**Comment by Chrisdehe** [comment]
祝好～
