### ISSUE TITLE
SFXgboost目前只能train，不能evaluate/predict吗

### ISSUE THREAD

**Issue by BruceLHH** [secretflow/secretflow#96]

**Comment by zhangxingmeng** [comment]
可以的，用你构造好分fl_model执行fl_model.evaluate, fl_model.predict就可以了，具体可以看看API文档或者fl_model.py代码

**Comment by zhangxingmeng** [comment]
SFXgboost暂时只支持train，产出的model可以save下来，这个model可以用标准原生xgboost来进行加载预测，评估等。
后续版本会增加联邦评估和预测的能力

**Comment by BruceLHH** [comment]
好的，谢谢
