### ISSUE TITLE
【License问题】发现隐语底层依赖了一个GPL v3的库libgomp.so.1，有个问题想请教一下

### ISSUE THREAD

**Issue by Jerry-zhxf** [secretflow/secretflow#962]
发现隐语底层依赖了一个GPL v3的库libgomp.so.1，但隐私的License为Apache 2.0，那如果企业使用隐语的话，是需要遵循GPL v3的要求，进行开源吗？

**Comment by anakinxc** [comment]
附上 gomp 的声明 [header](https://github.com/gcc-mirror/gcc/blob/a4184c8a65a00eaf8a8d7f92fb8ad2f8621b39e2/libgomp/libgomp.h#L17)

**Comment by Jerry-zhxf** [comment]
@anakinxc 好的，感谢解答~
