### ISSUE TITLE
vdf.to_csv(targetFilePath, index=False)丢失数据

### ISSUE THREAD

**Issue by hy928302776** [secretflow/secretflow#972]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b2

### OS Platform and Distribution

Centos7 4c32g

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
vdf.to_csv(targetFilePath, index=False)丢失数据
```

### Reproduction code to reproduce the issue.

```shell
代码：
def read_sample_table(srcFilePath, targetFilePath):
    """
    读样本表
    """
    logger.info(f"====read_sample_table【读样本表】start====srcFilePath:{srcFilePath},--targetFilePath:{targetFilePath}")
    vdf = v_read_csv(srcFilePath)
    logger.info(f"读取样本表数据量{vdf.count()}")
    vdf.to_csv(targetFilePath, index=False)
    logger.info("====read_sample_table【读样本表】over====")


日志

Path:{sf-node-1-5: '/root/nueva/6/244584479547457536/sf-node-1-5/244584479547457536_node1697599531452_output1.csv'}
[2023-10-24 11:25:13][dvadmin.dev_centre.sflib.item.generate_union_table.read_sample_table():15] [None] [INFO] 读取样本表数据量ID2     40001
x_10    40001
x_11    40001
x_12    40001
x_13    40001
x_14    40001
x_15    40001
x_16    40001
x_17    40001
x_18    40001
x_19    40001

但是输出文件只有一万多条
```

**Comment by hy928302776** [comment]
<img width="1216" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/40daa1a9-0597-49ad-a50e-ec671e674be1">
vim /root/nueva/6/244584479547457536/sf-node-1-5/244584479547457536_node1697599531452_output1.csv

<img width="1199" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/aa9c680d-b0a1-4c91-82cf-33eeb5cdba8b">

**Comment by zhangxingmeng** [comment]
感觉应该是read_csv默认做了psi，所以导致保存的只是求交后对齐的数据，可以看看数据确认下
