### ISSUE TITLE
关于自定义组件问题

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#975]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.8.0

### What happend and What you expected to happen.

```shell
每次测试自定义组件都需要打包镜像、注册镜像的流程。有没有一种方法可以快速的测试组件，减少等待时间
```

### Reproduction code to reproduce the issue.

```shell
./register_app_image/register_app_image.sh -u ${USER} -m center -n secretflow-image -i docker.io/secretflow/sf-dev-anolis8:test_compare
```

**Comment by 6fj** [comment]
Hi @mtl802 

我们建议你可以先写组件的单测，比如：https://github.com/secretflow/secretflow/tree/main/tests/component

我们使用pytest来测试代码，测试相关事项请查看：https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#test

感谢！

**Comment by mtl802** [comment]
@6fj 你好
请问我新加入的节点在是在同一个宿主机内创建的容器，节点的通信地址设置为宿主机公网IP:容器端口。
在合作节点添加里面显示的是可用状态。
但是在执行组件求交的时候就会报错，显示alice无法ping通新加的节点。
![image](https://github.com/secretflow/secretflow/assets/20579710/29191a89-6269-4d30-97de-a5c445e21c95)
请问怎么解决

**Comment by 6fj** [comment]
@UniqueMarvin 能帮忙看一下这个问题吗，感谢。

**Comment by mtl802** [comment]
> @UniqueMarvin 能帮忙看一下这个问题吗，感谢。

不好意思，这个issue我应该放到kusic里面的，我已经发过去了，麻烦了

**Comment by UniqueMarvin** [comment]
> > @UniqueMarvin 能帮忙看一下这个问题吗，感谢。
> 
> 不好意思，这个issue我应该放到kusic里面的，我已经发过去了，麻烦了

在这个issue中回复了 https://github.com/secretflow/secretflow/issues/975#issuecomment-1780469439
