### ISSUE TITLE
CentOS 7.9安装 MVP 遇到使用问题

### ISSUE THREAD

**Issue by mengxianyao** [secretflow/secretflow#979]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretpad-v0.2.0b0-6-g4eae988-20230911104908-4eae98.tar

### OS Platform and Distribution

CentOS Linux release 7.9.2009 (Core)

### Python version

 2.7.5

### What happend and What you expected to happen.

```shell
2023-10-25 16:42:55 INFO the jobId=oqfj, taskId=oqfj-bllryejo-node-3 start ...
2023-10-25 16:43:02 INFO the jobId=oqfj, taskId=oqfj-bllryejo-node-3 failed: party alice failed 

RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

### Reproduction code to reproduce the issue.

```shell
期望能提供基于 CentOS 的部署文档，目前只有 MacOS 和 Windows 的。
```

**Comment by wangyixianggogo** [comment]
hi
1、CentOS7、CentOS8我们是支持的。文档在[这](https://www.secretflow.org.cn/docs/quickstart/zgnd8oqo5chsqhzm#bjWCV)里
2、看报错是不支持的os或cpu，你是使用的M1芯片或M2芯片吗？

**Comment by mengxianyao** [comment]
CentOS Linux release 8.5.2111
Python 3.8.8

这个确定可以走通。
