### ISSUE TITLE
新增组件的时候，在Kuscia中注册自定义算法镜像，如何修改脚本将算法导入容器的操作变成并行操作

### ISSUE THREAD

**Issue by Handikang** [secretflow/secretflow#988]
### Issue Type

Others

### Source

source

### Secretflow Version

1.2.0

### OS Platform and Distribution

 ubuntu 20.04

### Python version

3.8.18

### What happend and What you expected to happen.

```shell
我自行修改了文件register_app_image下register_app_image.sh的内容，因为现实需要，未来可能会增加节点，就希望能实现将算法注册到容器中的操作实现并行化从而大幅度节省流程开销，下面是个人我认为可能需要修改的地方，我还是请教一下你们有办法吗，因为我尝试过修改这些命令都不行
```

### Reproduction code to reproduce the issue.

```shell
echo "=> => import app image into ${alice_container_name} container"
  docker exec -it "${alice_container_name}" ctr -a=${CTR_ROOT}/containerd/run/containerd.sock -n=k8s.io images import "${image_tar}" || exit 1

  echo "=> => import app image into ${bob_container_name} container"
  docker exec -it "${bob_container_name}" ctr -a=${CTR_ROOT}/containerd/run/containerd.sock -n=k8s.io images import "${image_tar}" || exit 1
```

**Comment by gshilei** [comment]
`
  echo "=> => import app image into ${alice_container_name} container"
  echo "$(docker exec ${alice_container_name} ctr -a=${CTR_ROOT}/containerd/run/containerd.sock -n=k8s.io images import ${image_tar})" &

  echo "=> => import app image into ${bob_container_name} container"
  echo "$(docker exec -it ${bob_container_name} ctr -a=${CTR_ROOT}/containerd/run/containerd.sock -n=k8s.io images import ${image_tar})"

`

**Comment by gshilei** [comment]
HI @Handikang ,

上面解决方案是否有解决你的问题呢 ？下面是跟这个Issue有关的社区OSCP任务，如果感兴趣的话，欢迎认领～

https://github.com/secretflow/kuscia/issues/135

**Comment by Handikang** [comment]
@gshilei 效率上有提升，我试过两个容器并行可能效果会提升50%，但是四个容器并行的时候效率提升就不明显了

**Comment by gshilei** [comment]
> @gshilei 效率上有提升，我试过两个容器并行可能效果会提升50%，但是四个容器并行的时候效率提升就不明显了

是的，会有临界点的。

上面是一个社区任务，跟这个Issue比较相关，如果感兴趣的话，非常欢迎你一同参与隐语Kuscia的可持续建设。
https://github.com/secretflow/kuscia/issues/135
