### ISSUE TITLE
在 SecretFlow 中实现经典联邦策略 FedGen

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#993]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP)](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- **任务名称**：在 SecretFlow 中实现经典联邦策略 FedGen
- **技术方向**：FL/strategy
- **任务难度**：进阶🌟🌟
- **任务期望时间**：4-5周

## 详细要求
- 安全性：尽量少 reveal
- 功能性：在 SecretFlow 中实现论文[Data-Free Knowledge Distillation for Heterogeneous Federated Learning](https://arxiv.org/abs/2105.10056)的算法。
- 正确性：至少复现论文中的一个实验验证实现的正确性
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 框架后端：实现 PyTorch 版本。若在完成 PyTorch 版本实现的基础上同步进行 TensorFlow 版本实现将额外累积一🌟。
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/backend/torch/strategy/

## 能力要求
- 了解基本 git 操作
- 熟悉 深度学习、联邦学习
- 对 SecretFlow 有一定了解

## 操作说明
- 范例：[PyTorch 后端](https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/backend/torch/strategy/fed_prox.py) 和 [TensorFlow 后端](https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/fl/backend/torch/strategy/fed_prox.py)

**Comment by OkayYang** [comment]
OkayYang Give it to me

**Comment by Yeekin-GYJ** [comment]
> OkayYang Give it to me

欢迎认领任务～ 该任务完成过程中如遇到问题可以在 issue 上直接反馈，也可以添加小助手微信：SecretFlow04 进行沟通 加入 OSCP 专属群聊哈

**Comment by OkayYang** [comment]
### 描述

你好，

我在该论文提供的 `FedGen` 源码中遇到了一个问题，论文中表示服务端训练更新生成模型 `w` 后，会将其广播给选中用户，但是我在作者提供的代码中并没找到相关行为。

我注意到 `send_parameters` 方法会将全局模型参数广播给用户，但没有广播生成模型参数。

### 代码片段

以下是服务器上训练生成模型的相关代码片段：

```python
    def train(self, args):
        #### pretraining
        for glob_iter in range(self.num_glob_iters):
            print("\n\n-------------Round number: ",glob_iter, " -------------\n\n")
            self.selected_users, self.user_idxs=self.select_users(glob_iter, self.num_users, return_idx=True)
            if not self.local:
                self.send_parameters(mode=self.mode)# broadcast averaged prediction model
            self.evaluate()
            chosen_verbose_user = np.random.randint(0, len(self.users))
            self.timestamp = time.time() # log user-training start time
            for user_id, user in zip(self.user_idxs, self.selected_users): # allow selected users to train
                verbose= user_id == chosen_verbose_user                # perform regularization using generated samples after the first communication round
                user.train(
                    glob_iter,
                    personalized=self.personalized,
                    early_stop=self.early_stop,
                    verbose=verbose and glob_iter > 0,
                    regularization= glob_iter > 0 )
            curr_timestamp = time.time() # log  user-training end time
            train_time = (curr_timestamp - self.timestamp) / len(self.selected_users)
            self.metrics['user_train_time'].append(train_time)
            if self.personalized:
                self.evaluate_personalized_model()

            self.timestamp = time.time() # log server-agg start time
            self.train_generator(
                self.batch_size,
                epoches=self.ensemble_epochs // self.n_teacher_iters,
                latent_layer_idx=self.latent_layer_idx,
                verbose=True
            )
            self.aggregate_parameters()
            curr_timestamp=time.time()  # log  server-agg end time
            agg_time = curr_timestamp - self.timestamp
            self.metrics['server_agg_time'].append(agg_time)
            if glob_iter  > 0 and glob_iter % 20 == 0 and self.latent_layer_idx == 0:
                self.visualize_images(self.generative_model, glob_iter, repeats=10)

        self.save_results(args)
        self.save_model()
```

**Comment by OkayYang** [comment]
这个算法需要更改FLModel的源码，是否允许？因为该算法需要server拥有一个生成器模型，利用生成器模型来做知识蒸馏。

**Comment by zhaocaibei123** [comment]
> 这个算法需要更改FLModel的源码，是否允许？因为该算法需要server拥有一个生成器模型，利用生成器模型来做知识蒸馏。

可以，放到 examples 目录就好
