### ISSUE TITLE
在 SecretFlow 中实现垂直联邦后门攻击 Villain

### ISSUE THREAD

**Issue by Candicepan** [secretflow/secretflow#997]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- **任务名称**：在 SecretFlow 中实现垂直联邦后门攻击 Villain
- **技术方向**：FL/security
- **任务难度**：进阶🌟🌟
- **任务期望时间**：4-5周

## 详细要求
- 安全性：尽量少 reveal
- 功能性：在 SecretFlow 中实现论文[Villain: Backdoor Attacks Against Vertical Split Learning](https://www.usenix.org/conference/usenixsecurity23/presentation/bai)的攻击算法。
- 正确性：复现在数据集 Bank Marketing，Give-Me-Some-Credit 上的实验
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 框架后端：实现 PyTorch 版本。若在完成 PyTorch 版本实现的基础上同步进行 TensorFlow 版本实现将额外累积一颗🌟。
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/sl/attack/torch/

## 能力要求
- 了解基本 git 操作
- 熟悉 深度学习、联邦学习
- 对 SecretFlow 有一定了解

## 操作说明
- 范例：https://github.com/secretflow/secretflow/blob/main/secretflow/ml/nn/sl/attack/torch/label_inferece_attack.py

**Comment by shnnosuke34725** [comment]
shnnosuke34725 Give it to me

**Comment by Yeekin-GYJ** [comment]
> shnnosuke34725 Give it to me

欢迎认领任务呀，该任务完成过程中有什么问题都可以在 issue 上直接反馈，也可以添加小助手微信：SecretFlow04 进行沟通 加入 OSCP 专属群聊哈～ 期待你的PR！

**Comment by YuanShunJie1** [comment]
Hello，请问你们对这个攻击方案Villain复现成功了吗？
